import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'archive-annex',
  overview: [
    b('Protecting data is not only about stopping attackers. It is also about getting data back after an accident, a deletion or a failure, and keeping it for as long as policy says. This building covers the AWS tools for that: {{term:aws-backup|AWS Backup}} for centralised backups, S3 versioning and replication for object data, and Amazon Macie for finding out what kind of data you are keeping.',
      ['backup-what-is', 's3-versioning', 's3-replication', 'macie'],
      ['backup-what-is|AWS Backup is a fully-managed service that makes it easy to centralize and automate data protection across AWS services, in the cloud, and on premises.',
       's3-versioning|You can use the S3 Versioning feature to preserve, retrieve, and restore every version of every object stored in your buckets.',
       's3-replication|The destination buckets can be in different AWS Regions or within the same Region as the source bucket.',
       'macie|Amazon Macie is a data security service that discovers sensitive data by using machine learning and pattern matching']),
  ],
  bullets: [
    {
      id: '1.3-K2',
      concepts: [
        b('Recovery needs a copy that survives the failure. S3 Versioning preserves, retrieves and restores every version of every object, so you can recover from unintended user actions and application failures, including accidental deletion or overwrite.',
          's3-versioning',
          ['You can use the S3 Versioning feature to preserve, retrieve, and restore every version of every object stored in your buckets.',
           'With versioning you can recover more easily from both unintended user actions and application failures.']),
        b('AWS Backup lets you automate and consolidate backup tasks that were previously done service by service, removing the need for custom scripts and manual processes. AWS notes that it does not govern backups you take outside AWS Backup.',
          'backup-what-is',
          ['It allows you to automate and consolidate backup tasks that were previously performed service-by-service, and removes the need to create custom scripts and manual processes.',
           'AWS Backup does not govern backups you take in your AWS environment outside of AWS Backup.']),
      ],
      services: ['AWS Backup', 'Amazon S3'],
      design: [
        b('Use versioning on important buckets to guard against deletes and overwrites, and AWS Backup for services such as DynamoDB tables and EFS file systems that are covered by a backup plan.',
          ['s3-versioning', 'backup-plans'],
          ['s3-versioning|Versioning-enabled buckets can help you recover objects from accidental deletion or overwrite.',
           'backup-plans|In AWS Backup, a backup plan is a policy expression that defines when and how you want to back up your AWS resources, such as Amazon DynamoDB tables or Amazon Elastic File System (Amazon EFS) file systems.']),
      ],
    },
    {
      id: '1.3-K3',
      concepts: [
        b('Retention is how long data is kept. A backup plan sets the schedule and retention, and AWS Backup manages the lifecycle of the backups according to your retention settings. Resources assigned to the plan are backed up and retained automatically.',
          'backup-plans',
          ['You can assign resources to backup plans, and AWS Backup automatically backs up and retains backups for those resources according to the backup plan.',
           "AWS Backup also seamlessly manages your backup plan's lifecycle based on your retention settings"]),
        b('Classification is knowing what the data is. Amazon Macie automates discovery, logging and reporting of sensitive data in your S3 data estate, either by automated sensitive data discovery or by sensitive data discovery jobs.',
          'macie-discovery',
          ['With Amazon Macie, you can automate discovery, logging, and reporting of sensitive data in your Amazon Simple Storage Service (Amazon S3) data estate.',
           'by configuring Macie to perform automated sensitive data discovery, and by creating and running sensitive data discovery jobs.']),
        b('To hold data immutably for a required period, S3 Object Lock and AWS Backup Vault Lock use a write-once-read-many model; backups in a locked vault cannot be deleted until their lifecycle completes.',
          ['s3-object-lock', 'backup-vault-lock'],
          ['s3-object-lock|Object Lock uses a write-once-read-many (WORM) model to store objects.',
           'backup-vault-lock|Because backups in a locked vault cannot be deleted until their lifecycle completes, ensure your retention settings are configured appropriately to avoid unintended storage costs.']),
      ],
      services: ['AWS Backup', 'Amazon Macie', 'Amazon S3'],
      design: [
        b('Classify first, then protect accordingly: use Macie to find sensitive data in S3, then apply tighter access, longer retention or locking to the buckets that hold it.',
          'macie', ['If Macie detects sensitive data in an S3 object, Macie generates a finding to notify you of the sensitive data that it found.']),
      ],
    },
    {
      id: '1.3-S5',
      concepts: [
        b('S3 replication copies objects to destination buckets in the same or a different AWS Region, and to buckets owned by the same or a different account. Live replication copies new and updated objects as they are written; versioning is a prerequisite for replication.',
          's3-replication',
          ['The destination buckets can be in different AWS Regions or within the same Region as the source bucket.',
           'Live replication – To automatically replicate new and updated objects as they are written to the source bucket, use live replication.',
           'Buckets that are configured for object replication can be owned by the same AWS account or by different accounts.']),
        b('AWS Backup can copy backups across Regions on demand or as part of a plan, which AWS says is valuable for business continuity or compliance requirements to store backups a minimum distance away from production data. It can also manage backups across all accounts in an AWS Organizations structure.',
          'backup-what-is',
          ['Using AWS Backup, you can copy backups to multiple different AWS Regions on demand or automatically as part of a scheduled backup plan.',
           'Cross-Region backup is particularly valuable if you have business continuity or compliance requirements to store backups a minimum distance away from your production data.',
           'You can use AWS Backup to manage your backups across all AWS accounts inside your AWS Organizations structure.']),
      ],
      services: ['AWS Backup', 'Amazon S3'],
      design: [
        b('Backups protect against deletion and corruption; replication protects against the loss of a Region or an account. Combine them: versioning and Backup for point-in-time recovery, plus replication or cross-Region backup copies for geographic separation.',
          ['backup-what-is', 's3-replication'],
          ['backup-what-is|Cross-Region backup is particularly valuable if you have business continuity or compliance requirements to store backups a minimum distance away from your production data.',
           's3-replication|The destination buckets can be in different AWS Regions or within the same Region as the source bucket.']),
      ],
    },
  ],
  cues: [
    cue('recover an accidentally deleted or overwritten object', 'S3 Versioning',
      b('Versioning-enabled buckets can help you recover objects from accidental deletion or overwrite.', 's3-versioning',
        ['Versioning-enabled buckets can help you recover objects from accidental deletion or overwrite.'])),
    cue('centralize and automate backups across AWS services and accounts', 'AWS Backup',
      b('AWS Backup centralises and automates data protection across AWS services, and can manage backups across an organization.', 'backup-what-is',
        ['AWS Backup is a fully-managed service that makes it easy to centralize and automate data protection across AWS services, in the cloud, and on premises.'])),
    cue('copy data to another Region for disaster recovery or compliance', 'S3 Cross-Region Replication or an AWS Backup cross-Region copy',
      b('S3 replication destinations can be in different Regions, and AWS Backup can copy backups across Regions.', 's3-replication',
        ['The destination buckets can be in different AWS Regions or within the same Region as the source bucket.'])),
    cue('discover where personally identifiable or sensitive data is stored in S3', 'Amazon Macie',
      b('Macie automates discovery, logging and reporting of sensitive data in your S3 data estate.', 'macie-discovery',
        ['With Amazon Macie, you can automate discovery, logging, and reporting of sensitive data in your Amazon Simple Storage Service (Amazon S3) data estate.'])),
    cue('objects must not be deleted or overwritten for a fixed retention period (WORM)', 'S3 Object Lock',
      b('S3 Object Lock can prevent objects from being deleted or overwritten for a fixed or variable amount of time, or indefinitely.', 's3-object-lock',
        ['S3 Object Lock can help prevent Amazon S3 objects from being deleted or overwritten for a fixed or variable amount of time, or indefinitely.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Backup',
      aws: 'AWS Backup',
      mapping: b('Both are centralised backup services. The Learn storage page lists Azure Backup, which backs up and recovers files, databases, disks and virtual machines, against AWS Backup.',
        ['learn-storage', 'backup-what-is'],
        ['learn-storage|This option is used to back up and recover files, databases, disks, and virtual machines.',
         'backup-what-is|AWS Backup is a fully-managed service that makes it easy to centralize and automate data protection across AWS services, in the cloud, and on premises.']),
      breaks: b('A backup service is not a replication or disaster-recovery service. AWS Backup can copy backups across Regions and accounts, and S3 replication and versioning are separate features; read each question for which of these it needs.',
        ['backup-what-is', 's3-replication', 'learn-storage'],
        ['backup-what-is|Using AWS Backup, you can copy backups to multiple different AWS Regions on demand or automatically as part of a scheduled backup plan.',
         's3-replication|There are two types of replication: live replication and on-demand replication.',
         'learn-storage|Backup Backup'],
        { allow: ['two'] }),
    },
  ],
};

export default notes;
