import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'compliance-registry',
  overview: [
    b('Compliance questions ask you to prove or enforce that data and resources meet a rule. AWS gives you evidence (reports and agreements in AWS Artifact), continuous checking (AWS Config rules and conformance packs), data-level governance (Lake Formation, Macie) and protective settings (Object Lock, Block Public Access, lifecycle rules). The Lookout Tower primer introduced CloudTrail and Config; this building uses them for compliance.',
      ['artifact', 'config-rules', 'lake-formation'],
      ['artifact|AWS Artifact provides on-demand downloads of AWS security and compliance documents.',
       'config-rules|Use AWS Config to evaluate the configuration settings of your AWS resources.',
       'lake-formation|AWS Lake Formation helps you centrally govern, secure, and globally share data for analytics and machine learning.']),
  ],
  bullets: [
    {
      id: '1.3-K1',
      concepts: [
        b('Governing access to data means deciding who sees what, centrally. AWS Lake Formation helps you centrally govern, secure and share data for analytics and machine learning, with its own permissions model that augments IAM and fine-grained controls at the column, row and cell level.',
          'lake-formation',
          ['AWS Lake Formation helps you centrally govern, secure, and globally share data for analytics and machine learning.',
           'Lake Formation provides its own permissions model that augments the IAM permissions model.',
           'Lake Formation permissions are enforced using granular controls at the column, row, and cell-levels']),
        b('For S3, access is governed by IAM and bucket policies, and S3 Block Public Access settings override policies and permissions that would otherwise allow public access. New buckets, access points and objects do not allow public access by default.',
          's3-block-public-access',
          ["By default, new buckets, access points, and objects don't allow public access.",
           'S3 Block Public Access settings override these policies and permissions so that you can limit public access to these resources.']),
      ],
      services: ['AWS Lake Formation', 'Amazon S3', 'Amazon Macie'],
      design: [
        b('Data lake governed centrally by column, row or cell: Lake Formation. Object storage that should not be public: S3 Block Public Access, with Macie generating a finding if a bucket becomes publicly accessible.',
          ['lake-formation', 's3-block-public-access', 'macie'],
          ['lake-formation|With Lake Formation, you can manage fine-grained access control for your data lake data on Amazon Simple Storage Service (Amazon S3) and its metadata in AWS Glue Data Catalog.',
           's3-block-public-access|S3 Block Public Access settings override these policies and permissions so that you can limit public access to these resources.',
           'macie|such as a bucket that becomes publicly accessible']),
      ],
    },
    {
      id: '1.3-S1',
      concepts: [
        b('AWS Artifact provides on-demand downloads of AWS security and compliance documents and certifications from accreditation bodies, and lets you review, accept and track the status of your agreements with AWS for one or many accounts.',
          'artifact',
          ['AWS Artifact provides on-demand downloads of AWS security and compliance documents.',
           'AWS Artifact also provides downloads of certifications from accreditation bodies that validate the implementation and operating effectiveness of AWS security controls.',
           'you can use AWS Artifact to review, accept, and track the status of your agreements with AWS for your AWS account and for multiple AWS accounts in your organization.']),
        b('AWS Config evaluates the configuration of your resources against {{term:config-rule|Config rules}}, and a conformance pack is a collection of Config rules and remediation actions that can be deployed as a single entity in an account and Region or across an organization.',
          ['config-rules', 'config-conformance-packs'],
          ['config-rules|You do this by creating AWS Config rules, which represent your ideal configuration settings.',
           'config-conformance-packs|A conformance pack is a collection of AWS Config rules and remediation actions that can be easily deployed as a single entity in an account and a Region or across an organization in AWS Organizations.']),
        b('CloudTrail provides the audit trail of API activity that compliance reviews ask for: actions by users, roles and services are recorded as events.',
          'cloudtrail-what-is', ['Actions taken by a user, role, or an AWS service are recorded as events in CloudTrail.']),
      ],
      services: ['AWS Artifact', 'AWS Config', 'Amazon Macie'],
      design: [
        b('To show an auditor AWS\'s own compliance status, download the reports from AWS Artifact. To show your own resources stay compliant, use Config rules or conformance packs and keep CloudTrail enabled for the audit trail.',
          ['artifact', 'config-conformance-packs', 'cloudtrail-what-is'],
          ['artifact|AWS Artifact provides on-demand downloads of AWS security and compliance documents.',
           'config-conformance-packs|A conformance pack is a collection of AWS Config rules and remediation actions',
           'cloudtrail-what-is|Actions taken by a user, role, or an AWS service are recorded as events in CloudTrail.']),
      ],
    },
    {
      id: '1.3-S6',
      concepts: [
        b('Access policy: IAM and bucket policies decide who can touch objects, and Block Public Access limits public exposure. Lifecycle: an S3 Lifecycle configuration is a set of rules that define actions S3 applies to a group of objects, such as transitioning them to another storage class or deleting expired objects. Protection: S3 Object Lock uses a write-once-read-many model to help meet regulatory requirements, and it works only in buckets that have S3 Versioning enabled.',
          ['s3-lifecycle', 's3-object-lock', 's3-block-public-access'],
          ['s3-lifecycle|An S3 Lifecycle configuration is a set of rules that define actions that Amazon S3 applies to a group of objects.',
           's3-lifecycle|Transition actions – These actions define when objects transition to another storage class.',
           's3-object-lock|You can use Object Lock to help meet regulatory requirements that require WORM storage, or to add another layer of protection against object changes or deletion.',
           's3-object-lock|Object Lock works only in buckets that have S3 Versioning enabled.']),
        b('Object Lock offers two ways to manage object retention: retention periods and legal holds. Its retention modes differ: in compliance mode no user, including the root user, can overwrite or delete a protected object version, whereas in governance mode users with special permissions can. AWS Backup Vault Lock also has governance and compliance modes, for backup vaults.',
          ['s3-object-lock', 'backup-vault-lock'],
          ['s3-object-lock|Object Lock provides two ways to manage object retention: retention periods and legal holds.',
           's3-object-lock|In compliance mode, a protected object version can\'t be overwritten or deleted by any user, including the root user in your AWS account.',
           's3-object-lock|In governance mode, users can\'t overwrite or delete an object version or alter its lock settings unless they have special permissions.',
           'backup-vault-lock|When you create a vault lock, you have a choice of two modes: Governance mode or Compliance mode.'],
          { allow: ['two'] }),
      ],
      services: ['Amazon S3', 'AWS Backup', 'IAM'],
      design: [
        b('Regulated data that must not be altered: Object Lock (WORM) on the bucket. Data that should move to lower-cost storage or expire: a lifecycle configuration (covered in depth at the Cold Cellar). Data that should not be exposed publicly: Block Public Access.',
          ['s3-object-lock', 's3-lifecycle', 's3-block-public-access'],
          ['s3-object-lock|Object Lock uses a write-once-read-many (WORM) model to store objects.',
           's3-lifecycle|S3 Lifecycle helps you store objects cost effectively throughout their lifecycle by transitioning them to lower-cost storage classes, or, deleting expired objects on your behalf.',
           's3-block-public-access|By default, new buckets, access points, and objects don\'t allow public access.']),
      ],
    },
  ],
  cues: [
    cue('download AWS compliance reports / audit documents', 'AWS Artifact',
      b('AWS Artifact provides on-demand downloads of AWS security and compliance documents.', 'artifact', ['AWS Artifact provides on-demand downloads of AWS security and compliance documents.'])),
    cue('continuously evaluate resource configuration against rules', 'AWS Config rules / conformance packs',
      b('AWS Config evaluates configuration settings of resources against rules.', 'config-rules', ['Use AWS Config to evaluate the configuration settings of your AWS resources.'])),
    cue('WORM / data must not be modified or deleted for a retention period', 'S3 Object Lock (versioning required; compliance mode is the one that holds against the root user)',
      b('Object Lock uses a write-once-read-many model, can help meet regulatory requirements that require WORM storage, and works only in buckets that have S3 Versioning enabled.', 's3-object-lock',
        ['You can use Object Lock to help meet regulatory requirements that require WORM storage',
         'Object Lock works only in buckets that have S3 Versioning enabled.'])),
    cue('prevent public access to buckets', 'S3 Block Public Access',
      b('S3 Block Public Access settings override bucket policies and permissions that would allow public access.', 's3-block-public-access',
        ['S3 Block Public Access settings override these policies and permissions so that you can limit public access to these resources.'])),
    cue('fine-grained (column / row) access control over a data lake', 'AWS Lake Formation',
      b('Lake Formation enforces granular controls at the column, row and cell levels.', 'lake-formation',
        ['Lake Formation permissions are enforced using granular controls at the column, row, and cell-levels'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Microsoft Service Trust Portal',
      aws: 'AWS Artifact',
      mapping: b('Both give customers access to audit reports, compliance guides and trust documents from the cloud provider.',
        ['learn-hub', 'artifact'],
        ['learn-hub|Use these services to access audit reports, compliance guides, and trust documents from across cloud services.',
         'artifact|AWS Artifact provides on-demand downloads of AWS security and compliance documents.']),
      breaks: b('AWS Artifact also lets you review, accept and track the status of your agreements with AWS for one account or many accounts in your organization. The Learn row describes the pair only as services to access audit reports, compliance guides and trust documents; it does not mention agreements.',
        ['artifact', 'learn-hub'],
        ['artifact|you can use AWS Artifact to review, accept, and track the status of your agreements with AWS for your AWS account and for multiple AWS accounts in your organization.',
         'learn-hub|Use these services to access audit reports, compliance guides, and trust documents from across cloud services.']),
    },
    {
      concept: 'Azure Policy',
      aws: 'AWS Config',
      mapping: b('The Learn comparison pairs AWS Config with Azure Policy and Change Analysis: governance for consistency and compliance of resources.',
        ['learn-hub', 'config-rules'],
        ['learn-hub|Azure Policy helps you implement governance for resource consistency, regulatory compliance, security, cost, and management.',
         'config-rules|Use AWS Config to evaluate the configuration settings of your AWS resources.']),
      breaks: b('Learn describes Azure Policy as helping you implement governance, with bulk remediation for existing resources and automatic remediation for new resources, and says you typically use AWS Config to monitor for configuration changes or to identify and remediate noncompliant resources. AWS Config records and evaluates configuration against rules; the AWS tool that sets a ceiling on permissions across accounts is a different service, service control policies in AWS Organizations.',
        ['config-rules', 'orgs-scps', 'learn-hub'],
        ['config-rules|You do this by creating AWS Config rules, which represent your ideal configuration settings.',
         'orgs-scps|SCPs offer central control over the maximum available permissions for the IAM users and IAM roles in your organization.',
         'learn-hub|Use Azure Policy for bulk remediation for existing resources and automatic remediation for new resources.',
         'learn-hub|You typically use AWS Config to monitor for configuration changes or to identify and remediate noncompliant resources.']),
    },
  ],
};

export default notes;
