import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'customs-house',
  overview: [
    b('Traffic crosses the VPC boundary in three ways, and each has a secure option: calls to AWS service {{term:service-endpoint|service endpoints}} (which can be made private with VPC endpoints), connections from your on-premises network (Site-to-Site VPN, Direct Connect), and remote users (Client VPN). This building is about choosing the one that keeps the traffic where you want it.',
      ['service-endpoints', 'vpce-gateway', 's2s-vpn', 'client-vpn'],
      ['service-endpoints|An endpoint is the URL of the entry point for an AWS web service.',
       'vpce-gateway|Gateway VPC endpoints provide reliable connectivity to Amazon S3 and DynamoDB without requiring an internet gateway or a NAT device for your VPC.',
       's2s-vpn|You can enable access to your remote devices from your VPC by creating an AWS Site-to-Site VPN (Site-to-Site VPN) connection',
       'client-vpn|AWS Client VPN is a managed client-based VPN service that enables you to securely access your AWS resources and resources in your on-premises network.'],
      { allow: ['three'] }),
  ],
  bullets: [
    {
      id: '1.2-K2',
      concepts: [
        b('An AWS service endpoint is the URL of the entry point for an AWS web service. The SDKs and CLI use the default endpoint for each service in a Region, and you can specify an alternate endpoint, such as a FIPS or dual-stack endpoint, for your API requests.',
          'service-endpoints',
          ['An endpoint is the URL of the entry point for an AWS web service.',
           'The AWS SDKs and the AWS Command Line Interface (AWS CLI) automatically use the default endpoint for each service in an AWS Region.',
           'But you can specify an alternate endpoint for your API requests.']),
        b('Some services can be reached either through their public service endpoints or privately. Amazon S3 and DynamoDB support both gateway endpoints and interface endpoints. A {{term:vpc-endpoint}} lets resources in your VPC reach supported services privately, and AWS PrivateLink is the technology behind interface endpoints, letting you privately connect your VPC to services and resources as if they were in your VPC.',
          ['vpce-gateway', 'privatelink-what-is'],
          ['vpce-gateway|You can access Amazon S3 and DynamoDB through their public service endpoints or through gateway endpoints.',
           'vpce-gateway|Amazon S3 and DynamoDB support both gateway endpoints and interface endpoints.',
           'privatelink-what-is|AWS PrivateLink is a highly available, scalable technology that you can use to privately connect your VPC to services and resources as if they were in your VPC.']),
        b('Gateway endpoints cover Amazon S3 and DynamoDB and are targets in a route table, while interface endpoints put an endpoint network interface with a private IP address in each subnet you choose. Compare them side by side in the Don\'t confuse section below.',
          ['vpce-gateway', 'vpce-interface'],
          ['vpce-gateway|Gateway VPC endpoints provide reliable connectivity to Amazon S3 and DynamoDB without requiring an internet gateway or a NAT device for your VPC.',
           'vpce-interface|For each subnet that you specify from your VPC, we create an endpoint network interface in the subnet and assign it a private IP address from the subnet address range.']),
      ],
      services: ['Amazon VPC', 'AWS PrivateLink'],
      design: [
        b('Private subnets that only need S3 or DynamoDB do not need a NAT gateway for them: a gateway endpoint reaches those services without an internet gateway or NAT device. An interface endpoint is the type for other AWS services and for services offered through PrivateLink, and also for S3 when the access comes from on-premises networks, from peered VPCs in other Regions or through a transit gateway.',
          ['vpce-gateway-s3', 'privatelink-concepts'],
          ['vpce-gateway-s3|With a gateway endpoint, you can access Amazon S3 from your VPC, without requiring an internet gateway or NAT device for your VPC, and with no additional cost.',
           'vpce-gateway-s3|However, gateway endpoints do not allow access from on-premises networks, from peered VPCs in other AWS Regions, or through a transit gateway.',
           'vpce-gateway-s3|For those scenarios, you must use an interface endpoint, which is available for an additional cost.',
           'privatelink-concepts|Consumers create VPC endpoints to connect to endpoint services and resources that are hosted by providers.']),
      ],
    },
    {
      id: '1.2-S4',
      concepts: [
        b('AWS Site-to-Site VPN creates an IPsec VPN connection between your on-premises network and your VPC. Each VPN connection includes two tunnels you can use simultaneously for high availability. It terminates on a virtual private gateway or a transit gateway, with a customer gateway describing your device.',
          ['s2s-vpn', 's2s-vpn-how'],
          ['s2s-vpn|Site-to-Site VPN supports Internet Protocol security (IPsec) VPN connections.',
           's2s-vpn|Each VPN connection includes two VPN tunnels which you can simultaneously use for high availability.',
           's2s-vpn-how|Transit gateway A transit gateway is a transit hub that you can use to interconnect your VPCs and your on-premises networks.']),
        b('Direct Connect links your network to a Direct Connect location over a fiber-optic cable, bypassing internet service providers in your network path. AWS says it can reduce network costs, increase bandwidth and provide a more consistent experience than internet-based connections. A private path is not the same as an encrypted one: AWS Direct Connect does not encrypt your traffic in transit by default, and combining it with Site-to-Site VPN provides an IPsec-encrypted private connection.',
          ['dx-what-is', 'connectivity-dx', 'dx-encryption'],
          ['dx-what-is|bypassing internet service providers in your network path.',
           'dx-encryption|AWS Direct Connect does not encrypt your traffic that is in transit by default.',
           'dx-encryption|This combination provides an IPsec-encrypted private connection',
           'connectivity-dx|Direct Connect can reduce network costs, increase bandwidth throughput, and provide a more consistent network experience than internet-based connections.']),
        b('AWS Client VPN is a managed client-based VPN service for individual remote users; it uses an OpenVPN-based client and establishes encrypted TLS connections.',
          'client-vpn',
          ['AWS Client VPN is a managed client-based VPN service that enables you to securely access your AWS resources and resources in your on-premises network.',
           'With Client VPN, you can access your resources from any location using an OpenVPN-based VPN client.',
           'Establishes encrypted TLS connections from any location through the OpenVPN client']),
      ],
      services: ['AWS Site-to-Site VPN', 'AWS Direct Connect', 'AWS Client VPN'],
      design: [
        b('Site-to-site office or data-center connectivity over the internet with encryption: Site-to-Site VPN. A dedicated, consistent link: Direct Connect. Individual remote workers: Client VPN. Direct Connect and VPN are compared in Transit Tariff.',
          ['connectivity-vpn', 'connectivity-dx', 'client-vpn'],
          ['connectivity-vpn|Amazon VPC provides the option of creating an IPsec VPN connection between your remote networks and Amazon VPC over the internet',
           'connectivity-dx|AWS Direct Connect makes it easy to establish a dedicated connection from an on-premises network to one or more VPCs.',
           'client-vpn|Managed service — Eliminates the operational burden of deploying and maintaining third-party remote access VPN solutions through complete AWS management.']),
      ],
    },
  ],
  cues: [
    cue('access Amazon S3 from private subnets without an internet gateway or NAT, at no extra cost', 'S3 gateway endpoint',
      b('With a gateway endpoint you can access S3 from your VPC without an internet gateway or NAT device and with no additional cost.', 'vpce-gateway-s3',
        ['With a gateway endpoint, you can access Amazon S3 from your VPC, without requiring an internet gateway or NAT device for your VPC, and with no additional cost.'])),
    cue('privately access an AWS service or a SaaS product over private IP addresses', 'interface endpoint (AWS PrivateLink)',
      b('PrivateLink privately connects your VPC to services and resources as if they were in your VPC.', 'privatelink-what-is',
        ['AWS PrivateLink is a highly available, scalable technology that you can use to privately connect your VPC to services and resources as if they were in your VPC.'])),
    cue('encrypted connection between the corporate data center and the VPC over the internet', 'AWS Site-to-Site VPN',
      b('Site-to-Site VPN is an IPsec VPN connection between your on-premises network and your VPC.', 's2s-vpn',
        ['Site-to-Site VPN supports Internet Protocol security (IPsec) VPN connections.'])),
    cue('dedicated private connection that does not use the public internet', 'AWS Direct Connect (not encrypted by default; add VPN for IPsec)',
      b('Direct Connect bypasses internet service providers in your network path, but it does not encrypt your traffic in transit by default.', ['dx-what-is', 'dx-encryption'],
        ['dx-what-is|bypassing internet service providers in your network path.', 'dx-encryption|AWS Direct Connect does not encrypt your traffic that is in transit by default.'])),
    cue('remote employees connect securely from anywhere', 'AWS Client VPN',
      b('Client VPN lets you access resources from any location using an OpenVPN-based VPN client.', 'client-vpn',
        ['With Client VPN, you can access your resources from any location using an OpenVPN-based VPN client.'])),
  ],
  examples: [],
  confuse: ['gateway-vs-interface-endpoints', 'direct-connect-vs-vpn'],
  azure: [
    {
      concept: 'VPN Gateway',
      aws: 'AWS Site-to-Site VPN',
      mapping: b('The Learn networking page lists VPN Gateway as the Azure counterpart to Site-to-Site VPN, and describes both as robust solutions for connecting on-premises networks to the cloud.',
        ['learn-networking', 's2s-vpn'],
        ['learn-networking|Site-to-Site VPN VPN Gateway', 'learn-networking|are robust solutions for connecting on-premises networks to the cloud.', 's2s-vpn|You can enable access to your remote devices from your VPC by creating an AWS Site-to-Site VPN (Site-to-Site VPN) connection']),
      breaks: b('Learn says the two services provide similar features but with a notable difference in performance, and lists route-based and policy-based VPNs as a feature difference on the Azure side. On the AWS side a Site-to-Site VPN connection consists of a virtual private gateway or a transit gateway, a customer gateway device and a customer gateway, and each connection includes two tunnels.',
        ['s2s-vpn', 's2s-vpn-how', 'learn-networking'],
        ['learn-networking|They provide similar features, but there\'s a notable difference with performance.',
         'learn-networking|The key differences are in their integration with other cloud services and in specific features like route-based and policy-based VPNs in Azure.',
         's2s-vpn-how|A Site-to-Site VPN connection consists of the following components: A virtual private gateway or a transit gateway A customer gateway device A customer gateway',
         's2s-vpn|Each VPN connection includes two VPN tunnels which you can simultaneously use for high availability.'],
        { allow: ['two'] }),
    },
    {
      concept: 'ExpressRoute',
      aws: 'AWS Direct Connect',
      mapping: b('ExpressRoute and Direct Connect are the dedicated private-connection services; the Learn networking page pairs them.',
        ['learn-networking', 'dx-what-is'],
        ['learn-networking|AWS Direct Connect can link a network directly to AWS.', 'learn-networking|Azure provides similar site-to-site dedicated connections through ExpressRoute.',
         'dx-what-is|Direct Connect links your internal network to a Direct Connect location over a standard Ethernet fiber-optic cable.']),
      breaks: b('With Direct Connect you create virtual interfaces to public AWS services or to a VPC, bypassing internet service providers in your network path, and AWS states that Direct Connect does not encrypt traffic in transit by default. Learn describes ExpressRoute as a dedicated private network connection and says nothing about encryption in that row.',
        ['dx-what-is', 'dx-encryption', 'learn-networking'],
        ['dx-what-is|you can create virtual interfaces directly to public AWS services (for example, to Amazon S3) or to Amazon VPC, bypassing internet service providers in your network path.',
         'dx-encryption|AWS Direct Connect does not encrypt your traffic that is in transit by default.',
         'learn-networking|You can use ExpressRoute to connect your local network directly to Azure resources by using a dedicated private network connection.']),
    },
    {
      concept: 'Azure Private Link',
      aws: 'AWS PrivateLink',
      mapping: b('Learn says Azure Private Link is similar to AWS PrivateLink: Private Link provides private connectivity from a virtual network to an Azure platform as a service (PaaS) solution, a customer-owned service, or a Microsoft partner service.',
        ['learn-networking', 'privatelink-what-is'],
        ['learn-networking|Private Link is similar to AWS PrivateLink.',
         'learn-networking|Azure Private Link provides private connectivity from a virtual network to an Azure platform as a service (PaaS) solution, a customer-owned service, or a Microsoft partner service.',
         'privatelink-what-is|AWS PrivateLink is a highly available, scalable technology that you can use to privately connect your VPC to services and resources as if they were in your VPC.']),
      breaks: b('Learn lists AWS VPC endpoints against Azure Private Endpoint, and AWS PrivateLink against Azure Private Link. In AWS, "VPC endpoint" covers more than one type: a gateway endpoint sends traffic to Amazon S3 or DynamoDB and does not use AWS PrivateLink, unlike the other types of VPC endpoints.',
        ['privatelink-concepts', 'learn-networking'],
        ['privatelink-concepts|There is another type of VPC endpoint, Gateway, which creates a gateway endpoint to send traffic to Amazon S3 or DynamoDB.',
         'privatelink-concepts|Gateway endpoints do not use AWS PrivateLink, unlike the other types of VPC endpoints.',
         'learn-networking|VPC endpoints Private Endpoint']),
    },
  ],
};

export default notes;
