import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'wardens-lodge',
  overview: [
    b('Applications need two kinds of protection that are easy to confuse: keeping their own secrets (database passwords, API keys) out of source code, and letting their end users sign in. AWS Secrets Manager and Systems Manager Parameter Store address the first; Amazon Cognito and IAM Identity Center address the second.',
      ['secrets-intro', 'cognito-what-is'],
      ['secrets-intro|Secrets Manager helps you improve your security posture, because you no longer need hard-coded credentials in application source code.',
       'cognito-what-is|With Amazon Cognito, you can authenticate and authorize users from the built-in user directory, from your enterprise directory, and from consumer identity providers like Google and Facebook.'],
      { allow: ['two'] }),
  ],
  bullets: [
    {
      id: '1.2-K1',
      concepts: [
        b('AWS Secrets Manager helps you manage, retrieve and rotate database credentials, application credentials, OAuth tokens, API keys and other secrets throughout their lifecycles. The application makes a runtime call to retrieve the secret instead of holding it in its code.',
          'secrets-intro',
          ['AWS Secrets Manager helps you manage, retrieve, and rotate database credentials, application credentials, OAuth tokens, API keys, and other secrets throughout their lifecycles.',
           'You replace hard-coded credentials with a runtime call to the Secrets Manager service to retrieve credentials dynamically when you need them.']),
        b('Rotation is the process of periodically updating a secret: when you rotate it, you update the credentials in both the secret and the database or service. Secrets Manager can rotate on a schedule you configure.',
          'secrets-rotation',
          ['Rotation is the process of periodically updating a secret.', 'When you rotate a secret, you update the credentials in both the secret and the database or service.']),
        b('Secrets are encrypted with AWS KMS. You can use the AWS managed key aws/secretsmanager that Secrets Manager creates, or your own KMS keys.',
          'secrets-intro',
          ['You can use the AWS managed key aws/secretsmanager that Secrets Manager creates to encrypt your secrets for free.', 'Encryption keys – We recommend AWS Key Management Service.']),
        b('Systems Manager Parameter Store is a centralized store for configuration data. It supports String, StringList and SecureString parameters; for secrets such as database credentials, API keys or tokens, AWS recommends Secrets Manager.',
          'ssm-parameter-store',
          ['Parameter Store is a centralized configuration data store for named values called parameters.',
           'For secrets such as database credentials, API keys, or tokens, we recommend AWS Secrets Manager, which provides purpose built security controls including automatic rotation and cross-region replication.']),
      ],
      services: ['AWS Secrets Manager', 'AWS Systems Manager', 'AWS KMS'],
      design: [
        b('Keep credentials out of source code, images and environment files. Store them in Secrets Manager (with rotation for database credentials) and give the application\'s IAM role permission to retrieve only the secrets it needs.',
          ['secrets-intro', 'secrets-rotation'],
          ['secrets-intro|Storing the credentials in Secrets Manager helps avoid possible compromise by anyone who can inspect your application or the components.',
           'secrets-rotation|In Secrets Manager, you can set up automatic rotation for your secrets.']),
      ],
    },
    {
      id: '1.2-K4',
      concepts: [
        b('Amazon Cognito answers two different questions. A user pool answers "who is this user?" (authentication): it is a user directory for web and mobile app sign-up and sign-in, and from your app\'s perspective an OpenID Connect identity provider. An identity pool answers "what AWS resources may they use?" (authorization): it exchanges identities for temporary AWS credentials.',
          ['cognito-what-is', 'cognito-user-pools', 'cognito-identity-pools'],
          ['cognito-what-is|Amazon Cognito answers two different questions.', 'cognito-what-is|(authentication) Use a user pool.', 'cognito-what-is|(authorization) Use an identity pool.',
           'cognito-user-pools|An Amazon Cognito user pool is a user directory for web and mobile app authentication and authorization.',
           'cognito-identity-pools|Identity pools generate temporary AWS credentials for the users of your app, whether they’ve signed in or you haven’t identified them yet.'],
          { allow: ['two'] }),
        b('User pools can also sign users in through external identity providers, and Cognito can authenticate users from its built-in directory, an enterprise directory or consumer providers such as Google and Facebook.',
          ['cognito-what-is', 'cognito-user-pools'],
          ['cognito-what-is|from the built-in user directory, from your enterprise directory, and from consumer identity providers like Google and Facebook.',
           'cognito-user-pools|including sign-in through external identity providers']),
        b('AWS IAM Identity Center is the AWS solution for connecting workforce users to AWS managed applications and other AWS resources. Use it for employees; use Cognito for the customers of your own application.',
          'sso-what-is', ['AWS IAM Identity Center is the AWS solution for connecting your workforce users to AWS managed applications']),
        b('Behind a web app, AWS WAF can also protect an Amazon Cognito user pool as a resource type.',
          'waf-what-is', ['Amazon Cognito user pool']),
      ],
      services: ['Amazon Cognito', 'AWS IAM Identity Center'],
      design: [
        b('End users of a mobile or web app who need to sign up, sign in, or use social login: Cognito user pool. Those users then need to call an AWS service such as S3 or DynamoDB directly: add a Cognito identity pool for temporary credentials. Employees accessing AWS accounts and workforce applications: IAM Identity Center.',
          ['cognito-what-is', 'cognito-identity-pools', 'sso-what-is'],
          ['cognito-what-is|(authentication) Use a user pool.', 'cognito-identity-pools|Sign API requests to AWS services like Amazon Simple Storage Service (Amazon S3) and Amazon DynamoDB.',
           'sso-what-is|AWS IAM Identity Center is the AWS solution for connecting your workforce users to AWS managed applications']),
      ],
    },
  ],
  cues: [
    cue('credentials must not be hard-coded / rotate database passwords automatically', 'AWS Secrets Manager',
      b('Secrets Manager removes the need for hard-coded credentials and can rotate secrets on a schedule.', 'secrets-intro',
        ['Secrets Manager helps you improve your security posture, because you no longer need hard-coded credentials in application source code.', 'With Secrets Manager, you can configure an automatic rotation schedule for your secrets.'])),
    cue('store configuration values (endpoints, flags), optionally encrypted', 'Systems Manager Parameter Store',
      b('Parameter Store is a centralized configuration data store; SecureString covers values that need encryption.', 'ssm-parameter-store',
        ['SecureString Use SecureString for configuration values that require encryption, such as service endpoints and account identifiers.'])),
    cue('sign-up and sign-in for a mobile or web app / social identity providers', 'Amazon Cognito user pool',
      b('A user pool is a user directory for web and mobile app authentication and authorization.', 'cognito-user-pools',
        ['An Amazon Cognito user pool is a user directory for web and mobile app authentication and authorization.'])),
    cue('give app users temporary AWS credentials to call S3 or DynamoDB directly', 'Amazon Cognito identity pool',
      b('Identity pools generate temporary AWS credentials for the users of your app.', 'cognito-identity-pools',
        ['Identity pools generate temporary AWS credentials for the users of your app'])),
    cue('workforce / employees single sign-on to AWS accounts and applications', 'AWS IAM Identity Center',
      b('IAM Identity Center connects workforce users to AWS applications and resources.', 'sso-what-is',
        ['AWS IAM Identity Center is the AWS solution for connecting your workforce users to AWS managed applications'])),
  ],
  examples: [],
  confuse: ['secrets-manager-vs-parameter-store'],
  azure: [
    {
      concept: 'Microsoft Entra External ID',
      aws: 'Amazon Cognito',
      mapping: b('For customer-facing apps, Learn pairs Cognito with the Microsoft identity platform and Entra External ID, which serves the same purpose: signing in the customers of your application.',
        ['learn-hub', 'cognito-user-pools'],
        ['learn-hub|External ID is a highly available global identity management service for consumer-facing',
         'cognito-user-pools|An Amazon Cognito user pool is a user directory for web and mobile app authentication and authorization.']),
      breaks: b('Cognito is two things. A user pool authenticates users, and an identity pool exchanges identities for temporary AWS credentials, which has no direct Learn row. Questions that need AWS credentials for app users are asking about the identity pool.',
        ['cognito-what-is', 'cognito-identity-pools', 'learn-hub'],
        ['cognito-what-is|Amazon Cognito answers two different questions.',
         'cognito-identity-pools|Identity pools generate temporary AWS credentials for the users of your app',
         'learn-hub|Microsoft identity platform and Microsoft Entra External ID'],
        { allow: ['two'] }),
    },
    {
      concept: 'Microsoft Entra ID',
      aws: 'AWS IAM Identity Center',
      mapping: b('For employees, Learn pairs Entra ID with IAM Identity Center and IAM, the services for controlling access to services and resources.',
        ['learn-hub', 'sso-what-is'],
        ['learn-hub|Use these services to more securely control access to services and resources and improve data security and protection.',
         'sso-what-is|AWS IAM Identity Center is the AWS solution for connecting your workforce users to AWS managed applications']),
      breaks: b('IAM Identity Center is for workforce users. Do not use it for the customers of your own application; that is Cognito.',
        ['sso-what-is', 'cognito-what-is', 'learn-hub'],
        ['learn-hub|Microsoft Entra ID', 'sso-what-is|AWS IAM Identity Center is the AWS solution for connecting your workforce users to AWS managed applications',
         'cognito-what-is|With Amazon Cognito, you can authenticate and authorize users from the built-in user directory, from your enterprise directory, and from consumer identity providers like Google and Facebook.']),
    },
  ],
};

export default notes;
