import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'watchtower',
  overview: [
    b('Threats come from outside AWS too: flooding a site with traffic (a {{term:ddos}} attack), injecting malicious SQL into a web request, leaked credentials, or sensitive data sitting in a public bucket. This building is the set of AWS services that block or detect those things: AWS Shield and AWS WAF at the edge, Amazon GuardDuty, Amazon Macie and Amazon Inspector for detection and assessment, and AWS Security Hub and Amazon Detective to bring findings together.',
      ['shield-overview', 'waf-sqli', 'waf-what-is', 'guardduty', 'macie'],
      ['shield-overview|A DDoS attack is an attack in which multiple compromised systems try to flood a target with traffic.',
       'waf-sqli|Attackers insert malicious SQL code into web requests in order to do things like modify your database or extract data from it.',
       'guardduty|Amazon GuardDuty is a threat detection service that continuously monitors, analyzes, and processes AWS data sources and logs in your AWS environment.',
       'macie|Amazon Macie is a data security service that discovers sensitive data by using machine learning and pattern matching']),
  ],
  beyondProject: [
    b('Your static site is delivered through CloudFront, and CloudFront is one of the resource types AWS WAF can protect; your counter\'s API Gateway REST API is another. What your projects do not show you is what happens when someone attacks them. SAA adds the design choices: put a web ACL on the distribution or API to filter bad requests, and rely on Shield for DDoS protection (Standard is automatic for every customer).',
      ['waf-what-is', 'shield-standard'],
      ['waf-what-is|You can protect the following resource types: Amazon CloudFront distributionAmazon API Gateway REST APIApplication Load Balancer',
       'shield-standard|All AWS customers benefit from the automatic protection of Shield Standard, at no additional charge.']),
  ],
  bullets: [
    {
      id: '1.2-K5',
      concepts: [
        b('{{term:guardduty|Amazon GuardDuty}} is a threat detection service that continuously monitors AWS data sources and logs, using threat intelligence feeds and machine learning to identify suspicious activity such as compromised AWS credentials. Its foundational data sources are CloudTrail management events, VPC Flow Logs and Route 53 Resolver DNS query logs.',
          ['guardduty', 'guardduty-data'],
          ['guardduty|GuardDuty uses threat intelligence feeds, such as lists of malicious IP addresses and domains, file hashes, and machine learning (ML) models to identify suspicious and potentially malicious activity in your AWS environment.',
           'guardduty|Compromised and exfiltrated AWS credentials.',
           'guardduty-data|AWS CloudTrail management eventsVPC Flow LogsRoute53 Resolver DNS query logs']),
        b('{{term:macie}} discovers sensitive data in Amazon S3 using machine learning and pattern matching, and generates a finding when it detects sensitive data or a security issue such as a bucket that becomes publicly accessible.',
          'macie',
          ['Amazon Macie is a data security service that discovers sensitive data by using machine learning and pattern matching',
           'Macie generates a finding for you to review and remediate as necessary.',
           'such as a bucket that becomes publicly accessible']),
        b('Amazon Inspector is a vulnerability management service that continually scans EC2 instances, container images in Amazon ECR and Lambda functions for software vulnerabilities and unintended network exposure.',
          'inspector', ['Amazon Inspector is a vulnerability management service that automatically discovers workloads and continually scans them for software vulnerabilities and unintended network exposure.',
            'Amazon Inspector discovers and scans Amazon EC2 instances, container images in Amazon ECR, and Lambda functions.']),
        b('AWS Security Hub gives a comprehensive view of your security state: it runs checks against security controls and also receives findings from services such as GuardDuty, Inspector and Macie. Amazon Detective collects log data and uses machine learning, statistical analysis and graph theory to help you investigate findings.',
          ['security-hub', 'detective'],
          ['security-hub|In addition to generating control findings, Security Hub CSPM also receives findings from other AWS services—such as Amazon GuardDuty, Amazon Inspector, and Amazon Macie',
           'detective|Amazon Detective automatically collects log data from your AWS resources and uses machine learning (ML), statistical analysis, and graph theory to build a dataset that you can use to conduct more efficient security investigations.']),
        b('Amazon Cognito (named in this bullet) handles user sign-in and access for applications. It is covered in Warden\'s Lodge, which owns the application-access bullet.',
          'cognito-what-is', ['With Amazon Cognito, you can authenticate and authorize users from the built-in user directory, from your enterprise directory, and from consumer identity providers like Google and Facebook.']),
      ],
      services: ['Amazon GuardDuty', 'Amazon Macie', 'Amazon Inspector', 'AWS Security Hub', 'Amazon Detective', 'Amazon Cognito'],
      design: [
        b('Match the service to the question. Suspicious activity or compromised credentials in the account: GuardDuty. Sensitive data in S3 or public buckets: Macie. Software vulnerabilities and network exposure on workloads: Inspector. One place that aggregates findings and security-check results: Security Hub. Digging into the cause of a finding: Detective.',
          ['guardduty', 'macie', 'inspector', 'security-hub', 'detective'],
          ['guardduty|Amazon GuardDuty is a threat detection service that continuously monitors, analyzes, and processes AWS data sources and logs in your AWS environment.',
           'macie|Amazon Macie is a data security service that discovers sensitive data by using machine learning and pattern matching',
           'inspector|continually scans them for software vulnerabilities and unintended network exposure',
           'security-hub|Security Hub CSPM runs checks against security controls and generates control findings to help you assess your compliance against security best practices.',
           'detective|Determine potential security issues through a unified view of user and resource interactions.']),
      ],
    },
    {
      id: '1.2-K6',
      concepts: [
        b('A {{term:ddos}} attack is one in which multiple compromised systems try to flood a target with traffic. AWS Shield provides protection against DDoS attacks for AWS resources at the network and transport layers (layers 3 and 4) and the application layer (layer 7).',
          'shield-overview',
          ['A DDoS attack is an attack in which multiple compromised systems try to flood a target with traffic.',
           'AWS Shield Standard and AWS Shield Advanced provide protections against Distributed Denial of Service (DDoS) attacks for AWS resources at the network and transport layers (layer 3 and 4) and the application layer (layer 7).']),
        b('SQL injection is an attack where malicious SQL code is inserted into web requests to modify or extract data from a database. AWS WAF has a rule statement that inspects requests for malicious SQL code.',
          'waf-sqli', ['Attackers insert malicious SQL code into web requests in order to do things like modify your database or extract data from it.', 'An SQL injection rule statement inspects for malicious SQL code.']),
      ],
      services: ['AWS Shield', 'AWS WAF'],
      design: [
        b('Threats external to AWS appear in questions as DDoS, SQL injection and similar web attacks. The first answers to reach for are AWS Shield (DDoS) and AWS WAF (filtering web requests), placed in front of CloudFront, an Application Load Balancer or API Gateway.',
          ['shield-overview', 'waf-what-is'],
          ['shield-overview|provide protections against Distributed Denial of Service (DDoS) attacks for AWS resources',
           'waf-what-is|You can protect the following resource types: Amazon CloudFront distributionAmazon API Gateway REST APIApplication Load Balancer']),
      ],
    },
    {
      id: '1.2-S3',
      concepts: [
        b('AWS WAF works by defining a web access control list (web ACL) and associating it with the web application resources you want to protect. Requests are forwarded to AWS WAF for inspection by the web ACL, and the protected resource responds with the content, a `403`, or a custom response.',
          ['waf-how-works', 'waf-what-is'],
          ['waf-how-works|You do this by defining a web access control list (web ACL) and then associating it with one or more web application resources that you want to protect.',
           'waf-how-works|The associated resources forward incoming requests to AWS WAF for inspection by the web ACL.',
           'waf-what-is|with an HTTP 403 status code (Forbidden), or with a custom response']),
        b('AWS Shield Standard gives all AWS customers automatic protection at no additional charge against common network and transport layer DDoS attacks. Shield Advanced is a subscription for expanded protection of the resources you choose.',
          ['shield-standard', 'shield-advanced'],
          ['shield-standard|All AWS customers benefit from the automatic protection of Shield Standard, at no additional charge.',
           'shield-advanced|For higher levels of protection against attacks, you can subscribe to AWS Shield Advanced.']),
        b('AWS Network Firewall filters traffic at the perimeter of your VPC and uses the open source intrusion prevention system Suricata for stateful inspection. AWS Firewall Manager applies protections such as AWS WAF, Shield Advanced, security groups and Network Firewall across multiple accounts from one place.',
          ['network-firewall', 'firewall-manager'],
          ['network-firewall|With Network Firewall, you can filter traffic at the perimeter of your VPC.',
           'network-firewall|Network Firewall uses the open source intrusion prevention system (IPS), Suricata, for stateful inspection',
           'firewall-manager|AWS Firewall Manager simplifies your administration and maintenance tasks across multiple accounts and resources for a variety of protections, including AWS WAF, AWS Shield Advanced, Amazon VPC security groups and network ACLs, AWS Network Firewall']),
        b('Integrating these with other security tools: the application-credentials half of this bullet (IAM Identity Center and AWS Secrets Manager for applications) is in Warden\'s Lodge.',
          'secrets-intro', ['AWS Secrets Manager helps you manage, retrieve, and rotate database credentials, application credentials, OAuth tokens, API keys, and other secrets throughout their lifecycles.']),
      ],
      services: ['AWS Shield', 'AWS WAF', 'AWS Network Firewall', 'AWS Firewall Manager', 'AWS IAM Identity Center', 'AWS Secrets Manager'],
      design: [
        b('Layer the defences: Shield for DDoS, a WAF web ACL on the CloudFront distribution, load balancer or API for request filtering, security groups and network ACLs inside the VPC, and Network Firewall when you need to inspect traffic at the VPC perimeter. Use Firewall Manager to apply these consistently across accounts.',
          ['waf-how-works', 'network-firewall', 'firewall-manager'],
          ['waf-how-works|You use AWS WAF to control how your protected resources respond to HTTP(S) web requests.',
           'network-firewall|With Network Firewall, you can filter traffic at the perimeter of your VPC.',
           'firewall-manager|With Firewall Manager, you set up your protections just once and the service automatically applies them across your accounts and resources']),
      ],
    },
  ],
  cues: [
    cue('DDoS attack / flood of traffic', 'AWS Shield (Standard is automatic; Advanced for expanded protection)',
      b('Shield Standard automatically protects all AWS customers; Advanced is a subscription for higher levels of protection.', 'shield-advanced',
        ['For higher levels of protection against attacks, you can subscribe to AWS Shield Advanced.'])),
    cue('SQL injection / filter HTTP requests / block IP addresses at the application layer', 'AWS WAF',
      b('AWS WAF lets you monitor and control HTTP(S) requests to protected resources, for example by IP address or query-string values.', 'waf-what-is',
        ['Based on criteria that you specify, such as the IP addresses that requests originate from or the values of query strings'])),
    cue('detect compromised credentials / unusual API activity / malicious IP communication', 'Amazon GuardDuty',
      b('GuardDuty identifies suspicious activity using threat intelligence feeds and machine learning, and covers compromised credentials.', 'guardduty',
        ['Compromised and exfiltrated AWS credentials.'])),
    cue('discover sensitive data (PII) in Amazon S3', 'Amazon Macie',
      b('Macie discovers sensitive data in S3 using machine learning and pattern matching.', 'macie',
        ['Amazon Macie is a data security service that discovers sensitive data by using machine learning and pattern matching'])),
    cue('scan EC2 instances, container images or Lambda functions for software vulnerabilities', 'Amazon Inspector',
      b('Amazon Inspector discovers and scans EC2 instances, container images in Amazon ECR and Lambda functions.', 'inspector',
        ['Amazon Inspector discovers and scans Amazon EC2 instances, container images in Amazon ECR, and Lambda functions.'])),
    cue('aggregate security findings from several services in one place', 'AWS Security Hub',
      b('Security Hub also receives findings from other AWS services such as GuardDuty, Inspector and Macie.', 'security-hub',
        ['Security Hub CSPM also receives findings from other AWS services—such as Amazon GuardDuty, Amazon Inspector, and Amazon Macie'])),
    cue('apply WAF or Shield Advanced protections across all accounts', 'AWS Firewall Manager',
      b('Firewall Manager applies protections across accounts and resources.', 'firewall-manager',
        ['With Firewall Manager, you set up your protections just once and the service automatically applies them across your accounts and resources'])),
  ],
  examples: [],
  confuse: ['shield-vs-waf'],
  azure: [
    {
      concept: 'Azure web application firewall',
      aws: 'AWS WAF',
      mapping: b('Both are web application firewalls for protecting web apps from common exploits.',
        ['learn-hub', 'waf-what-is'],
        ['learn-hub|These firewalls help protect web applications from common web exploits.',
         'waf-what-is|AWS WAF is a web application firewall that lets you monitor the HTTP(S) requests that are forwarded to your protected web application resources.']),
      breaks: b('In AWS, WAF is a separate service that you associate with a CloudFront distribution, API Gateway REST API, Application Load Balancer or another supported resource, using a web ACL.',
        ['waf-what-is', 'waf-how-works', 'learn-hub'],
        ['waf-what-is|You can protect the following resource types: Amazon CloudFront distributionAmazon API Gateway REST APIApplication Load Balancer',
         'learn-hub|AWS WAF Azure web application firewall',
         'waf-how-works|by defining a web access control list (web ACL) and then associating it with one or more web application resources that you want to protect']),
    },
    {
      concept: 'Azure DDoS Protection',
      aws: 'AWS Shield',
      mapping: b('Both protect cloud services from distributed denial of service attacks.',
        ['learn-hub', 'shield-overview'],
        ['learn-hub|These services help you protect your cloud services from distributed denial of service attacks.',
         'shield-overview|A DDoS attack is an attack in which multiple compromised systems try to flood a target with traffic.']),
      breaks: b('AWS has two tiers. Shield Standard protects every AWS customer automatically at no additional charge, and Shield Advanced is a subscription for expanded protection. Know which one a question is describing.',
        ['shield-standard', 'shield-advanced', 'learn-hub'],
        ['shield-standard|All AWS customers benefit from the automatic protection of Shield Standard, at no additional charge.',
         'shield-advanced|For higher levels of protection against attacks, you can subscribe to AWS Shield Advanced.',
         'learn-hub|Azure DDoS Protection'],
        { allow: ['two'] }),
    },
    {
      concept: 'Microsoft Sentinel',
      aws: 'Amazon GuardDuty',
      mapping: b('The Learn comparison pairs GuardDuty with Microsoft Sentinel because both are about detecting attacks.',
        ['learn-hub', 'guardduty'],
        ['learn-hub|Detect and investigate advanced attacks on-premises and in the cloud.',
         'guardduty|Amazon GuardDuty is a threat detection service that continuously monitors, analyzes, and processes AWS data sources and logs in your AWS environment.']),
      breaks: b('The pairing is loose. GuardDuty is a threat detection service that analyses AWS data sources such as CloudTrail management events, VPC Flow Logs and DNS query logs. The role of gathering findings from many services in one place is closer to AWS Security Hub, and investigating causes is Amazon Detective.',
        ['guardduty-data', 'security-hub', 'detective', 'learn-hub'],
        ['guardduty-data|AWS CloudTrail management eventsVPC Flow LogsRoute53 Resolver DNS query logs',
         'security-hub|Security Hub CSPM also receives findings from other AWS services—such as Amazon GuardDuty, Amazon Inspector, and Amazon Macie',
         'detective|Investigate and respond to security findings with streamlined visualizations.',
         'learn-hub|Microsoft Sentinel']),
    },
    {
      concept: 'Microsoft Defender for Cloud',
      aws: 'Amazon Inspector',
      mapping: b('Learn pairs Inspector with Defender for Cloud: both assess workloads for security weaknesses.',
        ['learn-hub', 'inspector'],
        ['learn-hub|Defender for Cloud is an automated security assessment service that improves the security and compliance of applications',
         'inspector|Amazon Inspector is a vulnerability management service that automatically discovers workloads and continually scans them for software vulnerabilities and unintended network exposure.']),
      breaks: b('Inspector scans specific resource types: EC2 instances, container images in ECR and Lambda functions. It is a vulnerability scanner rather than a whole cloud security posture product; posture checks sit in AWS Security Hub.',
        ['inspector', 'security-hub', 'learn-hub'],
        ['inspector|Amazon Inspector discovers and scans Amazon EC2 instances, container images in Amazon ECR, and Lambda functions.',
         'security-hub|Security Hub CSPM runs checks against security controls and generates control findings to help you assess your compliance against security best practices.',
         'learn-hub|Microsoft Defender for Cloud']),
    },
    {
      concept: 'Azure Firewall',
      aws: 'AWS Network Firewall',
      mapping: b('The Learn networking page describes Azure Firewall as a managed, stateful, cloud-native firewall similar to AWS Network Firewall.',
        ['learn-networking', 'network-firewall'],
        ['learn-networking|Azure Firewall provides a managed, stateful, cloud-native firewall with FQDN filtering, threat intelligence, and optional IDPS/TLS inspection, similar to AWS Network Firewall.',
         'network-firewall|With Network Firewall, you can filter traffic at the perimeter of your VPC.']),
      breaks: b('AWS Network Firewall is deployed to filter traffic at the perimeter of a VPC and uses Suricata-compatible rules for stateful inspection; it complements, and does not replace, security groups and network ACLs.',
        ['network-firewall', 'vpc-nacls', 'learn-networking'],
        ['learn-networking|Azure Firewall provides a managed, stateful, cloud-native firewall',
         'network-firewall|Network Firewall uses the open source intrusion prevention system (IPS), Suricata, for stateful inspection, and supports Suricata compatible rules.',
         'vpc-nacls|Custom network ACLs add an additional layer of security to your VPC.']),
    },
  ],
};

export default notes;
