import type { GlossaryTerm } from '../src/content/types.ts';
import { b } from './helpers.ts';

const t = (id: string, term: string, definition: GlossaryTerm['definition'], aliases?: string[]): GlossaryTerm =>
  aliases ? { id, term, aliases, definition } : { id, term, definition };

/** Each term is defined here once. Notes reference terms with {{term:id}} and never redefine them. */
const glossary: GlossaryTerm[] = [
  // ── Founders' Square ──
  t('well-architected-framework', 'AWS Well-Architected Framework',
    b('AWS\'s set of design principles and best practices for building workloads, organised into six pillars. The SAA exam validates your ability to design solutions based on it.',
      ['waf-pillars', 'exam-guide'],
      ['waf-pillars|the six pillars of operational excellence, security, reliability, performance efficiency, cost optimization, and sustainability',
       "exam-guide|The exam validates a candidate's ability to design solutions based on the AWS Well-Architected Framework."]),
    ['Well-Architected']),
  t('pillar', 'Pillar',
    b('One of the six areas of the Well-Architected Framework: operational excellence, security, reliability, performance efficiency, cost optimization and sustainability.',
      'waf-pillars', ['the six pillars of operational excellence, security, reliability, performance efficiency, cost optimization, and sustainability'])),
  t('root-user', 'Root user',
    b('The single sign-in identity you begin with when you create an AWS account. It has complete access to the account, so it is reserved for the few tasks that need it.',
      'iam-root-user', ['you begin with a single sign-in identity that has complete access to all AWS', 'Use the root user only to perform the tasks that require root-level permissions.']),
    ['AWS account root user']),
  t('mfa', 'Multi-factor authentication (MFA)',
    b('A sign-in check that needs more than a password. AWS recommends turning it on to help protect your resources, including the root user.',
      'iam-mfa', ['we recommend that you configure multi-factor authentication (MFA) to help protect your AWS resources']),
    ['MFA']),
  t('budget', 'Budget (AWS Budgets)',
    b('A spending or usage limit you set in AWS Budgets that alerts you when actual or forecasted costs approach or exceed a threshold.',
      'budgets-managing', ['Set spending limits for services and receive alerts when costs approach or exceed your defined threshold.']),
    ['AWS Budgets budget']),
  t('cidr-block', 'CIDR block',
    b('A range of IP addresses written in CIDR (Classless Inter-Domain Routing) notation, such as a VPC or subnet range.',
      'vpc-subnet-sizing', ['The IP addresses for your subnets are represented using Classless Inter-Domain Routing (CIDR) notation.']),
    ['CIDR']),
  t('protocol', 'Protocol (network)',
    b('The traffic type a network rule matches. In security group rules the most common are TCP, UDP and ICMP.',
      'vpc-sg-rules', ['The most common protocols are 6 (TCP), 17 (UDP), and 1 (ICMP).']),
    ['IP protocol']),
  t('port-range', 'Port range',
    b('For TCP and UDP rules, the range of ports a rule allows or matches.',
      'vpc-sg-rules', ['Port range: For TCP, UDP, or a custom protocol, the range of ports to allow.'])),
  t('metric', 'Metric (CloudWatch)',
    b('Performance data that CloudWatch collects and tracks at intervals you choose, kept in a namespace so different applications are not mixed together.',
      ['cw-concepts', 'cw-what-is'], ['cw-concepts|A namespace is a container for CloudWatch metrics.', 'cw-what-is|Metrics collect and track key performance data at user-defined intervals.']),
    ['CloudWatch metric']),
  t('alarm', 'Alarm (CloudWatch)',
    b('A CloudWatch rule that watches a metric and sends a notification or takes an automatic action when a threshold is breached.',
      'cw-alarms', ['You can create alarms that watch metrics and send notifications or automatically make changes to the resources you are monitoring when a threshold is breached.']),
    ['CloudWatch alarm']),
  t('log-group', 'Log group',
    b('A CloudWatch Logs container for log streams that share the same retention, monitoring and access control settings.',
      'cwl-concepts', ['Log groups define groups of log streams that share the same retention, monitoring, and access control settings.']),
    ['CloudWatch log group']),
  t('cloudtrail-event', 'CloudTrail event',
    b('A record of an action taken by a user, role or AWS service, including actions in the console, CLI, SDKs and APIs.',
      'cloudtrail-what-is', ['Actions taken by a user, role, or an AWS service are recorded as events in CloudTrail.']),
    ['CloudTrail management event']),
  t('config-rule', 'AWS Config rule',
    b('A rule that represents an ideal configuration setting; AWS Config evaluates your resources against it.',
      'config-rules', ['You do this by creating AWS Config rules, which represent your ideal configuration settings.'])),
  // ── Citadel: access and accounts ──
  t('iam', 'AWS Identity and Access Management (IAM)',
    b('The AWS service for managing permissions that control which AWS resources users can access.', 'iam-intro',
      ['With IAM, you can manage permissions that control which AWS resources users can access.']), ['IAM']),
  t('least-privilege', 'Least privilege',
    b('Granting only the permissions required to perform a task, by defining the actions that can be taken on specific resources under specific conditions.', 'iam-best-practices',
      ['grant only the permissions required to perform a task', 'defining the actions that can be taken on specific resources under specific conditions, also known as least-privilege permissions']),
    ['least-privilege permissions']),
  t('iam-user', 'IAM user', b('An entity that you create in your AWS account.', 'iam-users', ['An IAM user is an entity that you create in your AWS account.'])),
  t('iam-group', 'IAM user group', b('A collection of IAM users.', 'iam-groups', ['An IAM user group is a collection of IAM users.']), ['IAM group']),
  t('iam-role', 'IAM role',
    b('An IAM identity with specific permissions and no standard long-term credentials; assuming it gives temporary security credentials for the role session.', 'iam-roles',
      ['An IAM role is an IAM identity that you can create in your account that has specific permissions.', 'a role does not have standard long-term credentials such as a password or access keys associated with it.']),
    ['role']),
  t('policy', 'Policy (IAM)',
    b('An object in AWS that, when associated with an identity or resource, defines their permissions.', 'iam-policies',
      ['A policy is an object in AWS that, when associated with an identity or resource, defines their permissions.']), ['IAM policy']),
  t('federation', 'Federation',
    b('Letting people sign in to AWS with an identity from an outside identity provider, so you do not have to create an IAM user for everyone in your organisation.', 'iam-saml',
      ['without you having to create an IAM user for everyone in your organization'])),
  t('aws-directory-service', 'AWS Directory Service',
    b('A service that provides multiple ways to use Microsoft Active Directory with other AWS services.', 'ds-what-is',
      ['AWS Directory Service provides multiple ways to use Microsoft Active Directory (AD) with other AWS services.'])),
  t('aws-organizations', 'AWS Organizations',
    b('A service to centrally manage and govern many AWS accounts: create and group accounts, apply policies and simplify billing.', 'orgs-intro',
      ['AWS Organizations helps you centrally manage and govern your environment as you grow and scale your AWS resources.']), ['Organizations']),
  t('scp', 'Service control policy (SCP)',
    b('An organization policy that offers central control over the maximum available permissions for the IAM users and roles in an organization. It does not grant permissions.', 'orgs-scps',
      ['SCPs offer central control over the maximum available permissions for the IAM users and IAM roles in your organization.', 'SCPs do not grant permissions to the IAM users and IAM roles in your organization.']), ['SCP']),
  t('control-tower', 'AWS Control Tower',
    b('A service that sets up and governs a multi-account AWS environment following prescriptive best practices.', 'control-tower',
      ['AWS Control Tower offers a straightforward way to set up and govern an AWS multi-account environment, following prescriptive best practices.'])),
  t('aws-ram', 'AWS Resource Access Manager (AWS RAM)',
    b('A service that helps you securely share your resources across AWS accounts, within your organization or its organizational units.', 'ram-what-is',
      ['AWS Resource Access Manager (AWS RAM) helps you securely share your resources across AWS accounts, within your organiz']), ['AWS RAM']),
  t('sts', 'AWS Security Token Service (AWS STS)',
    b('The AWS service behind temporary security credentials, which are generated dynamically and provided when requested.', 'iam-temp-creds',
      ['You can use the AWS Security Token Service (AWS STS) to', 'Temporary security credentials are not stored with the user but are generated dynamically and provided to the user when requested.']), ['STS']),
  t('region', 'Region',
    b('A physical location around the world where AWS clusters data centers.', 'global-infra',
      ['AWS has the concept of a Region, which is a physical location around the world where we cluster data centers.']), ['AWS Region']),
  t('availability-zone', 'Availability Zone (AZ)',
    b('One or more discrete data centers with separate and redundant power, networking and connectivity in a Region.', 'fault-isolation-az',
      ['An Availability Zone is one or more discrete data centers with separate and redundant power infrastructure, networking, and connectivity in an AWS Region.']), ['AZ']),
  t('shared-responsibility-model', 'Shared responsibility model',
    b('AWS is responsible for security of the cloud (the infrastructure that runs its services); the customer is responsible for security in the cloud, determined by the services they select.', 'shared-responsibility',
      ['AWS is responsible for protecting the infrastructure that runs all of the services offered in the AWS Cloud.', 'Customer responsibility will be determined by the AWS Cloud services that a customer selects.'])),

  // ── Citadel: network, threats, encryption ──
  t('vpc', 'Amazon VPC (virtual private cloud)',
    b('A logically isolated virtual network in which you launch AWS resources.', 'vpc-how-it-works',
      ['you can launch AWS resources in a logically isolated virtual network']), ['VPC']),
  t('subnet', 'Subnet',
    b("A slice of a VPC's address range. Each subnet must reside entirely within one Availability Zone.", 'vpc-subnets',
      ['Each subnet must reside entirely within one Availability Zone and cannot span zones.'])),
  t('route-table', 'Route table',
    b('A set of routes, each with a destination and a target, that determines where network traffic from a subnet or gateway is directed.', 'vpc-route-tables',
      ['Each route table contains a set of rules, called routes, that determine where network traffic from your subnet or gateway is directed.'])),
  t('security-group', 'Security group',
    b('A rule set that controls the traffic allowed to reach and leave the resources it is associated with.', 'vpc-security-groups',
      ['A security group controls the traffic that is allowed to reach and leave the resources that it is associated with.'])),
  t('network-acl', 'Network ACL (NACL)',
    b('A subnet-level rule list that allows or denies specific inbound or outbound traffic.', 'vpc-nacls',
      ['A network access control list (ACL) allows or denies specific inbound or outbound traffic at the subnet level.']), ['network access control list', 'NACL']),
  t('ddos', 'DDoS (distributed denial of service) attack',
    b('An attack in which multiple compromised systems try to flood a target with traffic.', 'shield-overview',
      ['A DDoS attack is an attack in which multiple compromised systems try to flood a target with traffic.']), ['DDoS']),
  t('guardduty', 'Amazon GuardDuty',
    b('A threat detection service that continuously monitors, analyzes and processes AWS data sources and logs.', 'guardduty',
      ['Amazon GuardDuty is a threat detection service that continuously monitors, analyzes, and processes AWS data sources and logs in your AWS environment.']), ['GuardDuty']),
  t('macie', 'Amazon Macie',
    b('A data security service that discovers sensitive data by using machine learning and pattern matching.', 'macie',
      ['Amazon Macie is a data security service that discovers sensitive data by using machine learning and pattern matching']), ['Macie']),
  t('service-endpoint', 'Service endpoint',
    b('The URL of the entry point for an AWS web service.', 'service-endpoints', ['An endpoint is the URL of the entry point for an AWS web service.']), ['AWS service endpoint']),
  t('vpc-endpoint', 'VPC endpoint',
    b('A private connection from a VPC to a supported service, as a gateway endpoint (S3 and DynamoDB) or an interface endpoint (AWS PrivateLink).', ['vpce-gateway', 'privatelink-what-is'],
      ['vpce-gateway|Gateway VPC endpoints provide reliable connectivity to Amazon S3 and DynamoDB without requiring an internet gateway or a NAT device for your VPC.',
       'privatelink-what-is|AWS PrivateLink is a highly available, scalable technology that you can use to privately connect your VPC to services and resources as if they were in your VPC.'])),
  t('aws-kms', 'AWS Key Management Service (AWS KMS)',
    b('An AWS managed service that makes it easy to create and control the keys used to encrypt and sign your data.', 'kms-overview',
      ['AWS Key Management Service (AWS KMS) is an AWS managed service that makes it easy for you to create and control the keys used to encrypt and sign your data.']), ['AWS KMS', 'KMS']),
  t('key-policy', 'Key policy',
    b('A resource policy for an AWS KMS key; every KMS key must have exactly one, and it is the primary way to control access to the key.', 'kms-key-policies',
      ['A key policy is a resource policy for an AWS KMS key.', 'Every KMS key must have exactly one key policy.', 'Key policies are the primary way to control access to KMS keys.'])),
  t('acm', 'AWS Certificate Manager (ACM)',
    b('A service that handles creating, storing and renewing public and private SSL/TLS certificates and keys for AWS websites and applications.', 'acm-overview',
      ['AWS Certificate Manager (ACM) handles the complexity of creating, storing, and renewing public and private SSL/TLS X.509 certificates and keys that protect your AWS websites and applications.']), ['ACM']),
  t('aws-backup', 'AWS Backup',
    b('A fully managed service that centralizes and automates data protection across AWS services, in the cloud and on premises.', 'backup-what-is',
      ['AWS Backup is a fully-managed service that makes it easy to centralize and automate data protection across AWS services, in the cloud, and on premises.'])),
  // ── Harbor & Levees ──
  t('microservice', 'Microservices',
    b('An approach built from small, loosely coupled services that communicate through well-defined APIs and are managed by autonomous teams.', 'msa-whitepaper',
      ['This method relies on small, loosely coupled services that communicate through well-defined APIs, which are managed by autonomous teams.']), ['microservices architecture']),
  t('stateless', 'Stateless application',
    b('An application that does not need knowledge of previous interactions and does not store session information.', 'waf-stateless',
      ['A stateless application is an application that does not need knowledge of previous interactions and does not store session information.']), ['stateless']),
  t('session', 'Session',
    b('Unique data for a user that persists between requests while they use the application.', 'waf-stateless',
      ['A session is unique data for users that persists between requests while they use the application.'])),
  t('three-tier', 'Layered (multi-tier) application',
    b('An application split into technological layers, typically a presentation layer, an application layer and a data layer.', 'msa-simple',
      ['Typical monolithic applications consist of different layers: a presentation layer, an application layer, and a data layer.']), ['multi-tier', 'three-tier']),
  t('rto', 'Recovery time objective (RTO)',
    b('The maximum acceptable delay between the interruption of service and restoration of service.', 'dr-objectives',
      ['Recovery Time Objective (RTO) is the maximum acceptable delay between the interruption of service and restoration of service.']), ['RTO']),
  t('rpo', 'Recovery point objective (RPO)',
    b('The maximum acceptable amount of time since the last data recovery point.', 'dr-objectives',
      ['Recovery Point Objective (RPO) is the maximum acceptable amount of time since the last data recovery point.']), ['RPO']),
  t('immutable-infrastructure', 'Immutable infrastructure',
    b('A model that mandates that no updates, security patches or configuration changes happen in-place on production workloads: to change anything you deploy replacement resources.', 'waf-immutable',
      ['Immutable infrastructure is a model that mandates that no updates, security patches, or configuration changes happen in-place on production workloads.'])),
  t('ami', 'Amazon Machine Image (AMI)',
    b('An image that provides the software required to set up and boot an Amazon EC2 instance.', 'ami',
      ['An Amazon Machine Image (AMI) is an image that provides the software that is required to set up and boot an Amazon EC2 instance.']), ['AMI']),
  t('cloudformation-stack', 'CloudFormation template and stack',
    b('A template is a text file describing the AWS resources you want; when you use it to create a stack, CloudFormation provisions and configures the resources, and you manage them as a single unit.', 'cfn-what-is',
      ['You create a template that describes all the AWS resources that you want (like Amazon EC2 instances or Amazon RDS DB instances), and CloudFormation takes care of provisioning and configuring those resources for you.',
       'By using CloudFormation, you easily manage a collection of resources as a single unit.']), ['stack', 'template']),
  t('sticky-sessions', 'Sticky sessions (session affinity)',
    b('A load balancer feature that binds a user\'s session to a specific target so all requests from the user during the session go to the same target.', 'alb-target-attrs',
      ['you can use the sticky session feature (also known as session affinity) to enable the load balancer to bind a user\'s session to a specific target.']), ['session affinity']),
  t('loose-coupling', 'Loose coupling',
    b('Designing components so they do not depend on each other directly, typically by going through an intermediate layer such as a queue, stream or workflow, which isolates a failure in one component from affecting another.', 'waf-loose-coupling',
      ['Implementing loose coupling between dependencies isolates a failure in one from impacting another.']), ['loosely coupled']),
];

export default glossary;
