import type { Source } from '../src/content/types.ts';

const aws = (id: string, url: string, title: string): Source => ({ id, url, title, kind: 'aws' });
const azure = (id: string, url: string, title: string): Source => ({ id, url, title, kind: 'azure' });

const D = 'https://docs.aws.amazon.com';
const L = 'https://learn.microsoft.com/en-us/azure';

/** Every page cited by the notes, once. Ids are stable; `npm run check:links` verifies each URL, anchor and quote. */
const sources: Source[] = [
  // Exam guide and Well-Architected
  aws('exam-guide', `${D}/aws-certification/latest/solutions-architect-associate-03/solutions-architect-associate-03.html`, 'AWS Certified Solutions Architect - Associate (SAA-C03) exam guide'),
  aws('waf-pillars', `${D}/wellarchitected/latest/framework/the-pillars-of-the-framework.html`, 'AWS Well-Architected Framework: The pillars of the framework'),
  aws('waf-security', `${D}/wellarchitected/latest/framework/security.html`, 'AWS Well-Architected Framework: Security'),
  aws('waf-reliability', `${D}/wellarchitected/latest/framework/reliability.html`, 'AWS Well-Architected Framework: Reliability'),
  aws('waf-performance', `${D}/wellarchitected/latest/framework/performance-efficiency.html`, 'AWS Well-Architected Framework: Performance efficiency'),
  aws('waf-cost', `${D}/wellarchitected/latest/framework/cost-optimization.html`, 'AWS Well-Architected Framework: Cost optimization'),
  aws('waf-opex', `${D}/wellarchitected/latest/framework/operational-excellence.html`, 'AWS Well-Architected Framework: Operational excellence'),
  aws('waf-sustainability', `${D}/wellarchitected/latest/framework/sustainability.html`, 'AWS Well-Architected Framework: Sustainability'),
  aws('waf-tool', 'https://aws.amazon.com/well-architected-tool/', 'AWS Well-Architected Tool'),
  aws('lambda-welcome', `${D}/lambda/latest/dg/welcome.html`, 'What is AWS Lambda?'),

  // Account basics and cost visibility
  aws('iam-root-user', `${D}/IAM/latest/UserGuide/id_root-user.html`, 'AWS account root user'),
  aws('iam-mfa', `${D}/IAM/latest/UserGuide/id_credentials_mfa.html`, 'AWS Multi-factor authentication in IAM'),
  aws('iam-best-practices', `${D}/IAM/latest/UserGuide/best-practices.html`, 'Security best practices in IAM'),
  aws('budgets-managing', `${D}/cost-management/latest/userguide/budgets-managing-costs.html`, 'Managing your costs with AWS Budgets'),

  // Networking basics
  aws('vpc-cidr-blocks', `${D}/vpc/latest/userguide/vpc-cidr-blocks.html`, 'VPC CIDR blocks'),
  aws('vpc-subnet-sizing', `${D}/vpc/latest/userguide/subnet-sizing.html`, 'Subnet CIDR blocks'),
  aws('vpc-sg-rules', `${D}/vpc/latest/userguide/security-group-rules.html`, 'Security group rules'),

  // Monitoring and audit
  aws('cw-what-is', `${D}/AmazonCloudWatch/latest/monitoring/WhatIsCloudWatch.html`, 'What is Amazon CloudWatch?'),
  aws('cw-concepts', `${D}/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html`, 'CloudWatch metrics concepts'),
  aws('cw-alarms', `${D}/AmazonCloudWatch/latest/monitoring/CloudWatch_Alarms.html`, 'Using Amazon CloudWatch alarms'),
  aws('cwl-what-is', `${D}/AmazonCloudWatch/latest/logs/WhatIsCloudWatchLogs.html`, 'What is Amazon CloudWatch Logs?'),
  aws('cwl-concepts', `${D}/AmazonCloudWatch/latest/logs/CloudWatchLogsConcepts.html`, 'CloudWatch Logs concepts'),
  aws('cloudtrail-what-is', `${D}/awscloudtrail/latest/userguide/cloudtrail-user-guide.html`, 'What is AWS CloudTrail?'),
  aws('cloudtrail-concepts', `${D}/awscloudtrail/latest/userguide/cloudtrail-concepts.html`, 'CloudTrail concepts'),
  aws('config-what-is', `${D}/config/latest/developerguide/WhatIsConfig.html`, 'What is AWS Config?'),
  aws('config-rules', `${D}/config/latest/developerguide/evaluate-config.html`, 'Evaluating resources with AWS Config rules'),

  // IAM, Organizations and identity (Citadel 1.1)
  aws('iam-intro', `${D}/IAM/latest/UserGuide/introduction.html`, 'What is IAM?'),
  aws('iam-users', `${D}/IAM/latest/UserGuide/id_users.html`, 'IAM users'),
  aws('iam-groups', `${D}/IAM/latest/UserGuide/id_groups.html`, 'IAM user groups'),
  aws('iam-roles', `${D}/IAM/latest/UserGuide/id_roles.html`, 'IAM roles'),
  aws('iam-policies', `${D}/IAM/latest/UserGuide/access_policies.html`, 'Policies and permissions in IAM'),
  aws('iam-managed-inline', `${D}/IAM/latest/UserGuide/access_policies_managed-vs-inline.html`, 'Managed policies and inline policies'),
  aws('iam-eval-logic', `${D}/IAM/latest/UserGuide/reference_policies_evaluation-logic.html`, 'Policy evaluation logic'),
  aws('iam-el-effect', `${D}/IAM/latest/UserGuide/reference_policies_elements_effect.html`, 'IAM JSON policy elements: Effect'),
  aws('iam-el-principal', `${D}/IAM/latest/UserGuide/reference_policies_elements_principal.html`, 'AWS JSON policy elements: Principal'),
  aws('iam-el-version', `${D}/IAM/latest/UserGuide/reference_policies_elements_version.html`, 'IAM JSON policy elements: Version'),
  aws('iam-el-sid', `${D}/IAM/latest/UserGuide/reference_policies_elements_sid.html`, 'IAM JSON policy elements: Sid'),
  aws('iam-el-action', `${D}/IAM/latest/UserGuide/reference_policies_elements_action.html`, 'IAM JSON policy elements: Action'),
  aws('iam-el-resource', `${D}/IAM/latest/UserGuide/reference_policies_elements_resource.html`, 'IAM JSON policy elements: Resource'),
  aws('iam-el-condition', `${D}/IAM/latest/UserGuide/reference_policies_elements_condition.html`, 'IAM JSON policy elements: Condition'),
  aws('iam-boundaries', `${D}/IAM/latest/UserGuide/access_policies_boundaries.html`, 'Permissions boundaries for IAM entities'),
  aws('iam-identity-vs-resource', `${D}/IAM/latest/UserGuide/access_policies_identity-vs-resource.html`, 'Identity-based policies and resource-based policies'),
  aws('iam-cross-account', `${D}/IAM/latest/UserGuide/access_policies-cross-account-resource-access.html`, 'Cross account resource access in IAM'),
  aws('iam-cross-account-role', `${D}/IAM/latest/UserGuide/id_roles_create_for-user.html`, 'Create a role to delegate permissions to an IAM user'),
  aws('iam-account-switch', `${D}/IAM/latest/UserGuide/id_roles_common-scenarios_aws-accounts.html`, 'Access for an IAM user in another AWS account that you own'),
  aws('iam-switch-role', `${D}/IAM/latest/UserGuide/id_roles_use_switch-role-console.html`, 'Switch from a user to an IAM role (console)'),
  aws('iam-temp-creds', `${D}/IAM/latest/UserGuide/id_credentials_temp.html`, 'Temporary security credentials in IAM'),
  aws('iam-saml', `${D}/IAM/latest/UserGuide/id_roles_providers_saml.html`, 'SAML 2.0 federation'),
  aws('lambda-exec-role', `${D}/lambda/latest/dg/lambda-intro-execution-role.html`, 'Defining Lambda function permissions with an execution role'),
  aws('orgs-intro', `${D}/organizations/latest/userguide/orgs_introduction.html`, 'What is AWS Organizations?'),
  aws('orgs-scps', `${D}/organizations/latest/userguide/orgs_manage_policies_scps.html`, 'Service control policies (SCPs)'),
  aws('orgs-scp-eval', `${D}/organizations/latest/userguide/orgs_manage_policies_scps_evaluation.html`, 'SCP evaluation'),
  aws('control-tower', `${D}/controltower/latest/userguide/what-is-control-tower.html`, 'What is AWS Control Tower?'),
  aws('ram-what-is', `${D}/ram/latest/userguide/what-is.html`, 'What is AWS Resource Access Manager?'),
  aws('sso-what-is', `${D}/singlesignon/latest/userguide/what-is.html`, 'What is IAM Identity Center?'),
  aws('sso-ad', `${D}/singlesignon/latest/userguide/manage-your-identity-source-ad.html`, 'IAM Identity Center: Microsoft AD directory'),
  aws('ds-what-is', `${D}/directoryservice/latest/admin-guide/what_is.html`, 'What is AWS Directory Service?'),
  aws('s3-bucket-policy-examples', `${D}/AmazonS3/latest/userguide/example-bucket-policies.html`, 'Bucket policy examples'),
  aws('cf-oac', `${D}/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html`, 'Restrict access to an Amazon S3 origin (CloudFront)'),
  aws('fault-isolation-az', `${D}/whitepapers/latest/aws-fault-isolation-boundaries/availability-zones.html`, 'AWS Fault Isolation Boundaries: Availability Zones'),
  aws('regions-and-azs', `${D}/global-infrastructure/latest/regions/aws-regions.html`, 'AWS Regions'),
  aws('global-infra', 'https://aws.amazon.com/about-aws/global-infrastructure/regions_az/', 'AWS Regions and Availability Zones'),
  aws('global-infra-overview', 'https://aws.amazon.com/about-aws/global-infrastructure/', 'AWS Global Infrastructure'),
  aws('shared-responsibility', 'https://aws.amazon.com/compliance/shared-responsibility-model/', 'Shared Responsibility Model'),

  aws('orgs-scp-examples', `${D}/organizations/latest/userguide/orgs_manage_policies_scps_examples.html`, 'Service control policy examples'),
  aws('orgs-policies-attach', `${D}/organizations/latest/userguide/orgs_policies_attach.html`, 'Attaching and detaching policies in AWS Organizations'),
  aws('control-tower-controls', `${D}/controltower/latest/controlreference/controls.html`, 'AWS Control Tower controls'),
  // VPC (Citadel 1.2)
  aws('vpc-how-it-works', `${D}/vpc/latest/userguide/how-it-works.html`, 'How Amazon VPC works'),
  aws('vpc-security-groups', `${D}/vpc/latest/userguide/vpc-security-groups.html`, 'Control traffic to your AWS resources using security groups'),
  aws('vpc-nacls', `${D}/vpc/latest/userguide/vpc-network-acls.html`, 'Control subnet traffic with network access control lists'),
  aws('vpc-default-nacl', `${D}/vpc/latest/userguide/default-network-acl.html`, 'Default network ACL for a VPC'),
  aws('vpc-route-tables', `${D}/vpc/latest/userguide/VPC_Route_Tables.html`, 'Configure route tables'),
  aws('vpc-route-options', `${D}/vpc/latest/userguide/route-table-options.html`, 'Example routing options'),
  aws('vpc-route-priority', `${D}/vpc/latest/userguide/route-tables-priority.html`, 'How route priority works'),
  aws('vpc-igw', `${D}/vpc/latest/userguide/VPC_Internet_Gateway.html`, 'Enable internet access for a VPC using an internet gateway'),
  aws('vpc-nat-gateway', `${D}/vpc/latest/userguide/vpc-nat-gateway.html`, 'NAT gateways'),
  aws('vpc-nat-basics', `${D}/vpc/latest/userguide/nat-gateway-basics.html`, 'NAT gateway basics'),
  aws('vpc-subnets', `${D}/vpc/latest/userguide/configure-subnets.html`, 'Subnets for your VPC'),
  // Security services and app credentials (Citadel 1.2)
  aws('waf-what-is', `${D}/waf/latest/developerguide/waf-chapter.html`, 'AWS WAF'),
  aws('waf-how-works', `${D}/waf/latest/developerguide/how-aws-waf-works.html`, 'How AWS WAF works'),
  aws('waf-sqli', `${D}/waf/latest/developerguide/waf-rule-statement-type-sqli-match.html`, 'SQL injection attack rule statement'),
  aws('shield-overview', `${D}/waf/latest/developerguide/ddos-overview.html`, 'How AWS Shield and Shield Advanced work'),
  aws('shield-standard', `${D}/waf/latest/developerguide/ddos-standard-summary.html`, 'AWS Shield Standard overview'),
  aws('shield-advanced', `${D}/waf/latest/developerguide/ddos-advanced-summary.html`, 'AWS Shield Advanced overview'),
  aws('guardduty', `${D}/guardduty/latest/ug/what-is-guardduty.html`, 'What is Amazon GuardDuty?'),
  aws('guardduty-data', `${D}/guardduty/latest/ug/guardduty_data-sources.html`, 'GuardDuty foundational data sources'),
  aws('macie', `${D}/macie/latest/user/what-is-macie.html`, 'What is Amazon Macie?'),
  aws('inspector', `${D}/inspector/latest/user/what-is-inspector.html`, 'What is Amazon Inspector?'),
  aws('security-hub', `${D}/securityhub/latest/userguide/what-is-securityhub.html`, 'Introduction to AWS Security Hub CSPM'),
  aws('detective', 'https://aws.amazon.com/detective/', 'Amazon Detective'),
  aws('network-firewall', `${D}/network-firewall/latest/developerguide/what-is-aws-network-firewall.html`, 'What is AWS Network Firewall?'),
  aws('firewall-manager', `${D}/waf/latest/developerguide/fms-chapter.html`, 'AWS Firewall Manager'),
  aws('cognito-what-is', `${D}/cognito/latest/developerguide/what-is-amazon-cognito.html`, 'What is Amazon Cognito?'),
  aws('cognito-user-pools', `${D}/cognito/latest/developerguide/cognito-user-pools.html`, 'Authenticating users with Amazon Cognito user pools'),
  aws('cognito-identity-pools', `${D}/cognito/latest/developerguide/cognito-identity.html`, 'Amazon Cognito identity pools'),
  aws('secrets-intro', `${D}/secretsmanager/latest/userguide/intro.html`, 'What is AWS Secrets Manager?'),
  aws('secrets-rotation', `${D}/secretsmanager/latest/userguide/rotating-secrets.html`, 'Rotate AWS Secrets Manager secrets'),
  aws('ssm-parameter-store', `${D}/systems-manager/latest/userguide/systems-manager-parameter-store.html`, 'AWS Systems Manager Parameter Store'),
  // Endpoints and external connections (Citadel 1.2)
  aws('privatelink-what-is', `${D}/vpc/latest/privatelink/what-is-privatelink.html`, 'What is AWS PrivateLink?'),
  aws('privatelink-concepts', `${D}/vpc/latest/privatelink/concepts.html`, 'AWS PrivateLink concepts'),
  aws('vpce-gateway', `${D}/vpc/latest/privatelink/gateway-endpoints.html`, 'Gateway endpoints'),
  aws('vpce-gateway-s3', `${D}/vpc/latest/privatelink/vpc-endpoints-s3.html`, 'Gateway endpoints for Amazon S3'),
  aws('vpce-interface', `${D}/vpc/latest/privatelink/create-interface-endpoint.html`, 'Create an interface VPC endpoint'),
  aws('service-endpoints', `${D}/general/latest/gr/rande.html`, 'AWS service endpoints'),
  aws('s2s-vpn', `${D}/vpn/latest/s2svpn/VPC_VPN.html`, 'What is AWS Site-to-Site VPN?'),
  aws('s2s-vpn-how', `${D}/vpn/latest/s2svpn/how_it_works.html`, 'How AWS Site-to-Site VPN works'),
  aws('client-vpn', `${D}/vpn/latest/clientvpn-admin/what-is.html`, 'What is AWS Client VPN?'),
  aws('dx-what-is', `${D}/directconnect/latest/UserGuide/Welcome.html`, 'What is Direct Connect?'),
  aws('connectivity-dx', `${D}/whitepapers/latest/aws-vpc-connectivity-options/aws-direct-connect.html`, 'Amazon VPC connectivity options: AWS Direct Connect'),
  aws('connectivity-vpn', `${D}/whitepapers/latest/aws-vpc-connectivity-options/aws-site-to-site-vpn.html`, 'Amazon VPC connectivity options: AWS Site-to-Site VPN'),
  // Encryption and key management (Citadel 1.3)
  aws('kms-overview', `${D}/kms/latest/developerguide/overview.html`, 'AWS Key Management Service'),
  aws('kms-concepts', `${D}/kms/latest/developerguide/concepts.html`, 'AWS KMS keys'),
  aws('kms-key-policies', `${D}/kms/latest/developerguide/key-policies.html`, 'Key policies in AWS KMS'),
  aws('kms-default-key-policy', `${D}/kms/latest/developerguide/key-policy-default.html`, 'Default key policy'),
  aws('kms-rotation', `${D}/kms/latest/developerguide/rotate-keys.html`, 'Rotate AWS KMS keys'),
  aws('kms-key-stores', `${D}/kms/latest/developerguide/key-store-overview.html`, 'KMS key stores'),
  aws('cloudhsm', `${D}/cloudhsm/latest/userguide/introduction.html`, 'What is AWS CloudHSM?'),
  aws('s3-sse', `${D}/AmazonS3/latest/userguide/serv-side-encryption.html`, 'Protecting data with server-side encryption'),
  aws('s3-sse-s3', `${D}/AmazonS3/latest/userguide/UsingServerSideEncryption.html`, 'Using server-side encryption with Amazon S3 managed keys (SSE-S3)'),
  aws('s3-sse-s3-specify', `${D}/AmazonS3/latest/userguide/specifying-s3-encryption.html`, 'Specifying server-side encryption with Amazon S3 managed keys (SSE-S3)'),
  aws('s3-sse-kms', `${D}/AmazonS3/latest/userguide/UsingKMSEncryption.html`, 'Using server-side encryption with AWS KMS keys (SSE-KMS)'),
  aws('s3-sse-c', `${D}/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html`, 'Using server-side encryption with customer-provided keys (SSE-C)'),
  aws('acm-overview', `${D}/acm/latest/userguide/acm-overview.html`, 'What is AWS Certificate Manager?'),
  aws('acm-renewal', `${D}/acm/latest/userguide/managed-renewal.html`, 'Managed certificate renewal in AWS Certificate Manager'),
  aws('acm-services', `${D}/acm/latest/userguide/acm-services.html`, 'ACM: managed automation with integrated services'),
  aws('cf-https-requirements', `${D}/AmazonCloudFront/latest/DeveloperGuide/cnames-and-https-requirements.html`, 'Requirements for using SSL/TLS certificates with CloudFront'),
  aws('alb-https-listener', `${D}/elasticloadbalancing/latest/application/create-https-listener.html`, 'Create an HTTPS listener for your Application Load Balancer'),
  // Backup, retention and compliance (Citadel 1.3)
  aws('backup-what-is', `${D}/aws-backup/latest/devguide/whatisbackup.html`, 'What is AWS Backup?'),
  aws('backup-plans', `${D}/aws-backup/latest/devguide/about-backup-plans.html`, 'Backup plans'),
  aws('backup-vault-lock', `${D}/aws-backup/latest/devguide/vault-lock.html`, 'AWS Backup Vault Lock'),
  aws('s3-versioning', `${D}/AmazonS3/latest/userguide/Versioning.html`, 'Retaining multiple versions of objects with S3 Versioning'),
  aws('s3-replication', `${D}/AmazonS3/latest/userguide/replication.html`, 'Replicating objects within and across Regions'),
  aws('s3-object-lock', `${D}/AmazonS3/latest/userguide/object-lock.html`, 'Locking objects with Object Lock'),
  aws('s3-lifecycle', `${D}/AmazonS3/latest/userguide/object-lifecycle-mgmt.html`, 'Managing the lifecycle of objects'),
  aws('s3-block-public-access', `${D}/AmazonS3/latest/userguide/access-control-block-public-access.html`, 'Blocking public access to your Amazon S3 storage'),
  aws('macie-discovery', `${D}/macie/latest/user/data-classification.html`, 'Discovering sensitive data with Macie'),
  aws('artifact', `${D}/artifact/latest/ug/what-is-aws-artifact.html`, 'What is AWS Artifact?'),
  aws('config-conformance-packs', `${D}/config/latest/developerguide/conformance-packs.html`, 'Conformance Packs for AWS Config'),
  aws('lake-formation', `${D}/lake-formation/latest/dg/what-is-lake-formation.html`, 'What is AWS Lake Formation?'),
  aws('sagemaker-what-is', `${D}/sagemaker/latest/dg/whatis.html`, 'What is Amazon SageMaker AI?'),
  aws('quick-what-is', `${D}/quick/latest/userguide/what-is.html`, 'What is Amazon Quick?'),

  // Microsoft Learn (Azure side of the Azure notes only)
  azure('learn-hub', `${L}/architecture/aws-professional/`, 'Azure for AWS professionals: service comparison'),
  azure('learn-compute', `${L}/architecture/aws-professional/compute`, 'Compute services on Azure and AWS'),
  azure('learn-storage', `${L}/architecture/aws-professional/storage`, 'Compare storage on Azure and AWS'),
  azure('learn-networking', `${L}/architecture/aws-professional/networking`, 'Compare AWS and Azure networking options'),
  azure('learn-databases', `${L}/architecture/aws-professional/databases`, 'Database services on Azure and AWS'),
  azure('learn-zones', `${L}/reliability/availability-zones-overview`, 'Azure availability zones overview'),
  azure('learn-shared-responsibility', `${L}/security/fundamentals/shared-responsibility`, 'Shared responsibility in the cloud (Azure)'),
  azure('learn-storage-redundancy', `${L}/storage/common/storage-redundancy`, 'Azure Storage redundancy'),
  azure('learn-analytics', `${L}/architecture/aws-professional/analytics`, 'Analytics services on Azure and AWS'),
];

export default sources;
