import type { Source } from '../src/content/types.ts';

const aws = (id: string, url: string, title: string): Source => ({ id, url, title, kind: 'aws' });
const azure = (id: string, url: string, title: string): Source => ({ id, url, title, kind: 'azure' });

const D = 'https://docs.aws.amazon.com';
const L = 'https://learn.microsoft.com/en-us/azure';

/** Every page cited by the notes, once. Ids are stable; `npm run check:links` verifies each URL, anchor and quote. */
const sources: Source[] = [
  // Exam guide and Well-Architected
  aws('exam-guide', `${D}/aws-certification/latest/solutions-architect-associate-03/solutions-architect-associate-03.html`, 'AWS Certified Solutions Architect - Associate (SAA-C03) exam guide'),
  aws('waf-pillars', `${D}/wellarchitected/latest/framework/the-pillars-of-the-framework.html`, 'AWS Well-Architected Framework: The pillars of the framework'),
  aws('waf-security', `${D}/wellarchitected/latest/framework/security.html`, 'AWS Well-Architected Framework: Security'),
  aws('waf-reliability', `${D}/wellarchitected/latest/framework/reliability.html`, 'AWS Well-Architected Framework: Reliability'),
  aws('waf-performance', `${D}/wellarchitected/latest/framework/performance-efficiency.html`, 'AWS Well-Architected Framework: Performance efficiency'),
  aws('waf-cost', `${D}/wellarchitected/latest/framework/cost-optimization.html`, 'AWS Well-Architected Framework: Cost optimization'),
  aws('waf-opex', `${D}/wellarchitected/latest/framework/operational-excellence.html`, 'AWS Well-Architected Framework: Operational excellence'),
  aws('waf-tool', 'https://aws.amazon.com/well-architected-tool/', 'AWS Well-Architected Tool'),
  aws('lambda-welcome', `${D}/lambda/latest/dg/welcome.html`, 'What is AWS Lambda?'),

  // Account basics and cost visibility
  aws('iam-root-user', `${D}/IAM/latest/UserGuide/id_root-user.html`, 'AWS account root user'),
  aws('iam-mfa', `${D}/IAM/latest/UserGuide/id_credentials_mfa.html`, 'AWS Multi-factor authentication in IAM'),
  aws('iam-best-practices', `${D}/IAM/latest/UserGuide/best-practices.html`, 'Security best practices in IAM'),
  aws('budgets-managing', `${D}/cost-management/latest/userguide/budgets-managing-costs.html`, 'Managing your costs with AWS Budgets'),

  // Networking basics
  aws('vpc-cidr-blocks', `${D}/vpc/latest/userguide/vpc-cidr-blocks.html`, 'VPC CIDR blocks'),
  aws('vpc-subnet-sizing', `${D}/vpc/latest/userguide/subnet-sizing.html`, 'Subnet CIDR blocks'),
  aws('vpc-sg-rules', `${D}/vpc/latest/userguide/security-group-rules.html`, 'Security group rules'),

  // Monitoring and audit
  aws('cw-what-is', `${D}/AmazonCloudWatch/latest/monitoring/WhatIsCloudWatch.html`, 'What is Amazon CloudWatch?'),
  aws('cw-concepts', `${D}/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html`, 'CloudWatch metrics concepts'),
  aws('cw-alarms', `${D}/AmazonCloudWatch/latest/monitoring/CloudWatch_Alarms.html`, 'Using Amazon CloudWatch alarms'),
  aws('cwl-what-is', `${D}/AmazonCloudWatch/latest/logs/WhatIsCloudWatchLogs.html`, 'What is Amazon CloudWatch Logs?'),
  aws('cwl-concepts', `${D}/AmazonCloudWatch/latest/logs/CloudWatchLogsConcepts.html`, 'CloudWatch Logs concepts'),
  aws('cloudtrail-what-is', `${D}/awscloudtrail/latest/userguide/cloudtrail-user-guide.html`, 'What is AWS CloudTrail?'),
  aws('cloudtrail-concepts', `${D}/awscloudtrail/latest/userguide/cloudtrail-concepts.html`, 'CloudTrail concepts'),
  aws('config-what-is', `${D}/config/latest/developerguide/WhatIsConfig.html`, 'What is AWS Config?'),
  aws('config-rules', `${D}/config/latest/developerguide/evaluate-config.html`, 'Evaluating resources with AWS Config rules'),

  // IAM, Organizations and identity (Citadel 1.1)
  aws('iam-intro', `${D}/IAM/latest/UserGuide/introduction.html`, 'What is IAM?'),
  aws('iam-users', `${D}/IAM/latest/UserGuide/id_users.html`, 'IAM users'),
  aws('iam-groups', `${D}/IAM/latest/UserGuide/id_groups.html`, 'IAM user groups'),
  aws('iam-roles', `${D}/IAM/latest/UserGuide/id_roles.html`, 'IAM roles'),
  aws('iam-policies', `${D}/IAM/latest/UserGuide/access_policies.html`, 'Policies and permissions in IAM'),
  aws('iam-managed-inline', `${D}/IAM/latest/UserGuide/access_policies_managed-vs-inline.html`, 'Managed policies and inline policies'),
  aws('iam-eval-logic', `${D}/IAM/latest/UserGuide/reference_policies_evaluation-logic.html`, 'Policy evaluation logic'),
  aws('iam-el-effect', `${D}/IAM/latest/UserGuide/reference_policies_elements_effect.html`, 'IAM JSON policy elements: Effect'),
  aws('iam-el-principal', `${D}/IAM/latest/UserGuide/reference_policies_elements_principal.html`, 'AWS JSON policy elements: Principal'),
  aws('iam-el-version', `${D}/IAM/latest/UserGuide/reference_policies_elements_version.html`, 'IAM JSON policy elements: Version'),
  aws('iam-el-sid', `${D}/IAM/latest/UserGuide/reference_policies_elements_sid.html`, 'IAM JSON policy elements: Sid'),
  aws('iam-el-action', `${D}/IAM/latest/UserGuide/reference_policies_elements_action.html`, 'IAM JSON policy elements: Action'),
  aws('iam-el-resource', `${D}/IAM/latest/UserGuide/reference_policies_elements_resource.html`, 'IAM JSON policy elements: Resource'),
  aws('iam-el-condition', `${D}/IAM/latest/UserGuide/reference_policies_elements_condition.html`, 'IAM JSON policy elements: Condition'),
  aws('iam-boundaries', `${D}/IAM/latest/UserGuide/access_policies_boundaries.html`, 'Permissions boundaries for IAM entities'),
  aws('iam-identity-vs-resource', `${D}/IAM/latest/UserGuide/access_policies_identity-vs-resource.html`, 'Identity-based policies and resource-based policies'),
  aws('iam-cross-account', `${D}/IAM/latest/UserGuide/access_policies-cross-account-resource-access.html`, 'Cross account resource access in IAM'),
  aws('iam-cross-account-role', `${D}/IAM/latest/UserGuide/id_roles_create_for-user.html`, 'Create a role to delegate permissions to an IAM user'),
  aws('iam-account-switch', `${D}/IAM/latest/UserGuide/id_roles_common-scenarios_aws-accounts.html`, 'Access for an IAM user in another AWS account that you own'),
  aws('iam-switch-role', `${D}/IAM/latest/UserGuide/id_roles_use_switch-role-console.html`, 'Switch from a user to an IAM role (console)'),
  aws('iam-temp-creds', `${D}/IAM/latest/UserGuide/id_credentials_temp.html`, 'Temporary security credentials in IAM'),
  aws('iam-saml', `${D}/IAM/latest/UserGuide/id_roles_providers_saml.html`, 'SAML 2.0 federation'),
  aws('lambda-exec-role', `${D}/lambda/latest/dg/lambda-intro-execution-role.html`, 'Defining Lambda function permissions with an execution role'),
  aws('orgs-intro', `${D}/organizations/latest/userguide/orgs_introduction.html`, 'What is AWS Organizations?'),
  aws('orgs-scps', `${D}/organizations/latest/userguide/orgs_manage_policies_scps.html`, 'Service control policies (SCPs)'),
  aws('orgs-scp-eval', `${D}/organizations/latest/userguide/orgs_manage_policies_scps_evaluation.html`, 'SCP evaluation'),
  aws('control-tower', `${D}/controltower/latest/userguide/what-is-control-tower.html`, 'What is AWS Control Tower?'),
  aws('ram-what-is', `${D}/ram/latest/userguide/what-is.html`, 'What is AWS Resource Access Manager?'),
  aws('sso-what-is', `${D}/singlesignon/latest/userguide/what-is.html`, 'What is IAM Identity Center?'),
  aws('sso-ad', `${D}/singlesignon/latest/userguide/manage-your-identity-source-ad.html`, 'IAM Identity Center: Microsoft AD directory'),
  aws('ds-what-is', `${D}/directoryservice/latest/admin-guide/what_is.html`, 'What is AWS Directory Service?'),
  aws('cf-oac', `${D}/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html`, 'Restrict access to an Amazon S3 origin (CloudFront)'),
  aws('fault-isolation-az', `${D}/whitepapers/latest/aws-fault-isolation-boundaries/availability-zones.html`, 'AWS Fault Isolation Boundaries: Availability Zones'),
  aws('regions-and-azs', `${D}/global-infrastructure/latest/regions/aws-regions.html`, 'AWS Regions'),
  aws('global-infra', 'https://aws.amazon.com/about-aws/global-infrastructure/regions_az/', 'AWS Regions and Availability Zones'),
  aws('global-infra-overview', 'https://aws.amazon.com/about-aws/global-infrastructure/', 'AWS Global Infrastructure'),
  aws('shared-responsibility', 'https://aws.amazon.com/compliance/shared-responsibility-model/', 'Shared Responsibility Model'),

  aws('orgs-scp-examples', `${D}/organizations/latest/userguide/orgs_manage_policies_scps_examples.html`, 'Service control policy examples'),
  aws('orgs-policies-attach', `${D}/organizations/latest/userguide/orgs_policies_attach.html`, 'Attaching and detaching policies in AWS Organizations'),
  aws('control-tower-controls', `${D}/controltower/latest/controlreference/controls.html`, 'AWS Control Tower controls'),
  // VPC (Citadel 1.2)
  aws('vpc-how-it-works', `${D}/vpc/latest/userguide/how-it-works.html`, 'How Amazon VPC works'),
  aws('vpc-security-groups', `${D}/vpc/latest/userguide/vpc-security-groups.html`, 'Control traffic to your AWS resources using security groups'),
  aws('vpc-nacls', `${D}/vpc/latest/userguide/vpc-network-acls.html`, 'Control subnet traffic with network access control lists'),
  aws('vpc-default-nacl', `${D}/vpc/latest/userguide/default-network-acl.html`, 'Default network ACL for a VPC'),
  aws('vpc-route-tables', `${D}/vpc/latest/userguide/VPC_Route_Tables.html`, 'Configure route tables'),
  aws('vpc-route-options', `${D}/vpc/latest/userguide/route-table-options.html`, 'Example routing options'),
  aws('vpc-route-priority', `${D}/vpc/latest/userguide/route-tables-priority.html`, 'How route priority works'),
  aws('vpc-igw', `${D}/vpc/latest/userguide/VPC_Internet_Gateway.html`, 'Enable internet access for a VPC using an internet gateway'),
  aws('vpc-nat-gateway', `${D}/vpc/latest/userguide/vpc-nat-gateway.html`, 'NAT gateways'),
  aws('vpc-nat-basics', `${D}/vpc/latest/userguide/nat-gateway-basics.html`, 'NAT gateway basics'),
  aws('vpc-subnets', `${D}/vpc/latest/userguide/configure-subnets.html`, 'Subnets for your VPC'),
  // Security services and app credentials (Citadel 1.2)
  aws('waf-what-is', `${D}/waf/latest/developerguide/waf-chapter.html`, 'AWS WAF'),
  aws('waf-how-works', `${D}/waf/latest/developerguide/how-aws-waf-works.html`, 'How AWS WAF works'),
  aws('waf-sqli', `${D}/waf/latest/developerguide/waf-rule-statement-type-sqli-match.html`, 'SQL injection attack rule statement'),
  aws('shield-overview', `${D}/waf/latest/developerguide/ddos-overview.html`, 'How AWS Shield and Shield Advanced work'),
  aws('shield-standard', `${D}/waf/latest/developerguide/ddos-standard-summary.html`, 'AWS Shield Standard overview'),
  aws('shield-advanced', `${D}/waf/latest/developerguide/ddos-advanced-summary.html`, 'AWS Shield Advanced overview'),
  aws('guardduty', `${D}/guardduty/latest/ug/what-is-guardduty.html`, 'What is Amazon GuardDuty?'),
  aws('guardduty-data', `${D}/guardduty/latest/ug/guardduty_data-sources.html`, 'GuardDuty foundational data sources'),
  aws('macie', `${D}/macie/latest/user/what-is-macie.html`, 'What is Amazon Macie?'),
  aws('inspector', `${D}/inspector/latest/user/what-is-inspector.html`, 'What is Amazon Inspector?'),
  aws('security-hub', `${D}/securityhub/latest/userguide/what-is-securityhub.html`, 'Introduction to AWS Security Hub CSPM'),
  aws('detective', 'https://aws.amazon.com/detective/', 'Amazon Detective'),
  aws('network-firewall', `${D}/network-firewall/latest/developerguide/what-is-aws-network-firewall.html`, 'What is AWS Network Firewall?'),
  aws('firewall-manager', `${D}/waf/latest/developerguide/fms-chapter.html`, 'AWS Firewall Manager'),
  aws('cognito-what-is', `${D}/cognito/latest/developerguide/what-is-amazon-cognito.html`, 'What is Amazon Cognito?'),
  aws('cognito-user-pools', `${D}/cognito/latest/developerguide/cognito-user-pools.html`, 'Authenticating users with Amazon Cognito user pools'),
  aws('cognito-identity-pools', `${D}/cognito/latest/developerguide/cognito-identity.html`, 'Amazon Cognito identity pools'),
  aws('secrets-intro', `${D}/secretsmanager/latest/userguide/intro.html`, 'What is AWS Secrets Manager?'),
  aws('secrets-rotation', `${D}/secretsmanager/latest/userguide/rotating-secrets.html`, 'Rotate AWS Secrets Manager secrets'),
  aws('ssm-parameter-store', `${D}/systems-manager/latest/userguide/systems-manager-parameter-store.html`, 'AWS Systems Manager Parameter Store'),
  // Endpoints and external connections (Citadel 1.2)
  aws('privatelink-what-is', `${D}/vpc/latest/privatelink/what-is-privatelink.html`, 'What is AWS PrivateLink?'),
  aws('privatelink-concepts', `${D}/vpc/latest/privatelink/concepts.html`, 'AWS PrivateLink concepts'),
  aws('vpce-gateway', `${D}/vpc/latest/privatelink/gateway-endpoints.html`, 'Gateway endpoints'),
  aws('vpce-gateway-s3', `${D}/vpc/latest/privatelink/vpc-endpoints-s3.html`, 'Gateway endpoints for Amazon S3'),
  aws('vpce-interface', `${D}/vpc/latest/privatelink/create-interface-endpoint.html`, 'Create an interface VPC endpoint'),
  aws('service-endpoints', `${D}/general/latest/gr/rande.html`, 'AWS service endpoints'),
  aws('s2s-vpn', `${D}/vpn/latest/s2svpn/VPC_VPN.html`, 'What is AWS Site-to-Site VPN?'),
  aws('s2s-vpn-how', `${D}/vpn/latest/s2svpn/how_it_works.html`, 'How AWS Site-to-Site VPN works'),
  aws('client-vpn', `${D}/vpn/latest/clientvpn-admin/what-is.html`, 'What is AWS Client VPN?'),
  aws('dx-what-is', `${D}/directconnect/latest/UserGuide/Welcome.html`, 'What is Direct Connect?'),
  aws('connectivity-dx', `${D}/whitepapers/latest/aws-vpc-connectivity-options/aws-direct-connect.html`, 'Amazon VPC connectivity options: AWS Direct Connect'),
  aws('connectivity-vpn', `${D}/whitepapers/latest/aws-vpc-connectivity-options/aws-site-to-site-vpn.html`, 'Amazon VPC connectivity options: AWS Site-to-Site VPN'),
  // Encryption and key management (Citadel 1.3)
  aws('kms-overview', `${D}/kms/latest/developerguide/overview.html`, 'AWS Key Management Service'),
  aws('kms-concepts', `${D}/kms/latest/developerguide/concepts.html`, 'AWS KMS keys'),
  aws('kms-key-policies', `${D}/kms/latest/developerguide/key-policies.html`, 'Key policies in AWS KMS'),
  aws('kms-default-key-policy', `${D}/kms/latest/developerguide/key-policy-default.html`, 'Default key policy'),
  aws('kms-rotation', `${D}/kms/latest/developerguide/rotate-keys.html`, 'Rotate AWS KMS keys'),
  aws('kms-key-stores', `${D}/kms/latest/developerguide/key-store-overview.html`, 'KMS key stores'),
  aws('cloudhsm', `${D}/cloudhsm/latest/userguide/introduction.html`, 'What is AWS CloudHSM?'),
  aws('s3-sse', `${D}/AmazonS3/latest/userguide/serv-side-encryption.html`, 'Protecting data with server-side encryption'),
  aws('s3-sse-s3', `${D}/AmazonS3/latest/userguide/UsingServerSideEncryption.html`, 'Using server-side encryption with Amazon S3 managed keys (SSE-S3)'),
  aws('s3-sse-s3-specify', `${D}/AmazonS3/latest/userguide/specifying-s3-encryption.html`, 'Specifying server-side encryption with Amazon S3 managed keys (SSE-S3)'),
  aws('s3-sse-kms', `${D}/AmazonS3/latest/userguide/UsingKMSEncryption.html`, 'Using server-side encryption with AWS KMS keys (SSE-KMS)'),
  aws('s3-sse-c', `${D}/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html`, 'Using server-side encryption with customer-provided keys (SSE-C)'),
  aws('acm-overview', `${D}/acm/latest/userguide/acm-overview.html`, 'What is AWS Certificate Manager?'),
  aws('acm-renewal', `${D}/acm/latest/userguide/managed-renewal.html`, 'Managed certificate renewal in AWS Certificate Manager'),
  aws('acm-services', `${D}/acm/latest/userguide/acm-services.html`, 'ACM: managed automation with integrated services'),
  aws('cf-https-requirements', `${D}/AmazonCloudFront/latest/DeveloperGuide/cnames-and-https-requirements.html`, 'Requirements for using SSL/TLS certificates with CloudFront'),
  aws('alb-https-listener', `${D}/elasticloadbalancing/latest/application/create-https-listener.html`, 'Create an HTTPS listener for your Application Load Balancer'),
  // Backup, retention and compliance (Citadel 1.3)
  aws('backup-what-is', `${D}/aws-backup/latest/devguide/whatisbackup.html`, 'What is AWS Backup?'),
  aws('backup-plans', `${D}/aws-backup/latest/devguide/about-backup-plans.html`, 'Backup plans'),
  aws('backup-vault-lock', `${D}/aws-backup/latest/devguide/vault-lock.html`, 'AWS Backup Vault Lock'),
  aws('s3-versioning', `${D}/AmazonS3/latest/userguide/Versioning.html`, 'Retaining multiple versions of objects with S3 Versioning'),
  aws('s3-replication', `${D}/AmazonS3/latest/userguide/replication.html`, 'Replicating objects within and across Regions'),
  aws('s3-object-lock', `${D}/AmazonS3/latest/userguide/object-lock.html`, 'Locking objects with Object Lock'),
  aws('s3-lifecycle', `${D}/AmazonS3/latest/userguide/object-lifecycle-mgmt.html`, 'Managing the lifecycle of objects'),
  aws('s3-block-public-access', `${D}/AmazonS3/latest/userguide/access-control-block-public-access.html`, 'Blocking public access to your Amazon S3 storage'),
  aws('macie-discovery', `${D}/macie/latest/user/data-classification.html`, 'Discovering sensitive data with Macie'),
  aws('artifact', `${D}/artifact/latest/ug/what-is-aws-artifact.html`, 'What is AWS Artifact?'),
  aws('config-conformance-packs', `${D}/config/latest/developerguide/conformance-packs.html`, 'Conformance Packs for AWS Config'),
  aws('lake-formation', `${D}/lake-formation/latest/dg/what-is-lake-formation.html`, 'What is AWS Lake Formation?'),
  // Harbor & Levees (2.1 and 2.2)
  aws('msa-whitepaper', `${D}/whitepapers/latest/microservices-on-aws/microservices-on-aws.html`, 'Implementing Microservices on AWS'),
  aws('eda-overview', 'https://aws.amazon.com/event-driven-architecture/', 'Event-driven architecture'),
  aws('waf-loose-coupling', `${D}/wellarchitected/latest/reliability-pillar/rel_prevent_interaction_failure_loosely_coupled_system.html`, 'REL04-BP02 Implement loosely coupled dependencies'),
  aws('waf-idempotent', `${D}/wellarchitected/latest/reliability-pillar/rel_prevent_interaction_failure_idempotent.html`, 'REL04-BP04 Make mutating operations idempotent'),
  aws('waf-stateless', `${D}/wellarchitected/latest/framework/rel_mitigate_interaction_failure_stateless.html`, 'REL05-BP06 Make systems stateless where possible'),
  aws('sqs-what-is', `${D}/AWSSimpleQueueService/latest/SQSDeveloperGuide/welcome.html`, 'What is Amazon Simple Queue Service?'),
  aws('sns-what-is', `${D}/sns/latest/dg/welcome.html`, 'What is Amazon SNS?'),
  aws('eventbridge-what-is', `${D}/eventbridge/latest/userguide/eb-what-is.html`, 'What is Amazon EventBridge?'),
  aws('kinesis-streams', `${D}/streams/latest/dev/introduction.html`, 'What is Amazon Kinesis Data Streams?'),
  aws('kinesis-consumers', `${D}/streams/latest/dev/building-consumers.html`, 'Read data from Amazon Kinesis Data Streams'),
  aws('firehose', `${D}/firehose/latest/dev/what-is-this-service.html`, 'What is Amazon Data Firehose?'),
  aws('stepfunctions', `${D}/step-functions/latest/dg/welcome.html`, 'What is Step Functions?'),
  aws('eventbridge-patterns', `${D}/eventbridge/latest/userguide/eb-event-patterns.html`, 'Amazon EventBridge event patterns'),
  aws('eventbridge-rules', `${D}/eventbridge/latest/userguide/eb-rules.html`, 'Rules in Amazon EventBridge'),
  aws('sqs-standard', `${D}/AWSSimpleQueueService/latest/SQSDeveloperGuide/standard-queues.html`, 'Amazon SQS standard queues'),
  aws('sqs-dlq', `${D}/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html`, 'Using dead-letter queues in Amazon SQS'),
  aws('msa-simple', `${D}/whitepapers/latest/microservices-on-aws/simple-microservices-architecture-on-aws.html`, 'Simple microservices architecture on AWS'),
  aws('msa-ui', `${D}/whitepapers/latest/microservices-on-aws/user-interface.html`, 'User interface (Implementing Microservices on AWS)'),
  aws('msa-data-store', `${D}/whitepapers/latest/microservices-on-aws/data-store.html`, 'Data store (Implementing Microservices on AWS)'),
  aws('msa-distributed-data', `${D}/whitepapers/latest/microservices-on-aws/distributed-data-management.html`, 'Distributed data management (Implementing Microservices on AWS)'),
  aws('apigw-welcome', `${D}/apigateway/latest/developerguide/welcome.html`, 'What is Amazon API Gateway?'),
  aws('apigw-http-vs-rest', `${D}/apigateway/latest/developerguide/http-api-vs-rest.html`, 'Choose between REST APIs and HTTP APIs'),
  aws('apigw-throttling', `${D}/apigateway/latest/developerguide/api-gateway-request-throttling.html`, 'Throttle requests to your REST APIs'),
  aws('apigw-caching', `${D}/apigateway/latest/developerguide/api-gateway-caching.html`, 'Cache settings for REST APIs in API Gateway'),
  aws('lambda-quotas', `${D}/lambda/latest/dg/gettingstarted-limits.html`, 'Lambda quotas'),
  aws('lambda-concurrency', `${D}/lambda/latest/dg/lambda-concurrency.html`, 'Understanding Lambda function scaling'),
  aws('fargate-ecs', `${D}/AmazonECS/latest/developerguide/AWS_Fargate.html`, 'Architect for AWS Fargate for Amazon ECS'),
  aws('ecs-what-is', `${D}/AmazonECS/latest/developerguide/Welcome.html`, 'What is Amazon Elastic Container Service?'),
  aws('eks-what-is', `${D}/eks/latest/userguide/what-is-eks.html`, 'What is Amazon EKS?'),
  aws('ecr-what-is', `${D}/AmazonECR/latest/userguide/what-is-ecr.html`, 'What is Amazon Elastic Container Registry?'),
  aws('a2c', `${D}/app2container/latest/UserGuide/what-is-a2c.html`, 'What is AWS App2Container?'),
  aws('container-decision', `${D}/decision-guides/latest/decision-guides/choosing-aws-container-service.html`, 'Choosing an AWS container service'),
  aws('rds-scaling-ha', `${D}/AmazonRDS/latest/gettingstartedguide/scaling-ha.html`, 'Scaling and high availability in Amazon RDS'),
  aws('rds-read-replicas', `${D}/AmazonRDS/latest/UserGuide/USER_ReadRepl.html`, 'Working with DB instance read replicas'),
  aws('ec2-resize', `${D}/AWSEC2/latest/UserGuide/ec2-instance-resize.html`, 'Change the instance type'),
  aws('elb-what-is', `${D}/elasticloadbalancing/latest/userguide/what-is-load-balancing.html`, 'What is Elastic Load Balancing?'),
  aws('alb-intro', `${D}/elasticloadbalancing/latest/application/introduction.html`, 'What is an Application Load Balancer?'),
  aws('asg-what-is', `${D}/autoscaling/ec2/userguide/what-is-amazon-ec2-auto-scaling.html`, 'What is Amazon EC2 Auto Scaling?'),
  aws('asg-target-tracking', `${D}/autoscaling/ec2/userguide/as-scaling-target-tracking.html`, 'Target tracking scaling policies for Amazon EC2 Auto Scaling'),
  aws('asg-scheduled', `${D}/autoscaling/ec2/userguide/ec2-auto-scaling-scheduled-scaling.html`, 'Scheduled scaling for Amazon EC2 Auto Scaling'),
  aws('asg-predictive', `${D}/autoscaling/ec2/userguide/ec2-auto-scaling-predictive-scaling.html`, 'Predictive scaling for Amazon EC2 Auto Scaling'),
  aws('cloudfront-what-is', `${D}/AmazonCloudFront/latest/DeveloperGuide/Introduction.html`, 'What is Amazon CloudFront?'),
  aws('cloudfront-expiration', `${D}/AmazonCloudFront/latest/DeveloperGuide/Expiration.html`, 'Manage how long content stays in the cache (expiration)'),
  aws('elasticache-what-is', `${D}/AmazonElastiCache/latest/dg/WhatIs.html`, 'What is Amazon ElastiCache?'),
  aws('elasticache-strategies', `${D}/AmazonElastiCache/latest/dg/Strategies.html`, 'Caching strategies for ElastiCache'),
  aws('dax', `${D}/amazondynamodb/latest/developerguide/DAX.html`, 'In-memory acceleration with DynamoDB Accelerator (DAX)'),
  aws('ga-what-is', `${D}/global-accelerator/latest/dg/what-is-global-accelerator.html`, 'What is AWS Global Accelerator?'),
  aws('storage-decision', `${D}/decision-guides/latest/decision-guides/choosing-aws-storage-service.html`, 'Choosing an AWS storage service'),
  aws('database-decision', `${D}/decision-guides/latest/decision-guides/databases-on-aws-how-to-choose.html`, 'Choosing an AWS database service'),
  aws('compute-decision', `${D}/decision-guides/latest/decision-guides/choosing-aws-compute-service.html`, 'Choosing an AWS compute service'),
  aws('s3-what-is', `${D}/AmazonS3/latest/userguide/Welcome.html`, 'What is Amazon S3?'),
  aws('ebs-what-is', `${D}/ebs/latest/userguide/what-is-ebs.html`, 'What is Amazon Elastic Block Store?'),
  aws('efs-what-is', `${D}/efs/latest/ug/whatisefs.html`, 'What is Amazon Elastic File System?'),
  aws('transfer-what-is', `${D}/transfer/latest/userguide/what-is-aws-transfer-family.html`, 'What is AWS Transfer Family?'),
  aws('dynamodb-what-is', `${D}/amazondynamodb/latest/developerguide/Introduction.html`, 'What is Amazon DynamoDB?'),
  aws('neptune-what-is', `${D}/neptune/latest/userguide/intro.html`, 'What Is Amazon Neptune?'),
  aws('waf-multi-location', `${D}/wellarchitected/latest/reliability-pillar/rel_fault_isolation_multiaz_region_system.html`, 'REL10-BP01 Deploy the workload to multiple locations'),
  aws('route53-what-is', `${D}/Route53/latest/DeveloperGuide/Welcome.html`, 'What is Amazon Route 53?'),
  aws('route53-routing', `${D}/Route53/latest/DeveloperGuide/routing-policy.html`, 'Choosing a routing policy'),
  aws('route53-failover', `${D}/Route53/latest/DeveloperGuide/dns-failover.html`, 'Creating Amazon Route 53 health checks'),
  aws('route53-failover-types', `${D}/Route53/latest/DeveloperGuide/dns-failover-types.html`, 'Active-active and active-passive failover'),
  aws('waf-retries', `${D}/wellarchitected/latest/framework/rel_mitigate_interaction_failure_limit_retries.html`, 'REL05-BP03 Control and limit retry calls'),
  aws('waf-throttle', `${D}/wellarchitected/latest/framework/rel_mitigate_interaction_failure_throttle_requests.html`, 'REL05-BP02 Throttle requests'),
  aws('waf-fail-fast', `${D}/wellarchitected/latest/framework/rel_mitigate_interaction_failure_fail_fast.html`, 'REL05-BP04 Fail fast and limit queues'),
  aws('waf-graceful', `${D}/wellarchitected/latest/framework/rel_mitigate_interaction_failure_graceful_degradation.html`, 'REL05-BP01 Implement graceful degradation'),
  aws('rds-proxy', `${D}/AmazonRDS/latest/UserGuide/rds-proxy.html`, 'Amazon RDS Proxy'),
  aws('rds-proxy-planning', `${D}/AmazonRDS/latest/UserGuide/rds-proxy-planning.html`, 'Planning where to use RDS Proxy'),
  aws('rds-multi-az', `${D}/AmazonRDS/latest/UserGuide/Concepts.MultiAZ.html`, 'Configuring and managing a Multi-AZ deployment for Amazon RDS'),
  aws('dr-options', `${D}/whitepapers/latest/disaster-recovery-workloads-on-aws/disaster-recovery-options-in-the-cloud.html`, 'Disaster recovery options in the cloud'),
  aws('dr-objectives', `${D}/whitepapers/latest/disaster-recovery-workloads-on-aws/business-continuity-plan-bcp.html`, 'Business Continuity Plan (BCP): recovery objectives'),
  aws('servicequotas', `${D}/servicequotas/latest/userguide/intro.html`, 'What is Service Quotas?'),
  aws('servicequotas-cw', `${D}/servicequotas/latest/userguide/configure-cloudwatch.html`, 'Service Quotas and Amazon CloudWatch alarms'),
  aws('waf-quotas-regions', `${D}/wellarchitected/latest/reliability-pillar/rel_manage_service_limits_limits_considered.html`, 'REL01-BP02 Manage service quotas across accounts and regions'),
  aws('xray', `${D}/xray/latest/devguide/aws-xray.html`, 'What is AWS X-Ray?'),
  aws('trusted-advisor', `${D}/awssupport/latest/user/trusted-advisor.html`, 'AWS Trusted Advisor'),
  aws('waf-availability', `${D}/wellarchitected/latest/reliability-pillar/availability.html`, 'Availability (Reliability Pillar)'),
  aws('waf-monitor-components', `${D}/wellarchitected/latest/reliability-pillar/rel_monitor_aws_resources_monitor_resources.html`, 'REL06-BP01 Monitor all components for the workload'),
  aws('alb-metrics', `${D}/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html`, 'CloudWatch metrics for your Application Load Balancer'),
  aws('waf-immutable', `${D}/wellarchitected/latest/framework/rel_tracking_change_management_immutable_infrastructure.html`, 'REL08-BP04 Deploy using immutable infrastructure'),
  aws('waf-automate-changes', `${D}/wellarchitected/latest/framework/rel_tracking_change_management_automated_changemgmt.html`, 'REL08-BP05 Deploy changes with automation'),
  aws('cfn-what-is', `${D}/AWSCloudFormation/latest/UserGuide/Welcome.html`, 'What is CloudFormation?'),
  aws('cfn-drift', `${D}/AWSCloudFormation/latest/UserGuide/using-cfn-stack-drift.html`, 'Detect unmanaged configuration changes with drift detection'),
  aws('ssm-what-is', `${D}/systems-manager/latest/userguide/what-is-systems-manager.html`, 'What is AWS Systems Manager?'),
  aws('ssm-patch', `${D}/systems-manager/latest/userguide/patch-manager.html`, 'AWS Systems Manager Patch Manager'),
  aws('ami', `${D}/AWSEC2/latest/UserGuide/AMIs.html`, 'Amazon Machine Images in Amazon EC2'),
  aws('asg-instance-refresh', `${D}/autoscaling/ec2/userguide/asg-instance-refresh.html`, 'Use an instance refresh to update instances in an Auto Scaling group'),
  aws('s3-durability', `${D}/AmazonS3/latest/userguide/DataDurability.html`, 'Data protection in Amazon S3'),
  aws('efs-features', `${D}/efs/latest/ug/features.html`, 'Features of Amazon EFS'),
  aws('efs-replication', `${D}/efs/latest/ug/efs-replication.html`, 'Replicating EFS file systems'),
  aws('ebs-volumes', `${D}/ebs/latest/userguide/ebs-volumes.html`, 'Amazon EBS volumes'),
  aws('s3-storage-classes', `${D}/AmazonS3/latest/userguide/storage-class-intro.html`, 'Understanding and managing Amazon S3 storage classes'),
  aws('comprehend-what-is', `${D}/comprehend/latest/dg/what-is.html`, 'What is Amazon Comprehend?'),
  aws('polly-what-is', `${D}/polly/latest/dg/what-is.html`, 'What Is Amazon Polly?'),
  aws('ec2-recover', `${D}/AWSEC2/latest/UserGuide/ec2-instance-recover.html`, 'Automatic instance recovery'),
  aws('alb-target-attrs', `${D}/elasticloadbalancing/latest/application/edit-target-group-attributes.html`, 'Edit target group attributes for your Application Load Balancer'),
  aws('rds-multi-az-instance', `${D}/AmazonRDS/latest/UserGuide/Concepts.MultiAZSingleStandby.html`, 'Multi-AZ DB instance deployments for Amazon RDS'),
  aws('s3-performance', `${D}/AmazonS3/latest/userguide/optimizing-performance.html`, 'Best practices design patterns: optimizing Amazon S3 performance'),
  aws('ebs-volume-types', `${D}/ebs/latest/userguide/ebs-volume-types.html`, 'Amazon EBS volume types'),
  aws('efs-performance', `${D}/efs/latest/ug/performance.html`, 'Amazon EFS performance specifications'),
  aws('sgw-file-s3', `${D}/filegateway/latest/files3/what-is-file-s3.html`, 'What is Amazon S3 File Gateway'),
  aws('sgw-volume', `${D}/storagegateway/latest/vgw/WhatIsStorageGateway.html`, 'What is Volume Gateway?'),
  aws('sgw-tape', `${D}/storagegateway/latest/tgw/WhatIsStorageGateway.html`, 'What is Tape Gateway?'),
  aws('sgw-fsx-file', `${D}/filegateway/latest/filefsxw/what-is-file-fsxw.html`, 'What is Amazon FSx File Gateway'),
  aws('storage-gateway-docs', `${D}/storagegateway/`, 'AWS Storage Gateway documentation'),
  aws('ec2-type-names', `${D}/ec2/latest/instancetypes/instance-type-names.html`, 'Amazon EC2 instance type naming conventions'),
  aws('ec2-nitro', `${D}/ec2/latest/instancetypes/ec2-nitro-instances.html`, 'Instances built on the AWS Nitro System'),
  aws('compute-optimizer', `${D}/compute-optimizer/latest/ug/what-is-compute-optimizer.html`, 'What is AWS Compute Optimizer?'),
  aws('ec2-hibernate', `${D}/AWSEC2/latest/UserGuide/Hibernate.html`, 'Hibernate your Amazon EC2 instance'),
  aws('ec2-hibernate-prereq', `${D}/AWSEC2/latest/UserGuide/hibernating-prerequisites.html`, 'Prerequisites for EC2 instance hibernation'),
  aws('lambda-pricing', 'https://aws.amazon.com/lambda/pricing/', 'AWS Lambda pricing'),
  aws('local-zones', `${D}/local-zones/latest/ug/what-is-aws-local-zones.html`, 'What is AWS Local Zones?'),
  aws('ec2-lifecycle', `${D}/AWSEC2/latest/UserGuide/ec2-instance-lifecycle.html`, 'Amazon EC2 instance state changes'),
  aws('waf-cost-demand', `${D}/wellarchitected/latest/cost-optimization-pillar/manage-demand-and-supply-resources.html`, 'Cost Optimization Pillar: Manage demand and supply resources'),
  aws('rds-reserved', `${D}/AmazonRDS/latest/UserGuide/USER_WorkingWithReservedDBInstances.html`, 'Reserved DB instances for Amazon RDS'),
  aws('rds-tagging', `${D}/AmazonRDS/latest/UserGuide/USER_Tagging.html`, 'Tagging Amazon RDS resources'),
  aws('timestream-what-is', `${D}/timestream/latest/developerguide/what-is-timestream.html`, 'What is Amazon Timestream for LiveAnalytics?'),
  aws('redshift-columnar', `${D}/redshift/latest/dg/c_columnar_storage_disk_mem_mgmnt.html`, 'Columnar storage (Amazon Redshift)'),
  aws('dms-serverless', `${D}/dms/latest/userguide/CHAP_Serverless.html`, 'Working with AWS DMS Serverless'),
  aws('rds-oracle-licensing', `${D}/AmazonRDS/latest/UserGuide/Oracle.Concepts.Licensing.html`, 'RDS for Oracle licensing options'),
  aws('rds-backup-retention', `${D}/AmazonRDS/latest/UserGuide/USER_WorkingWithAutomatedBackups.BackupRetention.html`, 'Backup retention period (Amazon RDS)'),
  aws('rds-pitr', `${D}/AmazonRDS/latest/UserGuide/USER_PIT.html`, 'Restoring a DB instance to a specified time for Amazon RDS'),
  aws('rds-snapshot-create', `${D}/AmazonRDS/latest/UserGuide/USER_CreateSnapshot.html`, 'Creating a DB snapshot for a Single-AZ DB instance'),
  aws('backup-create-plan', `${D}/aws-backup/latest/devguide/creating-a-backup-plan.html`, 'Create a backup plan'),
  aws('ce-filtering', `${D}/cost-management/latest/userguide/ce-filtering.html`, 'Filtering the data that you want to view (Cost Explorer)'),
  aws('trusted-advisor-cost-checks', `${D}/awssupport/latest/user/cost-optimization-checks.html`, 'Trusted Advisor cost optimization checks'),
  aws('elb-pricing', 'https://aws.amazon.com/elasticloadbalancing/pricing/', 'Elastic Load Balancing pricing'),
  aws('apigw-usage-plans', `${D}/apigateway/latest/developerguide/api-gateway-api-usage-plans.html`, 'Usage plans and API keys for REST APIs in API Gateway'),
  aws('vpc-nat-comparison', `${D}/vpc/latest/userguide/vpc-nat-comparison.html`, 'Compare NAT gateways and NAT instances'),
  aws('vpc-nat-pricing', `${D}/vpc/latest/userguide/nat-gateway-pricing.html`, 'Pricing for NAT gateways'),
  aws('vpc-nat-regional', `${D}/vpc/latest/userguide/nat-gateways-regional.html`, 'Regional NAT gateways for automatic multi-AZ expansion'),
  aws('vpc-nat-scenarios', `${D}/vpc/latest/userguide/nat-gateway-scenarios.html`, 'NAT gateway use cases'),
  aws('dx-connection-types', `${D}/directconnect/latest/UserGuide/WorkingWithConnections.html`, 'Direct Connect dedicated and hosted connections'),
  aws('dx-dedicated', `${D}/directconnect/latest/UserGuide/dedicated_connection.html`, 'Dedicated Direct Connect connections'),
  aws('dx-resiliency', `${D}/directconnect/latest/UserGuide/resiliency_toolkit.html`, 'AWS Direct Connect Resiliency Toolkit'),
  aws('vpn-tunnels', `${D}/vpn/latest/s2svpn/VPNTunnels.html`, 'Tunnel options for your AWS Site-to-Site VPN connection'),
  aws('vpn-quotas', `${D}/vpn/latest/s2svpn/vpn-limits.html`, 'AWS Site-to-Site VPN quotas'),
  aws('vpn-pricing', 'https://aws.amazon.com/vpn/pricing/', 'AWS VPN pricing'),
  aws('cloudfront-pricing', 'https://aws.amazon.com/cloudfront/pricing/', 'Amazon CloudFront pricing'),
  aws('ga-pricing', 'https://aws.amazon.com/global-accelerator/pricing/', 'AWS Global Accelerator pricing'),
  aws('route53-pricing', 'https://aws.amazon.com/route53/pricing/', 'Amazon Route 53 pricing'),
  aws('route53-alias', `${D}/Route53/latest/DeveloperGuide/resource-record-sets-choosing-alias-non-alias.html`, 'Choosing between alias and non-alias records'),
  aws('ec2-instance-types', `${D}/ec2/latest/instancetypes/instance-types.html`, 'Amazon EC2 instance types'),
  aws('ec2-gp', `${D}/ec2/latest/instancetypes/gp.html`, 'Specifications for Amazon EC2 general purpose instances'),
  aws('ec2-co', `${D}/ec2/latest/instancetypes/co.html`, 'Specifications for Amazon EC2 compute optimized instances'),
  aws('ec2-mo', `${D}/ec2/latest/instancetypes/mo.html`, 'Specifications for Amazon EC2 memory optimized instances'),
  aws('ec2-so', `${D}/ec2/latest/instancetypes/so.html`, 'Specifications for Amazon EC2 storage optimized instances'),
  aws('ec2-ac', `${D}/ec2/latest/instancetypes/ac.html`, 'Specifications for Amazon EC2 accelerated computing instances'),
  aws('lambda-memory', `${D}/lambda/latest/dg/configuration-memory.html`, 'Configure Lambda function memory'),
  aws('batch-what-is', `${D}/batch/latest/userguide/what-is-batch.html`, 'What is AWS Batch?'),
  aws('emr-what-is', `${D}/emr/latest/ManagementGuide/emr-what-is-emr.html`, 'What is Amazon EMR?'),
  aws('appas-what-is', `${D}/autoscaling/application/userguide/what-is-application-auto-scaling.html`, 'What is Application Auto Scaling?'),
  aws('asg-step', `${D}/autoscaling/ec2/userguide/as-scaling-simple-step.html`, 'Step and simple scaling policies for Amazon EC2 Auto Scaling'),
  aws('scaling-plan-migrate', `${D}/autoscaling/plans/userguide/migrate-scaling-plan.html`, 'Migrate your scaling plan'),
  aws('cf-edge-functions', `${D}/AmazonCloudFront/latest/DeveloperGuide/edge-functions.html`, 'Customize at the edge with functions'),
  aws('sqs-visibility', `${D}/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html`, 'Amazon SQS visibility timeout'),
  aws('sqs-polling', `${D}/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-short-and-long-polling.html`, 'Amazon SQS short and long polling'),
  aws('sqs-fifo', `${D}/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-fifo-queues.html`, 'Amazon SQS FIFO queues'),
  aws('sns-sqs-fanout', `${D}/sns/latest/dg/sns-sqs-as-subscriber.html`, 'Fanout Amazon SNS notifications to Amazon SQS queues'),
  aws('asg-sqs', `${D}/autoscaling/ec2/userguide/as-using-sqs-queue.html`, 'Scaling based on Amazon SQS'),
  aws('lambda-provisioned', `${D}/lambda/latest/dg/provisioned-concurrency.html`, 'Configuring provisioned concurrency for a function'),
  aws('lambda-reserved', `${D}/lambda/latest/dg/configuration-concurrency.html`, 'Configuring reserved concurrency for a function'),
  aws('ecs-autoscaling', `${D}/AmazonECS/latest/developerguide/service-auto-scaling.html`, 'Automatically scale your Amazon ECS service'),
  aws('eks-autoscaling', `${D}/eks/latest/userguide/autoscaling.html`, 'Scale cluster compute with Karpenter and Cluster Autoscaler'),
  aws('aurora-overview', `${D}/AmazonRDS/latest/AuroraUserGuide/CHAP_AuroraOverview.html`, 'What is Amazon Aurora?'),
  aws('aurora-storage', `${D}/AmazonRDS/latest/AuroraUserGuide/Aurora.Overview.StorageReliability.html`, 'Aurora storage and reliability'),
  aws('aurora-serverless', `${D}/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2.html`, 'Using Aurora Serverless'),
  aws('rds-what-is', `${D}/AmazonRDS/latest/UserGuide/Welcome.html`, 'What is Amazon Relational Database Service?'),
  aws('dms-what-is', `${D}/dms/latest/userguide/Welcome.html`, 'What is AWS Database Migration Service?'),
  aws('dynamodb-capacity', `${D}/amazondynamodb/latest/developerguide/capacity-mode.html`, 'DynamoDB throughput capacity'),
  aws('rds-storage', `${D}/AmazonRDS/latest/UserGuide/CHAP_Storage.html`, 'Amazon RDS DB instance storage'),
  aws('aurora-replication', `${D}/AmazonRDS/latest/AuroraUserGuide/Aurora.Replication.html`, 'Replication with Amazon Aurora'),
  aws('aurora-global', `${D}/AmazonRDS/latest/AuroraUserGuide/aurora-global-database.html`, 'Using Amazon Aurora Global Database'),
  aws('elasticache-engines', `${D}/AmazonElastiCache/latest/dg/SelectEngine.html`, 'Comparing node-based Valkey, Memcached, and Redis OSS clusters'),
  aws('memorydb', `${D}/memorydb/latest/devguide/what-is-memorydb.html`, 'What is Amazon MemoryDB?'),
  aws('dynamodb-provisioned', `${D}/amazondynamodb/latest/developerguide/provisioned-capacity-mode.html`, 'DynamoDB provisioned capacity mode'),
  aws('dynamodb-ondemand', `${D}/amazondynamodb/latest/developerguide/on-demand-capacity-mode.html`, 'DynamoDB on-demand capacity mode'),
  aws('dynamodb-partition-keys', `${D}/amazondynamodb/latest/developerguide/bp-partition-key-design.html`, 'Best practices for designing and using partition keys effectively in DynamoDB'),
  aws('rds-instance-class', `${D}/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html`, 'DB instance classes'),
  aws('rds-instance-class-types', `${D}/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.Types.html`, 'DB instance class types'),
  aws('peering-what-is', `${D}/vpc/latest/peering/what-is-vpc-peering.html`, 'What is VPC peering?'),
  aws('peering-basics', `${D}/vpc/latest/peering/vpc-peering-basics.html`, 'VPC peering connection basics'),
  aws('tgw-what-is', `${D}/vpc/latest/tgw/what-is-transit-gateway.html`, 'What is AWS Transit Gateway for Amazon VPC?'),
  aws('tgw-how', `${D}/vpc/latest/tgw/how-transit-gateways-work.html`, 'How AWS Transit Gateway works'),
  aws('tgw-peering', `${D}/vpc/latest/tgw/tgw-peering.html`, 'Transit gateway peering attachments'),
  aws('nlb-intro', `${D}/elasticloadbalancing/latest/network/introduction.html`, 'What is a Network Load Balancer?'),
  aws('gwlb-intro', `${D}/elasticloadbalancing/latest/gateway/introduction.html`, 'What is a Gateway Load Balancer?'),
  aws('alb-listeners', `${D}/elasticloadbalancing/latest/application/load-balancer-listeners.html`, 'Listeners for your Application Load Balancers'),
  aws('ga-how', `${D}/global-accelerator/latest/dg/introduction-how-it-works.html`, 'How AWS Global Accelerator works'),
  aws('ga-product', 'https://aws.amazon.com/global-accelerator/', 'AWS Global Accelerator'),
  aws('outposts-what-is', `${D}/outposts/latest/userguide/what-is-outposts.html`, 'What is AWS Outposts?'),
  aws('wavelength-what-is', `${D}/wavelength/latest/developerguide/what-is-wavelength.html`, 'What is AWS Wavelength?'),
  aws('what-is-data-lake', 'https://aws.amazon.com/what-is/data-lake/', 'What is a data lake?'),
  aws('athena-what-is', `${D}/athena/latest/ug/what-is.html`, 'What is Amazon Athena?'),
  aws('athena-columnar', `${D}/athena/latest/ug/columnar-storage.html`, 'Use columnar storage formats'),
  aws('athena-partitions', `${D}/athena/latest/ug/partitions.html`, 'Partition your data'),
  aws('glue-what-is', `${D}/glue/latest/dg/what-is-glue.html`, 'What is AWS Glue?'),
  aws('firehose-rename', 'https://aws.amazon.com/about-aws/whats-new/2024/02/amazon-data-firehose-formerly-kinesis-data-firehose/', 'Introducing Amazon Data Firehose, formerly known as Amazon Kinesis Data Firehose'),
  aws('kinesis-concepts', `${D}/streams/latest/dev/key-concepts.html`, 'Amazon Kinesis Data Streams terminology and concepts'),
  aws('kinesis-efo', `${D}/streams/latest/dev/enhanced-consumers.html`, 'Develop enhanced fan-out consumers with dedicated throughput'),
  aws('msk-what-is', `${D}/msk/latest/developerguide/what-is-msk.html`, 'What is Amazon MSK?'),
  aws('msk-provisioned', `${D}/msk/latest/developerguide/msk-provisioned.html`, 'Amazon MSK Provisioned clusters'),
  aws('what-is-streaming-data', 'https://aws.amazon.com/what-is/streaming-data/', 'What is streaming data?'),
  aws('datasync-what-is', `${D}/datasync/latest/userguide/what-is-datasync.html`, 'What is AWS DataSync?'),
  aws('datasync-how', `${D}/datasync/latest/userguide/how-datasync-transfer-works.html`, 'How AWS DataSync works'),
  aws('snowball-edge', `${D}/snowball/latest/developer-guide/whatisedge.html`, 'What is Snowball Edge?'),
  aws('dtt', `${D}/datatransferterminal/latest/userguide/what-is-dtt.html`, 'What is Data Transfer Terminal?'),
  aws('glue-components', `${D}/glue/latest/dg/components-overview.html`, 'AWS Glue components'),
  aws('glue-catalog', `${D}/glue/latest/dg/catalog-and-crawler.html`, 'Data discovery and cataloging in AWS Glue'),
  aws('glue-parquet', `${D}/glue/latest/dg/aws-glue-programming-etl-format-parquet-home.html`, 'Using the Parquet format in AWS Glue'),
  aws('athena-ctas', `${D}/athena/latest/ug/ctas-examples.html`, 'Examples of CTAS queries'),
  aws('emr-serverless', `${D}/emr/latest/EMR-Serverless-UserGuide/emr-serverless.html`, 'What is Amazon EMR Serverless?'),
  aws('kinesis-vpc', `${D}/streams/latest/dev/vpc.html`, 'Use interface VPC endpoints for Kinesis Data Streams'),
  aws('kinesis-sse', `${D}/streams/latest/dev/server-side-encryption.html`, 'Data protection in Amazon Kinesis Data Streams: server-side encryption'),
  aws('kinesis-iam', `${D}/streams/latest/dev/controlling-access.html`, 'Controlling access to Amazon Kinesis Data Streams resources using IAM'),
  aws('firehose-vpc', `${D}/firehose/latest/dev/vpc.html`, 'Using interface VPC endpoints (AWS PrivateLink) for Firehose'),
  aws('msk-clientauth', `${D}/msk/latest/developerguide/kafka_apis_iam.html`, 'Authentication and authorization for Apache Kafka APIs'),
  aws('msk-encryption', `${D}/msk/latest/developerguide/msk-encryption.html`, 'Amazon MSK encryption'),
  aws('transfer-vpc', `${D}/transfer/latest/userguide/create-server-in-vpc.html`, 'Create a server in a virtual private cloud'),
  aws('msk-mtls', `${D}/msk/latest/developerguide/msk-authentication.html`, 'Mutual TLS client authentication for Amazon MSK'),
  aws('ce-what-is', `${D}/cost-management/latest/userguide/ce-what-is.html`, 'Analyzing your costs and usage with AWS Cost Explorer'),
  aws('savings-plans', `${D}/savingsplans/latest/userguide/what-is-savings-plans.html`, 'What are Savings Plans?'),
  aws('savings-plans-types', `${D}/savingsplans/latest/userguide/plan-types.html`, 'Savings Plans types'),
  aws('ec2-reserved-instances', `${D}/AWSEC2/latest/UserGuide/ec2-reserved-instances.html`, 'Reserved Instances for Amazon EC2 overview'),
  aws('ec2-ri-scope', `${D}/AWSEC2/latest/UserGuide/reserved-instances-scope.html`, 'Regional and zonal Reserved Instances (scope)'),
  aws('ec2-spot', `${D}/AWSEC2/latest/UserGuide/using-spot-instances.html`, 'Spot Instances'),
  aws('ec2-spot-interruptions', `${D}/AWSEC2/latest/UserGuide/spot-interruptions.html`, 'Spot Instance interruptions'),
  aws('ec2-purchasing', `${D}/AWSEC2/latest/UserGuide/instance-purchasing-options.html`, 'Amazon EC2 billing and purchasing options'),
  aws('cur-what-is', `${D}/cur/latest/userguide/what-is-cur.html`, 'What are AWS Cost and Usage Reports?'),
  aws('cost-alloc-tags', `${D}/awsaccountbilling/latest/aboutv2/cost-alloc-tags.html`, 'Organizing and tracking costs using AWS cost allocation tags'),
  aws('consolidated-billing', `${D}/awsaccountbilling/latest/aboutv2/consolidated-billing.html`, 'Consolidated billing for AWS Organizations'),
  aws('requester-pays', `${D}/AmazonS3/latest/userguide/RequesterPaysBuckets.html`, 'Using Requester Pays general purpose buckets for storage transfers and usage'),
  aws('instance-store', `${D}/AWSEC2/latest/UserGuide/InstanceStorage.html`, 'Instance store temporary block storage for EC2 instances'),
  aws('instance-store-lifetime', `${D}/AWSEC2/latest/UserGuide/instance-store-lifetime.html`, 'Data persistence for Amazon EC2 instance store volumes'),
  aws('ebs-modify', `${D}/ebs/latest/userguide/ebs-modify-volume.html`, 'Amazon EBS Elastic Volumes operations'),
  aws('rds-storage-autoscaling', `${D}/AmazonRDS/latest/UserGuide/USER_PIOPS.Autoscaling.html`, 'Managing capacity automatically with Amazon RDS storage autoscaling'),
  aws('fsx-windows', `${D}/fsx/latest/WindowsGuide/what-is.html`, 'What is FSx for Windows File Server?'),
  aws('fsx-lustre', `${D}/fsx/latest/LustreGuide/what-is.html`, 'What is Amazon FSx for Lustre?'),
  aws('fsx-ontap', `${D}/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html`, 'What is Amazon FSx for NetApp ONTAP?'),
  aws('fsx-openzfs', `${D}/fsx/latest/OpenZFSGuide/what-is-fsx.html`, 'What is Amazon FSx for OpenZFS?'),
  aws('efs-lifecycle', `${D}/efs/latest/ug/lifecycle-management-efs.html`, 'Managing storage lifecycle (EFS lifecycle management)'),
  aws('s3-multipart', `${D}/AmazonS3/latest/userguide/mpuoverview.html`, 'Uploading and copying objects using multipart upload in Amazon S3'),
  aws('s3-transfer-acceleration', `${D}/AmazonS3/latest/userguide/transfer-acceleration.html`, 'Configuring fast, secure file transfers using Amazon S3 Transfer Acceleration'),
  aws('s3-glacier-classes', `${D}/AmazonS3/latest/userguide/glacier-storage-classes.html`, 'Understanding S3 Glacier storage classes for long-term data storage'),
  aws('s3-lifecycle-transitions', `${D}/AmazonS3/latest/userguide/lifecycle-transition-general-considerations.html`, 'Transitioning objects using Amazon S3 Lifecycle'),
  aws('s3-lifecycle-rules', `${D}/AmazonS3/latest/userguide/intro-lifecycle-rules.html`, 'Lifecycle configuration elements'),
  aws('s3-lifecycle-expire', `${D}/AmazonS3/latest/userguide/lifecycle-expire-general-considerations.html`, 'Expiring objects'),
  aws('ebs-snapshots', `${D}/ebs/latest/userguide/ebs-snapshots.html`, 'Amazon EBS snapshots'),
  aws('ebs-snapshot-archive', `${D}/ebs/latest/userguide/snapshot-archive.html`, 'Archive Amazon EBS snapshots'),
  aws('rds-automated-backups', `${D}/AmazonRDS/latest/UserGuide/USER_WorkingWithAutomatedBackups.html`, 'Introduction to backups (Amazon RDS)'),
  aws('sagemaker-what-is', `${D}/sagemaker/latest/dg/whatis.html`, 'What is Amazon SageMaker AI?'),
  aws('quick-what-is', `${D}/quick/latest/userguide/what-is.html`, 'What is Amazon Quick?'),

  // Microsoft Learn (Azure side of the Azure notes only)
  azure('learn-hub', `${L}/architecture/aws-professional/`, 'Azure for AWS professionals: service comparison'),
  azure('learn-compute', `${L}/architecture/aws-professional/compute`, 'Compute services on Azure and AWS'),
  azure('learn-storage', `${L}/architecture/aws-professional/storage`, 'Compare storage on Azure and AWS'),
  azure('learn-networking', `${L}/architecture/aws-professional/networking`, 'Compare AWS and Azure networking options'),
  azure('learn-databases', `${L}/architecture/aws-professional/databases`, 'Database services on Azure and AWS'),
  azure('learn-zones', `${L}/reliability/availability-zones-overview`, 'Azure availability zones overview'),
  azure('learn-shared-responsibility', `${L}/security/fundamentals/shared-responsibility`, 'Shared responsibility in the cloud (Azure)'),
  azure('learn-storage-redundancy', `${L}/storage/common/storage-redundancy`, 'Azure Storage redundancy'),
  azure('learn-analytics', `${L}/architecture/aws-professional/analytics`, 'Analytics services on Azure and AWS'),
  aws('lambda-images', `${D}/lambda/latest/dg/images-create.html`, 'Create a Lambda function using a container image'),
  aws('waf-rate-based', `${D}/waf/latest/developerguide/waf-rule-statement-type-rate-based.html`, 'Using rate-based rule statements in AWS WAF'),
  aws('data-exports-what-is', `${D}/cur/latest/userguide/what-is-data-exports.html`, 'What is AWS Data Exports?'),
  aws('cur-create', `${D}/cur/latest/userguide/cur-create.html`, 'Creating Cost and Usage Reports'),
  aws('transfer-ftp', `${D}/transfer/latest/userguide/create-server-ftp.html`, 'Create an FTP-enabled server'),
  aws('apprunner-what-is', `${D}/apprunner/latest/dg/what-is-apprunner.html`, 'What is AWS App Runner?'),
  aws('ga-listeners', `${D}/global-accelerator/latest/dg/about-listeners.html`, 'Listeners for standard accelerators in AWS Global Accelerator'),
  aws('firehose-faqs', 'https://aws.amazon.com/firehose/faqs/', 'Amazon Data Firehose FAQs'),
  aws('asg-attach-lb', `${D}/autoscaling/ec2/userguide/attach-load-balancer-asg.html`, 'Attach a load balancer to your Auto Scaling group'),
  aws('firehose-delivery', `${D}/firehose/latest/dev/basic-deliver.html`, 'Data delivery in Amazon Data Firehose'),
  aws('ec2-capacity-reservations', `${D}/AWSEC2/latest/UserGuide/ec2-capacity-reservations.html`, 'Reserve compute capacity with EC2 On-Demand Capacity Reservations'),
  aws('ec2-capacity-reservation-billing', `${D}/AWSEC2/latest/UserGuide/capacity-reservations-pricing-billing.html`, 'Capacity Reservation pricing and billing'),
  aws('ec2-ri-classes', `${D}/AWSEC2/latest/UserGuide/reserved-instances-types.html`, 'Types of Reserved Instances (offering classes)'),
  aws('savings-plans-vs-ri', `${D}/savingsplans/latest/userguide/sp-ris.html`, 'Compute Savings Plans and Reserved Instances'),
  aws('ec2-on-demand', `${D}/AWSEC2/latest/UserGuide/ec2-on-demand-instances.html`, 'Purchasing On-Demand Instances for Amazon EC2'),
  aws('ec2-spot-notices', `${D}/AWSEC2/latest/UserGuide/spot-instance-termination-notices.html`, 'Spot Instance interruption notices'),
  aws('connectivity-privatelink', `${D}/whitepapers/latest/aws-vpc-connectivity-options/aws-privatelink.html`, 'Amazon VPC connectivity options: AWS PrivateLink'),
  aws('connectivity-tgw', `${D}/whitepapers/latest/aws-vpc-connectivity-options/aws-transit-gateway.html`, 'Amazon VPC connectivity options: AWS Transit Gateway'),
  aws('dax-concepts', `${D}/amazondynamodb/latest/developerguide/DAX.concepts.html`, 'DAX: concepts'),
  aws('privatelink-service', `${D}/vpc/latest/privatelink/create-endpoint-service.html`, 'Create an endpoint service (PrivateLink)'),
  aws('rekognition-what-is', `${D}/rekognition/latest/dg/what-is.html`, 'What is Amazon Rekognition?'),
  aws('textract-what-is', `${D}/textract/latest/dg/what-is.html`, 'What is Amazon Textract?'),
  aws('transcribe-what-is', `${D}/transcribe/latest/dg/what-is.html`, 'What is Amazon Transcribe?'),
  aws('translate-what-is', `${D}/translate/latest/dg/what-is.html`, 'What is Amazon Translate?'),
  aws('lex-what-is', `${D}/lexv2/latest/dg/what-is.html`, 'What is Amazon Lex V2?'),
  aws('rds-promote', `${D}/AmazonRDS/latest/UserGuide/USER_ReadRepl.Promote.html`, 'Promoting a read replica to be a standalone DB instance'),
  aws('secrets-pricing', 'https://aws.amazon.com/secrets-manager/pricing/', 'AWS Secrets Manager pricing'),
  aws('ssm-parameter-tiers', `${D}/systems-manager/latest/userguide/parameter-store-advanced-parameters.html`, 'Choosing parameter tiers in Parameter Store'),
  azure('learn-azure-gwlb', `${L}/load-balancer/gateway-overview`, 'Gateway Load Balancer (Azure Load Balancer)'),
  aws('aurora-serverless-how', `${D}/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2.how-it-works.html`, 'How Aurora serverless works'),
  aws('timestream-availability', `${D}/timestream/latest/developerguide/AmazonTimestreamForLiveAnalytics-availability-change.html`, 'Amazon Timestream for LiveAnalytics availability change'),
  aws('aurora-autoscaling', `${D}/AmazonRDS/latest/AuroraUserGuide/Aurora.Integrating.AutoScaling.html`, 'Amazon Aurora Auto Scaling with Aurora Replicas'),
  aws('dynamodb-table-classes', `${D}/amazondynamodb/latest/developerguide/WorkingWithTables.tableclasses.html`, 'Considerations when choosing a table class in DynamoDB'),
  aws('dynamodb-ttl', `${D}/amazondynamodb/latest/developerguide/TTL.html`, 'Using time to live (TTL) in DynamoDB'),
  aws('dynamodb-pricing', 'https://aws.amazon.com/dynamodb/pricing/', 'Amazon DynamoDB pricing'),
  aws('ga-faq', 'https://aws.amazon.com/global-accelerator/faqs/', 'AWS Global Accelerator FAQs'),
  aws('ebs-multi-attach', `${D}/ebs/latest/userguide/ebs-volumes-multi.html`, 'Attach an EBS volume to multiple EC2 instances using Multi-Attach'),
  aws('vpc-custom-nacl', `${D}/vpc/latest/userguide/custom-network-acl.html`, 'Custom network ACLs for your VPC'),
  aws('vpc-create-nacl', `${D}/vpc/latest/userguide/create-network-acl.html`, 'Create a network ACL for your VPC'),
  aws('vpc-egress-only-igw', `${D}/vpc/latest/userguide/egress-only-internet-gateway.html`, 'Enable outbound IPv6 traffic using an egress-only internet gateway'),
  aws('iam-root-best-practices', `${D}/IAM/latest/UserGuide/root-user-best-practices.html`, 'Root user best practices for your AWS account'),
  aws('iam-policy-eval-basics', `${D}/IAM/latest/UserGuide/reference_policies_evaluation-logic_policy-eval-basics.html`, 'Policy evaluation basics'),
  aws('iam-cross-account-eval', `${D}/IAM/latest/UserGuide/reference_policies_evaluation-logic-cross-account.html`, 'Cross-account policy evaluation logic'),
  aws('sec-account-separation', `${D}/wellarchitected/latest/security-pillar/aws-account-management-and-separation.html`, 'AWS account management and separation - Security Pillar'),
  aws('shield-protected-resources', `${D}/waf/latest/developerguide/ddos-advanced-summary-protected-resources.html`, 'Resources that Shield Advanced protects'),
  aws('shield-capabilities', `${D}/waf/latest/developerguide/ddos-advanced-summary-capabilities.html`, 'Shield Advanced capabilities and options'),
  aws('s3-replication-requirements', `${D}/AmazonS3/latest/userguide/replication-requirements.html`, 'Requirements for replication'),
  aws('alb-target-groups', `${D}/elasticloadbalancing/latest/application/load-balancer-target-groups.html`, 'Target groups for your Application Load Balancers'),
  aws('ec2-resize-ebs', `${D}/AWSEC2/latest/UserGuide/change-instance-type-of-ebs-backed-instance.html`, 'Change the instance type for your Amazon EC2 instance'),
  aws('ec2-resize-compat', `${D}/AWSEC2/latest/UserGuide/resize-limitations.html`, 'Compatibility for changing the instance type'),
  aws('graviton', 'https://aws.amazon.com/ec2/graviton/', 'AWS Graviton'),
  aws('drs-what-is', `${D}/drs/latest/userguide/what-is-drs.html`, 'What is Elastic Disaster Recovery?'),
  azure('learn-azure-asr', `${L}/site-recovery/site-recovery-overview`, 'About Azure Site Recovery'),
  aws('asg-warm-pools', `${D}/autoscaling/ec2/userguide/ec2-auto-scaling-warm-pools.html`, 'Decrease latency for applications with long boot times using warm pools'),
  aws('route53-geo', `${D}/Route53/latest/DeveloperGuide/routing-policy-geo.html`, 'Geolocation routing'),
  aws('lambda-snapstart', `${D}/lambda/latest/dg/snapstart.html`, 'Improving startup performance with Lambda SnapStart'),
  aws('aurora-endpoints', `${D}/AmazonRDS/latest/AuroraUserGuide/Aurora.Overview.Endpoints.html`, 'Amazon Aurora endpoint connections'),
  aws('elb-faqs', 'https://aws.amazon.com/elasticloadbalancing/faqs/', 'Elastic Load Balancing FAQs'),
  aws('elb-how-it-works', `${D}/elasticloadbalancing/latest/userguide/how-elastic-load-balancing-works.html`, 'How Elastic Load Balancing works'),
  aws('mq-what-is', `${D}/amazon-mq/latest/developer-guide/welcome.html`, 'What is Amazon MQ?'),
  aws('ebs-gp', `${D}/ebs/latest/userguide/general-purpose.html`, 'Amazon EBS General Purpose SSD volumes'),
  azure('learn-azure-servicebus', `${L}/service-bus-messaging/service-bus-messaging-overview`, 'What is Azure Service Bus?'),
  aws('elb-features', 'https://aws.amazon.com/elasticloadbalancing/features/', 'Elastic Load Balancing features'),
  aws('dx-encryption', `${D}/directconnect/latest/UserGuide/encryption-in-transit.html`, 'Encryption in AWS Direct Connect'),
  aws('s3-mpu-abort', `${D}/AmazonS3/latest/userguide/mpu-abort-incomplete-mpu-lifecycle-config.html`, 'Configuring a bucket lifecycle configuration to delete incomplete multipart uploads'),
  azure('learn-cosmos-consistency', `${L}/cosmos-db/consistency-levels`, 'Consistency levels in Azure Cosmos DB'),
  aws('dynamodb-read-consistency', `${D}/amazondynamodb/latest/developerguide/HowItWorks.ReadConsistency.html`, 'DynamoDB read consistency'),
  aws('ebs-archive-considerations', `${D}/ebs/latest/userguide/snapshot-archive-considerations.html`, 'Considerations and limitations for archiving Amazon EBS snapshots'),
  aws('ebs-archive-pricing', `${D}/ebs/latest/userguide/snapshot-archive-pricing.html`, 'Pricing and billing for archiving Amazon EBS snapshots'),
  aws('aurora-backups', `${D}/AmazonRDS/latest/AuroraUserGuide/Aurora.Managing.Backups.html`, 'Overview of backing up and restoring an Aurora DB cluster'),
  aws('vpc-pricing', 'https://aws.amazon.com/vpc/pricing/', 'Amazon VPC pricing'),
  aws('privatelink-pricing', 'https://aws.amazon.com/privatelink/pricing/', 'AWS PrivateLink pricing'),
  aws('vpc-flow-logs', `${D}/vpc/latest/userguide/flow-logs.html`, 'Logging IP traffic using VPC Flow Logs'),
  aws('vpc-nat-metrics', `${D}/vpc/latest/userguide/metrics-dimensions-nat-gateway.html`, 'NAT gateway metrics and dimensions'),
  aws('cost-anomaly', `${D}/cost-management/latest/userguide/manage-ad.html`, 'Detecting unusual spend with AWS Cost Anomaly Detection'),
  aws('secrets-access', `${D}/secretsmanager/latest/userguide/auth-and-access.html`, 'Authentication and access control for AWS Secrets Manager'),
  aws('dx-hosted', `${D}/directconnect/latest/UserGuide/hosted_connection.html`, 'Hosted Direct Connect connections'),
  aws('datasync-pricing', 'https://aws.amazon.com/datasync/pricing/', 'AWS DataSync pricing'),
  aws('transfer-pricing', 'https://aws.amazon.com/aws-transfer-family/pricing/', 'AWS Transfer Family pricing'),
  aws('waf-region-cost', `${D}/wellarchitected/latest/framework/cost_pricing_model_region_cost.html`, 'COST07-BP02 Choose Regions based on cost'),
  aws('rds-stop', `${D}/AmazonRDS/latest/UserGuide/USER_StopInstance.html`, 'Stopping an Amazon RDS DB instance temporarily'),
  aws('cloudfront-settings', `${D}/AmazonCloudFront/latest/DeveloperGuide/DownloadDistValuesGeneral.html`, 'CloudFront distribution settings'),
  aws('ec2-t-unlimited', `${D}/AWSEC2/latest/UserGuide/burstable-performance-instances-unlimited-mode.html`, 'Unlimited mode for burstable performance instances'),
  aws('s3-analytics', `${D}/AmazonS3/latest/userguide/analytics-storage-class.html`, 'Amazon S3 analytics – Storage Class Analysis'),
  aws('cloudfront-versioning', `${D}/AmazonCloudFront/latest/DeveloperGuide/UpdatingExistingObjects.html`, 'Use file versioning to update or remove content with a CloudFront distribution'),
  aws('vpc-nat-instances', `${D}/vpc/latest/userguide/work-with-nat-instances.html`, 'Work with NAT instances'),
];

export default sources;
