import type { Question } from '../../../src/content/types.ts';
import { mc, mr } from '../helpers.ts';

const questions: Question[] = [
  mc({
    id: 'archive-annex-001',
    building: 'archive-annex',
    bullets: ['1.3-K2'],
    d: 1,
    stem: 'A marketing team keeps campaign files in an Amazon S3 bucket. Team members sometimes overwrite a file with the wrong content, and the company wants to restore the earlier content of any file with the LEAST operational overhead. Which solution meets these requirements?',
    correct: ['Enable S3 Versioning on the bucket and restore the previous object version when needed', 'Each overwrite creates a new object version, so the earlier content can always be restored without any scripts.'],
    wrong: [
      ['Run a nightly script on an Amazon EC2 instance that copies every object to a second bucket', 'This relies on custom scripts to build and maintain, and it keeps only the content that existed at the last copy.'],
      ['Create an S3 Lifecycle rule that moves each object to S3 Glacier Flexible Retrieval after one day', 'A transition changes the storage class of the current object and is not a way to keep the earlier content of an overwritten file.'],
      ['Turn on S3 Block Public Access settings for the bucket', 'Block Public Access limits public exposure and does not preserve earlier content.'],
    ],
    slot: 0,
    evidence: [
      's3-versioning|Versioning-enabled buckets can help you recover objects from accidental deletion or overwrite.',
      's3-versioning|If you overwrite an object, it results in a new object version in the bucket. You can always restore the previous version.',
    ],
  }),
  mc({
    id: 'archive-annex-002',
    building: 'archive-annex',
    bullets: ['1.3-K2'],
    d: 1,
    stem: 'A company enabled S3 Versioning on a bucket that stores contract documents. A user then deletes one document with a simple delete request that does not specify a version ID. Which statement BEST describes the result?',
    correct: ['Amazon S3 adds a delete marker as the current version and keeps the earlier versions', 'A delete marker is added instead of removing the object permanently, so earlier versions remain recoverable.'],
    wrong: [
      ['Amazon S3 permanently removes every version of the document from the bucket right away', 'In a versioning-enabled bucket a simple delete does not remove the object permanently.'],
      ['Amazon S3 rejects the request because versioning-enabled buckets do not accept delete requests', 'Delete requests are accepted, and S3 handles them by adding a delete marker.'],
      ['Amazon S3 moves the document to S3 Glacier Deep Archive and keeps no other copy', 'A delete request does not change the storage class of any version.'],
    ],
    slot: 1,
    evidence: [
      's3-versioning|if you delete an object, Amazon S3 inserts a delete marker instead of removing the object permanently.',
      's3-versioning|The delete marker becomes the current object version.',
    ],
  }),
  mc({
    id: 'archive-annex-003',
    building: 'archive-annex',
    bullets: ['1.3-K2', '1.3-S5'],
    d: 3,
    tags: ['trap:dr-strategies'],
    stem: 'A company continuously replicates its order data to a second AWS Region. After a faulty release writes incorrect values into thousands of records, the company realizes that the replication may carry those values to the second Region. The company wants to be able to return the data to its state from before the release and wants to add this protection with the LEAST operational overhead. Which solution meets these requirements?',
    correct: ['Add scheduled point-in-time backups with AWS Backup under a retention setting', 'Point-in-time backups protect against data corruption in a way that continuous replication alone may not, and a backup plan automates them.'],
    wrong: [
      ['Raise the replication frequency so the second Region always has the newest data', 'A faster copy of the same incorrect values does not let the company return to the state before the release.'],
      ['Promote the copy in the second Region to be the primary database', 'The second Region holds the same replicated data, so this does not undo the incorrect values.'],
      ['Add a third replica of the data in another Availability Zone of the primary Region', 'Another replica improves availability but copies the same incorrect values and gives no earlier point to recover to.'],
    ],
    slot: 2,
    evidence: [
      'dr-options|Continuous data replication protects you against some types of disaster, but it may not protect you against data corruption or destruction unless your strategy also includes versioning of stored data or options for point-in-time recovery.',
      'backup-plans|You can assign resources to backup plans, and AWS Backup automatically backs up and retains backups for those resources according to the backup plan.',
    ],
  }),
  mc({
    id: 'archive-annex-004',
    building: 'archive-annex',
    bullets: ['1.3-K2'],
    d: 2,
    stem: 'A company runs Amazon EC2 instances with Amazon EBS volumes, Amazon RDS databases, Amazon DynamoDB tables, and Amazon EFS file systems. Each team backs up its own resources with separate scripts. The company wants one place to define backup schedules and retention for every one of these services with the LEAST operational overhead. Which solution meets these requirements?',
    correct: ['Create backup plans in AWS Backup and assign the resources to them', 'AWS Backup centralizes and automates data protection across services and removes the need for custom scripts.'],
    wrong: [
      ['Write a shared AWS Lambda function that calls each service snapshot API on a schedule', 'This is another custom script that the company has to build and maintain for every service.'],
      ['Configure the native backup feature of each service separately and track the schedules in a spreadsheet', 'This keeps backup tasks service-by-service and does not give one place to define schedules and retention.'],
      ['Store AWS CloudFormation templates for every resource and redeploy them after a failure', 'Templates recreate resources and do not back up the data that the resources hold.'],
    ],
    slot: 3,
    evidence: [
      'backup-what-is|AWS Backup is a fully-managed service that makes it easy to centralize and automate data protection across AWS services, in the cloud, and on premises.',
      'backup-what-is|It allows you to automate and consolidate backup tasks that were previously performed service-by-service, and removes the need to create custom scripts and manual processes.',
      'backup-plans|In AWS Backup, a backup plan is a policy expression that defines when and how you want to back up your AWS resources, such as Amazon DynamoDB tables or Amazon Elastic File System (Amazon EFS) file systems.',
    ],
  }),
  mc({
    id: 'archive-annex-005',
    building: 'archive-annex',
    bullets: ['1.3-S5'],
    d: 2,
    stem: 'A company has hundreds of resources in one account. Resources that carry the tag backup-tier set to gold need daily backups, and new tagged resources appear every week. The company wants every new tagged resource protected automatically with the LEAST ongoing effort. Which solution meets these requirements?',
    correct: ['Assign resources to an AWS Backup plan by using the backup-tier tag', 'AWS Backup integrates with tags, so a backup plan applies to every resource that carries the tag.'],
    wrong: [
      ['Start an on-demand backup job by hand each time a tagged resource is created', 'This is a manual step for every new resource and does not protect resources automatically.'],
      ['Create an AWS Config rule that reports resources that have no recent backup', 'A Config rule evaluates configuration and reports noncompliance, and it does not take backups.'],
      ['Add the identifier of each new resource to the backup plan after the team creates it', 'This repeats a manual change for every new resource instead of selecting resources by tag.'],
    ],
    slot: 0,
    evidence: [
      'backup-what-is|You can use AWS Backup to apply backup plans to your AWS resources in a wide variety of ways, including tagging them.',
      'backup-what-is|Integration with AWS tags enables you to quickly apply a backup plan to a group of AWS resources, so that they are backed up in a consistent and compliant manner.',
    ],
  }),
  mc({
    id: 'archive-annex-006',
    building: 'archive-annex',
    bullets: ['1.3-K3'],
    d: 2,
    stem: 'A company must keep backups of its Amazon EBS volumes for several years to meet retention rules. Backups older than a few weeks are rarely restored, and the company wants to reduce backup storage cost without writing custom code. Which solution meets these requirements MOST cost-effectively?',
    correct: ['Use a backup plan with a lifecycle that moves older backups to cold storage', 'A lifecycle policy automatically transitions backups from warm to cold storage, which lowers backup storage cost while retention is met.'],
    wrong: [
      ['Keep every backup in warm storage and delete backups by hand when the retention period ends', 'This pays the warm storage rate for rarely used backups and relies on a manual deletion step.'],
      ['Copy every backup to a second Region and keep both copies for the full retention period', 'A second copy adds storage and does not move any backup to a lower-cost tier.'],
      ['Apply AWS Backup Vault Lock to the vault and keep all backups in warm storage', 'Vault Lock prevents early deletion and does not lower the cost of storing backups.'],
    ],
    slot: 1,
    evidence: [
      'backup-what-is|AWS Backup enables you to meet compliance requirements while minimizing backup storage costs by storing backups in a low-cost cold storage tier.',
      'backup-what-is|You can configure lifecycle policies that automatically transition backups from warm storage to cold storage according to a schedule that you define.',
      'backup-create-plan|Cold storage for Amazon EBS is Amazon EBS Snapshots Archive.',
    ],
  }),
  mc({
    id: 'archive-annex-007',
    building: 'archive-annex',
    bullets: ['1.3-K3'],
    d: 2,
    stem: 'A company stores data in several hundred Amazon S3 buckets and does not know which ones hold personal data. The security team wants continuous, broad visibility into where sensitive data might reside across the whole S3 estate without defining each bucket and schedule by hand. Which solution meets these requirements with the LEAST operational effort?',
    correct: ['Turn on automated sensitive data discovery in Amazon Macie', 'Automated sensitive data discovery gives broad visibility into where sensitive data might reside in the S3 data estate.'],
    wrong: [
      ['Create one Amazon Macie sensitive data discovery job for a single bucket and run it once', 'A job is a deeper, targeted analysis of the buckets that you define, so it does not give broad visibility across the whole estate.'],
      ['Enable Amazon GuardDuty and review its findings for each bucket', 'GuardDuty analyzes logs for threats and does not classify what data the objects contain.'],
      ['Deploy an AWS Config rule that checks every bucket for personal data', 'Config rules evaluate configuration settings of resources and do not inspect object contents.'],
    ],
    slot: 2,
    evidence: [
      'macie-discovery|Automated sensitive data discovery provides broad visibility into where sensitive data might reside in your Amazon S3 data estate.',
      'macie-discovery|Sensitive data discovery jobs provide deeper, more targeted analysis.',
    ],
  }),
  mc({
    id: 'archive-annex-008',
    building: 'archive-annex',
    bullets: ['1.3-K3'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A company stores documents in Amazon S3 that contain internal customer numbers in the format CUST- followed by eight digits. The built-in Amazon Macie criteria do not detect this pattern, and the company wants Macie to report every object that contains such a number. Which solution meets these requirements with the LEAST effort?',
    correct: ['Create a Macie custom data identifier with a regular expression', 'A custom data identifier defines a text pattern to match, which detects data that reflects the company\'s own scenarios.'],
    wrong: [
      ['Add the pattern to a Macie allow list that is used by the discovery job', 'An allow list holds text patterns that Macie ignores, so matching numbers would no longer be reported.'],
      ['Enable AWS CloudTrail data events for the buckets that hold the documents', 'CloudTrail records API activity and does not inspect the contents of objects.'],
      ['Run an Amazon Inspector scan against the buckets that hold the documents', 'Inspector scans EC2 instances, container images, and Lambda functions for vulnerabilities, not object contents.'],
    ],
    slot: 3,
    evidence: [
      'macie-discovery|Each custom data identifier specifies a regular expression (regex) that defines a text pattern to match and, optionally, character sequences and a proximity rule that refine the results.',
      'macie-discovery|Allow lists – These specify text and text patterns that you want Macie to ignore.',
      'inspector|Amazon Inspector discovers and scans Amazon EC2 instances, container images in Amazon ECR, and Lambda functions.',
    ],
  }),
  mc({
    id: 'archive-annex-009',
    building: 'archive-annex',
    bullets: ['1.3-K3'],
    d: 3,
    stem: 'A company keeps customer records in an Amazon RDS for PostgreSQL database and must find out whether the records contain personal data. The security team wants to use Amazon Macie for the analysis and does not want to write a custom scanner. Which solution meets these requirements with the LEAST custom code?',
    correct: ['Export a snapshot of the database to Amazon S3 in Apache Parquet format and run a Macie sensitive data discovery job on the exported data', 'Macie is optimized for Amazon S3, and exporting RDS snapshots to S3 lets a job analyze data that is stored elsewhere.'],
    wrong: [
      ['Register the endpoint of the DB instance with Macie and start an automated sensitive data discovery run', 'Macie analyzes objects in Amazon S3 general purpose buckets, so it has no way to connect to a database endpoint.'],
      ['Run an Amazon Inspector scan of the DB instance to look for personal data in the tables', 'Inspector scans workloads for software vulnerabilities and unintended network exposure, not for personal data.'],
      ['Create an AWS Backup copy of the database and point Macie at the backup vault', 'A backup vault is not an S3 bucket, and Macie analyzes objects in S3.'],
    ],
    slot: 0,
    evidence: [
      'macie-discovery|Although Macie is optimized for Amazon S3, you can use it to discover sensitive data in resources that you currently store elsewhere.',
      'macie-discovery|For example, export Amazon Relational Database Service or Amazon Aurora snapshots to Amazon S3 in Apache Parquet format.',
      'macie-discovery|You can then create a job to analyze the data in Amazon S3.',
    ],
  }),
  mr({
    id: 'archive-annex-010',
    building: 'archive-annex',
    bullets: ['1.3-K3'],
    d: 2,
    stem: 'A security team wants Amazon Macie findings to appear in a broader view of the company security posture, and it wants a message sent to an Amazon SNS topic whenever Macie reports sensitive data. Which TWO actions meet these requirements with the LEAST custom development? (Choose two.)',
    correct: [
      ['Configure Macie to publish its findings to AWS Security Hub', 'Macie can also publish findings to Security Hub, which gives a broader view of security posture.'],
      ['Create an Amazon EventBridge rule for Macie findings that targets the SNS topic', 'Macie publishes findings to EventBridge as events, and EventBridge can route them to SNS topics.'],
    ],
    wrong: [
      ['Create an AWS Config rule that sends noncompliant bucket notifications to the SNS topic', 'Config rules report on resource configuration and do not carry Macie findings.'],
      ['Turn on S3 server access logging and parse the logs for personal data', 'Access logs record requests and are not Macie findings, and parsing them needs custom code.'],
      ['Ask AWS CloudTrail to deliver Macie findings directly to the SNS topic', 'CloudTrail records API activity and is not the way Macie findings are routed.'],
    ],
    slots: [1, 3],
    evidence: [
      'macie|Macie publishes findings to Amazon EventBridge as events.',
      'macie|EventBridge is a serverless event bus service that can route findings data to targets such as AWS Lambda functions and Amazon Simple Notification Service (Amazon SNS) topics.',
      'macie|You can configure Macie to also publish findings to AWS Security Hub CSPM.',
    ],
  }),
  mc({
    id: 'archive-annex-011',
    building: 'archive-annex',
    bullets: ['1.3-K3'],
    d: 2,
    stem: 'A financial services company must store trade confirmations in Amazon S3 so that no user, including the AWS account root user, can delete or overwrite an object version before its seven-year retention period ends. Which solution BEST meets these requirements?',
    correct: ['Enable S3 Versioning and S3 Object Lock, and apply a seven-year retention period in compliance mode', 'Compliance mode prevents any user, including the root user, from overwriting or deleting a protected object version, and Object Lock needs versioning.'],
    wrong: [
      ['Apply a seven-year retention period in governance mode and grant the BypassGovernanceRetention permission only to administrators', 'In governance mode, users with the special permission can still delete the object or alter its lock settings.'],
      ['Place an S3 Object Lock legal hold on every object version in the bucket', 'A legal hold has no fixed period and can be placed and removed by any user who has the legal hold permission.'],
      ['Copy every object to a bucket in a second Region with S3 Cross-Region Replication', 'Replication creates a second copy and does not prevent deletion of an object version in the bucket.'],
    ],
    slot: 1,
    evidence: [
      's3-object-lock|In compliance mode, a protected object version can\'t be overwritten or deleted by any user, including the root user in your AWS account.',
      's3-object-lock|Object Lock works only in buckets that have S3 Versioning enabled.',
      's3-object-lock|Legal holds can be freely placed and removed by any user who has the s3:PutObjectLegalHold permission.',
    ],
  }),
  mc({
    id: 'archive-annex-012',
    building: 'archive-annex',
    bullets: ['1.3-K3'],
    d: 2,
    stem: 'A media company stores raw footage in Amazon S3. It wants most users to be unable to delete the footage for one year, but the storage operations team must be able to remove objects early if a project is cancelled. The company also wants to test the retention setting before committing to a stricter one. Which solution BEST meets these requirements?',
    correct: ['Use S3 Object Lock in governance mode and grant the bypass permission to the operations team', 'Governance mode protects objects from most users while selected users can still alter retention settings, and it can be used to test settings.'],
    wrong: [
      ['Use S3 Object Lock in compliance mode with a one-year retention period for all footage objects', 'In compliance mode no user, including the root user, can delete the object and the retention period cannot be shortened.'],
      ['Use an S3 Lifecycle rule that expires every object after one year', 'An expiration rule deletes objects at the end of the period and does not stop users from deleting them earlier.'],
      ['Place a legal hold on each object and give the operations team no further permissions', 'A legal hold has no expiration date and does not provide a one-year retention period.'],
    ],
    slot: 2,
    evidence: [
      's3-object-lock|With governance mode, you protect objects against being deleted by most users, but you can still grant some users permission to alter the retention settings or delete the objects if necessary.',
      's3-object-lock|You can also use governance mode to test retention-period settings before creating a compliance-mode retention period.',
      's3-object-lock|To override or remove governance-mode retention settings, you must have the s3:BypassGovernanceRetention permission',
    ],
  }),
  mc({
    id: 'archive-annex-013',
    building: 'archive-annex',
    bullets: ['1.3-K3'],
    d: 2,
    stem: 'A company learns that it will be involved in a lawsuit. Legal counsel says that specific objects in an Amazon S3 bucket must stay unchanged until counsel releases them, and nobody can say when that will be. Which solution meets these requirements with the LEAST operational effort?',
    correct: ['Place an S3 Object Lock legal hold on the objects in a bucket that has versioning enabled', 'A legal hold has no fixed amount of time and stays in place until it is removed, which fits an open-ended release date.'],
    wrong: [
      ['Set a compliance-mode Object Lock retention period of ten years on each relevant object version in the bucket', 'This guesses a fixed period, and a compliance-mode retention period cannot be shortened if counsel releases the objects sooner.'],
      ['Set a governance-mode retention period of one year and extend it every year', 'Users with special permissions can still delete the objects, and someone must remember to extend the period.'],
      ['Enable S3 Versioning on the bucket and leave the objects as they are', 'Versioning keeps earlier versions but does not stop an object version from being deleted.'],
    ],
    slot: 3,
    evidence: [
      's3-object-lock|However, a legal hold doesn\'t have an associated fixed amount of time and remains in effect until removed.',
      's3-object-lock|You can use Legal Hold when you are not sure for how long you want your objects to stay immutable.',
      's3-object-lock|Object Lock works only in buckets that have S3 Versioning enabled.',
    ],
  }),
  mr({
    id: 'archive-annex-014',
    building: 'archive-annex',
    bullets: ['1.3-S5'],
    d: 3,
    stem: 'A company has an Amazon S3 bucket with S3 Object Lock enabled and wants to replicate its objects to a new bucket in another AWS Region. Which TWO settings must be configured on the destination bucket for replication to work? (Choose two.)',
    correct: [
      ['Turn on S3 Versioning for the destination bucket', 'Both the source bucket and the destination bucket must have versioning enabled.'],
      ['Turn on S3 Object Lock for the destination bucket', 'If the source bucket has Object Lock enabled, the destination buckets must also have Object Lock enabled.'],
    ],
    wrong: [
      ['Configure the destination bucket as a Requester Pays bucket', 'The destination buckets cannot be configured as Requester Pays buckets.'],
      ['Leave S3 Versioning off for the destination bucket to avoid duplicate versions', 'Replication requires versioning to be enabled on the destination bucket as well as the source.'],
      ['Add an S3 Lifecycle rule that expires every object in the destination bucket after one day', 'This is not a requirement for replication and would delete the replicas.'],
    ],
    slots: [0, 2],
    evidence: [
      's3-replication-requirements|Both source and destination buckets must have versioning enabled.',
      's3-replication-requirements|If the source bucket has S3 Object Lock enabled, the destination buckets must also have S3 Object Lock enabled.',
      's3-replication-requirements|The destination buckets cannot be configured as Requester Pays buckets.',
    ],
  }),
  mc({
    id: 'archive-annex-015',
    building: 'archive-annex',
    bullets: ['1.3-S5'],
    d: 1,
    stem: 'A company stores archives in Amazon S3 in one Region. A compliance rule requires a second copy in a different geographic area, farther away than separate Availability Zones, and the copy must be created automatically as objects are written. Which solution is the SIMPLEST that meets these requirements?',
    correct: ['Configure S3 Cross-Region Replication to a bucket in another Region', 'Cross-Region Replication copies objects to buckets in different Regions to satisfy requirements for greater distance.'],
    wrong: [
      ['Configure S3 Same-Region Replication to a second bucket in the same Region', 'The copy stays in the same Region, so it is not farther away than the Availability Zones.'],
      ['Rely on the S3 Standard storage class, which already stores objects across multiple Availability Zones', 'Availability Zones in one Region do not satisfy a rule that asks for a greater distance.'],
      ['Enable S3 Versioning on the bucket so that earlier versions are kept', 'Versions are kept in the same bucket and Region, so there is no second geographic area.'],
    ],
    slot: 0,
    evidence: [
      's3-replication|Although Amazon S3 stores your data across multiple geographically distant Availability Zones by default, compliance requirements might dictate that you store data at even greater distances.',
      's3-replication|To satisfy these requirements, use Cross-Region Replication to replicate data between distant AWS Regions.',
    ],
  }),
  mc({
    id: 'archive-annex-016',
    building: 'archive-annex',
    bullets: ['1.3-S5'],
    d: 2,
    stem: 'A company configured S3 replication on a bucket last week. Objects uploaded since then are copied, but the millions of objects that were already in the bucket are missing from the destination bucket. The company wants those objects copied with the LEAST effort. Which solution meets this requirement?',
    correct: ['Run an S3 Batch Replication job for the existing objects', 'Live replication skips objects that existed before it was set up, and Batch Replication replicates existing objects on demand.'],
    wrong: [
      ['Turn on S3 Replication Time Control for the replication rule', 'This controls the time frame for replicating new objects and does not copy objects that already existed.'],
      ['Delete the replication rule and create it again so that it rescans the bucket', 'Live replication does not replicate objects that existed before replication was set up, however often the rule is created.'],
      ['Enable S3 Transfer Acceleration on both buckets and upload the objects again', 'This changes the upload path and forces a manual upload of every existing object.'],
    ],
    slot: 1,
    evidence: [
      's3-replication|Live replication doesn\'t replicate any objects that existed in the bucket before you set up replication.',
      's3-replication|To replicate existing objects from the source bucket to one or more destination buckets on demand, use S3 Batch Replication.',
    ],
  }),
  mc({
    id: 'archive-annex-017',
    building: 'archive-annex',
    bullets: ['1.3-S5'],
    d: 2,
    stem: 'A company has a contract that requires new objects in an Amazon S3 bucket to reach a bucket in a second Region within a predictable time frame that is backed by a service-level agreement. Which solution meets this requirement?',
    correct: ['Use S3 Cross-Region Replication with S3 Replication Time Control turned on', 'S3 Replication Time Control replicates new objects within 15 minutes and is backed by a service-level agreement.'],
    wrong: [
      ['Use S3 Cross-Region Replication without S3 Replication Time Control', 'Standard replication does not come with the predictable, SLA-backed time frame that the contract asks for.'],
      ['Run an S3 Batch Replication job every hour to copy the new objects to the second Region', 'Batch Replication is an on-demand job, and S3 Replication Time Control does not apply to it.'],
      ['Schedule an AWS Backup copy of the bucket to the second Region every hour', 'A scheduled backup copy is not live object replication with a replication time commitment.'],
    ],
    slot: 2,
    evidence: [
      's3-replication|S3 RTC replicates 99.99 percent of new objects stored in Amazon S3 within 15 minutes (backed by a service-level agreement).',
      's3-replication|NoteS3 RTC does not apply to Batch Replication.',
    ],
  }),
  mc({
    id: 'archive-annex-018',
    building: 'archive-annex',
    bullets: ['1.3-S5'],
    d: 2,
    stem: 'A company has 12 AWS accounts in one Region, and each account writes application logs to its own S3 bucket. A regulation does not allow the data to leave the country, so everything must stay in this Region. The company wants the logs consolidated automatically into one bucket in a log archive account. Which solution meets these requirements?',
    correct: ['Configure S3 Same-Region Replication from each account bucket to the central bucket', 'Same-Region Replication aggregates logs from several accounts into one in-Region bucket and keeps data in the Region.'],
    wrong: [
      ['Configure S3 Cross-Region Replication from each account bucket to a bucket in another Region', 'The data would leave the Region, which the regulation does not allow.'],
      ['Run an S3 Batch Replication job by hand every night for each account bucket', 'Batch Replication is an on-demand option, so the consolidation would not be automatic.'],
      ['Enable S3 Transfer Acceleration on the central bucket and upload the logs to it', 'Transfer Acceleration speeds up uploads and does not copy the logs from other buckets.'],
    ],
    slot: 3,
    evidence: [
      's3-replication|Aggregate logs into a single bucket – If you store logs in multiple buckets or across multiple accounts, you can easily replicate logs into a single, in-Region bucket.',
      's3-replication|Same-Region Replication can help you automatically replicate critical data when compliance regulations don\'t allow the data to leave your country.',
    ],
  }),
  mc({
    id: 'archive-annex-019',
    building: 'archive-annex',
    bullets: ['1.3-S5'],
    d: 3,
    stem: 'A company replicates objects from a production account to a bucket in a separate security account in another Region. The replicas are rarely read and must be stored in the lowest-cost archive class, and the security account must own the replicas so that production account users cannot access them. The company wants the LEAST operational overhead. Which solution meets these requirements?',
    correct: ['Create a Cross-Region Replication rule that sets the destination storage class to S3 Glacier Deep Archive and changes replica ownership to the destination account', 'Replication can put objects directly into an archive class, and the owner override option gives the destination account ownership.'],
    wrong: [
      ['Create a Cross-Region Replication rule to S3 Standard and run an AWS Lambda function that copies each replica into S3 Glacier Deep Archive', 'The copy step is custom code to build and maintain when replication can set the storage class directly.'],
      ['Create a Same-Region Replication rule that sets the destination storage class to S3 Glacier Deep Archive and changes replica ownership', 'Same-Region Replication copies within one Region, so the replicas would not be in another Region.'],
      ['Create a Cross-Region Replication rule that sets S3 Glacier Deep Archive as the storage class and leaves the production account as owner of the replicas', 'The production account would still own the replicas, so its users could keep access to them.'],
    ],
    slot: 0,
    evidence: [
      's3-replication|You can use replication to directly put objects into S3 Glacier Flexible Retrieval, S3 Glacier Deep Archive, or another storage class in the destination buckets.',
      's3-replication|Regardless of who owns the source object, you can tell Amazon S3 to change replica ownership to the AWS account that owns the destination bucket.',
      's3-replication|You can use this option to restrict access to object replicas.',
    ],
  }),
  mc({
    id: 'archive-annex-020',
    building: 'archive-annex',
    bullets: ['1.3-S5'],
    d: 3,
    stem: 'A company has 40 accounts in an AWS Organizations structure. Compliance requires backups of the Amazon RDS databases and Amazon EBS volumes in every account to follow one policy defined in a single place and to be copied into a dedicated backup account. The company wants the LEAST operational overhead. Which solution meets these requirements?',
    correct: ['Use AWS Backup cross-account management to apply backup plans across the organization and copy backups to a vault in the backup account', 'Cross-account management applies backup plans across the accounts of the organization, and backups can be copied to another account in the organization.'],
    wrong: [
      ['Create separate backup plans by hand in each account and copy the backups with custom scripts', 'This duplicates the plans in every account and adds scripts, which is the manual effort that cross-account management removes.'],
      ['Deploy AWS Config conformance packs to every account to take the backups and copy them', 'Conformance packs deploy rules and remediation actions and are not a backup service.'],
      ['Schedule an AWS Lambda function in each account that shares native snapshots with the backup account', 'This relies on custom code in 40 accounts and gives no single place to define the policy.'],
    ],
    slot: 1,
    evidence: [
      'backup-what-is|You can use AWS Backup to manage your backups across all AWS accounts inside your AWS Organizations structure.',
      'backup-what-is|With cross-account management, you can automatically use backup policies to apply backup plans across the AWS accounts within your organization.',
      'backup-what-is|You can also copy backups to multiple different AWS accounts inside your AWS Organizations management structure.',
    ],
  }),
  mc({
    id: 'archive-annex-021',
    building: 'archive-annex',
    bullets: ['1.3-K2', '1.3-S5'],
    d: 1,
    tags: ['mock-reserve'],
    stem: 'A company runs an Amazon RDS for MySQL database. After an accidental data change, the company wants to be able to restore the database to any point in time during the previous two weeks. Which solution is the SIMPLEST that meets this requirement?',
    correct: ['Keep automated backups turned on with a backup retention period of 14 days', 'Automated backups let the company recover to any point in time during the backup retention period.'],
    wrong: [
      ['Take one manual DB snapshot every week and keep each snapshot for two weeks', 'A snapshot captures one moment, so the database could not be restored to any point in between.'],
      ['Create a read replica of the database in another Availability Zone', 'A read replica is a live copy of the data, including any accidental change, and is not a backup to restore from.'],
      ['Convert the database to a Multi-AZ deployment', 'Multi-AZ improves availability and does not give the company earlier points in time to restore.'],
    ],
    slot: 2,
    evidence: [
      'rds-automated-backups|If necessary, you can recover your DB instance to any point in time during the backup retention period.',
      'rds-backup-retention|You can set the backup retention period of a DB instance to between 0 and 35 days.',
    ],
  }),
  mc({
    id: 'archive-annex-022',
    building: 'archive-annex',
    bullets: ['1.3-K2'],
    d: 1,
    tags: ['mock-reserve'],
    stem: 'An engineer says that Amazon EBS automatically backs up the data on every volume, so the company has no backup process for its Amazon EC2 instances. The company must be able to restore the volumes after a failure. Which action BEST addresses the requirement?',
    correct: ['Create an AWS Backup plan that takes scheduled snapshots of the volumes', 'AWS does not back up EBS volume data automatically, and a backup plan creates the snapshots on a schedule.'],
    wrong: [
      ['Do nothing, because EBS already backs up the volumes to Amazon S3 on its own', 'AWS does not automatically back up the data stored on EBS volumes.'],
      ['Turn on S3 Versioning for the bucket that holds the snapshots', 'Snapshots are stored in S3 buckets that you cannot access directly, and no snapshots exist until someone creates them.'],
      ['Attach each volume to a second instance with EBS Multi-Attach', 'Multi-Attach lets several instances use a volume and does not create a backup of it.'],
    ],
    slot: 3,
    evidence: [
      'ebs-snapshots|AWS does not automatically back up the data stored on your EBS volumes.',
      'ebs-snapshots|it is your responsibility to create EBS snapshots on a regular basis, or to set up automatic snapshot creation by using Automate backups with Amazon Data Lifecycle Manager or AWS Backup.',
      'ebs-snapshots|Snapshots are stored in Amazon S3, in S3 buckets that you can\'t access directly.',
    ],
  }),
  mc({
    id: 'archive-annex-023',
    building: 'archive-annex',
    bullets: ['1.3-K3'],
    d: 3,
    stem: 'A company uses AWS Backup to protect Amazon RDS and Amazon EBS resources. A regulator requires that no backup can be deleted by any user, including administrators with full IAM permissions, until a seven-year minimum retention ends. Backup jobs that use a shorter retention period must fail. The company accepts that the lock cannot be removed after a short testing period. Which solution BEST meets these requirements?',
    correct: ['Apply AWS Backup Vault Lock in compliance mode with a seven-year minimum retention and a grace time for testing', 'After the grace time expires a compliance-mode vault lock is immutable, and jobs shorter than the minimum retention fail.'],
    wrong: [
      ['Apply AWS Backup Vault Lock in governance mode with a seven-year minimum retention', 'A vault lock in governance mode can have the lock removed by users who have sufficient IAM permissions.'],
      ['Set the backup plan lifecycle to seven years and rely on IAM policies to restrict deletion', 'IAM policies can be changed by privileged users, so nothing enforces retention against administrators.'],
      ['Copy the backups to a second Region and keep the copies in a vault without a lock', 'A copy in another vault does not stop a user with permissions from deleting backups in either vault.'],
    ],
    slot: 0,
    evidence: [
      'backup-vault-lock|Vaults locked in governance mode can have the lock removed by users with sufficient IAM permissions.',
      'backup-vault-lock|Once the grace time expires, the vault and its lock are immutable and cannot be changed or deleted by any user or by AWS.',
      'backup-vault-lock|If specified, backup and copy jobs to this vault with lifecycle retention periods shorter than the minimum retention period will fail.',
    ],
  }),
  mr({
    id: 'archive-annex-024',
    building: 'archive-annex',
    bullets: ['1.3-K3'],
    d: 2,
    stem: 'A company must show auditors that its AWS Backup backups follow the backup policy and must prevent anyone, including privileged users, from deleting backups before their retention period ends. Which TWO actions meet these requirements with the LEAST custom work? (Choose two.)',
    correct: [
      ['Turn on AWS Backup Audit Manager with controls that match the backup policy and review its daily reports', 'Audit Manager finds resources that are not compliant with the controls and generates daily reports as evidence.'],
      ['Apply AWS Backup Vault Lock to the backup vault', 'Vault Lock prevents anyone, including privileged users, from deleting backups or altering their retention period.'],
    ],
    wrong: [
      ['Download the company backup reports from AWS Artifact', 'AWS Artifact provides AWS compliance documents, and customers must obtain evidence of their own compliance themselves.'],
      ['Run an Amazon Macie sensitive data discovery job on the backup vault', 'Macie analyzes objects in S3 for sensitive data and does not report on backup policy compliance.'],
      ['Enable Amazon GuardDuty in the account that owns the vault', 'GuardDuty detects threats from logs and does not report on backup compliance or enforce retention.'],
    ],
    slots: [2, 4],
    evidence: [
      'backup-what-is|AWS Backup Audit Manager can help you locate specific activities and resources that are not yet compliant with the controls that you defined.',
      'backup-what-is|It also generates daily reports that you can use to demonstrate evidence of compliance with your controls over time.',
      'backup-what-is|You can use AWS Backup Vault Lock to prevent anyone (including you) from deleting backups or altering their retention period.',
      'artifact|AWS customers are responsible for developing or obtaining documents that demonstrate the security and compliance of their companies.',
    ],
  }),
  mr({
    id: 'archive-annex-025',
    building: 'archive-annex',
    bullets: ['1.3-K2', '1.3-K3'],
    d: 3,
    stem: 'A company stores invoices in an Amazon S3 bucket. It wants to restore the earlier content of any invoice that an employee overwrites, and it also wants every object version to be protected from deletion for 90 days after it is written, without setting a lock on each object. Which TWO actions meet these requirements? (Choose two.)',
    correct: [
      ['Enable S3 Versioning on the bucket', 'Each overwrite creates a new object version, so the previous version can be restored.'],
      ['Enable S3 Object Lock and set a default retention period on the bucket', 'A retention period set on the bucket properties applies to all objects in the bucket automatically.'],
    ],
    wrong: [
      ['Add an S3 Lifecycle rule that moves each object to S3 Glacier Flexible Retrieval after one day', 'A transition changes the storage class and does not keep earlier versions or protect against deletion.'],
      ['Turn on all four S3 Block Public Access settings for the bucket', 'Block Public Access limits public exposure and does not preserve versions or prevent deletion.'],
      ['Run an Amazon Macie sensitive data discovery job on the bucket every week', 'Macie finds sensitive data and neither restores earlier content nor protects objects from deletion.'],
    ],
    slots: [0, 3],
    evidence: [
      's3-versioning|If you overwrite an object, it results in a new object version in the bucket. You can always restore the previous version.',
      's3-object-lock|You can place a retention period explicitly on an individual object version or on a bucket\'s properties so that it applies to all objects in the bucket automatically.',
      's3-object-lock|Object Lock works only in buckets that have S3 Versioning enabled.',
    ],
  }),
  mr({
    id: 'archive-annex-026',
    building: 'archive-annex',
    bullets: ['1.3-S5'],
    d: 2,
    stem: 'A company wants live replication from a bucket in one AWS account to a bucket owned by a different AWS account in another Region. The source bucket does not use S3 Object Lock. Which TWO requirements apply to this setup? (Choose two.)',
    correct: [
      ['Versioning must be enabled on both the source bucket and the destination bucket', 'Replication requires versioning on both buckets.'],
      ['The destination bucket owner must grant the source bucket owner permission to replicate with a bucket policy', 'In a cross-account setup the destination bucket owner must grant this permission with a bucket policy.'],
    ],
    wrong: [
      ['The destination bucket must be configured as a Requester Pays bucket', 'The destination buckets cannot be configured as Requester Pays buckets.'],
      ['S3 Object Lock must be turned on for the destination bucket', 'This is required only when the source bucket has Object Lock enabled, which is not the case here.'],
      ['S3 Transfer Acceleration must be enabled on both buckets', 'Transfer Acceleration speeds up transfers to a bucket and is not a requirement for replication.'],
    ],
    slots: [1, 4],
    evidence: [
      's3-replication-requirements|Both source and destination buckets must have versioning enabled.',
      's3-replication-requirements|The owner of the destination buckets must grant the owner of the source bucket permissions to replicate objects with a bucket policy.',
      's3-replication-requirements|The destination buckets cannot be configured as Requester Pays buckets.',
    ],
  }),
];

export default questions;
