import type { Question } from '../../../src/content/types.ts';
import { mc, mr } from '../helpers.ts';

const questions: Question[] = [
  mc({
    id: 'certificate-office-001',
    building: 'certificate-office',
    bullets: ['1.3-S3'],
    d: 1,
    stem: 'A company runs a public website on Amazon EC2 instances behind an Application Load Balancer. Clients must connect with HTTPS, and the load balancer, not the instances, must do the TLS decryption work so that the application can focus on business logic. Which solution BEST meets these requirements?',
    correct: ['Add an HTTPS listener to the load balancer and deploy an ACM certificate on it', 'An HTTPS listener offloads encryption and decryption to the load balancer, and it needs at least one server certificate.'],
    wrong: [
      ['Add a TCP listener on port 443 to the Application Load Balancer', 'Listeners on an Application Load Balancer support only the HTTP and HTTPS protocols.'],
      ['Install the certificate on every instance and keep an HTTP listener on the load balancer', 'The instances, not the load balancer, would then do the encryption work.'],
      ['Attach a customer managed KMS key to the load balancer to terminate TLS connections', 'A KMS key protects data at rest and does not terminate TLS connections.'],
    ],
    slot: 0,
    evidence: [
      'alb-listeners|You can use an HTTPS listener to offload the work of encryption and decryption to your load balancer so that your applications can focus on their business logic.',
      'alb-listeners|Listeners support the following protocols and ports: Protocols: HTTP, HTTPS',
      'alb-https-listener|To create an HTTPS listener, you must deploy at least one SSL server certificate on your load balancer.',
    ],
  }),
  mc({
    id: 'certificate-office-002',
    building: 'certificate-office',
    bullets: ['1.3-S3'],
    d: 2,
    tags: ['placement-eligible'],
    stem: 'A company serves a static website through Amazon CloudFront from an Amazon S3 bucket. The bucket and all other company resources are in eu-west-1. The company will use its own domain name over HTTPS with a public ACM certificate. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Request the public certificate in us-east-1 and attach it to the distribution', 'CloudFront requires its ACM certificate in us-east-1, and it is then distributed to all the locations of the distribution.'],
    wrong: [
      ['Request the public certificate in eu-west-1 next to the bucket and attach it to the distribution', 'CloudFront can use an ACM certificate only if it is requested or imported in us-east-1, not in the Region of the bucket.'],
      ['Request a separate certificate in every Region that has CloudFront edge locations', 'This is unnecessary, because the us-east-1 certificate is distributed to all geographic locations of the distribution.'],
      ['Request the certificate in eu-west-1 and copy it to the US East (N. Virginia) Region', 'A certificate cannot be copied between Regions, so a new one must be requested or imported there.'],
    ],
    slot: 1,
    evidence: [
      'cf-https-requirements|To use an ACM certificate with a CloudFront distribution, make sure you request (or import) the certificate in the US East (N. Virginia) Region (us-east-1).',
      'acm-overview|ACM certificates in this region that are associated with a CloudFront distribution are distributed to all the geographic locations configured for that distribution.',
      'acm-overview|You cannot copy a certificate between regions.',
    ],
  }),
  mr({
    id: 'certificate-office-003',
    building: 'certificate-office',
    bullets: ['1.3-S3'],
    d: 3,
    tags: ['placement-eligible'],
    stem: 'A company serves its application through Amazon CloudFront with an Application Load Balancer in eu-west-1 as the custom origin. Viewers use https://www.example.com and the origin domain name is origin.example.com. Traffic must be encrypted between viewers and CloudFront and between CloudFront and the origin, using ACM certificates. Which TWO actions meet these requirements? (Choose two.)',
    correct: [
      ['Request an ACM certificate for www.example.com in us-east-1 and associate it with the distribution', 'A certificate for the viewer-facing name must be requested or imported in us-east-1 for CloudFront.'],
      ['Request an ACM certificate for origin.example.com in eu-west-1, deploy it on an HTTPS listener of the load balancer, and set the origin protocol policy to HTTPS Only', 'The origin certificate lives in the load balancer\'s Region, and HTTPS Only makes CloudFront use only HTTPS to the origin.'],
    ],
    wrong: [
      ['Request one certificate in us-east-1 and deploy it on both the distribution and the load balancer', 'ACM certificates are regional and cannot be copied between Regions, so the us-east-1 certificate cannot be deployed on a load balancer in eu-west-1.'],
      ['Request the viewer-facing certificate in eu-west-1, because the origin is in that Region', 'The viewer-facing certificate for CloudFront must be in us-east-1 regardless of the Region of the origin.'],
      ['Leave the origin protocol policy on HTTP Only and rely on the viewer HTTPS setting', 'The hop from CloudFront to the origin would then be unencrypted, which the requirements rule out.'],
    ],
    slots: [0, 3],
    evidence: [
      'cf-https-requirements|If you want to require HTTPS between CloudFront and your origin, and you\'re using a load balancer in Elastic Load Balancing as your origin, you can request or import the certificate in any AWS Region.',
      'cf-origin-https|HTTPS Only – CloudFront uses only HTTPS to communicate with your custom origin.',
      'acm-overview|Certificates in ACM are regional resources.',
      'acm-overview|You cannot copy a certificate between regions.',
    ],
  }),
  mc({
    id: 'certificate-office-004',
    building: 'certificate-office',
    bullets: ['1.3-S3'],
    d: 3,
    tags: ['placement-eligible'],
    stem: 'A company hosts a static site in an Amazon S3 bucket configured as a website endpoint, with Amazon CloudFront in front of it. A new compliance rule requires HTTPS between CloudFront and the origin. Which solution meets this requirement with the LEAST operational overhead?',
    correct: ['Switch to the standard S3 bucket origin and use the Redirect HTTP to HTTPS viewer policy', 'An S3 origin that supports HTTPS provides its own certificate, and HTTPS to S3 follows the viewer protocol policy.'],
    wrong: [
      ['Set the origin protocol policy to HTTPS Only on the existing S3 website endpoint origin', 'Amazon S3 does not support HTTPS for website endpoints, so CloudFront cannot use HTTPS with that origin.'],
      ['Import a third-party certificate into ACM and select it for the S3 website endpoint', 'The website endpoint cannot serve HTTPS, so no certificate can be installed on it.'],
      ['Install an ACM certificate on the S3 bucket and keep the website endpoint origin', 'S3 provides the certificate when HTTPS is used, and a website endpoint does not support HTTPS in any case.'],
    ],
    slot: 2,
    evidence: [
      'cf-s3-https|If your Amazon S3 bucket is configured as a website endpoint, you can\'t configure CloudFront to use HTTPS to communicate with your origin because Amazon S3 doesn\'t support HTTPS connections in that configuration.',
      'cf-s3-https|If you want to require HTTPS for communication between CloudFront and Amazon S3, you must change the value of Viewer Protocol Policy to Redirect HTTP to HTTPS or HTTPS Only.',
      'cf-s3-https|When you use HTTPS with an Amazon S3 bucket that supports HTTPS communication, Amazon S3 provides the SSL/TLS certificate, so you don\'t have to.',
    ],
  }),
  mc({
    id: 'certificate-office-005',
    building: 'certificate-office',
    bullets: ['1.3-S3'],
    d: 2,
    tags: ['placement-eligible'],
    stem: 'A company serves its site through Amazon CloudFront under its own domain name over HTTPS. Many external links and bookmarks still use http://. All viewer traffic to CloudFront must use HTTPS, while viewers who follow HTTP links must still reach the content. Which viewer protocol policy BEST meets these requirements?',
    correct: ['Redirect HTTP to HTTPS', 'HTTP GET and HEAD requests are redirected to HTTPS, so HTTP links keep working and the viewer then uses HTTPS.'],
    wrong: [
      ['HTTPS Only', 'CloudFront returns HTTP status code 403 to a viewer who sends an HTTP request, so HTTP links would stop working.'],
      ['Allow both HTTP and HTTPS', 'Viewers could keep using HTTP, so HTTPS would not be enforced for all viewer traffic.'],
      ['HTTPS Only for the origin protocol policy', 'The origin protocol policy governs CloudFront to the origin and does not control the protocol viewers use.'],
    ],
    slot: 3,
    evidence: [
      'cf-viewer-https|Redirect HTTP to HTTPS Viewers can use both protocols. HTTP GET and HEAD requests are automatically redirected to HTTPS requests.',
      "cf-viewer-https|HTTPS only Viewers can access your content only if they're using HTTPS. If a viewer sends an HTTP request instead of an HTTPS request, CloudFront returns HTTP status code 403 (Forbidden) and does not return the object.",
      'cf-viewer-https|You also can configure one or more cache behaviors to allow both HTTP and HTTPS, so that CloudFront requires HTTPS for some objects but not for others.',
    ],
  }),
  mc({
    id: 'certificate-office-006',
    building: 'certificate-office',
    bullets: ['1.3-S3'],
    d: 2,
    tags: ['placement-eligible'],
    stem: 'A company serves its site through Amazon CloudFront under its own domain with an ACM certificate. A group of customers with very old browsers cannot connect, because their clients do not support Server Name Indication (SNI). The company accepts additional monthly cost to serve them. Which solution BEST meets these requirements?',
    correct: ['Switch the distribution to Legacy Clients Support for custom SSL client support', 'Legacy Clients Support lets older browsers that do not support SNI connect, with additional monthly charges.'],
    wrong: [
      ['Keep SNI-only support and request a wildcard certificate for the domain', 'Clients without SNI support still cannot connect, whatever names the certificate covers.'],
      ['Set the viewer protocol policy of the distribution to allow both HTTP and HTTPS', 'This weakens the HTTPS requirement and does not let clients without SNI use HTTPS.'],
      ['Move the ACM certificate from the distribution to the origin load balancer', 'Viewers connect to CloudFront, so the viewer-facing certificate must remain on the distribution.'],
    ],
    slot: 0,
    evidence: [
      "cloudfront-settings|Legacy Clients Support – With this setting, older web browsers and clients that don't support SNI can connect to the distribution. However, this setting incurs additional monthly charges.",
      "cloudfront-settings|However, some viewers might use older web browsers or clients that don't support SNI, which means they can't connect to the distribution.",
    ],
  }),
  mc({
    id: 'certificate-office-007',
    building: 'certificate-office',
    bullets: ['1.3-S3'],
    d: 2,
    tags: ['trap:alb-nlb-gwlb'],
    stem: 'A compliance rule says that traffic from clients to a company\'s Amazon EC2 instances must stay encrypted all the way to the instances, and that the load balancer must not decrypt it. Clients connect on TCP port 443. Which solution BEST meets these requirements?',
    correct: ['A Network Load Balancer with a TCP listener on port 443', 'A TCP listener passes encrypted traffic through to the targets without decrypting it.'],
    wrong: [
      ['An Application Load Balancer with an HTTPS listener and an ACM certificate', 'The load balancer terminates the front-end connection and decrypts client requests before sending them to the targets.'],
      ['An Application Load Balancer with a TCP listener on port 443', 'Listeners on an Application Load Balancer support only the HTTP and HTTPS protocols, not TCP.'],
      ['An Application Load Balancer with an HTTPS listener and an HTTPS target group', 'The load balancer still decrypts the client connection and then re-encrypts it, which the rule forbids.'],
    ],
    slot: 1,
    evidence: [
      'alb-https-listener|If you need to pass encrypted traffic to targets without the load balancer decrypting it, you can create a Network Load Balancer or Classic Load Balancer with a TCP listener on port 443.',
      'alb-https-listener|The load balancer uses a server certificate to terminate the front-end connection and then decrypt requests from clients before sending them to the targets.',
      'alb-listeners|Listeners support the following protocols and ports: Protocols: HTTP, HTTPS',
    ],
  }),
  mc({
    id: 'certificate-office-008',
    building: 'certificate-office',
    bullets: ['1.3-S3'],
    d: 2,
    tags: ['placement-eligible'],
    stem: 'A company serves example.com, www.example.com and images.example.com from one Amazon CloudFront distribution over HTTPS with ACM certificates. Which certificate request meets these requirements with the LEAST operational overhead?',
    correct: ['One public certificate in us-east-1 for example.com and *.example.com', 'The wildcard covers the subdomains, the apex name is added as a second name, and one certificate in us-east-1 serves CloudFront.'],
    wrong: [
      ['One public certificate in us-east-1 for *.example.com only', 'A wildcard name protects the subdomains but not the bare or apex domain example.com.'],
      ['One public certificate in us-east-1 for example.com only', 'The apex name alone does not cover www.example.com or images.example.com.'],
      ['Two certificates, example.com in us-east-1 and *.example.com in eu-west-1', 'This needs two certificates, and the one in eu-west-1 cannot be used by CloudFront.'],
    ],
    slot: 2,
    evidence: [
      'acm-public-request|Also note that *.example.com protects only the subdomains of example.com, it does not protect the bare or apex domain (example.com).',
      'acm-public-request|This is useful for protecting both a bare or apex domain (such as example.com) and its subdomains such as *.example.com).',
      'cf-https-requirements|The certificate must cover the alternate domain name in the subject alternate name (SAN) field of the certificate.',
    ],
  }),
  mc({
    id: 'certificate-office-009',
    building: 'certificate-office',
    bullets: ['1.3-S7'],
    d: 1,
    stem: 'A company runs a public website behind an Application Load Balancer. The certificate must renew automatically so that an expired certificate never causes an outage, and the company controls its public DNS records. Which solution meets these requirements with the LEAST operational effort?',
    correct: ['Request a public ACM certificate with DNS validation and deploy it on the load balancer', 'ACM renews an Amazon-issued certificate automatically when DNS validation is used and it is associated with a service such as Elastic Load Balancing.'],
    wrong: [
      ['Import a certificate from a third-party certificate authority into ACM', 'ACM does not provide managed renewal for imported certificates, so the company would have to reimport it before it expires.'],
      ['Request a public ACM certificate with email validation and answer the validation emails', 'Email validation needs someone to act on validation emails to renew, which is more manual work than DNS validation.'],
      ['Upload a certificate to the load balancer and set a calendar reminder to replace it', 'The company would renew and replace the certificate by hand each time.'],
    ],
    slot: 3,
    evidence: [
      'acm-renewal|ACM will either renew your certificates automatically (if you are using DNS validation), or it will send you email notices when expiration is approaching.',
      'acm-renewal|ELIGIBLE if associated with another AWS service, such as Elastic Load Balancing or CloudFront.',
      'acm-import|The certificates that you import work the same as those provided by ACM, with one important exception: ACM does not provide managed renewal for imported certificates.',
      'acm-email-validation|ACM also sends validation emails to these same addresses to renew the certificate when the certificate is 45 days from expiry.',
    ],
  }),
  mc({
    id: 'certificate-office-010',
    building: 'certificate-office',
    bullets: ['1.3-S7'],
    d: 2,
    tags: ['placement-eligible'],
    stem: 'A company imported a certificate from a third-party certificate authority into ACM for its Amazon CloudFront distribution and has missed two renewals. The company wants to stop managing certificate expiry. Which solution meets this requirement with the LEAST operational overhead?',
    correct: ['Request a public ACM certificate with DNS validation in us-east-1 and associate it with the distribution', 'An Amazon-issued certificate in use on CloudFront renews automatically with DNS validation, and CloudFront needs it in us-east-1.'],
    wrong: [
      ['Turn on managed renewal for the imported certificate in the ACM console', 'Imported certificates are not eligible for ACM managed renewal.'],
      ['Create an Amazon EventBridge rule that sends an expiry notice and reimport the certificate by hand', 'The company would still renew and reimport the certificate manually, so the burden remains.'],
      ['Request a public ACM certificate with DNS validation in eu-west-1 and associate it with the distribution', 'CloudFront can use an ACM certificate only if it is requested or imported in us-east-1.'],
    ],
    slot: 0,
    evidence: [
      'acm-renewal|NOT ELIGIBLE if imported.',
      'acm-import|You are responsible for monitoring the expiration date of your imported certificates and for renewing them before they expire.',
      'cf-https-requirements|To use an ACM certificate with a CloudFront distribution, make sure you request (or import) the certificate in the US East (N. Virginia) Region (us-east-1).',
    ],
  }),
  mc({
    id: 'certificate-office-011',
    building: 'certificate-office',
    bullets: ['1.3-S7'],
    d: 3,
    tags: ['placement-eligible'],
    stem: 'A company\'s Amazon CloudFront distribution uses an ACM public certificate that was validated with DNS. After a DNS cleanup, the renewal status of the certificate shows Pending validation. Which action BEST resolves this and keeps renewal automatic?',
    correct: ['Re-create the CNAME validation record that ACM provided in the public DNS zone', 'ACM renews automatically while the certificate is in use and its CNAME record remains in place.'],
    wrong: [
      ['Delete the certificate from the distribution and associate it again to restart the renewal', 'Removing the certificate from the service stops automatic renewal rather than restarting it.'],
      ['Import the same certificate into eu-west-1 so that ACM can renew it there', 'Imported certificates are not eligible for managed renewal, and CloudFront needs its certificate in us-east-1.'],
      ['Switch the validation of the certificate from DNS to email without creating a new certificate', 'The validation method of an existing certificate cannot be switched between DNS and email.'],
    ],
    slot: 1,
    evidence: [
      'acm-renewal-status|If you used DNS validation, check to make sure your DNS record exists and that your certificate remains in use.',
      'acm-dns-validation|ACM automatically renews your certificate as long as the certificate is in use and your CNAME record remains in place.',
      'acm-dns-validation|You can stop automatic renewal either by removing the certificate from the AWS service with which it is associated or by deleting the CNAME record.',
      'acm-email-validation|After you create a certificate with email validation, you cannot switch to validating it with DNS.',
    ],
  }),
  mc({
    id: 'certificate-office-012',
    building: 'certificate-office',
    bullets: ['1.3-S7'],
    d: 1,
    stem: 'A company must rotate the key material of a customer managed symmetric KMS key that encrypts its Amazon S3 data once a year. Applications must not need code changes. Which solution BEST meets these requirements?',
    correct: ['Enable automatic key rotation on the existing KMS key', 'AWS KMS generates new key material for the key every year, and applications keep working without code changes.'],
    wrong: [
      ['Create a new KMS key each year and update every application to use it', 'The applications would need changes each year to use the new key.'],
      ['Enable key rotation on the AWS managed key for Amazon S3 in the account', 'Rotation cannot be enabled or disabled for AWS managed keys, and the company does not own that key.'],
      ['Delete the key and import new key material into a new key every year', 'This destroys the key and forces applications onto a different key.'],
    ],
    slot: 2,
    evidence: [
      'kms-rotation|By default, when you enable automatic key rotation for a KMS key, AWS KMS generates new cryptographic material for the KMS key every year.',
      'kms-rotation|Because AWS KMS transparently decrypts with the appropriate key material, you can safely use a rotated KMS key in applications and AWS services without code changes.',
      'kms-rotation|AWS KMS automatically rotates AWS managed keys every year (approximately 365 days). You cannot enable or disable key rotation for AWS managed keys.',
    ],
  }),
  mc({
    id: 'certificate-office-013',
    building: 'certificate-office',
    bullets: ['1.3-S7'],
    d: 3,
    stem: 'A company signs documents with an asymmetric RSA KMS key. Policy requires that the key material be rotated every year. Which solution BEST meets this requirement?',
    correct: ['Create a new asymmetric KMS key and point the alias that the application uses to it', 'Asymmetric keys cannot use automatic or on-demand rotation, so they are rotated manually by switching to a new key.'],
    wrong: [
      ['Enable automatic key rotation on the asymmetric KMS key', 'Automatic rotation is supported only on symmetric encryption KMS keys with key material that AWS KMS generates.'],
      ['Run an on-demand rotation of the asymmetric KMS key every year', 'Neither automatic nor on-demand rotation is supported for asymmetric KMS keys.'],
      ['Move the asymmetric KMS key into a custom key store and enable automatic rotation there', 'Keys in custom key stores cannot be rotated automatically or on demand either.'],
    ],
    slot: 3,
    evidence: [
      'kms-rotation|Automatic key rotation is supported only on symmetric encryption KMS keys with key material that AWS KMS generates (AWS_KMS origin).',
      'kms-rotation|Neither automatic nor on-demand key rotation is supported for the following types of KMS keys, but you can rotate these KMS keys manually.',
      'kms-rotation|Manual rotation is a good choice when you want to rotate KMS keys that are not eligible for automatic or on-demand key rotation, including asymmetric KMS keys, HMAC KMS keys and KMS keys in custom key stores.',
    ],
  }),
  mr({
    id: 'certificate-office-014',
    building: 'certificate-office',
    bullets: ['1.3-S7'],
    d: 2,
    stem: 'A company turns on automatic rotation for a customer managed symmetric KMS key that encrypts Amazon EBS volumes and Amazon S3 objects. Which TWO statements are true after the key material rotates? (Choose two.)',
    correct: [
      ['AWS KMS decrypts existing ciphertext with the key material that encrypted it', 'AWS KMS automatically chooses the version of the key material that was used to encrypt the data.'],
      ['The services that use the key keep working without code changes', 'AWS KMS decrypts transparently, so a rotated key can be used in applications and services without code changes.'],
    ],
    wrong: [
      ['All existing data keys are re-encrypted immediately under the new key material', 'Key rotation does not rotate the data keys or re-encrypt any data protected by the key.'],
      ['The KMS key receives a new key ID and ARN', 'The KMS key is the same logical resource, and its properties do not change.'],
      ['A compromised data key is no longer a risk', 'Key rotation will not mitigate the effect of a compromised data key.'],
    ],
    slots: [2, 4],
    evidence: [
      'kms-rotation|When you use the rotated KMS key to decrypt ciphertext, AWS KMS uses the key material that was used to encrypt it.',
      'kms-rotation|Because AWS KMS transparently decrypts with the appropriate key material, you can safely use a rotated KMS key in applications and AWS services without code changes.',
      'kms-rotation|Key rotation has no effect on the data that the KMS key protects. It does not rotate the data keys that the KMS key generated or re-encrypt any data protected by the KMS key.',
      'kms-rotation|The properties of the KMS key do not change',
    ],
  }),
  mr({
    id: 'certificate-office-015',
    building: 'certificate-office',
    bullets: ['1.3-S7'],
    d: 2,
    stem: 'A company\'s DNS-validated ACM certificate on an Application Load Balancer stopped renewing automatically after two changes made by different teams. Which TWO changes can stop automatic renewal? (Choose two.)',
    correct: [
      ['The certificate was removed from the load balancer', 'Removing the certificate from the service it is associated with stops automatic renewal.'],
      ['The CNAME validation record was deleted from DNS', 'Deleting the CNAME record stops automatic renewal.'],
    ],
    wrong: [
      ['A new listener rule was added to the load balancer', 'A listener rule changes request routing and has no effect on certificate renewal.'],
      ['AWS CloudTrail logging was turned on for ACM', 'CloudTrail only records API calls and does not affect renewal.'],
      ['The same certificate was also associated with a second load balancer in the Region', 'A certificate in use on a service remains eligible for renewal, and adding another association does not stop it.'],
    ],
    slots: [1, 4],
    evidence: [
      'acm-dns-validation|You can stop automatic renewal either by removing the certificate from the AWS service with which it is associated or by deleting the CNAME record.',
      'acm-renewal|ELIGIBLE if associated with another AWS service, such as Elastic Load Balancing or CloudFront.',
    ],
  }),
  mc({
    id: 'certificate-office-016',
    building: 'certificate-office',
    bullets: ['1.3-S3'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A company has a REST API in Amazon API Gateway in eu-central-1 and wants the ACM certificate for its custom domain name requested in eu-central-1, the same Region as the API. Which API Gateway custom domain type meets this requirement?',
    correct: ['A Regional custom domain name', 'A Regional custom domain name uses an ACM certificate requested or imported in the same Region as the API.'],
    wrong: [
      ['An edge-optimized custom domain name', 'An edge-optimized custom domain name needs its ACM certificate in us-east-1.'],
      ['An edge-optimized custom domain name with its certificate copied from us-east-1', 'A certificate cannot be copied between Regions, so it could not be placed in eu-central-1.'],
      ['A Regional custom domain name with the certificate requested in us-east-1', 'For a Regional custom domain name the certificate must be in the same Region as the API.'],
    ],
    slot: 0,
    evidence: [
      'apigw-edge-cert|To use an ACM certificate with a Regional custom domain name, you must request or import the certificate in the same Region as your API.',
      'apigw-edge-cert|To use an ACM certificate with an edge-optimized custom domain name, you must request or import the certificate in the US East (N. Virginia) – us-east-1 Region.',
      'acm-overview|You cannot copy a certificate between regions.',
    ],
  }),
  mc({
    id: 'certificate-office-017',
    building: 'certificate-office',
    bullets: ['1.3-S3'],
    d: 3,
    tags: ['mock-reserve'],
    stem: 'A company runs the same website behind Application Load Balancers in us-west-2 and eu-west-1, both under www.example.com, and controls its public DNS records. Both load balancers must serve HTTPS with ACM certificates that renew automatically. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Request a certificate for www.example.com in each Region with DNS validation', 'A certificate is needed in each Region, and the same CNAME record validates the domain for any Region.'],
    wrong: [
      ['Request one certificate in us-west-2 and copy it to eu-west-1', 'A certificate cannot be copied between Regions.'],
      ['Request one certificate in us-east-1 and attach it to both load balancers', 'ACM certificates are regional, so each load balancer needs a certificate in its own Region.'],
      ['Import the same third-party certificate into both Regions and rely on managed renewal', 'Imported certificates are not eligible for ACM managed renewal.'],
    ],
    slot: 1,
    evidence: [
      'acm-overview|To use a certificate with Elastic Load Balancing for the same fully qualified domain name (FQDN) or set of FQDNs in more than one AWS region, you must request or import a certificate for each region.',
      'acm-dns-validation|Since the CNAME validation token works for any AWS Region, you can re-create the same certificate in multiple Regions.',
      'acm-renewal|NOT ELIGIBLE if imported.',
    ],
  }),
  mc({
    id: 'certificate-office-018',
    building: 'certificate-office',
    bullets: ['1.3-S7'],
    d: 3,
    tags: ['mock-reserve'],
    stem: 'A company\'s mobile app pins the public ACM certificate that secures its Application Load Balancer. After ACM renewed the certificate, the app can no longer connect. Which change keeps the app working across future renewals with the LEAST ongoing effort?',
    correct: ['Pin the app to all Amazon root certificates instead of the leaf certificate', 'Renewal generates a new key pair, but the Amazon roots stay the same, so renewals do not break the pin.'],
    wrong: [
      ['Pin the app to the ARN of the certificate, which stays the same after renewal', 'An ARN is not part of the TLS handshake, and the app would still fail to validate the renewed certificate.'],
      ['Ask ACM to reuse the same public key when it renews the certificate', 'ACM generates a new public-private key pair to renew a certificate.'],
      ['Turn off managed renewal and re-request the certificate every few months', 'This adds manual work and a new certificate would still carry a new key pair.'],
    ],
    slot: 2,
    evidence: [
      'acm-best-practices|To renew a certificate, ACM generates a new public-private key pair. If your application pins the ACM certificate and the certificate is successfully renewed with a new public key, the application might be unable to connect to your domain.',
      'acm-best-practices|If you\'re using a public certificate, pin your application to all available Amazon root certificates.',
    ],
  }),
];

export default questions;
