import type { Question } from '../../../src/content/types.ts';
import { mc, mr } from '../helpers.ts';

const questions: Question[] = [
  mc({
    id: 'charter-hall-001',
    building: 'charter-hall',
    bullets: ['1.1-K3'],
    d: 1,
    stem: 'A company runs a web application on Amazon EC2 instances in a single Availability Zone. The company wants the application to keep running if the data center that hosts those instances loses power. Which design change is the SIMPLEST way to meet this requirement?',
    correct: ['Run additional instances in a second Availability Zone of the same Region', 'Availability Zones have separate and redundant power infrastructure, so instances in a second zone keep running when the first zone loses power.'],
    wrong: [
      ['Add a second subnet in the same Availability Zone and spread the instances across both subnets', 'Both subnets would still sit in the Availability Zone that loses power, so the application would stop.'],
      ['Replace the instances with a larger instance type in the same Availability Zone', 'A larger instance does not remove the dependency on the power infrastructure of one Availability Zone.'],
      ['Add more instances in the same Availability Zone and place them in a second security group', 'More instances in the same zone share its power infrastructure, and security groups do not affect power.'],
    ],
    slot: 0,
    evidence: [
      'fault-isolation-az|An Availability Zone is one or more discrete data centers with separate and redundant power infrastructure, networking, and connectivity in an AWS Region.',
      'global-infra|AWS customers focused on high availability can design their applications to run in multiple AZs to achieve even greater fault-tolerance.',
    ],
  }),
  mc({
    id: 'charter-hall-002',
    building: 'charter-hall',
    bullets: ['1.1-K3'],
    d: 1,
    stem: 'A new team member asks what an Availability Zone is. Which description is MOST accurate?',
    correct: ['One or more discrete data centers with redundant power, networking, and connectivity in an AWS Region', 'This is how AWS defines an Availability Zone: one or more discrete data centers inside a Region.'],
    wrong: [
      ['A single physical server rack inside one data center that hosts the instances of one account and cannot be shared', 'A zone is made of one or more data centers, not a single rack, and it is not tied to one account.'],
      ['A global network location that caches content close to end users and shortens response times', 'That describes a content delivery edge location, not a group of data centers inside a Region.'],
      ['A geographic area that contains exactly one data center and its own regional service endpoint', 'A Region is the geographic area, and it contains several Availability Zones rather than one data center.'],
    ],
    slot: 1,
    evidence: [
      'global-infra|An Availability Zone (AZ) is one or more discrete data centers with redundant power, networking, and connectivity in an AWS Region.',
      'global-infra|Each AWS Region consists of a minimum of three, isolated, and physically separate AZs within a geographic area.',
    ],
  }),
  mc({
    id: 'charter-hall-003',
    building: 'charter-hall',
    bullets: ['1.1-K3'],
    d: 2,
    stem: 'A company is launching an application for customers in Germany. Company policy requires that customer data stay in Europe, and the application needs a specific AWS service. Which approach to choosing a Region is BEST?',
    correct: ['Choose a Region in Europe that offers the required service', 'A Region choice should weigh the services and features needed, closeness to users, and legal requirements such as keeping resources in Europe.'],
    wrong: [
      ['Choose the Region that has the largest number of Availability Zones, wherever it is located', 'The number of Availability Zones does not address the requirement to keep customer data in Europe.'],
      ['Choose the Region closest to the company headquarters, wherever the customers are located', 'The headquarters location does not decide customer latency or the requirement to keep data in Europe.'],
      ['Deploy into whichever Region is the default Region of the AWS CLI profile of the team', 'The default Region is a convenience setting and does not ensure that the data stays in Europe.'],
    ],
    slot: 2,
    evidence: [
      'regions-and-azs|select a Region that has the AWS services and features that you need.',
      'regions-and-azs|For example, you want to create resources in Europe to be closer to your European customers or to meet legal requirements.',
    ],
  }),
  mc({
    id: 'charter-hall-004',
    building: 'charter-hall',
    bullets: ['1.1-K3'],
    d: 2,
    stem: 'A company wants to deploy a workload in an AWS Region that was introduced after March 2019. API calls to the Region fail even though the Region exists. Which action resolves the problem with the LEAST effort?',
    correct: ['Enable the Region for the AWS account', 'A Region introduced after March 20, 2019 must be enabled before it can be accessed.'],
    wrong: [
      ['Create a new AWS account that is dedicated to the Region and move the workload into it', 'A new account is not needed; the existing account can enable the Region, which is far less effort.'],
      ['Request a service quota increase for the Region from AWS Support before making any more API calls', 'Quotas limit how much of a service can be used and do not enable a Region.'],
      ['Create an IAM role with administrator access and use it for every API call to the Region', 'Permissions do not enable a Region; the Region must be enabled before it can be accessed.'],
    ],
    slot: 3,
    evidence: [
      'regions-and-azs|To use a Region introduced after March 20, 2019, you must enable the Region before you can access it.',
    ],
  }),
  mr({
    id: 'charter-hall-005',
    building: 'charter-hall',
    bullets: ['1.1-K3'],
    d: 2,
    stem: 'An architect designs a database tier that replicates synchronously between Availability Zones of one Region. Which TWO characteristics of Availability Zones support this design? (Choose two.)',
    correct: [
      ['The zones are close enough to each other for synchronous replication with single-digit millisecond latency', 'AWS states that zones are close enough to use synchronous replication with single-digit millisecond latency.'],
      ['The zones are meaningfully distant from each other to prevent correlated failures', 'The distance between zones lowers the chance that a single event affects more than one zone.'],
    ],
    wrong: [
      ['Generators and cooling equipment are shared across the zones to keep power consistent', 'Common points of failure such as generators and cooling equipment are not shared across zones.'],
      ['All zones of a Region sit in one data center building that is divided into separate floors', 'A zone is made of one or more discrete data centers, and zones are meaningfully distant from each other.'],
      ['Traffic between the zones crosses the public internet because no dedicated links connect them', 'Zones are interconnected with high-bandwidth, low-latency networking over fully redundant, dedicated metro fiber.'],
    ],
    slots: [0, 3],
    evidence: [
      'fault-isolation-az|Availability Zones in a Region are meaningfully distant from each other, up to 60 miles (~100 km) to prevent correlated failures, but close enough to use synchronous replication with single-digit millisecond latency.',
      'fault-isolation-az|Common points of failure, like generators and cooling equipment, are not shared across Availability Zones',
      'fault-isolation-az|All Availability Zones in a Region are interconnected with high-bandwidth, low-latency networking, over fully redundant, dedicated metro fiber.',
    ],
  }),
  mc({
    id: 'charter-hall-006',
    building: 'charter-hall',
    bullets: ['1.1-K3'],
    d: 3,
    stem: 'A company must pick a Region for a new workload. Region X is in the country where the law requires the data to stay and offers every service the workload needs, but it is farther from most users. Region Y is closer to most users and offers every required service, but it is in another country. Region Z is in the required country but lacks one required service. Which choice BEST meets the requirements?',
    correct: ['Region X, because it meets the legal and service requirements even though latency is higher', 'Services, legal requirements and latency all matter when choosing a Region, and only Region X meets the legal and service requirements.'],
    wrong: [
      ['Region Y, because lower latency to most users outweighs the requirement to keep the data in the country', 'Latency is a reason to choose a Region, but it cannot replace a legal requirement about where the data must stay.'],
      ['Region Z, because being in the required country is enough and the missing service can be ignored', 'The workload needs that service, so a Region that does not offer it fails the service requirement.'],
      ['Region Y, because encrypting the data makes the country of the Region irrelevant to the law', 'Encryption does not change a legal requirement that the data stay in a given country.'],
    ],
    slot: 0,
    evidence: [
      'regions-and-azs|select a Region that has the AWS services and features that you need.',
      'regions-and-azs|you can lower network latency when you select a Region that is close to the majority of your users.',
      'regions-and-azs|This information can help you meet your regulatory, compliance, and operational requirements.',
    ],
  }),
  mc({
    id: 'charter-hall-007',
    building: 'charter-hall',
    bullets: ['1.1-K3'],
    d: 2,
    stem: 'A company with a standard AWS account wants to deploy a workload into the GovCloud (US) Regions by using the console session and IAM roles of that account. Which statement BEST describes what happens?',
    correct: ['The account cannot access those Regions; a GovCloud (US) account is needed', 'A GovCloud (US) account provides access to those Regions, which cannot be accessed from a standard AWS account.'],
    wrong: [
      ['The account can use the Regions after an administrator enables them, as with any opt-in Region', 'Enabling applies to the Regions of the account type; GovCloud Regions cannot be accessed from a standard AWS account.'],
      ['The account can use the Regions after an SCP in the organization allows access to the GovCloud Regions', 'An SCP does not grant permissions and cannot make Regions of another account type reachable.'],
      ['The account can use the Regions through the credentials of an AWS (China) account for all other partitions', 'An AWS (China) account provides access to the Beijing and Ningxia Regions only.'],
    ],
    slot: 1,
    evidence: [
      "regions-and-azs|You can't describe or access the Regions of one type of account from another.",
      "regions-and-azs|For example, you can't access the AWS GovCloud (US) Regions or the China Regions from an AWS account.",
      'regions-and-azs|An Amazon AWS (China) account provides access to the Beijing and Ningxia Regions only.',
    ],
  }),
  mc({
    id: 'charter-hall-008',
    building: 'charter-hall',
    bullets: ['1.1-K5'],
    d: 1,
    stem: 'A security engineer asks who is responsible for the host operating system and the virtualization layer of the physical servers that run the Amazon EC2 instances of the company. Under the AWS shared responsibility model, which answer is MOST accurate?',
    correct: ['The company has no duty for those layers, because AWS operates, manages, and controls them', 'AWS operates, manages and controls the components from the host operating system and virtualization layer down to the physical security of the facilities.'],
    wrong: [
      ['The company, because the company chooses the instance type and therefore manages the host that runs it', 'Choosing an instance type does not move the host layer to the customer; AWS operates the host operating system and virtualization layer.'],
      ['The company, because customers manage every layer above the physical security of the data centers', 'The customer manages the guest operating system and above; AWS manages the host operating system and virtualization layer.'],
      ['Both equally, and the company approves each patch that AWS applies to the host operating system', 'The host layer is operated and controlled by AWS, so the company does not approve host patches.'],
    ],
    slot: 2,
    evidence: [
      'shared-responsibility|This shared model can help relieve the customer’s operational burden as AWS operates, manages and controls the components from the host operating system and virtualization layer down to the physical security of the facilities in which the service operates.',
    ],
  }),
  mc({
    id: 'charter-hall-009',
    building: 'charter-hall',
    bullets: ['1.1-K5'],
    d: 1,
    stem: 'An auditor asks who is responsible for the physical security of the data center facilities that host the workloads of a company on AWS. Which answer is BEST?',
    correct: ['AWS, which operates and controls the components down to the physical security of the facilities', 'AWS operates, manages and controls the components from the host operating system and virtualization layer down to the physical security of the facilities.'],
    wrong: [
      ['The company, because customers must secure the facilities that run their own workloads in the cloud', 'Customers do not operate the facilities; AWS controls the components down to their physical security.'],
      ['The company, but only for the racks that host its production instances in the data centers of the Region', 'Customers do not manage racks; AWS operates the facilities in which the services run.'],
      ['The company, through the security groups that it attaches to the instances of its workloads', 'Security groups are the customer configuration of a virtual firewall and do not provide physical security.'],
    ],
    slot: 3,
    evidence: [
      'shared-responsibility|This shared model can help relieve the customer’s operational burden as AWS operates, manages and controls the components from the host operating system and virtualization layer down to the physical security of the facilities in which the service operates.',
    ],
  }),
  mc({
    id: 'charter-hall-010',
    building: 'charter-hall',
    bullets: ['1.1-K5'],
    d: 2,
    stem: 'A company stores customer records in Amazon S3 and Amazon DynamoDB. Which task remains the responsibility of the company under the AWS shared responsibility model? Choose the MOST accurate answer.',
    correct: ['Managing the data, including its encryption options, and using IAM to apply the appropriate permissions', 'For abstracted services such as Amazon S3 and Amazon DynamoDB, customers manage their data, classify assets, and use IAM tools to apply permissions.'],
    wrong: [
      ['Patching the operating system of the servers that run the storage service that holds the records of the company', 'For abstracted services AWS operates the infrastructure layer, the operating system, and the platforms.'],
      ['Maintaining the hypervisor that runs the nodes that store the records of the company', 'AWS operates the components from the host operating system and virtualization layer down to the facilities.'],
      ['Replacing failed disks in the data centers that hold the stored objects of the company', 'The physical infrastructure is operated by AWS, so the company does not replace disks.'],
    ],
    slot: 0,
    evidence: [
      'shared-responsibility|For abstracted services, such as Amazon S3 and Amazon DynamoDB, AWS operates the infrastructure layer, the operating system, and platforms, and customers access the endpoints to store and retrieve data.',
      'shared-responsibility|Customers are responsible for managing their data (including encryption options), classifying their assets, and using IAM tools to apply the appropriate permissions.',
    ],
  }),
  mc({
    id: 'charter-hall-011',
    building: 'charter-hall',
    bullets: ['1.1-K5'],
    d: 2,
    stem: 'A security review finds that the security group of an Amazon EC2 instance allows SSH from any IP address. Under the shared responsibility model, who must fix this configuration? Choose the BEST answer.',
    correct: ['The company, because customers configure the AWS-provided security group firewall of their instances', 'The customer is responsible for the configuration of the AWS-provided firewall, called a security group, on each instance.'],
    wrong: [
      ['AWS, because security groups are part of the AWS-managed network infrastructure of the Region and its Availability Zones', 'AWS provides the firewall feature, but the customer is responsible for configuring the security group on each instance.'],
      ['AWS, because it must protect the infrastructure that runs Amazon EC2 from customer misconfiguration', 'Protecting the infrastructure is AWS responsibility; the rules of a security group are part of the customer configuration.'],
      ['AWS, because the remediation of every finding of a security review belongs to Security of the Cloud', 'Security in the Cloud is the customer responsibility and includes the configuration of the security groups of its instances.'],
    ],
    slot: 1,
    evidence: [
      'shared-responsibility|Customers that deploy an Amazon EC2 instance are responsible for management of the guest operating system (including updates and security patches), any application software or utilities installed by the customer on the instances, and the configuration of the AWS-provided firewall (called a security group) on each instance.',
    ],
  }),
  mr({
    id: 'charter-hall-012',
    building: 'charter-hall',
    bullets: ['1.1-K5'],
    d: 2,
    stem: 'A company runs a self-managed application on Amazon EC2 instances. Which TWO tasks are the responsibility of the company under the AWS shared responsibility model? (Choose two.)',
    correct: [
      ['Applying security patches to the guest operating system of the instances', 'Customers assume responsibility for the guest operating system, including updates and security patches.'],
      ['Managing the application software that the company installs on the instances', 'Customers are responsible for any application software or utilities that they install on their instances.'],
    ],
    wrong: [
      ['Operating the virtualization layer that runs the instances on the hosts', 'AWS operates and controls the components from the host operating system and virtualization layer.'],
      ['Controlling physical access to the data centers that house the hosts', 'AWS operates the physical security of the facilities in which the services run.'],
      ['Maintaining the networking and server hardware that the instances run on', 'The hardware, software, networking, and facilities that run AWS Cloud services are protected by AWS.'],
    ],
    slots: [1, 4],
    evidence: [
      'shared-responsibility|Customers that deploy an Amazon EC2 instance are responsible for management of the guest operating system (including updates and security patches), any application software or utilities installed by the customer on the instances, and the configuration of the AWS-provided firewall (called a security group) on each instance.',
      'shared-responsibility|This infrastructure is composed of the hardware, software, networking, and facilities that run AWS Cloud services.',
    ],
  }),
  mc({
    id: 'charter-hall-013',
    building: 'charter-hall',
    bullets: ['1.1-K5'],
    d: 3,
    stem: 'A company hosts a static website on Amazon EC2 instances and manages the operating system and the web server software on them. To reduce its security responsibilities, the company moves the content to Amazon S3. Which responsibility does the move remove from the company?',
    correct: ['Patching the operating system and platform software of the servers that serve the content', 'For an abstracted service such as Amazon S3, AWS operates the infrastructure layer, the operating system, and the platforms.'],
    wrong: [
      ['Managing who can access the content by applying permissions with IAM tools and bucket policies', 'Customers still use IAM tools to apply the appropriate permissions for abstracted services.'],
      ['Choosing the encryption options for the stored content that the website serves to visitors', 'Customers remain responsible for managing their data, including its encryption options.'],
      ['Classifying the content of the website to decide how sensitive each part of it is', 'Customers remain responsible for classifying their assets, whichever service stores them.'],
    ],
    slot: 2,
    evidence: [
      'shared-responsibility|For abstracted services, such as Amazon S3 and Amazon DynamoDB, AWS operates the infrastructure layer, the operating system, and platforms, and customers access the endpoints to store and retrieve data.',
      'shared-responsibility|Customers are responsible for managing their data (including encryption options), classifying their assets, and using IAM tools to apply the appropriate permissions.',
    ],
  }),
  mc({
    id: 'charter-hall-014',
    building: 'charter-hall',
    bullets: ['1.1-K5'],
    d: 2,
    stem: 'A company uses Amazon EC2 and asks how patch management is divided between AWS and the customer. Which statement BEST describes the division?',
    correct: ['AWS patches and fixes flaws in the infrastructure, and the customer patches its guest operating systems and applications', 'Patch management is a shared control: AWS patches the infrastructure and customers patch their guest OS and applications.'],
    wrong: [
      ['AWS patches the guest operating system of the instances, and the customer patches only its own application code', 'Customers are responsible for patching their guest operating systems as well as their applications.'],
      ['The customer patches the infrastructure under the instances, and AWS patches the applications that the customer installs', 'AWS patches and fixes flaws within the infrastructure, and the customer patches its applications.'],
      ['AWS handles every kind of patching for the instances, so the customer has no patching duties at all', 'The customer is responsible for patching the guest operating system and applications on its instances.'],
    ],
    slot: 3,
    evidence: [
      'shared-responsibility|Patch Management – AWS is responsible for patching and fixing flaws within the infrastructure, but customers are responsible for patching their guest OS and applications.',
    ],
  }),
  mr({
    id: 'charter-hall-015',
    building: 'charter-hall',
    bullets: ['1.1-K5'],
    d: 3,
    stem: 'A compliance team maps its controls to the AWS shared responsibility model. Which THREE controls are shared controls, in which AWS and the customer each apply a part in their own context? (Choose three.)',
    correct: [
      ['Patch management', 'AWS patches and fixes flaws within the infrastructure, while customers patch their guest OS and applications.'],
      ['Configuration management', 'AWS maintains the configuration of its infrastructure devices, while the customer configures its own guest operating systems, databases and applications.'],
      ['Awareness and training', 'AWS trains AWS employees, but a customer must train its own employees.'],
    ],
    wrong: [
      ['Physical and environmental controls of the data centers', 'These are inherited controls, which a customer fully inherits from AWS.'],
      ['Routing and zoning of customer data within specific security environments', 'This is a customer-specific control that is solely the responsibility of the customer.'],
    ],
    slots: [1, 3, 4],
    evidence: [
      'shared-responsibility|Patch Management – AWS is responsible for patching and fixing flaws within the infrastructure, but customers are responsible for patching their guest OS and applications.',
      'shared-responsibility|Configuration Management – AWS maintains the configuration of its infrastructure devices, but a customer is responsible for configuring their own guest operating systems, databases, and applications.',
      'shared-responsibility|Awareness & Training - AWS trains AWS employees, but a customer must train their own employees.',
    ],
  }),
  mc({
    id: 'charter-hall-016',
    building: 'charter-hall',
    bullets: ['1.1-K3'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'An architect wants to understand how AWS limits the chance that a faulty service update affects several Availability Zones of a Region at the same time. Which statement is accurate?',
    correct: ['AWS separates in time the deployments of service updates to the Availability Zones in the same Region', 'Deployments to Availability Zones in the same Region are separated in time to prevent correlated failure.'],
    wrong: [
      ['AWS deploys each service update to all Availability Zones of a Region at once so that they stay identical', 'Deployments to zones in the same Region are separated in time, not made all at once.'],
      ['AWS applies each update only to Regions that have a single Availability Zone before any other Region', 'The isolation comes from separating deployments to zones in time, not from a single-zone Region.'],
      ['AWS pauses deployments to every Availability Zone until the customers of the Region approve each update', 'AWS does not wait for customer approval; it separates deployments to zones in time.'],
    ],
    slot: 0,
    evidence: [
      'fault-isolation-az|When AWS deploys updates to its services, deployments to Availability Zones in the same Region are separated in time to prevent correlated failure.',
    ],
  }),
  mc({
    id: 'charter-hall-017',
    building: 'charter-hall',
    bullets: ['1.1-K5'],
    d: 3,
    tags: ['mock-reserve'],
    stem: 'An auditor asks a company to demonstrate controls over the physical and environmental security of the data centers that host its AWS workloads. The company does not operate those facilities. Which approach is BEST?',
    correct: ['Review the third-party audit attestation documents of AWS to determine the controls that the company inherits', 'Physical and environmental controls are inherited, and attestation documents show which inherited controls remain for the customer.'],
    wrong: [
      ['Install badge readers and cameras in the AWS data centers that host the workloads of the company', 'Customers do not operate the facilities, and AWS operates the physical security of the facilities.'],
      ['Configure stricter security group rules to prove that the facilities are physically protected', 'Security group rules are a customer configuration of a virtual firewall and do not evidence physical security.'],
      ['Classify the controls as customer-specific controls because the workloads belong to the company', 'Physical and environmental controls are inherited from AWS; customer-specific controls depend on the application the customer deploys.'],
    ],
    slot: 1,
    evidence: [
      'shared-responsibility|Controls which a customer fully inherits from AWS. Physical and Environmental controls',
      'shared-responsibility|Review third-party audit attestation documents to determine inherited controls and what required controls may be remaining for you to implement in your environment.',
    ],
  }),
  mr({
    id: 'charter-hall-018',
    building: 'charter-hall',
    bullets: ['1.1-K3'],
    d: 3,
    tags: ['mock-reserve'],
    stem: 'A company is building a workload for customers in Germany. Legal requirements say that customer data must stay in Europe, and the workload must keep running if one Availability Zone fails. Which THREE design decisions meet these requirements? (Choose three.)',
    correct: [
      ['Create the resources in a Region in Europe that offers the services the workload needs', 'The Region choice weighs the services needed and legal requirements, so a European Region that offers the services keeps the data in Europe.'],
      ['Spread the instances across at least two Availability Zones of that Region', 'Availability Zones are isolated and physically separate, so a workload partitioned across them survives the loss of one zone.'],
      ['Replicate the data tier synchronously between the Availability Zones of that Region', 'The network between Availability Zones supports synchronous replication, so a zone failure does not lose committed data.'],
    ],
    wrong: [
      ['Place a second copy of the workload in a Region outside Europe to be isolated from events in Europe', 'A copy of the customer data outside Europe breaks the legal requirement that the data stay in Europe.'],
      ['Run all instances in one Availability Zone on the largest instance type that is available', 'A larger instance type does not remove the single Availability Zone as a failure domain, so the workload would stop with that zone.'],
      ['Spread the instances across two subnets that are in the same Availability Zone', 'A subnet resides in one Availability Zone, so both subnets share the same failure domain and the workload would stop with that zone.'],
    ],
    slots: [0, 3, 5],
    evidence: [
      'regions-and-azs|select a Region that has the AWS services and features that you need.',
      'regions-and-azs|For example, you want to create resources in Europe to be closer to your European customers or to meet legal requirements.',
      'global-infra|Each AWS Region consists of a minimum of three, isolated, and physically separate AZs within a geographic area.',
      'global-infra|The network performance is sufficient to accomplish synchronous replication between AZs.',
    ],
  }),
];

export default questions;
