import type { Question } from '../../../src/content/types.ts';
import { mc, mr } from '../helpers.ts';

const questions: Question[] = [
  mc({
    id: 'compliance-registry-001',
    building: 'compliance-registry',
    bullets: ['1.3-K1'],
    d: 2,
    stem: 'A company stores sales data in an Amazon S3 data lake and queries it with Amazon Athena and Amazon Redshift Spectrum. Analysts from each department must see only certain columns and rows. The company wants to define these rules in one central place instead of editing policies for every team. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Use AWS Lake Formation to grant column-level and row-level permissions on the data lake tables', 'Lake Formation is a single place to manage access controls and enforces them at the column, row, and cell levels across the analytics services.'],
    wrong: [
      ['Write a bucket policy for each department that allows only certain S3 prefixes', 'A bucket policy controls access to objects and prefixes, and it cannot limit which columns and rows of a table an analyst sees.'],
      ['Create an IAM policy for each department that lists the S3 objects it may read', 'This repeats policy edits for every team and still works at the object level, not at the column and row level.'],
      ['Turn on S3 Block Public Access for the data lake bucket and share the bucket with all analysts', 'Block Public Access limits public exposure and does not restrict what authorized analysts can see.'],
    ],
    slot: 0,
    evidence: [
      'lake-formation|Lake Formation provides a single place to manage access controls for data in your data lake.',
      'lake-formation|Lake Formation permissions are enforced using granular controls at the column, row, and cell-levels across AWS analytics and machine learning services, including Amazon Athena, Amazon Quick, Amazon Redshift Spectrum, Amazon EMR, and AWS Glue.',
    ],
  }),
  mc({
    id: 'compliance-registry-002',
    building: 'compliance-registry',
    bullets: ['1.3-K1'],
    d: 3,
    stem: 'A data lake catalog contains thousands of tables that are classified as public, internal, or restricted. The company wants each team to receive access by classification instead of by listing every table, and new tables should be covered as soon as they are labeled. Which solution meets these requirements with the LEAST administrative effort?',
    correct: ['Define LF-Tags for the classifications, attach them to tables and columns, and grant permissions on the tags', 'LF-Tags replace the policy definitions of thousands of resources with a few logical tags, so access follows the label.'],
    wrong: [
      ['Grant each team permissions on every table by name and update the grants whenever a table is added', 'This keeps one grant per table, which does not scale to thousands of tables and misses new tables until someone updates the grants.'],
      ['Write one IAM policy per table that lists the teams that may read it', 'This creates thousands of separate policy definitions and repeats the work for every new table.'],
      ['Place each classification in its own S3 bucket and manage access with a bucket policy per bucket', 'This forces the company to reorganize the data lake and still lacks column-level control through a central catalog.'],
    ],
    slot: 1,
    evidence: [
      'lake-formation|Use Lake Formation attribute-based access control to manage hundreds or even thousands of data permissions by creating custom labels called LF-Tags.',
      'lake-formation|LF-Tags make sure that data governance can be scaled easily by replacing the policy definitions of thousands of resources with a few logical tags.',
    ],
  }),
  mc({
    id: 'compliance-registry-003',
    building: 'compliance-registry',
    bullets: ['1.3-K1'],
    d: 2,
    stem: 'A company wants to share selected tables of its data lake with a partner that has its own AWS account. The partner must receive fine-grained access to only those tables, and the company does not want to copy the data. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Use Lake Formation cross-account sharing to grant the partner access to the selected tables', 'Lake Formation shares data across accounts with fine-grained access to the catalog metadata and the underlying data.'],
    wrong: [
      ['Replicate the tables to a bucket in the partner account and let the partner query the copy', 'This creates a copy of the data, which the company wants to avoid, and the copy then has to be kept in sync.'],
      ['Attach a bucket policy that grants the partner account read access to the entire data lake bucket', 'The partner would see every table in the bucket instead of only the selected ones.'],
      ['Create IAM users in the company account for the partner staff and share their access keys', 'Sharing long-lived credentials is hard to manage and gives no table-level control without more configuration.'],
    ],
    slot: 2,
    evidence: [
      'lake-formation|Lake Formation also allows you to share data internally and externally across multiple AWS accounts, AWS organizations or directly with IAM principals in another account providing fine-grained access to the Data Catalog metadata and underlying data.',
    ],
  }),
  mc({
    id: 'compliance-registry-004',
    building: 'compliance-registry',
    bullets: ['1.3-K1'],
    d: 3,
    stem: 'A company runs a data lake where existing teams read tables through IAM policies and S3 permissions. The company wants to move to Lake Formation permissions one use case at a time without interrupting the permission policies of other users or workloads. Which solution meets these requirements?',
    correct: ['Turn on Lake Formation hybrid access mode and set Lake Formation permissions for one group of users at a time', 'Hybrid access mode is an incremental path that sets Lake Formation permissions for specific users without interrupting existing policies.'],
    wrong: [
      ['Switch every database to Lake Formation permissions at once during a maintenance window and then fix access problems', 'Switching everything together does not keep the existing permission policies of other users and workloads running without interruption.'],
      ['Copy all tables into a new data lake that uses Lake Formation permissions and retire the old one after the copy', 'This duplicates the data and forces every workload to move at once, which is not an incremental path.'],
      ['Keep IAM policies for all current users and use Lake Formation permissions only for users who join after a set date', 'This leaves current users on IAM policies indefinitely and does not move any existing use case to Lake Formation.'],
    ],
    slot: 3,
    evidence: [
      'lake-formation|Lake Formation hybrid access mode provides the flexibility to selectively enable Lake Formation permissions for databases and tables in your Data Catalog.',
      'lake-formation|With hybrid access mode, you now have an incremental path that allows you to set Lake Formation permissions for a specific set of users without interrupting the permission policies of other existing users or workloads.',
    ],
  }),
  mc({
    id: 'compliance-registry-005',
    building: 'compliance-registry',
    bullets: ['1.3-K1', '1.3-S6'],
    d: 2,
    stem: 'A company has 60 accounts in AWS Organizations. The security team must make sure that no Amazon S3 bucket in any member account can be made public, even if a developer attaches a permissive bucket policy, and it wants to set this once for the whole organization. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Enable S3 Block Public Access at the organization level by using an AWS Organizations policy', 'Organization-level Block Public Access applies to selected accounts automatically and overrides account-level settings.'],
    wrong: [
      ['Ask each developer to turn on Block Public Access for every new bucket in the account they work in', 'This depends on every developer remembering a manual step in every account, so nothing is set once for the organization.'],
      ['Enable Amazon Macie in each account and fix any publicly accessible bucket that it reports', 'Macie reports a bucket that becomes publicly accessible after the fact and does not prevent it from being made public.'],
      ['Create an AWS Config rule in each account that notifies the team when a bucket policy allows public access', 'A Config rule detects the violation after it exists and must be created account by account.'],
    ],
    slot: 0,
    evidence: [
      's3-block-public-access|Organization-level block public access uses AWS Organizations policies to centrally manage S3 public access controls across your entire organization.',
      's3-block-public-access|When enabled, these policies automatically apply to selected accounts and override individual account-level settings.',
    ],
  }),
  mc({
    id: 'compliance-registry-006',
    building: 'compliance-registry',
    bullets: ['1.3-K1'],
    d: 1,
    stem: 'A developer attached a bucket policy that grants public read access to an Amazon S3 bucket. The security team then turns on S3 Block Public Access settings for the bucket. Which statement BEST describes the result?',
    correct: ['The Block Public Access settings override the policy, so public access to the bucket is limited', 'Block Public Access settings override policies and permissions that would otherwise allow public access.'],
    wrong: [
      ['The bucket policy takes precedence because it was written for this specific bucket', 'Block Public Access settings override bucket policies and permissions that allow public access, however specific the policy is.'],
      ['Amazon S3 deletes the bucket policy as soon as the Block Public Access settings are turned on', 'Block Public Access settings do not alter existing policies or ACLs, they only override their effect.'],
      ['Only requests that come from other AWS Regions are blocked, and requests from the same Region still succeed', 'The settings are not limited by the Region that a request comes from.'],
    ],
    slot: 1,
    evidence: [
      's3-block-public-access|S3 Block Public Access settings override these policies and permissions so that you can limit public access to these resources.',
      's3-block-public-access|Block public access settings don\'t alter existing policies or ACLs.',
    ],
  }),
  mc({
    id: 'compliance-registry-007',
    building: 'compliance-registry',
    bullets: ['1.3-K1'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A company wants the security team to receive a finding whenever an Amazon S3 bucket becomes publicly accessible, from a service that also keeps an inventory of the company S3 buckets. Which service BEST meets these requirements?',
    correct: ['Amazon Macie', 'Macie maintains an inventory of S3 general purpose buckets and generates a finding when a bucket becomes publicly accessible.'],
    wrong: [
      ['Amazon Inspector', 'Inspector scans EC2 instances, container images, and Lambda functions for vulnerabilities, and it does not report on bucket access.'],
      ['AWS Shield Advanced', 'Shield Advanced protects applications against DDoS attacks and does not evaluate bucket access settings.'],
      ['AWS Artifact', 'Artifact provides AWS compliance documents and agreements, not findings about the company buckets.'],
    ],
    slot: 2,
    evidence: [
      'macie|If Macie detects a potential issue with the security or privacy of your data, such as a bucket that becomes publicly accessible, Macie generates a finding for you to review and remediate as necessary.',
      'macie|When you enable Macie, Macie automatically generates and begins maintaining an inventory of your S3 general purpose buckets.',
      'inspector|Amazon Inspector discovers and scans Amazon EC2 instances, container images in Amazon ECR, and Lambda functions.',
    ],
  }),
  mr({
    id: 'compliance-registry-008',
    building: 'compliance-registry',
    bullets: ['1.3-K1'],
    d: 3,
    stem: 'A company wants Amazon S3 to reject any request that tries to attach a public ACL to a bucket or its objects, and to reject any request that saves a bucket policy granting public access. Existing policies and ACLs may stay as they are for now. Which TWO settings meet these requirements? (Choose two.)',
    correct: [
      ['Turn on the BlockPublicAcls setting', 'With this setting, calls such as PutBucketAcl and PutObjectAcl fail if the ACL is public.'],
      ['Turn on the BlockPublicPolicy setting', 'With this setting, S3 rejects calls to PutBucketPolicy if the policy allows public access.'],
    ],
    wrong: [
      ['Turn on the IgnorePublicAcls setting', 'This setting makes S3 ignore public ACLs but it does not prevent new public ACLs from being set.'],
      ['Turn on the RestrictPublicBuckets setting', 'This setting restricts access to a bucket that has a public policy and does not reject the call that saves the policy.'],
      ['Turn on S3 Versioning for the bucket', 'Versioning keeps object versions and does not reject public ACLs or policies.'],
    ],
    slots: [1, 3],
    evidence: [
      's3-block-public-access|BlockPublicAcls Setting this option to TRUE causes the following behavior: PutBucketAcl and PutObjectAcl calls fail if the specified access control list (ACL) is public.',
      's3-block-public-access|BlockPublicPolicy Setting this option to TRUE for a bucket causes Amazon S3 to reject calls to PutBucketPolicy if the specified bucket policy allows public access.',
      's3-block-public-access|Enabling this setting doesn\'t affect the persistence of any existing ACLs and doesn\'t prevent new public ACLs from being set.',
    ],
  }),
  mc({
    id: 'compliance-registry-009',
    building: 'compliance-registry',
    bullets: ['1.3-S1'],
    d: 1,
    stem: 'An auditor asks a company for the SOC reports and ISO certifications of the AWS infrastructure that the company uses. Which option is the BEST way to obtain these documents?',
    correct: ['Download them from AWS Artifact', 'AWS Artifact provides on-demand downloads of AWS security and compliance documents and certifications.'],
    wrong: [
      ['Create an AWS Config conformance pack in the company account', 'A conformance pack evaluates the configuration of the company resources and does not provide AWS audit reports.'],
      ['Search the AWS CloudTrail event history for the reports', 'CloudTrail records API activity in the account and does not contain AWS compliance reports.'],
      ['Run an Amazon Inspector scan and send the findings to the auditor', 'Inspector findings describe vulnerabilities in the company workloads and are not AWS compliance reports.'],
    ],
    slot: 3,
    evidence: [
      'artifact|AWS Artifact provides on-demand downloads of AWS security and compliance documents.',
      'artifact|AWS Artifact also provides downloads of certifications from accreditation bodies that validate the implementation and operating effectiveness of AWS security controls.',
    ],
  }),
  mc({
    id: 'compliance-registry-010',
    building: 'compliance-registry',
    bullets: ['1.3-S1'],
    d: 2,
    stem: 'A company has 25 accounts in an AWS Organizations structure. A compliance program requires the company to accept an agreement with AWS that applies to every one of these accounts and to track the status in one place. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Use AWS Artifact to accept and track the agreement for the accounts in the organization', 'AWS Artifact lets you review, accept, and track agreements with AWS for one account and for multiple accounts in an organization.'],
    wrong: [
      ['Open an AWS Support case for each account to request and sign the agreement', 'This creates 25 separate manual requests and gives no single place to track the status.'],
      ['Use service control policies in AWS Organizations to accept the agreement for member accounts', 'Service control policies set the maximum available permissions for accounts and do not accept agreements.'],
      ['Download the agreement from AWS Config and store the signed copies in an Amazon S3 bucket', 'AWS Config evaluates resource configuration and is not where agreements with AWS are accepted.'],
    ],
    slot: 0,
    evidence: [
      'artifact|you can use AWS Artifact to review, accept, and track the status of your agreements with AWS for your AWS account and for multiple AWS accounts in your organization.',
      'orgs-scps|SCPs offer central control over the maximum available permissions for the IAM users and IAM roles in your organization.',
    ],
  }),
  mc({
    id: 'compliance-registry-011',
    building: 'compliance-registry',
    bullets: ['1.3-S1'],
    d: 1,
    tags: ['mock-reserve'],
    stem: 'A company is evaluating a product from an independent software vendor that is sold on AWS Marketplace. The company wants to review the vendor security and compliance documents. Which service BEST meets this requirement?',
    correct: ['AWS Artifact', 'AWS Artifact provides downloads of security and compliance documents for independent software vendors who sell their products on AWS Marketplace.'],
    wrong: [
      ['Amazon Macie', 'Macie discovers sensitive data in Amazon S3 and does not provide vendor documents.'],
      ['AWS Config', 'AWS Config evaluates the configuration of resources in the company account and does not provide vendor documents.'],
      ['AWS Shield', 'Shield protects applications against DDoS attacks and does not provide vendor documents.'],
    ],
    slot: 1,
    evidence: [
      'artifact|With AWS Artifact, you can also download security and compliance documents for independent software vendors (ISVs) who sell their products on AWS Marketplace.',
    ],
  }),
  mc({
    id: 'compliance-registry-012',
    building: 'compliance-registry',
    bullets: ['1.3-S1'],
    d: 1,
    stem: 'A company wants to be notified automatically when a resource in its account is created or changed in a way that violates the internal configuration standards. Which service BEST meets this requirement?',
    correct: ['AWS Config with rules that represent the ideal configuration settings', 'AWS Config continuously evaluates resources as they are created or changed and flags those that violate a rule.'],
    wrong: [
      ['AWS CloudTrail event history with a saved search for configuration changes', 'CloudTrail records API activity and does not evaluate resources against configuration rules.'],
      ['AWS Artifact reports for the AWS Region in use', 'Artifact provides AWS compliance documents, not an evaluation of the company resources.'],
      ['Amazon Macie with a sensitive data discovery job', 'Macie looks for sensitive data in Amazon S3 and does not check resource configuration.'],
    ],
    slot: 2,
    evidence: [
      'config-what-is|You can use AWS Config rules to evaluate the configuration settings of your AWS resources.',
      'config-what-is|When AWS Config detects that a resource violates the conditions in one of your rules, AWS Config flags the resource as noncompliant and sends a notification.',
      'config-what-is|AWS Config continuously evaluates your resources as they are created, changed, or deleted.',
    ],
  }),
  mr({
    id: 'compliance-registry-013',
    building: 'compliance-registry',
    bullets: ['1.3-S1'],
    d: 2,
    stem: 'A company with 30 accounts wants to deploy one set of AWS Config rules and remediation actions as a single unit to every account. It also wants to see the compliance data of all accounts and Regions in one account. Which TWO actions meet these requirements with the LEAST operational overhead? (Choose two.)',
    correct: [
      ['Deploy the rules and remediation actions as a conformance pack across the organization', 'A conformance pack is a collection of Config rules and remediation actions that can be deployed as a single entity across an organization.'],
      ['Create an AWS Config aggregator in a central account', 'An aggregator collects configuration and compliance data from multiple accounts and Regions into a single account and Region.'],
    ],
    wrong: [
      ['Create an AWS CloudTrail trail in each account', 'A trail records API activity and does not deploy rules or show compliance data.'],
      ['Download the AWS compliance reports from AWS Artifact for each account', 'Artifact documents describe AWS controls and do not deploy rules or aggregate compliance data.'],
      ['Run an Amazon Macie discovery job in each account', 'Macie looks for sensitive data in Amazon S3 and does not deploy rules or aggregate compliance data.'],
    ],
    slots: [0, 4],
    evidence: [
      'config-conformance-packs|A conformance pack is a collection of AWS Config rules and remediation actions that can be easily deployed as a single entity in an account and a Region or across an organization in AWS Organizations.',
      'config-what-is|An aggregator collects AWS Config configuration and compliance data from multiple AWS accounts and AWS Regions into a single account and Region.',
    ],
  }),
  mc({
    id: 'compliance-registry-014',
    building: 'compliance-registry',
    bullets: ['1.3-S1'],
    d: 2,
    stem: 'AWS Config has been recording a company account for two years. An auditor now asks which inbound port rules an Amazon EC2 security group allowed on a specific date five months ago. Which solution provides this information with the LEAST effort?',
    correct: ['View the recorded configuration history of the security group in AWS Config', 'AWS Config provides the historical configurations of resources, including the port rules that were open at a specific time.'],
    wrong: [
      ['Search the AWS CloudTrail event history for the security group changes around that date', 'Event history covers only the past 90 days of management events, so it cannot reach back five months.'],
      ['Run an Amazon Inspector network scan of the instances today', 'A scan shows the current exposure and cannot show the rules that were in place five months ago.'],
      ['Download the SOC reports from AWS Artifact for that period', 'Artifact reports describe AWS controls and do not list the rules of a customer security group.'],
    ],
    slot: 3,
    evidence: [
      'config-what-is|To demonstrate compliance, you need access to the historical configurations of your resources.',
      'config-what-is|You can also use AWS Config to view the configuration of your EC2 security groups, including the port rules that were open at a specific time.',
      'cloudtrail-what-is|Event history – The Event history provides a viewable, searchable, downloadable, and immutable record of the past 90 days of management events in an AWS Region.',
    ],
  }),
  mc({
    id: 'compliance-registry-015',
    building: 'compliance-registry',
    bullets: ['1.3-S1'],
    d: 3,
    stem: 'A regulation requires a company to keep a record of user and API activity from every account in its AWS Organizations structure for seven years. Auditors must be able to analyze the record in a managed store. The company wants the LEAST operational overhead. Which solution meets these requirements?',
    correct: ['Create a CloudTrail Lake event data store for the organization with the seven-year retention pricing option', 'An event data store can cover multiple accounts through AWS Organizations and can hold event data for up to about seven years.'],
    wrong: [
      ['Rely on the CloudTrail event history in each account, which keeps the activity record', 'Event history covers only the past 90 days of management events, which falls short of seven years.'],
      ['Create an event data store that covers only the management account and choose the seven-year retention pricing option', 'This event data store would record activity for the management account only, and the requirement covers every account in the organization.'],
      ['Turn on AWS Config in every account and use the configuration history as the activity record', 'Config records resource configurations and does not record user and API activity.'],
    ],
    slot: 0,
    evidence: [
      'cloudtrail-what-is|You can keep the event data in an event data store for up to 3,653 days (about 10 years) if you choose the One-year extendable retention pricing option, or up to 2,557 days (about 7 years) if you choose the Seven-year retention pricing option.',
      'cloudtrail-what-is|You can create an event data store for a single AWS account or for multiple AWS accounts by using AWS Organizations.',
      'cloudtrail-what-is|AWS CloudTrail Lake is a managed data lake for capturing, storing, accessing, and analyzing user and API activity on AWS for audit and security purposes.',
    ],
  }),
  mc({
    id: 'compliance-registry-016',
    building: 'compliance-registry',
    bullets: ['1.3-S1', '1.3-S6'],
    d: 2,
    stem: 'A broker-dealer must keep electronic records in write-once-read-many storage in an environment that is subject to SEC 17a-4, CFTC, and FINRA regulations. The company wants an Amazon S3 feature that has been assessed for use in such environments. Which solution BEST meets this requirement?',
    correct: ['Store the records in a bucket with S3 Versioning and S3 Object Lock', 'Object Lock uses a WORM model, works with versioning, and has been assessed for environments that are subject to these regulations.'],
    wrong: [
      ['Store the records in a bucket with S3 Versioning only', 'Versioning keeps multiple versions of objects and is not a write-once-read-many model.'],
      ['Store the records in a bucket with an S3 Lifecycle expiration rule set to the retention period', 'A lifecycle rule deletes expired objects and does not make records write-once-read-many.'],
      ['Store the records in a bucket that uses S3 Replication to a second Region', 'Replication copies objects to another bucket and does not provide a write-once-read-many model.'],
    ],
    slot: 1,
    evidence: [
      's3-object-lock|S3 Object Lock has been assessed by Cohasset Associates for use in environments that are subject to SEC 17a-4, CFTC, and FINRA regulations.',
      's3-object-lock|Object Lock uses a write-once-read-many (WORM) model to store objects.',
      's3-object-lock|Object Lock works only in buckets that have S3 Versioning enabled.',
    ],
  }),
  mc({
    id: 'compliance-registry-017',
    building: 'compliance-registry',
    bullets: ['1.3-S1'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A company must show auditors records of which Amazon S3 objects contain sensitive data and of the analysis that was performed to find them. Which solution produces these records with the LEAST operational overhead?',
    correct: ['Use Amazon Macie sensitive data findings and sensitive data discovery results', 'Macie produces records of the sensitive data that it finds and of the analysis that it performs.'],
    wrong: [
      ['Use the AWS CloudTrail event history for the account and export it for the auditors', 'Event history lists management events and does not record which objects contain sensitive data.'],
      ['Use the compliance reports in AWS Artifact', 'Artifact documents describe AWS controls and do not describe the contents of the company objects.'],
      ['Use an AWS Config rule that evaluates each bucket', 'A Config rule evaluates configuration settings and does not inspect object contents.'],
    ],
    slot: 2,
    evidence: [
      'macie-discovery|To help you meet and maintain compliance with your data security and privacy requirements, Macie produces records of the sensitive data that it finds and the analysis that it performs',
    ],
  }),
  mr({
    id: 'compliance-registry-018',
    building: 'compliance-registry',
    bullets: ['1.3-S1'],
    d: 2,
    stem: 'An auditor asks a company for evidence of two things: that the AWS infrastructure meets recognized standards, and that the company own resources continue to meet its configuration rules. Which TWO actions provide this evidence with the LEAST custom work? (Choose two.)',
    correct: [
      ['Download the AWS compliance reports and certifications from AWS Artifact', 'Artifact provides on-demand downloads of AWS security and compliance documents that can be given to auditors.'],
      ['Evaluate the company resources with AWS Config rules and share the compliance results', 'AWS Config evaluates the configuration settings of resources against the rules that represent the ideal settings.'],
    ],
    wrong: [
      ['Use AWS Artifact to evaluate whether the company resources meet the configuration rules', 'Customers are responsible for documents about their own companies, and Artifact does not evaluate their resources.'],
      ['Use Amazon Macie reports as the evidence of AWS infrastructure compliance', 'Macie reports on sensitive data in the company S3 buckets and not on the compliance of the AWS infrastructure.'],
      ['Use the AWS CloudTrail event history as proof that the resources meet the configuration rules', 'Event history records activity and does not evaluate configuration against rules.'],
    ],
    slots: [2, 3],
    evidence: [
      'artifact|To demonstrate the security and compliance of the AWS infrastructure and services that you use, you can submit AWS Artifact documents to your auditors or regulators as audit artifacts.',
      'artifact|AWS customers are responsible for developing or obtaining documents that demonstrate the security and compliance of their companies.',
      'config-rules|Use AWS Config to evaluate the configuration settings of your AWS resources.',
    ],
  }),
  mc({
    id: 'compliance-registry-019',
    building: 'compliance-registry',
    bullets: ['1.3-S6'],
    d: 2,
    stem: 'A company stores application logs in Amazon S3. The logs are read often for the first 30 days and rarely after that. A regulation requires keeping them for a fixed period, after which they must be deleted. The company wants to meet this with the LEAST operational overhead and the LOWEST storage cost. Which solution meets these requirements?',
    correct: ['Create an S3 Lifecycle configuration with transition actions to lower-cost storage classes and an expiration action at the end of the period', 'Transition actions move objects to lower-cost classes, and an expiration action deletes them after the regulatory period.'],
    wrong: [
      ['Run a scheduled AWS Lambda function that copies each log to another storage class and deletes old logs', 'This is custom code to build and maintain when S3 Lifecycle performs both actions without code.'],
      ['Keep the logs in S3 Standard and have an administrator delete them by hand when the period ends', 'This pays the S3 Standard rate for rarely read logs and depends on a manual deletion step.'],
      ['Enable S3 Object Lock in compliance mode on the bucket with a retention period that equals the period', 'Object Lock prevents deletion during the period and does not move the logs to a lower-cost class.'],
    ],
    slot: 3,
    evidence: [
      's3-lifecycle|There are two types of actions: Transition actions – These actions define when objects transition to another storage class.',
      's3-lifecycle|Expiration actions – These actions define when objects expire.',
      's3-lifecycle|For example, you might to choose to expire objects after they have been stored for a regulatory compliance period.',
    ],
  }),
  mr({
    id: 'compliance-registry-020',
    building: 'compliance-registry',
    bullets: ['1.3-S6'],
    d: 3,
    stem: 'A bucket with S3 Versioning enabled holds financial exports. After a seven-year retention period, every trace of an export must be removed, including all earlier versions and any leftover delete marker. Which THREE S3 Lifecycle actions are needed? (Choose three.)',
    correct: [
      ['An expiration action for the current versions of the objects after the retention period', 'Expiration applies to the current version of an object, which is the starting point of the removal.'],
      ['A NoncurrentVersionExpiration action that permanently deletes noncurrent versions', 'Object expiration has no effect on noncurrent versions, so this action removes the earlier versions.'],
      ['An expiration action that removes expired object delete markers', 'The Expiration action can direct S3 to remove expired object delete markers that remain.'],
    ],
    wrong: [
      ['A transition action to S3 Glacier Deep Archive after the retention period', 'A transition changes the storage class and does not remove any version.'],
      ['An action that returns the bucket to an unversioned state', 'After versioning is enabled the bucket can never return to an unversioned state, it can only be suspended.'],
      ['An action that aborts incomplete multipart uploads after one day', 'This cleans up unfinished uploads and does not remove completed object versions.'],
    ],
    slots: [1, 2, 5],
    evidence: [
      's3-lifecycle-expire|Object expiration applies only to an object\'s current version (it has no impact on noncurrent object versions).',
      's3-lifecycle-expire|You can use the NoncurrentVersionExpiration action element to direct Amazon S3 to permanently delete noncurrent versions of objects.',
      's3-lifecycle-expire|You can also use the Expiration action to direct Amazon S3 to remove any expired object delete markers.',
      's3-versioning|After you version-enable a bucket, it can never return to an unversioned state.',
    ],
  }),
  mc({
    id: 'compliance-registry-021',
    building: 'compliance-registry',
    bullets: ['1.3-S6'],
    d: 2,
    stem: 'A security engineer attaches a bucket policy that denies all actions for all principals on a general purpose S3 bucket, hoping to stop deletions. The bucket also has an S3 Lifecycle configuration with an expiration rule. Which statement BEST describes the effect on the lifecycle rule?',
    correct: ['The lifecycle rule keeps working, because a bucket policy cannot prevent deletions by a lifecycle rule', 'AWS states that even a bucket policy that denies all actions for all principals does not stop the lifecycle configuration.'],
    wrong: [
      ['The deny policy blocks the rule, so no object in the bucket expires until the deny statement is removed', 'A bucket policy cannot prevent deletions or transitions by a lifecycle rule.'],
      ['The rule runs only for objects that are uploaded after the bucket policy was attached', 'The rules of a lifecycle configuration apply to existing objects as well as to objects that are added later.'],
      ['The rule moves each expiring object to another bucket instead of deleting it', 'An expiration action makes S3 delete the expired objects on your behalf.'],
    ],
    slot: 0,
    evidence: [
      's3-lifecycle|You can\'t use a bucket policy to prevent deletions or transitions by an S3 Lifecycle rule.',
      's3-lifecycle|even if your bucket policy denies all actions for all principals, your S3 Lifecycle configuration still functions as normal.',
      's3-lifecycle|When you add a Lifecycle configuration to a bucket, the configuration rules apply to both existing objects and objects that you add later.',
    ],
  }),
  mc({
    id: 'compliance-registry-022',
    building: 'compliance-registry',
    bullets: ['1.3-S6'],
    d: 1,
    stem: 'A company wants every new object version in an Amazon S3 bucket to be protected from deletion for 180 days automatically, without anyone applying a lock to each object. Which solution meets this requirement with the LEAST effort?',
    correct: ['Enable S3 Versioning and Object Lock with a default retention period of 180 days on the bucket', 'A retention period set on the bucket applies to all objects in the bucket automatically, and Object Lock needs versioning.'],
    wrong: [
      ['Apply an Object Lock legal hold to each object version by hand after it is uploaded to the bucket', 'This is a manual step for every object, and a legal hold has no retention period.'],
      ['Add an S3 Lifecycle expiration rule that acts on objects after 180 days', 'An expiration rule deletes objects and does not protect them from deletion.'],
      ['Enable S3 Versioning only and tell users not to delete object versions for 180 days', 'Versioning alone does not stop a user from deleting a version.'],
    ],
    slot: 1,
    evidence: [
      's3-object-lock|Additionally, you can set a default retention period on an S3 bucket.',
      's3-object-lock|You can place a retention period explicitly on an individual object version or on a bucket\'s properties so that it applies to all objects in the bucket automatically.',
      's3-object-lock|Object Lock works only in buckets that have S3 Versioning enabled.',
    ],
  }),
  mc({
    id: 'compliance-registry-023',
    building: 'compliance-registry',
    bullets: ['1.3-S6'],
    d: 3,
    stem: 'A company uses S3 Object Lock for regulated records. Uploaders can choose a retention period for each object, and the compliance team wants to stop anyone from applying a period shorter than five years. The control must be enforced centrally without custom code. Which solution meets these requirements?',
    correct: ['Add a bucket policy that uses the s3:object-lock-remaining-retention-days condition key to limit allowed retention periods', 'The condition key in a bucket policy restricts the minimum and maximum retention periods that users may set.'],
    wrong: [
      ['Set a five-year default retention period on the bucket and rely on it for every upload', 'An individual retention setting on an object version overrides the retention settings of the bucket, so a shorter period could still be set.'],
      ['Use governance mode for the retention setting so that users cannot change it', 'Governance mode lets users with special permissions alter the settings, and it does not limit the length of the period that users set.'],
      ['Attach a permissions boundary that denies the s3:BypassGovernanceRetention permission to uploaders', 'That permission relates to overriding governance-mode settings and does not set a minimum retention period.'],
    ],
    slot: 2,
    evidence: [
      's3-object-lock|You may also restrict the minimum and maximum allowable retention periods with the s3:object-lock-remaining-retention-days condition key in the bucket policy.',
      's3-object-lock|When you PUT an object version that has an explicit individual retention mode and period in a bucket, the object version\'s individual Object Lock settings override any bucket property retention settings.',
    ],
  }),
  mr({
    id: 'compliance-registry-024',
    building: 'compliance-registry',
    bullets: ['1.3-S6'],
    d: 3,
    stem: 'A bucket holds regulated records. No user, including the root user, may delete or overwrite an object version during its retention period. The bucket must also never become publicly accessible, even if someone later attaches a permissive bucket policy. Which TWO actions meet these requirements? (Choose two.)',
    correct: [
      ['Enable S3 Versioning and S3 Object Lock in compliance mode with a retention period', 'In compliance mode no user, including the root user, can overwrite or delete a protected object version.'],
      ['Turn on S3 Block Public Access for the bucket', 'Block Public Access settings override policies and permissions that would otherwise allow public access.'],
    ],
    wrong: [
      ['Enable S3 Object Lock in governance mode with a retention period', 'In governance mode users with special permissions can alter lock settings or delete the object.'],
      ['Rely on the default behavior that new buckets do not allow public access', 'Users can later modify bucket policies or permissions to allow public access, so the default alone is not enough.'],
      ['Run an Amazon Macie sensitive data discovery job on the bucket every week', 'Macie reports on sensitive data and does not prevent deletion or public access.'],
    ],
    slots: [0, 4],
    evidence: [
      's3-object-lock|In compliance mode, a protected object version can\'t be overwritten or deleted by any user, including the root user in your AWS account.',
      's3-object-lock|In governance mode, users can\'t overwrite or delete an object version or alter its lock settings unless they have special permissions.',
      's3-block-public-access|By default, new buckets, access points, and objects don\'t allow public access.',
      's3-block-public-access|However, users can modify bucket policies, access point policies, or object permissions to allow public access.',
      's3-block-public-access|S3 Block Public Access settings override these policies and permissions so that you can limit public access to these resources.',
    ],
  }),
  mc({
    id: 'compliance-registry-025',
    building: 'compliance-registry',
    bullets: ['1.3-S6'],
    d: 2,
    stem: 'A company stores user session items in an Amazon DynamoDB table. A policy says that each item must be deleted after 30 days. The company wants the deletion to happen automatically, without custom code and without consuming write capacity. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Enable time to live on the table and store an expiration timestamp in each item', 'DynamoDB TTL deletes expired items automatically without consuming write throughput.'],
    wrong: [
      ['Schedule an AWS Lambda function that scans the table and deletes the old items', 'This is custom code to maintain, and the delete requests consume write capacity.'],
      ['Switch the table to on-demand capacity mode so that old items are removed over time', 'The capacity mode controls how reads and writes are billed and does not delete any items.'],
      ['Create an S3 Lifecycle rule on the bucket that holds the table backups', 'A lifecycle rule acts on S3 objects and does not delete items from the live table.'],
    ],
    slot: 3,
    evidence: [
      'dynamodb-ttl|Time To Live (TTL) for DynamoDB is a cost-effective method for deleting items that are no longer relevant.',
      'dynamodb-ttl|DynamoDB automatically deletes expired items within a few days of their expiration time, without consuming write throughput.',
      'dynamodb-ttl|The timestamp must be stored as a Number data type in Unix epoch time format at the seconds granularity.',
    ],
  }),
  mc({
    id: 'compliance-registry-026',
    building: 'compliance-registry',
    bullets: ['1.3-S6'],
    d: 2,
    stem: 'A company keeps project files in an Amazon EFS file system. Files that have not been accessed for a long time should move to a lower-cost storage class automatically, without any code. Which solution meets these requirements MOST cost-effectively?',
    correct: ['Configure EFS lifecycle management policies that transition files into the Infrequent Access storage class', 'Lifecycle management automatically transitions files between storage classes, and IA is cost-optimized for rarely accessed data.'],
    wrong: [
      ['Create an S3 Lifecycle configuration that targets the file system and moves old files to S3 Glacier', 'S3 Lifecycle manages objects in S3 buckets and is not a setting of an EFS file system.'],
      ['Run a nightly script on an Amazon EC2 instance that finds old files and copies them to another file system', 'This is custom code that must be maintained, and EFS lifecycle management does the same without any code.'],
      ['Use an AWS Backup plan to move the live files of the file system to its cold storage tier', 'Backup cold storage holds backups and does not store the live files of the file system.'],
    ],
    slot: 0,
    evidence: [
      'efs-lifecycle|Use lifecycle management to automatically transition data between storage classes according to the lifecycle configuration for the file system.',
      'efs-lifecycle|Transition into IA – Instructs lifecycle management when to move files in to the Infrequent Access (IA) storage class, which is cost-optimized for data that is accessed only a few times each quarter.',
    ],
  }),
];

export default questions;
