import type { Question } from '../../../src/content/types.ts';
import { mc, mr } from '../helpers.ts';

const questions: Question[] = [
  mc({
    id: 'customs-house-001',
    building: 'customs-house',
    bullets: ['1.2-K2'],
    d: 1,
    tags: ['trap:gateway-vs-interface-endpoints'],
    stem: 'Amazon EC2 instances in private subnets of a VPC copy large numbers of objects to Amazon S3 in the same Region. The traffic currently goes through a NAT gateway and the internet. The company wants the traffic to stay on the AWS network at the LOWEST cost, with no additional hourly charge for the connection. Which solution meets these requirements?',
    correct: ['Create a gateway VPC endpoint for Amazon S3 and add it to the route tables of the private subnets', 'A gateway endpoint reaches Amazon S3 without an internet gateway or NAT device, and there is no additional charge for using it.'],
    wrong: [
      ['Create an interface VPC endpoint for Amazon S3 in each Availability Zone that has a private subnet', 'It keeps the traffic private, but interface endpoints are billed for hourly usage and data processing, so it is not the lowest cost.'],
      ['Move the instances to public subnets and give each instance a public IP address', 'The traffic would then reach Amazon S3 through the internet gateway instead of staying on the AWS network.'],
      ['Replace the NAT gateway with a larger NAT instance that has more network bandwidth', 'A NAT device still sends the traffic out through the internet, and it adds instances to run.'],
    ],
    slot: 0,
    evidence: [
      'vpce-gateway-s3|With a gateway endpoint, you can access Amazon S3 from your VPC, without requiring an internet gateway or NAT device for your VPC, and with no additional cost.',
      'vpce-gateway-s3|After you create the gateway endpoint, you can add it as a target in your route table for traffic destined from your VPC to Amazon S3.',
      'vpce-interface|You are billed for hourly usage and data processing charges.',
    ],
  }),
  mc({
    id: 'customs-house-002',
    building: 'customs-house',
    bullets: ['1.2-S4'],
    d: 1,
    stem: 'A company has 200 remote employees who work from home. They need secure access from their laptops, from any location, to resources in a VPC. The company does not want to deploy and maintain VPN servers. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Create an AWS Client VPN endpoint and have employees connect with an OpenVPN-based client', 'Client VPN is a managed client-based VPN service for secure access from any location, so no VPN servers have to be run.'],
    wrong: [
      ['Create an AWS Site-to-Site VPN connection and configure a customer gateway for every employee\'s home', 'Site-to-Site VPN connects a whole remote network through a customer gateway device and is not meant for individual laptops.'],
      ['Order an AWS Direct Connect connection for each employee and attach it to the VPC', 'Direct Connect is a physical link from a network to an AWS location, and it is not a way to connect individual remote users.'],
      ['Install an OpenVPN server on Amazon EC2 instances in a public subnet and patch the instances', 'It works, but the company would deploy, scale and maintain the VPN servers itself.'],
    ],
    slot: 2,
    evidence: [
      'client-vpn|With Client VPN, you can access your resources from any location using an OpenVPN-based VPN client.',
      'client-vpn|Managed service — Eliminates the operational burden of deploying and maintaining third-party remote access VPN solutions through complete AWS management.',
    ],
  }),
  mc({
    id: 'customs-house-003',
    building: 'customs-house',
    bullets: ['1.2-K2'],
    d: 2,
    tags: ['trap:gateway-vs-interface-endpoints'],
    stem: 'A company\'s data center is connected to a VPC with AWS Direct Connect. On-premises applications must reach Amazon S3 using private IP addresses in the VPC, and the traffic must not use the public internet. Which solution meets these requirements MOST simply?',
    correct: ['Create an interface VPC endpoint for Amazon S3 and have the on-premises applications use it', 'Gateway endpoints do not allow access from on-premises networks, so an interface endpoint is the type to use for this access.'],
    wrong: [
      ['Create a gateway VPC endpoint for Amazon S3 and advertise it to the data center over the connection', 'Gateway endpoints do not allow access from on-premises networks.'],
      ['Route the on-premises requests to Amazon S3 through a NAT gateway in the VPC', 'A NAT gateway sends outbound traffic through the internet gateway, so the traffic would use the public internet.'],
      ['Add a bucket policy that allows the IP address range of the data center to read the bucket', 'A bucket policy controls who may read the bucket, but it does not change the network path to private IP addresses.'],
    ],
    slot: 1,
    evidence: [
      'vpce-gateway-s3|However, gateway endpoints do not allow access from on-premises networks, from peered VPCs in other AWS Regions, or through a transit gateway.',
      'vpce-gateway-s3|For those scenarios, you must use an interface endpoint, which is available for an additional cost.',
    ],
  }),
  mc({
    id: 'customs-house-004',
    building: 'customs-house',
    bullets: ['1.2-S4'],
    d: 2,
    tags: ['trap:direct-connect-vs-vpn'],
    stem: 'A company must connect its headquarters network to a VPC with an encrypted IPsec connection. The company wants to use its existing internet connection and does not want to order a dedicated physical circuit. Which solution meets these requirements in the SIMPLEST way?',
    correct: ['Create an AWS Site-to-Site VPN connection between a customer gateway device and the VPC', 'Site-to-Site VPN creates an IPsec VPN connection between the remote network and the VPC over the internet.'],
    wrong: [
      ['Order an AWS Direct Connect dedicated connection and attach it to the VPC', 'Direct Connect uses a dedicated physical connection, which the company does not want to order, and it is not encrypted by default.'],
      ['Create an AWS Client VPN endpoint and install the client on a server in the headquarters', 'Client VPN serves individual clients rather than linking an entire network to the VPC.'],
      ['Assign public IP addresses to the instances in the VPC and secure each one with a TLS certificate', 'It exposes the instances to the internet and does not create a connection between the two networks.'],
    ],
    slot: 3,
    evidence: [
      'connectivity-vpn|Amazon VPC provides the option of creating an IPsec VPN connection between your remote networks and Amazon VPC over the internet',
      's2s-vpn|VPN tunnel: An encrypted link where data can pass from the customer network to or from AWS.',
      'dx-encryption|AWS Direct Connect does not encrypt your traffic that is in transit by default.',
    ],
  }),
  mc({
    id: 'customs-house-005',
    building: 'customs-house',
    bullets: ['1.2-K2'],
    d: 2,
    tags: ['trap:peering-tgw-privatelink'],
    stem: 'A company runs a software-as-a-service application on Amazon EC2 instances behind a Network Load Balancer. Hundreds of customers in their own AWS accounts and VPCs, some with overlapping CIDR ranges, must reach the application privately. The company does not want to open network-level access to the rest of its VPC. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Create a VPC endpoint service for the load balancer and let each customer create an interface endpoint', 'PrivateLink lets consumers connect to a provider\'s endpoint service privately, and it suits VPCs with overlapping IP addresses.'],
    wrong: [
      ['Create a VPC peering connection between the company\'s VPC and the VPC of each customer', 'Peering cannot connect VPCs with overlapping CIDR blocks, and it opens network-level routing between the VPCs.'],
      ['Attach the company\'s VPC and every customer VPC to a shared AWS Transit Gateway with routes between them', 'It connects whole networks instead of one service, and it does not solve the overlapping CIDR ranges.'],
      ['Publish the application behind an internet-facing load balancer and protect it with AWS WAF', 'Customers would reach it over the public internet, but the requirement is private access.'],
    ],
    slot: 2,
    evidence: [
      'privatelink-concepts|Consumers create VPC endpoints to connect to endpoint services and resources that are hosted by providers.',
      'privatelink-concepts|A service provider must specify a load balancer when creating an endpoint service.',
      'connectivity-privatelink|Alternatively, AWS PrivateLink is a good solution when the VPCs have overlapped IP addresses.',
      'peering-basics|You cannot create a VPC peering connection between VPCs that have matching or overlapping IPv4 or IPv6 CIDR blocks.',
    ],
  }),
  mc({
    id: 'customs-house-006',
    building: 'customs-house',
    bullets: ['1.2-S4'],
    d: 2,
    tags: ['trap:direct-connect-vs-vpn'],
    stem: 'A media company moves several terabytes every day from its data center to AWS. The current VPN over the internet shows variable throughput and latency. The company wants a dedicated connection with a more consistent network experience that does not pass through internet service providers. Which solution meets these requirements BEST?',
    correct: ['Provision an AWS Direct Connect connection and create a virtual interface to the VPC', 'Direct Connect links the network to an AWS location, bypassing internet service providers, with a more consistent experience than internet-based connections.'],
    wrong: [
      ['Add a second AWS Site-to-Site VPN connection and spread the traffic across both connections', 'Both VPN connections still run over the internet, so the variable throughput and latency remain.'],
      ['Create an AWS Client VPN endpoint and connect the data center servers as clients', 'Client VPN also runs over the internet and is built for individual users, not for a steady data center transfer.'],
      ['Place a larger customer gateway device in the data center and enable the Large Bandwidth Tunnel option', 'Higher tunnel bandwidth does not remove the internet path or give a more consistent network experience.'],
    ],
    slot: 0,
    evidence: [
      'connectivity-dx|Direct Connect can reduce network costs, increase bandwidth throughput, and provide a more consistent network experience than internet-based connections.',
      'dx-what-is|bypassing internet service providers in your network path.',
      'connectivity-vpn|Amazon VPC provides the option of creating an IPsec VPN connection between your remote networks and Amazon VPC over the internet',
    ],
  }),
  mc({
    id: 'customs-house-007',
    building: 'customs-house',
    bullets: ['1.2-K2'],
    d: 2,
    stem: 'Application servers in private subnets use an interface VPC endpoint to call Amazon Kinesis Data Streams. The calls time out. The endpoint network interfaces use only the default security group of the VPC, and the servers belong to a different security group. Which change will fix the problem with the LEAST effort?',
    correct: ['Add a security group to the endpoint that allows inbound HTTPS from the servers\' security group', 'The endpoint network interfaces are protected by security groups, which must allow the expected traffic from the resources in the VPC.'],
    wrong: [
      ['Add a route to the interface endpoint in the route tables of the private subnets', 'Interface endpoints are reached through their network interfaces and private IP addresses, so a route is not what blocks the calls.'],
      ['Attach an internet gateway to the VPC and give every server a public IP address for the Kinesis calls', 'The servers would no longer use the endpoint, and the traffic would go over the internet.'],
      ['Replace the interface endpoint with a gateway endpoint for Amazon Kinesis Data Streams', 'Gateway endpoints support only Amazon S3 and DynamoDB, so one cannot be created for this service.'],
    ],
    slot: 3,
    evidence: [
      'vpce-interface|Create a security group for the endpoint network interface that allows the expected traffic from the resources in your VPC.',
      'vpce-interface|For example, to ensure that the AWS CLI can send HTTPS requests to the AWS service, the security group must allow inbound HTTPS traffic.',
      'vpce-gateway|Gateway VPC endpoints provide reliable connectivity to Amazon S3 and DynamoDB without requiring an internet gateway or a NAT device for your VPC.',
    ],
  }),
  mc({
    id: 'customs-house-008',
    building: 'customs-house',
    bullets: ['1.2-S4'],
    d: 2,
    tags: ['trap:direct-connect-vs-vpn'],
    stem: 'A company uses a 1 Gbps dedicated AWS Direct Connect connection between its data center and AWS. A regulation now requires the traffic to be encrypted in transit, and the company wants to keep using the Direct Connect connection. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Create AWS Site-to-Site VPN tunnels on top of the Direct Connect connection', 'Direct Connect is not encrypted by default, and VPN tunnels on top of the connection provide an IPsec-encrypted private connection.'],
    wrong: [
      ['Enable MAC security (MACsec) on the existing 1 Gbps dedicated connection', 'MACsec is supported only on 10, 100 and 400 Gbps dedicated connections (at selected locations), so it is not available on a 1 Gbps connection.'],
      ['Keep the connection as it is, because the private path already encrypts all traffic', 'AWS states that Direct Connect does not encrypt traffic in transit by default; private is not the same as encrypted.'],
      ['Replace the connection with an AWS Client VPN endpoint for the data center servers', 'It gives up the Direct Connect connection that the company wants to keep, and Client VPN is built for individual users.'],
    ],
    slot: 1,
    evidence: [
      'dx-encryption|AWS Direct Connect does not encrypt your traffic that is in transit by default.',
      'connectivity-dx|For connections of 1 Gbps or less, you can create VPN tunnels on top of the connection',
      'dx-macsec|MACsec is supported on 10 Gbps , 100 Gbps, and 400 Gbps dedicated Direct Connect connections at selected points of presence.',
      'dx-encryption|This combination provides an IPsec-encrypted private connection',
    ],
  }),
  mc({
    id: 'customs-house-009',
    building: 'customs-house',
    bullets: ['1.2-K2'],
    d: 1,
    stem: 'A government contractor\'s application uses the AWS SDK to call AWS services. A compliance rule requires the API calls to use endpoints that support FIPS 140. Which approach meets this requirement with the LEAST effort?',
    correct: ['Configure the SDK to use FIPS endpoints by setting the AWS_USE_FIPS_ENDPOINT variable', 'Some services offer FIPS endpoints, and the SDKs let you choose them with a setting such as AWS_USE_FIPS_ENDPOINT.'],
    wrong: [
      ['Switch the SDK to dual-stack endpoints so that the calls use both IPv4 and IPv6', 'Dual-stack endpoints add IPv6 access; they do not make the endpoint support FIPS 140.'],
      ['Create gateway VPC endpoints for every AWS service that the application calls', 'Gateway endpoints exist only for Amazon S3 and DynamoDB, and they are not FIPS endpoints.'],
      ['Keep the default Regional endpoints and add a security group that allows only HTTPS to them', 'The default endpoints are standard endpoints, and a security group rule does not change which endpoint is used.'],
    ],
    slot: 0,
    evidence: [
      'service-endpoints|Some AWS services offer endpoints that support Federal Information Processing Standard (FIPS) 140 in some Regions.',
      'service-endpoints|Set the AWS_USE_FIPS_ENDPOINT environment variable to true',
      'service-endpoints|Some AWS services offer dual stack endpoints, so that you can access them using either IPv4 or IPv6 requests.',
    ],
  }),
  mc({
    id: 'customs-house-010',
    building: 'customs-house',
    bullets: ['1.2-S4'],
    d: 2,
    stem: 'A company has an AWS Site-to-Site VPN connection to its data center. The network engineer configured only one of the two tunnels on the on-premises firewall. When AWS performed maintenance on that tunnel, connectivity to the VPC dropped. Which action prevents this with the LEAST effort?',
    correct: ['Configure the second tunnel of the VPN connection on the on-premises firewall as well', 'Traffic moves automatically to the available tunnel only if both tunnels are configured, which is why AWS says to configure both.'],
    wrong: [
      ['Order an AWS Direct Connect connection and remove the VPN connection', 'It is a new physical circuit and a larger project than finishing the configuration of the tunnels that already exist.'],
      ['Turn on the Large Bandwidth Tunnel option for the tunnel that is already configured', 'It raises the bandwidth per tunnel but does not give a second path when that tunnel is down.'],
      ['Create a new VPN connection that uses a second virtual private gateway for the same VPC', 'The existing connection already has two tunnels, so the missing piece is configuration, not another gateway.'],
    ],
    slot: 2,
    evidence: [
      'vpn-tunnels|It is important to configure both tunnels for redundancy.',
      'vpn-tunnels|When one tunnel becomes unavailable (for example, down for maintenance), network traffic is automatically routed to the available tunnel for that specific Site-to-Site VPN connection.',
      's2s-vpn|Each VPN connection includes two VPN tunnels which you can simultaneously use for high availability.',
    ],
  }),
  mr({
    id: 'customs-house-011',
    building: 'customs-house',
    bullets: ['1.2-K2'],
    d: 3,
    tags: ['trap:gateway-vs-interface-endpoints'],
    stem: 'A company stores data in Amazon S3 in us-east-1. Amazon EC2 instances in private subnets of a VPC in us-east-1 and servers in an on-premises data center, connected to the VPC by AWS Site-to-Site VPN, must both reach Amazon S3 privately. The company wants the MOST cost-effective design. Which TWO actions meet these requirements? (Choose two.)',
    correct: [
      ['Create a gateway VPC endpoint for Amazon S3 and add it to the route tables of the private subnets', 'A gateway endpoint gives the instances private access to Amazon S3 with no additional charge.'],
      ['Create an interface VPC endpoint for Amazon S3 and have the on-premises servers use it through the VPN', 'On-premises networks cannot use a gateway endpoint, so they need an interface endpoint.'],
    ],
    wrong: [
      ['Use the interface endpoint for the instances in the VPC as well and skip the gateway endpoint', 'It works, but interface endpoints are billed for hourly usage and data processing, whereas the gateway endpoint has no additional charge.'],
      ['Advertise the prefix list of the gateway endpoint to the data center over the VPN connection', 'Gateway endpoints do not allow access from on-premises networks.'],
      ['Add a NAT gateway in a public subnet and route the instances and the servers through it', 'It sends the Amazon S3 traffic out through the internet gateway instead of keeping it private.'],
    ],
    slots: [0, 3],
    evidence: [
      'vpce-gateway-s3|With a gateway endpoint, you can access Amazon S3 from your VPC, without requiring an internet gateway or NAT device for your VPC, and with no additional cost.',
      'vpce-gateway-s3|However, gateway endpoints do not allow access from on-premises networks, from peered VPCs in other AWS Regions, or through a transit gateway.',
      'vpce-interface|You are billed for hourly usage and data processing charges.',
    ],
  }),
  mc({
    id: 'customs-house-012',
    building: 'customs-house',
    bullets: ['1.2-S4'],
    d: 3,
    tags: ['trap:direct-connect-vs-vpn'],
    stem: 'A company runs a critical workload that depends on its AWS Direct Connect connectivity. The company must protect against the failure of a single device and of a whole Direct Connect location, and it wants the MOST highly available design. Which design meets these requirements?',
    correct: ['Order separate connections that end on separate devices in more than one location', 'The maximum resiliency model uses separate connections on separate devices in more than one location for critical workloads.'],
    wrong: [
      ['Order two connections that end on separate devices in the same Direct Connect location', 'It survives a device failure, but a failure of that location would still stop both connections.'],
      ['Order one connection and group it with others in a link aggregation group at the same endpoint', 'A link aggregation group aggregates connections at a single endpoint, so it does not protect against a location failure.'],
      ['Order one connection with the highest port speed available at a single Direct Connect location', 'A faster port adds bandwidth, but the single device and the single location remain points of failure.'],
    ],
    slot: 3,
    evidence: [
      'dx-resiliency|You can achieve maximum resiliency for critical workloads by using separate connections that terminate on separate devices in more than one location',
      'dx-resiliency|Development and test: This model provides you a way to achieve development and test resiliency for non-critical workloads, by using separate connections that terminate on separate devices in one location.',
      'connectivity-dx|For dedicated connections, you can also use a link aggregation group (LAG) to aggregate multiple connections at a single AWS Direct Connect endpoint.',
    ],
  }),
  mc({
    id: 'customs-house-013',
    building: 'customs-house',
    bullets: ['1.2-K2'],
    d: 3,
    stem: 'A company stores regulated documents in an Amazon S3 bucket. Compliance requires that the bucket can be accessed only by Amazon EC2 instances in one VPC through the gateway endpoint for Amazon S3, and not from the internet. The instances have private IP addresses. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Add a bucket policy that denies requests that do not come through the gateway endpoint (aws:sourceVpce)', 'A bucket policy can deny requests that do not use a specific endpoint, which limits access to the VPC endpoint.'],
    wrong: [
      ['Add a bucket policy that allows only the private IP addresses of the instances, using the aws:SourceIp condition key', 'The aws:SourceIp condition cannot be used for requests to Amazon S3 that traverse a VPC endpoint.'],
      ['Attach an endpoint policy to the gateway endpoint that allows access to only this bucket', 'An endpoint policy limits what can be reached through the endpoint, but requests from the internet would still reach the bucket.'],
      ['Turn on the S3 Block Public Access settings for the bucket and keep its default policy', 'Block Public Access prevents public grants, but it does not limit access to one VPC endpoint.'],
    ],
    slot: 1,
    evidence: [
      'vpce-gateway-s3|You can use bucket policies to control access to buckets from specific endpoints, VPCs, IP address ranges, and AWS accounts.',
      'vpce-gateway-s3|You can create a bucket policy that restricts access to a specific endpoint by using the aws:sourceVpce condition key.',
      'vpce-gateway-s3|You can\'t use the aws:SourceIp condition in an identity policy or a bucket policy for requests to Amazon S3 that traverse a VPC endpoint.',
      'vpce-policies|An endpoint policy does not override or replace identity-based policies or resource-based policies.',
    ],
  }),
  mr({
    id: 'customs-house-014',
    building: 'customs-house',
    bullets: ['1.2-S4'],
    d: 3,
    tags: ['trap:peering-tgw-privatelink'],
    stem: 'A company has 12 VPCs in one Region and a data center. All VPCs must reach the data center over AWS Site-to-Site VPN, and the company wants to avoid creating a separate VPN connection for each VPC. Which TWO actions meet these requirements with the LEAST operational overhead? (Choose two.)',
    correct: [
      ['Create a transit gateway and attach each of the 12 VPCs to it', 'A transit gateway is a transit hub that interconnects VPCs and on-premises networks.'],
      ['Create the Site-to-Site VPN connection on the transit gateway instead of on a virtual private gateway', 'A VPN connection can end on a transit gateway, so one connection serves all attached VPCs.'],
    ],
    wrong: [
      ['Attach one virtual private gateway to all 12 VPCs and create one VPN connection on it', 'A virtual private gateway can be attached to a single VPC.'],
      ['Peer the 11 other VPCs with the one VPC that has the VPN connection and route through it', 'VPC peering does not support transitive peering relationships, so traffic cannot pass through the VPC to the data center.'],
      ['Create an interface VPC endpoint in each VPC that points to the data center', 'Interface endpoints reach AWS services and endpoint services, not an on-premises network.'],
    ],
    slots: [1, 3],
    evidence: [
      's2s-vpn-how|Transit gateway A transit gateway is a transit hub that you can use to interconnect your VPCs and your on-premises networks.',
      's2s-vpn-how|A Site-to-Site VPN connection consists of the following components: A virtual private gateway or a transit gateway A customer gateway device A customer gateway',
      's2s-vpn|Virtual private gateway: A virtual private gateway is the VPN endpoint on the Amazon side of your Site-to-Site VPN connection that can be attached to a single VPC.',
      'peering-basics|VPC peering does not support transitive peering relationships.',
    ],
  }),
  mr({
    id: 'customs-house-015',
    building: 'customs-house',
    bullets: ['1.2-S4'],
    d: 2,
    stem: 'A company has an AWS Direct Connect connection to its data center. On-premises servers must reach Amazon EC2 instances in a single VPC by private IP addresses and must also reach Amazon S3, all over the Direct Connect connection. The VPC does not use a transit gateway, has no interface endpoints, and the company does not want to create any. Which TWO virtual interfaces meet these requirements with the LEAST complexity? (Choose two.)',
    correct: [
      ['A private virtual interface for access to the VPC', 'A private virtual interface enables access to a VPC by using private IP addresses.'],
      ['A public virtual interface for access to Amazon S3', 'A public virtual interface enables access to public AWS services such as Amazon S3.'],
    ],
    wrong: [
      ['A transit virtual interface for access to the VPC', 'A transit virtual interface is for Transit Gateways associated with Direct Connect gateways, and this VPC has none.'],
      ['A second private virtual interface for access to Amazon S3', 'A private virtual interface reaches the VPC; Amazon S3 over it would need an interface endpoint, which this design does not have, and a second private virtual interface adds nothing.'],
      ['A Site-to-Site VPN tunnel on the Direct Connect connection for access to the VPC', 'It encrypts the traffic but does not provide the virtual interfaces that give access to the VPC and Amazon S3.'],
    ],
    slots: [0, 4],
    evidence: [
      'dx-what-is|A private virtual interface enables access to your VPC.',
      'dx-what-is|A public virtual interface enables access to public services, such as Amazon S3.',
      'dx-what-is|Transit virtual interface This type of interface is used to access one or more Amazon VPC Transit Gateways associated with Direct Connect gateways.',
    ],
  }),
  mc({
    id: 'customs-house-016',
    building: 'customs-house',
    bullets: ['1.2-K2'],
    d: 1,
    tags: ['mock-reserve'],
    stem: 'AWS Lambda functions in private subnets of a VPC reach Amazon DynamoDB through a gateway VPC endpoint that uses the default endpoint policy. The security team wants traffic over this endpoint to reach only the orders table, for every workload in the VPC, without editing each workload\'s IAM role. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Attach a custom endpoint policy to the gateway endpoint that allows access only to the orders table', 'An endpoint policy controls which principals can use the endpoint to access which resources, and the default policy allows full access.'],
    wrong: [
      ['Add outbound rules to the security groups of the functions that allow traffic only to the orders table', 'Security group rules match protocol, port and the service prefix list for the whole service, not individual DynamoDB tables.'],
      ['Add network ACL rules to the private subnets that allow traffic only to the orders table', 'Network ACL rules match IP address ranges and ports, not individual DynamoDB tables.'],
      ['Replace the gateway endpoint with an interface endpoint and keep its default endpoint policy', 'The default endpoint policy allows full access, so every table stays reachable, and interface endpoints add hourly and data processing charges.'],
    ],
    slot: 2,
    evidence: [
      'vpce-policies|An endpoint policy is a resource-based policy that you attach to a VPC endpoint to control which AWS principals can use the endpoint to access an AWS service.',
      'vpce-gateway-ddb|For Policy, select Full access to allow all operations by all principals on all resources over the VPC endpoint.',
      'vpce-gateway-ddb|Otherwise, select Custom to attach a VPC endpoint policy that controls the permissions that principals have to perform actions on resources over the VPC endpoint.',
      'vpce-interface|You are billed for hourly usage and data processing charges.',
    ],
  }),
  mc({
    id: 'customs-house-017',
    building: 'customs-house',
    bullets: ['1.2-S4'],
    d: 2,
    tags: ['mock-reserve', 'trap:direct-connect-vs-vpn'],
    stem: 'A company has a 100 Gbps dedicated AWS Direct Connect connection. The security team wants the data encrypted between the corporate data center and the Direct Connect location without creating VPN tunnels. Which solution meets this requirement with the LEAST effort?',
    correct: ['Use a Direct Connect connection that supports MACsec and enable MAC security on it', 'Connections that support MACsec can encrypt data from the corporate data center to the Direct Connect location.'],
    wrong: [
      ['Rely on the dedicated connection, because Direct Connect encrypts traffic by default', 'AWS states that Direct Connect does not encrypt traffic in transit by default.'],
      ['Create an AWS Client VPN endpoint and connect the data center router to it', 'Client VPN is for individual users and builds VPN sessions, which the company wants to avoid.'],
      ['Create AWS Site-to-Site VPN tunnels on top of the Direct Connect connection', 'It encrypts the traffic, but it creates the VPN tunnels that the company does not want.'],
    ],
    slot: 1,
    evidence: [
      'dx-encryption|You can use Direct Connect connections that support MACsec to encrypt your data from your corporate data center to the Direct Connect location.',
      'connectivity-dx|For dedicated connections of 10 or 100 Gbps, you can use MAC security (MACsec) as an encryption option.',
      'dx-encryption|AWS Direct Connect does not encrypt your traffic that is in transit by default.',
    ],
  }),
  mr({
    id: 'customs-house-018',
    building: 'customs-house',
    bullets: ['1.2-S4'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A company has one AWS Site-to-Site VPN connection to a virtual private gateway, with a single customer gateway device in its data center. A failure of that device would cut connectivity to the VPC. Which TWO actions will MOST effectively protect against this failure? (Choose two.)',
    correct: [
      ['Add a second customer gateway device in the data center', 'A second device keeps traffic flowing if the first one fails or needs maintenance.'],
      ['Create a second Site-to-Site VPN connection that uses the same virtual private gateway and the new customer gateway', 'A second VPN connection through the second device protects against loss of connectivity if one device becomes unavailable.'],
    ],
    wrong: [
      ['Turn on the Large Bandwidth Tunnel option on the existing connection', 'It raises the bandwidth of a tunnel, but both tunnels still end on the same device.'],
      ['Create a Client VPN endpoint for the data center network', 'Client VPN connects individual clients and does not give the network a second path.'],
      ['Add a NAT gateway in each Availability Zone of the VPC', 'A NAT gateway gives private subnets outbound internet access and does not add a path to the data center.'],
    ],
    slots: [2, 4],
    evidence: [
      'vpn-redundant|To protect against a loss of connectivity in case your customer gateway device becomes unavailable, you can set up a second Site-to-Site VPN connection to your VPC and virtual private gateway by adding a second customer gateway device.',
      'vpn-redundant|Set up a second Site-to-Site VPN connection by using the same virtual private gateway and creating a new customer gateway.',
      's2s-vpn|Large Bandwidth Tunnel : A tunnel configuration that supports up to 5 Gbps bandwidth per tunnel, compared to the standard 1.25 Gbps.',
    ],
  }),
];

export default questions;
