import type { Question } from '../../../src/content/types.ts';
import { mc, mr } from '../helpers.ts';

const questions: Question[] = [
  mc({
    id: 'embassy-row-001',
    building: 'embassy-row',
    bullets: ['1.1-K1'],
    d: 1,
    stem: 'A company runs dozens of AWS accounts for different teams. The company wants to group the accounts by environment, apply governance policies to each group, and pay with a single payment method. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Create an organization in AWS Organizations and place the accounts in organizational units', 'AWS Organizations lets you group accounts, apply policies for governance, and use a single payment method for all of the accounts.'],
    wrong: [
      ['Create an IAM user group for each team in one account and attach a billing policy to each group', 'IAM groups exist inside a single account, so they cannot group separate accounts, apply governance to them, or combine their payment.'],
      ['Share the resources of each account with the other accounts by using AWS Resource Access Manager', 'AWS RAM shares resources across accounts but does not group accounts, apply governance policies, or consolidate payment.'],
      ['Send AWS CloudTrail events from every account to one Amazon S3 bucket in a logging account', 'A central log helps auditing but does not group the accounts, apply policies to them, or simplify billing.'],
    ],
    slot: 0,
    evidence: [
      'orgs-intro|Using Organizations, you can create accounts and allocate resources, group accounts to organize your workflows, apply policies for governance, and simplify billing by using a single payment method for all of your accounts.',
    ],
  }),
  mc({
    id: 'embassy-row-002',
    building: 'embassy-row',
    bullets: ['1.1-K1'],
    d: 1,
    stem: 'A company runs its production application and its development and test environments in a single AWS account. An auditor asks the company to isolate production workloads from development and test workloads as strongly as possible. Which approach provides the MOST isolation?',
    correct: ['Move the development and test workloads into separate AWS accounts that are grouped in an organization', 'AWS describes accounts as a hard boundary and recommends account-level separation for isolating production from development and test workloads.'],
    wrong: [
      ['Place the development workloads in separate subnets of the production VPC and add network ACL rules between them', 'Subnets and network ACLs separate traffic inside one account, but the workloads still sit inside the same account boundary.'],
      ['Create one IAM user group per environment in the same account and attach a separate permissions policy to each group', 'Groups separate who can do what, but every environment still runs inside the same account boundary.'],
      ['Tag every production resource and write IAM policies that deny access to developers who work on other resources', 'Tags and policy conditions are controls inside one account; they are not the hard boundary that separate accounts provide.'],
    ],
    slot: 1,
    evidence: [
      'sec-account-separation|In AWS, accounts are a hard boundary.',
      'sec-account-separation|For example, account-level separation is strongly recommended for isolating production workloads from development and test workloads.',
    ],
  }),
  mc({
    id: 'embassy-row-003',
    building: 'embassy-row',
    bullets: ['1.1-K1'],
    d: 2,
    stem: 'A central networking team owns Amazon VPC subnets in a shared-services account of an AWS Organizations organization. Application teams in 40 other member accounts must launch resources into those subnets. The company does not want duplicate subnets in every account. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Share the subnets with the organization by using AWS Resource Access Manager (AWS RAM)', 'AWS RAM lets the networking team create the subnets once and share them with the accounts in the organization, so no duplicate subnets are provisioned.'],
    wrong: [
      ['Create a VPC peering connection from the VPC of each member account to the shared-services VPC', 'Peering routes traffic between networks, but it does not let a member account launch its resources into the other account subnets.'],
      ['Attach a service control policy to the organization root that allows access to the shared-services subnets', 'SCPs do not grant permissions; they only set limits on what the accounts can do.'],
      ['Create an IAM role in the shared-services account for each team and have the teams launch resources through it', 'The resources would be created in the shared-services account instead of the team accounts, and every team needs its own role to maintain.'],
    ],
    slot: 2,
    evidence: [
      'orgs-intro|Ensure that application resources are created on your Amazon Virtual Private Cloud (Amazon VPC) subnets by centrally defining them once and sharing them across your organization using AWS Resource Access Manager (AWS RAM).',
      'ram-what-is|This eliminates the need to provision duplicate resources in every account, which reduces operational overhead.',
    ],
  }),
  mc({
    id: 'embassy-row-004',
    building: 'embassy-row',
    bullets: ['1.1-K1', '1.1-S5'],
    d: 2,
    tags: ['placement-eligible', 'trap:iam-roles-vs-resource-policies'],
    stem: 'A shared-services account owns an Amazon S3 bucket that holds static assets, such as images and style sheets, for the websites in every account of the company organization. Every current and future account must be able to read the bucket. The security team does not want to edit the bucket policy whenever an account is added or removed. Which solution meets these requirements with the LEAST ongoing effort?',
    correct: ['Add a bucket policy statement that allows s3:GetObject and uses the aws:PrincipalOrgID condition key with the organization ID', 'Policies that use aws:PrincipalOrgID automatically include the correct accounts as accounts are added and removed, so the bucket policy needs no manual updates.'],
    wrong: [
      ['Add a bucket policy statement that lists the account ID of every member account in the organization as a principal of the bucket', 'It works today, but every added or removed account requires an edit to the policy, which is the ongoing effort the team wants to avoid.'],
      ['Create an IAM user in each member account and add every user ARN to the principals of the bucket policy', 'Each new account needs a new user and another edit of the policy, and long-term user credentials add more to manage.'],
      ['Attach a service control policy to the organization root that allows s3:GetObject on the bucket', 'SCPs do not grant permissions, so the bucket would still need a policy that allows the access.'],
    ],
    slot: 3,
    evidence: [
      "iam-global-condition-keys|When you add and remove accounts, policies that include the aws:PrincipalOrgID key automatically include the correct accounts and don't require manual updating.",
      'orgs-scps|SCPs do not grant permissions to the IAM users and IAM roles in your organization.',
    ],
  }),
  mr({
    id: 'embassy-row-005',
    building: 'embassy-row',
    bullets: ['1.1-K1', '1.1-S3', '1.1-S5'],
    d: 2,
    tags: ['trap:iam-roles-vs-resource-policies'],
    stem: 'A company owns an Amazon S3 bucket in account A. Engineers in account B must read objects from the bucket. Which TWO approaches can give the engineers cross-account access? (Choose two.)',
    correct: [
      ['Attach a resource-based policy to the bucket that names the principals of account B', 'A resource-based policy specifies which principal can access the resource, so it can grant access directly to principals in another account.'],
      ['Create a role in account A that trusts account B and let the engineers assume it', 'A cross-account role has a trust policy that allows IAM principals in another account to assume it, so the role works as a proxy.'],
    ],
    wrong: [
      ['Add a Principal element for account B to an identity-based policy of an IAM group in account A', 'The Principal element cannot be used in an identity-based policy, so such a policy cannot name another account.'],
      ['Attach a service control policy to account A that allows s3:GetObject for account B', 'SCPs do not grant permissions to anyone; they only set the maximum available permissions.'],
      ['Attach a permissions boundary to the bucket that lists the account B engineers', 'A permissions boundary applies to IAM users and roles, not to a bucket, and it sets a maximum without granting access.'],
    ],
    slots: [0, 3],
    evidence: [
      'iam-cross-account|To do this, you can attach a resource policy directly to the resource that you want to share, or use a role as a proxy.',
      's3-bucket-policies|A bucket policy is a resource-based policy that you can use to grant access permissions to your Amazon S3 bucket and the objects in it.',
      'iam-el-principal|You cannot use the Principal element in an identity-based policy.',
      'orgs-scps|SCPs do not grant permissions to the IAM users and IAM roles in your organization.',
    ],
  }),
  mc({
    id: 'embassy-row-006',
    building: 'embassy-row',
    bullets: ['1.1-S3'],
    d: 1,
    stem: 'A reporting application in one AWS account must read data in a second AWS account that the company owns. The security team does not want long-term access keys stored in the application. Which solution BEST meets this requirement?',
    correct: ['Create an IAM role in the second account and have the application assume it to get temporary credentials', 'The role has no long-term credentials; assuming it returns temporary security credentials that are generated dynamically when requested.'],
    wrong: [
      ['Create an IAM user in the second account and store its access keys in the configuration file of the application', 'Access keys are long-term credentials that would be embedded in the application, which the team wants to avoid.'],
      ['Create an IAM user in the second account and rotate its access keys by hand every quarter', 'Rotation shortens the exposure, but the application still depends on long-term access keys that someone must distribute.'],
      ['Use the root user access keys of the second account and keep them in an encrypted file', 'Root user keys are long-term credentials, so the application would still hold access keys.'],
    ],
    slot: 0,
    evidence: [
      'iam-temp-creds|You do not have to distribute or embed long-term AWS security credentials with an application.',
      'iam-temp-creds|Temporary security credentials are not stored with the user but are generated dynamically and provided to the user when requested.',
      'iam-roles|a role does not have standard long-term credentials such as a password or access keys associated with it.',
    ],
  }),
  mc({
    id: 'embassy-row-007',
    building: 'embassy-row',
    bullets: ['1.1-K1', '1.1-S3'],
    d: 2,
    stem: 'A company has a security account and 12 workload accounts. Auditors sign in to the security account and need temporary read-only access to resources in the workload accounts. The company does not want to create and manage separate IAM users for the auditors in every workload account. Which solution meets these requirements MOST securely?',
    correct: ['Create a read-only role in each workload account whose trust policy names the security account, and let the auditors assume it', 'Auditors keep one identity in the security account and switch to the role for temporary access to only the permissions that the role defines.'],
    wrong: [
      ['Create an IAM user in every workload account for each auditor and send the initial sign-in details to every auditor in an encrypted email message', 'It creates the duplicate identities and credentials that the company wants to avoid, and shared sign-in details weaken security.'],
      ['Allow anonymous read access to the resources and limit it with a condition on the office IP address range', 'Anonymous access exposes the resources to everyone who matches the condition and does not tie access to authenticated auditors.'],
      ['Attach a service control policy to the security account that allows read access to the workload accounts', 'SCPs do not grant permissions, and a policy in the security account cannot give access to resources in another account.'],
    ],
    slot: 1,
    evidence: [
      'iam-account-switch|Although you could create separate identities (and passwords) for users who work in both accounts, managing credentials for multiple accounts makes identity management difficult.',
      'iam-account-switch|In the role, the administrator defines a trust policy that specifies the development account as a Principal, meaning that authorized users from the development account can use the UpdateApp role.',
    ],
  }),
  mc({
    id: 'embassy-row-008',
    building: 'embassy-row',
    bullets: ['1.1-S3'],
    d: 2,
    stem: 'A company hires a third-party monitoring vendor whose software must read configuration data in the company AWS account. The vendor serves many customers from its own AWS account. The company wants to prevent another customer of the vendor from tricking the vendor into using the company role. Which solution meets this requirement MOST effectively?',
    correct: ['Create a cross-account role whose trust policy requires a unique external ID that the vendor must supply when assuming the role', 'The external ID is the mechanism AWS provides to prevent the confused deputy problem when a third party assumes a role in your account.'],
    wrong: [
      ['Create a cross-account role that trusts the whole vendor account and give the vendor only the ARN of that role for use in its software', 'Trusting the whole vendor account with no external ID does not stop another customer of the vendor from causing the vendor to use the role.'],
      ['Create an IAM user for the vendor and email its access keys to the vendor security contact', 'Access keys are long-term credentials, and sharing them does not address the risk of another customer misusing the vendor.'],
      ['Attach a service control policy to the company account that names the vendor account', 'SCPs do not grant permissions and do not stop the vendor from being tricked into using the role.'],
    ],
    slot: 2,
    evidence: [
      'iam-third-party|The primary function of the external ID is to address and prevent The confused deputy problem.',
      "iam-third-party|You should assign a unique external ID to each customer and instruct them to add the external ID to their role's trust policy.",
    ],
  }),
  mr({
    id: 'embassy-row-009',
    building: 'embassy-row',
    bullets: ['1.1-S3'],
    d: 2,
    stem: 'A company has a development account and a production account. Members of the Developers IAM group in the development account must be able to update objects in an Amazon S3 bucket in the production account by using temporary credentials. Which TWO steps are required? (Choose two.)',
    correct: [
      ['In the production account, create a role with permissions for the bucket and a trust policy that names the development account', 'The trust policy lets principals of the trusted account use the role, and the permissions policy defines what the role may do in the bucket.'],
      ['In the development account, attach a policy to the Developers group that allows sts:AssumeRole on the role ARN', 'Users in the trusted account must also be granted permission to assume the role through the sts:AssumeRole action.'],
    ],
    wrong: [
      ["In the production account, add the Developers group as a principal in the permissions policy of the role", 'A user group cannot be identified as a principal, and the permissions policy of a role defines what the role can do rather than who can assume it.'],
      ['In the development account, create access keys for the production role and give them to each developer', 'A role has no standard long-term credentials such as access keys; it provides temporary credentials when it is assumed.'],
      ['In the production account, attach a service control policy that allows the Developers group to assume the role', 'SCPs do not grant permissions, so they cannot give the group the ability to assume the role.'],
    ],
    slots: [1, 4],
    evidence: [
      'iam-cross-account-role|To do this, the administrator attaches a policy to the user or a group that grants permission for the sts:AssumeRole action.',
      'iam-account-switch|In the role, the administrator defines a trust policy that specifies the development account as a Principal, meaning that authorized users from the development account can use the UpdateApp role.',
      'iam-el-principal|You cannot identify a user group as a principal in a policy',
    ],
  }),
  mc({
    id: 'embassy-row-010',
    building: 'embassy-row',
    bullets: ['1.1-S3'],
    d: 2,
    stem: 'A developer signs in to the AWS Management Console as an IAM user whose policy allows only Amazon S3 read access. The developer then switches to a role in the same account that allows only Amazon EC2 read access. Which statement BEST describes the developer permissions while the role is active?',
    correct: ['Only the Amazon EC2 read permissions of the role apply, and the user S3 read permissions are set aside until the developer exits the role', 'Only one set of permissions is active at a time; switching to a role temporarily sets aside the original user permissions.'],
    wrong: [
      ['The developer has both Amazon S3 read and Amazon EC2 read permissions because the two sets are combined', 'The permissions of the user and of a role that the user switches to are not cumulative, so the sets are not combined.'],
      ['The developer keeps only the Amazon S3 read permissions because the permissions of the IAM user always take precedence over the permissions of a role', 'While the role is active the user permissions are set aside, so they do not take precedence over the role permissions.'],
      ['The developer has no permissions until an administrator attaches the role to the group of the IAM user', 'Once the user is allowed to switch, the role permissions apply as soon as the switch succeeds; no attachment to a group is involved.'],
    ],
    slot: 3,
    evidence: [
      "iam-switch-role|The permissions of your user and any roles that you switch to aren't cumulative.",
      'iam-switch-role|Only one set of permissions is active at a time.',
    ],
  }),
  mc({
    id: 'embassy-row-011',
    building: 'embassy-row',
    bullets: ['1.1-S3'],
    d: 3,
    stem: 'A batch job runs under an IAM role in account A. The job uses the credentials of that role to assume a role in account B, whose maximum session duration is set to 12 hours. The job needs about three hours, but its credentials stop working after one hour. Which statement explains this behavior?',
    correct: ['Using the credentials of one role to assume another role is role chaining, which limits the session to one hour', 'AWS limits a chained session to one hour, regardless of the maximum session duration set on the individual roles.'],
    wrong: [
      ['The trust policy of the role in account B must include an external ID before it can issue longer sessions', 'An external ID is a condition for third-party access and does not change how long a chained session lasts.'],
      ['AWS ignores the maximum session duration of every role that is assumed from a different AWS account', 'The cause is role chaining; the maximum session duration is not ignored for cross-account roles in general.'],
      ['Roles can never issue credentials that last longer than one hour, so the job must use IAM user access keys', 'A role can be configured with a maximum session duration; the one-hour limit comes from role chaining.'],
    ],
    slot: 0,
    evidence: [
      'iam-switch-role|Using the credentials from one role to assume a different role is called role chaining. When you use role chaining, the session duration is limited to one hour, regardless of the maximum session duration setting configured for individual roles.',
    ],
  }),
  mc({
    id: 'embassy-row-012',
    building: 'embassy-row',
    bullets: ['1.1-K1', '1.1-S3'],
    d: 2,
    stem: 'A developer in account A gets an AccessDenied error when calling sts:AssumeRole for a role in account B. The trust policy of the role names account A as the principal, and the permissions policy of the role allows the needed Amazon S3 actions. The IAM user of the developer has an identity-based policy that allows only Amazon S3 actions. Which change fixes the problem with the LEAST privilege?',
    correct: ['Add a statement to the identity-based policy of the developer that allows sts:AssumeRole on the role ARN', 'Users in the trusted account must be granted permission to assume the role; the trust policy is only one half of the permissions.'],
    wrong: [
      ['Add s3:* with a Resource of * to the permissions policy of the role in account B', 'The call fails before any S3 action is attempted, so broader S3 permissions do not fix it and they widen access.'],
      ['Attach a service control policy to account A that allows sts:AssumeRole for all roles', 'SCPs do not grant permissions, and allowing all roles would be broader than the single role the developer needs.'],
      ['Replace the principal in the trust policy with the root user of account B so the role trusts its own account', 'The developer is in account A, so trusting only account B removes the access that the trust policy is meant to give.'],
    ],
    slot: 1,
    evidence: [
      'iam-cross-account-role|You must also give individual users in the trusted account permissions to switch to the role in the console, or assume the role programmatically.',
      'iam-roles|The trust policy is attached to the role in the trusting account, and is one-half of the permissions.',
    ],
  }),
  mc({
    id: 'embassy-row-013',
    building: 'embassy-row',
    bullets: ['1.1-S3', '1.1-S5'],
    d: 3,
    tags: ['trap:iam-roles-vs-resource-policies'],
    stem: 'An Amazon EC2 application in account A copies objects from an Amazon S3 bucket in account B into an S3 bucket in account A during the same job. The application must keep using the permissions of its own instance role in account A for the destination bucket. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Add a bucket policy to the source bucket that names the instance role of account A, and allow s3:GetObject in the identity-based policy of the role', 'With a resource-based policy the principal keeps its permissions in its own account, which suits copying information to or from the shared resource.'],
    wrong: [
      ['Create a role in account B with s3:GetObject on the source bucket and have the application assume that role for the whole copy job, including the writes', 'After the application assumes the role it gives up its account A permissions, so it could no longer write to the destination bucket.'],
      ['Create an IAM user in account B, store its access keys on the instance, and allow the user to read the source bucket', 'It adds long-term access keys to manage on the instance, which is more overhead than using the instance role.'],
      ['Make the source bucket public and read it with unsigned requests from the application', 'Every object would be exposed to anyone, so it is not a secure way to share data between two accounts.'],
    ],
    slot: 2,
    evidence: [
      'iam-cross-account|When an account accesses a resource through another account using a resource-based policy, the principal still works in the trusted account and does not have to give up their permissions to receive the role permissions.',
      'iam-cross-account|This is useful for tasks such as copying information to or from the shared resource in the other account.',
      'iam-cross-account-eval|You must also attach an identity-based policy to the identity that acts as the principal in the request.',
    ],
  }),
  mc({
    id: 'embassy-row-014',
    building: 'embassy-row',
    bullets: ['1.1-S3', '1.1-S5'],
    d: 3,
    tags: ['placement-eligible', 'trap:iam-roles-vs-resource-policies'],
    stem: 'A company serves a static website from an Amazon S3 bucket behind Amazon CloudFront in a production account. A CI/CD pipeline in a separate tooling account must write new site files to the bucket and perform several other actions in the production account on each release. The company wants to manage the permissions of the pipeline in one place in the production account and forbids long-term access keys. Which solution meets these requirements MOST securely?',
    correct: ['Create a role in the production account that trusts the pipeline role in the tooling account and grants all the release permissions', 'A cross-account role centralizes permission management across multiple services and gives the pipeline temporary credentials instead of access keys.'],
    wrong: [
      ['Add a bucket policy that names the pipeline role in the tooling account and allows s3:PutObject on the site bucket for each release of the website', 'A bucket policy covers only the bucket, so it cannot centralize the other production-account permissions that the pipeline needs.'],
      ['Create an IAM user in the production account for the pipeline and keep its access keys in the pipeline secrets', 'Access keys are long-term credentials, which the company forbids, and the user adds a credential to rotate.'],
      ['Attach a service control policy to the tooling account that allows writes to the production bucket', 'SCPs do not grant permissions and cannot give access to resources in another account.'],
    ],
    slot: 3,
    evidence: [
      'iam-cross-account|Not all AWS services support resource-based policies. For these services, you can use cross-account IAM roles to centralize permission management when providing cross-account access to multiple services.',
      'iam-temp-creds|You do not have to distribute or embed long-term AWS security credentials with an application.',
    ],
  }),
  mc({
    id: 'embassy-row-015',
    building: 'embassy-row',
    bullets: ['1.1-S4'],
    d: 1,
    stem: 'A company is adopting a multi-account strategy and has no landing zone yet. Which solution is the FASTEST way to set up a governed multi-account environment that follows prescriptive best practices?',
    correct: ['Set up a landing zone by using AWS Control Tower', 'Control Tower sets up and governs a multi-account environment that follows prescriptive best practices.'],
    wrong: [
      ['Create each account by hand in AWS Organizations and configure the baseline of every account separately', 'It can work, but it is slow and has no built-in best-practice setup or ongoing governance controls.'],
      ['Share a baseline VPC with every account by using AWS Resource Access Manager and tag the accounts', 'AWS RAM shares resources; it does not create accounts, apply best practices, or govern them.'],
      ['Enable AWS IAM Identity Center and assign permission sets to the accounts that already exist', 'IAM Identity Center manages workforce access to accounts but does not set up a governed multi-account environment.'],
    ],
    slot: 0,
    evidence: [
      'control-tower|AWS Control Tower offers a straightforward way to set up and govern an AWS multi-account environment, following prescriptive best practices.',
    ],
  }),
  mc({
    id: 'embassy-row-016',
    building: 'embassy-row',
    bullets: ['1.1-K1', '1.1-S4'],
    d: 2,
    tags: ['trap:scp-boundary-identity'],
    stem: 'A company has 30 accounts in an organization. No account in the Workloads OU may launch resources in Regions other than two approved Regions, and account administrators must not be able to remove the restriction. Which solution meets these requirements?',
    correct: ['Attach a service control policy that denies actions outside the approved Regions to the Workloads OU', 'An SCP sets a guardrail for the users and roles in the accounts under the OU, even if an administrator grants broader permissions.'],
    wrong: [
      ['Attach an IAM policy that denies actions in the other Regions to every user and role in each of the accounts of the Workloads OU', 'Account administrators could detach or edit those policies, and every account would have to be maintained separately.'],
      ['Set a permissions boundary that denies the other Regions on every IAM role in each account', 'A boundary is set per user or role, so it must be maintained for every entity and is not one central control.'],
      ['Create an AWS Config rule in each account that flags resources found in the other Regions', 'A Config rule detects noncompliant resources after they exist; it does not stop the launches.'],
    ],
    slot: 1,
    evidence: [
      'sec-account-separation|For example, you can apply an SCP that restricts users from launching resources in Regions that you have not explicitly allowed.',
      "orgs-scps|a user or role in the affected account can't use that permission, even if the account administrator attaches the AdministratorAccess IAM policy with */* permissions to the user.",
    ],
  }),
  mc({
    id: 'embassy-row-017',
    building: 'embassy-row',
    bullets: ['1.1-S4'],
    d: 2,
    stem: 'A security engineer attaches a service control policy that denies launching Amazon EC2 instances to the organization root. Launches fail in the member accounts, but an administrator in the management account can still launch instances. Which statement BEST explains this behavior?',
    correct: ['SCPs affect only member accounts and have no effect on users or roles in the management account', 'AWS states that SCPs affect only the member accounts in the organization.'],
    wrong: [
      ['The management account always has a FullAWSAccess SCP that overrides any Deny attached to the root', 'FullAWSAccess only allows actions and an allow does not override a deny; the real reason is that SCPs skip the management account.'],
      ['SCPs take effect in the management account only after the administrator enables a permissions boundary there', 'SCPs do not depend on permissions boundaries, and they never apply to the management account.'],
      ['SCPs apply only to IAM roles, so IAM users in any account can still launch instances', 'SCPs affect IAM users and roles in member accounts, so the users in member accounts are blocked as well.'],
    ],
    slot: 2,
    evidence: [
      'orgs-scps|SCPs affect only member accounts in the organization. They have no effect on users or roles in the management account.',
    ],
  }),
  mc({
    id: 'embassy-row-018',
    building: 'embassy-row',
    bullets: ['1.1-S4'],
    d: 3,
    stem: 'In an organization, the root and Account B each have an SCP that explicitly allows Amazon DynamoDB actions. The Production OU, which contains Account B, has an SCP that explicitly denies DynamoDB actions. An administrator in Account B attaches an IAM policy that allows dynamodb:* to a role. Which outcome BEST describes a DynamoDB request made by that role?',
    correct: ['The request is denied, because a deny in an SCP at any level on the path to the account blocks the action', 'A deny attached at the OU is evaluated for all member accounts under it, regardless of the allows at other levels.'],
    wrong: [
      ['The request is allowed, because the SCP that is attached directly to Account B takes precedence over the SCP of the Production OU', 'No level takes precedence over a deny; a deny at any level on the path blocks the permission.'],
      ['The request is allowed, because the IAM policy in Account B grants the permission to the role', 'An IAM policy cannot grant more than the SCPs allow, and the deny in the SCP of the OU blocks the action.'],
      ['The request is allowed, because the SCP at the root explicitly allows DynamoDB for every account', 'An allow at the root is only one level of the path and does not override a deny at the OU.'],
    ],
    slot: 3,
    evidence: [
      'orgs-scp-eval|For a permission to be denied for a specific account, any SCP from the root through each OU in the direct path to the account (including the target account itself) can deny that permission.',
      'orgs-scp-eval|As a result, both Account A and Account B will be denied access to the service as a deny policy attached to any level in the organization is evaluated for all the OUs and member accounts underneath it.',
    ],
  }),
  mc({
    id: 'embassy-row-019',
    building: 'embassy-row',
    bullets: ['1.1-S4'],
    d: 3,
    stem: 'An administrator detaches the FullAWSAccess SCP from the organization root and attaches a new SCP whose only statement denies organizations:LeaveOrganization. Afterward, users and roles in every member account lose access to all services. Which change restores access while keeping the restriction with the LEAST amount of change?',
    correct: ['Add an Allow statement for the needed services to the new SCP so that an allow exists at the root', 'A permission needs an explicit allow at every level, and a deny-only SCP at the root blocks every service.'],
    wrong: [
      ['Attach the AdministratorAccess IAM policy to every user and role in the member accounts', 'IAM policies cannot grant what the SCPs do not allow, and the change would be repeated in every account.'],
      ['Move all member accounts into a new OU directly under the root', 'The new OU still sits under a root that has no allowing SCP, so every action stays blocked.'],
      ['Attach the new deny SCP to each OU instead of the root', 'Without an allow at the root and at each level, access stays blocked, and there are more attachments to maintain.'],
    ],
    slot: 0,
    evidence: [
      'orgs-scp-eval|A Deny-only SCP at the root therefore blocks every service unless an explicit Allow covers it.',
      'orgs-scp-eval|If this policy is removed and not replaced at any level of the organization, all OUs and accounts under that level would be blocked from taking any actions.',
    ],
  }),
  mr({
    id: 'embassy-row-020',
    building: 'embassy-row',
    bullets: ['1.1-S4'],
    d: 2,
    stem: 'A security team will roll out a restrictive SCP in a production organization with many accounts. The team wants the LOWEST risk of locking users out of key services. Which TWO actions should the team take? (Choose two.)',
    correct: [
      ['Create a test OU, move accounts into it a few at a time, and attach the SCP to that OU', 'Testing on a small number of accounts reveals problems before the SCP affects every account, which AWS recommends over attaching it to the root.'],
      ['Review service last accessed data to find which services the accounts actually use', 'It shows which allowed services are used or unused, so the SCP can be refined without breaking active workloads.'],
    ],
    wrong: [
      ['Attach the SCP to the organization root and fix problems as users report them', 'It applies the policy to every account without testing, which risks locking users out.'],
      ['Attach the SCP to the management account first to test its effect', 'SCPs have no effect on users or roles in the management account, so the test would show nothing.'],
      ['Detach FullAWSAccess from the root before testing so that only the new SCP applies', 'Removing the allow policy blocks all actions in every account unless another policy allows them.'],
    ],
    slots: [2, 4],
    evidence: [
      "orgs-scps|Instead, create an OU that you can move your accounts into one at a time, or at least in small numbers, to ensure that you don't inadvertently lock users out of key services.",
      'orgs-scps|You can use this information to identify unused permissions so that you can refine your SCPs to better adhere to the principle of least privilege.',
      'orgs-scps|They have no effect on users or roles in the management account.',
    ],
  }),
  mr({
    id: 'embassy-row-021',
    building: 'embassy-row',
    bullets: ['1.1-S4'],
    d: 2,
    tags: ['trap:scp-boundary-identity'],
    stem: 'An IAM user in a member account of an organization must be able to launch Amazon EC2 instances. The organization uses SCPs, and no permissions boundary is attached to the user. Which TWO conditions must be true for the request to be allowed? (Choose two.)',
    correct: [
      ['SCPs that allow the action are in effect at the root, at each OU on the path, and at the account', 'For a permission to be allowed there must be an explicit Allow at every level from the root through the account.'],
      ['An identity-based policy of the user or of a group of the user allows the action', 'SCPs grant nothing, so the user also needs an IAM permission policy that allows the action.'],
    ],
    wrong: [
      ['A permissions boundary that allows the action is attached to the user', 'A permissions boundary only limits permissions and is not required; none is attached in this scenario.'],
      ['The member account is registered as a delegated administrator for AWS Organizations', 'Delegated administration is unrelated to whether the user is allowed to launch instances.'],
      ['AWS Control Tower manages the account and has enabled a control that allows the action', 'Control Tower is not required for the user to launch instances, and controls help govern accounts rather than grant permissions.'],
    ],
    slots: [0, 3],
    evidence: [
      'orgs-scps|A user without any IAM permission policies has no access, even if the applicable SCPs allow all services and all actions.',
      'orgs-scp-eval|For a permission to be allowed for a specific account, there must be an explicit Allow statement at every level from the root through each OU in the direct path to the account (including the target account itself).',
    ],
  }),
  mc({
    id: 'embassy-row-022',
    building: 'embassy-row',
    bullets: ['1.1-S4'],
    d: 2,
    tags: ['trap:scp-boundary-identity'],
    stem: 'A company lets teams administer their own accounts in a Sandbox OU. Security requires that no IAM user or role in those accounts can use services outside an approved list, even if administrators grant themselves full access. The company wants to manage this restriction in one place. Which solution meets these requirements?',
    correct: ['Attach an SCP that allows only the approved services to the Sandbox OU and replace FullAWSAccess there', 'SCPs set the maximum permissions for every user and role in the OU, and an allow list SCP can replace FullAWSAccess.'],
    wrong: [
      ['Attach the approved-services policy to every IAM user and role in each Sandbox account as a permissions boundary', 'A boundary is set per entity in each account, so it is not one central control for the whole OU.'],
      ['Attach an identity-based policy that allows only the approved services to every IAM group in the accounts', 'Identity-based policies grant permissions rather than set a limit, so administrators could still attach broader policies.'],
      ['Add a bucket policy and a key policy to every shared resource that lists the approved services', 'Resource-based policies say who may access a resource and exist only on resources that support them; they do not limit which services accounts use.'],
    ],
    slot: 1,
    evidence: [
      'orgs-scps|An SCP defines a permission guardrail, or sets limits, on the actions that the IAM users and IAM roles in your organization can perform.',
      'orgs-scp-eval|You can replace FullAWSAccess with a policy allowing only a set of services so that new AWS services are not allowed unless they are explicitly allowed by updating SCPs.',
      'iam-boundaries|A permissions boundary is an advanced feature for using a managed policy to set the maximum permissions that an identity-based policy can grant to an IAM entity.',
    ],
  }),
  mr({
    id: 'embassy-row-023',
    building: 'embassy-row',
    bullets: ['1.1-S4'],
    d: 2,
    stem: 'A company with many accounts in an organization uses AWS Control Tower. Teams must be able to request new accounts that start from a standard, pre-approved configuration, and central administrators must be able to see where resources drift from policy. Which TWO capabilities meet these requirements? (Choose two.)',
    correct: [
      ['Account Factory configurable account templates', 'Account Factory lets teams provision new accounts quickly from configurable templates with pre-approved account configurations.'],
      ['Detective controls enabled on the organizational units', 'Detective controls provide continuous detection of policy non-conformance, which the dashboard shows by account and OU.'],
    ],
    wrong: [
      ['A service control policy that grants each team permission to create accounts', 'SCPs do not grant permissions, so they cannot give teams the ability to create accounts.'],
      ['Preventive controls enabled on the organizational units', 'A preventive control disallows actions that lead to policy violations, but it does not help teams request accounts or show administrators where resources drift from policy.'],
      ['An AWS RAM resource share that gives each team the permissions of the management account', 'AWS RAM shares resources with other accounts; it does not provision accounts or detect drift.'],
    ],
    slots: [1, 3],
    evidence: [
      'control-tower|AWS Control Tower enables end users on your distributed teams to provision new AWS accounts quickly, by means of configurable account templates in Account Factory.',
      'control-tower|Use the dashboard to see provisioned accounts across your enterprise, controls enabled for policy enforcement, controls enabled for continuous detection of policy non-conformance, and noncompliant resources organized by accounts and OUs.',
      'control-tower-controls|AWS Control Tower implements preventive, detective, and proactive controls that help you govern your resources and monitor compliance across groups of AWS accounts.',
    ],
  }),
  mc({
    id: 'embassy-row-024',
    building: 'embassy-row',
    bullets: ['1.1-S4'],
    d: 2,
    tags: ['placement-eligible', 'trap:scp-boundary-identity'],
    stem: 'A company hosts public websites from Amazon S3 buckets behind Amazon CloudFront distributions in accounts under a Production OU. Security requires that no one in those accounts, including account administrators and the root user, can delete the distributions. Which solution meets this requirement with the LEAST operational overhead?',
    correct: ['Attach an SCP that denies cloudfront:DeleteDistribution to the Production OU', 'SCPs restrict all users and roles in the attached accounts, including the member account root user, and one attachment covers every account under the OU.'],
    wrong: [
      ['Attach an IAM policy that denies cloudfront:DeleteDistribution to each administrator in each account', 'The policy would have to be created and maintained separately in every account, and it does not restrict the account root user.'],
      ['Set a permissions boundary that denies cloudfront:DeleteDistribution on each IAM role in each account', 'A boundary is attached per IAM role, so every account needs separate maintenance and the root user is not covered.'],
      ['Create an AWS Config rule that flags an account when a distribution has been deleted', 'A Config rule reports a problem after the deletion happened; it does not prevent the deletion.'],
    ],
    slot: 2,
    evidence: [
      'orgs-scps|SCPs affect all users and roles in attached accounts, including the root user.',
      "orgs-scps|An SCP restricts permissions for IAM users and roles in member accounts, including the member account's root user.",
    ],
  }),
  mc({
    id: 'embassy-row-025',
    building: 'embassy-row',
    bullets: ['1.1-S4'],
    d: 2,
    tags: ['placement-eligible'],
    stem: 'A company serves websites through Amazon CloudFront from private Amazon S3 buckets in accounts under a Websites OU, and it uses AWS Control Tower. The security team must be able to determine whether any account in the OU allows public read access to its S3 buckets, without writing custom code. Which solution meets this requirement with the LEAST effort?',
    correct: ['Enable the detective control that detects whether public read access to S3 buckets is allowed on the Websites OU', 'A control applies to the whole OU, and a detective control determines whether public read access to S3 buckets would be permitted in any account under it.'],
    wrong: [
      ['Write an AWS Lambda function in each account that scans the bucket policies every hour and emails the findings to the security team', 'It needs custom code in every account, which the team wants to avoid.'],
      ['Attach an SCP to the management account that allows only private buckets in the Websites OU', 'SCPs have no effect on the management account, and an SCP limits permissions rather than reporting on existing buckets.'],
      ['Review the bucket permissions of every account in the console each week and record the results', 'It is a manual process in each account, which is more effort than enabling one control on the OU.'],
    ],
    slot: 3,
    evidence: [
      'control-tower-controls|if you enable the detective control Detect Whether Public Read Access to Amazon S3 Buckets is Allowed on an OU, you can determine whether an entity (such as a user) would be permitted to have read access over the internet to any Amazon S3 buckets, for any accounts under that OU.',
      'control-tower-controls|A control applies to an entire organizational unit (OU), and every AWS account within the OU is affected by the control.',
    ],
  }),
  mc({
    id: 'embassy-row-026',
    building: 'embassy-row',
    bullets: ['1.1-S5'],
    d: 1,
    stem: 'A company wants to state, on an Amazon SQS queue itself, which principals from other AWS accounts may send messages to the queue. Which type of policy BEST fits this requirement?',
    correct: ['A resource-based policy attached to the queue', 'A resource-based policy is attached to a resource and specifies which principal can access that resource.'],
    wrong: [
      ['An identity-based policy attached to an IAM user in each account', 'Identity-based policies state what an identity can do and are attached to users, groups or roles, not to the queue.'],
      ['A permissions boundary attached to the queue', 'A permissions boundary applies to IAM users and roles and only limits their maximum permissions.'],
      ['A service control policy attached to the organization root', 'SCPs set maximum permissions for users and roles in an organization and are not attached to a queue.'],
    ],
    slot: 0,
    evidence: [
      'iam-identity-vs-resource|Resource-based policies are attached to a resource.',
      'iam-identity-vs-resource|you can attach resource-based policies to Amazon S3 buckets, Amazon SQS queues, VPC endpoints, AWS Key Management Service encryption keys, Amazon DynamoDB tables and streams',
      'iam-cross-account|Unlike an identity-based policy for a role, a resource-based policy specifies who (which principal) can access that resource.',
    ],
  }),
  mc({
    id: 'embassy-row-027',
    building: 'embassy-row',
    bullets: ['1.1-S5'],
    d: 1,
    stem: 'An administrator adds a Principal element for another AWS account to a policy that is attached to an IAM role, hoping to let that account read an Amazon S3 bucket. IAM rejects the policy. Which statement BEST explains why and what to do instead?',
    correct: ['The Principal element is not allowed in identity-based policies, so attach a bucket policy that names the other account', 'Only resource-based policies use the Principal element, so the other account must be named in the bucket policy.'],
    wrong: [
      ['The policy exceeded the size limit of IAM, so split the statement into two smaller policies on the role', 'Policy size is not the reason; an identity-based policy cannot use the Principal element at all.'],
      ['The Principal element works only with IAM user groups, so add the other account to a group in the same account', 'A user group cannot be identified as a principal, because groups relate to permissions, not authentication.'],
      ['The role must be deleted first, so recreate it with the Principal element in its permissions policy', 'Recreating the role does not help, because the permissions policy of a role cannot contain a Principal element.'],
    ],
    slot: 1,
    evidence: [
      'iam-el-principal|You cannot use the Principal element in an identity-based policy.',
      'iam-el-principal|You must use the Principal element in resource-based policies.',
      'iam-el-principal|You cannot identify a user group as a principal in a policy',
    ],
  }),
  mc({
    id: 'embassy-row-028',
    building: 'embassy-row',
    bullets: ['1.1-S5'],
    d: 3,
    tags: ['placement-eligible'],
    stem: 'A company serves a static website from an Amazon S3 bucket through Amazon CloudFront. The bucket must stay private, and its objects use server-side encryption with AWS KMS keys (SSE-KMS). The distribution uses an origin access identity (OAI), and requests for the encrypted objects fail. Which solution meets these requirements with the LEAST change?',
    correct: ['Switch the origin to origin access control, update the bucket policy for the CloudFront service principal, and add a statement to the KMS key policy', 'OAC supports SSE-KMS where OAI does not, and the distribution needs permission to use the KMS key through the key policy.'],
    wrong: [
      ['Keep the OAI and add a statement to the KMS key policy that lets the OAI use the key', 'OAI does not support SSE-KMS or requires extra workarounds, so a key policy statement alone does not fix the failing requests.'],
      ['Re-encrypt the objects with SSE-S3 and make the bucket public so that CloudFront can read it', 'It abandons the SSE-KMS requirement and removes the requirement that the bucket stay private.'],
      ['Enable static website hosting on the bucket and point the origin at the website endpoint', 'A bucket configured as a website endpoint cannot use origin access control, so CloudFront could not read a private bucket.'],
    ],
    slot: 2,
    evidence: [
      'cf-oac|To give the CloudFront distribution permission to use the KMS key, add a statement to the KMS key policy.',
      "cf-oac|OAI doesn't support these features or it requires extra workarounds in those scenarios.",
      'cf-oac|We recommend that you use OAC instead because it supports the following features:',
    ],
  }),
  mc({
    id: 'embassy-row-029',
    building: 'embassy-row',
    bullets: ['1.1-S5'],
    d: 2,
    tags: ['placement-eligible'],
    stem: 'A company hosts a static website from an Amazon S3 bucket that is configured as a website endpoint, and it fronts the bucket with Amazon CloudFront. The company now wants the bucket to be private so that only CloudFront can read the objects. Which solution meets this requirement?',
    correct: ['Use the regular S3 bucket endpoint as the origin and attach an origin access control with a bucket policy for CloudFront', 'OAC needs a regular S3 bucket origin, and the bucket policy lets the CloudFront service principal read the objects while the bucket stays private.'],
    wrong: [
      ['Keep the website endpoint as a custom origin and attach an origin access control to the origin', 'A bucket configured as a website endpoint must be set up as a custom origin, so it cannot use origin access control.'],
      ['Keep the website endpoint and replace the bucket policy with one that names an origin access identity', 'A custom origin for a website endpoint is not an Amazon S3 origin, so an origin access identity does not send authenticated requests to it.'],
      ['Keep the bucket public and rely on the CloudFront domain name being hard to guess', 'The bucket would stay readable by anyone who finds it, so it is not private.'],
    ],
    slot: 3,
    evidence: [
      'cf-oac|If your origin is an Amazon S3 bucket configured as a website endpoint, you must set it up with CloudFront as a custom origin.',
      'cf-oac|This origin must be a regular S3 bucket, not a bucket configured as a website endpoint.',
      'cf-oac|Use an S3 bucket policy to allow the CloudFront service principal (cloudfront.amazonaws.com) to access the bucket.',
    ],
  }),
  mr({
    id: 'embassy-row-030',
    building: 'embassy-row',
    bullets: ['1.1-S5'],
    d: 3,
    tags: ['placement-eligible'],
    stem: 'A company lets customers upload files with PUT requests through an Amazon CloudFront distribution to a private Amazon S3 bucket. The company wants to use origin access control (OAC), and the traffic between CloudFront and Amazon S3 must always use HTTPS. Which THREE actions meet these requirements? (Choose three.)',
    correct: [
      ['Choose the Sign requests setting on the origin access control', 'Communication between CloudFront and Amazon S3 is always through HTTPS only when the OAC is set to always sign requests.'],
      ['Add a bucket policy statement that lets the CloudFront service principal use s3:GetObject and s3:PutObject for the distribution', 'The bucket policy for OAC can allow read and write access for the distribution, so uploads work while the bucket stays private.'],
      ['Keep S3 Object Ownership set to Bucket owner enforced', 'OAC with an Amazon S3 bucket origin requires the Bucket owner enforced setting for Object Ownership.'],
    ],
    wrong: [
      ['Choose the Do not sign requests setting so that CloudFront forwards the viewer request unchanged', 'CloudFront then uses the protocol from the viewer protocol policy instead of always using HTTPS, and the requests are not signed by the OAC.'],
      ['Enable static website hosting on the bucket and use the website endpoint as the origin', 'A bucket configured as a website endpoint cannot use origin access control.'],
      ['Attach a service control policy that allows CloudFront to write to the bucket', 'SCPs do not grant permissions to anything, so they cannot let CloudFront write to the bucket.'],
    ],
    slots: [0, 2, 5],
    evidence: [
      'cf-oac|When you use OAC to secure your Amazon S3 origin, communication between CloudFront and Amazon S3 is always through HTTPS, but only when you choose to always sign requests.',
      'cf-oac|Example S3 bucket policy that allows read and write access for a CloudFront distribution with OAC enabled',
      'cf-oac|When you use CloudFront OAC with Amazon S3 bucket origins, you must set Amazon S3 Object Ownership to Bucket owner enforced, the default for new Amazon S3 buckets.',
    ],
  }),
  mc({
    id: 'embassy-row-031',
    building: 'embassy-row',
    bullets: ['1.1-S5'],
    d: 3,
    tags: ['placement-eligible'],
    stem: 'A company serves a static website from a private Amazon S3 bucket through Amazon CloudFront. The distribution uses an origin access identity (OAI), and the bucket policy allows only that OAI. The company wants to move to origin access control without making the bucket public and without interrupting visitors, and visitors keep using the existing distribution domain name. Which approach meets these requirements with the LEAST change to the existing setup?',
    correct: ['Add a bucket policy statement for the CloudFront service principal next to the OAI statement, then switch the distribution to origin access control', 'The bucket policy first allows both OAI and OAC, and the distribution is then updated to use OAC, so reads keep working throughout.'],
    wrong: [
      ['Remove the OAI statement from the bucket policy, then add the statement for the service principal and update the distribution', 'Visitors would be denied between the removal and the update, because neither identity would have access during that time.'],
      ['Make the bucket public during the change and restore the private setting afterward', 'It exposes the objects to everyone during the change, which breaks the requirement to keep the bucket private.'],
      ['Create a second distribution with origin access control and delete the first distribution after the switch', 'It builds a second distribution with a different domain name and then needs a switch, which is more change than updating the existing distribution to use OAC.'],
    ],
    slot: 0,
    evidence: [
      "cf-oac|After you update the S3 origin's bucket policy to allow access to both OAI and OAC, you can update the distribution configuration to use OAC instead of OAI.",
      'cf-oac|If you\'re already using OAI and want to migrate, see Migrating from origin access identity (OAI) to origin access control (OAC).',
    ],
  }),
  mc({
    id: 'embassy-row-032',
    building: 'embassy-row',
    bullets: ['1.1-K1'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A company needs a single record of the API activity in every member account of its organization, stored centrally, that member accounts cannot turn off or modify. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Create an organization trail in AWS CloudTrail from the management account', 'An organization trail logs events for the management account and all member accounts, and the resulting log cannot be turned off or modified by member accounts.'],
    wrong: [
      ['Ask each account owner to create a trail that delivers events to a central Amazon S3 bucket', 'Each owner could stop or change a trail in their own account, and the setup is repeated in every account.'],
      ['Use the CloudTrail Event history of each account and export the results every month', 'Event history is kept per account and covers a limited period, and the export is manual work.'],
      ['Create an AWS Config aggregator in the management account for all member accounts', 'AWS Config records the configuration of resources, not a log of the API calls that were made.'],
    ],
    slot: 1,
    evidence: [
      'cloudtrail-org-trail|Organization trails log events for the management account and all member accounts in the organization.',
      'orgs-intro|You can activate AWS CloudTrail across accounts, which creates a log of all activity in your cloud environment that cannot be turned off or modified by member accounts.',
    ],
  }),
  mc({
    id: 'embassy-row-033',
    building: 'embassy-row',
    bullets: ['1.1-S3'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'Security requires that only users who signed in with multi-factor authentication (MFA) can assume a sensitive production role from another account. The company wants to enforce this on the role itself. Which solution meets this requirement?',
    correct: ['Add MFA protection to the role so that only users who sign in with an MFA device can assume it', 'MFA protection configured on the role requires an MFA sign-in before the role can be assumed.'],
    wrong: [
      ['Require MFA only when users sign in to the console of the development account', 'It does not enforce MFA on the role itself, so a session created without MFA could still assume the role.'],
      ['Attach a service control policy that grants sts:AssumeRole only to users who used MFA', 'SCPs do not grant permissions, so they cannot grant sts:AssumeRole to anyone.'],
      ['Add the serial number of the MFA device to the permissions policy of the role as a resource', 'The permissions policy defines what the role can do; it does not control who can assume the role.'],
    ],
    slot: 2,
    evidence: [
      'iam-account-switch|You can add multi-factor authentication (MFA) protection to the role so that only users who sign in with an MFA device can assume the role.',
    ],
  }),
  mc({
    id: 'embassy-row-034',
    building: 'embassy-row',
    bullets: ['1.1-S4'],
    d: 1,
    tags: ['mock-reserve'],
    stem: 'The organization of a company was created with only the consolidated billing features. A security engineer cannot use service control policies. Which action makes SCPs available with the LEAST effort?',
    correct: ['Enable all features in the organization', 'SCPs are available only in an organization that has all features enabled.'],
    wrong: [
      ['Attach the FullAWSAccess SCP to the organization root', 'FullAWSAccess is itself an SCP, so it cannot be attached while SCPs are not available in the organization.'],
      ['Create a permissions boundary for the IAM users in each member account', 'Permissions boundaries are an IAM feature for single users and roles and do not replace SCPs.'],
      ['Register a delegated administrator account for the organization', 'A delegated administrator manages supported services and does not turn on SCPs.'],
    ],
    slot: 3,
    evidence: [
      "orgs-scps|SCPs aren't available if your organization has enabled only the consolidated billing features.",
      'orgs-scps|SCPs are available only in an organization that has all features enabled.',
    ],
  }),
  mr({
    id: 'embassy-row-035',
    building: 'embassy-row',
    bullets: ['1.1-S5'],
    d: 3,
    tags: ['mock-reserve'],
    stem: 'An AWS Lambda function in a shared-services account must be invokable by IAM roles in every account of the company organization, with the LEAST maintenance of the function policy. Which TWO actions meet these requirements? (Choose two.)',
    correct: [
      ['Add a resource-based policy to the function that allows lambda:InvokeFunction and uses the aws:PrincipalOrgID condition key', 'A resource-based policy can grant organizations access to a function, and the condition key keeps the accounts current without manual updates.'],
      ['Allow lambda:InvokeFunction on the function ARN in an identity-based policy of the roles in the invoking accounts', 'In cross-account access the principal also needs an Allow in its identity-based policy.'],
    ],
    wrong: [
      ['Attach a service control policy to the organization root that grants lambda:InvokeFunction on the function', 'SCPs do not grant permissions, so they cannot allow the invocation.'],
      ['List the account ID of every member account as a principal in the resource-based policy of the function', 'It requires editing the policy whenever an account is added or removed, which adds the maintenance the company wants to avoid.'],
      ['Create a copy of the function in every account of the organization', 'It duplicates the function instead of sharing it and multiplies the deployments to maintain.'],
    ],
    slots: [2, 4],
    evidence: [
      'lambda-resource-policy|With resource-based permissions policies, you can grant other AWS accounts, users, organizations, and AWS services access to your Lambda functions.',
      'iam-cross-account|In cross account access, a principal needs an Allow in the identity policy and the resource-based policy.',
      "iam-global-condition-keys|When you add and remove accounts, policies that include the aws:PrincipalOrgID key automatically include the correct accounts and don't require manual updating.",
    ],
  }),
];

export default questions;
