import type { Question } from '../../../src/content/types.ts';
import { mc, mr } from '../helpers.ts';

const questions: Question[] = [
  mc({
    id: 'federation-bridge-001',
    building: 'federation-bridge',
    bullets: ['1.1-K2'],
    d: 1,
    stem: 'A company uses AWS Organizations with 12 AWS accounts. The company has no corporate identity provider or directory, and about 40 employees need access to the accounts they are assigned. The company wants to create and manage the employees in one place and let them sign in to all assigned accounts with the LEAST administrative effort. Which solution meets these requirements?',
    correct: ['Enable AWS IAM Identity Center and create the employees in its built-in identity store', 'IAM Identity Center is recommended for centralized access management of human users across accounts, and users can be created and managed directly in it.'],
    wrong: [
      ['Create an IAM SAML identity provider and the matching IAM roles separately in each of the 12 accounts', 'A SAML identity provider needs an external identity provider that the company does not have, and the setup would be repeated in all 12 accounts.'],
      ['Create an IAM user for every employee in each account and require a password change at first sign-in', 'It creates many identities with long-term credentials in 12 places instead of managing the employees in one place.'],
      ['Create an Amazon Cognito user pool and have employees sign in to the AWS Management Console through it', 'Amazon Cognito authenticates the users of mobile and web apps and is not the way to manage workforce access to AWS accounts.'],
    ],
    slot: 0,
    evidence: [
      'iam-idp-federation|For centralized access management of human users, we recommend that you use IAM Identity Center to manage access to your accounts and permissions within those accounts.',
      'sso-what-is|You can connect your existing identity provider and synchronize users and groups from your directory, or create and manage your users directly in IAM Identity Center.',
      'iam-idp-federation|Amazon Cognito is designed for developers who want to authenticate and authorize users in their mobile and web apps.',
    ],
  }),
  mc({
    id: 'federation-bridge-002',
    building: 'federation-bridge',
    bullets: ['1.1-S6'],
    d: 1,
    stem: 'A company keeps all employee accounts in a corporate directory. Until now, the cloud team created a separate IAM user with a long-term password for each employee who needs AWS access. Which approach BEST follows AWS guidance for human users?',
    correct: ['Federate the corporate directory with AWS so that employees sign in with it and assume IAM roles', 'AWS recommends that human users use federation with an identity provider, which gives them temporary credentials instead of separate IAM users.'],
    wrong: [
      ['Keep the IAM users and require each employee to change the password every 90 days', 'Each employee would still hold a separate IAM user with long-term credentials, whereas federation with the directory is recommended.'],
      ['Create one shared IAM user for each department and give the credentials to the whole team', 'Shared credentials are still long-term IAM user credentials, and the corporate directory is not used at all.'],
      ['Create access keys for each employee and store the keys in the corporate directory', 'Access keys are long-term credentials that must be distributed and rotated, which federation avoids.'],
    ],
    slot: 1,
    evidence: [
      'iam-users|IAM best practices recommend that you require human users to use federation with an identity provider to access AWS using temporary credentials instead of using IAM users with long-term credentials.',
      'iam-idp-federation|This is useful if your organization already has its own identity system, such as a corporate user directory.',
    ],
  }),
  mc({
    id: 'federation-bridge-003',
    building: 'federation-bridge',
    bullets: ['1.1-K2'],
    d: 2,
    stem: 'A company is building a mobile app for the general public. Users sign in with their existing Google or Apple accounts, and the app must then upload photos directly to an Amazon S3 bucket by using temporary, limited-privilege AWS credentials. Which solution meets these requirements with the LEAST custom code?',
    correct: ['Use Amazon Cognito with an identity pool that exchanges the sign-in token for temporary AWS credentials', 'An identity pool exchanges a trusted token from a social provider for temporary, limited-privilege credentials that the app can use with Amazon S3.'],
    wrong: [
      ['Use AWS IAM Identity Center and add each app user to a group that has an Amazon S3 permission set', 'IAM Identity Center connects workforce users to AWS accounts and applications and is not meant for the public users of an app.'],
      ['Create an IAM user for each person who signs up and embed that user\'s access keys in the app', 'Long-term keys embedded in a public app are the opposite of temporary credentials, and it creates one IAM user per customer.'],
      ['Create an IAM SAML identity provider and an IAM role that every app user assumes through a custom broker', 'It needs custom brokering code, whereas Amazon Cognito already exchanges social sign-in tokens for temporary credentials.'],
    ],
    slot: 2,
    evidence: [
      'cognito-what-is|An identity pool exchanges a trusted token (from a user pool, a social provider, or a SAML or OIDC provider) for temporary, limited-privilege AWS credentials so that your app can call services like Amazon S3 and Amazon DynamoDB on the user\'s behalf.',
      'iam-idp-federation|Amazon Cognito is designed for developers who want to authenticate and authorize users in their mobile and web apps.',
    ],
  }),
  mc({
    id: 'federation-bridge-004',
    building: 'federation-bridge',
    bullets: ['1.1-K2'],
    d: 2,
    stem: 'A company set up SAML 2.0 federation in a single AWS account. Federated employees authenticate successfully with the identity provider but receive an error when they try to assume the IAM role. The permissions policy of the role is correct, but its trust policy names only the account root as the trusted principal. What is the SIMPLEST fix?',
    correct: ['Change the trust policy so that it names the IAM SAML provider as the Principal', 'The trust policy of a role for SAML federation specifies the SAML provider as the Principal, which lets the federated users assume the role.'],
    wrong: [
      ['Add sts:AssumeRole to the permissions policy of the role for the federated employees', 'The permissions policy defines what users may do once they have assumed the role, not who is allowed to assume it.'],
      ['Create an IAM user for each federated employee and add the users to the trust policy', 'It brings back an IAM user for everyone, which federation with the identity provider is meant to avoid.'],
      ['Create access keys for the role and give the keys to the identity provider administrator', 'A role has no long-term credentials; assuming it provides temporary security credentials for the role session.'],
    ],
    slot: 3,
    evidence: [
      'iam-saml|When you create the trust policy for the role, you specify the SAML provider that you created earlier as the Principal.',
      'iam-saml|The roles that you create in IAM define what SAML federated principals from your organization are allowed to do in AWS.',
      'iam-roles|Instead, when you assume a role, it provides you with temporary security credentials for your role session.',
    ],
  }),
  mc({
    id: 'federation-bridge-005',
    building: 'federation-bridge',
    bullets: ['1.1-S6'],
    d: 2,
    stem: 'A company runs its employee directory on Microsoft Active Directory in its data center. Compatible AWS applications must let employees sign in with their existing Active Directory credentials. The company does not need Active Directory features inside AWS and does not want to synchronize the directory or host federation infrastructure. Which solution is the SIMPLEST?',
    correct: ['Deploy AD Connector to proxy sign-in requests to the on-premises domain controllers', 'AD Connector forwards sign-in requests to the existing directory and removes the need for directory synchronization or federation infrastructure.'],
    wrong: [
      ['Deploy AWS Managed Microsoft AD and create a new set of user accounts in the cloud directory', 'It creates a second directory to maintain, and actual Active Directory features in AWS are not needed here.'],
      ['Deploy Simple AD and re-create the employee accounts as new identities in the cloud directory', 'Simple AD is a standalone directory in which identities are created again, so the existing accounts are not used.'],
      ['Deploy AD FS servers on Amazon EC2 and configure an IAM SAML provider for the applications', 'Hosting AD FS is the federation infrastructure that the company wants to avoid.'],
    ],
    slot: 0,
    evidence: [
      'ds-what-is|Use AD Connector if you only need to allow your on-premises users to log in to AWS applications and services with their Active Directory credentials.',
      'ds-what-is|AD Connector also eliminates the need of directory synchronization or the cost and complexity of hosting a federation infrastructure.',
      'ds-what-is|Simple AD is a standalone directory in the cloud, where you create and manage user identities and manage access to applications.',
    ],
  }),
  mc({
    id: 'federation-bridge-006',
    building: 'federation-bridge',
    bullets: ['1.1-S6'],
    d: 2,
    stem: 'A company is migrating Windows-based applications to AWS. The workload uses Amazon EC2 Windows instances and Amazon RDS for SQL Server, and the team needs a directory that runs actual Microsoft Active Directory in the AWS Cloud. Which directory option BEST meets these requirements?',
    correct: ['Create an AWS Managed Microsoft AD directory and join the Windows workloads to its domain', 'AWS Managed Microsoft AD provides actual Active Directory features and supports Windows workloads, including Amazon RDS for SQL Server.'],
    wrong: [
      ['Create an AD Connector directory that proxies requests to a self-managed Active Directory domain', 'AD Connector is a proxy service and is not compatible with RDS SQL Server.'],
      ['Create a Simple AD directory and join the Windows workloads to its domain in the cloud', 'Simple AD is not compatible with RDS SQL Server and offers only basic Active Directory features.'],
      ['Create an Amazon Cognito user pool and register the Windows instances as members of the pool', 'A user pool is a user directory for sign-in to apps and APIs and is not a Windows domain that servers can join.'],
    ],
    slot: 1,
    evidence: [
      'ds-what-is|AWS Managed Microsoft AD is your best choice if you need actual Active Directory features to support AWS applications or Windows workloads, including Amazon Relational Database Service for Microsoft SQL Server.',
      'ds-what-is|AD Connector is not compatible with RDS SQL Server.',
      'ds-what-is|Simple AD is not compatible with RDS SQL Server.',
    ],
  }),
  mc({
    id: 'federation-bridge-007',
    building: 'federation-bridge',
    bullets: ['1.1-K2'],
    d: 2,
    stem: 'A company federated its SAML 2.0 identity provider separately with each of 8 AWS accounts by creating an IAM SAML provider and roles in every account. Whenever the certificate of the identity provider changes, administrators must update all 8 accounts. The accounts belong to one AWS Organizations organization. Which change MOST reduces this effort?',
    correct: ['Connect the identity provider once to an IAM Identity Center organization instance and assign access to the accounts', 'With IAM Identity Center you federate once and have only one certificate to manage for a SAML 2.0 identity provider.'],
    wrong: [
      ['Create the IAM SAML provider in one account and reference it from the roles in the other 7 accounts', 'A SAML provider used in a role trust policy must be in the same account as the role, so this cannot work.'],
      ['Replace the SAML providers with an OIDC provider that is created separately in each of the 8 accounts', 'Each account would still have its own provider entity, so the federation setup stays repeated 8 times.'],
      ['Create an Amazon Cognito identity pool in each account and add the identity provider to every pool', 'It still repeats the federation setup in every account and targets app users rather than workforce access.'],
    ],
    slot: 2,
    evidence: [
      'sso-what-is|With IAM Identity Center, you only federate once, and you have only one certificate to manage when using a SAML 2.0 identity provider.',
      'iam-saml|SAML IDPs used in a role trust policy must be in the same account that the role is in.',
    ],
  }),
  mc({
    id: 'federation-bridge-008',
    building: 'federation-bridge',
    bullets: ['1.1-K2'],
    d: 1,
    stem: 'A company lets employees sign in to AWS through a SAML 2.0 identity provider. A developer asks what an application receives from AWS when its call to AssumeRoleWithSAML succeeds. Which statement BEST describes the response?',
    correct: ['A set of temporary security credentials for the role that was assumed', 'The API returns temporary security credentials that the application uses to make signed requests to AWS.'],
    wrong: [
      ['A new IAM user that AWS creates for the employee, together with a long-term password', 'Federation exists so that no IAM user has to be created for each person in the organization.'],
      ['A permanent pair of access keys that AWS stores for the employee in the account', 'The response carries temporary security credentials, not permanent access keys.'],
      ['A copy of the directory password of the employee that AWS keeps for later sign-ins', 'The identity provider authenticates the employee, and AWS receives a SAML assertion rather than the password.'],
    ],
    slot: 3,
    evidence: [
      'iam-saml|If the request is successful, the API returns a set of temporary security credentials, which your application can use to make signed requests to AWS.',
      'iam-saml|This feature enables federated single sign-on (SSO), so users can log into the AWS Management Console or call AWS API operations without you having to create an IAM user for everyone in your organization.',
    ],
  }),
  mc({
    id: 'federation-bridge-009',
    building: 'federation-bridge',
    bullets: ['1.1-S6'],
    d: 2,
    stem: 'Employees of a company are managed in a corporate directory, and each employee also has a separate IAM user. When people leave, the identity team removes them from the directory, and their IAM users stay active for weeks until the cloud team notices. Which solution MOST reduces this risk with the LEAST ongoing effort?',
    correct: ['Federate the directory with AWS and remove the IAM users so that access follows the directory accounts', 'Federated users sign in through the identity provider, so there are no separate long-term IAM users left to find and delete.'],
    wrong: [
      ['Write a nightly script that compares both lists and deletes the IAM users that are missing from the directory', 'It keeps long-term IAM users and adds custom code to maintain, whereas federation removes the need for separate users.'],
      ['Require MFA on every IAM user in addition to the password the employee already uses', 'MFA adds a second factor at sign-in, but the IAM user of a leaver would still exist and could still be used.'],
      ['Rotate the access keys of every IAM user in the account every 30 days with a scheduled job', 'Rotation does not deactivate users who left, and the IAM users stay separate from the directory.'],
    ],
    slot: 0,
    evidence: [
      'iam-users|IAM best practices recommend that you require human users to use federation with an identity provider to access AWS using temporary credentials instead of using IAM users with long-term credentials.',
      'iam-idp-federation|With an identity provider (IdP), you can manage your user identities outside of AWS and give these external user identities permissions to use AWS resources in your account.',
    ],
  }),
  mc({
    id: 'federation-bridge-010',
    building: 'federation-bridge',
    bullets: ['1.1-K2', '1.1-S6'],
    d: 3,
    stem: 'The employees of a company are spread across two Active Directory forests in its data centers. The company wants to give all employees single sign-on to the AWS accounts of its organization by using AWS IAM Identity Center with their existing Active Directory credentials, and wants to avoid copying users into a new identity store. Which solution meets these requirements?',
    correct: ['Create an AWS Managed Microsoft AD directory with trusts to both forests and connect it to IAM Identity Center', 'AWS Managed Microsoft AD supports multiple forests, and IAM Identity Center can work with users from any domain connected through an AD trust.'],
    wrong: [
      ['Create two AD Connector directories, one for each forest, and connect both of them to IAM Identity Center', 'Only one AD Connector directory or one AWS Managed Microsoft AD directory can be connected at a time.'],
      ['Create a Simple AD directory in the cloud and connect it to IAM Identity Center as the identity source', 'IAM Identity Center does not support Simple AD as a connected directory, and Simple AD does not support trust relationships.'],
      ['Create the users manually in the IAM Identity Center directory and ask each employee to set a new password', 'It copies the users into a new identity store and does not use the existing Active Directory credentials.'],
    ],
    slot: 1,
    evidence: [
      'sso-ad|You can connect only one AD Connector directory or one directory in AWS Managed Microsoft AD at a time.',
      'sso-ad|If you need to support multiple domains or forests, use AWS Managed Microsoft AD.',
      'sso-ad|When you use AWS Managed Microsoft AD as your identity source, IAM Identity Center can work with users from AWS Managed Microsoft AD or from any domain connected through an AD trust.',
      'ds-what-is|Simple AD does not support multi-factor authentication (MFA), trust relationships, DNS dynamic update, schema extensions, communication over LDAPS, PowerShell AD cmdlets, or FSMO role transfer.',
    ],
  }),
  mc({
    id: 'federation-bridge-011',
    building: 'federation-bridge',
    bullets: ['1.1-S6', '1.1-K2'],
    d: 3,
    stem: 'A company has one on-premises Active Directory domain and 15 AWS accounts in an AWS Organizations organization. Employees must reach the accounts with their Active Directory credentials by using AWS IAM Identity Center. The company does not want to run AD FS servers or create a new set of user accounts in AWS. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Create an AD Connector directory in the management account and use it as the identity source for IAM Identity Center', 'AD Connector reaches the existing directory without federation infrastructure, and it can serve as the Active Directory source for IAM Identity Center.'],
    wrong: [
      ['Deploy AD FS on Amazon EC2 and create an IAM SAML provider with matching roles in each of the 15 accounts', 'It hosts the federation infrastructure that the company wants to avoid and repeats the setup in all 15 accounts.'],
      ['Create an AWS Managed Microsoft AD directory and re-create all employee accounts inside the new directory', 'It requires re-creating every employee account in a new directory, and the existing Active Directory accounts are not used.'],
      ['Connect a Simple AD directory to IAM Identity Center and synchronize the employee accounts into it', 'IAM Identity Center does not support Simple AD as a connected directory.'],
    ],
    slot: 2,
    evidence: [
      'sso-ad|You must have an existing AD Connector or AWS Managed Microsoft AD directory set up in AWS Directory Service, and it must reside within your AWS Organizations management account.',
      'ds-what-is|AD Connector also eliminates the need of directory synchronization or the cost and complexity of hosting a federation infrastructure.',
      'sso-ad|IAM Identity Center does not support SAMBA 4-based Simple AD as a connected directory.',
    ],
  }),
  mc({
    id: 'federation-bridge-012',
    building: 'federation-bridge',
    bullets: ['1.1-K2'],
    d: 2,
    stem: 'A startup is developing a SaaS application for thousands of customers. Customers must be able to sign up and sign in with an email address or with their social media accounts, and the startup does not want to operate a user directory itself. Which service is the BEST fit?',
    correct: ['An Amazon Cognito user pool that stores and authenticates the customers', 'Amazon Cognito provides a scalable directory to manage and authenticate subscribers and works with social media identities.'],
    wrong: [
      ['AWS IAM Identity Center with its built-in identity store for the customers', 'IAM Identity Center connects workforce users to AWS and is not a directory for customers of an application.'],
      ['AWS Managed Microsoft AD with a separate domain trust for each customer', 'It provides actual Active Directory for AD-aware workloads, not a high-scale directory for subscribers.'],
      ['A separate IAM user for each customer, created automatically at sign-up', 'IAM users carry long-term credentials, and IAM is not designed as a customer directory.'],
    ],
    slot: 3,
    evidence: [
      'ds-what-is|Use Amazon Cognito if you develop high-scale SaaS applications and need a scalable directory to manage and authenticate your subscribers and that works with social media identities.',
      'sso-what-is|AWS IAM Identity Center is the AWS solution for connecting your workforce users to AWS managed applications',
    ],
  }),
  mr({
    id: 'federation-bridge-013',
    building: 'federation-bridge',
    bullets: ['1.1-K2'],
    d: 2,
    stem: 'A company uses AWS IAM Identity Center with 30 member accounts in AWS Organizations. The company wants its Finance group to have the same job-function permissions in every account where the group works, and wants to change those permissions in one place later, with the LEAST effort. Which TWO actions meet these requirements? (Choose two.)',
    correct: [
      ['Create a permission set that defines the job-function permissions', 'Permission sets centrally create permissions for common job functions and provision them across AWS accounts.'],
      ['Assign the Finance group to the permission set in each account where the group works', 'Permission sets are assigned to users and groups, so the group gets the same permissions in every assigned account.'],
    ],
    wrong: [
      ['Create identical IAM roles by hand in each of the 30 accounts and edit every role when the permissions change', 'The roles would have to be created and kept consistent by hand in all 30 accounts, which is the effort the company wants to avoid.'],
      ['Attach a service control policy to the organization root that grants the Finance permissions', 'SCPs do not grant permissions, so they cannot give the group its job-function permissions.'],
      ['Attach a permissions boundary to each Finance user so that the boundary grants the job-function permissions', 'A permissions boundary sets the maximum permissions that an identity-based policy can grant and does not grant permissions itself.'],
    ],
    slots: [0, 3],
    evidence: [
      'sso-what-is|You can also use IAM Identity Center permission sets to centrally create permissions for common job functions such as admin, provision them across AWS accounts, and assign them to users and groups.',
      'orgs-scps|SCPs do not grant permissions to the IAM users and IAM roles in your organization.',
      'iam-boundaries|A permissions boundary is an advanced feature for using a managed policy to set the maximum permissions that an identity-based policy can grant to an IAM entity.',
    ],
  }),
  mr({
    id: 'federation-bridge-014',
    building: 'federation-bridge',
    bullets: ['1.1-S6'],
    d: 3,
    stem: 'A company is moving a Windows application to AWS. The application servers on Amazon EC2 and an Amazon RDS for SQL Server database must use Active Directory, and employees must keep using the credentials from the Active Directory in the company\'s data center without copying the accounts into AWS. Which TWO actions meet these requirements? (Choose two.)',
    correct: [
      ['Create an AWS Managed Microsoft AD directory in AWS for the servers and the database', 'AWS Managed Microsoft AD supports Windows workloads, including Amazon RDS for SQL Server.'],
      ['Create a trust relationship between the AWS Managed Microsoft AD directory and the on-premises Active Directory', 'A trust lets AWS Managed Microsoft AD use credentials from the Active Directory that runs on premises.'],
    ],
    wrong: [
      ['Create an AD Connector directory that points to the on-premises domain controllers', 'AD Connector is a proxy service and is not compatible with RDS SQL Server.'],
      ['Create a Simple AD directory and re-create the employee accounts inside it', 'Simple AD is not compatible with RDS SQL Server and does not support trust relationships.'],
      ['Use the built-in identity store of IAM Identity Center as the domain for the servers and database', 'IAM Identity Center provides workforce sign-in to AWS accounts and applications, not an Active Directory domain for servers.'],
    ],
    slots: [1, 4],
    evidence: [
      'ds-what-is|All compatible applications work with user credentials that you store in AWS Managed Microsoft AD, or you can connect to your existing AD infrastructure with a trust and use credentials from an Active Directory running on-premises or on EC2 Windows.',
      'ds-what-is|AWS Managed Microsoft AD is your best choice if you need actual Active Directory features to support AWS applications or Windows workloads, including Amazon Relational Database Service for Microsoft SQL Server.',
      'ds-what-is|AD Connector is not compatible with RDS SQL Server.',
    ],
  }),
  mr({
    id: 'federation-bridge-015',
    building: 'federation-bridge',
    bullets: ['1.1-K2'],
    d: 1,
    stem: 'An administrator is setting up AWS IAM Identity Center for workforce access. Which TWO can IAM Identity Center use as the identity source for users and groups? (Choose two.)',
    correct: [
      ['An external SAML 2.0 identity provider', 'IAM Identity Center can use an external identity provider as the source of users and groups.'],
      ['A directory in AWS Managed Microsoft AD', 'IAM Identity Center can connect a directory in AWS Managed Microsoft AD by using AWS Directory Service.'],
    ],
    wrong: [
      ['A Simple AD directory in AWS Directory Service', 'IAM Identity Center does not support Simple AD as a connected directory.'],
      ['An Amazon Cognito user pool for the employees', 'It is not one of the identity sources that IAM Identity Center lists: Active Directory, an external identity provider or its own directory.'],
      ['The IAM users of the management account', 'It is not one of the identity sources that IAM Identity Center lists: Active Directory, an external identity provider or its own directory.'],
    ],
    slots: [0, 2],
    evidence: [
      'iam-idp-federation|You can use Active Directory, an external identity provider (IdP), or an IAM Identity Center directory as the identity source for users and groups to assign access to your AWS resources.',
      'sso-ad|With AWS IAM Identity Center, you can connect a self-managed directory in Active Directory (AD) or a directory in AWS Managed Microsoft AD by using AWS Directory Service.',
      'sso-ad|IAM Identity Center does not support SAMBA 4-based Simple AD as a connected directory.',
    ],
  }),
  mc({
    id: 'federation-bridge-016',
    building: 'federation-bridge',
    bullets: ['1.1-K2'],
    d: 3,
    stem: 'A company with a single AWS account uses SAML 2.0 federation. Employees in the Finance group need read-only access to Amazon S3 reports, and employees in the Engineering group must manage Amazon EC2 instances. Both groups sign in through the same identity provider, and the company wants the identity provider to decide which permissions each person gets. Which solution BEST meets these requirements?',
    correct: ['Create two IAM roles that trust the SAML provider and map each identity provider group to its role in the assertions', 'Assertions map users or groups to IAM roles, and the permissions of each role define what that group may do in AWS.'],
    wrong: [
      ['Create one IAM role with both sets of permissions and let every employee from the identity provider assume it', 'Finance employees would gain EC2 management and Engineering employees would gain S3 access, which exceeds what each group needs.'],
      ['Create an IAM user for each employee and add the Finance and Engineering users to two separate IAM groups', 'It uses IAM users with long-term credentials, and the identity provider no longer decides the permissions.'],
      ['Create two IAM roles that trust the account root and let employees switch roles after they sign in with a shared IAM user', 'It relies on a shared IAM user, and the identity provider does not decide which role each person gets.'],
    ],
    slot: 0,
    evidence: [
      'iam-saml|In your organization\'s IdP, you define assertions that map users or groups in your organization to the IAM roles.',
      'iam-saml|Note that different users and groups in your organization might map to different IAM roles.',
      'iam-saml|The roles that you create in IAM define what SAML federated principals from your organization are allowed to do in AWS.',
    ],
  }),
  mc({
    id: 'federation-bridge-017',
    building: 'federation-bridge',
    bullets: ['1.1-S6'],
    d: 3,
    tags: ['mock-reserve'],
    stem: 'A company needs a directory in AWS for Linux applications that require LDAP and for a few Windows servers. The company has no directory on premises. Later it plans to give the same users single sign-on to its AWS accounts through AWS IAM Identity Center and wants to avoid replacing the directory at that point. Which directory option BEST meets these requirements?',
    correct: ['Create an AWS Managed Microsoft AD directory in AWS Directory Service', 'It supplies LDAP support for Linux applications and actual Active Directory for Windows, and IAM Identity Center can connect to it.'],
    wrong: [
      ['Create a Simple AD directory in AWS Directory Service because it is the lowest-scale option', 'IAM Identity Center does not support Simple AD as a connected directory, so the directory would have to be replaced later.'],
      ['Create an AD Connector directory in AWS Directory Service for the servers and applications', 'AD Connector is a proxy to an existing on-premises Active Directory, and the company has none to connect to.'],
      ['Create an Amazon Cognito user pool and let the Linux and Windows servers authenticate against it', 'A user pool authenticates users of apps and APIs and is not an LDAP or Windows domain directory.'],
    ],
    slot: 1,
    evidence: [
      'ds-what-is|It\'s also best if you want a standalone Active Directory in the AWS Cloud that supports Office 365 or you need an LDAP directory to support your Linux applications.',
      'sso-ad|IAM Identity Center does not support SAMBA 4-based Simple AD as a connected directory.',
      'ds-what-is|AD Connector is a proxy service that provides an easy way to connect compatible AWS applications, such as Amazon WorkSpaces, Amazon Quick, and Amazon EC2 for Windows Server instances, to your existing on-premises Microsoft Active Directory.',
    ],
  }),
  mr({
    id: 'federation-bridge-018',
    building: 'federation-bridge',
    bullets: ['1.1-K2'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A company wants its employees to sign in to the AWS Management Console with a corporate SAML 2.0 identity provider in one AWS account, without an IAM user for each employee. Which TWO configuration steps are required in AWS? (Choose two.)',
    correct: [
      ['Create a SAML identity provider in IAM by using the metadata document from the identity provider', 'The metadata describes the identity provider to IAM and carries the keys AWS uses to validate the authentication responses.'],
      ['Create an IAM role whose trust policy names the SAML provider as the principal', 'The trust relationship between the organization and AWS is established by naming the SAML provider as the principal of the role.'],
    ],
    wrong: [
      ['Create an IAM user for every employee and store the SAML assertion as that user\'s console password', 'Federation exists so that an IAM user does not have to be created for everyone in the organization.'],
      ['Create an AWS Managed Microsoft AD directory and join the identity provider to its domain', 'A directory is not required for SAML federation, which relies on the identity provider and IAM roles.'],
      ['Create an Amazon Cognito user pool and register the console sign-in URL as its callback address', 'Console access through SAML federation uses an IAM SAML provider and roles, not a Cognito user pool.'],
    ],
    slots: [1, 3],
    evidence: [
      'iam-saml|Using your organization\'s IdP, you generate an equivalent SAML metadata XML file that can describe your IdP as an IAM identity provider in AWS.',
      'iam-saml|In the role\'s trust policy, you set the SAML provider as the principal, which establishes a trust relationship between your organization and AWS.',
      'iam-saml|This feature enables federated single sign-on (SSO), so users can log into the AWS Management Console or call AWS API operations without you having to create an IAM user for everyone in your organization.',
    ],
  }),
  mc({
    id: 'federation-bridge-019',
    building: 'federation-bridge',
    bullets: ['1.1-S6'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A company wants to join new Amazon EC2 Windows instances to its existing on-premises Active Directory domain. The company does not need Active Directory features in AWS and wants the SIMPLEST setup for these instances. Which solution meets these requirements?',
    correct: ['Use AD Connector and join the instances to the on-premises domain with seamless domain join', 'AD Connector lets EC2 Windows instances join the on-premises Active Directory domain through seamless domain join.'],
    wrong: [
      ['Create an AWS Managed Microsoft AD directory and join the instances to its new cloud domain', 'It creates a separate domain rather than using the existing on-premises domain, and it provides more than is needed.'],
      ['Install domain controllers on new EC2 instances and replicate the on-premises domain to them', 'The company would have to operate its own domain controllers, which is more work than a proxy service.'],
      ['Use the built-in identity store of IAM Identity Center and join the instances to that store', 'IAM Identity Center connects workforce users to AWS and is not an Active Directory domain that instances can join.'],
    ],
    slot: 2,
    evidence: [
      'ds-what-is|You can also join your EC2 Windows instances to your on-premises Active Directory domain through AD Connector using seamless domain join.',
      'ds-what-is|AD Connector is your best choice when you want to use your existing on-premises directory with compatible AWS services.',
    ],
  }),
];

export default questions;
