import type { Question } from '../../../src/content/types.ts';
import { mc, mr } from '../helpers.ts';

const questions: Question[] = [
  mc({
    id: 'gatehouse-001',
    building: 'gatehouse',
    bullets: ['1.2-K3'],
    d: 1,
    tags: ['trap:sg-vs-nacl'],
    stem: 'A company runs a public web application on Amazon EC2 instances in a VPC. Security staff identify one IPv4 address range that sends malicious requests. That range must be blocked at the subnet while every other internet user stays allowed. Which solution meets these requirements MOST simply?',
    correct: ['Add an inbound deny rule for the address range to the network ACL of the subnet', 'A network ACL can allow or deny traffic at the subnet level, so a deny rule blocks that range and everything else stays allowed.'],
    wrong: [
      ['Add an inbound deny rule for the address range to the security group of the instances', 'A security group can hold allow rules only, so it cannot express a deny rule.'],
      ['Remove the route to the internet gateway from the route table of the subnet', 'That would cut off every internet user, not only the malicious range.'],
      ['Edit the security group so that it allows only the addresses of known legitimate users', 'The site must stay open to all other internet users, and a security group cannot deny the range explicitly.'],
    ],
    slot: 0,
    evidence: [
      'vpc-sg-rules|You can specify allow rules, but not deny rules.',
      'vpc-nacls|Each rule can either allow or deny traffic.',
    ],
  }),
  mc({
    id: 'gatehouse-002',
    building: 'gatehouse',
    bullets: ['1.2-K3'],
    d: 2,
    tags: ['trap:sg-vs-nacl'],
    stem: 'A solutions architect removes every outbound rule from the security group of an Amazon EC2 web server. The group keeps one inbound rule that allows TCP port 443 from 0.0.0.0/0. Clients on the internet must still receive responses to their HTTPS requests. What should the architect do to meet this requirement with the LEAST effort?',
    correct: ['Make no change, because the stateful security group lets the responses leave on its own', 'Responses to allowed inbound traffic are allowed to leave the instance regardless of the outbound rules.'],
    wrong: [
      ['Add an outbound rule that allows TCP port 443 to 0.0.0.0/0 so that responses can reach clients', 'The response goes back to the port the client chose, and no outbound rule is needed for it to leave a stateful security group.'],
      ['Add an outbound rule that allows TCP ports 1024-65535 to 0.0.0.0/0 for the client ephemeral ports', 'This extra rule is not needed, because the security group already lets responses to allowed inbound traffic leave.'],
      ['Add an outbound rule that allows all traffic to the VPC CIDR block only', 'It would not cover clients on the internet and it is not needed for responses to allowed requests.'],
    ],
    slot: 1,
    evidence: [
      'vpc-security-groups|Responses to allowed inbound traffic are allowed to leave the instance, regardless of the outbound rules.',
    ],
  }),
  mr({
    id: 'gatehouse-003',
    building: 'gatehouse',
    bullets: ['1.2-K3'],
    d: 3,
    tags: ['trap:sg-vs-nacl'],
    stem: 'A company hosts a public HTTPS website on Amazon EC2 instances in one subnet. An architect associates a new custom network ACL with the subnet and must add the rules that let the site work for clients on many operating systems while keeping the rule set small. Which TWO rules form the SIMPLEST rule set that meets these requirements? (Choose two.)',
    correct: [
      ['Inbound rule: allow TCP port 443 from 0.0.0.0/0', 'It admits the HTTPS requests; the initial rules of a custom network ACL block all inbound traffic.'],
      ['Outbound rule: allow TCP ports 1024-65535 to 0.0.0.0/0', 'A network ACL is stateless, so the responses need an outbound rule, and the client chooses the ephemeral port that the response goes to.'],
    ],
    wrong: [
      ['Inbound rule: allow TCP ports 1024-65535 from 0.0.0.0/0', 'This admits return traffic for requests that start inside the subnet, and the website only answers requests.'],
      ['Outbound rule: allow TCP port 443 to 0.0.0.0/0', 'Responses go to the ephemeral port of the client and not to port 443.'],
      ['Inbound rule: allow all traffic from the CIDR block of the subnet', 'It does not admit clients from the internet.'],
    ],
    slots: [0, 3],
    evidence: [
      'vpc-create-nacl|The initial rules for a custom network ACL block all inbound and outbound traffic.',
      'vpc-custom-nacl|For every rule that you add, there must be an inbound or outbound rule that allows response traffic.',
      'vpc-custom-nacl|In practice, to cover the different types of clients that might initiate traffic to public-facing instances in your VPC, you can open ephemeral ports 1024-65535.',
    ],
  }),
  mc({
    id: 'gatehouse-004',
    building: 'gatehouse',
    bullets: ['1.2-K3'],
    d: 3,
    tags: ['trap:sg-vs-nacl'],
    stem: 'The network ACL of a public subnet has inbound rule 100, which allows TCP port 443 from 0.0.0.0/0, and rule 200, which allows TCP port 80 from 0.0.0.0/0. The company must now block HTTPS requests that come from 198.51.100.0/24 while keeping port 443 open to all other sources. Which change meets this requirement with the LEAST effort?',
    correct: ['Add an inbound rule numbered 90 that denies TCP port 443 from 198.51.100.0/24', 'Rules are evaluated from the lowest number, so the deny rule matches before rule 100 allows the traffic.'],
    wrong: [
      ['Add an inbound rule numbered 150 that denies TCP port 443 from 198.51.100.0/24', 'Rule 100 matches first and is applied, and no further rules are evaluated, so the deny rule is never reached.'],
      ['Add an inbound deny rule for 198.51.100.0/24 to the security group of the instances', 'A security group can hold allow rules only and cannot deny traffic.'],
      ['Associate a second network ACL that holds the deny rule with the same subnet', 'A subnet can be associated with only one network ACL, so this replaces rules 100 and 200.'],
    ],
    slot: 2,
    evidence: [
      'vpc-nacls|We evaluate the rules in order, starting with the lowest numbered rule, when deciding whether allow or deny traffic.',
      'vpc-nacls|If the traffic matches a rule, the rule is applied and we do not evaluate any additional rules.',
      'vpc-nacls|However, a subnet can be associated with only one network ACL at a time.',
    ],
  }),
  mc({
    id: 'gatehouse-005',
    building: 'gatehouse',
    bullets: ['1.2-K3'],
    d: 2,
    tags: ['trap:sg-vs-nacl'],
    stem: 'A solutions architect creates a custom network ACL for the database subnet of a VPC and associates it with the subnet. The security groups are unchanged, yet the application servers can no longer connect to the database on TCP port 5432. What is the MOST likely cause?',
    correct: ['The initial rules of a custom network ACL block all inbound and outbound traffic', 'A new custom network ACL denies everything by default, so allow rules for the database port and its responses are required.'],
    wrong: [
      ['A security group must be recreated whenever a new network ACL is associated with its subnet', 'The two are independent controls, and associating a network ACL does not change a security group.'],
      ['The route table of the subnet must be replaced with the main route table of the VPC', 'Route tables direct traffic and have no effect on the rules of a network ACL.'],
      ['A network ACL takes effect only after it is associated with the entire VPC instead of a subnet', 'A network ACL is associated with subnets, and the association here already exists.'],
    ],
    slot: 3,
    evidence: [
      'vpc-create-nacl|The initial rules for a custom network ACL block all inbound and outbound traffic.',
    ],
  }),
  mr({
    id: 'gatehouse-006',
    building: 'gatehouse',
    bullets: ['1.2-K3'],
    d: 2,
    tags: ['trap:sg-vs-nacl'],
    stem: 'A three-tier application in a VPC has an Application Load Balancer, application servers that listen on TCP port 8080, and a database that listens on TCP port 5432. Each tier has its own security group. The application servers scale in and out, so their IP addresses change often. Each tier must accept traffic ONLY from the tier in front of it. Which TWO inbound rules meet these requirements with the LEAST ongoing effort? (Choose two.)',
    correct: [
      ['Application server group: allow TCP port 8080 with the load balancer security group as the source', 'The rule applies to every instance in the referenced group, so it keeps working as the load balancer changes.'],
      ['Database group: allow TCP port 5432 with the application server security group as the source', 'The rule follows the application servers as they scale, so only that tier reaches the database.'],
    ],
    wrong: [
      ['Application server group: allow TCP port 8080 from the CIDR block of the VPC', 'Every resource in the VPC could reach the application servers, not only the load balancer.'],
      ['Database group: allow TCP port 5432 from 0.0.0.0/0', 'Any source on the internet could try to reach the database.'],
      ['Application server group: allow TCP port 8080 from 0.0.0.0/0', 'Any source on the internet could bypass the load balancer.'],
    ],
    slots: [1, 4],
    evidence: [
      'vpc-sg-rules|When you specify a security group as the source or destination for a rule, the rule affects all instances that are associated with the security groups.',
      'vpc-sg-rules|Add rules to the security group for the database servers to allow database requests from the web servers. The source is the security group for the web servers.',
    ],
  }),
  mc({
    id: 'gatehouse-007',
    building: 'gatehouse',
    bullets: ['1.2-K3'],
    d: 1,
    stem: 'Administrators must connect with SSH to Linux instances from the corporate network, which uses the public range 198.51.100.0/24. Which security group configuration is the MOST secure way to meet this requirement?',
    correct: ['An inbound rule that allows only TCP port 22 from 198.51.100.0/24', 'It limits both the port and the source to what the administrators need.'],
    wrong: [
      ['An inbound rule that allows TCP port 22 from 0.0.0.0/0', 'It lets anyone on the internet try to connect over SSH.'],
      ['An inbound rule that allows TCP ports 0-65535 from 198.51.100.0/24', 'It opens a large port range when only port 22 is needed.'],
      ['An inbound rule that allows all traffic from 0.0.0.0/0 and ::/0', 'It lets anyone on the internet use any port and protocol.'],
    ],
    slot: 0,
    evidence: [
      'vpc-security-groups|When you add inbound rules for ports 22 (SSH) or 3389 (RDP) so that you can access your EC2 instances, authorize only specific IP address ranges.',
      'vpc-security-groups|Do not open large port ranges.',
    ],
  }),
  mc({
    id: 'gatehouse-008',
    building: 'gatehouse',
    bullets: ['1.2-K3'],
    d: 2,
    tags: ['trap:sg-vs-nacl'],
    stem: 'An engineer adds a rule to the network ACL of the subnet that holds the backend Amazon EC2 instances of a load balancer. The rule denies all traffic whose source is that subnet\'s own CIDR block. Soon after, the load balancer reports every target as unhealthy. Which statement BEST explains the failure?',
    correct: ['The deny rule stops the load balancer from carrying out health checks on the instances', 'A deny rule for the subnet CIDR block blocks the health check traffic that the load balancer sends to its targets.'],
    wrong: [
      ['The security groups of the instances cannot be used together with a custom network ACL', 'Security groups and network ACLs work together, so this does not explain the failure.'],
      ['A network ACL deny rule applies only to outbound traffic from the instances', 'A network ACL has inbound rules and outbound rules and a deny rule applies to the traffic it matches.'],
      ['Backend instances must be in a subnet that has no network ACL associated with it', 'Every subnet is associated with a network ACL, so this cannot be the cause.'],
    ],
    slot: 1,
    evidence: [
      'vpc-custom-nacl|With Elastic Load Balancing, if the subnet for your backend instances has a network ACL in which you\'ve added a deny rule for all traffic with a source of either 0.0.0.0/0 or the subnet\'s CIDR, your load balancer can\'t carry out health checks on the instances.',
    ],
  }),
  mc({
    id: 'gatehouse-009',
    building: 'gatehouse',
    bullets: ['1.2-S1'],
    d: 1,
    stem: 'Application instances in a private subnet must download operating system updates from the internet. The instances must not accept connections that are initiated from the internet. Which solution is the MOST secure way to meet these requirements?',
    correct: ['Create a NAT gateway in a public subnet and route the private subnet traffic for 0.0.0.0/0 to it', 'The instances can connect to services outside the VPC, and external services cannot initiate a connection with them.'],
    wrong: [
      ['Route the private subnet traffic for 0.0.0.0/0 straight to an internet gateway and assign public IPv4 addresses', 'Resources on the internet could then initiate connections to the instances.'],
      ['Create an egress-only internet gateway and route 0.0.0.0/0 to it', 'An egress-only internet gateway is for IPv6 traffic only and does not serve IPv4 updates.'],
      ['Move the instances to a public subnet and allow all outbound traffic in the security group', 'A public subnet with public addresses can be reached from the internet, which the company does not want.'],
    ],
    slot: 2,
    evidence: [
      'vpc-nat-gateway|You can use a NAT gateway so that instances in a private subnet can connect to services outside your VPC but external services can\'t initiate a connection with those instances.',
      'vpc-egress-only-igw|To enable outbound-only internet communication over IPv4, use a NAT gateway instead.',
    ],
  }),
  mc({
    id: 'gatehouse-010',
    building: 'gatehouse',
    bullets: ['1.2-S1'],
    d: 2,
    stem: 'Application servers run in private subnets in three Availability Zones, and all of them route outbound traffic to a single NAT gateway in Availability Zone A. During an event in Availability Zone A, the servers in the other zones lost internet access. Which change provides the HIGHEST availability for outbound access?',
    correct: ['Create a NAT gateway in every Availability Zone and route each subnet to the local one', 'A zone failure then affects only the resources in that zone, and each zone keeps its own path to the internet.'],
    wrong: [
      ['Associate a second Elastic IP address with the existing NAT gateway', 'The NAT gateway is still created in a single Availability Zone, so a zone failure still removes it.'],
      ['Create a second NAT gateway in Availability Zone A and split the subnets between the two', 'Both gateways are still in the failed zone, so the other zones would still lose access.'],
      ['Replace the NAT gateway with a new one in Availability Zone B and route all of the subnets to it', 'It would still be one NAT gateway in one Availability Zone, so a failure of that zone removes outbound access for the subnets in the other zones.'],
    ],
    slot: 3,
    evidence: [
      'vpc-nat-basics|If you have resources in multiple Availability Zones and they share one NAT gateway, and if the NAT gateway\'s Availability Zone is down, resources in the other Availability Zones lose internet access.',
      'vpc-nat-basics|To improve resiliency, create a NAT gateway in each Availability Zone, and configure your routing to ensure that resources use the NAT gateway in the same Availability Zone.',
    ],
  }),
  mc({
    id: 'gatehouse-011',
    building: 'gatehouse',
    bullets: ['1.2-S1'],
    d: 2,
    tags: ['trap:nat-gateway-vs-instance'],
    stem: 'A company needs outbound internet access for instances in private subnets. The operations team does not want to patch the NAT software or write failover scripts. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['A NAT gateway in a public subnet', 'AWS manages a NAT gateway, so there is no maintenance, and it requires less effort to administer.'],
    wrong: [
      ['A NAT instance in a public subnet with a script for failover', 'The team would patch the instance and maintain the failover script, which is the work it wants to avoid.'],
      ['An Amazon EC2 bastion host in a public subnet with port forwarding', 'The team would have to configure and patch the host, and a bastion host is not a managed NAT service.'],
      ['An internet gateway route with public IPv4 addresses on the instances', 'It exposes the instances to inbound connections from the internet.'],
    ],
    slot: 0,
    evidence: [
      'vpc-nat-comparison|We recommend that you use NAT gateways because they provide better availability and bandwidth and require less effort on your part to administer.',
      'vpc-nat-comparison|Managed by AWS. You do not need to perform any maintenance.',
    ],
  }),
  mc({
    id: 'gatehouse-012',
    building: 'gatehouse',
    bullets: ['1.2-S1'],
    d: 3,
    tags: ['trap:nat-gateway-vs-instance'],
    stem: 'A company routes the outbound traffic of its private subnets through a NAT gateway. A new policy says that instances may send only HTTPS traffic to the internet, and the company wants to keep the managed NAT gateway. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Limit the outbound rules of the security groups of the instances to TCP port 443', 'Security groups attach to the instances behind the NAT gateway, so they can control the outbound traffic of those instances.'],
    wrong: [
      ['Associate a security group that allows only TCP port 443 with the NAT gateway', 'You cannot associate a security group with a NAT gateway.'],
      ['Replace the NAT gateway with a NAT instance only so that a security group can be attached', 'The company wants to keep the managed NAT gateway, and this adds maintenance work.'],
      ['Create an egress-only internet gateway with a rule for TCP port 443', 'An egress-only internet gateway is for IPv6 traffic only and cannot take a security group.'],
    ],
    slot: 1,
    evidence: [
      'vpc-nat-basics|You can\'t associate a security group with a NAT gateway. You can associate security groups with your instances to control inbound and outbound traffic.',
      'vpc-egress-only-igw|You can\'t associate a security group with an egress-only internet gateway to control the traffic that is allowed to reach or leave the egress-only internet gateway.',
    ],
  }),
  mc({
    id: 'gatehouse-013',
    building: 'gatehouse',
    bullets: ['1.2-S1'],
    d: 2,
    stem: 'An architect creates a public NAT gateway in a private subnet and adds a route for 0.0.0.0/0 to it in the route table of the application subnet. The application instances still cannot reach the internet. What is the SIMPLEST way to fix this?',
    correct: ['Create the public NAT gateway in a public subnet that routes to the internet gateway', 'A public NAT gateway belongs in a public subnet, and its traffic is routed on to the internet gateway of the VPC.'],
    wrong: [
      ['Attach a security group that allows outbound HTTPS to the NAT gateway', 'You cannot associate a security group with a NAT gateway, and the problem is where the gateway sits.'],
      ['Give every application instance an Elastic IP address instead of using the NAT gateway', 'That makes the instances reachable from the internet and does not fix the gateway placement.'],
      ['Add a route for 0.0.0.0/0 to the local target in the application route table', 'The local route only covers traffic inside the VPC, so it cannot reach the internet.'],
    ],
    slot: 2,
    evidence: [
      'vpc-nat-gateway|You create a public NAT gateway in a public subnet and must associate an Elastic IP address with the NAT gateway at creation. You route traffic from the NAT gateway to the internet gateway for the VPC.',
    ],
  }),
  mc({
    id: 'gatehouse-014',
    building: 'gatehouse',
    bullets: ['1.2-S1'],
    d: 3,
    tags: ['trap:gateway-vs-interface-endpoints'],
    stem: 'Application servers in private subnets send large volumes of data to Amazon S3 through a NAT gateway. The company wants this traffic to avoid the internet and the NAT gateway, at the LOWEST cost and with no change to the servers. Which solution meets these requirements?',
    correct: ['Create a gateway VPC endpoint for Amazon S3 and add it to the private route tables', 'A gateway endpoint reaches S3 without an internet gateway or NAT device, and there is no additional charge for it.'],
    wrong: [
      ['Create an interface VPC endpoint for Amazon S3 in each Availability Zone', 'An interface endpoint is not the lowest cost option, because the gateway endpoint for S3 has no additional charge.'],
      ['Create another NAT gateway in each Availability Zone for the S3 traffic to share the load', 'Traffic would still pass through NAT gateways and their data processing.'],
      ['Move the servers to a public subnet and send the S3 traffic through the internet gateway', 'The traffic would travel over the internet and the servers would be exposed to inbound connections.'],
    ],
    slot: 3,
    evidence: [
      'vpce-gateway|Gateway VPC endpoints provide reliable connectivity to Amazon S3 and DynamoDB without requiring an internet gateway or a NAT device for your VPC.',
      'vpce-gateway|There is no additional charge for using gateway endpoints.',
      'vpc-route-options|You can also create more specific routes to other targets to avoid unnecessary data processing charges for using a NAT gateway, or to route certain traffic privately.',
    ],
  }),
  mr({
    id: 'gatehouse-015',
    building: 'gatehouse',
    bullets: ['1.2-S1'],
    d: 2,
    stem: 'A company launches an Amazon EC2 web server in a new subnet of a nondefault VPC, and the server must be reachable from the internet over IPv4. An internet gateway is attached to the VPC. Which TWO additional steps are required? (Choose two.)',
    correct: [
      ['Add a route for 0.0.0.0/0 that targets the internet gateway to the route table of the subnet', 'The subnet then has a direct route to the internet gateway, which makes it a public subnet.'],
      ['Give the instance a public IPv4 address or an Elastic IP address', 'For IPv4 communication over the internet gateway, the instance needs a public IPv4 address.'],
    ],
    wrong: [
      ['Create a NAT gateway in the subnet and route 0.0.0.0/0 to it', 'A NAT gateway serves outbound-only connections from private subnets and does not make the server reachable.'],
      ['Create an egress-only internet gateway and add a route for ::/0 to it', 'It is for outbound IPv6 traffic only and prevents the internet from initiating connections.'],
      ['Create a VPC peering connection to the default VPC and route through it', 'Peering connects VPCs and does not provide a path to the internet.'],
    ],
    slots: [2, 4],
    evidence: [
      'vpc-route-options|To do this, create and attach an internet gateway to your VPC, and then add a route with a destination of 0.0.0.0/0 for IPv4 traffic or ::/0 for IPv6 traffic, and a target of the internet gateway ID (igw-xxxxxxxxxxxxxxxxx).',
      'vpc-igw|To enable communication over the internet for IPv4, your instance must have a public IPv4 address.',
    ],
  }),
  mc({
    id: 'gatehouse-016',
    building: 'gatehouse',
    bullets: ['1.2-S1'],
    d: 2,
    stem: 'A subnet route table has three routes: 10.0.0.0/16 to local, 172.31.0.0/16 to a VPC peering connection, and 0.0.0.0/0 to an internet gateway. An instance in the subnet sends a packet to 172.31.4.20. Where does the VPC send the packet?',
    correct: ['To the VPC peering connection, because that route is the most specific match', 'AWS directs traffic using the most specific route that matches, known as the longest prefix match.'],
    wrong: [
      ['To the internet gateway, because 0.0.0.0/0 is the default route for all traffic', 'The default route is used only when no more specific route matches.'],
      ['To the local target, because every packet from the subnet is first delivered inside the VPC', 'The local route covers only destinations within 10.0.0.0/16, and 172.31.4.20 is outside it.'],
      ['To the internet gateway first, with the peering connection used if that route fails', 'The route table has no fallback order between targets and the most specific route wins.'],
    ],
    slot: 0,
    evidence: [
      'vpc-route-priority|In general, we direct traffic using the most specific route that matches the traffic. This is known as the longest prefix match.',
      'vpc-route-priority|Any traffic from the subnet that\'s destined for the 172.31.0.0/16 IP address range uses the peering connection, because this route is more specific than the route for internet gateway.',
    ],
  }),
  mc({
    id: 'gatehouse-017',
    building: 'gatehouse',
    bullets: ['1.2-S2'],
    d: 1,
    stem: 'A team asks how to tell a public subnet from a private subnet in a VPC. Which characteristic defines a public subnet?',
    correct: ['Its route table has a direct route to an internet gateway', 'The route table makes a subnet public, and resources in a public subnet can access the public internet.'],
    wrong: [
      ['Its CIDR block belongs to a public IP address range', 'Routing, not the address range, decides the subnet type.'],
      ['Its network ACL allows all inbound and outbound traffic', 'A network ACL filters traffic and does not decide whether a subnet has a route to the internet.'],
      ['It hosts at least one NAT gateway', 'A NAT gateway often sits in a public subnet, but its presence does not define the subnet type.'],
    ],
    slot: 1,
    evidence: [
      'vpc-subnets|Public subnet – The subnet has a direct route to an internet gateway. Resources in a public subnet can access the public internet.',
      'vpc-subnets|Private subnet – The subnet does not have a direct route to an internet gateway.',
    ],
  }),
  mr({
    id: 'gatehouse-018',
    building: 'gatehouse',
    bullets: ['1.2-S2'],
    d: 2,
    stem: 'A company runs a database on Amazon EC2 instances. The database must be reachable only from the application servers of the same VPC and never from the internet. Which TWO actions meet these requirements in the MOST secure way? (Choose two.)',
    correct: [
      ['Launch the database instances in private subnets that have no direct route to an internet gateway', 'A private subnet does not have a direct route to an internet gateway, so the internet cannot reach the instances.'],
      ['Allow the database port in the database security group only from the security group of the application servers', 'A security group rule can name another security group as its source, which limits access to that tier.'],
    ],
    wrong: [
      ['Launch the database instances in a public subnet and assign Elastic IP addresses', 'A public subnet with public addresses can be reached from the internet.'],
      ['Allow the database port from 0.0.0.0/0 in the security group and rely on database passwords', 'It leaves the database open to every source on the internet.'],
      ['Create an egress-only internet gateway and route all IPv4 traffic through it', 'An egress-only internet gateway handles IPv6 traffic only and is not a way to isolate a tier.'],
    ],
    slots: [0, 2],
    evidence: [
      'vpc-subnets|Private subnet – The subnet does not have a direct route to an internet gateway.',
      'vpc-sg-rules|When you specify a security group as the source or destination for a rule, the rule affects all instances that are associated with the security groups.',
    ],
  }),
  mc({
    id: 'gatehouse-019',
    building: 'gatehouse',
    bullets: ['1.2-S2'],
    d: 1,
    stem: 'A company deploys a web tier on Amazon EC2 instances that must keep running if one Availability Zone fails. How should the architect lay out the subnets for this tier to achieve the HIGHEST availability?',
    correct: ['Create at least one subnet for the tier in each Availability Zone it uses', 'A subnet resides entirely within one Availability Zone and cannot span zones.'],
    wrong: [
      ['Create one subnet in one Availability Zone and use EC2 Auto Scaling to replace failed instances in it', 'The subnet and every replacement instance stay in one Availability Zone, so a failure of that zone stops the whole tier.'],
      ['Create one subnet and let the VPC place its addresses across zones', 'Each subnet is tied to a single zone when it is created.'],
      ['Create one subnet and add a second CIDR block for the other zone', 'Adding an address range does not move the subnet to another zone.'],
    ],
    slot: 2,
    evidence: [
      'vpc-subnets|Each subnet must reside entirely within one Availability Zone and cannot span zones.',
      'vpc-subnets|By launching AWS resources in separate Availability Zones, you can protect your applications from the failure of a single Availability Zone.',
    ],
  }),
  mc({
    id: 'gatehouse-020',
    building: 'gatehouse',
    bullets: ['1.2-S2'],
    d: 3,
    tags: ['trap:sg-vs-nacl'],
    stem: 'A security team requires that SMB (TCP port 445) is never reachable from the internet for any resource in the workload subnets, even if an engineer launches an instance with an overly permissive security group. The team wants a single control with the LEAST ongoing effort. Which solution meets these requirements?',
    correct: ['Add an inbound deny rule for TCP port 445 to the network ACL of the workload subnets', 'A network ACL applies to the whole subnet and can deny traffic, so it works as a guard rail for every instance.'],
    wrong: [
      ['Add an inbound deny rule for TCP port 445 to the default security group', 'A security group cannot deny, and instances can be launched with other groups.'],
      ['Review the security group of every new instance by hand before it is launched', 'It depends on a manual step for each instance, which is the ongoing effort the team wants to avoid.'],
      ['Remove the allow rule for TCP port 445 from the security group of each current instance', 'It covers only current instances and not instances launched later with a permissive group.'],
    ],
    slot: 3,
    evidence: [
      'vpc-infra-security|Network ACLs can be effective as a secondary control (for example, to deny a specific subset of traffic) or as high-level subnet guard rails.',
      'vpc-infra-security|Also, because network ACLs apply to an entire subnet, they can be used as defense-in-depth in case an instance is ever launched without the correct security group.',
    ],
  }),
  mc({
    id: 'gatehouse-021',
    building: 'gatehouse',
    bullets: ['1.2-S2'],
    d: 2,
    stem: 'A subnet is associated with network ACL A. An administrator then associates network ACL B with the same subnet. What is the result?',
    correct: ['Network ACL A is no longer associated, and only network ACL B controls the subnet', 'A subnet can be associated with only one network ACL at a time, and a new association removes the previous one.'],
    wrong: [
      ['Both network ACLs are evaluated, with the lower rule number winning across them', 'Only one network ACL applies to a subnet at a time, so there is no combined evaluation.'],
      ['The association fails until network ACL A is deleted', 'The new association is accepted and replaces the old one.'],
      ['Network ACL B is stored, and network ACL A stays in force until the subnet is restarted', 'Subnets are not restarted, and the association changes directly.'],
    ],
    slot: 0,
    evidence: [
      'vpc-nacls|You can associate a network ACL with multiple subnets. However, a subnet can be associated with only one network ACL at a time. When you associate a network ACL with a subnet, the previous association is removed.',
    ],
  }),
  mr({
    id: 'gatehouse-022',
    building: 'gatehouse',
    bullets: ['1.2-S1', '1.2-S2'],
    d: 3,
    stem: 'A company designs a VPC across two Availability Zones for a web application. Only the load balancer may accept connections from the internet. The application servers need outbound internet access for updates, and the database servers must have no path to the internet. Which THREE actions create the MOST secure design that meets these requirements? (Choose three.)',
    correct: [
      ['Place the Application Load Balancer in public subnets, one in each Availability Zone', 'Public subnets route to an internet gateway, which the internet-facing load balancer needs.'],
      ['Place the application servers in private subnets and route 0.0.0.0/0 to a NAT gateway in a public subnet', 'The servers can connect out for updates, and external services cannot initiate a connection with them.'],
      ['Place the database servers in private subnets whose route tables have no route to an internet gateway or NAT gateway', 'Without such a route, the database tier has no path to the internet.'],
    ],
    wrong: [
      ['Place the application servers in public subnets with Elastic IP addresses', 'This would make the servers reachable from the internet, not only the load balancer.'],
      ['Place the database servers in private subnets and route 0.0.0.0/0 to the NAT gateway', 'A route to the NAT gateway gives the database servers a path to the internet.'],
      ['Place the application servers in private subnets and route 0.0.0.0/0 to an egress-only internet gateway', 'An egress-only internet gateway handles IPv6 traffic only and does not serve IPv4 updates.'],
    ],
    slots: [1, 3, 5],
    evidence: [
      'vpc-subnets|Public subnet – The subnet has a direct route to an internet gateway.',
      'vpc-route-options|Then add a route for the private subnet\'s route table that routes IPv4 internet traffic (0.0.0.0/0) to the NAT device.',
      'vpc-egress-only-igw|An egress-only internet gateway is for use with IPv6 traffic only.',
    ],
  }),
  mc({
    id: 'gatehouse-023',
    building: 'gatehouse',
    bullets: ['1.2-S2'],
    d: 2,
    stem: 'An Amazon EC2 instance in a private subnet has a public IPv4 address, but users on the internet still cannot connect to it. The security group allows the traffic. Which reason BEST explains this?',
    correct: ['The route table of the subnet has no route to an internet gateway', 'With no route to an internet gateway, instances cannot communicate with the internet even when they have public IP addresses.'],
    wrong: [
      ['The instance needs a NAT gateway to accept inbound connections from the internet', 'A NAT gateway serves outbound connections and does not accept inbound ones.'],
      ['Public IPv4 addresses work only in subnets that have a custom network ACL associated', 'Addressing does not depend on the type of network ACL, and every subnet has one.'],
      ['The security group must also be attached to the internet gateway', 'A security group is associated with resources such as instances and not with an internet gateway.'],
    ],
    slot: 1,
    evidence: [
      'vpc-igw|Because there is no route to the internet gateway, instances in the private subnet can\'t communicate with the internet, even if they have public IP addresses.',
    ],
  }),
  // Reserve questions
  mc({
    id: 'gatehouse-024',
    building: 'gatehouse',
    bullets: ['1.2-K3'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'An Amazon EC2 instance is associated with two security groups. The first group allows TCP port 443 from 0.0.0.0/0, and the second allows TCP port 22 from 198.51.100.0/24. Which traffic can reach the instance?',
    correct: ['HTTPS from any source and SSH from 198.51.100.0/24, because the rules are combined', 'The rules from each security group are aggregated into one set that decides whether to allow access.'],
    wrong: [
      ['Only traffic that both groups allow, so no inbound traffic is accepted', 'Rules are aggregated rather than intersected, so each allow rule still applies.'],
      ['Only the rules of the security group that was associated with the instance first, not the second', 'All associated groups apply, not just the first one.'],
      ['HTTPS from any source only, because SSH rules apply only to a single group', 'A resource can have several groups, and the SSH rule in the second group still applies.'],
    ],
    slot: 2,
    evidence: [
      'vpc-sg-rules|When you associate multiple security groups with a resource, the rules from each security group are aggregated to form a single set of rules that are used to determine whether to allow access.',
    ],
  }),
  mc({
    id: 'gatehouse-025',
    building: 'gatehouse',
    bullets: ['1.2-S1'],
    d: 3,
    tags: ['mock-reserve', 'trap:nat-gateway-vs-instance'],
    stem: 'A company keeps adding workloads in new Availability Zones. Today the team creates a zonal NAT gateway and a separate route table for each new zone. The company wants automatic high availability across zones, no public subnet to host the NAT, and the LEAST operational overhead as workloads expand. Which solution meets these requirements?',
    correct: ['Create a regional NAT gateway and route the private subnets of all zones to it', 'It expands across Availability Zones with the workloads and needs no public subnet or new gateway for each zone.'],
    wrong: [
      ['Keep creating zonal NAT gateways in public subnets and update the route tables for each new zone', 'This is the repeated work the company wants to remove, and it needs public subnets.'],
      ['Run NAT instances in an Auto Scaling group in each Availability Zone', 'The team would patch the instances and maintain failover, which increases the overhead.'],
      ['Create a private NAT gateway in one Availability Zone and route all zones to it', 'A private NAT gateway is for private connectivity and sits in a single zone.'],
    ],
    slot: 3,
    evidence: [
      'vpc-nat-regional|A regional NAT gateway automatically expands across Availability Zones based on your workload presence.',
      'vpc-nat-regional|You also don\'t have to create and delete NAT Gateways and edit your route tables every time your workloads expand to new Availability Zones.',
      'vpc-nat-regional|you do not need a public subnet in your VPC to host a regional NAT Gateway',
    ],
  }),
  mc({
    id: 'gatehouse-026',
    building: 'gatehouse',
    bullets: ['1.2-S1'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A VPC has both IPv4 and IPv6 CIDR blocks. Instances in a private subnet use IPv6 addresses and must download updates from the internet, while the internet must not be able to start an IPv6 connection to them. Which solution is the SIMPLEST that meets these requirements?',
    correct: ['An egress-only internet gateway with a route for ::/0 in the subnet route table', 'It allows outbound IPv6 communication and prevents the internet from initiating an IPv6 connection.'],
    wrong: [
      ['An internet gateway with a route for ::/0 in the subnet route table', 'IPv6 addresses are public by default, so the internet could initiate connections to the instances.'],
      ['A public NAT gateway with an Elastic IP address and a route for ::/0', 'A NAT gateway performs NAT64 for IPv6 workloads that reach IPv4 resources; it does not provide outbound-only IPv6-to-IPv6 access, which is what the instances need and what the egress-only internet gateway provides.'],
      ['A security group rule that denies all inbound IPv6 traffic on the instances', 'A security group cannot hold deny rules, and it provides no outbound path.'],
    ],
    slot: 0,
    evidence: [
      'vpc-egress-only-igw|An egress-only internet gateway is a horizontally scaled, redundant, and highly available VPC component that allows outbound communication over IPv6 from instances in your VPC to the internet, and prevents the internet from initiating an IPv6 connection with your instances.',
    ],
  }),
  mc({
    id: 'gatehouse-027',
    building: 'gatehouse',
    bullets: ['1.2-S2'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A company connects an on-premises network to a VPC with an AWS Site-to-Site VPN connection through a virtual private gateway. A reporting tier in the VPC must be reachable only from the on-premises network and must have no path to the internet. Which subnet design is the SIMPLEST way to meet these requirements?',
    correct: ['A subnet that routes to the virtual private gateway and has no internet gateway route', 'This is a VPN-only subnet, which reaches the VPN connection and has no route to an internet gateway.'],
    wrong: [
      ['A public subnet whose route table sends 0.0.0.0/0 to an internet gateway for the tier', 'It gives the tier a direct route to the internet gateway.'],
      ['A subnet with a route to an internet gateway and the VPN routes disabled', 'It still has a route to the internet gateway, and the tier could not use the VPN.'],
      ['A public subnet that also hosts a NAT gateway for the reporting tier', 'A public subnet has a route to the internet gateway, which is not allowed here.'],
    ],
    slot: 1,
    evidence: [
      'vpc-subnets|VPN-only subnet – The subnet has a route to a Site-to-Site VPN connection through a virtual private gateway. The subnet does not have a route to an internet gateway.',
    ],
  }),
];

export default questions;
