import type { Question } from '../../../src/content/types.ts';
import { mc, mr } from '../helpers.ts';

const questions: Question[] = [
  mc({
    id: 'identity-keep-001',
    building: 'identity-keep',
    bullets: ['1.1-K4'],
    d: 1,
    stem: "A company's data analysts need to download report files from a single prefix in one Amazon S3 bucket. An administrator is writing the IAM policy for the analysts. Which policy BEST follows the principle of least privilege?",
    correct: ['A policy that allows only s3:GetObject on the objects under that prefix', 'It grants only the action the analysts need on the specific resources they use, which is what least privilege means.'],
    wrong: [
      ['A policy that allows s3:* on every bucket in the account', 'It grants far more actions and far more resources than the analysts need for downloading reports.'],
      ['A policy that allows s3:GetObject and s3:PutObject on the whole bucket', 'Uploading is not required, and the whole bucket is wider than the single prefix the analysts use.'],
      ['The AWS managed AmazonS3FullAccess policy attached to the analysts', 'It gives full access to Amazon S3, which is much broader than reading files from one prefix.'],
    ],
    slot: 0,
    evidence: [
      'iam-best-practices|When you set permissions with IAM policies, grant only the permissions required to perform a task.',
      'iam-best-practices|You do this by defining the actions that can be taken on specific resources under specific conditions, also known as least-privilege permissions.',
    ],
  }),
  mc({
    id: 'identity-keep-002',
    building: 'identity-keep',
    bullets: ['1.1-S1'],
    d: 1,
    stem: 'A startup created its AWS account a month ago, and the founder still signs in as the account root user for all daily work. The founder wants to follow AWS guidance to MOST improve the security of the account. What should the founder do?',
    correct: ['Create an administrative user for daily work and keep the root user for root-only tasks', 'AWS recommends an administrative user for everyday tasks and root user sign-in only for tasks that require root-level permissions.'],
    wrong: [
      ['Keep using the root user for daily work, but change its password every 30 days and log each sign-in', 'The root user has complete access to the account, so using it daily stays risky no matter how often the password changes.'],
      ['Create access keys for the root user and run all daily work from the AWS CLI instead of the console', 'AWS strongly recommends not creating access keys for the root user because it has full access to everything.'],
      ['Share the root user credentials with two more administrators so that the risk is spread across the team', 'More people holding the most powerful credentials increases exposure instead of reducing the use of the root user.'],
    ],
    slot: 1,
    evidence: [
      'iam-root-best-practices|Instead of accessing the root user, create an administrative user for everyday tasks.',
      'iam-root-user|Use the root user only to perform the tasks that require root-level permissions.',
    ],
  }),
  mc({
    id: 'identity-keep-003',
    building: 'identity-keep',
    bullets: ['1.1-S2'],
    d: 1,
    stem: 'A company hires several new developers each quarter. All developers need the same permissions to a set of AWS services, and the administrators want to manage those permissions in one place with the LEAST effort. Which solution meets these requirements?',
    correct: ['Create an IAM user group with the permissions policy and add each developer to it', 'Every user in the group receives the policy permissions, and a new developer only has to be added to the group.'],
    wrong: [
      ['Attach the same permissions policy to every developer IAM user one by one as each person joins', 'Each new hire needs another attachment, and a permission change has to be repeated user by user.'],
      ['Create one shared IAM user with the permissions policy and give its credentials to every developer', 'Sharing one identity gives no individual identity per developer and does not use a group to manage permissions.'],
      ['Create an IAM role for each developer and give each role its own inline policy', 'An inline policy is tied to a single identity, so every change has to be repeated for each role.'],
    ],
    slot: 2,
    evidence: [
      'iam-groups|User groups let you specify permissions for multiple users, which can make it easier to manage the permissions for those users.',
      'iam-groups|If a new user joins your organization and needs administrator privileges you can assign the appropriate permissions by adding the user to the Admins user group.',
    ],
  }),
  mc({
    id: 'identity-keep-004',
    building: 'identity-keep',
    bullets: ['1.1-S1'],
    d: 1,
    stem: 'A security policy requires every IAM user in an AWS account to choose a console password that meets a minimum complexity. An administrator wants to enforce this for all IAM users with the SIMPLEST approach. What should the administrator do?',
    correct: ['Set a password policy for the account', 'A password policy enforces a minimum password complexity for the IAM users of the account.'],
    wrong: [
      ['Require MFA for every IAM user in the account', 'MFA adds a second factor at sign-in but sets no rule about how complex the password must be.'],
      ['Attach a permissions boundary to every IAM user in the account', 'A permissions boundary limits the maximum permissions of an identity and has no effect on password rules.'],
      ['Put all IAM users in a group that has an inline policy attached', 'A group policy grants or denies permissions and does not enforce password complexity.'],
    ],
    slot: 3,
    evidence: [
      'iam-users|Set a password policy to enforce a minimum password complexity.',
      'iam-users|Create and change the passwords that permit access to the AWS Management Console.',
    ],
  }),
  mc({
    id: 'identity-keep-005',
    building: 'identity-keep',
    bullets: ['1.1-K4'],
    d: 2,
    stem: 'A company has 300 employees who need console and CLI access to workloads in five AWS accounts. The company wants people to use temporary credentials and to manage access from one place with the LEAST administrative effort. Which solution BEST meets these requirements?',
    correct: ['Use AWS IAM Identity Center to manage workforce access to the accounts', 'AWS recommends IAM Identity Center for centralized access management, and federated users receive temporary credentials.'],
    wrong: [
      ['Create an IAM user for each employee in every account and require MFA', 'It creates about 1,500 identities with long-term credentials that are managed account by account.'],
      ['Create one shared IAM user per account and distribute its access keys', 'Shared long-term access keys are not temporary credentials and give no individual identity per employee.'],
      ['Create employee IAM users in one account and copy their access keys into the other four', 'The employees keep long-term credentials, and the keys must be copied and maintained in every account.'],
    ],
    slot: 0,
    evidence: [
      'iam-best-practices|Require your human users to use temporary credentials when accessing AWS.',
      'iam-best-practices|For centralized access management, we recommend that you use AWS IAM Identity Center (IAM Identity Center) to manage access to your accounts and permissions within those accounts.',
    ],
  }),
  mc({
    id: 'identity-keep-006',
    building: 'identity-keep',
    bullets: ['1.1-S1', '1.1-K4'],
    d: 2,
    stem: 'A nightly script on an Amazon EC2 instance copies files to an Amazon S3 bucket. The script signs its requests with access keys that belong to the account root user. Which change MOST improves security with the LEAST disruption to the script?',
    correct: ['Delete the root access keys and attach an IAM role with S3 permissions to the instance', 'The role gives the instance temporary credentials, and no root access keys remain to be stolen.'],
    wrong: [
      ['Rotate the root access keys every 90 days and keep them in an encrypted file', 'Root access keys would still exist, and the root user has full access to the account.'],
      ['Store the root access keys in AWS Secrets Manager and have the script read them', 'The script still uses root access keys, which AWS strongly recommends not to create.'],
      ['Create an IAM user with AdministratorAccess and store its access keys in the script configuration file', 'It replaces root keys with long-term keys that have far more permissions than copying files needs.'],
    ],
    slot: 1,
    evidence: [
      'iam-root-best-practices|We strongly recommend that you do not create access keys for your root user because the root user has full access to all AWS services and resources in the account, including billing information.',
      "iam-best-practices|When you're building on an AWS compute service, such as Amazon EC2 or Lambda, AWS delivers the temporary credentials of an IAM role to that compute resource.",
    ],
  }),
  mr({
    id: 'identity-keep-007',
    building: 'identity-keep',
    bullets: ['1.1-S1'],
    d: 2,
    stem: 'A company requires IAM users with administrator permissions to sign in with MFA. The company wants the MOST phishing-resistant protection and does not want one lost device to lock an administrator out. Which TWO actions meet these requirements? (Choose two.)',
    correct: [
      ['Register a passkey or security key as an MFA device for each administrator', 'FIDO-based passkeys and security keys resist phishing, and AWS recommends them over other MFA types.'],
      ['Register more than one MFA device for each administrator', 'Several devices can be registered, and a remaining device can be used to sign in if one is lost.'],
    ],
    wrong: [
      ['Register a single virtual authenticator app on each administrator\'s phone', 'A TOTP app is less phishing-resistant than a security key, and one lost phone leaves no other device.'],
      ['Assign one hardware TOTP token to the whole administrator team to share', 'Each MFA device assigned to a user must be unique, so a token cannot be shared between users.'],
      ['Require a longer password for each administrator and rotate it every 30 days', 'Password rules are not MFA, and they do not provide a second device if one is lost.'],
    ],
    slots: [0, 3],
    evidence: [
      'iam-mfa|We recommend that you use phishing-resistant MFA, such as passkeys and security keys, as your MFA device.',
      'iam-mfa|In the event of a lost, stolen, or inaccessible MFA device you can use one of the remaining MFA devices to access the AWS account without performing the AWS account recovery procedure.',
      'iam-mfa|Each MFA device assigned to a user must be unique.',
    ],
  }),
  mc({
    id: 'identity-keep-008',
    building: 'identity-keep',
    bullets: ['1.1-K4'],
    d: 2,
    stem: 'An IAM policy lets several users read and write objects in an Amazon S3 bucket. The security team now requires these permissions to apply only when the requests are sent using TLS. Which solution meets this requirement with the LEAST change to the policy design?',
    correct: ['Add a Condition element to the policy statement that requires requests to use TLS', 'A condition makes the statement apply only when the request meets it, such as being sent using TLS.'],
    wrong: [
      ['Add a Principal element to the policy that names TLS as the allowed protocol', 'An identity-based policy cannot use the Principal element, which identifies who, not the protocol.'],
      ['Attach a permissions boundary that lists the same S3 actions as the policy', 'A boundary caps the maximum permissions of an identity and does not check how a request was sent.'],
      ['Move the users into an IAM group and attach the policy to the group instead', 'Grouping changes how permissions are assigned but adds no check on the protocol of the request.'],
    ],
    slot: 2,
    evidence: [
      'iam-best-practices|That way, you can grant access to actions and resources, but only if the access request meets specific conditions.',
      'iam-best-practices|For example, you can write a policy condition to specify that all requests must be sent using TLS.',
      'iam-el-principal|You cannot use the Principal element in an identity-based policy.',
    ],
  }),
  mc({
    id: 'identity-keep-009',
    building: 'identity-keep',
    bullets: ['1.1-K4'],
    d: 2,
    stem: 'A security team wants to be told continuously when a resource in its AWS account, such as an Amazon S3 bucket or an IAM role, can be accessed publicly or from another AWS account. The team wants the LEAST operational effort. Which service should the team use?',
    correct: ['IAM Access Analyzer', 'It monitors supported resource types continuously and generates a finding for resources that allow public or cross-account access.'],
    wrong: [
      ['Amazon Inspector', 'Amazon Inspector scans workloads for software vulnerabilities and does not report who can access a resource.'],
      ['AWS CloudTrail Event history', 'It is a record of past management events, not an analysis of which principals a resource allows.'],
      ['Amazon GuardDuty', 'GuardDuty is a threat detection service and does not analyze the access that resource policies grant.'],
    ],
    slot: 3,
    evidence: [
      'iam-best-practices|IAM Access Analyzer also monitors supported resource types continuously and generates a finding for resources that allow public or cross-account access.',
      'iam-best-practices|Before you grant permissions for public or cross-account access in AWS, we recommend that you verify if such access is required.',
    ],
  }),
  mr({
    id: 'identity-keep-010',
    building: 'identity-keep',
    bullets: ['1.1-K4'],
    d: 1,
    stem: 'A company is reviewing how it uses IAM before a security audit. Which THREE actions are the BEST fit with AWS security best practices? (Choose three.)',
    correct: [
      ['Give applications that run on Amazon EC2 instances an IAM role instead of IAM user access keys', 'AWS delivers the temporary credentials of the role to the instance, so no long-lived keys are distributed.'],
      ['Let workforce users sign in through an identity provider and receive temporary credentials', 'AWS recommends federated access for human users, which provides temporary credentials.'],
      ['Require MFA for every IAM user and for the root user', 'AWS says to require MFA wherever an IAM user or root user is needed.'],
    ],
    wrong: [
      ['Create one IAM user with long-term access keys that all developers share', 'Long-term shared keys are the opposite of temporary credentials and give no individual identity.'],
      ['Embed access keys in the application source code so deployments need no setup', 'Long-lived keys in code are exactly what IAM roles for workloads are meant to avoid.'],
      ['Create access keys for the root user so administrators can use the AWS CLI', 'AWS strongly recommends not creating access keys for the root user.'],
    ],
    slots: [1, 2, 4],
    evidence: [
      'iam-best-practices|Applications written using an AWS SDK will discover and use these temporary credentials to access AWS resources, and there is no need to distribute long lived credentials for an IAM user to your workloads running on AWS.',
      'iam-best-practices|You can use an identity provider for your human users to provide federated access to AWS accounts by assuming roles, which provide temporary credentials.',
      'iam-best-practices|However, for scenarios in which you need an IAM user or root user in your account, require MFA for additional security.',
    ],
  }),
  mc({
    id: 'identity-keep-011',
    building: 'identity-keep',
    bullets: ['1.1-S2'],
    d: 2,
    tags: ['trap:iam-roles-vs-resource-policies'],
    stem: 'A company wants all members of the IAM user group Analysts, in the same AWS account, to read objects in an Amazon S3 bucket. An administrator wrote a bucket policy that names the Analysts group as the Principal, and it does not work. Which fix is the SIMPLEST?',
    correct: ['Attach an identity-based policy that allows reading the bucket to the Analysts group', 'Group members receive the policy permissions, and in one account an allow from an identity-based policy is enough.'],
    wrong: [
      ['Rewrite the bucket policy to name the ARN of every analyst IAM user as a principal', 'It can work, but the bucket policy must be edited whenever someone joins or leaves, which is more effort.'],
      ['Create an IAM role that trusts the Analysts group as a principal and have analysts assume it', 'A group cannot be identified as a principal in a policy, because groups relate to permissions, not authentication.'],
      ['Attach the existing bucket policy to the Analysts group instead of to the S3 bucket itself', 'A resource-based policy is attached to a resource, not to a group, so this is not possible.'],
    ],
    slot: 0,
    evidence: [
      'iam-groups|You cannot identify a user group as a Principal in a policy (such as a resource-based policy) because groups relate to permissions, not authentication, and principals are authenticated IAM entities.',
      'iam-eval-logic|If an action is allowed by an identity-based policy, a resource-based policy, or both, then AWS allows the action.',
    ],
  }),
  mc({
    id: 'identity-keep-012',
    building: 'identity-keep',
    bullets: ['1.1-S2'],
    d: 2,
    stem: 'Members of the IAM group Contractors get s3:* on all buckets from the AWS managed AmazonS3FullAccess policy. A new rule says contractors must never be able to delete objects in the audit-logs bucket, even if another policy allows it. What is the SIMPLEST way to meet this rule?',
    correct: ['Attach a policy to the group that explicitly denies s3:DeleteObject on audit-logs', 'An explicit deny in any of the policies overrides the allow, so no other policy can restore the delete permission.'],
    wrong: [
      ['Edit AmazonS3FullAccess to remove s3:DeleteObject for the audit-logs bucket', 'The permissions of an AWS managed policy cannot be changed.'],
      ['Attach a second policy to the group that allows only the other S3 actions on audit-logs', 'Policies are combined with a logical OR, so the existing s3:* allow still permits deleting.'],
      ['Attach a permissions boundary that blocks s3:DeleteObject to the Contractors group', 'A permissions boundary can be set only for a user or a role, not for a group.'],
    ],
    slot: 1,
    evidence: [
      'iam-policy-eval-basics|An explicit deny in any of the policies overrides the allow.',
      'iam-managed-inline|You cannot change the permissions defined in AWS managed policies.',
      'iam-policies|If multiple policies apply to a request, AWS applies a logical OR across all of those policies when evaluating them.',
      'iam-policies|Use a managed policy as the permissions boundary for an IAM entity (user or role).',
    ],
  }),
  mr({
    id: 'identity-keep-013',
    building: 'identity-keep',
    bullets: ['1.1-S2'],
    d: 2,
    stem: 'A company has a Developers team and a QA team, and some engineers work on both. The company wants to manage the permissions of each team in one place with the LEAST effort. Which TWO actions meet these requirements? (Choose two.)',
    correct: [
      ['Create one IAM user group per team and attach each team\'s permissions policy to its group', 'Permissions are specified once on the group and apply to every user in it.'],
      ['Add the engineers who work on both teams to both groups', 'A user can belong to multiple user groups, so these engineers receive the permissions of each team.'],
    ],
    wrong: [
      ['Create an Everyone group and nest the Developers and QA groups inside it', 'User groups can\'t be nested; they can contain only users, not other IAM groups.'],
      ['Attach the same inline policy to every engineer individually', 'An inline policy keeps a strict one-to-one relationship with an identity, so each change must be repeated per engineer.'],
      ['Create one shared IAM user for each team and give out its credentials', 'A shared user removes individual identities and does not manage permissions per engineer.'],
    ],
    slots: [2, 4],
    evidence: [
      'iam-groups|You can attach an identity-based policy to a user group so that all of the users in the user group receive the policy\'s permissions.',
      'iam-groups|A user group can contain many users, and a user can belong to multiple user groups.',
      'iam-groups|User groups can\'t be nested; they can contain only users, not other IAM groups.',
    ],
  }),
  mr({
    id: 'identity-keep-014',
    building: 'identity-keep',
    bullets: ['1.1-S1'],
    d: 3,
    stem: "A standalone AWS account uses the CTO's personal email address for the root user, and the CTO alone holds the root password and the only MFA device. The company wants to reduce delays when AWS contacts the account owner and to make sure no single person can sign in as the root user. Which TWO actions meet these requirements MOST securely? (Choose two.)",
    correct: [
      ['Change the root email address to one that the business manages and that forwards to a group of users', 'A business-managed group address avoids delays if individuals are away or have left the company.'],
      ['Give the root password and the MFA device to two different groups of administrators', 'With multi-person approval, no one person can access both the password and the MFA.'],
    ],
    wrong: [
      ['Create access keys for the root user and share them with the security team', 'AWS strongly recommends not creating access keys for the root user, and sharing them widens exposure.'],
      ['Give every member of the IT staff the root password and a copy of the MFA device', 'It lets any single person sign in as the root user, which the company wants to prevent.'],
      ['Remove MFA from the root user once the password is stored in a password manager', 'MFA is a required second factor for the root user, so removing it weakens protection.'],
    ],
    slots: [0, 2],
    evidence: [
      'iam-root-best-practices|Use an email address that is managed by your business and forwards received messages directly to a group of users.',
      'iam-root-best-practices|Consider using multi-person approval to make sure that no one person can access both MFA and password for the root user.',
      'iam-mfa|MFA is enforced for all account types for their root user.',
    ],
  }),
  mc({
    id: 'identity-keep-015',
    building: 'identity-keep',
    bullets: ['1.1-S1'],
    d: 2,
    stem: 'A company wants its security team to get an email each time the AWS account root user is used. The company wants an alert at the time of use rather than a periodic report, with the LEAST ongoing effort. Which solution meets these requirements?',
    correct: ['Create an Amazon EventBridge rule for root user activity that publishes to an Amazon SNS topic', 'The rule reacts when the root user is used, and the SNS topic notifies the team.'],
    wrong: [
      ['Download the IAM credential report every week and have the team review the root user row', 'Reviewing a report is a manual, periodic task and not an alert at the time of use.'],
      ['Create an AWS Config rule that checks whether the root user has MFA enabled and flags drift', 'Config rules monitor root user compliance, such as MFA, and do not notify on each use of the root user.'],
      ['Turn on the AWS Trusted Advisor security check for MFA on the root account and review it daily', 'The check shows whether MFA is enabled and does not alert when the root user signs in or acts.'],
    ],
    slot: 2,
    evidence: [
      'iam-root-best-practices|If you want to set up notifications to alert you of approved root user actions, you can leverage Amazon EventBridge along with Amazon SNS to write an EventBridge rule to track root user usage for the specific action and notify you using an Amazon SNS topic.',
      'iam-root-best-practices|AWS Config provides rules to monitor compliance with root user best practices.',
      "iam-root-best-practices|Trusted Advisor provides a security check so you know if MFA isn't enabled on the root user account.",
    ],
  }),
  mc({
    id: 'identity-keep-016',
    building: 'identity-keep',
    bullets: ['1.1-K4'],
    d: 2,
    tags: ['placement-eligible'],
    stem: "A company's order-processing AWS Lambda function reads and writes items in a single Amazon DynamoDB table named Orders. A developer wants to attach the AWS managed policy AmazonDynamoDBFullAccess to the function's execution role because it is fast to set up. Which approach follows AWS guidance MOST closely?",
    correct: ['Attach a customer managed policy that allows only the needed actions on the Orders table', 'It reduces permissions to what the function needs on the specific table, as AWS recommends over broad managed policies.'],
    wrong: [
      ['Attach AmazonDynamoDBFullAccess, because AWS managed policies already provide least privilege', 'AWS managed policies might not grant least privilege because they are available for use by all AWS customers.'],
      ['Attach AdministratorAccess so that the function never fails with an access denied error', 'It grants every permission in the account, which is the opposite of granting only what the function needs.'],
      ["Store an IAM user's table-scoped access keys in the function's environment variables", 'It uses long-term keys, whereas Lambda supplies temporary credentials through the execution role.'],
    ],
    slot: 3,
    evidence: [
      'iam-best-practices|Keep in mind that AWS managed policies might not grant least-privilege permissions for your specific use cases because they are available for use by all AWS customers.',
      'iam-best-practices|As a result, we recommend that you reduce permissions further by defining customer managed policies that are specific to your use cases.',
    ],
  }),
  mc({
    id: 'identity-keep-017',
    building: 'identity-keep',
    bullets: ['1.1-K4'],
    d: 3,
    tags: ['placement-eligible'],
    stem: 'An AWS Lambda function writes to an Amazon DynamoDB table by using the access keys of an IAM user. The keys sit in encrypted environment variables and are rotated every quarter. A security review requires that the function use no long-term credentials, with the LEAST operational overhead from now on. Which solution meets these requirements?',
    correct: ["Remove the keys and grant the table permissions to the function's execution role", 'Lambda assumes the execution role automatically and supplies temporary credentials, so nothing is stored or rotated.'],
    wrong: [
      ['Store the access keys in AWS Secrets Manager and enable automatic rotation', 'The keys remain long-term credentials, and rotation adds a service to configure and operate.'],
      ['Make the function code call sts:AssumeRole on its own execution role at start-up', 'Lambda already assumes the role, and AWS says to avoid manually calling sts:AssumeRole in function code.'],
      ['Encrypt the environment variables with a customer managed AWS KMS key', 'Encryption protects the stored keys, but they are still long-term credentials that must be rotated.'],
    ],
    slot: 0,
    evidence: [
      'lambda-exec-role|Lambda automatically assumes your execution role when you invoke your function.',
      'lambda-exec-role|You should avoid manually calling sts:AssumeRole to assume the execution role in your function code.',
      'iam-best-practices|Applications written using an AWS SDK will discover and use these temporary credentials to access AWS resources, and there is no need to distribute long lived credentials for an IAM user to your workloads running on AWS.',
    ],
  }),
  mc({
    id: 'identity-keep-018',
    building: 'identity-keep',
    bullets: ['1.1-S2'],
    d: 2,
    tags: ['placement-eligible'],
    stem: "A developer creates an IAM role whose permissions policy allows dynamodb:PutItem on the Orders table, and selects it as the execution role of a new AWS Lambda function. The function cannot use the role. The role's trust policy names the Amazon EC2 service as the trusted principal. Which change fixes the problem with the LEAST effort?",
    correct: ['Update the trust policy so that it names the Lambda service principal as a trusted service', 'The trust policy decides who can assume the role, and Lambda needs lambda.amazonaws.com listed to assume it.'],
    wrong: [
      ["Add sts:AssumeRole to the role's permissions policy", 'The permissions policy says what the role can do once assumed, not who is allowed to assume it.'],
      ['Create access keys for the role and add them to the function configuration', 'A role has no standard long-term credentials such as access keys; it provides temporary credentials when assumed.'],
      ['Attach the AWSLambdaBasicExecutionRole managed policy to the role', 'That policy gives basic permissions to log to Amazon CloudWatch Logs and does not change who can assume the role.'],
    ],
    slot: 1,
    evidence: [
      "lambda-exec-role|In order for Lambda to properly assume your execution role, the role's trust policy must specify the Lambda service principal (lambda.amazonaws.com) as a trusted service.",
      'iam-roles|The trust policy specifies which trusted account members are allowed to assume the role.',
      'lambda-exec-role|Specifically, this execution role includes the AWSLambdaBasicExecutionRole managed policy, which gives your function basic permissions to log events to Amazon CloudWatch Logs.',
    ],
  }),
  mr({
    id: 'identity-keep-019',
    building: 'identity-keep',
    bullets: ['1.1-K4'],
    d: 3,
    tags: ['placement-eligible'],
    stem: "An AWS Lambda function's execution role has broad Amazon DynamoDB and Amazon S3 permissions that the team granted during development. The function moves to production next week. Security requires permissions that match what the function actually uses and name specific resources, with the LEAST manual analysis. Which TWO actions meet these requirements? (Choose two.)",
    correct: [
      ["Use IAM Access Analyzer to generate a policy template from the role's AWS CloudTrail activity", 'It reviews the CloudTrail logs over the chosen date range and produces a template with only the permissions used.'],
      ['Create a managed policy from the tested template and attach it to the role in place of the broad permissions', 'The fine-grained policy replaces the broad permissions, so the role keeps only what the function needs.'],
    ],
    wrong: [
      ['Keep the broad permissions and create an alarm for unusual API calls from the role', 'It only detects problems later and does not reduce the permissions of the role.'],
      ['Attach a permissions boundary that allows dynamodb:* and s3:*', 'A boundary that matches the broad permissions does not reduce what the role is allowed to do.'],
      ["Create an IAM user with access keys that cover the function's observed calls and place them in the function", 'It adds long-term keys, whereas the function should keep using its execution role.'],
    ],
    slots: [1, 3],
    evidence: [
      'lambda-exec-role|IAM Access Analyzer reviews your AWS CloudTrail logs over the date range that you specify and generates a policy template with only the permissions that the function used during that time.',
      'lambda-exec-role|You can use the template to create a managed policy with fine-grained permissions, and then attach it to the IAM role.',
      'lambda-exec-role|Before publishing your function in the production environment, as a best practice, adjust the policy to include only the required permissions.',
    ],
  }),
  mc({
    id: 'identity-keep-020',
    building: 'identity-keep',
    bullets: ['1.1-S2'],
    d: 2,
    tags: ['placement-eligible'],
    stem: 'A company runs 12 AWS Lambda functions, each with its own execution role, and all of them need the same read access to one Amazon DynamoDB table. The security team wants to change that access in a single place with the LEAST operational overhead. Which solution meets this requirement?',
    correct: ['Create one customer managed policy and attach it to all 12 execution roles', 'A change to a managed policy is applied to every identity it is attached to.'],
    wrong: [
      ['Add an inline policy with the same permissions to each of the 12 roles', 'Each role would hold its own copy, so a change has to be made 12 times.'],
      ['Put the 12 execution roles in an IAM user group and attach the policy to the group', 'User groups can contain only users, so they cannot hold roles.'],
      ['Attach the AWS managed AmazonDynamoDBReadOnlyAccess policy to each role', 'AWS managed policies cannot be changed and cover read access to more than the one table.'],
    ],
    slot: 2,
    evidence: [
      'iam-managed-inline|If a policy could apply to more than one entity, it’s better to use a managed policy.',
      'iam-managed-inline|When you update permissions in the policy, the changes are applied to all principal entities that the policy is attached to.',
      'iam-managed-inline|Notice that two roles include the same policy (the DynamoDB-books-app policy), but they are not sharing a single policy.',
      'iam-groups|User groups can\'t be nested; they can contain only users, not other IAM groups.',
    ],
  }),
  mc({
    id: 'identity-keep-021',
    building: 'identity-keep',
    bullets: ['1.1-K4'],
    d: 3,
    tags: ['placement-eligible'],
    stem: 'Two AWS Lambda functions share one execution role that allows dynamodb:* on all tables. The ingestion function only writes items to the Orders table, and the reporting function only reads items from the Reports table. Security wants least privilege and a limited impact if either function is compromised. Which solution BEST meets these requirements?',
    correct: ['Give each function its own execution role with a policy that allows only its actions on its own table', 'Each role grants only the actions that function needs on the specific resource it uses.'],
    wrong: [
      ['Keep the shared role and add Deny statements for the actions each function should not use', 'The shared role still holds broad allows, and one role cannot express different needs for each function.'],
      ['Keep the shared role and attach a permissions boundary that allows dynamodb:*', 'A boundary only caps permissions, and one that allows dynamodb:* removes nothing from the role.'],
      ['Attach AmazonDynamoDBFullAccess to the ingestion role and the read-only managed policy to the reporting role', 'Both managed policies apply to all tables, so each function can reach tables it does not use.'],
    ],
    slot: 3,
    evidence: [
      'iam-best-practices|You do this by defining the actions that can be taken on specific resources under specific conditions, also known as least-privilege permissions.',
      'iam-best-practices|Keep in mind that AWS managed policies might not grant least-privilege permissions for your specific use cases because they are available for use by all AWS customers.',
      'iam-boundaries|A permissions boundary is an advanced feature for using a managed policy to set the maximum permissions that an identity-based policy can grant to an IAM entity.',
    ],
  }),
  mc({
    id: 'identity-keep-022',
    building: 'identity-keep',
    bullets: ['1.1-S2', '1.1-K4'],
    d: 3,
    tags: ['placement-eligible', 'trap:scp-boundary-identity'],
    stem: 'A platform team wants application teams to create their own IAM roles for AWS Lambda functions without waiting for a ticket. No role that a team creates may ever have more than Amazon DynamoDB, Amazon S3 and Amazon CloudWatch Logs permissions, even if a developer writes a broad policy. The same account also runs workloads that need other services. Which solution meets these requirements with the LEAST platform team involvement?',
    correct: ['Let developers create the roles and use a permissions boundary that allows only those three services as the maximum', 'The boundary sets the maximum permissions that are delegated, whatever identity-based policies the developers write.'],
    wrong: [
      ['Attach a service control policy that allows only those three services to the account', 'It would limit every principal in the account, including the workloads that need other services.'],
      ['Give developers full IAM permissions and review each new role once a week', 'It allows over-broad roles to exist until a review catches them, and it adds manual platform work.'],
      ['Have the platform team create every role on request with a narrow policy', 'It meets the limit but keeps the platform team in the loop for every role, which the teams want to avoid.'],
    ],
    slot: 0,
    evidence: [
      'iam-best-practices|When you delegate permissions to others, use permissions boundaries to set the maximum permissions that you delegate.',
      'iam-best-practices|For example, you could allow developers to create and manage roles for their workloads.',
      'iam-policies|The SCP limits permissions for principals in member accounts, including each AWS account root user.',
    ],
  }),
  mc({
    id: 'identity-keep-023',
    building: 'identity-keep',
    bullets: ['1.1-S2'],
    d: 3,
    tags: ['placement-eligible', 'trap:scp-boundary-identity'],
    stem: 'An AWS Lambda execution role has an identity-based policy that allows dynamodb:PutItem on the Orders table and logs:*. Security attached a permissions boundary to the role that allows only s3:* and logs:*. The function now fails with an access denied error on PutItem. What is the MOST appropriate fix that keeps the boundary in place?',
    correct: ['Add dynamodb:PutItem on the Orders table to the permissions boundary policy', 'The effective permissions are the intersection of the identity-based policy and the boundary, so both must allow the action.'],
    wrong: [
      ['Attach a second identity-based policy that allows dynamodb:PutItem to the role', 'Identity-based policies cannot exceed the boundary, so the boundary still blocks the action.'],
      ['Add the role ARN as the principal in a resource-based policy on the table', 'When a role ARN is the principal, an explicit allow in the permissions boundary is still required.'],
      ['Change the role trust policy to name the Lambda service principal again', 'The trust policy decides who can assume the role and does not affect what the role may do.'],
    ],
    slot: 1,
    evidence: [
      'iam-boundaries|An entity\'s permissions boundary allows it to perform only the actions that are allowed by both its identity-based policies and its permissions boundaries.',
      'iam-policies|However, if you specify a role ARN in the principal element of a resource-based policy, an explicit allow in the permission boundary is required.',
      'iam-roles|The trust policy specifies which trusted account members are allowed to assume the role.',
    ],
  }),
  mc({
    id: 'identity-keep-024',
    building: 'identity-keep',
    bullets: ['1.1-K4'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A company has accumulated hundreds of IAM users, roles and policies over several years. The security team wants to identify permissions and credentials that are no longer used so it can remove them, with the LEAST effort. What should the team use?',
    correct: ['IAM last accessed information', 'It helps identify the users, roles, permissions, policies and credentials that are no longer needed so they can be removed.'],
    wrong: [
      ['AWS CloudTrail Event history searched by hand for each identity', 'Event history covers only recent management events, and searching it identity by identity is slow manual work.'],
      ['Amazon Inspector scans of the account', 'Amazon Inspector looks for software vulnerabilities and does not show which permissions are unused.'],
      ['AWS Config rules that check the policy version of each role', 'A rule evaluates a configuration setting and does not report which permissions have been used.'],
    ],
    slot: 2,
    evidence: [
      'iam-best-practices|IAM provides last accessed information to help you identify the users, roles, permissions, policies, and credentials that you no longer need so that you can remove them.',
      'iam-best-practices|You can also use this information to refine your IAM policies to better adhere to least-privilege permissions.',
    ],
  }),
  mc({
    id: 'identity-keep-025',
    building: 'identity-keep',
    bullets: ['1.1-S2'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A company wants its database administrators to have permissions for their job function, and wants AWS to keep those permissions current as new services and API operations appear. The company wants the LEAST ongoing maintenance. Which solution meets these requirements?',
    correct: ['Attach an AWS managed policy for the job function to the administrators', 'AWS maintains and updates job function policies as new services and API operations are introduced.'],
    wrong: [
      ['Copy an AWS managed policy into a customer managed policy and attach that', 'The copy is maintained by the company, so it must be updated by hand as new services appear.'],
      ['Write an inline policy for each database administrator', 'Each inline policy belongs to one identity and must be maintained by the company.'],
      ['Attach the AdministratorAccess policy to the database administrators', 'It gives full access to every service and is recommended only for the account administrator.'],
    ],
    slot: 3,
    evidence: [
      'iam-managed-inline|One key advantage of using job function policies is that they are maintained and updated by AWS as new services and API operations are introduced.',
      'iam-managed-inline|We recommend that you use this policy only for the account administrator.',
    ],
  }),
  mc({
    id: 'identity-keep-026',
    building: 'identity-keep',
    bullets: ['1.1-S1'],
    d: 3,
    tags: ['mock-reserve'],
    stem: 'A company manages 60 member accounts with AWS Organizations. Each member account has root user credentials and an MFA device held by different people. Security wants member accounts to be unable to sign in as the root user at all, while root-only tasks can still be done when needed, with the LEAST ongoing effort. Which solution meets these requirements?',
    correct: ['Centralize root access and remove the root user credentials from the member accounts', 'Member accounts then cannot sign in as root, and privileged tasks are performed centrally when required.'],
    wrong: [
      ['Register a second MFA device for the root user of each member account', 'The root credentials would still exist in all 60 accounts, so sign-in remains possible.'],
      ['Apply a service control policy that denies root user actions in the member accounts', 'The credentials still exist, and root-only actions would be blocked as well.'],
      ['Create access keys for the root user of each member account and store them centrally', 'AWS strongly recommends not creating access keys for the root user, and the credentials would still exist.'],
    ],
    slot: 0,
    evidence: [
      'iam-root-best-practices|For multiple AWS accounts managed through AWS Organizations, we recommend removing root user credentials from member accounts to help prevent unauthorized use.',
      'iam-root-best-practices|Member accounts can\'t sign in to their root user or perform password recovery for their root user.',
      'iam-root-user|Perform privileged tasks that require root user credentials Some tasks can only be performed when you sign in as the root user of an account.',
    ],
  }),
  mr({
    id: 'identity-keep-027',
    building: 'identity-keep',
    bullets: ['1.1-S1'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A company has a standalone AWS account that is not part of AWS Organizations. Which TWO tasks can be done only by signing in as the root user? (Choose two.) Select the BEST answers.',
    correct: [
      ['Close the AWS account', 'Standalone accounts require root credentials to close the account.'],
      ['Restore the permissions of the only IAM administrator after the administrator revoked them by mistake', 'The root user can edit policies to restore IAM user permissions.'],
    ],
    wrong: [
      ['Update the alternate contacts of the account', 'Alternate contacts do not require root user credentials.'],
      ['Launch an Amazon EC2 instance in the account', 'An IAM identity with the right permissions can launch instances without the root user.'],
      ['Create a new IAM user with a console password', 'An administrator IAM identity can create IAM users, so the root user is not required.'],
    ],
    slots: [1, 4],
    evidence: [
      'iam-root-user|Standalone AWS accounts that are not part of AWS Organizations require root credentials to close the account.',
      'iam-root-user|If the only IAM administrator accidentally revokes their own permissions, you can sign in as the root user to edit policies and restore those permissions.',
      "iam-root-user|Other account settings, such as account name, contact information, alternate contacts, payment currency preference, and AWS Regions, don't require root user credentials.",
    ],
  }),
];

export default questions;
