import type { Question } from '../../../src/content/types.ts';
import { mc, mr } from '../helpers.ts';

const questions: Question[] = [
  mc({
    id: 'key-vault-001',
    building: 'key-vault',
    bullets: ['1.3-K4'],
    d: 1,
    stem: 'A company encrypts data in several AWS services with keys that it controls. The security team must have full control over each key\'s lifecycle and permissions, and must be able to audit every use of the keys in AWS CloudTrail logs. Which key option BEST meets these requirements?',
    correct: ['Customer managed keys that the team creates in AWS KMS', 'Customer managed keys give full control over lifecycle and usage, and their use can be audited in CloudTrail logs.'],
    wrong: [
      ['AWS managed keys that integrated services create in the account', 'The team cannot change the properties of AWS managed keys, rotate them, change their key policies, or schedule them for deletion, so it lacks lifecycle control.'],
      ['AWS owned keys that each service manages in its own accounts', 'AWS owned keys are controlled by the service and not viewable by the customer, who cannot audit activity on them or delete them.'],
      ['Amazon S3 managed keys (SSE-S3) that S3 applies to every new object', 'SSE-S3 gives no separate key to view, no control policy to edit and no key usage to follow in CloudTrail.'],
    ],
    slot: 0,
    evidence: [
      'kms-concepts|Customer managed keys are recommended for customers who want full control over the lifecycle and usage of their keys.',
      'kms-concepts|You can use your customer managed key in cryptographic operations and audit usage in AWS CloudTrail logs.',
      'kms-concepts|However, you cannot change any properties of AWS managed keys, rotate them, change their key policies, or schedule them for deletion.',
      'kms-concepts|you cannot change their policies, you cannot audit activities on these keys, and you cannot delete them.',
    ],
  }),
  mc({
    id: 'key-vault-002',
    building: 'key-vault',
    bullets: ['1.3-K4'],
    d: 1,
    tags: ['trap:kms-vs-cloudhsm'],
    stem: 'A payments company must keep its encryption keys in single-tenant hardware security modules and have full control of the cryptographic algorithms and keys it uses. Which service BEST meets these requirements?',
    correct: ['AWS CloudHSM', 'CloudHSM offers single-tenant, standards-compliant HSMs and gives full control of the algorithms and keys.'],
    wrong: [
      ['AWS KMS customer managed keys in the standard key store', 'The standard key store is a tenant-agnostic fleet of HSMs, not single-tenant HSMs that the company controls.'],
      ['AWS Secrets Manager with automatic rotation turned on', 'Secrets Manager manages secrets such as credentials and does not provide HSMs or control over algorithms.'],
      ['AWS Certificate Manager with private certificates', 'ACM issues and renews certificates and does not provide single-tenant HSMs for general key storage.'],
    ],
    slot: 1,
    evidence: [
      'cloudhsm|We offer HSMs that are standards-compliant, single-tenant',
      'cloudhsm|AWS CloudHSM gives you full control of the algorithms and keys you use.',
      'kms-key-stores|This HSM type can be thought of as a tenant-agnostic fleet of HSMs',
    ],
  }),
  mc({
    id: 'key-vault-003',
    building: 'key-vault',
    bullets: ['1.3-K4'],
    d: 2,
    tags: ['trap:kms-vs-cloudhsm'],
    stem: 'A company must encrypt data in Amazon S3 and Amazon EBS and show auditors that only named IAM roles can use the encryption keys. The company has no requirement for single-tenant hardware or for key material to be held outside AWS. Which approach meets these requirements with the LEAST operational overhead?',
    correct: ['Customer managed KMS keys in the standard key store, with key policies that name the permitted roles', 'The key policy controls who can use the key, which is sufficient for many compliance requirements, and the standard key store has the lowest operational burden.'],
    wrong: [
      ['KMS keys in a custom key store backed by an AWS CloudHSM cluster that the company builds and operates', 'This adds cluster operations, cost and reduced performance, and nothing in the requirements calls for a single-tenant HSM.'],
      ['KMS keys in an external key store that forwards requests to a key manager outside the AWS Cloud', 'This is only for an explicit requirement to keep key material outside AWS, and it adds an XKS proxy to operate.'],
      ['An AWS CloudHSM cluster with application code that encrypts each file before upload', 'The company would operate HSMs and write encryption code, when the AWS services can use KMS keys directly.'],
    ],
    slot: 2,
    evidence: [
      'kms-key-stores|For many compliance requirements, the control you have over key access through the KMS key policy is sufficient.',
      'kms-key-stores|Consider creating a custom key store only when your organization has regulatory requirements that explicitly mandate key material protection in a single-tenant HSM or in an HSM that you control outside of AWS.',
      'kms-key-stores|lets you take full advantage of the scalability, availability, and durability of AWS KMS with the lowest operational burden and cost of the AWS key stores.',
    ],
  }),
  mc({
    id: 'key-vault-004',
    building: 'key-vault',
    bullets: ['1.3-K4'],
    d: 2,
    tags: ['trap:kms-vs-cloudhsm'],
    stem: 'A healthcare company\'s regulator requires that the key material protecting its Amazon EBS volumes sits in a single-tenant HSM that the company owns and manages in AWS. The company wants Amazon EBS to keep using AWS KMS keys. Which solution BEST meets these requirements?',
    correct: ['Create a KMS custom key store backed by AWS CloudHSM and create the keys in it', 'An AWS CloudHSM key store is backed by a dedicated, customer-owned cluster, and EBS volume encryption is a suitable low-throughput use.'],
    wrong: [
      ['Create customer managed keys in the standard key store and turn on automatic key rotation', 'The standard key store uses shared AWS KMS HSMs, so the key material is not in a single-tenant HSM that the company owns.'],
      ['Create a KMS external key store that connects to a key manager through an XKS proxy', 'An external key store keeps key material in a system outside the AWS Cloud, not in an HSM that the company manages in AWS.'],
      ['Use the AWS managed key for Amazon EBS and restrict who can use it with a key policy', 'AWS managed keys live in the standard key store, and the company cannot change their key policies.'],
    ],
    slot: 3,
    evidence: [
      'kms-key-stores|There are two types: AWS CloudHSM key stores, backed by a dedicated, customer-owned AWS CloudHSM cluster, and external key stores, backed by an HSM or key management system outside the AWS Cloud.',
      'kms-key-stores|Consider creating a custom key store only when your organization has regulatory requirements that explicitly mandate key material protection in a single-tenant HSM or in an HSM that you control outside of AWS.',
      'kms-key-stores|They are suitable only for low transactions per second (TPS) workloads such as Amazon Elastic Block Store volume encryption',
    ],
  }),
  mc({
    id: 'key-vault-005',
    building: 'key-vault',
    bullets: ['1.3-K4'],
    d: 3,
    tags: ['trap:kms-vs-cloudhsm'],
    stem: 'A company\'s contract says the key material that protects a customer\'s data must be generated and held in a key management system in the company\'s own data center, outside AWS. The workload only encrypts a few Amazon EBS volumes, so throughput is low. Which solution BEST meets this requirement?',
    correct: ['Create a KMS external key store that uses an XKS proxy to reach the on-premises key manager', 'An external key store keeps the key material in a key management system outside AWS and is suitable for low-throughput uses such as EBS.'],
    wrong: [
      ['Create a KMS custom key store backed by an AWS CloudHSM cluster that runs in the company\'s own VPC', 'AWS CloudHSM clusters are hosted within AWS, so the key material stays inside AWS.'],
      ['Import the on-premises key material into a customer managed key in the standard key store', 'Imported key material is held by AWS KMS in the standard key store and is therefore not kept outside AWS.'],
      ['Create customer managed keys in the standard key store and restrict them with key policies', 'The key material is generated and protected inside AWS KMS HSMs, not in the company\'s data center.'],
    ],
    slot: 0,
    evidence: [
      'kms-key-stores|You can configure AWS KMS to use an external key store (XKS), where key material is generated, stored and used in a key management system outside AWS.',
      'kms-key-stores|Consider an external key store only when you have an explicit and unchangeable requirement to keep key material outside AWS.',
      'kms-key-stores|Although AWS CloudHSM clusters are hosted within AWS, they provide single-tenant HSM instances that are owned and managed by you.',
    ],
  }),
  mc({
    id: 'key-vault-006',
    building: 'key-vault',
    bullets: ['1.3-K4'],
    d: 2,
    stem: 'A company generates its encryption keys in its own key ceremony system and wants AWS KMS to use that key material for data in Amazon S3. Policy also requires the ability to remove the key material from AWS on a defined schedule. The company does not want to operate any HSMs. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Create a KMS key without key material, then import the material with an expiration time', 'Importing key material lets the company control how it is generated and when it is removed, with the key still in the standard key store.'],
    wrong: [
      ['Create a KMS key in a custom key store backed by AWS CloudHSM and generate the material in the cluster', 'The key material would be generated in the cluster rather than in the key ceremony system, and the company would operate HSMs.'],
      ['Use the AWS managed key for Amazon S3 and delete and re-create it on the required schedule', 'The company cannot manage the lifecycle of an AWS managed key, supply its own material, or schedule it for deletion.'],
      ['Use the default SSE-S3 encryption and rotate the Amazon S3 managed keys with a custom script', 'SSE-S3 uses keys that Amazon S3 manages, so the company cannot supply its own key material or control its removal.'],
    ],
    slot: 1,
    evidence: [
      'kms-key-stores|Importing key material is useful when you need to generate keys using a specific system or source of entropy, retain a backup copy outside AWS, or remove key material on a defined schedule.',
      'kms-key-stores|You can set an expiration time on import or call DeleteImportedKeyMaterial to revoke access immediately.',
    ],
  }),
  mr({
    id: 'key-vault-007',
    building: 'key-vault',
    bullets: ['1.3-K4'],
    d: 2,
    tags: ['trap:kms-vs-cloudhsm'],
    stem: 'A company runs a payment signing application against an AWS CloudHSM cluster because the application needs single-tenant HSMs. The cluster must stay available if one Availability Zone fails, and throughput must grow as load increases. Which TWO actions meet these requirements? (Choose two.)',
    correct: [
      ['Place the HSMs of the cluster in at least two Availability Zones', 'Spreading the HSMs of a cluster across Availability Zones provides redundancy and high availability.'],
      ['Add more HSMs to the cluster as load grows', 'Adding more HSMs to a cluster provides higher performance.'],
    ],
    wrong: [
      ['Create a second cluster in the same Availability Zone as the first one', 'Both clusters would fail together if that Availability Zone failed, so availability is not improved.'],
      ['Create IAM roles for the HSM users so that AWS recovers the cluster after an outage', 'The company controls its own HSM user management outside of IAM roles, and IAM roles do not add availability.'],
      ['Replace the cluster with AWS managed KMS keys that provide the same single-tenant HSMs', 'AWS managed keys are in the standard key store and do not provide single-tenant HSMs under the company\'s control.'],
    ],
    slots: [1, 3],
    evidence: [
      'cloudhsm-clusters|Adding more HSMs to a cluster provides higher performance. Spreading clusters across Availability Zones provides redundancy and high availability.',
      'cloudhsm|Because your data plane is end-to-end (E2E) encrypted and not visible to AWS, you control your own user management (outside of IAM roles).',
    ],
  }),
  mc({
    id: 'key-vault-008',
    building: 'key-vault',
    bullets: ['1.3-K4', '1.3-S2'],
    d: 3,
    stem: 'A company encrypts its Amazon EBS volumes with the default AWS managed key for EBS. It must now share snapshots of those volumes with a partner AWS account that will restore them. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Copy each snapshot with a customer managed key that allows the partner account, then share the copy', 'A copy can be encrypted under a different KMS key, and a customer managed key can be opened to the partner account.'],
    wrong: [
      ['Share the existing snapshots with the partner account and add the partner account to the AWS managed key policy', 'The company cannot change the key policy of an AWS managed key, and resources encrypted under one cannot be shared with other accounts.'],
      ['Change the KMS key of each existing snapshot to a customer managed key and then share the snapshots', 'The KMS key associated with an existing snapshot or volume cannot be changed; only a copy can use a different key.'],
      ['Make each snapshot public so that the partner account can copy it', 'Public snapshots of encrypted volumes are not supported.'],
    ],
    slot: 2,
    evidence: [
      'kms-concepts|You cannot share resources encrypted under an AWS managed key with other accounts.',
      'ebs-encryption|You cannot change the KMS key that is associated with an existing snapshot or volume. However, you can associate a different KMS key during a snapshot copy operation so that the resulting copied snapshot is encrypted by the new KMS key.',
      'ebs-encryption|Public snapshots of encrypted volumes are not supported, but you can share an encrypted snapshot with specific accounts.',
    ],
  }),
  mr({
    id: 'key-vault-009',
    building: 'key-vault',
    bullets: ['1.3-K4'],
    d: 2,
    stem: 'A security team compares the customer managed keys it creates with the AWS managed keys that integrated services create in its account. Which TWO actions can the team perform ONLY on the customer managed keys? (Choose two.)',
    correct: [
      ['Change the key policy of the key', 'The team controls the key policy of a customer managed key but cannot change the key policy of an AWS managed key.'],
      ['Schedule the key for deletion', 'The team can schedule deletion of a customer managed key, but not of an AWS managed key.'],
    ],
    wrong: [
      ['View the key policy of the key', 'The team has permission to view the key policies of AWS managed keys as well.'],
      ['Audit the use of the key in AWS CloudTrail logs', 'The team can audit the use of AWS managed keys in CloudTrail logs as well.'],
      ['See the key listed in the AWS KMS console', 'AWS managed keys appear in the console on their own page, so this is not exclusive to customer managed keys.'],
    ],
    slots: [2, 4],
    evidence: [
      'kms-concepts|You have permission to view the AWS managed keys in your account, view their key policies, and audit their use in AWS CloudTrail logs.',
      'kms-concepts|However, you cannot change any properties of AWS managed keys, rotate them, change their key policies, or schedule them for deletion.',
      'kms-concepts|AWS managed keys appear on the AWS managed keys page of the AWS Management Console for AWS KMS.',
    ],
  }),
  mc({
    id: 'key-vault-010',
    building: 'key-vault',
    bullets: ['1.3-S2'],
    d: 1,
    tags: ['trap:sse-s3-kms-c'],
    stem: 'A company stores documents in a newly created Amazon S3 bucket. Policy says all objects must be encrypted at rest, and there is no requirement to control the keys. Which action meets this requirement with the LEAST effort?',
    correct: ['Do nothing, because SSE-S3 already encrypts every new object', 'Every new object upload is encrypted by default with SSE-S3, at no additional fee.'],
    wrong: [
      ['Enable SSE-KMS on the bucket with a new customer managed key', 'This adds a key to manage and an additional cost, when the requirement is already met.'],
      ['Configure SSE-C and send a key with every upload request', 'The applications would have to supply and track keys, which is more work than the default.'],
      ['Encrypt each file in the application before it is uploaded', 'This requires custom code and key handling for a requirement that is already met.'],
    ],
    slot: 3,
    evidence: [
      's3-sse-s3|All new object uploads to Amazon S3 buckets are encrypted by default with server-side encryption with Amazon S3 managed keys (SSE-S3).',
      's3-sse-s3|There are no additional fees for using server-side encryption with Amazon S3 managed keys (SSE-S3).',
    ],
  }),
  mc({
    id: 'key-vault-011',
    building: 'key-vault',
    bullets: ['1.3-S2'],
    d: 2,
    tags: ['trap:sse-s3-kms-c'],
    stem: 'A company keeps records in an Amazon S3 bucket. Auditors require that a key policy names the roles that may use the encryption key, and that every use of the key is recorded in AWS CloudTrail. Which encryption option meets these requirements with the LEAST operational overhead?',
    correct: ['SSE-KMS with a customer managed KMS key', 'A customer managed key has a key policy the company edits, and its use is recorded in CloudTrail logs.'],
    wrong: [
      ['SSE-S3 default encryption on the bucket', 'SSE-S3 has no separate key or key policy for the company to edit, and key usage cannot be followed in CloudTrail.'],
      ['SSE-C with keys supplied on each upload and download', 'The company would manage and track the keys itself, and there is no key policy or KMS audit trail.'],
      ['SSE-KMS with the AWS managed key for Amazon S3', 'The company cannot change the key policy of an AWS managed key, so it cannot name the permitted roles.'],
    ],
    slot: 0,
    evidence: [
      's3-sse|With AWS KMS, you have more control over your keys. For example, you can view separate keys, edit control policies, and follow the keys in AWS CloudTrail.',
      's3-sse-kms|To audit the usage of your AWS KMS keys for your SSE-KMS encrypted data, you can use AWS CloudTrail logs.',
      'kms-concepts|However, you cannot change any properties of AWS managed keys, rotate them, change their key policies, or schedule them for deletion.',
    ],
  }),
  mc({
    id: 'key-vault-012',
    building: 'key-vault',
    bullets: ['1.3-S2'],
    d: 2,
    tags: ['trap:sse-s3-kms-c'],
    stem: 'A company stores hundreds of millions of objects in an Amazon S3 bucket that uses SSE-KMS. AWS KMS request charges are high because S3 calls AWS KMS for each object request. The company wants to lower these charges without changing its client applications. Which solution is the MOST cost-effective?',
    correct: ['Enable an S3 Bucket Key for SSE-KMS on the bucket', 'A bucket-level key reduces the request traffic from Amazon S3 to AWS KMS, and no client changes are needed.'],
    wrong: [
      ['Switch the bucket default encryption to dual-layer server-side encryption (DSSE-KMS)', 'S3 Bucket Keys are not supported for DSSE-KMS, so the request traffic to AWS KMS would not fall.'],
      ['Turn on automatic key rotation for the customer managed key', 'Rotating key material does not change how many requests S3 sends to AWS KMS.'],
      ['Create a separate customer managed key for each prefix in the bucket', 'S3 shares a bucket-level key only among objects encrypted by the same key, so more keys means more requests.'],
    ],
    slot: 1,
    evidence: [
      's3-bucket-keys|Using a bucket-level key for SSE-KMS can reduce AWS KMS request costs by up to 99 percent by decreasing the request traffic from Amazon S3 to AWS KMS.',
      "s3-bucket-keys|S3 Bucket Keys aren't supported for dual-layer server-side encryption with AWS Key Management Service (AWS KMS) keys (DSSE-KMS).",
      's3-bucket-keys|Amazon S3 will only share an S3 Bucket Key for objects encrypted by the same AWS KMS key.',
    ],
  }),
  mc({
    id: 'key-vault-013',
    building: 'key-vault',
    bullets: ['1.3-S2'],
    d: 2,
    stem: 'A company changes the default encryption of an Amazon S3 bucket from SSE-S3 to SSE-KMS. The bucket already holds tens of millions of objects, and compliance requires every existing object to be encrypted with the KMS key as well. Which solution meets this requirement with the LEAST operational overhead?',
    correct: ['Run an S3 Batch Operations Copy job that rewrites the objects into the same bucket', 'Batch Operations can copy existing objects back to the same bucket as SSE-KMS encrypted objects, at the scale of billions of objects.'],
    wrong: [
      ['Wait for Amazon S3 to re-encrypt the existing objects in the background with the new default', 'Changing the default encryption does not change the encryption type of the objects already in the bucket.'],
      ['Create an S3 Lifecycle rule that transitions the objects to S3 Standard-IA', 'A transition changes the storage class and does not re-encrypt the objects with the KMS key.'],
      ['Write a script that downloads each object and uploads it again with SSE-C headers', 'This takes custom code and would apply SSE-C, not SSE-KMS.'],
    ],
    slot: 2,
    evidence: [
      's3-sse|When you change the default encryption configuration of your bucket to SSE-KMS, the encryption type of the existing Amazon S3 objects in the bucket is not changed.',
      's3-sse|You can use the Copy objects action to copy existing objects, which writes them back to the same bucket as SSE-KMS encrypted objects.',
      's3-sse|A single Batch Operations job can perform the specified operation on billions of objects.',
    ],
  }),
  mr({
    id: 'key-vault-014',
    building: 'key-vault',
    bullets: ['1.3-S2'],
    d: 2,
    stem: 'A company will encrypt the objects in an Amazon S3 bucket in eu-west-1 with SSE-KMS and a customer managed key. Which TWO requirements must the KMS key meet? (Choose two.)',
    correct: [
      ['It is a symmetric encryption KMS key', 'Amazon S3 supports only symmetric encryption KMS keys.'],
      ['It is in the same AWS Region as the bucket', 'With SSE-KMS the KMS keys must be in the same Region as the bucket.'],
    ],
    wrong: [
      ['It is an asymmetric RSA KMS key used for encrypt and decrypt', 'Amazon S3 does not support asymmetric KMS keys for SSE-KMS.'],
      ['It is an HMAC KMS key', 'An HMAC key generates and verifies message authentication codes and is not a symmetric encryption key.'],
      ['It is in us-east-1 so that every bucket can share it', 'The key must be in the same Region as the bucket, which here is eu-west-1.'],
    ],
    slots: [0, 3],
    evidence: [
      's3-sse-kms|When you use SSE-KMS encryption with an S3 bucket, the AWS KMS keys must be in the same Region as the bucket.',
      's3-sse-kms|Amazon S3 supports only symmetric encryption KMS keys.',
    ],
  }),
  mc({
    id: 'key-vault-015',
    building: 'key-vault',
    bullets: ['1.3-S2'],
    d: 3,
    tags: ['trap:sse-s3-kms-c'],
    stem: 'A company must supply its own encryption key with each upload request so that Amazon S3 never stores the key. It created a new general purpose bucket, and uploads that specify SSE-C now fail with an HTTP 403 AccessDenied error. Which action resolves this with the LEAST change?',
    correct: ['Call PutBucketEncryption to set BlockedEncryptionTypes to NONE in the default encryption configuration of the bucket', 'SSE-C requests are rejected while SSE-C is blocked, and it must be deliberately enabled in the bucket\'s default encryption configuration.'],
    wrong: [
      ['Allow the application role to use a customer managed key in the key policy', 'SSE-C does not use a KMS key, so no key policy change addresses the rejected requests.'],
      ['Send the SSE-C headers over HTTP so the request is not inspected', 'Amazon S3 rejects any request made over HTTP when using SSE-C.'],
      ['Enable an S3 Bucket Key on the bucket so the key is cached', 'S3 Bucket Keys reduce AWS KMS requests for SSE-KMS and have no effect on SSE-C.'],
    ],
    slot: 3,
    evidence: [
      "s3-sse-c|If your workload requires SSE-C, you must explicitly enable it by setting BlockedEncryptionTypes to NONE in your bucket's default encryption configuration using the PutBucketEncryption API.",
      's3-sse-c|While SSE-C is blocked, any PutObject, CopyObject, PostObject, Multipart Upload, or replication request that specifies SSE-C encryption is rejected with an HTTP 403 AccessDenied error.',
      's3-sse-c|You must use HTTPS when specifying SSE-C headers on your requests.',
    ],
  }),
  mc({
    id: 'key-vault-016',
    building: 'key-vault',
    bullets: ['1.3-S2'],
    d: 1,
    tags: ['trap:sse-s3-kms-c'],
    stem: 'A company\'s compliance framework requires two independent layers of encryption to be applied to objects on the server side in Amazon S3. Which option BEST meets this requirement?',
    correct: ['Dual-layer server-side encryption with AWS KMS keys (DSSE-KMS)', 'DSSE-KMS applies two independent layers of AES-256 encryption to each object.'],
    wrong: [
      ['Server-side encryption with AWS KMS keys (SSE-KMS)', 'SSE-KMS applies a single layer of encryption.'],
      ['Server-side encryption with Amazon S3 managed keys (SSE-S3)', 'SSE-S3 applies a single layer of AES-256 encryption.'],
      ['Server-side encryption with customer-provided keys (SSE-C)', 'SSE-C applies one layer of encryption with the key the customer provides.'],
    ],
    slot: 0,
    evidence: [
      's3-sse|DSSE-KMS applies two independent layers of AES-256 encryption instead of one layer',
    ],
  }),
  mr({
    id: 'key-vault-017',
    building: 'key-vault',
    bullets: ['1.3-S2'],
    d: 2,
    stem: 'A company has an unencrypted Amazon EBS volume attached to a running database instance. It must end up with an encrypted volume that holds the same data. Which TWO steps are part of the solution? (Choose two.)',
    correct: [
      ['Create a snapshot of the unencrypted volume', 'The snapshot is the starting point, because an existing unencrypted volume cannot be encrypted directly.'],
      ['Create a new volume from the snapshot with encryption enabled', 'A new encrypted volume created from the snapshot holds the same data.'],
    ],
    wrong: [
      ['Turn on encryption for the existing volume in its settings', 'Existing unencrypted volumes cannot be encrypted directly.'],
      ['Attach a KMS key to the existing snapshot so it is encrypted in place', 'Existing unencrypted snapshots cannot be encrypted directly, and the KMS key of a snapshot cannot be changed.'],
      ['Modify the volume type to an encrypted volume type', 'Encryption is not a volume type, and changing the type does not encrypt the volume.'],
    ],
    slots: [1, 4],
    evidence: [
      "ebs-encryption|You can't directly encrypt existing unencrypted volumes or snapshots. To encrypt an unencrypted volume, create a snapshot of that volume, and then use the snapshot to create a new encrypted volume.",
      'ebs-encryption|Amazon EBS encryption uses AWS KMS keys when creating encrypted volumes and snapshots.',
    ],
  }),
  mc({
    id: 'key-vault-018',
    building: 'key-vault',
    bullets: ['1.3-S4'],
    d: 1,
    stem: 'A company wants to define which IAM roles can use a KMS key to encrypt and decrypt data and which roles can only administer the key. Which feature BEST meets this requirement?',
    correct: ['The key policy of the KMS key', 'Key policies are the primary way to control access to KMS keys, and their statements say who can use a key and how.'],
    wrong: [
      ['A security group that is attached to AWS KMS', 'Security groups filter network traffic for resources in a VPC and do not control permissions on a KMS key.'],
      ['An S3 bucket policy that names the roles', 'A bucket policy controls access to the bucket and its objects, not to the KMS key.'],
      ['IAM identity policies alone, with no key policy statement that enables them', 'Without permission from the key policy, IAM policies that allow access have no effect.'],
    ],
    slot: 1,
    evidence: [
      'kms-key-policies|Key policies are the primary way to control access to KMS keys.',
      'kms-key-policies|The statements in the key policy determine who has permission to use the KMS key and how they can use it.',
      'kms-key-policies|Without permission from the key policy, IAM policies that allow permissions have no effect.',
    ],
  }),
  mc({
    id: 'key-vault-019',
    building: 'key-vault',
    bullets: ['1.3-S4'],
    d: 2,
    stem: 'An engineer creates a customer managed key through the AWS KMS API with a custom key policy that names one application role. IAM policies that allow kms:Decrypt for other roles in the account have no effect. The company wants account administrators to grant key access with IAM policies. Which change meets this requirement with the LEAST effort?',
    correct: ['Add a key policy statement that gives the account principal permission to use IAM policies to allow access', 'This statement lets the account use IAM policies to allow access to all KMS operations on the key.'],
    wrong: [
      ['Attach an IAM policy that allows kms:PutKeyPolicy to the other roles', 'IAM policies that allow permissions have no effect unless the key policy enables them, so this grant is ignored.'],
      ['Set a permissions boundary on each of the other roles that includes kms:Decrypt', 'A permissions boundary only limits permissions and does not enable IAM policies for the key.'],
      ['Convert the key to an AWS managed key so that IAM policies apply automatically', 'A customer managed key cannot be converted, and AWS managed key policies cannot be changed by the company.'],
    ],
    slot: 2,
    evidence: [
      'kms-key-policies|Unless the key policy explicitly allows it, you cannot use IAM policies to allow access to a KMS key.',
      'kms-default-key-policy|Without this permission, IAM policies that allow access to the key are ineffective, although IAM policies that deny access to the key are still effective.',
      'kms-default-key-policy|Unlike other AWS resource policies, an AWS KMS key policy does not automatically give permission to the account or any of its principals.',
    ],
  }),
  mc({
    id: 'key-vault-020',
    building: 'key-vault',
    bullets: ['1.3-S4'],
    d: 3,
    stem: 'A company wants separation of duties for a customer managed key. A key-management role must administer the key but not be able to decrypt data, and an application role must encrypt and decrypt but not manage the key. The key must also stay manageable if the key-management role is later deleted. Which key policy design meets these requirements?',
    correct: ['An account statement enabling IAM policies, an administrators statement for the key-management role, and a users statement for the application role', 'Administrators manage but cannot use the key, users can use it, and the account statement keeps the key manageable.'],
    wrong: [
      ['Two statements that give the key-management role administration and the application role use, with no account statement', 'If the only principal with access is deleted, the key becomes unmanageable, so the account statement is missing.'],
      ['One statement that gives both roles every kms action so that either can recover the key', 'The key-management role could then decrypt data and the application role could manage the key, breaking the separation.'],
      ['An account statement plus a users statement for the key-management role and an administrators statement for the application role', 'The statements are swapped, so the application role could manage the key and the key-management role could not.'],
    ],
    slot: 3,
    evidence: [
      'kms-default-key-policy|Key administrators have permissions to manage the KMS key, but do not have permissions to use the KMS key in cryptographic operations.',
      'kms-default-key-policy|Key users have permission to use the KMS key directly in all cryptographic operations supported on the KMS key.',
      'kms-default-key-policy|suppose you create a key policy that gives only one user access to the KMS key. If you then delete that user, the key becomes unmanageable and you must contact AWS Support to regain access to the KMS key.',
    ],
  }),
  mc({
    id: 'key-vault-021',
    building: 'key-vault',
    bullets: ['1.3-S4'],
    d: 3,
    stem: 'A data account owns a customer managed key that encrypts objects in an Amazon S3 bucket. A role in an analytics account must decrypt the objects, and its S3 permissions are already in place. An engineer added a key policy statement that allows the analytics account to use the key, but the role still receives AccessDenied. What is MISSING?',
    correct: ['An IAM policy in the analytics account that allows the role to use the key', 'The key policy sets who can have access, and an IAM policy in the external account gives its roles that access.'],
    wrong: [
      ['A second key policy in the analytics account for the same KMS key', 'Every KMS key has exactly one key policy, and it lives in the account that owns the key.'],
      ['A copy of the KMS key created in the analytics account', 'A copy is not needed, because users in another account can use the key once both policies allow it.'],
      ['An AWS managed key policy in the analytics account that trusts the data account', 'AWS managed keys cannot be shared with other accounts and have no policy that the company can change.'],
    ],
    slot: 0,
    evidence: [
      'kms-cross-account|Neither the key policy nor the IAM policy alone is sufficient—you must change both.',
      'kms-cross-account|IAM policies in the external account must delegate the key policy permissions to its users and roles.',
      'kms-key-policies|Every KMS key must have exactly one key policy.',
    ],
  }),
  mr({
    id: 'key-vault-022',
    building: 'key-vault',
    bullets: ['1.3-S4', '1.3-S2'],
    d: 2,
    stem: 'A role must upload objects, including large multipart uploads, to an Amazon S3 bucket that uses SSE-KMS and must also download them. Which TWO KMS permissions must the role have on the key? (Choose two.)',
    correct: [
      ['kms:GenerateDataKey', 'Uploading an object with SSE-KMS requires kms:GenerateDataKey on the key.'],
      ['kms:Decrypt', 'Downloading an object encrypted with an AWS KMS key requires kms:Decrypt, which a multipart upload also needs.'],
    ],
    wrong: [
      ['kms:ScheduleKeyDeletion', 'This permission schedules the deletion of the key and is not needed to read or write encrypted objects.'],
      ['kms:PutKeyPolicy', 'This permission changes the key policy and is an administrative action, not a use of the key.'],
      ['kms:CreateAlias', 'This permission creates an alias for the key and does not encrypt or decrypt data.'],
    ],
    slots: [0, 2],
    evidence: [
      's3-sse-kms|To successfully make a PutObject request to encrypt an object with an AWS KMS key to Amazon S3, you need kms:GenerateDataKey permissions on the key.',
      's3-sse-kms|To download an object encrypted with an AWS KMS key, you need kms:Decrypt permissions for the key.',
      's3-sse-kms|To perform a multipart upload to encrypt an object with an AWS KMS key, you must have the kms:GenerateDataKey and kms:Decrypt permissions for the key.',
    ],
  }),
  mc({
    id: 'key-vault-023',
    building: 'key-vault',
    bullets: ['1.3-S4'],
    d: 3,
    stem: 'A company owns 40 customer managed keys whose key policies enable IAM policies for the account. A contractor\'s IAM role is compromised and must be blocked from using any KMS key in the account right away. Which solution is the FASTEST and meets this requirement without editing 40 key policies?',
    correct: ['Attach an IAM policy to the role that explicitly denies the KMS actions', 'An IAM policy can deny a permission to a KMS key without any permission from a key policy.'],
    wrong: [
      ['Remove the role from the key policy statements of all 40 keys', 'This means editing 40 policies, and the role can still get access through IAM policies that the key policies enable.'],
      ['Turn on automatic rotation for all 40 keys so that the role\'s access is revoked', 'Rotating key material does not change who is allowed to use a key.'],
      ['Schedule all 40 keys for deletion and cancel the deletion for the keys that are needed', 'This disrupts every workload that uses the keys and still needs per-key work.'],
    ],
    slot: 1,
    evidence: [
      'kms-key-policies|(You can use an IAM policy to deny a permission to a KMS key without permission from a key policy.)',
      'kms-key-policies|The default key policy enables IAM policies.',
    ],
  }),
  mc({
    id: 'key-vault-024',
    building: 'key-vault',
    bullets: ['1.3-K4'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A company wants to stop all use of a customer managed KMS key that it believes no workload needs. A forgotten application might still depend on it, and the company must be able to restore full access later with no time limit. Which action meets these requirements with the LEAST risk of permanent data loss?',
    correct: ['Disable the key and re-enable it if an application fails', 'A disabled KMS key can be re-enabled at any time, unlike a deleted key.'],
    wrong: [
      ['Schedule deletion of the key with a 30-day waiting period', 'Deletion cannot be canceled after the waiting period ends, so access could not be restored without a time limit.'],
      ['Delete the key immediately and recreate it if an application fails', 'AWS KMS requires a waiting period of at least 7 days for deletion, and a deleted key cannot be recovered.'],
      ['Turn off automatic key rotation on the key', 'This does not stop applications from using the key.'],
    ],
    slot: 2,
    evidence: [
      'kms-delete-key|If you are not sure, consider disabling the KMS key instead of deleting it.',
      'kms-delete-key|You can re-enable a disabled KMS key and cancel the scheduled deletion of a KMS key, but you cannot recover a deleted KMS key.',
      'kms-delete-key|After the waiting period ends you cannot cancel key deletion, and AWS KMS deletes the KMS key.',
    ],
  }),
  mc({
    id: 'key-vault-025',
    building: 'key-vault',
    bullets: ['1.3-S2'],
    d: 2,
    tags: ['mock-reserve', 'trap:sse-s3-kms-c'],
    stem: 'A company delivers Amazon S3 server access logs to a central bucket whose default encryption is SSE-KMS with a customer managed key. The log objects that arrive are encrypted with a key the security team cannot use. Which change resolves this with the LEAST effort?',
    correct: ['Change the default encryption of the destination bucket to SSE-S3', 'A destination bucket for server access logging must use Amazon S3 managed keys.'],
    wrong: [
      ['Add the security team\'s role to the key policy of the customer managed key', 'The delivered log objects may use a key the team cannot access, so editing this key\'s policy does not fix it.'],
      ['Enable an S3 Bucket Key on the destination bucket', 'A Bucket Key reduces AWS KMS requests and does not change which key encrypts the log objects.'],
      ['Switch the destination bucket to SSE-C and have the log service supply the key', 'The logging service cannot supply customer-provided keys with each request.'],
    ],
    slot: 3,
    evidence: [
      's3-sse-kms|If a bucket is used as a destination for Amazon S3 server access logging, the destination bucket must use Amazon S3 managed keys (SSE-S3).',
      's3-sse-kms|If the destination bucket uses SSE-KMS default encryption, Amazon S3 might deliver log objects that are encrypted with a key that you can\'t access.',
    ],
  }),
  mc({
    id: 'key-vault-026',
    building: 'key-vault',
    bullets: ['1.3-S4'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A company copies encrypted data to eu-west-1 and encrypts it there with a separate KMS key. Engineers assumed that the key policy of the us-east-1 key also controls the new key. Which statement describes the correct approach?',
    correct: ['Define the permitted principals in the key policy of the eu-west-1 key itself', 'A key policy controls access only to a KMS key in the same Region, so each key needs its own policy.'],
    wrong: [
      ['Rely on the us-east-1 key policy, because key policies are global like IAM policies', 'Key policies are Regional, unlike IAM policies, which are global.'],
      ['Copy the us-east-1 key policy to an IAM group so it applies to every Region', 'A key policy has no effect on a KMS key in another Region, and an IAM group does not replace the key policy.'],
      ['Share the us-east-1 key with eu-west-1 by adding the Region to its key policy', 'A key policy controls access only to a KMS key in the same Region and cannot extend to another Region.'],
    ],
    slot: 0,
    evidence: [
      'kms-key-policies|Unlike IAM policies, which are global, key policies are Regional. A key policy controls access only to a KMS key in the same Region. It has no effect on KMS keys in other Regions.',
    ],
  }),
];

export default questions;
