import type { Question } from '../../../src/content/types.ts';
import { mc, mr } from '../helpers.ts';

const questions: Question[] = [
  mc({
    id: 'wardens-lodge-001',
    building: 'wardens-lodge',
    bullets: ['1.2-K1'],
    d: 1,
    tags: ['trap:secrets-manager-vs-parameter-store'],
    stem: 'A company\'s Python application on Amazon EC2 has a database user name and password written directly in its source code. The security team requires that the credentials be removed from the code, retrieved only when the application needs them, and changed automatically on a schedule. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Store the credentials in AWS Secrets Manager, retrieve them at run time, and enable automatic rotation', 'Secrets Manager replaces hard-coded credentials with a run-time call and can rotate the secret on a schedule, which covers all three requirements.'],
    wrong: [
      ['Store the credentials in a Systems Manager Parameter Store String parameter and change the value by hand each quarter', 'It keeps the credentials out of the code, but nothing rotates them automatically, and AWS recommends Secrets Manager for credentials.'],
      ['Encrypt the credentials with an AWS KMS key and embed the ciphertext in the application source code', 'The credentials would still live in the source code, and every change would need a new deployment of the application.'],
      ['Save the credentials in an Amazon S3 object and add a cron job on each instance that replaces the object every month', 'It needs custom scripts to fetch and change the credentials, so rotation is not automatic and the operational effort is higher.'],
    ],
    slot: 0,
    evidence: [
      'secrets-intro|You replace hard-coded credentials with a runtime call to the Secrets Manager service to retrieve credentials dynamically when you need them.',
      'secrets-intro|With Secrets Manager, you can configure an automatic rotation schedule for your secrets.',
      'ssm-parameter-store|For secrets such as database credentials, API keys, or tokens, we recommend AWS Secrets Manager, which provides purpose built security controls including automatic rotation and cross-region replication.',
    ],
  }),
  mc({
    id: 'wardens-lodge-002',
    building: 'wardens-lodge',
    bullets: ['1.2-K4'],
    d: 1,
    stem: 'A startup is building a public mobile app. Customers must be able to sign up with an email address, sign in with their Google accounts, and reset forgotten passwords. The startup does not want to build or host its own user directory. Which AWS service should the startup use to meet these requirements with the LEAST development effort?',
    correct: ['An Amazon Cognito user pool with Google configured as a social identity provider', 'A user pool is a user directory for web and mobile app sign-up and sign-in, and users can also sign in through social providers such as Google.'],
    wrong: [
      ['AWS IAM Identity Center with a permission set created for each customer who signs up', 'IAM Identity Center connects workforce users to AWS accounts and managed applications; it is not a sign-up directory for public customers.'],
      ['An IAM user with a console password and an access key created for each new customer', 'It creates long-term IAM identities for the public instead of using a user directory, and it has no social sign-in or app sign-up flow.'],
      ['An Amazon Cognito identity pool that is configured without any user pool or other directory', 'An identity pool exchanges tokens for AWS credentials; it does not store users or provide sign-up, which is the job of a user pool.'],
    ],
    slot: 1,
    evidence: [
      'cognito-what-is|(authentication) Use a user pool.',
      'cognito-what-is|Users can sign in directly, through social providers like Google and Apple, or through enterprise SAML and OIDC providers.',
      'cognito-user-pools|An Amazon Cognito user pool is a user directory for web and mobile app authentication and authorization.',
      'sso-what-is|AWS IAM Identity Center is the AWS solution for connecting your workforce users to AWS managed applications',
    ],
  }),
  mc({
    id: 'wardens-lodge-003',
    building: 'wardens-lodge',
    bullets: ['1.2-K1'],
    d: 2,
    tags: ['trap:secrets-manager-vs-parameter-store'],
    stem: 'A company runs several microservices in development, test and production. Each service needs configuration values such as endpoint URLs and feature toggles, and a few of those values must be stored encrypted. The company wants the values organized by environment and service in a path-like structure and read by the services at run time. No credential rotation is required. Which solution meets these requirements MOST simply?',
    correct: ['Store the values as Parameter Store parameters in a hierarchy and use SecureString for the encrypted ones', 'Parameter Store is a centralized configuration store with parameter hierarchies, and SecureString parameters are encrypted with AWS KMS.'],
    wrong: [
      ['Create one AWS Secrets Manager secret for every value and enable automatic rotation on all of the secrets', 'It adds a per-secret service and rotation that the requirements do not ask for, and plain configuration values are what Parameter Store is for.'],
      ['Keep the values in a JSON file in an Amazon S3 bucket that each service downloads when it starts', 'It gives no path-based hierarchy per environment and service, and the services would need custom code to parse and protect the file.'],
      ['Set the values as plaintext environment variables in each service\'s task definition and redeploy on every change', 'The encrypted values would be exposed in plaintext, and each change would need a redeployment instead of a run-time read.'],
    ],
    slot: 2,
    evidence: [
      'ssm-parameter-store|Parameter Store is a centralized configuration data store for named values called parameters.',
      'ssm-parameter-store|Hierarchical parameter management Use parameter hierarchies to group related parameters, making it easier to discover, manage, and filter them across environments and applications.',
      'ssm-parameter-store|SecureString Use SecureString for configuration values that require encryption, such as service endpoints and account identifiers.',
      'ssm-parameter-store|Parameter Store encrypts the values using AWS Key Management Service.',
    ],
  }),
  mc({
    id: 'wardens-lodge-004',
    building: 'wardens-lodge',
    bullets: ['1.2-K4'],
    d: 2,
    stem: 'A company runs a web application on Amazon EC2 instances behind an Application Load Balancer. Employees must sign in with their corporate identities through a SAML 2.0 identity provider before any request reaches the application, and the company does not want to add sign-in code to the application. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Add an authenticate action to the load balancer listener that uses an Amazon Cognito user pool federated with the SAML provider', 'The load balancer can authenticate users through the user pools of Amazon Cognito, including corporate identities from SAML, so the application needs no sign-in code.'],
    wrong: [
      ['Attach an AWS WAF web ACL to the load balancer that allows only requests from the corporate network address range', 'It filters by source address and never identifies individual employees through the SAML identity provider.'],
      ['Configure an HTTPS listener with an AWS Certificate Manager certificate and a security policy that requires the newest TLS version', 'It encrypts traffic between browser and load balancer but does not authenticate employees at all.'],
      ['Build a sign-in page into the application that checks employee credentials in a user table in Amazon RDS', 'It requires sign-in code in the application, and it ignores the corporate SAML identity provider.'],
    ],
    slot: 3,
    evidence: [
      'alb-authenticate|You can configure an Application Load Balancer to securely authenticate users as they access your applications.',
      'alb-authenticate|This enables you to offload the work of authenticating users to your load balancer so that your applications can focus on their business logic.',
      'alb-authenticate|Authenticate users through corporate identities, using SAML, OpenID Connect (OIDC), or OAuth, through the user pools supported by Amazon Cognito.',
    ],
  }),
  mc({
    id: 'wardens-lodge-005',
    building: 'wardens-lodge',
    bullets: ['1.2-K1'],
    d: 2,
    stem: 'A company runs containers on Amazon ECS with AWS Fargate. The containers need a database password when they start. The password must stay out of the container image and out of the plain text of the task definition, and it must be rotated automatically. The company does not want to write code in the containers to fetch it. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Store the password in AWS Secrets Manager and reference the secret in the task definition for Amazon ECS to inject', 'Amazon ECS can inject secrets from Secrets Manager into containers at run time, and Secrets Manager adds automatic rotation.'],
    wrong: [
      ['Set the password as a plain text environment variable in the task definition and update the definition each month', 'The password would sit in plain text in the task definition, and rotation would be a manual task.'],
      ['Bake the password into the container image in Amazon ECR and build a new image whenever the password changes', 'The password would be inside the image, and each rotation would need a new image build and deployment.'],
      ['Store the password in an encrypted Amazon S3 object and add startup code to each container that downloads the object', 'It requires code in the containers to fetch the value, and nothing rotates the password automatically.'],
    ],
    slot: 0,
    evidence: [
      'ecs-sensitive-data|Secrets can be seamlessly injected into containers from AWS Secrets Manager and Amazon EC2 Systems Manager Parameter Store.',
      'ecs-sensitive-data|Secrets Manager, however, also includes the ability to automatically rotate secrets, generate random secrets, and share secrets across accounts.',
      'ecs-sensitive-data|They\'re referenced as environment variables that use the secrets container definition parameter.',
    ],
  }),
  mc({
    id: 'wardens-lodge-006',
    building: 'wardens-lodge',
    bullets: ['1.2-K4'],
    d: 2,
    stem: 'A company exposes a REST API through Amazon API Gateway. Customers of its mobile app sign in with an Amazon Cognito user pool. Only signed-in customers may call the API, and the company wants API Gateway to check each customer\'s token without writing and maintaining authorization code. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Create an authorizer of the Cognito user pool type in API Gateway and enable it on the API methods', 'API Gateway can use a Cognito user pool as an authorizer, so signed-in customers present a token and no custom authorization code is needed.'],
    wrong: [
      ['Write an AWS Lambda authorizer that parses and verifies the token for every request', 'A Lambda authorizer implements a custom authorization scheme, which is code the company would have to write and maintain.'],
      ['Require an API key on each method and bundle the same key into the mobile app', 'API keys are not meant for authentication or authorization, and a shared key does not identify each signed-in customer.'],
      ['Turn on IAM authorization for the methods and create an IAM user with access keys for each customer', 'It creates a long-term IAM identity for every customer, whereas the customers already sign in with the user pool.'],
    ],
    slot: 1,
    evidence: [
      'apigw-cognito-authorizer|To use an Amazon Cognito user pool with your API, you must first create an authorizer of the COGNITO_USER_POOLS type and then configure an API method to use that authorizer.',
      'apigw-lambda-authorizer|Use a Lambda authorizer to implement a custom authorization scheme.',
      'apigw-usage-plans|Don\'t use API keys for authentication or authorization to control access to your APIs.',
    ],
  }),
  mc({
    id: 'wardens-lodge-007',
    building: 'wardens-lodge',
    bullets: ['1.2-K1'],
    d: 1,
    stem: 'A developer stored the access key ID and secret access key of an IAM user in a configuration file on an Amazon EC2 instance so that the application can read objects from an Amazon S3 bucket. A security review flags these long-term keys. Which change BEST follows AWS guidance for applications running on AWS?',
    correct: ['Delete the keys and attach an IAM role with the needed Amazon S3 permissions to the instance', 'Workloads on AWS should use temporary credentials from an IAM role, which the AWS SDK discovers, so no long-term keys have to be distributed.'],
    wrong: [
      ['Restrict the configuration file so that only the application\'s operating system user can read it', 'The keys are still long-term credentials kept on the instance; the guidance is to avoid distributing them at all.'],
      ['Encrypt the configuration file with an AWS KMS key and leave the access keys in the encrypted file', 'The application would still depend on long-term keys that someone has to distribute, now with extra decryption steps.'],
      ['Create a second IAM user for the application and swap the keys in the file every year', 'It replaces one long-term key pair with another and still relies on distributing credentials to the instance.'],
    ],
    slot: 2,
    evidence: [
      'iam-best-practices|Applications written using an AWS SDK will discover and use these temporary credentials to access AWS resources, and there is no need to distribute long lived credentials for an IAM user to your workloads running on AWS.',
      'iam-best-practices|Where possible, we recommend relying on temporary credentials instead of creating long-term credentials such as access keys.',
      'ec2-iam-roles|Amazon EC2 uses an instance profile as a container for an IAM role.',
    ],
  }),
  mc({
    id: 'wardens-lodge-008',
    building: 'wardens-lodge',
    bullets: ['1.2-K4'],
    d: 2,
    stem: 'A photo-sharing web application lets visitors browse public thumbnails stored in Amazon S3 before they create an account. The browser code calls Amazon S3 with AWS credentials. Visitors who have not signed in must receive credentials with a very narrow read-only scope, and signed-in members must receive broader permissions. Which solution meets these requirements with the LEAST custom code?',
    correct: ['Use an Amazon Cognito identity pool with guest access and separate IAM roles for guests and members', 'An identity pool generates temporary AWS credentials for users who have not signed in, with a narrow scope, and can map signed-in users to a broader role.'],
    wrong: [
      ['Use an Amazon Cognito user pool alone and send the user pool tokens as the credentials to Amazon S3', 'User pool tokens identify the user to the app; Amazon S3 needs AWS credentials, which come from an identity pool.'],
      ['Place the read-only access keys of one shared IAM user in the browser code and rotate them each month', 'It puts long-term keys in public code, and it gives signed-in members no separate, broader permissions.'],
      ['Create guest accounts in AWS IAM Identity Center and have visitors sign in to the AWS access portal first', 'IAM Identity Center is for workforce users, and visitors who have not signed in could not use it.'],
    ],
    slot: 3,
    evidence: [
      'cognito-identity-pools|For your users who haven’t signed in yet, configure your identity pool to generate AWS credentials with a narrow scope of access.',
      'cognito-identity-pools|Identity pools generate temporary AWS credentials for the users of your app, whether they’ve signed in or you haven’t identified them yet.',
      'cognito-identity-pools|Assign a single IAM role to all of your authenticated users, or choose the role based on the claims of each user.',
    ],
  }),
  mr({
    id: 'wardens-lodge-009',
    building: 'wardens-lodge',
    bullets: ['1.2-K1'],
    d: 3,
    stem: 'A company stores database credentials as a secret in AWS Secrets Manager in Account A. The secret is encrypted with the AWS managed key aws/secretsmanager. An application role in Account B must read the secret value. Which THREE actions are required to allow this access? (Choose three.)',
    correct: [
      ['Re-encrypt the secret with a customer managed KMS key and add a key policy that lets the Account B role use the key', 'The AWS managed key cannot be used for cross-account access, so the secret needs a key that the company creates and a key policy for the other account.'],
      ['Attach a resource-based policy to the secret that allows the Account B role to read the secret value', 'Cross-account access must be allowed in a resource policy attached to the secret.'],
      ['Attach an identity-based policy to the Account B role that allows it to read the secret', 'Cross-account access must be allowed in an identity policy as well as in the resource policy.'],
    ],
    wrong: [
      ['Add the Account B role to the key policy of the AWS managed key aws/secretsmanager', 'The AWS managed key cannot be used for cross-account access, and its key policy is not the way to grant it.'],
      ['Replicate the secret to a second Region so that Account B can read the replica without any policy', 'Replication copies the secret across Regions; it does not give another account permission to read it.'],
      ['Create an IAM user in Account A for the application and copy that user\'s access keys into Account B', 'It adds long-term keys that must be distributed, whereas the resource policy and identity policy grant access to the role.'],
    ],
    slots: [1, 3, 5],
    evidence: [
      'secrets-cross-account|To allow users in one account to access secrets in another account (cross-account access), you must allow access both in a resource policy and in an identity policy.',
      'secrets-cross-account|This is because you can\'t use the AWS managed key (aws/secretsmanager) for cross-account access.',
      'secrets-cross-account|Instead, you must encrypt your secret with a KMS key that you create, and then attach a key policy to it.',
    ],
  }),
  mc({
    id: 'wardens-lodge-010',
    building: 'wardens-lodge',
    bullets: ['1.2-K1'],
    d: 2,
    stem: 'An AWS Lambda function reads a third-party API key from an environment variable in its configuration. The vendor requires the key to be replaced every 60 days. The company wants the function to pick up each new key without editing the function configuration or deploying new code, and it wants stronger protection than a configuration setting. Which solution meets these requirements MOST effectively?',
    correct: ['Store the key in AWS Secrets Manager, let the function\'s execution role read the secret, and retrieve it at run time', 'AWS recommends Secrets Manager rather than environment variables for API keys, and a run-time lookup picks up a changed secret without redeploying.'],
    wrong: [
      ['Encrypt the environment variable with a customer managed AWS KMS key and update the variable whenever the key changes', 'Encryption protects the value, but every new key still means editing the function configuration.'],
      ['Place the key in a text file inside the deployment package and upload a new package every 60 days', 'It keeps the key in the code package, and each new key needs a new deployment.'],
      ['Put the key in a Lambda layer shared by the functions and publish a new layer version for each new key', 'Every new key needs a new layer version and an update of each function, and the key sits in a package.'],
    ],
    slot: 0,
    evidence: [
      'lambda-envvars|To increase security, we recommend that you use AWS Secrets Manager instead of environment variables to store database credentials and other sensitive information like API keys or authorization tokens.',
      'secrets-intro|Since the credentials are no longer stored with the application, rotating credentials no longer requires updating your applications and deploying changes to application clients.',
    ],
  }),
  mc({
    id: 'wardens-lodge-011',
    building: 'wardens-lodge',
    bullets: ['1.2-K4'],
    d: 3,
    stem: 'Users of a web application sign in through an Amazon Cognito user pool. Members of the editors group must be able to upload objects to an Amazon S3 bucket directly from the browser, while all other signed-in users may only read objects. Each user must receive only the AWS permissions that match their group. Which solution meets these requirements with the LEAST custom code?',
    correct: ['Link each user pool group to an IAM role and pass the ID token to a Cognito identity pool to obtain credentials for that role', 'User pool groups appear in the tokens and can be linked to IAM roles, and the identity pool turns the token into temporary credentials for the matching role.'],
    wrong: [
      ['Give every authenticated user one IAM role that allows uploads and hide the upload button for users who are not editors', 'Hiding a button in the app does not limit AWS permissions, so any signed-in user could still upload.'],
      ['Create an IAM user for each editor and give the editors the access keys through the application', 'It creates long-term IAM users and keys instead of using the groups that the user pool already provides.'],
      ['Sign the Amazon S3 requests with the access token from the user pool and check the group claim in a bucket policy', 'Amazon S3 does not accept user pool tokens as AWS credentials; an identity pool is needed to obtain them.'],
    ],
    slot: 1,
    evidence: [
      'cognito-user-pools|After your users sign up, you can add them to groups that Amazon Cognito lists in the access and ID tokens.',
      'cognito-user-pools|You can also link user pool groups to IAM roles when you pass the ID token to an identity pool.',
      'cognito-identity-pools|Assign a single IAM role to all of your authenticated users, or choose the role based on the claims of each user.',
    ],
  }),
  mc({
    id: 'wardens-lodge-012',
    building: 'wardens-lodge',
    bullets: ['1.2-K4'],
    d: 3,
    stem: 'A company is launching an internal analytics portal and a public mobile app. Employees already exist in the corporate identity provider and need single sign-on to the company\'s AWS accounts and to AWS managed applications such as Amazon Quick. Customers of the mobile app must sign up with an email address or an Apple account. Which combination meets these requirements with the LEAST custom development?',
    correct: ['AWS IAM Identity Center for the employees and an Amazon Cognito user pool for the customers', 'IAM Identity Center connects workforce users to AWS accounts and managed applications, and a user pool handles sign-up and sign-in for app users.'],
    wrong: [
      ['An Amazon Cognito user pool for the employees and AWS IAM Identity Center for the customers', 'The services are reversed: IAM Identity Center is for the workforce and a user pool is for the app\'s own users.'],
      ['IAM users with console passwords for the employees and an Amazon Cognito identity pool for the customers', 'IAM users for people are long-term identities, and an identity pool does not provide a customer sign-up directory.'],
      ['An Amazon Cognito identity pool for the employees and IAM users with access keys for the customers', 'An identity pool issues AWS credentials rather than workforce single sign-on, and IAM users are not a customer sign-up directory.'],
    ],
    slot: 2,
    evidence: [
      'sso-what-is|AWS IAM Identity Center is the AWS solution for connecting your workforce users to AWS managed applications such as Kiro and Amazon Quick, and other AWS resources.',
      'cognito-user-pools|An Amazon Cognito user pool is a user directory for web and mobile app authentication and authorization.',
      'cognito-what-is|Users can sign in directly, through social providers like Google and Apple, or through enterprise SAML and OIDC providers.',
    ],
  }),
  mc({
    id: 'wardens-lodge-013',
    building: 'wardens-lodge',
    bullets: ['1.2-K1'],
    d: 2,
    stem: 'A company runs its application in us-east-1 and a second copy in eu-west-1. Both copies use database credentials stored in AWS Secrets Manager. The eu-west-1 application must read the credentials in its own Region with low latency, and a credential rotation in the primary Region must reach the second Region. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Configure the secret to replicate to eu-west-1 and have the second application read the replica', 'Secrets Manager can replicate a secret to other Regions for Regional access and low latency, and a rotated value propagates to the replicas.'],
    wrong: [
      ['Create a separate secret in eu-west-1 and run a scheduled AWS Lambda function that copies each new value', 'It works, but the company must write, schedule and maintain the copy function instead of using built-in replication.'],
      ['Have the eu-west-1 application call the Secrets Manager endpoint in us-east-1 for every credential request', 'Every read would cross Regions, which does not meet the requirement to read in its own Region with low latency.'],
      ['Copy the credentials into Systems Manager Parameter Store in both Regions and update each copy by hand', 'The manual updates are operational work, and rotation in the primary Region would not reach the other copy automatically.'],
    ],
    slot: 3,
    evidence: [
      'secrets-replicate|You can replicate your secrets in multiple AWS Regions to support applications spread across those Regions to meet Regional access and low latency requirements.',
      'secrets-replicate|If you turn on rotation for your primary secret, Secrets Manager rotates the secret in the primary Region, and the new secret value propagates to all of the associated replica secrets.',
    ],
  }),
  mr({
    id: 'wardens-lodge-014',
    building: 'wardens-lodge',
    bullets: ['1.2-K4'],
    d: 2,
    stem: 'A company uses an Amazon Cognito user pool for the sign-in of its public web application. The security team sees password-guessing attempts and automated sign-up abuse against the user pool. Which TWO actions will MOST directly strengthen protection of the sign-in? (Choose two.)',
    correct: [
      ['Turn on multi-factor authentication for the user pool', 'A user pool can require a second factor, such as a one-time password, after the password.'],
      ['Associate an AWS WAF web ACL with the user pool', 'AWS WAF web ACLs help protect a user pool against malicious traffic, such as automated abuse.'],
    ],
    wrong: [
      ['Add an identity pool with guest access in front of the user pool', 'An identity pool issues AWS credentials; it does not defend the sign-in of the user pool.'],
      ['Apply an IAM account password policy for the application\'s customers', 'An IAM password policy applies to IAM users, not to the customers stored in a user pool.'],
      ['Attach a network ACL to the user pool to block suspicious source addresses', 'Network ACLs control traffic for subnets in a VPC, and a user pool is not placed in a subnet.'],
    ],
    slots: [0, 2],
    evidence: [
      'cognito-user-pools|Protect your users against password guessing, account takeover, and malicious traffic with multi-factor authentication (MFA), adaptive authentication, and AWS WAF web ACLs.',
      'cognito-what-is|Amazon Cognito supports time-based one-time password (TOTP) and SMS message MFA.',
    ],
  }),
  mr({
    id: 'wardens-lodge-015',
    building: 'wardens-lodge',
    bullets: ['1.2-K1'],
    d: 3,
    stem: 'A company keeps the API key of a third-party payment provider in AWS Secrets Manager. The provider lets the company create a new key through its API. The security policy requires the key to change every 30 days with no manual steps, and the application must keep reading the secret at run time. Which TWO actions meet these requirements? (Choose two.)',
    correct: [
      ['Write a rotation function in AWS Lambda that creates the new key at the provider and stores it in the secret', 'For secrets other than managed ones, Secrets Manager rotation uses a Lambda function to update the secret and the service.'],
      ['Turn on automatic rotation for the secret with a 30-day schedule that uses the rotation function', 'Secrets Manager can rotate a secret automatically on a schedule, and the rotation function does the update.'],
    ],
    wrong: [
      ['Enable managed rotation so that Secrets Manager rotates the key at the provider without a Lambda function', 'Rotating a key at a third-party provider is an "other type of secret", and for those rotation uses a Lambda function.'],
      ['Add a Systems Manager Parameter Store expiration notification policy and replace the key when the event arrives', 'The policy only sends a notification, and replacing the key afterwards is a manual step.'],
      ['Publish a reminder to an Amazon SNS topic every 30 days so that an administrator replaces the key', 'The administrator performs the change, which breaks the requirement for no manual steps.'],
    ],
    slots: [2, 4],
    evidence: [
      'secrets-rotation|Rotation by Lambda function – For other types of secrets, Secrets Manager rotation uses a Lambda function to update the secret and the database or service.',
      'secrets-rotation|In Secrets Manager, you can set up automatic rotation for your secrets.',
      'ssm-parameter-policies|Parameter Store offers the following types of policies: Expiration, ExpirationNotification, and NoChangeNotification.',
    ],
  }),
  mc({
    id: 'wardens-lodge-016',
    building: 'wardens-lodge',
    bullets: ['1.2-K1'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'An application runs on Amazon EC2 instances in private subnets of a VPC that has no internet gateway and no NAT device. The application must retrieve database credentials from AWS Secrets Manager without the traffic crossing the public internet. Which solution meets these requirements MOST simply?',
    correct: ['Create an interface VPC endpoint for Secrets Manager in the VPC', 'An interface endpoint, powered by AWS PrivateLink, lets resources reach Secrets Manager privately without an internet gateway or NAT device.'],
    wrong: [
      ['Create a gateway VPC endpoint for Secrets Manager and add it to the route tables', 'Gateway endpoints cover only Amazon S3 and DynamoDB, so Secrets Manager needs an interface endpoint.'],
      ['Add a NAT gateway in a public subnet and route the private subnets through it', 'The traffic would then leave through the internet, which the requirement rules out.'],
      ['Copy the credentials into the user data of each instance when it launches', 'The credentials would be copied to every instance, and they would no longer be retrieved from Secrets Manager at run time.'],
    ],
    slot: 1,
    evidence: [
      'secrets-vpc-endpoint|You can establish a private connection between your VPC and Secrets Manager by creating an interface VPC endpoint.',
      'secrets-vpc-endpoint|Interface endpoints are powered by AWS PrivateLink, a technology that enables you to privately access Secrets Manager APIs without an internet gateway, NAT device, VPN connection, or Direct Connect connection.',
      'vpce-gateway|Gateway VPC endpoints provide reliable connectivity to Amazon S3 and DynamoDB without requiring an internet gateway or a NAT device for your VPC.',
    ],
  }),
  mc({
    id: 'wardens-lodge-017',
    building: 'wardens-lodge',
    bullets: ['1.2-K4'],
    d: 1,
    tags: ['mock-reserve'],
    stem: 'A company\'s web application authenticates customers with an Amazon Cognito user pool. The security team wants customers to enter a one-time code from an authenticator app after they type their password. Which solution meets this requirement with the LEAST effort?',
    correct: ['Turn on multi-factor authentication in the user pool and allow time-based one-time passwords', 'Cognito supports time-based one-time password and SMS message MFA, and user pools can add multi-factor authentication after sign-in.'],
    wrong: [
      ['Create an IAM user with a virtual MFA device for every customer and have them sign in with those users', 'It moves the customers out of the user pool into IAM users, which is the wrong identity type for app customers.'],
      ['Configure the Cognito identity pool to require a second factor before it issues AWS credentials', 'An identity pool exchanges identities for AWS credentials; the sign-in factors are set in the user pool.'],
      ['Add an AWS WAF rule that blocks sign-in requests that do not include a one-time code header', 'AWS WAF inspects web requests but does not generate or verify one-time codes for users.'],
    ],
    slot: 2,
    evidence: [
      'cognito-what-is|Amazon Cognito supports time-based one-time password (TOTP) and SMS message MFA.',
      'cognito-user-pools|Managed login is a set of web pages for sign-up, sign-in, multi-factor authentication (MFA), and password reset.',
    ],
  }),
  mr({
    id: 'wardens-lodge-018',
    building: 'wardens-lodge',
    bullets: ['1.2-K4'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A software-as-a-service company runs a web application whose users sign in through an Amazon Cognito user pool. Some business customers want their employees to sign in with their own SAML 2.0 identity provider, and consumer users want to sign in with their Google accounts. The application must receive one consistent kind of token from the user pool. Which TWO configurations meet these requirements? (Choose two.)',
    correct: [
      ['Add each customer\'s SAML 2.0 identity provider to the user pool as an enterprise identity provider', 'A user pool turns SAML 2.0 assertions into user profiles and tokens, so the application sees one token format.'],
      ['Add Google to the user pool as a social identity provider', 'A user pool lets users sign in through social providers such as Google and issues its own tokens to the application.'],
    ],
    wrong: [
      ['Create an IAM user in the company\'s account for every employee of every business customer', 'It creates a large number of long-term IAM identities and bypasses the user pool and the customers\' own identity providers.'],
      ['Create an IAM role for each customer and give the customers\' employees console access to it', 'It gives employees access to the AWS Management Console, which is not application sign-in with the user pool.'],
      ['Create AWS IAM Identity Center permission sets for each customer\'s employees', 'IAM Identity Center is for the company\'s own workforce and AWS accounts, not for the application\'s external users.'],
    ],
    slots: [1, 4],
    evidence: [
      'cognito-user-pools|Amazon Cognito processes OIDC id tokens, OAuth 2.0 userInfo data, and SAML 2.0 assertions into user profiles in your user pool.',
      'cognito-what-is|Users can sign in directly, through social providers like Google and Apple, or through enterprise SAML and OIDC providers.',
    ],
  }),
];

export default questions;
