import type { Question } from '../../../src/content/types.ts';
import { mc, mr } from '../helpers.ts';

const questions: Question[] = [
  mc({
    id: 'watchtower-001',
    building: 'watchtower',
    bullets: ['1.2-K5'],
    d: 1,
    stem: 'A company keeps customer documents in Amazon S3 buckets. The security team must discover which objects contain personal data such as names and card numbers. Which AWS service BEST meets this requirement?',
    correct: ['Amazon Macie', 'Macie discovers sensitive data in Amazon S3 by using machine learning and pattern matching.'],
    wrong: [
      ['Amazon GuardDuty', 'GuardDuty detects suspicious activity in logs and accounts, and it does not classify the contents of S3 objects.'],
      ['Amazon Inspector', 'Inspector scans workloads for software vulnerabilities and unintended network exposure, not for personal data.'],
      ['AWS Shield', 'Shield protects applications against DDoS attacks and does not look inside stored objects.'],
    ],
    slot: 0,
    evidence: [
      'macie|Amazon Macie is a data security service that discovers sensitive data by using machine learning and pattern matching, provides visibility into data security risks, and enables automated protection against those risks.',
    ],
  }),
  mc({
    id: 'watchtower-002',
    building: 'watchtower',
    bullets: ['1.2-K6'],
    d: 2,
    tags: ['placement-eligible', 'trap:shield-vs-waf'],
    stem: 'A company serves its web application through an Amazon CloudFront distribution. A small set of client IP addresses now sends a flood of HTTP requests that look valid and slows the origin. The company wants to rate limit those clients with the LEAST operational overhead. Which solution meets these requirements?',
    correct: ['Associate an AWS WAF web ACL that contains a rate-based rule with the distribution', 'A rate-based rule counts incoming requests and rate limits them when they arrive too fast, and a web ACL can be associated with a CloudFront distribution.'],
    wrong: [
      ['Rely on AWS Shield Standard, which already blocks floods of web requests', 'Shield Standard defends against network and transport layer attacks, and a flood of valid-looking web requests is an application layer attack.'],
      ['Deploy AWS Network Firewall in the VPC of the origin to rate limit the HTTP requests', 'Network Firewall filters traffic at the perimeter of a VPC and is not a way to rate limit by client on a CloudFront distribution.'],
      ['Enable Amazon GuardDuty and review its findings about the clients', 'GuardDuty detects threats and generates findings, and it does not rate limit or block requests.'],
    ],
    slot: 1,
    evidence: [
      'waf-rate-based|A rate-based rule counts incoming requests and rate limits requests when they are coming at too fast a rate.',
      'waf-cloudfront|When you create a protection pack (web ACL), you can specify one or more CloudFront distributions that you want AWS WAF to inspect.',
      'shield-overview|Application layer attacks (layer 7) – This category of attack vector attempts to deny service to legitimate users by flooding an application with queries that are valid for the target, such as web request floods.',
    ],
  }),
  mc({
    id: 'watchtower-003',
    building: 'watchtower',
    bullets: ['1.2-K5'],
    d: 2,
    stem: 'A company runs Amazon EC2 instances, stores container images in Amazon ECR, and deploys AWS Lambda functions. The security team wants these workloads discovered and continually scanned for software vulnerabilities without scheduling any scans. Which service BEST meets these requirements?',
    correct: ['Amazon Inspector', 'Inspector automatically discovers workloads and continually scans EC2 instances, container images in ECR, and Lambda functions.'],
    wrong: [
      ['Amazon GuardDuty', 'GuardDuty analyzes logs and data sources for threats and does not scan workloads for software vulnerabilities.'],
      ['Amazon Macie', 'Macie discovers sensitive data in Amazon S3 and does not scan compute workloads for vulnerabilities.'],
      ['Amazon Detective', 'Detective helps investigate findings after the fact and does not scan workloads.'],
    ],
    slot: 2,
    evidence: [
      'inspector|Amazon Inspector is a vulnerability management service that automatically discovers workloads and continually scans them for software vulnerabilities and unintended network exposure.',
      'inspector|Amazon Inspector discovers and scans Amazon EC2 instances, container images in Amazon ECR, and Lambda functions.',
      "inspector|With Amazon Inspector, you don't need to manually schedule or configure assessment scans.",
    ],
  }),
  mc({
    id: 'watchtower-004',
    building: 'watchtower',
    bullets: ['1.2-K6', '1.2-S3'],
    d: 3,
    tags: ['placement-eligible'],
    stem: 'A company exposes a public REST API with Amazon API Gateway in one Region. The security team needs requests that carry malicious SQL code and requests from specific countries blocked before any other access control logic runs, with the LEAST custom code. Which solution meets these requirements?',
    correct: ['Associate a same-Region AWS WAF web ACL that has SQL injection and geographic rules with the API stage', 'AWS WAF rules are evaluated before other access controls, and a web ACL can block malicious SQL code and requests from a specific country.'],
    wrong: [
      ['Create the AWS WAF web ACL with the same rules in a different Region and associate it with the API stage', 'The web ACL and the AWS WAF resources it uses must be located in the same Region as the API.'],
      ['Write an AWS Lambda authorizer that inspects each request for SQL code and the country of origin', 'This needs custom code to build and maintain, and AWS WAF already provides these rule types.'],
      ['Subscribe to AWS Shield Advanced and add protection for the API Gateway REST API', 'Shield Advanced does not list API Gateway among its protected resource types and does not inspect requests for SQL code.'],
    ],
    slot: 3,
    evidence: [
      'apigw-waf|You can use AWS WAF to protect your API Gateway REST API from common web exploits, such as SQL injection and cross-site scripting (XSS) attacks.',
      "apigw-waf|The web ACL and any other AWS WAFV2 resources that it uses must be located in the same Region as your API.",
      'apigw-waf|When AWS WAF is enabled on an API, AWS WAF rules are evaluated before other access control features, such as resource policies, IAM policies, Lambda authorizers, and Amazon Cognito authorizers.',
      'shield-protected-resources|You can use Shield Advanced for advanced monitoring and protection with the following resource types:',
    ],
  }),
  mc({
    id: 'watchtower-005',
    building: 'watchtower',
    bullets: ['1.2-K6'],
    d: 1,
    stem: 'A company hosts a web application behind an Application Load Balancer. Attackers send web requests that contain malicious SQL code to modify the database. Which solution BEST protects the application from these requests?',
    correct: ['An AWS WAF web ACL with a SQL injection rule statement on the load balancer', 'A SQL injection rule statement inspects requests for malicious SQL code, and a web ACL can protect an Application Load Balancer.'],
    wrong: [
      ['AWS Shield Standard enabled on the Application Load Balancer', 'Shield Standard defends against network and transport layer DDoS attacks and does not inspect requests for SQL code.'],
      ['Amazon Inspector scheduled scans of the load balancer and the instances behind it every night', 'Inspector scans EC2 instances, container images, and Lambda functions for vulnerabilities and does not filter web requests.'],
      ['Amazon Macie on the database backups stored in Amazon S3', 'Macie discovers sensitive data in Amazon S3 and does not block malicious requests.'],
    ],
    slot: 0,
    evidence: [
      'waf-sqli|An SQL injection rule statement inspects for malicious SQL code. Attackers insert malicious SQL code into web requests in order to do things like modify your database or extract data from it.',
      'waf-what-is|You can protect the following resource types: Amazon CloudFront distributionAmazon API Gateway REST APIApplication Load Balancer',
    ],
  }),
  mr({
    id: 'watchtower-006',
    building: 'watchtower',
    bullets: ['1.2-K5'],
    d: 2,
    stem: 'A security team enables Amazon GuardDuty in an account and turns on no optional protection plans. Which THREE data sources does GuardDuty analyze automatically? (Choose three.)',
    correct: [
      ['AWS CloudTrail management events', 'CloudTrail management events are one of the foundational data sources that GuardDuty ingests when it is enabled.'],
      ['VPC Flow Logs', 'VPC Flow Logs are a foundational data source that GuardDuty ingests automatically.'],
      ['DNS logs', 'DNS logs are a foundational data source that GuardDuty ingests automatically.'],
    ],
    wrong: [
      ['Application Load Balancer access logs', 'They are not one of the foundational data sources that GuardDuty ingests when enabled.'],
      ['Amazon S3 server access logs', 'They are not one of the foundational data sources that GuardDuty ingests when enabled.'],
      ['AWS Config configuration snapshots', 'They are not one of the foundational data sources that GuardDuty ingests when enabled.'],
    ],
    slots: [0, 2, 4],
    evidence: [
      "guardduty|When you enable GuardDuty in an AWS account, GuardDuty automatically starts ingesting the foundational data sources associated with that account. These data sources include AWS CloudTrail management events, VPC flow logs (from Amazon EC2 instances), and DNS logs.",
      "guardduty|You don't need to enable anything else for GuardDuty to start analyzing and processing these data sources to generate associated security findings.",
    ],
  }),
  mc({
    id: 'watchtower-007',
    building: 'watchtower',
    bullets: ['1.2-S3'],
    d: 3,
    tags: ['placement-eligible', 'trap:shield-vs-waf'],
    stem: 'An online retailer serves its site through Amazon CloudFront with an Application Load Balancer as the origin. The company wants expanded DDoS protection, some protection against scaling charges that a DDoS attack could cause, and direct access to DDoS specialists during an attack. The company has an Enterprise Support plan. Which solution BEST meets these requirements?',
    correct: ['Subscribe to AWS Shield Advanced and add protection to the distribution and the load balancer', 'Shield Advanced offers cost protection and access to the Shield Response Team, and it protects only the resources that you add.'],
    wrong: [
      ['Keep AWS Shield Standard, which already protects every AWS customer automatically', 'Shield Standard protects against common network and transport layer attacks and does not provide cost protection or the Shield Response Team.'],
      ['Subscribe to AWS Shield Advanced and rely on it to protect all resources in the account automatically', 'Shield Advanced does not protect resources automatically, so each resource must be added.'],
      ['Associate an AWS WAF web ACL with rate-based rules with the distribution', 'AWS WAF filters web requests and is not the offering with DDoS cost protection and the Shield Response Team.'],
    ],
    slot: 1,
    evidence: [
      'shield-capabilities|Cost protection opportunities – Shield Advanced offers some cost protection against spikes in your AWS bill that might result from a DDoS attack against your protected resources.',
      'shield-capabilities|To use the services of the SRT, you must also be subscribed to the Business Support plan or the Enterprise Support plan.',
      "shield-protected-resources|Shield Advanced doesn't automatically protect your resources.",
    ],
  }),
  mc({
    id: 'watchtower-008',
    building: 'watchtower',
    bullets: ['1.2-K5'],
    d: 2,
    stem: 'A company runs Amazon GuardDuty, Amazon Inspector, and Amazon Macie in several accounts. The security team wants a single pane of glass that collects these findings and also runs checks against security standards. Which service BEST meets these requirements?',
    correct: ['AWS Security Hub', 'Security Hub receives findings from services such as GuardDuty, Inspector, and Macie and runs checks against security controls.'],
    wrong: [
      ['Amazon Detective', 'Detective helps investigate a finding by showing related activity and is not the central place for findings and standards checks.'],
      ['AWS Firewall Manager', 'Firewall Manager applies protections such as AWS WAF rules across accounts and does not collect these findings.'],
      ['Amazon CloudWatch dashboards', 'Dashboards visualize metrics and logs and do not run checks against security standards.'],
    ],
    slot: 2,
    evidence: [
      'security-hub|This gives you a single pane of glass into a variety of security-related issues.',
      'security-hub|Security Hub CSPM runs checks against security controls and generates control findings to help you assess your compliance against security best practices.',
      'securityhub-ga|Security Hub automatically aggregates and correlates signals from Amazon GuardDuty, Amazon Inspector, AWS Security Hub Cloud Security Posture Management (AWS Security Hub CSPM), and Amazon Macie',
    ],
  }),
  mc({
    id: 'watchtower-009',
    building: 'watchtower',
    bullets: ['1.2-K6'],
    d: 2,
    tags: ['trap:shield-vs-waf'],
    stem: 'A web application behind an Application Load Balancer is overwhelmed by a flood of requests that look valid. The requests come from a few hundred client addresses. Which solution BEST limits the flood without blocking normal users?',
    correct: ['An AWS WAF rate-based rule in a web ACL that is associated with the load balancer', 'It counts requests and rate limits clients that send them too fast, so normal users stay below the limit.'],
    wrong: [
      ['AWS Shield Standard alone', 'Shield Standard covers network and transport layer attacks, and this is a flood at the application layer.'],
      ['A network ACL rule that denies all inbound traffic on port 443', 'It would block every user, including the normal ones.'],
      ['An Amazon Macie job on the load balancer logs', 'Macie discovers sensitive data in Amazon S3 and does not limit request floods.'],
    ],
    slot: 3,
    evidence: [
      'shield-overview|Application layer attacks (layer 7) – This category of attack vector attempts to deny service to legitimate users by flooding an application with queries that are valid for the target, such as web request floods.',
      'waf-rate-based|A rate-based rule counts incoming requests and rate limits requests when they are coming at too fast a rate.',
      'shield-standard|Shield Standard defends against the most common, frequently occurring network and transport layer DDoS attacks that target your website or applications.',
    ],
  }),
  mr({
    id: 'watchtower-010',
    building: 'watchtower',
    bullets: ['1.2-K6', '1.2-S3'],
    d: 3,
    tags: ['placement-eligible', 'trap:shield-vs-waf'],
    stem: 'A company serves a search application through Amazon CloudFront. Attackers put malicious SQL code in query strings, and a list of known abusive IP addresses keeps sending requests. The company wants both blocked with the LEAST operational overhead. Which TWO actions meet these requirements? (Choose two.)',
    correct: [
      ['Add a SQL injection rule statement that inspects the query string to a web ACL associated with the distribution', 'The SQL injection rule statement inspects requests for malicious SQL code, and the web ACL protects the distribution.'],
      ['Add an IP set match rule that blocks the abusive addresses to the same web ACL', 'An IP set match rule statement lets you block web requests based on the IP addresses that the requests originate from.'],
    ],
    wrong: [
      ['Enable AWS Shield Standard on the distribution for the SQL injection requests', 'Shield Standard protects against network and transport layer DDoS attacks and does not inspect query strings.'],
      ['Add deny rules for the abusive addresses to the security group of the origin', 'A security group can hold allow rules only, so it cannot hold deny rules.'],
      ['Run Amazon GuardDuty to block the abusive addresses', 'GuardDuty detects suspicious activity and generates findings but does not block requests.'],
    ],
    slots: [1, 3],
    evidence: [
      'waf-sqli|An SQL injection rule statement inspects for malicious SQL code.',
      'waf-ipset|Use this to allow or block web requests based on the IP addresses that the requests originate from.',
      'waf-cloudfront|When you create a protection pack (web ACL), you can specify one or more CloudFront distributions that you want AWS WAF to inspect.',
      'vpc-sg-rules|You can specify allow rules, but not deny rules.',
    ],
  }),
  mc({
    id: 'watchtower-011',
    building: 'watchtower',
    bullets: ['1.2-K5'],
    d: 1,
    stem: 'A company wants a managed service that continuously monitors its AWS account and log data and alerts it to suspicious activity such as compromised AWS credentials. Which service is the BEST fit for the company?',
    correct: ['Amazon GuardDuty', 'GuardDuty continuously monitors AWS data sources and logs and detects threats such as compromised credentials.'],
    wrong: [
      ['Amazon Macie', 'Macie discovers sensitive data in Amazon S3 and is not the service that monitors the account for compromised credentials.'],
      ['AWS WAF', 'AWS WAF filters web requests to protected resources and does not analyze account activity.'],
      ['AWS Secrets Manager', 'Secrets Manager stores and rotates secrets and does not detect threats.'],
    ],
    slot: 0,
    evidence: [
      'guardduty|Amazon GuardDuty is a threat detection service that continuously monitors, analyzes, and processes AWS data sources and logs in your AWS environment.',
      'guardduty|Compromised and exfiltrated AWS credentials.',
    ],
  }),
  mc({
    id: 'watchtower-012',
    building: 'watchtower',
    bullets: ['1.2-S3'],
    d: 3,
    tags: ['placement-eligible'],
    stem: 'A public REST API on Amazon API Gateway is overused by a few client IP addresses. The company wants to cap the requests that each client IP address may send in a rolling five-minute period and block addresses over the cap, with other clients unaffected. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['An AWS WAF rate-based rule in a web ACL associated with the API stage', 'A rate-based rule can set the number of requests allowed by each client IP address in a trailing five-minute period.'],
    wrong: [
      ['An API Gateway usage plan with a throttling rate for the API', 'A usage plan sets limits for the clients that hold its API keys and does not work by client IP address.'],
      ['AWS Shield Advanced protection on the API Gateway REST API', 'API Gateway is not among the resource types that Shield Advanced lists, and Shield does not cap requests by client IP address.'],
      ['An AWS Lambda authorizer that counts requests per client IP address', 'It needs custom code and a store for the counts, which is more work than a managed rule.'],
    ],
    slot: 1,
    evidence: [
      'apigw-waf|For example, you can use rate-based rules to specify the number of web requests that are allowed by each client IP in a trailing, continuously updated, 5-minute period.',
      'apigw-usage-plans|A usage plan specifies who can access one or more deployed API stages and methods—and optionally sets the target request rate to start throttling requests.',
    ],
  }),
  mr({
    id: 'watchtower-013',
    building: 'watchtower',
    bullets: ['1.2-S3'],
    d: 2,
    stem: 'Applications in a VPC must reach only approved internet domains. A company wants to block a custom list of known bad domains and to pass traffic only from known AWS service domains such as Amazon S3. Which TWO capabilities meet these requirements with the LEAST operational overhead? (Choose two.)',
    correct: [
      ['An AWS Network Firewall rule that uses a custom list of known bad domains', 'Network Firewall can use custom lists of known bad domains to limit the domain names that applications can access.'],
      ['An AWS Network Firewall rule that passes traffic only from known AWS service domains or IP address endpoints', 'Network Firewall can pass traffic through only from known AWS service domains or IP address endpoints, such as Amazon S3.'],
    ],
    wrong: [
      ['A security group rule that denies the bad domain names', 'A security group can hold allow rules only, and its rules name addresses, not domains.'],
      ['Amazon Inspector findings about network exposure', 'Inspector reports vulnerabilities and unintended network exposure and does not filter traffic by domain.'],
      ['Amazon GuardDuty findings that block the domains', 'GuardDuty detects threats and generates findings and does not filter traffic.'],
    ],
    slots: [2, 4],
    evidence: [
      'network-firewall|Pass traffic through only from known AWS service domains or IP address endpoints, such as Amazon S3.',
      'network-firewall|Use custom lists of known bad domains to limit the types of domain names that your applications can access.',
      'vpc-sg-rules|You can specify allow rules, but not deny rules.',
    ],
  }),
  mc({
    id: 'watchtower-014',
    building: 'watchtower',
    bullets: ['1.2-K5'],
    d: 2,
    stem: 'Amazon GuardDuty reports unusual API activity from an IAM role. The security team wants to investigate the related user and resource interactions to find the root cause. Which service is the BEST choice for the team?',
    correct: ['Amazon Detective', 'Detective builds a dataset from log data with machine learning, statistical analysis, and graph theory to support security investigations.'],
    wrong: [
      ['Amazon Macie', 'Macie discovers sensitive data in Amazon S3 and does not investigate API activity.'],
      ['Amazon Inspector', 'Inspector scans workloads for vulnerabilities and does not investigate the cause of a finding.'],
      ['AWS Shield Advanced', 'Shield Advanced protects against DDoS attacks and does not investigate account activity.'],
    ],
    slot: 2,
    evidence: [
      'detective|Amazon Detective automatically collects log data from your AWS resources and uses machine learning (ML), statistical analysis, and graph theory to build a dataset that you can use to conduct more efficient security investigations.',
      'detective|Determine potential security issues through a unified view of user and resource interactions.',
    ],
  }),
  mc({
    id: 'watchtower-015',
    building: 'watchtower',
    bullets: ['1.2-S3'],
    d: 3,
    tags: ['placement-eligible'],
    stem: 'An Amazon API Gateway REST API has a resource policy that allows requests from a partner CIDR block. A security engineer associates an AWS WAF web ACL with the API stage, and the web ACL has a rule that blocks that same CIDR block. What happens to a request from the partner CIDR block?',
    correct: ['AWS WAF blocks the request, and the resource policy is not evaluated', 'AWS WAF rules are evaluated before resource policies, so the block takes precedence over the allow.'],
    wrong: [
      ['The resource policy allows the request, because an explicit allow overrides a block rule', 'AWS WAF is evaluated first, and its block takes precedence over the resource policy.'],
      ['API Gateway evaluates both and allows the request if either one allows it', 'The resource policy is not evaluated when AWS WAF has already blocked the request.'],
      ['The request goes to a Lambda authorizer, which makes the final decision', 'AWS WAF rules are evaluated before Lambda authorizers.'],
    ],
    slot: 3,
    evidence: [
      "apigw-waf|For example, if AWS WAF blocks access from a CIDR block that a resource policy allows, AWS WAF takes precedence and the resource policy isn't evaluated.",
      'apigw-waf|When AWS WAF is enabled on an API, AWS WAF rules are evaluated before other access control features, such as resource policies, IAM policies, Lambda authorizers, and Amazon Cognito authorizers.',
    ],
  }),
  mc({
    id: 'watchtower-016',
    building: 'watchtower',
    bullets: ['1.2-K5'],
    d: 1,
    stem: 'A company is building a mobile app and needs a managed user directory where customers can sign up and sign in, including with social identity providers such as Google. Which service meets these requirements with the LEAST effort?',
    correct: ['An Amazon Cognito user pool', 'A user pool is a user directory that authenticates users who sign in directly or through social providers.'],
    wrong: [
      ['AWS IAM Identity Center', 'IAM Identity Center connects workforce users to AWS accounts and applications and is not the directory for app customers.'],
      ['AWS Secrets Manager', 'Secrets Manager stores and rotates secrets and is not a user directory.'],
      ['Amazon GuardDuty', 'GuardDuty detects threats and does not authenticate users.'],
    ],
    slot: 0,
    evidence: [
      'cognito-what-is|Amazon Cognito is an identity platform for web and mobile apps. It’s a user directory, an authentication server, and an authorization service for OAuth 2.0 access tokens and AWS credentials.',
      'sso-what-is|AWS IAM Identity Center is the AWS solution for connecting your workforce users to AWS managed applications such as Kiro and Amazon Quick, and other AWS resources.',
    ],
  }),
  mc({
    id: 'watchtower-017',
    building: 'watchtower',
    bullets: ['1.2-K6'],
    d: 3,
    tags: ['trap:shield-vs-waf'],
    stem: 'A company runs an internet-facing Application Load Balancer. It wants application layer (layer 7) DDoS attacks against the load balancer to be mitigated automatically as they are detected, without the team writing and tuning rules. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Subscribe to AWS Shield Advanced, protect the load balancer, and enable automatic layer 7 mitigation', 'Shield Advanced can respond automatically to layer 7 attacks against protected resources by managing AWS WAF protections.'],
    wrong: [
      ['Rely on AWS Shield Standard, which defends all AWS customers automatically at the network layer', 'Shield Standard covers network and transport layer attacks, not automatic layer 7 mitigation.'],
      ['Write an AWS WAF rate-based rule and keep tuning its limit each time a new attack pattern occurs', 'It needs the team to write and tune rules, which the company wants to avoid.'],
      ['Deploy AWS Network Firewall with a stateful rule group in front of the load balancer and update the rules during each attack', 'Network Firewall filters traffic at the VPC perimeter and is not the automatic layer 7 mitigation of Shield Advanced.'],
    ],
    slot: 1,
    evidence: [
      'shield-capabilities|You can configure Shield Advanced to respond automatically to mitigate application layer (layer 7) attacks against your protected resources.',
      'shield-capabilities|With automatic mitigation, Shield Advanced enforces AWS WAF rate limiting on requests from known DDoS sources, and it automatically adds and manages custom AWS WAF protections in response to detected DDoS attacks.',
      'shield-protected-resources|Application Load Balancers.',
    ],
  }),
  mr({
    id: 'watchtower-018',
    building: 'watchtower',
    bullets: ['1.2-K5'],
    d: 2,
    stem: 'A company stores customer files in Amazon S3 and runs workloads in several accounts. The security team must discover personal data in the S3 buckets and must detect compromised AWS credentials in the accounts. Which TWO services meet these requirements? (Choose two.)',
    correct: [
      ['Amazon Macie', 'Macie discovers sensitive data in Amazon S3 by using machine learning and pattern matching.'],
      ['Amazon GuardDuty', 'GuardDuty can detect compromised and exfiltrated AWS credentials.'],
    ],
    wrong: [
      ['Amazon Inspector', 'Inspector scans workloads for software vulnerabilities and unintended network exposure.'],
      ['Amazon Detective', 'Detective helps investigate findings and does not discover sensitive data or detect threats.'],
      ['AWS Shield Advanced', 'Shield Advanced protects resources against DDoS attacks.'],
    ],
    slots: [0, 3],
    evidence: [
      'macie|Amazon Macie is a data security service that discovers sensitive data by using machine learning and pattern matching, provides visibility into data security risks, and enables automated protection against those risks.',
      'guardduty|Compromised and exfiltrated AWS credentials.',
    ],
  }),
  mc({
    id: 'watchtower-019',
    building: 'watchtower',
    bullets: ['1.2-K6'],
    d: 2,
    tags: ['placement-eligible', 'trap:shield-vs-waf'],
    stem: 'A small company serves a static website through Amazon CloudFront and wants protection from common network and transport layer DDoS attacks. The company does not want an additional subscription or setup. What is the SIMPLEST way to protect the site?',
    correct: ['Use AWS Shield Standard, which already covers CloudFront distributions at no extra charge', 'Shield Standard gives all AWS customers automatic protection, and CloudFront distributions get comprehensive availability protection from it.'],
    wrong: [
      ['Subscribe to AWS Shield Advanced and add protection to the CloudFront distribution for the network layers', 'It is an extra subscription, and the company only needs protection that is already included.'],
      ['Create an AWS WAF web ACL with a rate-based rule and associate it with the distribution', 'A rate-based rule limits request floods at the application layer and needs setup, and Shield Standard already covers the network and transport layers.'],
      ['Deploy AWS Network Firewall in a VPC in front of the distribution to filter the traffic', 'Network Firewall protects a VPC and is extra setup that a CloudFront distribution does not need for this.'],
    ],
    slot: 2,
    evidence: [
      'shield-standard|All AWS customers benefit from the automatic protection of Shield Standard, at no additional charge.',
      'shield-standard|While Shield Standard helps protect all AWS customers, you get particular benefit with Amazon Route 53 hosted zones, Amazon CloudFront distributions, and AWS Global Accelerator standard accelerators. These resources receive comprehensive availability protection against all known network and transport layer attacks.',
    ],
  }),
  mr({
    id: 'watchtower-020',
    building: 'watchtower',
    bullets: ['1.2-S3'],
    d: 2,
    tags: ['trap:secrets-manager-vs-parameter-store'],
    stem: 'An application on Amazon EC2 has a database password hard coded in its source code. The security team wants the hard-coded credential removed and the password rotated automatically on a schedule, with no application redeployment for each rotation. Which TWO actions meet these requirements in the MOST secure way? (Choose two.)',
    correct: [
      ['Store the credential in AWS Secrets Manager and configure an automatic rotation schedule', 'Secrets Manager can rotate credentials on an automatic schedule, so rotating no longer needs changes to the application.'],
      ['Change the application to retrieve the credential from Secrets Manager at runtime', 'Replacing hard-coded credentials with a runtime call lets the application get credentials dynamically when it needs them.'],
    ],
    wrong: [
      ['Store the password in an environment variable of the instance and change it each quarter', 'It keeps a long-term secret outside a managed rotation, and every change needs manual effort.'],
      ['Store the password as a plain string parameter in AWS Systems Manager Parameter Store', 'AWS recommends Secrets Manager for credentials that need rotation.'],
      ['Encrypt the password in a file in Amazon S3 and download it at startup', 'It adds custom work and has no rotation schedule.'],
    ],
    slots: [1, 4],
    evidence: [
      'secrets-intro|With Secrets Manager, you can configure an automatic rotation schedule for your secrets.',
      'secrets-intro|You replace hard-coded credentials with a runtime call to the Secrets Manager service to retrieve credentials dynamically when you need them.',
      'ssm-parameter-store|If you manage credentials such as usernames, passwords, or any other secrets, we recommend using AWS Secrets Manager.',
    ],
  }),
  mc({
    id: 'watchtower-021',
    building: 'watchtower',
    bullets: ['1.2-S3'],
    d: 1,
    stem: 'A company wants to give its workforce users single sign-on access to several AWS accounts and AWS managed applications, managed centrally. Which AWS service BEST meets these requirements?',
    correct: ['AWS IAM Identity Center', 'IAM Identity Center connects workforce users to AWS accounts and AWS managed applications and manages their access centrally.'],
    wrong: [
      ['Amazon Cognito user pools', 'User pools are a directory for the customers of a web or mobile app and not the service for workforce access to AWS accounts.'],
      ['AWS Secrets Manager', 'Secrets Manager stores and rotates secrets and does not provide sign-on.'],
      ['AWS Firewall Manager', 'Firewall Manager applies firewall protections across accounts and does not provide sign-on.'],
    ],
    slot: 3,
    evidence: [
      'sso-what-is|AWS IAM Identity Center is the AWS solution for connecting your workforce users to AWS managed applications such as Kiro and Amazon Quick, and other AWS resources.',
      'sso-what-is|IAM Identity Center streamlines and simplifies workforce user access to applications or AWS accounts, or both, through the following key capabilities.',
    ],
  }),
  mc({
    id: 'watchtower-022',
    building: 'watchtower',
    bullets: ['1.2-K5'],
    d: 2,
    stem: 'A company wants Amazon Macie to give broad visibility into where sensitive data might be in all of its Amazon S3 buckets, and also a deeper, more targeted analysis of one bucket. Which Macie features meet these requirements?',
    correct: ['Automated discovery for all buckets and a discovery job for the one bucket', 'Automated discovery gives broad visibility, and a discovery job gives deeper, more targeted analysis.'],
    wrong: [
      ['A sensitive data discovery job for every bucket and automated discovery for none', 'A job for every bucket gives targeted analysis and not broad, continuous visibility for all of them.'],
      ['Automated sensitive data discovery for all buckets and for the one bucket', 'Automated discovery uses sampling and does not give the deeper, targeted analysis.'],
      ['A Security Hub CSPM control check for the one bucket and none for the others', 'Security Hub CSPM runs checks against security controls and does not discover sensitive data.'],
    ],
    slot: 0,
    evidence: [
      'macie|Automated sensitive data discovery provides broad visibility into where sensitive data might reside in your Amazon S3 data estate.',
      'macie|Sensitive data discovery jobs provide deeper, more targeted analysis.',
    ],
  }),
  mc({
    id: 'watchtower-023',
    building: 'watchtower',
    bullets: ['1.2-S3'],
    d: 2,
    tags: ['placement-eligible'],
    stem: 'A company uses AWS Organizations and runs Amazon CloudFront distributions in many accounts. The security team wants an AWS WAF web ACL applied to every CloudFront distribution in every account, including distributions created later, managed from one place with the LEAST effort. Which solution meets these requirements?',
    correct: ['Use AWS Firewall Manager with an AWS WAF policy for all CloudFront distributions in the organization', 'Firewall Manager protects all resources of a type, such as all CloudFront distributions, and adds protection to new resources automatically.'],
    wrong: [
      ['Create and associate a web ACL by hand in each account, and repeat that step whenever a distribution is added', 'It repeats manual work in every account and leaves new distributions unprotected until someone acts.'],
      ['Subscribe each account to AWS Shield Advanced and rely on it to apply the web ACL', 'Shield Advanced protects resources that you add and is not the service that applies a web ACL across accounts.'],
      ['Enable Amazon GuardDuty in every account to block requests to the distributions', 'GuardDuty detects threats and generates findings and does not apply a web ACL.'],
    ],
    slot: 1,
    evidence: [
      'firewall-manager|Helps to protect all resources of a particular type, such as all Amazon CloudFront distributions',
      'firewall-manager|Automatically adds protection to resources that are added to your account',
    ],
  }),
  // Reserve questions
  mc({
    id: 'watchtower-024',
    building: 'watchtower',
    bullets: ['1.2-K5'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'Users of a mobile app sign in with an Amazon Cognito user pool. After sign-in, the app must upload files directly to Amazon S3 using temporary, limited-privilege AWS credentials. What should the architect add to meet this requirement?',
    correct: ['An Amazon Cognito identity pool that exchanges the user pool token for AWS credentials', 'An identity pool exchanges a trusted token for temporary, limited-privilege AWS credentials.'],
    wrong: [
      ['An IAM user for every app user, with long-term access keys stored in the app', 'It would put long-term credentials in the app and does not use the sign-in token.'],
      ['An AWS WAF web ACL on the user pool that issues the credentials', 'AWS WAF filters web requests and does not issue AWS credentials.'],
      ['An AWS Secrets Manager secret that the app reads before each upload', 'A shared secret does not give each signed-in user temporary, limited-privilege credentials.'],
    ],
    slot: 2,
    evidence: [
      'cognito-what-is|An identity pool exchanges a trusted token (from a user pool, a social provider, or a SAML or OIDC provider) for temporary, limited-privilege AWS credentials so that your app can call services like Amazon S3 and Amazon DynamoDB on the user’s behalf.',
    ],
  }),
  mc({
    id: 'watchtower-025',
    building: 'watchtower',
    bullets: ['1.2-K6'],
    d: 3,
    tags: ['mock-reserve', 'trap:shield-vs-waf'],
    stem: 'A game backend runs behind a Network Load Balancer that uses Elastic IP addresses. The company wants expanded DDoS protection for the backend. Which solution meets this requirement?',
    correct: ['Subscribe to AWS Shield Advanced and add protection to the load balancer Elastic IP addresses', 'Shield Advanced protects Network Load Balancers through their association with Elastic IP addresses that you add.'],
    wrong: [
      ['Rely on AWS Shield Standard because it provides expanded protection for all resources in the account', 'Shield Standard gives the baseline protection, and expanded protection needs a Shield Advanced subscription.'],
      ['Subscribe to AWS Shield Advanced and expect it to protect every resource automatically', 'Shield Advanced does not protect resources automatically, so each resource must be added.'],
      ['Associate an AWS WAF web ACL with the Network Load Balancer', 'AWS WAF lists Application Load Balancers among its protected resource types, not Network Load Balancers.'],
    ],
    slot: 3,
    evidence: [
      'shield-protected-resources|Network Load Balancers, through associations to Amazon EC2 Elastic IP addresses.',
      "shield-protected-resources|Shield Advanced doesn't automatically protect your resources.",
      'shield-advanced|When you subscribe to Shield Advanced and add protection to your resources, Shield Advanced provides expanded DDoS attack protection for those resources.',
    ],
  }),
  mc({
    id: 'watchtower-026',
    building: 'watchtower',
    bullets: ['1.2-S3'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A company must inspect the traffic that enters and leaves its VPC subnets, using intrusion prevention rules that are compatible with Suricata. The company wants a managed service. Which solution BEST meets these requirements?',
    correct: ['AWS Network Firewall', 'Network Firewall is a managed, stateful firewall with intrusion detection and prevention that supports Suricata compatible rules.'],
    wrong: [
      ['AWS WAF', 'AWS WAF monitors HTTP(S) requests to protected web application resources and is not a VPC traffic firewall.'],
      ['Security groups on the instances', 'Security groups allow traffic by protocol, port, and source and do not provide intrusion prevention rules.'],
      ['AWS Shield Standard', 'Shield Standard defends against DDoS attacks and does not apply Suricata rules.'],
    ],
    slot: 0,
    evidence: [
      'network-firewall|AWS Network Firewall is a stateful, managed, network firewall and intrusion detection and prevention service for your virtual private cloud (VPC) that you create in Amazon Virtual Private Cloud (Amazon VPC).',
      'network-firewall|Network Firewall uses the open source intrusion prevention system (IPS), Suricata, for stateful inspection, and supports Suricata compatible rules.',
    ],
  }),
];

export default questions;
