import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'lookout-tower',
  overview: [
    b('This is a primer. Three AWS services answer three different questions about a running system, and later buildings assume you can tell them apart. **Amazon CloudWatch** answers "how is it performing?", **AWS CloudTrail** answers "who did what?", and **AWS Config** answers "what does it look like, and how did that change?". Depth lives in Tide Gauges (metrics, tracing and availability) and Compliance Registry (governance and compliance).',
      ['cw-what-is', 'cloudtrail-what-is', 'config-what-is'],
      ['cw-what-is|Operational visibility with metrics, alarms, and dashboards',
       'cloudtrail-what-is|Actions taken by a user, role, or an AWS service are recorded as events in CloudTrail.',
       'config-what-is|AWS Config provides a detailed view of the configuration of AWS resources in your AWS account.'],
      { allow: ['three'] }),
    b('CloudWatch collects {{term:metric|metrics}} (performance data at intervals you choose), raises {{term:alarm|alarms}} when a threshold is breached, and gathers logs. Alarms can send a notification or automatically make changes to the resources you are monitoring.',
      ['cw-what-is', 'cw-alarms'],
      ['cw-what-is|Metrics collect and track key performance data at user-defined intervals.',
       'cw-alarms|You can create alarms that watch metrics and send notifications or automatically make changes to the resources you are monitoring when a threshold is breached.']),
    b('CloudWatch Logs lets you monitor, store and access log files from sources such as EC2 instances, CloudTrail and Route 53. Logs live in a {{term:log-group}}, which sets retention, monitoring and access control for the streams inside it.',
      ['cwl-what-is', 'cwl-concepts'],
      ['cwl-what-is|You can use Amazon CloudWatch Logs to monitor, store, and access your log files from Amazon Elastic Compute Cloud (Amazon EC2) instances, AWS CloudTrail, Route 53, and other sources.',
       'cwl-concepts|Log groups define groups of log streams that share the same retention, monitoring, and access control settings.']),
    b('CloudTrail records the actions taken by users, roles and AWS services as {{term:cloudtrail-event|CloudTrail events}}, including actions in the console, CLI, SDKs and APIs. Event history gives a viewable, searchable record of the past 90 days of management events in a Region; a trail is how you keep events beyond that.',
      ['cloudtrail-what-is', 'cloudtrail-concepts'],
      ['cloudtrail-what-is|Event history – The Event history provides a viewable, searchable, downloadable, and immutable record of the past 90 days of management events in an AWS Region.',
       'cloudtrail-what-is|Events include actions taken in the AWS Management Console, AWS Command Line Interface, and AWS SDKs and APIs.',
       'cloudtrail-concepts|By default, trails and event data stores log management events, but not data or Insights events.']),
    b('AWS Config records how your resources are configured and how that changed over time, and it can evaluate them against {{term:config-rule|Config rules}} that represent your ideal configuration settings. It does not watch performance and it is not an API log.',
      ['config-what-is', 'config-rules'],
      ['config-what-is|how they were configured in the past so that you can see how the configurations and relationships change over time',
       'config-rules|You do this by creating AWS Config rules, which represent your ideal configuration settings.']),
  ],
  bullets: [],
  cues: [
    cue('who made this API call / who deleted the resource', 'AWS CloudTrail',
      b('CloudTrail records actions taken by a user, role or AWS service as events.', 'cloudtrail-what-is',
        ['Actions taken by a user, role, or an AWS service are recorded as events in CloudTrail.'])),
    cue('how has this resource\'s configuration changed / is it compliant with our rules', 'AWS Config',
      b('AWS Config shows how resources were configured in the past and how configurations and relationships change over time, and it evaluates them against rules.', 'config-what-is',
        ['how they were configured in the past so that you can see how the configurations and relationships change over time'])),
    cue('notify me when CPU or another metric crosses a limit', 'CloudWatch alarm',
      b('A CloudWatch alarm watches a metric and sends a notification or acts automatically when a threshold is breached.', 'cw-alarms',
        ['You can create alarms that watch metrics and send notifications or automatically make changes to the resources you are monitoring when a threshold is breached.'])),
    cue('centralise application and system logs', 'CloudWatch Logs',
      b('CloudWatch Logs lets you see all of your logs, regardless of their source, as a single consistent flow of events ordered by time.', 'cwl-what-is',
        ['CloudWatch Logs enables you to see all of your logs, regardless of their source, as a single and consistent flow of events ordered by time.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Monitor',
      aws: 'Amazon CloudWatch (and AWS X-Ray)',
      mapping: b('Azure Monitor is the service you already know for collecting and acting on telemetry; the Learn comparison pairs it with CloudWatch and X-Ray.',
        ['learn-hub', 'cw-what-is'],
        ['learn-hub|Azure Monitor is a comprehensive solution that you can use to collect, analyze, and act on telemetry from your cloud and on-premises environments.',
         'cw-what-is|Operational visibility with metrics, alarms, and dashboards']),
      breaks: b('The Learn row pairs Azure Monitor with two AWS services, CloudWatch and X-Ray. In AWS, metrics, alarms and logs are CloudWatch; request tracing is the separate AWS X-Ray service, covered in Tide Gauges.',
        ['learn-hub', 'cw-what-is'],
        ['learn-hub|Amazon CloudWatch and AWS X-Ray', 'cw-what-is|Operational visibility with metrics, alarms, and dashboards'],
        { allow: ['two'] }),
    },
    {
      concept: 'Azure activity log',
      aws: 'AWS CloudTrail',
      mapping: b('The Azure activity log records subscription-level events such as a resource being modified or a VM being started. CloudTrail plays the same audit role by recording who did what to your AWS resources.',
        ['learn-hub', 'cloudtrail-what-is'],
        ['learn-hub|The activity log is a platform log in Azure that provides insight into subscription-level events, like when a resource is modified or when a VM is started.',
         'cloudtrail-what-is|Actions taken by a user, role, or an AWS service are recorded as events in CloudTrail.']),
      breaks: b('The scopes differ. The Azure activity log is described at subscription level, whereas CloudTrail Event history is a record of the past 90 days of management events in one Region, and keeping more means creating a trail.',
        ['learn-hub', 'cloudtrail-what-is'],
        ['learn-hub|provides insight into subscription-level events',
         'cloudtrail-what-is|record of the past 90 days of management events in an AWS Region']),
    },
    {
      concept: 'Azure Policy and Change Analysis',
      aws: 'AWS Config',
      mapping: b('The Learn comparison pairs AWS Config with Azure Policy and Change Analysis. All of them are about knowing how resources are configured and whether that matches your intent.',
        ['learn-hub', 'config-what-is'],
        ['learn-hub|Azure Policy helps you implement governance for resource consistency, regulatory compliance, security, cost, and management.',
         'config-what-is|AWS Config provides a detailed view of the configuration of AWS resources in your AWS account.']),
      breaks: b('One AWS service maps to two Azure features here. AWS Config both records configuration history and evaluates resources against rules, which is why Learn lists Azure Policy and Change Analysis together.',
        ['learn-hub', 'config-rules'],
        ['learn-hub|Azure Policy Change Analysis', 'config-rules|You do this by creating AWS Config rules, which represent your ideal configuration settings.'],
        { allow: ['two'] }),
    },
  ],
};

export default notes;
