import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'backup-archive',
  overview: [
    b('Backups cost money in several ways: how much is stored, how long it is kept, and which tier it sits in. Cost-effective backup design keeps only what the recovery requirement needs, stores changes rather than full copies where possible, and moves old backups to a cheaper tier. Archive Annex covers the compliance side (immutability and retention rules); Disaster Bunker covers how backups fit the recovery strategies.',
      ['backup-what-is', 'ebs-snapshots', 'ebs-snapshot-archive'],
      ['backup-what-is|AWS Backup is a fully-managed service that makes it easy to centralize and automate data protection across AWS services, in the cloud, and on premises.',
       'ebs-snapshots|This minimizes the time required to create the snapshot and saves on storage costs by not duplicating data.',
       'ebs-snapshot-archive|Amazon EBS Snapshots Archive is a storage tier that you can use for low-cost, long-term storage of your rarely-accessed snapshots that do not need frequent or fast retrieval.']),
  ],
  bullets: [
    {
      id: '4.1-K5',
      concepts: [
        b('A backup strategy decides what to back up, how often, where the copies live and how long they are kept. How often you back up determines the recovery point you can achieve, and AWS does not automatically back up the data on your EBS volumes: it is your responsibility to create snapshots regularly or automate them with Amazon Data Lifecycle Manager or AWS Backup.',
          ['dr-options', 'ebs-snapshots'],
          ['dr-options|How often you run your backup will determine your achievable recovery point (which should align to meet your RPO).',
           'ebs-snapshots|AWS does not automatically back up the data stored on your EBS volumes.',
           'ebs-snapshots|For data resiliency and disaster recovery, it is your responsibility to create EBS snapshots on a regular basis, or to set up automatic snapshot creation by using Automate backups with Amazon Data Lifecycle Manager or AWS Backup.']),
        b('Incremental backups keep storage costs down. An EBS snapshot is incremental: it saves only the blocks that changed since the most recent snapshot, which saves time and storage cost. AWS Backup also stores periodic backups incrementally for supported resource types: the first backup is a full copy and later backups store only changes; resource types that do not support incremental backups store a full copy every time, which can result in higher storage costs.',
          ['ebs-snapshots', 'backup-what-is'],
          ['ebs-snapshots|incremental backup, which means that we save only the blocks on the volume that have changed since the most recent snapshot.',
           'backup-what-is|The first backup of an AWS resource backs up a full copy of your data. For each successive incremental backup, only the changes to your AWS resources are backed up.',
           'backup-what-is|For resources that do not support incremental backups, each backup is a full copy, which can result in higher storage costs.']),
        b('Amazon RDS takes automated backups during the backup window and keeps them for the backup retention period you specify, so you can recover to any point in time within that period; manual DB snapshots are kept until you delete them.',
          'rds-automated-backups',
          ['Amazon RDS creates and saves automated backups of your DB instance or Multi-AZ DB cluster during the backup window of your DB instance.',
           'RDS saves the automated backups of your DB instance according to the backup retention period that you specify.',
           'If necessary, you can recover your DB instance to any point in time during the backup retention period.']),
        b('AWS Backup centralises policy-based backups using backup plans that define your requirements and apply to resources across services, and backups can be copied to other Regions on demand or as part of a scheduled plan.',
          'backup-what-is',
          ['Use these backup plans to define your backup requirements and then apply them to the AWS resources that you want to protect across the AWS services that you use.',
           'Using AWS Backup, you can copy backups to multiple different AWS Regions on demand or automatically as part of a scheduled backup plan.']),
      ],
      services: ['AWS Backup', 'Amazon S3 Glacier'],
      design: [
        b('Cue: "meet the RPO with the least storage" → incremental snapshots and backups on the schedule the RPO needs; "keep daily backups for a month" → retention setting in the backup plan or RDS retention period.',
          ['dr-options', 'ebs-snapshots'],
          ['dr-options|How often you run your backup will determine your achievable recovery point (which should align to meet your RPO).',
           'ebs-snapshots|This minimizes the time required to create the snapshot and saves on storage costs by not duplicating data.']),
      ],
    },
    {
      id: '4.1-S6',
      concepts: [
        b('For backups you rarely need, EBS Snapshots Archive is a lower-cost tier for rarely accessed snapshots that do not need frequent or fast retrieval: snapshots in the standard tier are incremental, and archiving converts the incremental snapshot to a full snapshot in the archive tier.',
          'ebs-snapshot-archive',
          ['Amazon EBS Snapshots Archive is a storage tier that you can use for low-cost, long-term storage of your rarely-accessed snapshots that do not need frequent or fast retrieval.',
           'Snapshots stored in the standard tier are incremental.',
           'When you archive a snapshot, the incremental snapshot is converted to a full snapshot, and it is moved from the standard tier to the Amazon EBS Snapshots Archive tier (archive tier).']),
        b('Archiving is not always cheaper. The minimum archive period is 90 days, and deleting or permanently restoring an archived snapshot before then is billed for the remaining days. It can take up to 72 hours to restore an archived snapshot to the standard tier, restores are billed, and archived snapshots are always full snapshots, which will likely be larger than the incremental snapshot they were created from. AWS describes the saving as applying to snapshots you plan to store for at least the minimum period and rarely need to access.',
          ['ebs-archive-considerations', 'ebs-archive-pricing', 'ebs-snapshot-archive'],
          ['ebs-archive-considerations|The minimum archive period is 90 days.',
           'ebs-archive-considerations|If you delete or permanently restore an archived snapshot before the minimum archive period of 90 days, you are billed for remaining days in the archive tier, rounded to the nearest hour.',
           'ebs-archive-considerations|It can take up to 72 hours to restore an archived snapshot from the archive tier to the standard tier, depending on the size of the snapshot.',
           'ebs-archive-considerations|Archived snapshots are always full snapshots.',
           'ebs-archive-considerations|The full snapshot will likely be larger than the incremental snapshot from which it was created.',
           'ebs-archive-pricing|Snapshot restores are billed at a rate of',
           'ebs-snapshot-archive|for snapshots that you plan to store for 90 days or longer and that you rarely need to access.']),
        b('AWS Backup has its own cold tier: the backup plan lifecycle can transition eligible resource types to cold storage on a timetable within the total retention period, and to use cold storage the total retention period must be at least 90 days. AWS recommends not moving a backup to cold storage until after at least 8 days, because a transition that is too early makes AWS Backup create another warm full backup.',
          'backup-create-plan',
          ['Cold storage: Select this box to let eligible resource types transition to cold storage in accordance with the timetable you specify in the total retention period.',
           'To use cold storage, you must have a total retention period of 90 days or greater.',
           'AWS Backup recommends that you set your lifecycle settings to not move your backup to cold storage until after at least 8 days.',
           'If the full backup is transitioned to cold storage too soon (for example, a transition to cold storage after 1 day), AWS Backup will create another warm full backup.']),
        b('For file and object backups in S3, archive classes provide the cold tier: S3 Glacier Flexible Retrieval and Deep Archive for long-term archives (Cold Cellar), and Tape Gateway lets you cost-effectively and durably archive backup data in those classes.',
          'sgw-tape',
          ['With Tape Gateway, you can cost-effectively and durably archive backup data in S3 Glacier Flexible Retrieval or S3 Glacier Deep Archive.']),
        b('Choosing between backup and archive: backup protects against loss or corruption and is restored to resume operations (retention measured by the recovery need); archive keeps data for long-term retention that is rarely retrieved. AWS Backup handles the first across services, and the Glacier classes serve the second.',
          ['backup-what-is', 's3-glacier-classes'],
          ['backup-what-is|AWS Backup is a fully-managed service that makes it easy to centralize and automate data protection across AWS services, in the cloud, and on premises.',
           's3-glacier-classes|Storage classes designed for less frequent access patterns with longer retrieval times offer lower storage costs.']),
      ],
      services: ['AWS Backup', 'Amazon S3 Glacier'],
      design: [
        b('Cue: "central backup of EC2, EBS, RDS and EFS with one policy" → AWS Backup; "old EBS snapshots must be kept cheaply for years and rarely restored" → Snapshots Archive (minimum archive period, slow restore); "AWS Backup recoveries kept for months" → lifecycle to cold storage; "backup application writes to tape" → Tape Gateway; "long-term archive in S3" → Glacier classes.',
          ['backup-what-is', 'ebs-snapshot-archive', 'sgw-tape'],
          ['backup-what-is|Use these backup plans to define your backup requirements and then apply them to the AWS resources that you want to protect across the AWS services that you use.',
           'ebs-snapshot-archive|Amazon EBS Snapshots Archive is a storage tier that you can use for low-cost, long-term storage of your rarely-accessed snapshots that do not need frequent or fast retrieval.',
           'sgw-tape|Tape Gateway provides cloud-backed virtual tape storage.']),
      ],
    },
  ],
  cues: [
    cue('back up many AWS services centrally with one policy', 'AWS Backup (backup plans)',
      b('Backup plans define backup requirements and apply to resources across services.', 'backup-what-is',
        ['Use these backup plans to define your backup requirements and then apply them to the AWS resources that you want to protect across the AWS services that you use.'])),
    cue('reduce backup storage: only changes after the first backup', 'Incremental snapshots and backups',
      b('Incremental backups store only the changes after the first full copy.', 'backup-what-is',
        ['The first backup of an AWS resource backs up a full copy of your data. For each successive incremental backup, only the changes to your AWS resources are backed up.'])),
    cue('old EBS snapshots must be kept long-term at low cost', 'EBS Snapshots Archive',
      b('Snapshots Archive is low-cost, long-term storage for rarely accessed snapshots.', 'ebs-snapshot-archive',
        ['Amazon EBS Snapshots Archive is a storage tier that you can use for low-cost, long-term storage of your rarely-accessed snapshots that do not need frequent or fast retrieval.'])),
    cue('restore the database to any point in time in the last N days', 'RDS automated backups with a retention period',
      b('RDS lets you recover to any point in time during the backup retention period.', 'rds-automated-backups',
        ['If necessary, you can recover your DB instance to any point in time during the backup retention period.'])),
    cue('backup software that writes to tapes, archive in the cloud', 'Tape Gateway',
      b('Tape Gateway archives backup data cost-effectively in Glacier Flexible Retrieval or Deep Archive.', 'sgw-tape',
        ['With Tape Gateway, you can cost-effectively and durably archive backup data in S3 Glacier Flexible Retrieval or S3 Glacier Deep Archive.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Backup',
      aws: 'AWS Backup',
      mapping: b('Learn pairs AWS Backup with Azure Backup, used to back up and recover files, databases, disks and virtual machines.',
        ['learn-storage', 'backup-what-is'],
        ['learn-storage|Backup Backup This option is used to back up and recover files, databases, disks, and virtual machines.',
         'backup-what-is|AWS Backup is a fully-managed service that makes it easy to centralize and automate data protection across AWS services, in the cloud, and on premises.']),
      breaks: b('On AWS, EBS Snapshots Archive is a storage tier for low-cost, long-term storage of rarely-accessed snapshots. Learn pairs AWS Backup with Azure Backup by function, backing up and recovering files, databases, disks and virtual machines, and has no pairing for EBS Snapshots Archive.',
        ['ebs-snapshot-archive', 'learn-storage'],
        ['ebs-snapshot-archive|Amazon EBS Snapshots Archive is a storage tier that you can use for low-cost, long-term storage of your rarely-accessed snapshots that do not need frequent or fast retrieval.',
         'learn-storage|Backup Backup This option is used to back up and recover files, databases, disks, and virtual machines.']),
    },
    {
      concept: 'Storage archive access tier',
      aws: 'S3 Glacier storage classes',
      mapping: b('Learn pairs Azure Archive Blob Storage with AWS Glacier for rarely accessed data that can tolerate several hours of retrieval latency.',
        ['learn-storage', 's3-glacier-classes'],
        ['learn-storage|Azure Archive Blob Storage is comparable to AWS Glacier storage service.',
         'learn-storage|It\'s intended for rarely accessed data that is stored for at least 180 days and can tolerate several hours of retrieval latency.',
         's3-glacier-classes|Storage classes designed for less frequent access patterns with longer retrieval times offer lower storage costs.']),
      breaks: b('Learn pairs S3 Glacier with the Azure cold access tier, where access times remain in the milliseconds, and S3 Glacier Deep Archive with the archive access tier, where it can take hours to retrieve data. On AWS, the Glacier classes range from Instant Retrieval with millisecond retrieval to Flexible Retrieval at minutes to 12 hours and Deep Archive at 9 to 48 hours (Cold Cellar).',
        ['s3-glacier-classes', 'learn-storage'],
        ['s3-glacier-classes|S3 Glacier Instant Retrieval 90 days Quarterly Milliseconds No S3 Glacier Flexible Retrieval 90 days Semi-annually Minutes to 12 hours Yes S3 Glacier Deep Archive 180 days Annually 9 to 48 hours Yes',
         'learn-storage|S3 Glacier Cold access storage tier Cold storage has lower storage costs and higher access costs. Access times remain in the milliseconds.',
         'learn-storage|S3 Glacier Deep Archive Storage archive access tier Archive storage has the lowest storage cost and higher data retrieval costs. It can take hours to retrieve data.']),
    },
  ],
};

export default notes;
