import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'capacity-meter',
  overview: [
    b('Database cost grows with the capacity you provision and the work you ask the database to do. Several levers reduce it without changing what the application does: plan capacity to the load (capacity units for DynamoDB, instance class for RDS), put a cache in front so repeated reads never reach the database, pool connections so the database does not need more capacity just to hold them, and move read traffic to replicas. Each lever has its own cost, so the exam asks which one fits the problem.',
      ['dynamodb-capacity', 'elasticache-strategies', 'rds-proxy-planning', 'rds-read-replicas'],
      ['dynamodb-capacity|In Amazon DynamoDB, you can choose between on-demand mode and provisioned mode for your tables to accommodate different workload requirements.',
       'elasticache-strategies|Amazon ElastiCache is an in-memory key-value store that sits between your application and the data store (database) that it accesses.',
       'rds-proxy-planning|The proxy enables applications to open many client connections, while the proxy manages a smaller number of long-lived connections to the DB instance .',
       'rds-read-replicas|You can reduce the load on your primary DB instance by routing queries from your applications to the read replica.']),
  ],
  beyondProject: [
    b('Your project uses DynamoDB. For provisioned mode the SAA step is reading capacity units. For an item up to 4 KB, one read capacity unit represents one strongly consistent read per second, or two eventually consistent reads per second, so an eventually consistent read needs half the read capacity. AWS says to consider provisioned capacity if you have steady workloads with predictable growth and can reliably forecast capacity requirements; otherwise on-demand mode avoids capacity planning.',
      ['dynamodb-provisioned', 'dynamodb-capacity'],
      ['dynamodb-provisioned|For an item up to 4 KB, one read capacity unit (RCU) represents one strongly consistent read operation per second, or two eventually consistent read operations per second.',
       'dynamodb-capacity|You can choose to use provisioned capacity if you have steady workloads with predictable growth, and if you can reliably forecast capacity requirements for your application.'],
      { allow: ['two'] }),
  ],
  bullets: [
    {
      id: '4.3-K3',
      concepts: [
        b('A cache is an in-memory key-value store between the application and its database. On a request the application asks the cache first and reads the database only on a miss, so repeated reads stop costing database capacity. In lazy loading only requested data is cached, which avoids filling the cache with data that is never requested; the cost is a cache miss penalty.',
          'elasticache-strategies',
          ['Amazon ElastiCache is an in-memory key-value store that sits between your application and the data store (database) that it accesses.',
           'Only requested data is cached.',
           'Because most data is never requested, lazy loading avoids filling up the cache with data that isn\'t requested.',
           'The disadvantages of lazy loading are as follows: There is a cache miss penalty.']),
        b('For DynamoDB, DAX is a managed in-memory cache that is API-compatible with DynamoDB. For read-heavy or bursty workloads it provides increased throughput and potential operational cost savings by reducing the need to overprovision read capacity units. It helps eventually consistent reads: if a request specifies strongly consistent reads, DAX passes the request through to DynamoDB.',
          ['dax', 'dax-concepts'],
          ['dax|DAX reduces operational and application complexity by providing a managed service that is API-compatible with DynamoDB.',
           'dax|For read-heavy or bursty workloads, DAX provides increased throughput and potential operational cost savings by reducing the need to overprovision read capacity units.',
           'dax-concepts|If the request specifies strongly consistent reads, DAX passes the request through to DynamoDB.']),
      ],
      services: ['Amazon ElastiCache', 'Amazon DynamoDB'],
      design: [
        b('Cue: "the same items are read over and over and the database is the bottleneck" → ElastiCache in front of the database; "DynamoDB read-heavy, avoid overprovisioning read capacity" → DAX. A cache adds cost of its own, so the case for it is that it avoids a larger or more provisioned database.',
          ['elasticache-strategies', 'dax'],
          ['elasticache-strategies|Amazon ElastiCache is an in-memory key-value store that sits between your application and the data store (database) that it accesses.',
           'dax|For read-heavy or bursty workloads, DAX provides increased throughput and potential operational cost savings by reducing the need to overprovision read capacity units.']),
      ],
    },
    {
      id: '4.3-K5',
      concepts: [
        b('DynamoDB capacity is chosen as on-demand mode or provisioned mode, and the throughput mode determines how the capacity is managed and how you are charged for reads and writes. In provisioned mode you specify throughput in capacity units, can change them later, or enable auto scaling to modify them automatically. Throughput requests that exceed the table\'s throughput are throttled.',
          ['dynamodb-capacity', 'dynamodb-provisioned'],
          ['dynamodb-capacity|A table’s throughput mode determines how the capacity of a table is managed.',
           'dynamodb-capacity|Throughput mode also determines how you\'re charged for the read and write operations on your tables.',
           'dynamodb-provisioned|You can modify these settings later, if needed, or enable DynamoDB auto scaling to modify them automatically.',
           'dynamodb-provisioned|Throughput requests that exceed the default table throughput quota are throttled.']),
        b('Provisioned capacity fits steady workloads with predictable growth, because you pay for the capacity you set; on-demand mode removes the planning and, with pay-per-request pricing, you pay only for the throughput you use.',
          ['dynamodb-capacity', 'dynamodb-ondemand'],
          ['dynamodb-capacity|You can choose to use provisioned capacity if you have steady workloads with predictable growth, and if you can reliably forecast capacity requirements for your application.',
           'dynamodb-ondemand|With pay-per-request pricing, you don’t have to worry about idle capacity because you only pay for the throughput you actually use.']),
        b('Some DynamoDB cost levers are not about throughput. The Standard-Infrequent Access table class is optimised for tables where storage is the dominant cost, such as old order history or logs, while the default Standard table class is recommended for the vast majority of workloads. Time to Live deletes items that are no longer relevant without consuming write throughput. For steady provisioned capacity you can buy reserved capacity, which is charged at a reserved rate for capacity used up to the amount you purchased.',
          ['dynamodb-table-classes', 'dynamodb-ttl', 'dynamodb-pricing'],
          ['dynamodb-table-classes|The DynamoDB Standard table class is the default, and is recommended for the vast majority of workloads.',
           'dynamodb-table-classes|The DynamoDB Standard-Infrequent Access (DynamoDB Standard-IA) table class is optimized for tables where storage is the dominant cost.',
           'dynamodb-ttl|Time To Live (TTL) for DynamoDB is a cost-effective method for deleting items that are no longer relevant.',
           'dynamodb-ttl|DynamoDB automatically deletes expired items within a few days of their expiration time, without consuming write throughput.',
           'dynamodb-pricing|Each hour, if the amount of capacity used is less than or equal to the total reserved provisioned capacity you’ve purchased, all capacity will be charged at the reserved capacity rate.']),
        b('For relational databases, capacity planning means choosing the DB instance class and storage. The instance class determines the computation and memory capacity of a DB instance, and you can change the class as the workload changes.',
          'rds-instance-class',
          ['The DB instance class determines the computation and memory capacity of an Amazon RDS DB instance.']),
      ],
      services: ['Amazon DynamoDB', 'Amazon RDS'],
      design: [
        b('Cue: "predictable, steady throughput" → provisioned capacity (with auto scaling); "spiky or unknown" → on-demand; "relational database over- or under-sized" → change the DB instance class, guided by measured utilisation.',
          ['dynamodb-capacity', 'rds-instance-class'],
          ['dynamodb-capacity|You can choose to use provisioned capacity if you have steady workloads with predictable growth, and if you can reliably forecast capacity requirements for your application.',
           'rds-instance-class|The DB instance class determines the computation and memory capacity of an Amazon RDS DB instance.']),
      ],
    },
    {
      id: '4.3-K6',
      concepts: [
        b('Amazon RDS Proxy lets applications pool and share database connections. The proxy enables applications to open many client connections while it manages a smaller number of long-lived connections to the DB instance, and it can reduce the CPU overhead of establishing connections. This lets a database serve many short-lived clients without being sized only to hold their connections.',
          ['rds-proxy', 'rds-proxy-planning'],
          ['rds-proxy|By using Amazon RDS Proxy, you can allow your applications to pool and share database connections to improve their ability to scale.',
           'rds-proxy-planning|The proxy enables applications to open many client connections, while the proxy manages a smaller number of long-lived connections to the DB instance .',
           'rds-proxy-planning|It can also help reduce the CPU overhead for establishing connections.']),
        b('A DB instance that encounters "too many connections" errors is a good candidate for a proxy, and so are AWS Lambda functions, which can open many short-lived connections.',
          'rds-proxy-planning',
          ['Any DB instance that encounters "too many connections" errors is a good candidate for associating with a proxy.',
           'AWS Lambda functions can also be good candidates for using a proxy.']),
      ],
      services: ['Amazon RDS'],
      design: [
        b('Cue: "Lambda functions exhaust database connections" → RDS Proxy rather than a larger instance.',
          'rds-proxy-planning',
          ['AWS Lambda functions can also be good candidates for using a proxy.']),
      ],
    },
    {
      id: '4.3-K8',
      concepts: [
        b('A read replica is a read-only copy of a DB instance, and routing queries from your applications to the replica reduces the load on the primary DB instance. Read replicas are billed as standard DB instances at the same rates as the DB instance class used for the replica, so a replica is a way to buy read capacity rather than a free feature.',
          'rds-read-replicas',
          ['A read replica is a read-only copy of a DB instance.',
           'You can reduce the load on your primary DB instance by routing queries from your applications to the read replica.',
           'Read replicas are billed as standard DB instances at the same rates as the DB instance class used for the replica.']),
        b('You are not charged for the data transfer incurred in replicating data between the source DB instance and a read replica within the same AWS Region. AWS covers cross-Region replication costs separately, under Cross-Region replication costs and DB instance billing for Amazon RDS.',
          'rds-read-replicas',
          ['You aren\'t charged for the data transfer incurred in replicating data between the source DB instance and a read replica within the same AWS Region.',
           'For more information, see Cross-Region replication costs and DB instance billing for Amazon RDS']),
        b('For Amazon RDS DB instances (the non-Aurora engines), RDS does not support autoscaling of read replicas, which is the automatic adding or removing of read replicas as read demand changes, so you add and delete replicas yourself. Aurora differs: Aurora Auto Scaling dynamically adjusts the number of Aurora Replicas in a cluster, and removes unnecessary replicas when the workload decreases so that you do not pay for unused provisioned DB instances.',
          ['rds-read-replicas', 'aurora-autoscaling'],
          ['rds-read-replicas|RDS doesn\'t support autoscaling of read replicas, which is the automatic add or removing of read replicas as read demand changes.',
           'aurora-autoscaling|To meet your connectivity and workload requirements, Aurora Auto Scaling dynamically adjusts the number of Aurora Replicas (reader DB instances) provisioned for an Aurora DB cluster.',
           'aurora-autoscaling|When the connectivity or workload decreases, Aurora Auto Scaling removes unnecessary Aurora Replicas so that you don\'t pay for unused provisioned DB instances.']),
        b('DAX is a DynamoDB-compatible caching service that delivers fast response times for accessing eventually consistent data; if a request specifies strongly consistent reads, DAX passes the request through to DynamoDB.',
          ['dax', 'dax-concepts'],
          ['dax|DAX is a DynamoDB-compatible caching service that enables you to benefit from fast in-memory performance for demanding applications.',
           'dax|For these use cases, DynamoDB Accelerator (DAX) delivers fast response times for accessing eventually consistent data.',
           'dax-concepts|If the request specifies strongly consistent reads, DAX passes the request through to DynamoDB.']),
      ],
      services: ['Amazon RDS', 'Amazon ElastiCache'],
      design: [
        b('Cue: "reporting queries slow the production database" → a read replica (billed like an instance); "the same reads repeat" → a cache; both reduce the load on the primary.',
          ['rds-read-replicas', 'elasticache-strategies'],
          ['rds-read-replicas|You can reduce the load on your primary DB instance by routing queries from your applications to the read replica.',
           'elasticache-strategies|Amazon ElastiCache is an in-memory key-value store that sits between your application and the data store (database) that it accesses.']),
      ],
    },
  ],
  cues: [
    cue('steady, predictable DynamoDB throughput', 'Provisioned capacity mode (with auto scaling)',
      b('Provisioned capacity suits steady workloads with predictable growth.', 'dynamodb-capacity',
        ['You can choose to use provisioned capacity if you have steady workloads with predictable growth, and if you can reliably forecast capacity requirements for your application.'])),
    cue('unpredictable DynamoDB traffic, no capacity planning', 'On-demand capacity mode',
      b('On-demand mode has pay-per-request pricing with no idle capacity to worry about.', 'dynamodb-ondemand',
        ['With pay-per-request pricing, you don’t have to worry about idle capacity because you only pay for the throughput you actually use.'])),
    cue('repeated reads of the same data overload the database', 'ElastiCache (lazy loading) in front of the database',
      b('A cache sits between the application and the database, and lazy loading caches only requested data.', 'elasticache-strategies',
        ['Only requested data is cached.'])),
    cue('DynamoDB read-heavy, avoid overprovisioning read capacity', 'DAX',
      b('DAX can reduce the need to overprovision read capacity units.', 'dax',
        ['For read-heavy or bursty workloads, DAX provides increased throughput and potential operational cost savings by reducing the need to overprovision read capacity units.'])),
    cue('too many database connections from Lambda or many clients', 'Amazon RDS Proxy',
      b('A DB instance that hits "too many connections" errors is a good candidate for a proxy.', 'rds-proxy-planning',
        ['Any DB instance that encounters "too many connections" errors is a good candidate for associating with a proxy.'])),
    cue('offload read-only queries from the primary database', 'RDS read replica',
      b('Routing queries to a read replica reduces the load on the primary.', 'rds-read-replicas',
        ['You can reduce the load on your primary DB instance by routing queries from your applications to the read replica.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Managed Redis',
      aws: 'Amazon ElastiCache',
      mapping: b('Learn pairs Amazon ElastiCache with Azure Managed Redis as an in-memory cache and temporary data store, for caching, sessions, messaging and other low-latency temporary-data patterns.',
        ['learn-databases', 'elasticache-what-is'],
        ['learn-databases|In-memory cache and temporary data store Amazon ElastiCache Azure Managed Redis Use Azure Managed Redis for caching, sessions, messaging, and other low-latency temporary-data patterns.',
         'elasticache-what-is|Amazon ElastiCache is a web service that makes it easy to set up, manage, and scale a distributed in-memory data store or cache environment in the cloud.']),
      breaks: b('Learn says Azure Managed Redis is a cache and temporary data store. DAX, a cache built for DynamoDB that is API-compatible with it, has no Learn pairing.',
        ['learn-databases', 'dax'],
        ['learn-databases|Azure Managed Redis is a cache and temporary data store.',
         'dax|DAX reduces operational and application complexity by providing a managed service that is API-compatible with DynamoDB.']),
    },
  ],
};

export default notes;
