import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'counting-house',
  overview: [
    b('Compute is usually the largest line on an AWS bill, so the exam asks about it from both sides: how you pay (the purchasing option) and how you see and control the spend (the cost tools). EC2 offers On-Demand Instances, Savings Plans, Reserved Instances, Spot Instances, Dedicated Hosts, Dedicated Instances and Capacity Reservations. Ledger Office introduced the cost tools; this building applies them to compute and adds the purchasing options.',
      ['ec2-purchasing'],
      ['ec2-purchasing|You can use the following options to optimize your costs for Amazon EC2',
       'ec2-purchasing|On-Demand Instances – Pay, by the second, for the instances that you launch.']),
  ],
  bullets: [
    {
      id: '4.2-K1',
      concepts: [
        b('Cost allocation tags show which team or project is spending on compute. A tag is a label that you or AWS assigns to a resource, and you must activate a tag as a cost allocation tag before it appears in Cost Explorer or on a cost allocation report.',
          'cost-alloc-tags',
          ['A tag is a label that you or AWS assigns to an AWS resource.',
           'You must activate both types of tags separately before they can appear in Cost Explorer or on a cost allocation report.']),
        b('Consolidated billing matters for purchasing options: when accounts are in one organisation, the combined usage shares volume pricing discounts, Reserved Instance discounts and Savings Plans, so a commitment bought in one account can benefit others.',
          'consolidated-billing',
          ['This shares the volume pricing discounts, Reserved Instance discounts, and Savings Plans.']),
      ],
      services: ['AWS Organizations', 'Amazon EC2'],
      design: [
        b('Cue: "charge compute costs back to each department" → tag instances and activate the tags; "many accounts should share one commitment" → consolidated billing in AWS Organizations.',
          ['cost-alloc-tags', 'consolidated-billing'],
          ['cost-alloc-tags|After you activate cost allocation tags, AWS uses the cost allocation tags to organize your resource costs on your cost allocation report, to make it easier for you to categorize and track your AWS costs.',
           'consolidated-billing|This shares the volume pricing discounts, Reserved Instance discounts, and Savings Plans.']),
      ],
    },
    {
      id: '4.2-K2',
      concepts: [
        b('Cost Explorer is where you decide what to commit to: to get started with Savings Plans, you use AWS Cost Explorer to view your recommended Savings Plans commitment, purchase and manage your plans, and view your historical usage.',
          'savings-plans',
          ['To get started, use AWS Cost Explorer to view your recommended Savings Plans commitment, refresh Savings Plans recommendations, purchase Savings Plans, manage your Savings Plans, and view your historical AWS usage.']),
        b('AWS Budgets can monitor how well commitments are used: it tracks your aggregate utilisation and coverage metrics for Reserved Instances or Savings Plans, in addition to cost and usage budgets with alerts.',
          'budgets-managing',
          ['You can use AWS Budgets to monitor your aggregate utilization and coverage metrics for your Reserved Instances (RIs) or Savings Plans.']),
        b('The Cost and Usage Report is the detailed record behind the other tools: it contains the most comprehensive set of cost and usage data available, published to an S3 bucket you own.',
          'cur-what-is',
          ['AWS Cost and Usage Reports (AWS CUR) contains the most comprehensive set of cost and usage data available.',
           'You can use Cost and Usage Reports to publish your AWS billing reports to an Amazon Simple Storage Service (Amazon S3) bucket that you own.']),
      ],
      services: ['AWS Cost Explorer', 'AWS Budgets'],
      design: [
        b('Cue: "which Savings Plan should we buy?" → Cost Explorer recommendations; "are we using what we committed to?" → Budgets utilisation and coverage; "full line-item data" → Cost and Usage Report.',
          ['savings-plans', 'budgets-managing', 'cur-what-is'],
          ['savings-plans|To get started, use AWS Cost Explorer to view your recommended Savings Plans commitment, refresh Savings Plans recommendations, purchase Savings Plans, manage your Savings Plans, and view your historical AWS usage.',
           'budgets-managing|You can use AWS Budgets to monitor your aggregate utilization and coverage metrics for your Reserved Instances (RIs) or Savings Plans.',
           'cur-what-is|AWS Cost and Usage Reports (AWS CUR) contains the most comprehensive set of cost and usage data available.']),
      ],
    },
    {
      id: '4.2-K4',
      concepts: [
        b('On-Demand Instances are paid for by the second for the instances you launch, with no commitment. They are the baseline that the other options reduce.',
          'ec2-purchasing',
          ['On-Demand Instances – Pay, by the second, for the instances that you launch.']),
        b('Savings Plans give savings beyond On-Demand rates in exchange for a commitment to a specified amount of compute usage, measured per hour, for a one or three year term. There are Compute, Database, EC2 Instance and SageMaker AI plan types, and payment can be All upfront, Partial upfront or No upfront.',
          ['savings-plans', 'savings-plans-types'],
          ['savings-plans|Savings Plans provide savings beyond On-Demand rates in exchange for a commitment of using a specified amount of compute power (measured per hour) for a one or three year period.',
           'savings-plans-types|AWS offers four types of Savings Plans: Compute Savings Plans, Database Savings Plans, EC2 Instance Savings Plans, and SageMaker AI Savings Plans.',
           'savings-plans|You can pay for your commitment using All upfront, Partial upfront, or No upfront payment options.'],
          { allow: ['one', 'four'] }),
        b('Compute Savings Plans are the most flexible: they apply to EC2 usage regardless of instance family, size, Region, operating system or tenancy, and also to Fargate and Lambda usage, so you can move a workload between instance families or Regions, or from EC2 to Fargate, without losing the discount.',
          'savings-plans-types',
          ['Compute Savings Plans provide the most flexibility',
           'They also apply to your Fargate and Lambda usage.',
           'With Compute Savings Plans, you can move a workload from c5 to m5, shift your usage from EU (Ireland) to EU (London), or migrate your application from Amazon EC2 to Amazon ECS using Fargate at any time.']),
        b('Reserved Instances commit to a specific instance configuration, including instance type and Region, for a term of 1 or 3 years. AWS recommends Savings Plans over Reserved Instances, so a Reserved Instance is the answer mainly when the question needs a zonal reservation or names it directly. Scope is regional or zonal and the price is the same; only a zonal Reserved Instance reserves capacity.',
          ['ec2-purchasing', 'ec2-reserved-instances', 'ec2-ri-scope'],
          ['ec2-purchasing|Reserved Instances – Reduce your Amazon EC2 costs by making a commitment to a consistent instance configuration, including instance type and Region, for a term of 1 or 3 years.',
           'ec2-reserved-instances|We recommend Savings Plans over Reserved Instances.',
           'ec2-ri-scope|You pay the same price for a regional or zonal Reserved Instance.',
           'ec2-ri-scope|A zonal Reserved Instance reserves capacity in the specified Availability Zone.']),
        b('A Spot Instance uses spare EC2 capacity that is available for less than the On-Demand price. Amazon EC2 can take it back at any time (an interruption), so it suits applications that can be flexible about when they run and can be interrupted, not databases or anything that must stay up.',
          ['ec2-spot', 'ec2-spot-interruptions'],
          ['ec2-spot|A Spot Instance is an instance that uses spare EC2 capacity that is available for less than the On-Demand price.',
           'ec2-spot|Spot Instances are a cost-effective choice if you can be flexible about when your applications run and if your applications can be interrupted.',
           'ec2-spot-interruptions|It is always possible that your Spot Instance might be interrupted.']),
        b('Other options solve licensing and capacity rather than price. Dedicated Hosts are a physical host dedicated to your instances so you can bring existing per-socket, per-core or per-VM software licences; Capacity Reservations reserve capacity in a specific Availability Zone.',
          'ec2-purchasing',
          ['Dedicated Hosts – Pay for a physical host that is fully dedicated to running your instances, and bring your existing per-socket, per-core, or per-VM software licenses to reduce costs.',
           'Capacity Reservations – Reserve capacity for your EC2 instances in a specific Availability Zone.']),
      ],
      services: ['Savings Plans', 'Amazon EC2'],
      design: [
        b('Cue: steady, always-on usage → Savings Plans (or Reserved Instances); the instance family may change → Compute Savings Plans; batch, stateless or fault-tolerant work → Spot; short-lived or unpredictable → On-Demand; per-core licences → Dedicated Hosts. The full comparison is in the Don\'t confuse section below.',
          ['ec2-purchasing', 'savings-plans-types', 'ec2-spot'],
          ['ec2-purchasing|If you can\'t make a commitment to a specific instance configuration, but you can commit to a usage amount, purchase Savings Plans to reduce your On-Demand Instance costs.',
           'savings-plans-types|Compute Savings Plans provide the most flexibility',
           'ec2-spot|Spot Instances are a cost-effective choice if you can be flexible about when your applications run and if your applications can be interrupted.']),
      ],
    },
  ],
  cues: [
    cue('commit to a usage amount but the instance types will change', 'Compute Savings Plans',
      b('If you cannot commit to an instance configuration but can commit to a usage amount, purchase Savings Plans.', 'ec2-purchasing',
        ['If you can\'t make a commitment to a specific instance configuration, but you can commit to a usage amount, purchase Savings Plans to reduce your On-Demand Instance costs.'])),
    cue('Savings Plan discount must also cover Fargate or Lambda', 'Compute Savings Plans',
      b('Compute Savings Plans also apply to Fargate and Lambda usage.', 'savings-plans-types',
        ['They also apply to your Fargate and Lambda usage.'])),
    cue('reserve capacity in one specific Availability Zone', 'Zonal Reserved Instances or Capacity Reservations',
      b('A zonal Reserved Instance reserves capacity in the specified Availability Zone; a regional one does not.', 'ec2-ri-scope',
        ['A regional Reserved Instance does not reserve capacity.',
         'A zonal Reserved Instance reserves capacity in the specified Availability Zone.'])),
    cue('fault-tolerant batch processing that can be interrupted and restarted', 'Spot Instances',
      b('Spot is cost-effective if you can be flexible about when applications run and they can be interrupted.', 'ec2-spot',
        ['Spot Instances are a cost-effective choice if you can be flexible about when your applications run and if your applications can be interrupted.'])),
    cue('bring existing per-socket or per-core software licences', 'Dedicated Hosts',
      b('Dedicated Hosts let you bring your existing per-socket, per-core or per-VM software licences.', 'ec2-purchasing',
        ['Dedicated Hosts – Pay for a physical host that is fully dedicated to running your instances, and bring your existing per-socket, per-core, or per-VM software licenses to reduce costs.'])),
    cue('short-term, unpredictable workload with no commitment', 'On-Demand Instances',
      b('On-Demand Instances are paid by the second with no commitment.', 'ec2-purchasing',
        ['On-Demand Instances – Pay, by the second, for the instances that you launch.'])),
    cue('check whether purchased commitments are actually used', 'AWS Budgets (RI and Savings Plans utilisation and coverage)',
      b('Budgets monitors aggregate utilisation and coverage for Reserved Instances and Savings Plans.', 'budgets-managing',
        ['You can use AWS Budgets to monitor your aggregate utilization and coverage metrics for your Reserved Instances (RIs) or Savings Plans.'])),
  ],
  examples: [],
  confuse: ['savings-plans-ri-spot'],
  azure: [
    {
      concept: 'Microsoft Cost Management',
      aws: 'AWS Billing and Cost Management (Cost Explorer, Budgets)',
      mapping: b('Learn pairs AWS Billing and Cost Management with Microsoft Cost Management, which helps you understand your Azure bill, monitor and control spending and optimise resource use. On AWS, Cost Explorer is also where the Savings Plans recommendation is viewed.',
        ['learn-hub', 'savings-plans'],
        ['learn-hub|AWS Billing and Cost Management Microsoft Cost Management Cost Management helps you understand your Azure invoice or bill.',
         'learn-hub|It also helps you manage your billing account and subscriptions, monitor and control Azure spending, and optimize resource use.',
         'savings-plans|To get started, use AWS Cost Explorer to view your recommended Savings Plans commitment, refresh Savings Plans recommendations, purchase Savings Plans, manage your Savings Plans, and view your historical AWS usage.']),
      breaks: b('The Learn pairing covers the billing tools only. The purchasing options (On-Demand, Savings Plans, Reserved Instances, Spot, Dedicated Hosts, Capacity Reservations) are separate AWS choices that the exam tests directly, and the Learn row does not map them, so learn their commitment and interruption trade-offs from the AWS pages.',
        ['ec2-purchasing', 'learn-hub'],
        ['ec2-purchasing|You can use the following options to optimize your costs for Amazon EC2',
         'learn-hub|AWS Billing and Cost Management Microsoft Cost Management Cost Management helps you understand your Azure invoice or bill.']),
    },
  ],
};

export default notes;
