import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'counting-house',
  overview: [
    b('The exam asks about compute cost from both sides: how you pay (the purchasing option) and how you see and control the spend (the cost tools). EC2 offers On-Demand Instances, Savings Plans, Reserved Instances, Spot Instances, Dedicated Hosts, Dedicated Instances and Capacity Reservations. Ledger Office introduced the cost tools; this building applies them to compute and adds the purchasing options.',
      ['ec2-purchasing'],
      ['ec2-purchasing|You can use the following options to optimize your costs for Amazon EC2',
       'ec2-purchasing|On-Demand Instances – Pay, by the second, for the instances that you launch.']),
  ],
  bullets: [
    {
      id: '4.2-K1',
      concepts: [
        b('Cost allocation tags show which team or project is spending on compute. A tag is a label that you or AWS assigns to a resource, and you must activate a tag as a cost allocation tag before it appears in Cost Explorer or on a cost allocation report.',
          'cost-alloc-tags',
          ['A tag is a label that you or AWS assigns to an AWS resource.',
           'You must activate both types of tags separately before they can appear in Cost Explorer or on a cost allocation report.']),
        b('Consolidated billing matters for purchasing options: when accounts are in one organisation, the combined usage shares volume pricing discounts, Reserved Instance discounts and Savings Plans, so a commitment bought in one account can benefit others.',
          'consolidated-billing',
          ['This shares the volume pricing discounts, Reserved Instance discounts, and Savings Plans.']),
      ],
      services: ['AWS Organizations', 'Amazon EC2'],
      design: [
        b('Cue: "charge compute costs back to each department" → tag instances and activate the tags; "many accounts should share one commitment" → consolidated billing in AWS Organizations.',
          ['cost-alloc-tags', 'consolidated-billing'],
          ['cost-alloc-tags|After you activate cost allocation tags, AWS uses the cost allocation tags to organize your resource costs on your cost allocation report, to make it easier for you to categorize and track your AWS costs.',
           'consolidated-billing|This shares the volume pricing discounts, Reserved Instance discounts, and Savings Plans.']),
      ],
    },
    {
      id: '4.2-K2',
      concepts: [
        b('Cost Explorer is where you decide what to commit to: to get started with Savings Plans, you use AWS Cost Explorer to view your recommended Savings Plans commitment, purchase and manage your plans, and view your historical usage.',
          'savings-plans',
          ['To get started, use AWS Cost Explorer to view your recommended Savings Plans commitment, refresh Savings Plans recommendations, purchase Savings Plans, manage your Savings Plans, and view your historical AWS usage.']),
        b('AWS Budgets can monitor how well commitments are used: it tracks your aggregate utilisation and coverage metrics for Reserved Instances or Savings Plans, in addition to cost and usage budgets with alerts.',
          'budgets-managing',
          ['You can use AWS Budgets to monitor your aggregate utilization and coverage metrics for your Reserved Instances (RIs) or Savings Plans.']),
        b('The Cost and Usage Report is the detailed record behind the other tools: it contains the most comprehensive set of cost and usage data available, published to an S3 bucket you own.',
          'cur-what-is',
          ['AWS Cost and Usage Reports (AWS CUR) contains the most comprehensive set of cost and usage data available.',
           'You can use Cost and Usage Reports to publish your AWS billing reports to an Amazon Simple Storage Service (Amazon S3) bucket that you own.']),
      ],
      services: ['AWS Cost Explorer', 'AWS Budgets'],
      design: [
        b('Cue: "which Savings Plan should we buy?" → Cost Explorer recommendations; "are we using what we committed to?" → Budgets utilisation and coverage; "full line-item data" → Cost and Usage Report.',
          ['savings-plans', 'budgets-managing', 'cur-what-is'],
          ['savings-plans|To get started, use AWS Cost Explorer to view your recommended Savings Plans commitment, refresh Savings Plans recommendations, purchase Savings Plans, manage your Savings Plans, and view your historical AWS usage.',
           'budgets-managing|You can use AWS Budgets to monitor your aggregate utilization and coverage metrics for your Reserved Instances (RIs) or Savings Plans.',
           'cur-what-is|AWS Cost and Usage Reports (AWS CUR) contains the most comprehensive set of cost and usage data available.']),
      ],
    },
    {
      id: '4.2-K4',
      concepts: [
        b('With On-Demand Instances you pay for compute capacity by the second with no long-term commitments, and you pay only for the seconds the instance is in the running state, with a 60-second minimum. They are the baseline that the other options reduce.',
          ['ec2-on-demand', 'ec2-purchasing'],
          ['ec2-on-demand|With On-Demand Instances, you pay for compute capacity by the second with no long-term commitments.',
           'ec2-on-demand|You pay only for the seconds that your On-Demand Instances are in the running state, with a 60-second minimum.']),
        b('Savings Plans give savings beyond On-Demand rates in exchange for a commitment to a specified amount of compute usage, measured per hour, for a one or three year term. The commitment cannot be changed or cancelled during the term. There are Compute, Database, EC2 Instance and SageMaker AI plan types, and payment can be All upfront, Partial upfront or No upfront.',
          ['savings-plans', 'savings-plans-types', 'savings-plans-vs-ri'],
          ['savings-plans|Savings Plans provide savings beyond On-Demand rates in exchange for a commitment of using a specified amount of compute power (measured per hour) for a one or three year period.',
           'savings-plans-types|AWS offers four types of Savings Plans: Compute Savings Plans, Database Savings Plans, EC2 Instance Savings Plans, and SageMaker AI Savings Plans.',
           'savings-plans-types|The terms of the commitment can\'t be changed after purchase.',
           'savings-plans-vs-ri|Savings Plans offer lower prices compared to On-Demand pricing in exchange for a commitment, and can\'t be cancelled during the term.',
           'savings-plans|You can pay for your commitment using All upfront, Partial upfront, or No upfront payment options.'],
          { allow: ['one', 'four'] }),
        b('Compute Savings Plans are the most flexible: they apply to EC2 usage regardless of instance family, size, Region, operating system or tenancy, and also to Fargate and Lambda usage, so you can move a workload between instance families or Regions, or from EC2 to Fargate, without losing the discount.',
          'savings-plans-types',
          ['Compute Savings Plans provide the most flexibility',
           'They also apply to your Fargate and Lambda usage.',
           'With Compute Savings Plans, you can move a workload from c5 to m5, shift your usage from EU (Ireland) to EU (London), or migrate your application from Amazon EC2 to Amazon ECS using Fargate at any time.']),
        b('EC2 Instance Savings Plans are less flexible than Compute Savings Plans: you commit to a specific instance family in a chosen Region, and the plan applies regardless of instance size, operating system and tenancy within that family in that Region. Database Savings Plans apply to AWS database services such as Aurora, RDS, DynamoDB and ElastiCache instead of to compute.',
          'savings-plans-types',
          ['in exchange for a commitment to a specific instance family in a chosen AWS Region (for example, m5 in Virginia).',
           'These plans automatically apply to usage regardless of instance size (for example, m5.xlarge, m5.2xlarge, etc.), OS (for example, Windows, Linux, etc.), and tenancy (Host, Dedicated, Default) within the specified family in a Region.',
           'Database Savings Plans provide flexibility to use AWS database services while reducing costs']),
        b('Reserved Instances commit to a specific instance configuration, including instance type and Region, for a term of 1 or 3 years. AWS recommends Savings Plans over Reserved Instances. Savings Plans do not provide capacity reservations.',
          ['ec2-purchasing', 'ec2-reserved-instances', 'savings-plans-vs-ri'],
          ['ec2-purchasing|Reserved Instances – Reduce your Amazon EC2 costs by making a commitment to a consistent instance configuration, including instance type and Region, for a term of 1 or 3 years.',
           'ec2-reserved-instances|We recommend Savings Plans over Reserved Instances.',
           'savings-plans-vs-ri|Savings Plans doesn\'t provide capacity reservations, but you can allocate On-Demand Capacity Reservation (ODCR) for your needs and your Savings Plans will apply.']),
        b('A Reserved Instance has an offering class and a scope. A Standard Reserved Instance provides a more significant discount than a Convertible one but cannot be exchanged; a Convertible Reserved Instance can be exchanged during the term. The scope does not affect the price, and only a zonal Reserved Instance reserves capacity. A regional Reserved Instance applies to usage in any Availability Zone in the Region and gives instance size flexibility within the family (Amazon Linux/Unix with default tenancy only); a zonal one applies to the specified Availability Zone and instance size only.',
          ['ec2-ri-classes', 'ec2-ri-scope'],
          ['ec2-ri-classes|A Standard Reserved Instance provides a more significant discount than a Convertible Reserved Instance, but you can\'t exchange a Standard Reserved Instance.',
           'ec2-ri-classes|Can be exchanged during the term for another Convertible Reserved Instance with new attributes, including instance family, instance type, platform, scope, or tenancy.',
           'ec2-ri-scope|You pay the same price for a regional or zonal Reserved Instance.',
           'ec2-ri-scope|A regional Reserved Instance does not reserve capacity.',
           'ec2-ri-scope|A zonal Reserved Instance reserves capacity in the specified Availability Zone.',
           'ec2-ri-scope|The Reserved Instance discount applies to instance usage in any Availability Zone in the specified Region.',
           'ec2-ri-scope|The Reserved Instance discount applies to instance usage within the instance family, regardless of size.',
           'ec2-ri-scope|Only supported on Amazon Linux/Unix Reserved Instances with default tenancy.',
           'ec2-ri-scope|No Availability Zone flexibility—the Reserved Instance discount applies to instance usage in the specified Availability Zone only.',
           'ec2-ri-scope|No instance size flexibility—the Reserved Instance discount applies to instance usage for the specified instance family and instance size only.']),
        b('A Spot Instance uses spare EC2 capacity that is available for less than the On-Demand price. Amazon EC2 might interrupt it, so it is a cost-effective choice if you can be flexible about when your applications run and your applications can be interrupted.',
          ['ec2-spot', 'ec2-spot-interruptions'],
          ['ec2-spot|A Spot Instance is an instance that uses spare EC2 capacity that is available for less than the On-Demand price.',
           'ec2-spot|Spot Instances are a cost-effective choice if you can be flexible about when your applications run and if your applications can be interrupted.',
           'ec2-spot-interruptions|It is always possible that your Spot Instance might be interrupted.']),
        b('Amazon EC2 issues a Spot Instance interruption notice, a warning two minutes before it stops or terminates the instance, so a fault-tolerant application can react; with hibernation as the interruption behaviour there is no two-minute warning because hibernation begins immediately.',
          'ec2-spot-notices',
          ['A Spot Instance interruption notice is a warning that is issued two minutes before Amazon EC2 stops or terminates your Spot Instance.',
           'If you specify hibernation as the interruption behavior, you receive an interruption notice, but you do not receive a two-minute warning because the hibernation process begins immediately.']),
        b('Dedicated Hosts are a physical host fully dedicated to running your instances, and you can bring your existing per-socket, per-core or per-VM software licences to reduce costs.',
          'ec2-purchasing',
          ['Dedicated Hosts – Pay for a physical host that is fully dedicated to running your instances, and bring your existing per-socket, per-core, or per-VM software licenses to reduce costs.']),
        b('Capacity Reservations reserve compute capacity in a specific Availability Zone for any duration. An immediate-use reservation has no term commitment and can be cancelled at any time, but it is charged at the equivalent On-Demand rate whether or not you run instances in it, and it gives no billing discount by itself. Savings Plans can apply to the usage that runs in it.',
          ['ec2-capacity-reservations', 'ec2-capacity-reservation-billing', 'savings-plans-vs-ri'],
          ['ec2-capacity-reservations|Amazon EC2 Capacity Reservations allow you to reserve compute capacity for your Amazon EC2 instances in a specific Availability Zone for any duration.',
           'ec2-capacity-reservations|If you request a Capacity Reservation for immediate use, the Capacity Reservation becomes available for use immediately and there is no term commitment.',
           'ec2-capacity-reservations|You can modify the Capacity Reservation at any time, and you can cancel it at any time to release the reserved capacity and to stop incurring charges.',
           'ec2-capacity-reservation-billing|Capacity Reservations are charged at the equivalent On-Demand rate whether you run instances in reserved capacity or not, including any applicable regional surcharge for Dedicated Instances.',
           'ec2-capacity-reservations|No billing discount.',
           'savings-plans-vs-ri|Savings Plans doesn\'t provide capacity reservations, but you can allocate On-Demand Capacity Reservation (ODCR) for your needs and your Savings Plans will apply.']),
      ],
      services: ['Savings Plans', 'Amazon EC2'],
      design: [
        b('Cue: steady, always-on usage → Savings Plans (or Reserved Instances); the instance family may change → Compute Savings Plans; batch, stateless or fault-tolerant work → Spot; short-lived or unpredictable → On-Demand; per-core licences → Dedicated Hosts. The full comparison is in the Don\'t confuse section below.',
          ['ec2-purchasing', 'savings-plans-types', 'ec2-spot'],
          ['ec2-purchasing|If you can\'t make a commitment to a specific instance configuration, but you can commit to a usage amount, purchase Savings Plans to reduce your On-Demand Instance costs.',
           'savings-plans-types|Compute Savings Plans provide the most flexibility',
           'ec2-spot|Spot Instances are a cost-effective choice if you can be flexible about when your applications run and if your applications can be interrupted.']),
      ],
    },
  ],
  cues: [
    cue('commit to a usage amount but the instance types will change', 'Compute Savings Plans',
      b('If you cannot commit to an instance configuration but can commit to a usage amount, purchase Savings Plans.', 'ec2-purchasing',
        ['If you can\'t make a commitment to a specific instance configuration, but you can commit to a usage amount, purchase Savings Plans to reduce your On-Demand Instance costs.'])),
    cue('Savings Plan discount must also cover Fargate or Lambda', 'Compute Savings Plans',
      b('Compute Savings Plans also apply to Fargate and Lambda usage.', 'savings-plans-types',
        ['They also apply to your Fargate and Lambda usage.'])),
    cue('reserve capacity in one specific Availability Zone', 'Zonal Reserved Instances or Capacity Reservations',
      b('A zonal Reserved Instance reserves capacity in the specified Availability Zone; a regional one does not.', 'ec2-ri-scope',
        ['A regional Reserved Instance does not reserve capacity.',
         'A zonal Reserved Instance reserves capacity in the specified Availability Zone.'])),
    cue('fault-tolerant batch processing that can be interrupted and restarted', 'Spot Instances',
      b('Spot is cost-effective if you can be flexible about when applications run and they can be interrupted.', 'ec2-spot',
        ['Spot Instances are a cost-effective choice if you can be flexible about when your applications run and if your applications can be interrupted.'])),
    cue('bring existing per-socket or per-core software licences', 'Dedicated Hosts',
      b('Dedicated Hosts let you bring your existing per-socket, per-core or per-VM software licences.', 'ec2-purchasing',
        ['Dedicated Hosts – Pay for a physical host that is fully dedicated to running your instances, and bring your existing per-socket, per-core, or per-VM software licenses to reduce costs.'])),
    cue('short-term, unpredictable workload with no commitment', 'On-Demand Instances',
      b('On-Demand Instances are paid by the second with no commitment.', 'ec2-purchasing',
        ['On-Demand Instances – Pay, by the second, for the instances that you launch.'])),
    cue('check whether purchased commitments are actually used', 'AWS Budgets (RI and Savings Plans utilisation and coverage)',
      b('Budgets monitors aggregate utilisation and coverage for Reserved Instances and Savings Plans.', 'budgets-managing',
        ['You can use AWS Budgets to monitor your aggregate utilization and coverage metrics for your Reserved Instances (RIs) or Savings Plans.'])),
  ],
  examples: [],
  confuse: ['savings-plans-ri-spot'],
  azure: [
    {
      concept: 'Microsoft Cost Management',
      aws: 'AWS Billing and Cost Management (Cost Explorer, Budgets)',
      mapping: b('Learn pairs AWS Billing and Cost Management with Microsoft Cost Management, which helps you understand your Azure bill, monitor and control spending and optimise resource use. On AWS, Cost Explorer is also where the Savings Plans recommendation is viewed.',
        ['learn-hub', 'savings-plans'],
        ['learn-hub|AWS Billing and Cost Management Microsoft Cost Management Cost Management helps you understand your Azure invoice or bill.',
         'learn-hub|It also helps you manage your billing account and subscriptions, monitor and control Azure spending, and optimize resource use.',
         'savings-plans|To get started, use AWS Cost Explorer to view your recommended Savings Plans commitment, refresh Savings Plans recommendations, purchase Savings Plans, manage your Savings Plans, and view your historical AWS usage.']),
      breaks: b('Learn pairs Microsoft Cost Management with the AWS billing tools. The EC2 purchasing options (On-Demand, Savings Plans, Reserved Instances, Spot, Dedicated Hosts, Capacity Reservations) have no Learn pairing; AWS lists them as options to optimize your costs for Amazon EC2.',
        ['ec2-purchasing', 'learn-hub'],
        ['ec2-purchasing|You can use the following options to optimize your costs for Amazon EC2',
         'learn-hub|AWS Billing and Cost Management Microsoft Cost Management Cost Management helps you understand your Azure invoice or bill.']),
    },
  ],
};

export default notes;
