import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'db-cost-desk',
  overview: [
    b('The cost tools are the same for every service; what changes is what you look for. For databases that means tagging DB instances and snapshots so their spend can be attributed, using the consolidated bill of an organisation to share commitments, and using Cost Explorer, Budgets and the Cost and Usage Report to see database spend. Ledger Office introduced each tool and Counting House applied them to compute; this building applies them to databases.',
      ['rds-tagging', 'cost-alloc-tags', 'ce-what-is'],
      ['rds-tagging|An Amazon RDS tag is a name-value pair that you define and associate with an Amazon RDS resource such as a DB instance or DB snapshot.',
       'cost-alloc-tags|You can use tags to organize your resources, and cost allocation tags to track your AWS costs on a detailed level.',
       'ce-what-is|AWS Cost Explorer is a tool that enables you to view and analyze your costs and usage.']),
  ],
  bullets: [
    {
      id: '4.3-K1',
      concepts: [
        b('An Amazon RDS tag is a name-value pair that you define and associate with an RDS resource such as a DB instance or DB snapshot. To see database spend by team or application, tag the databases and activate the tag as a cost allocation tag, because you must activate a tag before it appears in Cost Explorer or on a cost allocation report.',
          ['rds-tagging', 'cost-alloc-tags'],
          ['rds-tagging|An Amazon RDS tag is a name-value pair that you define and associate with an Amazon RDS resource such as a DB instance or DB snapshot.',
           'cost-alloc-tags|You must activate both types of tags separately before they can appear in Cost Explorer or on a cost allocation report.']),
        b('Multi-account billing helps database commitments. In consolidated billing the management account pays the charges of all member accounts, and the combined usage shares Reserved Instance discounts and Savings Plans, so a database commitment bought in one account can benefit others in the organisation.',
          'consolidated-billing',
          ['Every organization in AWS Organizations has a management account that pays the charges of all the member accounts.',
           'This shares the volume pricing discounts, Reserved Instance discounts, and Savings Plans.']),
      ],
      services: ['AWS Organizations'],
      design: [
        b('Cue: "attribute database costs to each application team" → tag the databases and activate cost allocation tags; "share a database commitment across many accounts" → consolidated billing in AWS Organizations.',
          ['rds-tagging', 'consolidated-billing'],
          ['rds-tagging|You can use tags to add metadata to your Amazon RDS resources.',
           'consolidated-billing|This shares the volume pricing discounts, Reserved Instance discounts, and Savings Plans.']),
      ],
    },
    {
      id: '4.3-K2',
      concepts: [
        b('Cost Explorer shows what databases cost over time: you can view and analyse costs and usage, forecast how much you are likely to spend, and get recommendations for which Reserved Instances to purchase. Filters and groupings let you narrow the report to database services or to a tag.',
          'ce-what-is',
          ['AWS Cost Explorer is a tool that enables you to view and analyze your costs and usage.',
           'You can view data for up to the last 13 months, forecast how much you\'re likely to spend for the next 18 months, and get recommendations for what Reserved Instances to purchase.'],
          { allow: ['13', '18'] }),
        b('Budgets can alert when database spend crosses a limit, and can monitor the utilisation and coverage of Reserved Instances or Savings Plans, which shows whether a database commitment is being used.',
          'budgets-managing',
          ['Set spending limits for services and receive alerts when costs approach or exceed your defined threshold.',
           'You can use AWS Budgets to monitor your aggregate utilization and coverage metrics for your Reserved Instances (RIs) or Savings Plans.']),
        b('The Cost and Usage Report is the most comprehensive set of cost and usage data available, published to an S3 bucket you own, and it can be broken down by tags you define, so database tags show up in the line items.',
          'cur-what-is',
          ['AWS Cost and Usage Reports (AWS CUR) contains the most comprehensive set of cost and usage data available.',
           'You can receive reports that break down your costs by the hour, day, or month, by product or product resource, or by tags that you define yourself.']),
        b('There are different ways to commit for database usage. Reserved DB instances are a billing discount applied to the use of certain on-demand DB instances, for a one- or three-year term, and the discount is tied to instance type and Region. Database Savings Plans offer flexibility to use AWS database services while reducing costs, and also apply to serverless usage.',
          ['rds-reserved', 'savings-plans-types'],
          ['rds-reserved|Reserved DB instances are not physical instances, but rather a billing discount applied to the use of certain on-demand DB instances in your account.',
           'rds-reserved|Discounts for reserved DB instances are tied to instance type and AWS Region.',
           'rds-reserved|Using reserved DB instances, you can reserve a DB instance for a one- or three-year term.',
           'savings-plans-types|Database Savings Plans provide flexibility to use AWS database services while reducing costs',
           'savings-plans-types|These plans automatically apply to the latest provisioned instance generations regardless of engine, instance family, size, Availability Zone (AZ), or Region, and also apply to serverless usage.'],
          { allow: ['one'] }),
      ],
      services: ['AWS Cost Explorer', 'AWS Budgets', 'AWS Cost and Usage Report'],
      design: [
        b('Cue: "which database costs are growing?" → Cost Explorer; "alert when the database bill passes a limit" → Budgets; "line-item database costs analysed with a query tool" → Cost and Usage Report; "steady database usage" → a reserved DB instance or Database Savings Plan.',
          ['ce-what-is', 'budgets-managing', 'cur-what-is', 'rds-reserved'],
          ['ce-what-is|AWS Cost Explorer is a tool that enables you to view and analyze your costs and usage.',
           'budgets-managing|Set spending limits for services and receive alerts when costs approach or exceed your defined threshold.',
           'cur-what-is|AWS Cost and Usage Reports (AWS CUR) contains the most comprehensive set of cost and usage data available.',
           'rds-reserved|Reserved DB instances are not physical instances, but rather a billing discount applied to the use of certain on-demand DB instances in your account.']),
      ],
    },
  ],
  cues: [
    cue('attribute database spend to teams', 'Tag DB instances and activate cost allocation tags',
      b('A tag is a name-value pair on a resource, and cost allocation tags must be activated before they appear in Cost Explorer.', 'cost-alloc-tags',
        ['You must activate both types of tags separately before they can appear in Cost Explorer or on a cost allocation report.'])),
    cue('steady RDS usage for a long term, reduce the on-demand cost', 'Reserved DB instances (or a Database Savings Plan)',
      b('Reserved DB instances are a billing discount for a one- or three-year term, tied to instance type and Region.', 'rds-reserved',
        ['Using reserved DB instances, you can reserve a DB instance for a one- or three-year term.',
         'Discounts for reserved DB instances are tied to instance type and AWS Region.'])),
    cue('commit to database usage but engine and size may change', 'Database Savings Plans',
      b('Database Savings Plans apply regardless of engine, instance family, size, Availability Zone or Region.', 'savings-plans-types',
        ['These plans automatically apply to the latest provisioned instance generations regardless of engine, instance family, size, Availability Zone (AZ), or Region, and also apply to serverless usage.'])),
    cue('alert when database spend approaches a limit', 'AWS Budgets',
      b('Budgets alerts when costs approach or exceed your threshold.', 'budgets-managing',
        ['Set spending limits for services and receive alerts when costs approach or exceed your defined threshold.'])),
    cue('detailed database billing data delivered to S3', 'AWS Cost and Usage Report',
      b('CUR is published to an S3 bucket you own, with breakdown by tags you define.', 'cur-what-is',
        ['You can receive reports that break down your costs by the hour, day, or month, by product or product resource, or by tags that you define yourself.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Microsoft Cost Management',
      aws: 'AWS Billing and Cost Management (Cost Explorer, Budgets)',
      mapping: b('Learn pairs AWS Billing and Cost Management with Microsoft Cost Management, which helps you monitor and control Azure spending and optimise resource use. On AWS, Cost Explorer also gives recommendations for which Reserved Instances to purchase.',
        ['learn-hub', 'ce-what-is'],
        ['learn-hub|It also helps you manage your billing account and subscriptions, monitor and control Azure spending, and optimize resource use.',
         'ce-what-is|You can view data for up to the last 13 months, forecast how much you\'re likely to spend for the next 18 months, and get recommendations for what Reserved Instances to purchase.'],
        { allow: ['13', '18'] }),
      breaks: b('The Learn row maps the billing tools only. For databases on AWS the exam also asks you to choose how to commit: a reserved DB instance is tied to instance type and Region, whereas a Database Savings Plan applies across engines and sizes. The Learn pairing does not cover either.',
        ['rds-reserved', 'savings-plans-types', 'learn-hub'],
        ['rds-reserved|Discounts for reserved DB instances are tied to instance type and AWS Region.',
         'savings-plans-types|These plans automatically apply to the latest provisioned instance generations regardless of engine, instance family, size, Availability Zone (AZ), or Region, and also apply to serverless usage.',
         'learn-hub|AWS Billing and Cost Management Microsoft Cost Management Cost Management helps you understand your Azure invoice or bill.']),
    },
  ],
};

export default notes;
