import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'distribution-office',
  overview: [
    b('Where compute runs, and how available it must be, both change the bill. A {{term:region}} is a physical location where AWS clusters data centers, and each group of logical data centers is an {{term:availability-zone}}. Edge and hybrid options (CloudFront edge locations, Local Zones, Wavelength, Outposts) put compute or content closer to users or to your premises. And not every workload needs the same availability: a production system usually justifies the cost of running across Availability Zones, while a development environment often does not.',
      ['global-infra', 'cloudfront-what-is', 'outposts-what-is', 'waf-cost-demand'],
      ['global-infra|AWS has the concept of a Region, which is a physical location around the world where we cluster data centers.',
       'global-infra|We call each group of logical data centers an Availability Zone.',
       'cloudfront-what-is|CloudFront delivers your content through a worldwide network of data centers called edge locations.',
       'outposts-what-is|AWS Outposts is a fully managed service that extends AWS infrastructure, services, APIs, and tools to customer premises.',
       'waf-cost-demand|The economic benefits of just-in-time supply should be balanced against the need to provision to account for resource failures, high availability, and provision time.']),
  ],
  bullets: [
    {
      id: '4.2-K3',
      concepts: [
        b('A Region is where you place the workload. Select a Region that has the AWS services and features you need, and you can lower network latency by selecting a Region that is close to most of your users. An account can create resources in the Regions that meet your requirements, for example to be closer to customers or to meet legal requirements.',
          'regions-and-azs',
          ['For example, select a Region that has the AWS services and features that you need.',
           'Also, you can lower network latency when you select a Region that is close to the majority of your users.',
           'For example, you want to create resources in Europe to be closer to your European customers or to meet legal requirements.']),
        b('Region choice is also a cost choice. Resource pricing is different in each Region because of local market conditions such as the cost of land, fiber, electricity and taxes, and AWS says to use Regions with lower prices only if you have no obligations in data privacy, security and business requirements. Latency, data residency and the services you need decide first; price differences decide among the Regions that remain.',
          'waf-region-cost',
          ['Resource pricing may be different in each Region.',
           'Each AWS Region operates within local market conditions, and resource pricing is different in each Region due to differences in the cost of land, fiber, electricity, and taxes, for example.',
           'Use Regions that provide lower prices for AWS services to deploy your workloads if you have no obligations in data privacy, security and business requirements.']),
        b('Availability Zones are the groups of logical data centers inside a Region. Spreading a workload across Availability Zones is the usual way to raise availability, and it has a cost: more instances and cross-zone copies. EC2 Auto Scaling can balance instances evenly across the Availability Zones you choose as the group scales.',
          ['global-infra', 'asg-what-is'],
          ['global-infra|We call each group of logical data centers an Availability Zone.',
           'asg-what-is|You can specify multiple Availability Zones for your Auto Scaling group, and Amazon EC2 Auto Scaling balances your instances evenly across the Availability Zones as the group scales.']),
      ],
      services: ['Amazon EC2'],
      design: [
        b('Cue: "lowest latency for users in one geography" → a Region close to them; "must stay in a specific country" → a Region in that country; "survive a data center failure" → more than one Availability Zone.',
          ['regions-and-azs', 'asg-what-is'],
          ['regions-and-azs|Also, you can lower network latency when you select a Region that is close to the majority of your users.',
           'asg-what-is|You can specify multiple Availability Zones for your Auto Scaling group, and Amazon EC2 Auto Scaling balances your instances evenly across the Availability Zones as the group scales.']),
      ],
    },
    {
      id: '4.2-K5',
      concepts: [
        b('Edge processing moves work toward the user. CloudFront delivers content through edge locations and routes each request to the edge location that provides the lowest latency, retrieving content from the origin only when it is not already cached there. That keeps repeated requests off the origin.',
          'cloudfront-what-is',
          ['CloudFront delivers your content through a worldwide network of data centers called edge locations.',
           'When a user requests content that you\'re serving with CloudFront, the request is routed to the edge location that provides the lowest latency (time delay), so that content is delivered with the best possible performance.',
           'If the content is already in the edge location with the lowest latency, CloudFront delivers it immediately.']),
        b('Local Zones put compute close to end users for low-latency applications such as real-time gaming and live streaming. AWS resources in Local Zones have different prices than they do in the parent AWS Region, so check prices before choosing one.',
          'local-zones',
          ['You can use Local Zones to provide your users with low-latency access to your applications.',
           'Run low-latency applications at the edge — Build and deploy applications close to end users to enable real-time gaming, live streaming, augmented and virtual reality (AR/VR), virtual workstations, and more.',
           'AWS resources in Local Zones have different prices than they do in parent AWS Regions.']),
        b('Wavelength deploys standard AWS compute and storage services to the edge of communications service providers\' networks, to deliver low latency to mobile devices and end users. You extend a VPC to one or more Wavelength Zones and run EC2 instances there while communicating back to services in the parent Region.',
          'wavelength-what-is',
          ['Wavelength deploys standard AWS compute and storage services to the edge of communications service providers\' (CSP) networks.',
           'You can extend a virtual private cloud (VPC) to one or more Wavelength Zones.',
           'You can then use AWS resources such as Amazon Elastic Compute Cloud (Amazon EC2) instances to run the applications that require low latency or edge resiliency within the Wavelength Zone, while seamlessly communicating back to your existing AWS services deployed in the parent AWS Region.']),
      ],
      services: ['Amazon CloudFront', 'AWS Wavelength'],
      design: [
        b('Cue: "cache static content near users and cut load on the origin" → CloudFront; "low-latency access for a gaming or streaming audience near a metro area" → Local Zones; "mobile devices on a carrier network" → Wavelength. Edge placement is for latency first; check whether the question also asks for lowest cost, because edge resources can be priced differently from the parent Region.',
          ['cloudfront-what-is', 'local-zones', 'wavelength-what-is'],
          ['cloudfront-what-is|If the content is already in the edge location with the lowest latency, CloudFront delivers it immediately.',
           'local-zones|AWS resources in Local Zones have different prices than they do in parent AWS Regions.',
           'wavelength-what-is|AWS Wavelength enables developers to build applications that require edge computing infrastructure to deliver low latency to mobile devices and end users or increase the resiliency of their existing edge applications.']),
      ],
    },
    {
      id: '4.2-K6',
      concepts: [
        b('AWS Outposts extends AWS infrastructure, services, APIs and tools to customer premises. An Outpost is a pool of AWS compute and storage capacity deployed at your site, operated, monitored and managed by AWS as part of an AWS Region. Applications on premises use the same programming interfaces as in AWS Regions and use local compute and storage for lower latency and local data processing.',
          'outposts-what-is',
          ['AWS Outposts is a fully managed service that extends AWS infrastructure, services, APIs, and tools to customer premises.',
           'An Outpost is a pool of AWS compute and storage capacity deployed at a customer site.',
           'AWS operates, monitors, and manages this capacity as part of an AWS Region.']),
        b('Instances in Outpost subnets communicate with instances in the AWS Region using private IP addresses, all within the same VPC, so an Outpost is an extension of a Region VPC rather than a separate network. Hybrid is the answer when the requirement names on-premises latency or local data processing; if it is only a one-time data move, look at Haul & Hybrid Customs instead.',
          'outposts-what-is',
          ['Instances in Outpost subnets communicate with other instances in the AWS Region using private IP addresses, all within the same VPC.']),
      ],
      services: ['AWS Outposts'],
      design: [
        b('Cue: "run AWS services on premises for low-latency local processing, with the same APIs" → Outposts; contrast with Wavelength (carrier edge) and Local Zones (AWS-operated metro locations).',
          ['outposts-what-is', 'wavelength-what-is', 'local-zones'],
          ['outposts-what-is|By providing local access to AWS managed infrastructure, AWS Outposts enables customers to build and run applications on premises using the same programming interfaces as in AWS Regions, while using local compute and storage resources for lower latency and local data processing needs.',
           'wavelength-what-is|Wavelength deploys standard AWS compute and storage services to the edge of communications service providers\' (CSP) networks.',
           'local-zones|You can use Local Zones to provide your users with low-latency access to your applications.']),
      ],
    },
    {
      id: '4.2-S4',
      concepts: [
        b('Match the availability to the workload class. The reliability pillar defines availability as the percentage of time that a workload is available for use, and the cost pillar says the benefit of just-in-time supply must be balanced against provisioning for resource failures, high availability and provision time. So a production workload that cannot tolerate an outage pays for redundancy, and a non-production workload usually should not.',
          ['waf-availability', 'waf-cost-demand'],
          ['waf-availability|Availability is the percentage of time that a workload is available for use.',
           'waf-cost-demand|The economic benefits of just-in-time supply should be balanced against the need to provision to account for resource failures, high availability, and provision time.']),
        b('For production, the usual building blocks are Multi-AZ: an RDS Multi-AZ deployment provisions and maintains a synchronous standby replica in a different Availability Zone, and an Auto Scaling group balances instances across Availability Zones. For disaster recovery, the strategies range from the low cost and low complexity of making backups to more complex strategies using multiple active Regions, so pick the cheapest that meets the recovery objectives (Disaster Bunker).',
          ['rds-multi-az-instance', 'asg-what-is', 'dr-options'],
          ['rds-multi-az-instance|In a Multi-AZ DB instance deployment, Amazon RDS automatically provisions and maintains a synchronous standby replica in a different Availability Zone.',
           'asg-what-is|You can specify multiple Availability Zones for your Auto Scaling group, and Amazon EC2 Auto Scaling balances your instances evenly across the Availability Zones as the group scales.',
           'dr-options|Disaster recovery strategies available to you within AWS can be broadly categorized into four approaches, ranging from the low cost and low complexity of making backups to more complex strategies using multiple active Regions.'],
          { allow: ['four'] }),
        b('For non-production, cost levers are to run fewer copies and to stop what is not in use. You are not charged for usage or data transfer fees for an EC2 instance when it is stopped, though charges are incurred for the storage of any attached EBS volumes, and Elastic IP addresses also incur charges regardless of the instance\'s state. A stopped RDS DB instance is not charged for DB instance hours but is charged for provisioned storage and backup storage, and it is started again automatically if you do not start it within seven consecutive days. Scheduled scaling can also lower the desired capacity at predictable times.',
          ['ec2-lifecycle', 'rds-stop', 'asg-scheduled'],
          ['ec2-lifecycle|You are not charged for usage or data transfer fees for your instance when it is stopped.',
           'ec2-lifecycle|Charges are incurred for the storage of any Amazon EBS volumes.',
           'ec2-lifecycle|Some AWS resources, such as Amazon EBS volumes and Elastic IP addresses, incur charges regardless of the instance\'s state.',
           'rds-stop|While the instance is stopped, you\'re not charged for DB instance hours.',
           'rds-stop|While your DB instance is stopped, you are charged for provisioned storage (including Provisioned IOPS).',
           'rds-stop|If you don\'t manually start your DB instance after it is stopped for seven consecutive days, RDS automatically starts your DB instance for you.',
           'asg-scheduled|You create scheduled actions that increase or decrease your group\'s desired capacity at specific times.']),
      ],
      services: ['Amazon EC2', 'Amazon RDS'],
      design: [
        b('Cue: "production database must survive an Availability Zone failure" → Multi-AZ; "development environment, minimise cost" → a single Availability Zone, smaller resources, stopped when unused; "disaster recovery with a loose recovery objective" → the cheaper DR strategies. This is study guidance: the exam wording decides.',
          ['rds-multi-az-instance', 'ec2-lifecycle', 'dr-options'],
          ['rds-multi-az-instance|Amazon RDS provides high availability and failover support for DB instances using Multi-AZ deployments with a single standby DB instance.',
           'ec2-lifecycle|You are not charged for usage or data transfer fees for your instance when it is stopped.',
           'dr-options|Disaster recovery strategies available to you within AWS can be broadly categorized into four approaches, ranging from the low cost and low complexity of making backups to more complex strategies using multiple active Regions.'],
          { allow: ['four'] }),
      ],
    },
  ],
  cues: [
    cue('lower latency for most users by choosing where to deploy', 'A Region close to the majority of users',
      b('Selecting a Region close to the majority of your users lowers network latency.', 'regions-and-azs',
        ['Also, you can lower network latency when you select a Region that is close to the majority of your users.'])),
    cue('cache content at locations near users to reduce origin load', 'Amazon CloudFront edge locations',
      b('CloudFront delivers content from edge locations and retrieves it from the origin only if it is not cached there.', 'cloudfront-what-is',
        ['If the content is already in the edge location with the lowest latency, CloudFront delivers it immediately.'])),
    cue('low-latency application close to end users in a metro area', 'AWS Local Zones',
      b('Local Zones provide users with low-latency access to your applications.', 'local-zones',
        ['You can use Local Zones to provide your users with low-latency access to your applications.'])),
    cue('low latency to mobile devices on a carrier network', 'AWS Wavelength',
      b('Wavelength deploys AWS compute and storage at the edge of communications service providers\' networks.', 'wavelength-what-is',
        ['Wavelength deploys standard AWS compute and storage services to the edge of communications service providers\' (CSP) networks.'])),
    cue('run AWS infrastructure and APIs in our own data centre for local processing', 'AWS Outposts',
      b('Outposts extends AWS infrastructure, services, APIs and tools to customer premises.', 'outposts-what-is',
        ['AWS Outposts is a fully managed service that extends AWS infrastructure, services, APIs, and tools to customer premises.'])),
    cue('development instances idle outside working hours', 'Stop the instances (no instance usage charge while stopped)',
      b('You are not charged for usage for a stopped instance, but EBS storage is still charged.', 'ec2-lifecycle',
        ['You are not charged for usage or data transfer fees for your instance when it is stopped.',
         'Charges are incurred for the storage of any Amazon EBS volumes.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Local (formerly Azure Stack HCI)',
      aws: 'AWS Outposts',
      mapping: b('Learn pairs AWS Outposts with Azure Local (formerly Azure Stack HCI): both deliver cloud-managed, on-premises infrastructure for low-latency workloads and data-residency requirements.',
        ['learn-compute', 'outposts-what-is'],
        ['learn-compute|Both services deliver cloud-managed, on-premises infrastructure for low-latency workloads and data-residency requirements.',
         'outposts-what-is|AWS Outposts is a fully managed service that extends AWS infrastructure, services, APIs, and tools to customer premises.']),
      breaks: b('Learn describes Azure Local as a validated hyperconverged infrastructure platform managed through the Azure portal. An Outpost is described differently on AWS: a pool of AWS compute and storage capacity that AWS operates, monitors and manages as part of an AWS Region, with instances joining your VPC. The exam tests that Region-extension model, not the hyperconverged platform.',
        ['learn-compute', 'outposts-what-is'],
        ['learn-compute|Azure Local provides a validated hyperconverged infrastructure (HCI) platform managed through the Azure portal.',
         'outposts-what-is|AWS operates, monitors, and manages this capacity as part of an AWS Region.']),
    },
  ],
};

export default notes;
