import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'elastic-mint',
  overview: [
    b('Compute is cheapest when you pay only for the capacity you use. Lambda runs code without provisioning or managing servers, Fargate runs containers without managing servers or clusters of EC2 instances, and EC2 gives you the instance itself, with Auto Scaling to add and remove instances as demand changes. A load balancer spreads the traffic across the targets. This building is about choosing among them and scaling them so you do not pay for idle capacity.',
      ['lambda-welcome', 'fargate-ecs', 'asg-what-is', 'elb-what-is'],
      ['lambda-welcome|With Lambda, you can run code without provisioning or managing servers.',
       'fargate-ecs|AWS Fargate is a technology that you can use with Amazon ECS to run containers without having to manage servers or clusters of Amazon EC2 instances.',
       'asg-what-is|If you specify scaling policies, then Amazon EC2 Auto Scaling can launch or terminate instances as demand on your application increases or decreases.',
       'elb-what-is|Elastic Load Balancing automatically distributes your incoming traffic across multiple targets, such as EC2 instances, containers, and IP addresses, in one or more Availability Zones.']),
  ],
  beyondProject: [
    b('Your visitor counter runs on Lambda. The SAA cost question is when Lambda is the cheaper choice than EC2 or Fargate. Lambda Functions are priced on the number of requests served and the duration your code runs, so you pay for work done rather than for an idle server, and a single invocation can run for up to 15 minutes. Spiky or infrequent, short event-driven work fits that model; for long-running or steady high-volume work, compare the cost against EC2 or Fargate. These limits are documented and can change.',
      ['lambda-pricing', 'lambda-quotas'],
      ['lambda-pricing|Lambda Functions are priced based on the number of requests served and the duration your code runs, measured in GB-seconds.',
       'lambda-quotas|Code can run for up to 15 minutes in a single invocation']),
    b('Concurrency settings can add cost. There is no charge for configuring reserved concurrency for a function, but provisioned concurrency incurs additional charges to your account, so it is the option to remove when the question asks for the lowest cost and can tolerate cold starts.',
      'lambda-concurrency',
      ['There is no charge for configuring reserved concurrency for a function.',
       'Configuring provisioned concurrency incurs charges to your AWS account.']),
  ],
  bullets: [
    {
      id: '4.2-K8',
      concepts: [
        b('Serverless computing removes the idle server. Lambda manages execution environments, scaling, routing and fault tolerance, and each invocation runs independently with no shared state, scaling horizontally to match demand.',
          'lambda-welcome',
          ['Lambda manages execution environments, scaling, routing, and fault tolerance.',
           'Each invocation runs independently with no shared state, scaling horizontally to match demand.']),
        b('Containers raise utilisation by packaging an application with its dependencies and running it on shared infrastructure. With Fargate you package your application in containers, specify the CPU and memory requirements, define networking and IAM policies, and launch the application; this removes the need to choose server types, decide when to scale your clusters, or optimize cluster packing.',
          'fargate-ecs',
          ['This removes the need to choose server types, decide when to scale your clusters, or optimize cluster packing.',
           'When you run your tasks and services with Fargate, you package your application in containers, specify the CPU and memory requirements, define networking and IAM policies, and launch the application.']),
        b('A {{term:microservice|microservices}} design lets each part scale on its own, so only the busy part needs more capacity. ECS runs those containerised services, and ECS service auto scaling can add or remove tasks to follow demand.',
          ['ecs-what-is', 'ecs-autoscaling'],
          ['ecs-what-is|Amazon Elastic Container Service (Amazon ECS) is a fully managed container orchestration service that helps you easily deploy, manage, and scale containerized applications.',
           'ecs-autoscaling|Automatically scale your Amazon ECS service']),
      ],
      services: ['AWS Lambda', 'AWS Fargate', 'Amazon EC2'],
      design: [
        b('Cue: "event-driven, short tasks, unpredictable traffic, no servers to manage" → Lambda; "containers, but no cluster of instances to manage" → Fargate; "need the instance itself, long-running or steady load" → EC2 (with a commitment if usage is steady).',
          ['lambda-welcome', 'fargate-ecs', 'ec2-purchasing'],
          ['lambda-welcome|With Lambda, you can run code without provisioning or managing servers.',
           'fargate-ecs|With AWS Fargate, you no longer have to provision, configure, or scale clusters of virtual machines to run containers.',
           'ec2-purchasing|If you can\'t make a commitment to a specific instance configuration, but you can commit to a usage amount, purchase Savings Plans to reduce your On-Demand Instance costs.']),
      ],
    },
    {
      id: '4.2-K9',
      concepts: [
        b('EC2 Auto Scaling keeps a group between the minimum and maximum size you set and at the desired capacity, launching or terminating instances as scaling policies react to demand. It also monitors instance health and replaces terminated or impaired instances to maintain the desired capacity.',
          'asg-what-is',
          ['You can specify the minimum number of instances in each Auto Scaling group, and Amazon EC2 Auto Scaling ensures that your group never goes below this size.',
           'You can specify the maximum number of instances in each Auto Scaling group, and Amazon EC2 Auto Scaling ensures that your group never goes above this size.',
           'If you specify scaling policies, then Amazon EC2 Auto Scaling can launch or terminate instances as demand on your application increases or decreases.',
           'Amazon EC2 Auto Scaling automatically monitors the health and availability of your instances using EC2 health checks and replaces terminated or impaired instances to maintain your desired capacity.']),
        b('Scaling approaches differ in cost. Target tracking keeps a metric such as average CPU at a target value, which helps maintain high utilisation for better cost efficiency without manual intervention. Scheduled scaling changes desired capacity at specific times for predictable load changes. Predictive scaling forecasts load from history to add capacity ahead of demand, and can save money by avoiding over-provisioning.',
          ['asg-target-tracking', 'asg-scheduled', 'asg-predictive'],
          ['asg-target-tracking|This allows your application to maintain optimal performance and high utilization for your EC2 instances for better cost efficiency without manual intervention.',
           'asg-scheduled|With scheduled scaling, you can set up automatic scaling for your application based on predictable load changes.',
           'asg-predictive|Predictive scaling can also potentially save you money on your EC2 bill by helping you avoid the need to over provision capacity.']),
        b('For an Auto Scaling group whose instances are slow to start, a warm pool is the Auto Scaling feature: a pool of pre-initialized EC2 instances that sits alongside the group, so a scale-out can draw on instances that are ready to serve traffic. You can keep warm pool instances Stopped, Running or Hibernated; Stopped is an effective way to minimize costs because you pay only for the volumes and attached Elastic IP addresses, and Running is highly discouraged. AWS warns that creating a warm pool when it is not required can lead to unnecessary costs.',
          'asg-warm-pools',
          ['A warm pool gives you the ability to decrease latency for your applications that have exceptionally long boot times, for example, because instances need to write massive amounts of data to disk.',
           'A warm pool is a pool of pre-initialized EC2 instances that sits alongside an Auto Scaling group.',
           'You can keep instances in the warm pool in one of three states: Stopped, Running, or Hibernated.',
           'Keeping instances in a Stopped state is an effective way to minimize costs.',
           'With stopped instances, you pay only for the volumes that you use and the Elastic IP addresses attached to the instances.',
           'Keeping instances in a Running state inside the warm pool is also possible, but is highly discouraged to avoid incurring unnecessary charges.',
           'Creating a warm pool when it\'s not required can lead to unnecessary costs.'],
          { allow: ['three'] }),
        b('Hibernation is a cost tool for a single instance that is slow to start. Hibernation saves the contents of the instance memory (RAM) to the EBS root volume; when the instance starts again, the RAM contents are reloaded and the processes that were running resume. You are not charged for instance usage for a hibernated instance in the stopped state, but you are charged for storage of any EBS volumes, including storage for the RAM contents.',
          'ec2-hibernate',
          ['Hibernation saves the contents from the instance memory (RAM) to your Amazon Elastic Block Store (Amazon EBS) root volume.',
           'The RAM contents are reloaded',
           'The processes that were previously running on the instance are resumed',
           'You\'re not charged for instance usage for a hibernated instance when it is in the stopped state or for data transfer when the contents of the RAM are transferred to the EBS root volume.',
           'You are charged for storage of any EBS volumes, including storage for the RAM contents.']),
      ],
      services: ['Amazon EC2 Auto Scaling', 'Amazon EC2'],
      design: [
        b('Cue: "keep average CPU at a level" → target tracking; "load rises every weekday morning" → scheduled scaling; "regular daily or weekly patterns and slow start-up" → predictive scaling; "Auto Scaling group instances take very long to boot" → a warm pool; "one instance takes a long time to reach a warm state" → hibernation to pre-warm.',
          ['asg-target-tracking', 'asg-scheduled', 'asg-predictive', 'asg-warm-pools', 'ec2-hibernate'],
          ['asg-scheduled|With scheduled scaling, you can set up automatic scaling for your application based on predictable load changes.',
           'asg-predictive|In general, if you have regular patterns of traffic increases and applications that take a long time to initialize, you should consider using predictive scaling.',
           'asg-warm-pools|A warm pool is a pool of pre-initialized EC2 instances that sits alongside an Auto Scaling group.',
           'ec2-hibernate|If an instance or application takes a long time to bootstrap and build a memory footprint to become fully productive, you can use hibernation to pre-warm the instance.']),
      ],
    },
    {
      id: '4.2-S1',
      concepts: [
        b('Elastic Load Balancing distributes traffic across multiple targets, such as EC2 instances, containers and IP addresses, in one or more Availability Zones, and sends requests only to healthy targets. Choose the type by the traffic and the need.',
          'elb-what-is',
          ['Elastic Load Balancing automatically distributes your incoming traffic across multiple targets, such as EC2 instances, containers, and IP addresses, in one or more Availability Zones.',
           'It monitors the health of its registered targets, and routes traffic only to the healthy targets.']),
        b('The Application Load Balancer works at the application layer, the seventh layer of the OSI model, and can route requests to different target groups based on the content of the application traffic, so one load balancer can front several services.',
          'alb-intro',
          ['An Application Load Balancer functions at the application layer, the seventh layer of the Open Systems Interconnection (OSI) model.',
           'You can configure listener rules to route requests to different target groups based on the content of the application traffic.'],
          { allow: ['seventh'] }),
        b('The Network Load Balancer works at the fourth layer, can handle millions of requests per second, and its target groups support protocols such as TCP, UDP and TLS.',
          'nlb-intro',
          ['Network Load Balancer functions at the fourth layer of the Open Systems Interconnection (OSI) model.',
           'It can handle millions of requests per second.',
           'Network Load Balancer target groups support the TCP, UDP, TCP_UDP, TLS, QUIC, and TCP_QUIC protocols.'],
          { allow: ['fourth'] }),
        b('The Gateway Load Balancer deploys, scales and manages virtual appliances such as firewalls and intrusion detection and prevention systems behind a single entry and exit point for traffic. The full comparison is in the Don\'t confuse section of Express Interchange.',
          'gwlb-intro',
          ['Gateway Load Balancers enable you to deploy, scale, and manage virtual appliances, such as firewalls, intrusion detection and prevention systems, and deep packet inspection systems.']),
      ],
      services: ['Elastic Load Balancing (ELB)'],
      design: [
        b('Cue: "HTTP routing by path or host" → Application Load Balancer; "extreme throughput of TCP or UDP traffic" → Network Load Balancer; "inspect all traffic with third-party appliances" → Gateway Load Balancer.',
          ['alb-intro', 'nlb-intro', 'gwlb-intro'],
          ['alb-intro|You can configure listener rules to route requests to different target groups based on the content of the application traffic.',
           'nlb-intro|It can handle millions of requests per second.',
           'gwlb-intro|Gateway Load Balancers enable you to deploy, scale, and manage virtual appliances, such as firewalls, intrusion detection and prevention systems, and deep packet inspection systems.']),
      ],
    },
    {
      id: '4.2-S2',
      concepts: [
        b('Scaling up (vertical) means moving to a larger instance by changing the instance type; scaling out (horizontal) means adding more instances. You change the type of a compatible EBS-backed instance only after stopping it, so plan for downtime, and you start paying the rate of the new type. Auto Scaling adds instances when demand rises and, because it can also terminate them, removes the cost when demand falls.',
          ['ec2-resize', 'ec2-resize-ebs', 'asg-target-tracking'],
          ['ec2-resize|When you change the instance type, you\'ll start paying the rate of the new instance type.',
           'ec2-resize-ebs|Considerations You must stop your instance before you can change its instance type.',
           'ec2-resize-ebs|Ensure that you plan for downtime while your instance is stopped.',
           'asg-target-tracking|Then, your Auto Scaling group will scale out, or increase capacity, when CPU exceeds 50 percent to handle increased load.']),
        b('Hibernation applies when you enable it at launch: you can enable hibernation for an On-Demand Instance or a Spot Instance when you launch it, and you cannot enable it on an existing instance, whether running or stopped. It needs an HVM AMI that supports hibernation, a supported instance family (bare metal instances are not supported), RAM below a size limit, and an encrypted EBS root volume large enough to hold the RAM contents.',
          'ec2-hibernate-prereq',
          ['You can enable hibernation support for an On-Demand Instance or a Spot Instance when you launch it.',
           'You can\'t enable hibernation on an existing instance, whether it is running or stopped.',
           'You must use an HVM AMI that supports hibernation.',
           'You must use an instance family that supports hibernation.',
           'However, bare metal instances are not supported.',
           'Linux instances – Must be less than 150 GiB.',
           'The root volume must be large enough to store the RAM contents and accommodate your expected usage, for example, OS or applications.',
           'The root volume must be encrypted to protect sensitive content that is in memory during hibernation.']),
      ],
      services: ['Amazon EC2', 'Amazon EC2 Auto Scaling'],
      design: [
        b('Cue: "single instance is too small, resize" → vertical, change the instance type; "traffic varies, add instances automatically" → horizontal with Auto Scaling; "instance is slow to warm up and sits idle between uses" → hibernation, enabled at launch.',
          ['ec2-resize', 'asg-what-is', 'ec2-hibernate-prereq'],
          ['ec2-resize|When you change the instance type, you\'ll start paying the rate of the new instance type.',
           'asg-what-is|If you specify scaling policies, then Amazon EC2 Auto Scaling can launch or terminate instances as demand on your application increases or decreases.',
           'ec2-hibernate-prereq|You can\'t enable hibernation on an existing instance, whether it is running or stopped.']),
      ],
    },
    {
      id: '4.2-S3',
      concepts: [
        b('Match the service to the workload shape. Lambda for short, event-driven work (a single invocation can run for up to 15 minutes), priced by requests and duration. Fargate for containers when you do not want to manage servers or clusters. EC2 when you need control of the instance, long-running processes, or a specific instance type, and then the purchasing options from Counting House apply.',
          ['lambda-quotas', 'lambda-pricing', 'fargate-ecs', 'ec2-purchasing'],
          ['lambda-quotas|Code can run for up to 15 minutes in a single invocation',
           'lambda-pricing|Lambda Functions are priced per request and execution duration.',
           'fargate-ecs|AWS Fargate is a technology that you can use with Amazon ECS to run containers without having to manage servers or clusters of Amazon EC2 instances.',
           'ec2-purchasing|You can use the following options to optimize your costs for Amazon EC2']),
        b('With Fargate you specify the CPU and memory requirements for the task, and each Fargate task has its own isolation boundary and does not share the underlying kernel, CPU, memory or network interface with another task.',
          'fargate-ecs',
          ['Each Fargate task has its own isolation boundary and does not share the underlying kernel, CPU resources, memory resources, or elastic network interface with another task.']),
      ],
      services: ['AWS Lambda', 'Amazon EC2', 'AWS Fargate'],
      design: [
        b('Cue: "infrequent, spiky workload, minimise cost" → Lambda; "containerised app, no instances to manage" → Fargate; "steady always-on load, specific instance type" → EC2 with Savings Plans or Reserved Instances; "interruptible batch" → EC2 Spot.',
          ['lambda-pricing', 'fargate-ecs', 'ec2-purchasing', 'ec2-spot'],
          ['lambda-pricing|Lambda Functions are priced per request and execution duration.',
           'fargate-ecs|With AWS Fargate, you no longer have to provision, configure, or scale clusters of virtual machines to run containers.',
           'ec2-purchasing|If you can\'t make a commitment to a specific instance configuration, but you can commit to a usage amount, purchase Savings Plans to reduce your On-Demand Instance costs.',
           'ec2-spot|Spot Instances are a cost-effective choice if you can be flexible about when your applications run and if your applications can be interrupted.']),
      ],
    },
  ],
  cues: [
    cue('unpredictable, spiky, event-driven work with no idle cost', 'AWS Lambda',
      b('Lambda functions are priced per request and execution duration.', 'lambda-pricing',
        ['Lambda Functions are priced per request and execution duration.'])),
    cue('run containers without managing servers or clusters', 'AWS Fargate',
      b('Fargate runs containers without having to manage servers or clusters of EC2 instances.', 'fargate-ecs',
        ['AWS Fargate is a technology that you can use with Amazon ECS to run containers without having to manage servers or clusters of Amazon EC2 instances.'])),
    cue('keep average CPU near a target to maintain high utilisation', 'Target tracking scaling',
      b('Target tracking helps maintain high utilisation for better cost efficiency without manual intervention.', 'asg-target-tracking',
        ['This allows your application to maintain optimal performance and high utilization for your EC2 instances for better cost efficiency without manual intervention.'])),
    cue('load changes at known times each week', 'Scheduled scaling',
      b('Scheduled scaling suits predictable load changes.', 'asg-scheduled',
        ['With scheduled scaling, you can set up automatic scaling for your application based on predictable load changes.'])),
    cue('regular daily or weekly pattern and slow-to-initialise application', 'Predictive scaling',
      b('Predictive scaling suits regular traffic patterns and applications that take a long time to initialise.', 'asg-predictive',
        ['In general, if you have regular patterns of traffic increases and applications that take a long time to initialize, you should consider using predictive scaling.'])),
    cue('instance takes a long time to warm up; stop it without paying for compute', 'EC2 hibernation (enabled at launch)',
      b('Hibernation can pre-warm an instance, and a hibernated instance in the stopped state is not charged for instance usage.', 'ec2-hibernate',
        ['If an instance or application takes a long time to bootstrap and build a memory footprint to become fully productive, you can use hibernation to pre-warm the instance.',
         'You\'re not charged for instance usage for a hibernated instance when it is in the stopped state or for data transfer when the contents of the RAM are transferred to the EBS root volume.'])),
    cue('route to different services by URL path on one load balancer', 'Application Load Balancer',
      b('An Application Load Balancer routes to different target groups based on the content of the request.', 'alb-intro',
        ['You can configure listener rules to route requests to different target groups based on the content of the application traffic.'])),
    cue('deploy and scale third-party virtual appliances such as firewalls', 'Gateway Load Balancer',
      b('Gateway Load Balancers deploy, scale and manage virtual appliances.', 'gwlb-intro',
        ['Gateway Load Balancers enable you to deploy, scale, and manage virtual appliances, such as firewalls, intrusion detection and prevention systems, and deep packet inspection systems.'])),
  ],
  examples: [],
  confuse: ['alb-nlb-gwlb'],
  azure: [
    {
      concept: 'Azure Functions',
      aws: 'AWS Lambda',
      mapping: b('The Learn compute comparison pairs AWS Lambda with Azure Functions: both provide serverless, event-driven code execution with pay-per-execution pricing and automatic scaling.',
        ['learn-compute', 'lambda-pricing'],
        ['learn-compute|AWS Lambda Azure Functions Both services provide serverless, event-driven code execution with pay-per-execution pricing and automatic scaling.',
         'lambda-pricing|Lambda Functions are priced per request and execution duration.']),
      breaks: b('The cost model on AWS has parts the Learn row does not show: Lambda is priced per request and execution duration, and provisioned concurrency incurs additional charges. In cost questions, check whether the answer adds provisioned concurrency when cold starts are acceptable.',
        ['lambda-concurrency', 'learn-compute'],
        ['lambda-concurrency|Configuring provisioned concurrency incurs charges to your AWS account.',
         'learn-compute|AWS Lambda Azure Functions Both services provide serverless, event-driven code execution with pay-per-execution pricing and automatic scaling.']),
    },
    {
      concept: 'Azure Virtual Machine Scale Sets',
      aws: 'Amazon EC2 Auto Scaling',
      mapping: b('Learn pairs AWS Auto Scaling with Azure Virtual Machine Scale Sets (and App Service autoscaling): in Azure, you use virtual machine scale sets to deploy and manage identical sets of VMs, and autoscaling changes the number of compute instances or resources based on defined metrics and thresholds.',
        ['learn-compute', 'asg-what-is'],
        ['learn-compute|In Azure, you can use virtual machine scale sets to deploy and manage identical sets of VMs.',
         'learn-compute|You can use autoscaling to automatically change the number of compute instances or resources based on defined metrics and thresholds.',
         'asg-what-is|If you specify scaling policies, then Amazon EC2 Auto Scaling can launch or terminate instances as demand on your application increases or decreases.']),
      breaks: b('On AWS the exam asks you to choose the scaling method: target tracking, scheduled or predictive scaling, plus minimum, maximum and desired capacity. The Learn row describes the group of identical VMs but not these policy types.',
        ['asg-predictive', 'learn-compute'],
        ['asg-predictive|Predictive scaling works by analyzing historical load data to detect daily or weekly patterns in traffic flows.',
         'learn-compute|In Azure, you can use virtual machine scale sets to deploy and manage identical sets of VMs.']),
    },
  ],
};

export default notes;
