import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'engine-exchange',
  overview: [
    b('The database engine decides the licence, the tools and the migration effort, so it is a cost decision as well as a technical one. Amazon RDS runs engines you already know, and Aurora is compatible with MySQL and PostgreSQL. Moving between engines is more work than keeping the same engine: AWS DMS migrates the data, and DMS Schema Conversion or the AWS Schema Conversion Tool converts the schema when the engine changes. Express Quarter introduced DMS; this building looks at the cost side of the same choices.',
      ['rds-what-is', 'aurora-overview', 'dms-what-is'],
      ['rds-what-is|You can use database engines that you are already familiar with: IBM Db2, MariaDB, Microsoft SQL Server, MySQL, Oracle Database, and PostgreSQL.',
       'aurora-overview|Amazon Aurora (Aurora) is a fully managed relational database engine that\'s compatible with MySQL and PostgreSQL.',
       'dms-what-is|With AWS DMS, you can discover your source data stores, convert your source schemas, and migrate your data.']),
  ],
  bullets: [
    {
      id: '4.3-K7',
      concepts: [
        b('A {{term:homogeneous-migration}} keeps the same engine and a {{term:heterogeneous-migration}} changes it. AWS DMS supports migrating away from old infrastructure while keeping the same engine, and fully heterogeneous migrations between the supported engines; to migrate to a different engine you can use DMS Schema Conversion.',
          'dms-what-is',
          ['Conversely, if you want to migrate away from old infrastructure but continue to use the same database engine, AWS DMS also supports that process.',
           'AWS DMS supports fully heterogeneous data migrations between the supported engines.',
           'To migrate to a different database engine, you can use DMS Schema Conversion.']),
        b('Amazon RDS lets you use engines you already know: IBM Db2, MariaDB, Microsoft SQL Server, MySQL, Oracle Database and PostgreSQL. Aurora is a relational engine compatible with MySQL and PostgreSQL, so the code, tools and applications you use with existing MySQL and PostgreSQL databases can be used with Aurora.',
          ['rds-what-is', 'aurora-overview'],
          ['rds-what-is|You can use database engines that you are already familiar with: IBM Db2, MariaDB, Microsoft SQL Server, MySQL, Oracle Database, and PostgreSQL.',
           'aurora-overview|The code, tools, and applications you use today with your existing MySQL and PostgreSQL databases can be used with Aurora.']),
      ],
      services: ['AWS DMS', 'Amazon RDS', 'Amazon Aurora'],
      design: [
        b('Cue: "same engine, move to AWS with minimal change" → homogeneous migration (DMS); "move from a commercial engine to MySQL or PostgreSQL" → heterogeneous migration with schema conversion first, then DMS.',
          'dms-what-is',
          ['After you convert your source schemas and apply the converted code to your target database, you can use AWS DMS to migrate your data.',
           'AWS DMS supports fully heterogeneous data migrations between the supported engines.']),
      ],
    },
    {
      id: '4.3-S2',
      concepts: [
        b('Choose the engine the application needs before comparing cost: MySQL or PostgreSQL applications can run on RDS or on Aurora, which is compatible with both, and Microsoft SQL Server, Oracle and Db2 applications run on RDS with their own engine. The code, tools and applications already written for an engine fix the choice; AWS gives no rule that one open-source engine is cheaper than the other, so a question that asks "MySQL compared with PostgreSQL" is decided by what the application already uses or needs.',
          ['rds-what-is', 'aurora-overview'],
          ['rds-what-is|You can use database engines that you are already familiar with: IBM Db2, MariaDB, Microsoft SQL Server, MySQL, Oracle Database, and PostgreSQL.',
           'aurora-overview|The code, tools, and applications you use today with your existing MySQL and PostgreSQL databases can be used with Aurora.']),
        b('Licensing is a cost lever for commercial engines. RDS for Oracle has two licensing options, License Included and Bring Your Own License. In License Included you do not need to purchase Oracle Database licences separately, and AWS holds the licence for the database software, but the model is only supported on Oracle Database Standard Edition 2; in BYOL you use your existing Oracle licences, and for a Multi-AZ deployment you must have a licence for both the primary and the standby DB instance.',
          'rds-oracle-licensing',
          ['Amazon RDS for Oracle has two licensing options: License Included (LI) and Bring Your Own License (BYOL).',
           'In the License Included model, you don\'t need to purchase Oracle Database licenses separately.',
           'AWS holds the license for the Oracle database software.',
           'The License Included model is only supported on Amazon RDS for Oracle Database Standard Edition 2 (SE2).',
           'If you use the Bring Your Own License model, you must have a license for both the primary DB instance and the standby DB instance in a Multi-AZ deployment.']),
        b('For Aurora, the storage configuration is a cost choice too. Aurora I/O-Optimized has no additional charges for read and write I/O operations and suits I/O-intensive applications; Aurora Standard is cost-effective for moderate I/O usage and adds a standard rate for I/O requests. AWS says I/O-Optimized is the better choice when I/O spending is a large share of total Aurora spending, and Standard when it is a small share.',
          'aurora-storage',
          ['Aurora I/O-Optimized – Improved price performance and predictability for I/O-intensive applications.',
           'You pay only for the usage and storage of your DB clusters, with no additional charges for read and write I/O operations.',
           'Aurora Standard – Cost-effective pricing for many applications with moderate I/O usage.',
           'In addition to the usage and storage of your DB clusters, you also pay a standard rate per 1 million requests for I/O operations.',
           'Aurora I/O-Optimized is the best choice when your I/O spending is 25% or more of your total Aurora database spending.',
           'Aurora Standard is the best choice when your I/O spending is less than 25% of your total Aurora database spending.']),
        b('Moving a workload from a commercial engine to MySQL or PostgreSQL can remove the licence cost. Aurora builds on the idea AWS states: MySQL and PostgreSQL combine the speed and reliability of high-end commercial databases with the simplicity and cost-effectiveness of open-source databases. The price of that change is a heterogeneous migration with schema conversion.',
          ['aurora-overview', 'dms-what-is'],
          ['aurora-overview|You already know how MySQL and PostgreSQL combine the speed and reliability of high-end commercial databases with the simplicity and cost-effectiveness of open-source databases.',
           'dms-what-is|This service automatically assesses and converts your source schemas to a new target engine.']),
      ],
      services: ['Amazon RDS', 'Amazon Aurora'],
      design: [
        b('Cue: "keep the existing Oracle licences" → RDS for Oracle with BYOL; "no licences to buy" → License Included; "application is MySQL or PostgreSQL compatible and needs elastic, resilient capacity" → Aurora.',
          ['rds-oracle-licensing', 'aurora-overview'],
          ['rds-oracle-licensing|In the BYOL model, you can use your existing Oracle Database licenses to deploy databases on Amazon RDS.',
           'aurora-overview|Amazon Aurora (Aurora) is a fully managed relational database engine that\'s compatible with MySQL and PostgreSQL.']),
      ],
    },
    {
      id: '4.3-S5',
      concepts: [
        b('AWS DMS migrates relational databases, data warehouses, NoSQL databases and other data stores into the AWS Cloud or between cloud and on-premises setups. Schemas move first when the engine changes: DMS Schema Conversion automatically assesses and converts your source schemas to a new target engine, or you can download the AWS Schema Conversion Tool (AWS SCT) to convert them, and after applying the converted code to the target database you use AWS DMS to migrate the data.',
          'dms-what-is',
          ['AWS Database Migration Service (AWS DMS) is a cloud service that makes it possible to migrate relational databases, data warehouses, NoSQL databases, and other types of data stores.',
           'This service automatically assesses and converts your source schemas to a new target engine.',
           'Alternatively, you can download the AWS Schema Conversion Tool (AWS SCT) to your local PC to convert your source schemas.After you convert your source schemas and apply the converted code to your target database, you can use AWS DMS to migrate your data.']),
        b('You can perform one-time migrations or replicate ongoing changes to keep sources and targets in sync, which lets you cut over with little downtime when the source stays live.',
          'dms-what-is',
          ['You can perform one-time migrations or replicate ongoing changes to keep sources and targets in sync.']),
        b('For cost, AWS DMS Serverless provides automatic provisioning, scaling, built-in high availability and a pay-for-use billing model. It removes replication instance management tasks like capacity estimation, provisioning and cost optimisation, so you do not size and pay for a replication instance yourself.',
          'dms-serverless',
          ['AWS DMS Serverless is a feature that provides automatic provisioning, scaling, built-in high availability, and a pay-for-use billing model, to increase operations agility and optimize your costs.',
           'The Serverless feature eliminates replication instance management tasks like capacity estimation, provisioning, cost optimization, and managing replication engine versions and patching.']),
      ],
      services: ['AWS DMS', 'Amazon RDS', 'Amazon Aurora'],
      design: [
        b('Cue: "convert the schema to a different engine" → DMS Schema Conversion or AWS SCT; "move the data and keep replicating changes" → AWS DMS; "do not want to manage or size the replication capacity" → AWS DMS Serverless.',
          ['dms-what-is', 'dms-serverless'],
          ['dms-what-is|After you convert your source schemas and apply the converted code to your target database, you can use AWS DMS to migrate your data.',
           'dms-serverless|AWS DMS Serverless is a feature that provides automatic provisioning, scaling, built-in high availability, and a pay-for-use billing model, to increase operations agility and optimize your costs.']),
      ],
    },
  ],
  cues: [
    cue('same database engine, moving away from old infrastructure', 'Homogeneous migration with AWS DMS',
      b('AWS DMS supports migrating away from old infrastructure while using the same engine.', 'dms-what-is',
        ['Conversely, if you want to migrate away from old infrastructure but continue to use the same database engine, AWS DMS also supports that process.'])),
    cue('migrate to a different database engine', 'DMS Schema Conversion (or AWS SCT), then AWS DMS',
      b('To migrate to a different engine you can use DMS Schema Conversion.', 'dms-what-is',
        ['To migrate to a different database engine, you can use DMS Schema Conversion.'])),
    cue('keep existing Oracle licences on RDS', 'RDS for Oracle Bring Your Own License',
      b('In the BYOL model you use your existing Oracle Database licences on RDS.', 'rds-oracle-licensing',
        ['In the BYOL model, you can use your existing Oracle Database licenses to deploy databases on Amazon RDS.'])),
    cue('no Oracle licence purchase, pay as part of the instance', 'RDS for Oracle License Included',
      b('In License Included you do not purchase Oracle Database licences separately.', 'rds-oracle-licensing',
        ['In the License Included model, you don\'t need to purchase Oracle Database licenses separately.'])),
    cue('migrate with pay-for-use billing and no replication instance to size', 'AWS DMS Serverless',
      b('DMS Serverless provides automatic provisioning, scaling and a pay-for-use billing model.', 'dms-serverless',
        ['AWS DMS Serverless is a feature that provides automatic provisioning, scaling, built-in high availability, and a pay-for-use billing model, to increase operations agility and optimize your costs.'])),
    cue('keep source and target in sync until cut-over', 'DMS ongoing replication',
      b('DMS can replicate ongoing changes to keep sources and targets in sync.', 'dms-what-is',
        ['You can perform one-time migrations or replicate ongoing changes to keep sources and targets in sync.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Database Migration Service',
      aws: 'AWS Database Migration Service (AWS DMS)',
      mapping: b('Learn pairs AWS DMS with Azure Database Migration Service, and says support varies by source, target and online or offline migration mode.',
        ['learn-databases', 'dms-what-is'],
        ['learn-databases|Database migration AWS Database Migration Service Azure Database Migration Service Support varies by source, target, and online or offline migration mode.',
         'dms-what-is|AWS DMS supports fully heterogeneous data migrations between the supported engines.']),
      breaks: b('The Learn row does not cover the AWS cost options. On AWS you can run AWS DMS Serverless, which has a pay-for-use billing model and removes the need to size a replication instance, and the licensing choice for the target engine (for example License Included or Bring Your Own License for RDS for Oracle) is a separate cost decision from the migration tool.',
        ['dms-serverless', 'rds-oracle-licensing', 'learn-databases'],
        ['dms-serverless|AWS DMS Serverless is a feature that provides automatic provisioning, scaling, built-in high availability, and a pay-for-use billing model, to increase operations agility and optimize your costs.',
         'rds-oracle-licensing|Amazon RDS for Oracle has two licensing options: License Included (LI) and Bring Your Own License (BYOL).',
         'learn-databases|Support varies by source, target, and online or offline migration mode.']),
    },
  ],
};

export default notes;
