import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'haul-hybrid-customs',
  overview: [
    b('Transfer Dock covered how the transfer services work. This building asks the cost question: which method gets the data into AWS storage at the lowest cost while meeting the deadline? The inputs are the same (data size, network speed, one-time or ongoing, protocol) but the answer is the cheapest option that still fits, not the fastest. Actual prices are on AWS pricing pages and change, so this building teaches how to compare options, not figures.',
      ['datasync-what-is', 'transfer-what-is', 'storage-gateway-docs'],
      ['datasync-what-is|AWS DataSync is a secure, reliable, high‐speed file transfer service that helps you quickly and easily transfer your file or object data to, from, and between AWS storage services.',
       'transfer-what-is|AWS Transfer Family is a secure transfer service that enables you to transfer files into and out of AWS storage services.',
       'storage-gateway-docs|AWS Storage Gateway is a service that connects an on-premises software appliance with cloud-based storage to provide seamless and secure integration between your on-premises IT environment and the AWS storage infrastructure in the AWS Cloud.']),
  ],
  bullets: [
    {
      id: '4.1-K8',
      concepts: [
        b('Hybrid storage options keep some data on premises and some in AWS. AWS DataSync transfers file or object data between on-premises storage (NFS, SMB, HDFS, object storage) and AWS storage services. AWS Transfer Family gives partners and applications SFTP, AS2, FTPS and FTP access to S3 or EFS. AWS Storage Gateway connects an on-premises appliance to cloud storage for ongoing access.',
          ['datasync-what-is', 'transfer-what-is', 'storage-gateway-docs'],
          ['datasync-what-is|DataSync works with the following on-premises storage systems: Network File System (NFS) Server Message Block (SMB) Hadoop Distributed File Systems (HDFS) Object storage',
           'transfer-what-is|AWS Transfer Family offers fully managed support for the transfer of files over SFTP, AS2, FTPS, FTP, and web browser-based transfers directly into and out of AWS storage services.',
           'storage-gateway-docs|AWS Storage Gateway is a service that connects an on-premises software appliance with cloud-based storage to provide seamless and secure integration between your on-premises IT environment and the AWS storage infrastructure in the AWS Cloud.']),
        b('Storage Gateway is the cost-oriented hybrid option when on-premises applications must keep their file, volume or tape interfaces: S3 File Gateway provides a cost-effective alternative to on-premises storage, and Tape Gateway lets you cost-effectively and durably archive backup data in S3 Glacier Flexible Retrieval or S3 Glacier Deep Archive.',
          ['sgw-file-s3', 'sgw-tape'],
          ['sgw-file-s3|A S3 File Gateway simplifies file storage in Amazon S3, integrates to existing applications through industry-standard file system protocols, and provides a cost-effective alternative to on-premises storage.',
           'sgw-tape|With Tape Gateway, you can cost-effectively and durably archive backup data in S3 Glacier Flexible Retrieval or S3 Glacier Deep Archive.']),
      ],
      services: ['AWS DataSync', 'AWS Transfer Family', 'AWS Storage Gateway'],
      design: [
        b('Cue: ongoing hybrid access with local caching → Storage Gateway; scheduled or one-time bulk copy → DataSync; partners using SFTP → Transfer Family.',
          ['datasync-what-is', 'sgw-file-s3'],
          ['datasync-what-is|AWS DataSync is a secure, reliable, high‐speed file transfer service that helps you quickly and easily transfer your file or object data to, from, and between AWS storage services.',
           'sgw-file-s3|You can think of a S3 File Gateway as a file system mount on Amazon S3.']),
      ],
    },
    {
      id: '4.1-S1',
      concepts: [
        b('Batch uploads against many small ones. Multipart upload splits one large object into parts uploaded independently and in parallel, which improves throughput and recovers quickly from network problems, and AWS suggests considering it for large objects. Because every upload is a request, grouping small files into fewer, larger objects reduces the number of requests, which S3 bills along with storage and bandwidth.',
          's3-multipart',
          ['Multipart upload allows you to upload a single object to Amazon S3 as a set of parts.',
           'Improved throughput – You can upload parts in parallel to improve throughput.',
           'Quick recovery from any network issues – Smaller part size minimizes the impact of restarting a failed upload due to a network error.',
           'Throughout its lifetime, you are billed for all storage, bandwidth, and requests for this multipart upload and its associated parts.']),
        b('Incomplete multipart uploads cost money: while the parts of an in-progress multipart upload exist, you are billed for the storage, bandwidth and requests for the upload and its parts, so abort or complete uploads and use a lifecycle rule to clean up incomplete ones.',
          's3-multipart',
          ['Throughout its lifetime, you are billed for all storage, bandwidth, and requests for this multipart upload and its associated parts.']),
        b('S3 Transfer Acceleration is a bucket-level feature for fast transfers over long distances between your client and an S3 general purpose bucket, using the globally distributed edge locations of CloudFront. It suits users uploading from all over the world to a central bucket, or bandwidth you cannot fully use over the internet.',
          's3-transfer-acceleration',
          ['Amazon S3 Transfer Acceleration is a bucket-level feature that enables fast, easy, and secure transfers of files over long distances between your client and an S3 general purpose bucket.',
           'Your customers upload to a centralized general purpose bucket from all over the world.',
           'You can\'t use all of your available bandwidth over the internet when uploading to Amazon S3.']),
      ],
      services: ['Amazon S3'],
      design: [
        b('Cue: many tiny files and high request counts → batch into larger objects; one large file over an unreliable link → multipart upload; global uploaders to one bucket → Transfer Acceleration.',
          ['s3-multipart', 's3-transfer-acceleration'],
          ['s3-multipart|Improved throughput – You can upload parts in parallel to improve throughput.',
           's3-transfer-acceleration|Your customers upload to a centralized general purpose bucket from all over the world.']),
      ],
    },
    {
      id: '4.1-S3',
      concepts: [
        b('Lowest cost means the cheapest method that still meets the deadline: if the existing network can move the data in time, an online service (DataSync, or a plain upload with multipart) avoids buying extra hardware or connections; if it cannot, a physical transfer or a faster dedicated connection is considered. Snowball Edge, the classic offline option, is no longer available to new customers; AWS points new customers to DataSync for online transfers, Data Transfer Terminal for secure physical transfers, or partner solutions.',
          ['snowball-edge', 'dtt'],
          ['snowball-edge|AWS Snowball Edge is no longer available to new customers.',
           'snowball-edge|New customers should explore AWS DataSync for online transfers, AWS Data Transfer Terminal for secure physical transfers, or AWS Partner solutions.',
           'dtt|AWS Data Transfer Terminal is a network-ready, physical location you can bring your data storage devices for fast data transfer to and from your AWS Cloud service.'],
          { status: 'deprecated' }),
        b('Cost factors AWS expects you to weigh: Direct Connect and VPN connections are the two connectivity options and their cost differs (Transit Tariff), the storage class you land the data in (Cold Cellar), and request counts for many small objects.',
          ['dx-what-is', 's2s-vpn'],
          ['dx-what-is|Direct Connect links your internal network to a Direct Connect location over a standard Ethernet fiber-optic cable.',
           's2s-vpn|Site-to-Site VPN supports Internet Protocol security (IPsec) VPN connections.'],
          { allow: ['two'] }),
      ],
      services: ['AWS DataSync', 'AWS Snow Family', 'AWS Direct Connect'],
      design: [
        b('Cue: "least expensive way to move a large amount of data when bandwidth is limited" → an offline physical option (and note Snowball Edge availability); "ongoing small changes" → DataSync or Storage Gateway over the existing link.',
          'snowball-edge',
          ['Each Snowball Edge device can transport data at speeds faster than the internet.']),
      ],
    },
    {
      id: '4.1-S7',
      concepts: [
        b('Selecting the migration service by what is being moved: file or object data between storage systems → DataSync; files over SFTP, AS2, FTPS or FTP → Transfer Family; continuing hybrid access to cloud-backed volumes, files or tapes → Storage Gateway; databases → AWS DMS (Database Registry).',
          ['datasync-what-is', 'transfer-what-is', 'sgw-volume', 'dms-what-is'],
          ['datasync-what-is|AWS DataSync is a secure, reliable, high‐speed file transfer service that helps you quickly and easily transfer your file or object data to, from, and between AWS storage services.',
           'transfer-what-is|AWS Transfer Family offers fully managed support for the transfer of files over SFTP, AS2, FTPS, FTP, and web browser-based transfers directly into and out of AWS storage services.',
           'sgw-volume|AWS Storage Gateway offers file-based (S3 File Gateway and FSx File Gateway), volume-based (Volume Gateway), and tape-based (Tape Gateway) storage solutions.',
           'dms-what-is|AWS Database Migration Service (AWS DMS) is a cloud service that makes it possible to migrate relational databases, data warehouses, NoSQL databases, and other types of data stores.']),
      ],
      services: ['AWS DataSync', 'AWS Transfer Family', 'AWS Storage Gateway', 'AWS Snow Family'],
      design: [
        b('Pattern: protocol and purpose pick the service; size and speed pick online or offline; both then pick the destination storage class for cost.',
          'datasync-what-is',
          ['DataSync works with the following AWS storage services: Amazon S3 Amazon EFS Amazon FSx for Windows File Server Amazon FSx for Lustre Amazon FSx for OpenZFS Amazon FSx for NetApp ONTAP']),
      ],
    },
  ],
  cues: [
    cue('scheduled copy of NFS/SMB data into S3 or EFS', 'AWS DataSync',
      b('DataSync transfers file or object data to, from and between AWS storage services.', 'datasync-what-is',
        ['AWS DataSync is a secure, reliable, high‐speed file transfer service that helps you quickly and easily transfer your file or object data to, from, and between AWS storage services.'])),
    cue('SFTP clients must keep working against S3', 'AWS Transfer Family',
      b('Transfer Family supports SFTP, AS2, FTPS and FTP.', 'transfer-what-is',
        ['AWS Transfer Family offers fully managed support for the transfer of files over SFTP, AS2, FTPS, FTP, and web browser-based transfers directly into and out of AWS storage services.'])),
    cue('replace physical tapes with cloud-backed virtual tapes', 'Tape Gateway',
      b('Tape Gateway provides cloud-backed virtual tape storage and cost-effective durable archive.', 'sgw-tape',
        ['With Tape Gateway, you can cost-effectively and durably archive backup data in S3 Glacier Flexible Retrieval or S3 Glacier Deep Archive.'])),
    cue('uploads of very large objects fail over unreliable networks', 'S3 multipart upload',
      b('Multipart upload recovers quickly from network issues by restarting only a failed part.', 's3-multipart',
        ['Quick recovery from any network issues – Smaller part size minimizes the impact of restarting a failed upload due to a network error.'])),
    cue('users worldwide upload to one bucket, long distance', 'S3 Transfer Acceleration',
      b('Transfer Acceleration speeds transfers over long distances using CloudFront edge locations.', 's3-transfer-acceleration',
        ['Amazon S3 Transfer Acceleration is a bucket-level feature that enables fast, easy, and secure transfers of files over long distances between your client and an S3 general purpose bucket.'])),
    cue('stored parts of abandoned multipart uploads are costing money', 'Abort incomplete multipart uploads (lifecycle rule)',
      b('You are billed for storage, bandwidth and requests of an in-progress multipart upload and its parts.', 's3-multipart',
        ['Throughout its lifetime, you are billed for all storage, bandwidth, and requests for this multipart upload and its associated parts.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Data Box',
      aws: 'AWS Snowball Edge',
      mapping: b('Learn pairs Snowball Edge with Azure Data Box, a data transport solution that uses enhanced-security storage devices to transfer large amounts of data to and from Azure.',
        ['learn-storage', 'snowball-edge'],
        ['learn-storage|Snowball Edge Data Box Petabyte-scale to exabyte-scale data transport solution that uses enhanced-security data storage devices to transfer large amounts of data to and from Azure.',
         'snowball-edge|Snowball Edge is a device with on-board storage and compute power for select AWS capabilities.']),
      breaks: b('Do not treat the pairing as a current AWS choice for a new design: AWS says Snowball Edge is no longer available to new customers and points to DataSync, Data Transfer Terminal or partners.',
        ['snowball-edge', 'learn-storage'],
        ['snowball-edge|AWS Snowball Edge is no longer available to new customers.',
         'learn-storage|Snowball Edge Data Box Petabyte-scale to exabyte-scale data transport solution that uses enhanced-security data storage devices to transfer large amounts of data to and from Azure.']),
    },
    {
      concept: 'Azure File Sync',
      aws: 'AWS DataSync and S3 File Gateway',
      mapping: b('Learn pairs DataSync with Azure File Sync, and notes Azure Files can be deployed by directly mounting serverless Azure file shares or by caching Azure file shares on-premises using Azure File Sync.',
        ['learn-storage', 'datasync-what-is'],
        ['learn-storage|DataSync File Sync Azure Files can be deployed in two main ways: by directly mounting the serverless Azure file shares or by caching Azure file shares on-premises using Azure File Sync.',
         'datasync-what-is|AWS DataSync is a secure, reliable, high‐speed file transfer service that helps you quickly and easily transfer your file or object data to, from, and between AWS storage services.'],
        { allow: ['two'] }),
      breaks: b('They are not the same kind of service. Azure File Sync caches an Azure file share on premises, much like an AWS S3 File Gateway, whereas DataSync is a managed transfer service that moves data between storage systems.',
        ['sgw-file-s3', 'datasync-what-is', 'learn-storage'],
        ['sgw-file-s3|You can think of a S3 File Gateway as a file system mount on Amazon S3.',
         'datasync-what-is|AWS DataSync is a secure, reliable, high‐speed file transfer service that helps you quickly and easily transfer your file or object data to, from, and between AWS storage services.',
         'learn-storage|Provides on-premises, locally cached NFS and SMB file shares that are cloud-backed.']),
    },
  ],
};

export default notes;
