import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'haul-hybrid-customs',
  overview: [
    b('Transfer Dock covered how the transfer services work. This building asks the cost question: which method gets the data into AWS storage at the lowest cost while meeting the deadline? The inputs are the same (data size, network speed, one-time or ongoing, protocol) but the answer is the cheapest option that still fits, not the fastest. Actual prices are on AWS pricing pages and change, so this building teaches how to compare options, not figures.',
      ['datasync-what-is', 'transfer-what-is', 'storage-gateway-docs'],
      ['datasync-what-is|AWS DataSync is a secure, reliable, high‐speed file transfer service that helps you quickly and easily transfer your file or object data to, from, and between AWS storage services.',
       'transfer-what-is|AWS Transfer Family is a secure transfer service that enables you to transfer files into and out of AWS storage services.',
       'storage-gateway-docs|AWS Storage Gateway is a service that connects an on-premises software appliance with cloud-based storage to provide seamless and secure integration between your on-premises IT environment and the AWS storage infrastructure in the AWS Cloud.']),
  ],
  bullets: [
    {
      id: '4.1-K8',
      concepts: [
        b('Hybrid storage options keep some data on premises and some in AWS. AWS DataSync transfers file or object data between on-premises storage (NFS, SMB, HDFS, object storage) and AWS storage services. AWS Transfer Family gives partners and applications SFTP, AS2, FTPS and FTP access to S3 or EFS. AWS Storage Gateway connects an on-premises appliance to cloud storage for ongoing access.',
          ['datasync-what-is', 'transfer-what-is', 'storage-gateway-docs'],
          ['datasync-what-is|DataSync works with the following on-premises storage systems: Network File System (NFS) Server Message Block (SMB) Hadoop Distributed File Systems (HDFS) Object storage',
           'transfer-what-is|AWS Transfer Family offers fully managed support for the transfer of files over SFTP, AS2, FTPS, FTP, and web browser-based transfers directly into and out of AWS storage services.',
           'storage-gateway-docs|AWS Storage Gateway is a service that connects an on-premises software appliance with cloud-based storage to provide seamless and secure integration between your on-premises IT environment and the AWS storage infrastructure in the AWS Cloud.']),
        b('The services are billed differently. DataSync charges a flat per-gigabyte fee for the amount of data transferred between your storage locations, with no upfront costs and no minimum charges. Transfer Family charges for the protocols enabled on your server endpoints, plus the gigabytes uploaded and downloaded, so an enabled endpoint is a cost to remove when it is not in use; standard request, storage and data transfer rates for S3 or EFS are charged in addition.',
          ['datasync-pricing', 'transfer-pricing'],
          ['datasync-pricing|You pay a flat, per-gigabyte fee for the amount of data transferred between your storage locations.',
           'datasync-pricing|With DataSync, there are no upfront costs and no minimum charges.',
           'transfer-pricing|You only pay for the protocols enabled on your Server endpoint(s), the amount of data (gigabytes) uploaded and downloaded over SFTP or FTPS or FTP, or the number of messages sent or received over AS2, and the amount of data processed using Transfer Family workflows.',
           'transfer-pricing|You are charged standard request, storage, and data transfer rates to read to and write from Amazon S3 or Amazon EFS.']),
        b('Storage Gateway is the cost-oriented hybrid option when on-premises applications must keep their file, volume or tape interfaces: S3 File Gateway provides a cost-effective alternative to on-premises storage, and Tape Gateway lets you cost-effectively and durably archive backup data in S3 Glacier Flexible Retrieval or S3 Glacier Deep Archive.',
          ['sgw-file-s3', 'sgw-tape'],
          ['sgw-file-s3|A S3 File Gateway simplifies file storage in Amazon S3, integrates to existing applications through industry-standard file system protocols, and provides a cost-effective alternative to on-premises storage.',
           'sgw-tape|With Tape Gateway, you can cost-effectively and durably archive backup data in S3 Glacier Flexible Retrieval or S3 Glacier Deep Archive.']),
      ],
      services: ['AWS DataSync', 'AWS Transfer Family', 'AWS Storage Gateway'],
      design: [
        b('Cue: ongoing hybrid access with local caching → Storage Gateway; scheduled or one-time bulk copy → DataSync; partners using SFTP → Transfer Family.',
          ['datasync-what-is', 'sgw-file-s3'],
          ['datasync-what-is|AWS DataSync is a secure, reliable, high‐speed file transfer service that helps you quickly and easily transfer your file or object data to, from, and between AWS storage services.',
           'sgw-file-s3|You can think of a S3 File Gateway as a file system mount on Amazon S3.']),
      ],
    },
    {
      id: '4.1-S1',
      concepts: [
        b('Batch uploads against many small ones. Multipart upload splits one large object into parts uploaded independently and in parallel, which improves throughput and recovers quickly from network problems, and AWS suggests considering it for large objects. S3 charges per request for PUT requests that ingest objects, so many individual uploads of small files mean many billed requests, while grouping them into fewer, larger objects means fewer.',
          ['s3-multipart', 's3-pricing'],
          ['Multipart upload allows you to upload a single object to Amazon S3 as a set of parts.',
           'Improved throughput – You can upload parts in parallel to improve throughput.',
           'Quick recovery from any network issues – Smaller part size minimizes the impact of restarting a failed upload due to a network error.',
           's3-pricing|There are per-request ingest charges when using PUT, COPY, or lifecycle rules to move data into any S3 storage class.']),
        b('Incomplete multipart uploads cost money: while the parts of an in-progress multipart upload exist, you are billed for the storage, bandwidth and requests for the upload and its parts, so abort or complete uploads and use a lifecycle rule to clean up incomplete ones.',
          's3-multipart',
          ['Throughout its lifetime, you are billed for all storage, bandwidth, and requests for this multipart upload and its associated parts.']),
        b('S3 Transfer Acceleration is a bucket-level feature for fast transfers over long distances between your client and an S3 general purpose bucket, using the globally distributed edge locations of CloudFront. It suits users uploading from all over the world to a central bucket, or bandwidth you cannot fully use over the internet. When you use Transfer Acceleration, additional data transfer charges might apply.',
          's3-transfer-acceleration',
          ['Amazon S3 Transfer Acceleration is a bucket-level feature that enables fast, easy, and secure transfers of files over long distances between your client and an S3 general purpose bucket.',
           'Your customers upload to a centralized general purpose bucket from all over the world.',
           'You can\'t use all of your available bandwidth over the internet when uploading to Amazon S3.',
           'When you use Transfer Acceleration, additional data transfer charges might apply.']),
      ],
      services: ['Amazon S3'],
      design: [
        b('Cue: many tiny files and high request counts → batch into larger objects; one large file over an unreliable link → multipart upload; global uploaders to one bucket → Transfer Acceleration.',
          ['s3-multipart', 's3-transfer-acceleration'],
          ['s3-multipart|Improved throughput – You can upload parts in parallel to improve throughput.',
           's3-transfer-acceleration|Your customers upload to a centralized general purpose bucket from all over the world.']),
      ],
    },
    {
      id: '4.1-S3',
      concepts: [
        b('AWS Data Transfer Terminal is a network-ready, physical location you can bring your data storage devices to for fast data transfer to and from your AWS Cloud service. As study guidance, lowest cost means choosing the cheapest method that still meets the deadline.',
          ['dtt'],
          ['dtt|AWS Data Transfer Terminal is a network-ready, physical location you can bring your data storage devices for fast data transfer to and from your AWS Cloud service.']),
        b('Snowball Edge, the classic offline option, is no longer available to new customers; AWS points new customers to DataSync for online transfers, Data Transfer Terminal for secure physical transfers, or partner solutions. For a current design, base the offline option on what AWS now points to.',
          ['snowball-edge'],
          ['snowball-edge|AWS Snowball Edge is no longer available to new customers.',
           'snowball-edge|New customers should explore AWS DataSync for online transfers, AWS Data Transfer Terminal for secure physical transfers, or AWS Partner solutions.'],
          { status: 'closed' }),
        b('Two connectivity options: Direct Connect links your internal network to a Direct Connect location over a standard Ethernet fiber-optic cable, and Site-to-Site VPN supports IPsec VPN connections. Compare their costs in Transit Tariff, and the landing storage class in Cold Cellar.',
          ['dx-what-is', 's2s-vpn'],
          ['dx-what-is|Direct Connect links your internal network to a Direct Connect location over a standard Ethernet fiber-optic cable.',
           's2s-vpn|Site-to-Site VPN supports Internet Protocol security (IPsec) VPN connections.'],
          { allow: ['two'] }),
      ],
      services: ['AWS DataSync', 'AWS Snow Family', 'AWS Direct Connect'],
      design: [
        b('Cue: "least expensive way to move a large amount of data when bandwidth is limited" → an offline physical option (and note Snowball Edge availability); "ongoing small changes" → DataSync or Storage Gateway over the existing link.',
          'snowball-edge',
          ['Each Snowball Edge device can transport data at speeds faster than the internet.']),
      ],
    },
    {
      id: '4.1-S7',
      concepts: [
        b('Selecting the migration service by what is being moved: file or object data between storage systems → DataSync; files over SFTP, AS2, FTPS or FTP → Transfer Family; continuing hybrid access to cloud-backed volumes, files or tapes → Storage Gateway; databases → AWS DMS (Database Registry).',
          ['datasync-what-is', 'transfer-what-is', 'sgw-volume', 'dms-what-is'],
          ['datasync-what-is|AWS DataSync is a secure, reliable, high‐speed file transfer service that helps you quickly and easily transfer your file or object data to, from, and between AWS storage services.',
           'transfer-what-is|AWS Transfer Family offers fully managed support for the transfer of files over SFTP, AS2, FTPS, FTP, and web browser-based transfers directly into and out of AWS storage services.',
           'sgw-volume|AWS Storage Gateway offers file-based (S3 File Gateway and FSx File Gateway), volume-based (Volume Gateway), and tape-based (Tape Gateway) storage solutions.',
           'dms-what-is|AWS Database Migration Service (AWS DMS) is a cloud service that makes it possible to migrate relational databases, data warehouses, NoSQL databases, and other types of data stores.']),
      ],
      services: ['AWS DataSync', 'AWS Transfer Family', 'AWS Storage Gateway', 'AWS Snow Family'],
      design: [
        b('Pattern: protocol and purpose pick the service; size and speed pick online or offline; both then pick the destination storage class for cost.',
          'datasync-what-is',
          ['DataSync works with the following AWS storage services: Amazon S3 Amazon EFS Amazon FSx for Windows File Server Amazon FSx for Lustre Amazon FSx for OpenZFS Amazon FSx for NetApp ONTAP']),
      ],
    },
  ],
  cues: [
    cue('scheduled copy of NFS/SMB data into S3 or EFS', 'AWS DataSync',
      b('DataSync transfers file or object data to, from and between AWS storage services.', 'datasync-what-is',
        ['AWS DataSync is a secure, reliable, high‐speed file transfer service that helps you quickly and easily transfer your file or object data to, from, and between AWS storage services.'])),
    cue('SFTP clients must keep working against S3', 'AWS Transfer Family',
      b('Transfer Family supports SFTP, AS2, FTPS and FTP.', 'transfer-what-is',
        ['AWS Transfer Family offers fully managed support for the transfer of files over SFTP, AS2, FTPS, FTP, and web browser-based transfers directly into and out of AWS storage services.'])),
    cue('replace physical tapes with cloud-backed virtual tapes', 'Tape Gateway',
      b('Tape Gateway provides cloud-backed virtual tape storage and cost-effective durable archive.', 'sgw-tape',
        ['With Tape Gateway, you can cost-effectively and durably archive backup data in S3 Glacier Flexible Retrieval or S3 Glacier Deep Archive.'])),
    cue('uploads of very large objects fail over unreliable networks', 'S3 multipart upload',
      b('Multipart upload recovers quickly from network issues by restarting only a failed part.', 's3-multipart',
        ['Quick recovery from any network issues – Smaller part size minimizes the impact of restarting a failed upload due to a network error.'])),
    cue('users worldwide upload to one bucket, long distance', 'S3 Transfer Acceleration',
      b('Transfer Acceleration speeds transfers over long distances using CloudFront edge locations.', 's3-transfer-acceleration',
        ['Amazon S3 Transfer Acceleration is a bucket-level feature that enables fast, easy, and secure transfers of files over long distances between your client and an S3 general purpose bucket.'])),
    cue('stored parts of abandoned multipart uploads are costing money', 'Abort incomplete multipart uploads (lifecycle rule)',
      b('You are billed for storage, bandwidth and requests of an in-progress multipart upload and its parts.', 's3-multipart',
        ['Throughout its lifetime, you are billed for all storage, bandwidth, and requests for this multipart upload and its associated parts.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Data Box',
      aws: 'AWS Snowball Edge',
      mapping: b('Learn pairs Snowball Edge with Azure Data Box, a data transport solution that uses enhanced-security storage devices to transfer large amounts of data to and from Azure.',
        ['learn-storage', 'snowball-edge'],
        ['learn-storage|Snowball Edge Data Box Petabyte-scale to exabyte-scale data transport solution that uses enhanced-security data storage devices to transfer large amounts of data to and from Azure.',
         'snowball-edge|Snowball Edge is a device with on-board storage and compute power for select AWS capabilities.']),
      breaks: b('Learn pairs Snowball Edge with Azure Data Box; AWS says Snowball Edge is no longer available to new customers and points new customers to DataSync, Data Transfer Terminal or partner solutions.',
        ['snowball-edge', 'learn-storage'],
        ['snowball-edge|AWS Snowball Edge is no longer available to new customers.',
         'learn-storage|Snowball Edge Data Box Petabyte-scale to exabyte-scale data transport solution that uses enhanced-security data storage devices to transfer large amounts of data to and from Azure.']),
    },
    {
      concept: 'Azure File Sync',
      aws: 'AWS DataSync and S3 File Gateway',
      mapping: b('Learn pairs DataSync with Azure File Sync, and notes Azure Files can be deployed by directly mounting serverless Azure file shares or by caching Azure file shares on-premises using Azure File Sync.',
        ['learn-storage', 'datasync-what-is'],
        ['learn-storage|DataSync File Sync Azure Files can be deployed in two main ways: by directly mounting the serverless Azure file shares or by caching Azure file shares on-premises using Azure File Sync.',
         'datasync-what-is|AWS DataSync is a secure, reliable, high‐speed file transfer service that helps you quickly and easily transfer your file or object data to, from, and between AWS storage services.'],
        { allow: ['two'] }),
      breaks: b('Learn lists Azure File Sync against both DataSync and S3 File Gateway, and describes S3 File Gateway as providing on-premises, locally cached NFS and SMB file shares that are cloud-backed. AWS describes S3 File Gateway as a file system mount on Amazon S3, whereas DataSync is a file transfer service for moving file or object data to, from and between AWS storage services.',
        ['sgw-file-s3', 'datasync-what-is', 'learn-storage'],
        ['sgw-file-s3|You can think of a S3 File Gateway as a file system mount on Amazon S3.',
         'datasync-what-is|AWS DataSync is a secure, reliable, high‐speed file transfer service that helps you quickly and easily transfer your file or object data to, from, and between AWS storage services.',
         'learn-storage|Provides on-premises, locally cached NFS and SMB file shares that are cloud-backed.']),
    },
  ],
};

export default notes;
