import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'instance-foundry',
  overview: [
    b('The instance type you pick is a cost decision. An instance type fixes the hardware of the host your instance runs on, each type is grouped in a family by its compute, memory and storage capabilities, and a size within the family sets how much of that capability you get. Engine Works (Express Quarter) taught the families for performance; this building uses them to pick the cheapest instance that still fits, and to find out when the instance you have is the wrong one.',
      ['ec2-instance-types', 'ec2-resize'],
      ['ec2-instance-types|Each instance type offers different compute, memory, and storage capabilities, and is grouped in an instance family based on these capabilities.',
       'ec2-instance-types|When you launch an EC2 instance, the instance type that you specify determines the hardware of the host computer used for your instance.',
       'ec2-resize|When you change the instance type, you\'ll start paying the rate of the new instance type.']),
  ],
  bullets: [
    {
      id: '4.2-K7',
      concepts: [
        b('Families are named for the resource they are rich in. General purpose instances use compute, memory and networking in equal proportions; compute optimized instances suit compute intensive work such as batch processing, media transcoding and high performance web servers; memory optimized instances suit workloads that process large data sets in memory; storage optimized instances suit high sequential read and write access to very large data sets on local storage; accelerated computing instances use co-processors for graphics or floating point work.',
          ['ec2-gp', 'ec2-co', 'ec2-mo', 'ec2-so', 'ec2-ac'],
          ['ec2-gp|These instances are ideal for applications that use these resources in equal proportions, such as web servers and code repositories.',
           'ec2-co|Compute optimized instances are designed for compute intensive applications that benefit from high performance processors.',
           'ec2-mo|Memory optimized instances are designed to deliver fast performance for workloads that process large data sets in memory.',
           'ec2-so|Storage optimized instances are designed for workloads that require high, sequential read and write access to very large data sets on local storage.',
           'ec2-ac|Accelerated computing instances use hardware accelerators, or co-processors, to perform functions, such as floating point number calculations, graphics processing, or data pattern matching, more efficiently than is possible in software running on CPUs.']),
        b('Instance types are named from their instance family and instance size, so the name tells you both the family and how large the instance is within it. Changing the type, within or across families, is a resize, and you start paying the rate of the new instance type.',
          ['ec2-type-names', 'ec2-resize'],
          ['ec2-type-names|Instance types are named based on their instance family and instance size.',
           'ec2-resize|When you change the instance type, you\'ll start paying the rate of the new instance type.']),
        b('Resizing is not free of effort. For an EBS-backed instance you must stop the instance before you can change its instance type, so plan for downtime while it is stopped. You can change the type only if the instance\'s configuration is compatible with the type you want; otherwise you launch a new instance and migrate. Processor architecture is one such limit: an instance on an Arm processor can only move to instance types that support Arm.',
          ['ec2-resize-ebs', 'ec2-resize-compat'],
          ['ec2-resize-ebs|Considerations You must stop your instance before you can change its instance type.',
           'ec2-resize-ebs|Ensure that you plan for downtime while your instance is stopped.',
           'ec2-resize-compat|You can change the instance type only if the instance\'s current configuration is compatible with the instance type that you want.',
           'ec2-resize-compat|Architecture AMIs are specific to the architecture of the processor, so you must select an instance type with the same processor architecture as the current instance type.',
           'ec2-resize-compat|For example: If the current instance type has a processor based on the Arm architecture, you are limited to the instance types that support a processor based on the Arm architecture, such as C6g and M6g.']),
        b('AWS Graviton is a family of processors that AWS designed to deliver the best price performance for workloads running in Amazon EC2, so choosing a Graviton-based (Arm) instance type is a cost lever. The caveat is the architecture limit above: an x86 workload has to be built for Arm, and an AMI is specific to its processor architecture.',
          ['graviton', 'ec2-resize-compat'],
          ['graviton|AWS Graviton is a family of processors designed to deliver the best price performance for your cloud workloads running in Amazon Elastic Compute Cloud (Amazon EC2).',
           'ec2-resize-compat|Architecture AMIs are specific to the architecture of the processor, so you must select an instance type with the same processor architecture as the current instance type.']),
        b('Virtualization on current instances comes from the Nitro System, a collection of hardware and software components built by AWS. Its lightweight Nitro hypervisor manages memory and CPU allocation, and the Nitro System also provides bare metal instances that eliminate virtualization overhead. Bare metal fits workloads that need low-level hardware features not available in virtualized environments, or a non-virtualized environment for licensing or support.',
          'ec2-nitro',
          ['The Nitro System is a collection of hardware and software components built by AWS that enable high performance, high availability, and high security.',
           'Nitro hypervisor - A lightweight hypervisor that manages memory and CPU allocation and delivers performance that is indistinguishable from bare metal for most workloads.',
           'The Nitro System provides bare metal capabilities that eliminate virtualization overhead and support workloads that require full access to host hardware.',
           'Applications that require a non-virtualized environment for licensing or support']),
        b('Burstable performance (T) instances give a baseline level of CPU performance with the ability to burst above it, governed by CPU credits. They suit workloads that are usually idle with occasional spikes. In unlimited mode an instance can sustain high CPU utilization for any period of time, and the hourly price covers the spikes when average CPU utilization over a rolling 24-hour period stays at or below the baseline; if the instance runs above that for a prolonged period it incurs an additional charge, so a workload that needs sustained high CPU may be cheaper on a non-burstable type.',
          ['ec2-instance-types', 'ec2-t-unlimited'],
          ['ec2-instance-types|Burstable performance (T) instances provide a baseline level of CPU performance with the ability to burst above the baseline.',
           'ec2-instance-types|The baseline utilization and ability to burst are governed by CPU credits.',
           'ec2-t-unlimited|A burstable performance instance configured as unlimited can sustain high CPU utilization for any period of time whenever required.',
           'ec2-t-unlimited|The hourly instance price automatically covers all CPU usage spikes if the average CPU utilization of the instance is at or below the baseline over a rolling 24-hour period or the instance lifetime, whichever is shorter.',
           'ec2-t-unlimited|If the average CPU usage over a 24-hour period exceeds the baseline, you incur charges for surplus credits.']),
      ],
      services: ['Amazon EC2'],
      design: [
        b('Cue: "needs a non-virtualized environment for licensing" → bare metal instance; "large in-memory data set" → memory optimized; "batch processing, transcoding" → compute optimized. Whichever family you pick, EC2 instance types are grouped by capability so the question\'s limiting resource names the family.',
          ['ec2-nitro', 'ec2-mo', 'ec2-co'],
          ['ec2-nitro|Applications that require a non-virtualized environment for licensing or support',
           'ec2-mo|Memory optimized instances are designed to deliver fast performance for workloads that process large data sets in memory.',
           'ec2-co|Compute optimized instances are designed for compute intensive applications that benefit from high performance processors.']),
      ],
    },
    {
      id: '4.2-S5',
      concepts: [
        b('Choose the family from the resource that limits the workload, then check cost. Select an instance type based on the requirements of the application or software that you plan to run. A web server and code repository that use compute, memory and networking in equal proportions fit general purpose; a memory-bound in-memory data set fits memory optimized; paying for compute optimized capacity when the workload is memory-bound wastes money, and the reverse starves the application.',
          ['ec2-instance-types', 'ec2-gp', 'ec2-mo'],
          ['ec2-instance-types|Select an instance type based on the requirements of the application or software that you plan to run on your instance.',
           'ec2-gp|These instances are ideal for applications that use these resources in equal proportions, such as web servers and code repositories.',
           'ec2-mo|Memory optimized instances are designed to deliver fast performance for workloads that process large data sets in memory.']),
        b('AWS Compute Optimizer analyses the configuration and utilisation metrics of your resources and gives rightsizing recommendations and identifies idle resources. It reports whether resources are optimal and generates recommendations to reduce the cost and improve the performance of your workloads. It supports EC2 instances, EC2 Auto Scaling groups, EBS volumes, Lambda functions, ECS services on Fargate, RDS and Aurora databases, and more.',
          'compute-optimizer',
          ['AWS Compute Optimizer is a service that analyzes your AWS resources\' configuration and utilization metrics to provide you with rightsizing recommendations and identify idle resources.',
           'It reports whether your resources are optimal, and generates optimization recommendations to reduce the cost and improve the performance of your workloads.',
           'Compute Optimizer generates recommendations for the following resources: Amazon Elastic Compute Cloud (Amazon EC2) instances Amazon EC2 Auto Scaling groups Amazon Elastic Block Store (Amazon EBS) volumes AWS Lambda functions Amazon Elastic Container Service (Amazon ECS) services on AWS Fargate']),
      ],
      services: ['Amazon EC2', 'AWS Compute Optimizer'],
      design: [
        b('Cue: "which instance family is best for the observed workload?" → Compute Optimizer recommendation; "the instance is underused" → move to a smaller or different family as Compute Optimizer suggests.',
          ['compute-optimizer', 'ec2-resize'],
          ['compute-optimizer|The analysis and visualization of your usage patterns can help you decide when to move or resize your running resources, stop or delete idle resources, and still meet your performance and capacity requirements.',
           'ec2-resize|If you want a recommendation for an instance type that is best able to handle your existing workload, you can use AWS Compute Optimizer.']),
      ],
    },
    {
      id: '4.2-S6',
      concepts: [
        b('Choose the size by measured use, not by guess. Compute Optimizer provides graphs showing recent utilisation history and projected utilisation for its recommendations, which you can use to evaluate which recommendation gives the best price-performance trade-off. It needs enough metric data before it can generate recommendations.',
          'compute-optimizer',
          ['Compute Optimizer also provides graphs showing recent utilization metric history data, as well as projected utilization for recommendations, which you can use to evaluate which recommendation provides the best price-performance trade-off.',
           'For Compute Optimizer to generate recommendations for these resources, they must meet a specific set of requirements, and must have accumulated sufficient metric data.']),
        b('Resizing an EC2 instance means changing its instance type, and which procedure applies depends on the root volume and on compatibility: an EBS-backed instance with a compatible configuration can have its type changed (after you stop it), while an instance store-backed instance, or one whose configuration is not compatible, must be migrated to a new instance type. You start paying the rate of the new type.',
          'ec2-resize',
          ['Root volume Compatibility Use these instructions EBS Compatible Change the instance type EBS Not compatible Migrate to a new instance type Instance store Not applicable Migrate to a new instance type',
           'When you change the instance type, you\'ll start paying the rate of the new instance type.']),
        b('Sizing is also a scaling decision: instead of one large instance, an Auto Scaling group of smaller instances can follow demand (Elastic Mint covers scaling methods), and Compute Optimizer also gives recommendations for Auto Scaling groups.',
          'compute-optimizer',
          ['Compute Optimizer generates recommendations for the following resources: Amazon Elastic Compute Cloud (Amazon EC2) instances Amazon EC2 Auto Scaling groups Amazon Elastic Block Store (Amazon EBS) volumes AWS Lambda functions Amazon Elastic Container Service (Amazon ECS) services on AWS Fargate']),
      ],
      services: ['Amazon EC2', 'AWS Compute Optimizer'],
      design: [
        b('Cue: "right-size based on utilisation with the least effort" → Compute Optimizer; "instance is oversized and costs too much" → resize to the recommended type; remember that the new type is billed at its own rate.',
          ['compute-optimizer', 'ec2-resize'],
          ['compute-optimizer|It reports whether your resources are optimal, and generates optimization recommendations to reduce the cost and improve the performance of your workloads.',
           'ec2-resize|When you change the instance type, you\'ll start paying the rate of the new instance type.']),
      ],
    },
  ],
  cues: [
    cue('find the most cost-effective instance type for the current utilisation', 'AWS Compute Optimizer',
      b('Compute Optimizer analyses configuration and utilisation to give rightsizing recommendations.', 'compute-optimizer',
        ['AWS Compute Optimizer is a service that analyzes your AWS resources\' configuration and utilization metrics to provide you with rightsizing recommendations and identify idle resources.'])),
    cue('batch processing or media transcoding needs fast processors', 'Compute optimized family',
      b('Compute optimized instances suit compute intensive work that benefits from high performance processors.', 'ec2-co',
        ['Compute optimized instances are designed for compute intensive applications that benefit from high performance processors.'])),
    cue('process a very large data set in memory', 'Memory optimized family',
      b('Memory optimized instances are designed for workloads that process large data sets in memory.', 'ec2-mo',
        ['Memory optimized instances are designed to deliver fast performance for workloads that process large data sets in memory.'])),
    cue('web servers and code repositories that use CPU and memory evenly', 'General purpose family',
      b('General purpose instances suit applications that use compute, memory and networking in equal proportions.', 'ec2-gp',
        ['These instances are ideal for applications that use these resources in equal proportions, such as web servers and code repositories.'])),
    cue('licence or support requires a non-virtualized environment', 'Bare metal instance',
      b('Bare metal suits applications that require a non-virtualized environment for licensing or support.', 'ec2-nitro',
        ['Applications that require a non-virtualized environment for licensing or support'])),
    cue('mostly idle workload with occasional CPU spikes', 'Burstable (T) instances',
      b('Burstable instances provide a baseline CPU level with the ability to burst, governed by CPU credits.', 'ec2-instance-types',
        ['Burstable performance (T) instances provide a baseline level of CPU performance with the ability to burst above the baseline.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Virtual Machines',
      aws: 'Amazon EC2 instance types',
      mapping: b('Learn describes virtual machines and servers as services where you pay only for what you use and can change sizes as needed, and says that AWS instance types and Azure VM sizes have similar categories.',
        ['learn-compute', 'ec2-instance-types'],
        ['learn-compute|You pay only for what you use and can change sizes as needed.',
         'learn-compute|AWS instance types and Azure VM sizes have similar categories, but the RAM, CPU, and storage capabilities differ.',
         'ec2-instance-types|Each instance type offers different compute, memory, and storage capabilities, and is grouped in an instance family based on these capabilities.']),
      breaks: b('Learn says AWS instance types and Azure VM sizes have similar categories, but the RAM, CPU and storage capabilities differ. On AWS, Compute Optimizer analyses your resources\' configuration and utilization metrics to provide rightsizing recommendations; Learn pairs it with Azure Advisor rather than with Azure Virtual Machines.',
        ['learn-compute', 'compute-optimizer'],
        ['learn-compute|AWS instance types and Azure VM sizes have similar categories, but the RAM, CPU, and storage capabilities differ.',
         'compute-optimizer|AWS Compute Optimizer is a service that analyzes your AWS resources\' configuration and utilization metrics to provide you with rightsizing recommendations and identify idle resources.']),
    },
    {
      concept: 'Azure Advisor (Cost category)',
      aws: 'AWS Compute Optimizer',
      mapping: b('The Learn compute comparison pairs AWS Compute Optimizer with the Cost category of Azure Advisor: both analyse usage metrics to recommend rightsizing for compute resources.',
        ['learn-compute', 'compute-optimizer'],
        ['learn-compute|Both services analyze usage metrics to recommend rightsizing for compute resources.',
         'compute-optimizer|AWS Compute Optimizer is a service that analyzes your AWS resources\' configuration and utilization metrics to provide you with rightsizing recommendations and identify idle resources.']),
      breaks: b('Learn describes Azure Advisor as providing reliability, security, cost, operational and performance recommendations across VMs, virtual machine scale sets and most Azure services. On AWS, Compute Optimizer reports whether resources are optimal and generates optimization recommendations, while AWS Trusted Advisor provides checks across cost optimization, security, performance, fault tolerance and service limits (Tide Gauges).',
        ['learn-compute', 'compute-optimizer'],
        ['learn-compute|Azure Advisor provides reliability, security, cost, operational, and performance recommendations across VMs, virtual machine scale sets, and most Azure services.',
         'learn-compute|AWS Trusted Advisor provides checks across cost optimization, security, performance, fault tolerance, and service limits.',
         'compute-optimizer|It reports whether your resources are optimal, and generates optimization recommendations to reduce the cost and improve the performance of your workloads.']),
    },
  ],
};

export default notes;
