import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'ledger-office',
  overview: [
    b('You cannot optimise what you cannot see. AWS gives you several kinds of cost visibility: tags that label spend ({{term:cost-allocation-tag|cost allocation tags}}), organisation-level billing ({{term:consolidated-billing}}), analysis tools (Cost Explorer), and alerts and detailed data (Budgets and the Cost and Usage Report). Requester Pays moves a data-transfer cost to the person downloading the data.',
      ['cost-alloc-tags', 'consolidated-billing', 'ce-what-is', 'budgets-managing'],
      ['cost-alloc-tags|You can use tags to organize your resources, and cost allocation tags to track your AWS costs on a detailed level.',
       'consolidated-billing|Every organization in AWS Organizations has a management account that pays the charges of all the member accounts.',
       'ce-what-is|AWS Cost Explorer is a tool that enables you to view and analyze your costs and usage.',
       'budgets-managing|You can use AWS Budgets to track and take action on your AWS costs and usage.']),
  ],
  bullets: [
    {
      id: '4.1-K1',
      concepts: [
        b('In general the bucket owner pays for all S3 storage and data transfer costs associated with a bucket. With a Requester Pays bucket, the requester instead of the bucket owner pays the cost of the request and the data download; the bucket owner always pays for storing the data.',
          'requester-pays',
          ['In general, bucket owners pay for all Amazon S3 storage and data transfer costs that are associated with their bucket.',
           'With Requester Pays buckets, the requester instead of the bucket owner pays the cost of the request and the data download from the bucket.',
           'The bucket owner always pays the cost of storing data.']),
        b('Use it when you want to share data without incurring the charges of others accessing it, such as large public datasets (reference data, geospatial information, web crawling data). Requests must be authenticated, so anonymous access to a Requester Pays bucket is not allowed; when a requester assumes an IAM role, the account the role belongs to is charged.',
          'requester-pays',
          ['Typically, you configure buckets to be Requester Pays buckets when you want to share data but not incur charges associated with others accessing the data.',
           'If you enable Requester Pays on a general purpose bucket, anonymous access to that bucket is not allowed.',
           'When the requester assumes an AWS Identity and Access Management (IAM) role before making their request, the account to which the role belongs is charged for the request.']),
      ],
      services: ['Amazon S3'],
      design: [
        b('Cue: "share a large dataset with other accounts but the owner should not pay for their downloads" → Requester Pays bucket; the requesters must be authenticated AWS identities.',
          'requester-pays',
          ['The request authentication enables Amazon S3 to identify and charge the requester for their use of the Requester Pays bucket.']),
      ],
    },
    {
      id: '4.1-K2',
      concepts: [
        b('A tag is a label, a key and a value, that you or AWS assigns to a resource. Cost allocation tags track costs at a detailed level: after you activate them, AWS uses them to organise resource costs on your cost allocation report. There are AWS-generated tags and user-defined tags, and you must activate both types separately before they appear in Cost Explorer or on a cost allocation report. Tags can take up to 24 hours to appear in the console, so activate them early.',
          'cost-alloc-tags',
          ['A tag is a label that you or AWS assigns to an AWS resource.',
           'After you activate cost allocation tags, AWS uses the cost allocation tags to organize your resource costs on your cost allocation report, to make it easier for you to categorize and track your AWS costs.',
           'AWS provides two types of cost allocation tags, an AWS-generated tags and user-defined tags.',
           'You must activate both types of tags separately before they can appear in Cost Explorer or on a cost allocation report.',
           'All tags can take up to 24 hours to appear in the Billing and Cost Management console.'],
          { allow: ['two', '24'] }),
        b('Consolidated billing in AWS Organizations: the management account pays the charges of all member accounts, you get one bill, can track charges across accounts, and can combine usage across the organisation, which shares volume pricing discounts, Reserved Instance discounts and Savings Plans. It costs nothing extra.',
          'consolidated-billing',
          ['One bill – You get one bill for multiple accounts in the same SOR.',
           'Combined usage – You can combine the usage across all accounts in the organization.',
           'This shares the volume pricing discounts, Reserved Instance discounts, and Savings Plans.',
           'No extra fee – Consolidated billing is offered at no additional cost.']),
        b('Cost allocation tags apply going forward once activated, but AWS lets the management account backfill them: it can request a backfill of cost allocation tags for up to twelve months, and the tag is then retroactively activated for those earlier months. Tag keys can take up to 24 hours to appear and to activate.',
          ['tags-backfill', 'cost-alloc-tags'],
          ['tags-backfill|Management account users can request a backfill of cost allocation tags for up to twelve months.',
           'tags-backfill|As a result, the Project tag is retroactively activated for the prior months from January to December 2023.',
           'cost-alloc-tags|All tags can take up to 24 hours to appear in the Billing and Cost Management console.'],
          { allow: ['twelve', '24'] }),
      ],
      services: ['AWS Organizations'],
      design: [
        b('Cue: "attribute costs to departments or projects" → tag resources and activate the tags as cost allocation tags; "one invoice and shared discounts across many accounts" → consolidated billing under an organisation.',
          ['cost-alloc-tags', 'consolidated-billing'],
          ['cost-alloc-tags|You can use tags to organize your resources, and cost allocation tags to track your AWS costs on a detailed level.',
           'consolidated-billing|This can result in a lower charge for your project, department, or company than with individual standalone accounts.']),
      ],
    },
    {
      id: '4.1-K3',
      concepts: [
        b('AWS Cost Explorer lets you view and analyse your costs and usage using the main graph, the cost and usage reports, or the RI reports, with filters, groupings and dates you can change.',
          'ce-what-is',
          ['AWS Cost Explorer is a tool that enables you to view and analyze your costs and usage.',
           'You can explore your usage and costs using the main graph, the Cost Explorer cost and usage reports, or the Cost Explorer RI reports.']),
        b('AWS Budgets tracks and takes action on your costs and usage: you set limits and receive alerts when costs approach or exceed a threshold, and can monitor utilisation and coverage of Reserved Instances or Savings Plans.',
          'budgets-managing',
          ['You can use AWS Budgets to track and take action on your AWS costs and usage.',
           'You can use AWS Budgets to monitor your aggregate utilization and coverage metrics for your Reserved Instances (RIs) or Savings Plans.']),
        b('The AWS Cost and Usage Report (CUR) contains the most comprehensive set of cost and usage data available. It publishes billing reports to an S3 bucket you own, broken down by the hour, day or month, by product or product resource, or by tags you define. AWS updates the report at least once a day until your charges are finalised. AWS Data Exports describes Cost and Usage Report 2.0 (CUR 2.0) as the new and recommended way to receive detailed cost and usage data.',
          ['cur-what-is', 'cur-create', 'data-exports-what-is'],
          ['cur-what-is|AWS Cost and Usage Reports (AWS CUR) contains the most comprehensive set of cost and usage data available.',
           'cur-what-is|You can use Cost and Usage Reports to publish your AWS billing reports to an Amazon Simple Storage Service (Amazon S3) bucket that you own.',
           'cur-what-is|You can receive reports that break down your costs by the hour, day, or month, by product or product resource, or by tags that you define yourself.',
           'cur-create|After delivery starts, AWS updates the AWS Cost and Usage Reports files at least once a day.',
           'data-exports-what-is|Cost and Usage Report 2.0 (CUR 2.0) is the new and recommended way to receive your detailed AWS cost and usage data.']),
      ],
      services: ['AWS Cost Explorer', 'AWS Budgets', 'AWS Cost and Usage Report'],
      design: [
        b('Cue: "visualise and explore spending trends" → Cost Explorer; "alert me when spending crosses a limit" → Budgets; "line-item data for custom analysis (for example with Athena)" → Cost and Usage Report.',
          ['ce-what-is', 'budgets-managing', 'cur-what-is'],
          ['ce-what-is|AWS Cost Explorer is a tool that enables you to view and analyze your costs and usage.',
           'budgets-managing|Set spending limits for services and receive alerts when costs approach or exceed your defined threshold.',
           'cur-what-is|AWS Cost and Usage Reports (AWS CUR) contains the most comprehensive set of cost and usage data available.']),
      ],
    },
  ],
  cues: [
    cue('the data consumers, not the bucket owner, should pay for downloads', 'S3 Requester Pays bucket',
      b('With Requester Pays, the requester pays the request and download costs.', 'requester-pays',
        ['With Requester Pays buckets, the requester instead of the bucket owner pays the cost of the request and the data download from the bucket.'])),
    cue('allocate costs by project or department', 'Cost allocation tags (activated)',
      b('Cost allocation tags organise resource costs on the cost allocation report.', 'cost-alloc-tags',
        ['After you activate cost allocation tags, AWS uses the cost allocation tags to organize your resource costs on your cost allocation report, to make it easier for you to categorize and track your AWS costs.'])),
    cue('single bill and shared volume discounts across accounts', 'Consolidated billing (AWS Organizations)',
      b('Consolidated billing gives one bill and combined usage across accounts at no extra fee.', 'consolidated-billing',
        ['No extra fee – Consolidated billing is offered at no additional cost.'])),
    cue('analyse and visualise cost and usage over time', 'AWS Cost Explorer',
      b('Cost Explorer views and analyses costs and usage.', 'ce-what-is',
        ['AWS Cost Explorer is a tool that enables you to view and analyze your costs and usage.'])),
    cue('alert when actual or forecast spending exceeds a threshold', 'AWS Budgets',
      b('Budgets alerts when costs approach or exceed your threshold.', 'budgets-managing',
        ['Set spending limits for services and receive alerts when costs approach or exceed your defined threshold.'])),
    cue('most detailed billing data delivered to S3 for analysis', 'AWS Cost and Usage Report',
      b('CUR is the most comprehensive set of cost and usage data and is published to your S3 bucket.', 'cur-what-is',
        ['You can use Cost and Usage Reports to publish your AWS billing reports to an Amazon Simple Storage Service (Amazon S3) bucket that you own.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Microsoft Cost Management',
      aws: 'AWS Billing and Cost Management (Cost Explorer, Budgets)',
      mapping: b('Learn pairs AWS Billing and Cost Management with Microsoft Cost Management, which helps you understand your Azure bill, manage your billing account and subscriptions, monitor and control spending, and optimise resource use.',
        ['learn-hub', 'ce-what-is'],
        ['learn-hub|AWS Billing and Cost Management Microsoft Cost Management Cost Management helps you understand your Azure invoice or bill.',
         'learn-hub|It also helps you manage your billing account and subscriptions, monitor and control Azure spending, and optimize resource use.',
         'ce-what-is|AWS Cost Explorer is a tool that enables you to view and analyze your costs and usage.']),
      breaks: b('On AWS the job is split across separate tools: Cost Explorer to view and analyse costs and usage, Budgets to track and take action on them, and the Cost and Usage Report for the most comprehensive data set. Learn pairs the billing service as a whole with Microsoft Cost Management.',
        ['budgets-managing', 'cur-what-is', 'learn-hub'],
        ['budgets-managing|You can use AWS Budgets to track and take action on your AWS costs and usage.',
         'cur-what-is|AWS Cost and Usage Reports (AWS CUR) contains the most comprehensive set of cost and usage data available.',
         'learn-hub|AWS Billing and Cost Management Microsoft Cost Management Cost Management helps you understand your Azure invoice or bill.']),
    },
    {
      concept: 'Cost details APIs / Cost Management + Billing',
      aws: 'AWS Cost and Usage Reports',
      mapping: b('Learn pairs Cost and Usage Reports with the cost details APIs and Cost Management + Billing: services that generate, monitor, forecast and share billing data by time, organisation or product resource.',
        ['learn-hub', 'cur-what-is'],
        ['learn-hub|Cost and Usage Reports Cost details APIs Cost Management + Billing These services help you generate, monitor, forecast, and share billing data for resource usage by time, organization, or product resources.',
         'cur-what-is|You can receive reports that break down your costs by the hour, day, or month, by product or product resource, or by tags that you define yourself.']),
      breaks: b('Learn pairs Cost and Usage Reports with Azure\'s cost details APIs and Cost Management + Billing. On AWS, Cost and Usage Reports publish AWS billing reports to an S3 bucket you own.',
        ['cur-what-is', 'learn-hub'],
        ['cur-what-is|You can use Cost and Usage Reports to publish your AWS billing reports to an Amazon Simple Storage Service (Amazon S3) bucket that you own.',
         'learn-hub|Cost and Usage Reports Cost details APIs Cost Management + Billing These services help you generate, monitor, forecast, and share billing data for resource usage by time, organization, or product resources.']),
    },
    {
      concept: 'Resource Manager resource groups and tags',
      aws: 'Cost allocation tags',
      mapping: b('Learn pairs Resource Groups and Tag Editor with Azure Resource Manager resource groups and tags: a resource group is a container that holds related resources for an Azure solution, and you apply tags to organise resources by categories.',
        ['learn-hub', 'cost-alloc-tags'],
        ['learn-hub|A resource group is a container that holds related resources for an Azure solution.',
         'learn-hub|Apply tags to your Azure resources to logically organize them by categories.',
         'cost-alloc-tags|A tag is a label that you or AWS assigns to an AWS resource.']),
      breaks: b('An Azure resource group is a container of resources; an AWS tag is only a key-value label on a resource, and for billing it must be activated as a cost allocation tag before it appears in Cost Explorer or on the cost allocation report.',
        ['cost-alloc-tags', 'learn-hub'],
        ['cost-alloc-tags|You must activate both types of tags separately before they can appear in Cost Explorer or on a cost allocation report.',
         'learn-hub|A resource group is a container that holds related resources for an Azure solution.']),
    },
  ],
};

export default notes;
