import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'nat-toll',
  overview: [
    b('A NAT gateway lets instances in a private subnet reach services outside the VPC while outside services cannot start a connection to them. It is a common hidden cost: you are charged for each hour the NAT gateway is available and each gigabyte of data it processes. The choices that move the bill are NAT gateway or NAT instance, how many NAT gateways you run and where, and how much traffic you send through them. Gatehouse (Citadel) explained what a NAT gateway is; this building is about its cost.',
      ['vpc-nat-gateway', 'vpc-nat-pricing'],
      ['vpc-nat-gateway|You can use a NAT gateway so that instances in a private subnet can connect to services outside your VPC but external services can\'t initiate a connection with those instances.',
       'vpc-nat-pricing|When you provision a NAT gateway, you are charged for each hour that your NAT gateway is available and each gigabyte of data that it processes.']),
  ],
  bullets: [
    {
      id: '4.4-K4',
      concepts: [
        b('A NAT gateway is managed by AWS, so you do not perform maintenance, while a NAT instance is an EC2 instance you manage by installing software updates or operating system patches. AWS recommends NAT gateways because they provide better availability and bandwidth and require less effort to administer.',
          'vpc-nat-comparison',
          ['We recommend that you use NAT gateways because they provide better availability and bandwidth and require less effort on your part to administer.',
           'Managed by AWS. You do not need to perform any maintenance.',
           'Managed by you, for example, by installing software updates or operating system patches on the instance.']),
        b('The bills are built differently. A NAT gateway is charged depending on the number of gateways, the duration of usage and the amount of data sent through them, and you do not choose a type or size. A NAT instance is charged depending on the number of instances, the duration of usage and the instance type and size, which you choose for your predicted workload. Cost per gigabyte processed therefore matters for a gateway, and right-sizing the instance matters for an instance.',
          'vpc-nat-comparison',
          ['Charged depending on the number of NAT gateways you use, duration of usage, and amount of data that you send through the NAT gateways.',
           'Charged depending on the number of NAT instances that you use, duration of usage, and instance type and size.',
           'Choose a suitable instance type and size, according to your predicted workload.']),
        b('The comparison also lists differences that a cost question may turn on: a NAT instance can be used as a bastion server and supports port forwarding by manual configuration, while a NAT gateway does not support either, and you cannot associate security groups with a NAT gateway. The full comparison is in the Don\'t confuse section below.',
          'vpc-nat-comparison',
          ['Bastion servers Not supported.',
           'Use as a bastion server.',
           'You cannot associate security groups with NAT gateways.']),
        b('To reduce what a NAT gateway charges for data, AWS suggests: keep resources that send or receive a lot of traffic in the same Availability Zone as the NAT gateway, or create a NAT gateway in each Availability Zone with resources; and, if most traffic through the gateway is to AWS services that support interface endpoints or gateway endpoints, create an endpoint for those services instead.',
          'vpc-nat-pricing',
          ['If your AWS resources send or receive a significant volume of traffic across Availability Zones, ensure that the resources are in the same Availability Zone as the NAT gateway.',
           'Alternatively, create a NAT gateway in each Availability Zone with resources.',
           'If most traffic through your NAT gateway is to AWS services that support interface endpoints or gateway endpoints, consider creating an interface endpoint or gateway endpoint for these services.']),
      ],
      services: ['Amazon VPC', 'Amazon EC2'],
      design: [
        b('Cue: "private instances need outbound internet, least administration" → NAT gateway; "most of the NAT traffic goes to S3 or DynamoDB" → add a gateway endpoint so that traffic bypasses the NAT gateway; "need a bastion or port forwarding on the NAT device" → NAT instance.',
          ['vpc-nat-comparison', 'vpc-nat-pricing'],
          ['vpc-nat-comparison|We recommend that you use NAT gateways because they provide better availability and bandwidth and require less effort on your part to administer.',
           'vpc-nat-pricing|If most traffic through your NAT gateway is to AWS services that support interface endpoints or gateway endpoints, consider creating an interface endpoint or gateway endpoint for these services.']),
      ],
    },
    {
      id: '4.4-S1',
      concepts: [
        b('Public or private is the first choice. You use a public NAT gateway so that instances in a private subnet can send outbound traffic to the internet while the internet cannot start connections to them. You use a private NAT gateway to reach your on-premises network with a pool of allow-listed addresses, or to communicate between networks that have overlapping CIDR ranges.',
          'vpc-nat-scenarios',
          ['You can use a public NAT gateway to enable instances in a private subnet to send outbound traffic to the internet, while preventing the internet from establishing connections to the instances.',
           'You can use a private NAT gateway to enable communication from your VPCs to your on-premises network using a pool of allow-listed addresses.',
           'You can use a private NAT gateway to enable communication between networks even if they have overlapping CIDR ranges.']),
        b('One shared NAT gateway or one per Availability Zone? Each NAT gateway is created in one Availability Zone with redundancy in that zone. A single shared gateway has the lowest hourly cost, but if resources in several zones share it and its zone goes down, resources in the other zones lose internet access, and traffic from other zones crosses Availability Zones to reach it, which AWS lists as a data transfer cost. A gateway per zone with matching routing costs more in hourly charges, but is zone-independent and keeps traffic in its zone.',
          ['vpc-nat-basics', 'vpc-nat-comparison', 'vpc-nat-pricing'],
          ['vpc-nat-basics|If you have resources in multiple Availability Zones and they share one NAT gateway, and if the NAT gateway\'s Availability Zone is down, resources in the other Availability Zones lose internet access.',
           'vpc-nat-comparison|Create a NAT gateway in each Availability Zone to ensure zone-independent architecture.',
           'vpc-nat-pricing|If your AWS resources send or receive a significant volume of traffic across Availability Zones, ensure that the resources are in the same Availability Zone as the NAT gateway.']),
        b('A regional NAT gateway is the third pattern. It automatically expands across Availability Zones based on your workload presence, where standard (zonal) NAT gateways operate in a single Availability Zone, and AWS recommends considering it for all use cases except those that require private connectivity. A regional NAT gateway does not offer private connectivity, so use the zonal mode for private NAT use cases. AWS does not state in these pages how a regional gateway compares in price; its pricing is on the VPC pricing page, so compare before choosing.',
          'vpc-nat-regional',
          ['A regional NAT gateway automatically expands across Availability Zones based on your workload presence.',
           'Unlike standard NAT gateways (referred to as zonal NAT gateways), which operate in a single Availability Zone, regional NAT gateways follow your workloads to provide automatic high availability.',
           'Consider using Regional NAT Gateways for all use cases except those that require private connectivity.',
           'Regional NAT Gateways do not offer private connectivity and we recommend using your NAT Gateways in zonal availability mode for private NAT use cases.',
           'For pricing information, see Amazon VPC Pricing.']),
      ],
      services: ['Amazon VPC'],
      design: [
        b('Cue: "lowest cost, development environment, accepts zone dependency" → one shared NAT gateway; "production, avoid cross-zone data charges and a single point of failure" → a NAT gateway in each Availability Zone, with each subnet routed to its own zone\'s gateway; "simplify and keep high availability without managing per-zone gateways" → regional NAT gateway. This is study guidance: the wording of the question decides.',
          ['vpc-nat-basics', 'vpc-nat-comparison', 'vpc-nat-regional'],
          ['vpc-nat-basics|If you have resources in multiple Availability Zones and they share one NAT gateway, and if the NAT gateway\'s Availability Zone is down, resources in the other Availability Zones lose internet access.',
           'vpc-nat-comparison|Create a NAT gateway in each Availability Zone to ensure zone-independent architecture.',
           'vpc-nat-regional|A regional NAT gateway automatically expands across Availability Zones based on your workload presence.']),
      ],
    },
  ],
  cues: [
    cue('private subnet needs outbound internet with the least administration', 'NAT gateway',
      b('AWS recommends NAT gateways for better availability and bandwidth with less administration.', 'vpc-nat-comparison',
        ['We recommend that you use NAT gateways because they provide better availability and bandwidth and require less effort on your part to administer.'])),
    cue('NAT charges are high and most traffic goes to S3 or DynamoDB', 'Gateway endpoint (and interface endpoints) instead of NAT',
      b('If most NAT traffic is to services that support endpoints, consider creating an endpoint.', 'vpc-nat-pricing',
        ['If most traffic through your NAT gateway is to AWS services that support interface endpoints or gateway endpoints, consider creating an interface endpoint or gateway endpoint for these services.'])),
    cue('NAT data transfer charges across Availability Zones', 'Same-zone NAT gateway per Availability Zone with resources',
      b('Keep resources in the same Availability Zone as the NAT gateway or create one in each zone with resources.', 'vpc-nat-pricing',
        ['Alternatively, create a NAT gateway in each Availability Zone with resources.'])),
    cue('NAT must survive an Availability Zone failure', 'A NAT gateway in each Availability Zone (or a regional NAT gateway)',
      b('Create a NAT gateway in each Availability Zone to ensure zone-independent architecture.', 'vpc-nat-comparison',
        ['Create a NAT gateway in each Availability Zone to ensure zone-independent architecture.'])),
    cue('overlapping CIDR ranges or allow-listed addresses to on-premises', 'Private NAT gateway',
      b('A private NAT gateway enables communication between networks even if they have overlapping CIDR ranges.', 'vpc-nat-scenarios',
        ['You can use a private NAT gateway to enable communication between networks even if they have overlapping CIDR ranges.'])),
    cue('NAT device also needed as a bastion or for port forwarding', 'NAT instance',
      b('A NAT instance can be used as a bastion server; a NAT gateway does not support bastion servers.', 'vpc-nat-comparison',
        ['Use as a bastion server.'])),
  ],
  examples: [],
  confuse: ['nat-gateway-vs-instance'],
  azure: [
    {
      concept: 'Azure NAT Gateway',
      aws: 'AWS NAT gateways',
      mapping: b('Learn pairs AWS NAT gateways with Azure NAT Gateway: these services simplify outbound-only Internet connectivity for virtual networks.',
        ['learn-networking', 'vpc-nat-gateway'],
        ['learn-networking|These services simplify outbound-only Internet connectivity for virtual networks.',
         'vpc-nat-gateway|You can use a NAT gateway so that instances in a private subnet can connect to services outside your VPC but external services can\'t initiate a connection with those instances.']),
      breaks: b('Learn adds that Azure NAT gateways can have multiple public IPs, and also makes a statement about how many IP addresses an AWS NAT gateway can use. The AWS NAT gateway basics page says you can associate up to 8 IPv4 addresses with a NAT gateway (1 primary and 7 secondary), so the sources disagree and this is recorded as a contradiction; trust the AWS page for AWS behaviour. The exam cost points are also AWS-specific: the hourly plus per-gigabyte billing, one gateway per Availability Zone, and replacing NAT traffic with endpoints.',
        ['learn-networking', 'vpc-nat-basics', 'vpc-nat-pricing'],
        ['learn-networking|Azure NAT gateways can have multiple public IPs.',
         'vpc-nat-basics|You can increase this limit by associating up to 8 IPv4 addresses to your NAT gateways (1 primary IPv4 address and 7 secondary IPv4 addresses).',
         'vpc-nat-pricing|When you provision a NAT gateway, you are charged for each hour that your NAT gateway is available and each gigabyte of data that it processes.'],
        { allow: ['8', '1', '7'] }),
    },
  ],
};

export default notes;
