import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'network-cost-audit',
  overview: [
    b('Network charges are easy to miss because they hide inside many services: data moving between Availability Zones or Regions, NAT gateways, load balancers, endpoints and idle public addresses. The audit building is about finding them in an existing workload. Cost Explorer can filter by Region, Availability Zone, service and usage type, tags attribute spend to a team, and Trusted Advisor flags idle or unused network resources. The fixes themselves are in NAT Toll, Transit Tariff and Route Tariff.',
      ['ce-filtering', 'cost-alloc-tags', 'trusted-advisor-cost-checks'],
      ['ce-filtering|You can use Cost Explorer to see which service you use the most, which Availability Zone (AZ) most of your traffic is in, and which member account uses AWS the most.',
       'cost-alloc-tags|You can use tags to organize your resources, and cost allocation tags to track your AWS costs on a detailed level.',
       'trusted-advisor-cost-checks|Idle NAT gateways']),
  ],
  bullets: [
    {
      id: '4.4-K1',
      concepts: [
        b('Cost allocation tags let you attribute network costs, such as a NAT gateway or a load balancer, to the team or application that uses it. A tag is a label that you or AWS assigns to a resource, and you must activate it as a cost allocation tag before it appears in Cost Explorer or on a cost allocation report.',
          'cost-alloc-tags',
          ['A tag is a label that you or AWS assigns to an AWS resource.',
           'You must activate both types of tags separately before they can appear in Cost Explorer or on a cost allocation report.']),
        b('Multi-account billing shows network cost across an organisation. With consolidated billing the management account pays the charges of all member accounts, you can track charges across accounts, and in Cost Explorer you can use the Linked Account and Service filters to identify the member account that spent the most on a service.',
          ['consolidated-billing', 'ce-filtering'],
          ['consolidated-billing|Every organization in AWS Organizations has a management account that pays the charges of all the member accounts.',
           'ce-filtering|For example, you can use the Linked Account and Services filters to identify the member account that spent the most money on Amazon EC2.']),
      ],
      services: ['AWS Organizations'],
      design: [
        b('Cue: "which team is responsible for the NAT or load balancer cost?" → cost allocation tags; "which account spends most?" → Cost Explorer grouped by linked account.',
          ['cost-alloc-tags', 'ce-filtering'],
          ['cost-alloc-tags|After you activate cost allocation tags, AWS uses the cost allocation tags to organize your resource costs on your cost allocation report, to make it easier for you to categorize and track your AWS costs.',
           'ce-filtering|For example, you can use the Linked Account and Services filters to identify the member account that spent the most money on Amazon EC2.']),
      ],
    },
    {
      id: '4.4-K2',
      concepts: [
        b('Cost Explorer filters costs by values that include Availability Zone, Region, Service, Tag, Usage type and Usage type group, and you can refine the analysis with multiple filters and by grouping the data. That is how you find which Region or Availability Zone most of the traffic and cost is in.',
          'ce-filtering',
          ['With Cost Explorer, you can filter how you view your AWS costs by one or more of the following values: API operation Availability Zone (AZ) Billing entity Charge type Include all Instance type Legal entity Linked account Platform Product attribute Purchase option Region Resources Service Tag Tenancy Usage type Usage type group',
           'You can continue refining your cost analysis by using multiple filters, grouping your data by filter type, and choosing Advanced Options tab options.']),
        b('Cost Explorer tells you where the money goes, not which flows cause it. To find which traffic uses a NAT gateway or crosses zones, look at the traffic itself: VPC Flow Logs capture information about the IP traffic going to and from network interfaces, and NAT gateway metrics in CloudWatch, such as bytes sent out to the destination, show how much traffic passes through each gateway. AWS Cost Anomaly Detection uses machine learning models to detect and alert on anomalous spend patterns.',
          ['vpc-flow-logs', 'vpc-nat-metrics', 'cost-anomaly', 'ce-filtering'],
          ['vpc-flow-logs|VPC Flow Logs is a feature that enables you to capture information about the IP traffic going to and from network interfaces in your VPC.',
           'vpc-nat-metrics|BytesOutToDestination The number of bytes sent out through the NAT gateway to the destination.',
           'cost-anomaly|AWS Cost Anomaly Detection is a feature that uses machine learning models to detect and alert on anomalous spend patterns in your deployed AWS services.',
           'ce-filtering|You can use Cost Explorer to see which service you use the most, which Availability Zone (AZ) most of your traffic is in, and which member account uses AWS the most.']),
        b('AWS Budgets sets spending limits and alerts when costs approach or exceed a threshold, so an unexpected jump in network spend is caught early. The Cost and Usage Report is the most comprehensive set of cost and usage data available, published to an S3 bucket you own and broken down by product or product resource, so it holds the line items behind a transfer charge.',
          ['budgets-managing', 'cur-what-is'],
          ['budgets-managing|Set spending limits for services and receive alerts when costs approach or exceed your defined threshold.',
           'cur-what-is|AWS Cost and Usage Reports (AWS CUR) contains the most comprehensive set of cost and usage data available.',
           'cur-what-is|You can receive reports that break down your costs by the hour, day, or month, by product or product resource, or by tags that you define yourself.']),
      ],
      services: ['AWS Cost Explorer', 'AWS Budgets', 'AWS Cost and Usage Report'],
      design: [
        b('Cue: "see which Region or Availability Zone drives the cost" → Cost Explorer filters; "alert when network spend passes a limit" → Budgets; "line-item detail to query" → Cost and Usage Report.',
          ['ce-filtering', 'budgets-managing', 'cur-what-is'],
          ['ce-filtering|You can use Cost Explorer to see which service you use the most, which Availability Zone (AZ) most of your traffic is in, and which member account uses AWS the most.',
           'budgets-managing|Set spending limits for services and receive alerts when costs approach or exceed your defined threshold.',
           'cur-what-is|AWS Cost and Usage Reports (AWS CUR) contains the most comprehensive set of cost and usage data available.']),
      ],
    },
    {
      id: '4.4-S5',
      concepts: [
        b('Trusted Advisor inspects your AWS environment and recommends where to save money. Its cost optimization checks include idle NAT gateways, idle load balancers, inactive VPC interface endpoints and unassociated Elastic IP addresses, each a network resource that you pay for whether or not traffic uses it.',
          ['trusted-advisor', 'trusted-advisor-cost-checks'],
          ['trusted-advisor|Trusted Advisor inspects your AWS environment, and then makes recommendations when opportunities exist to save money, improve system availability and performance, or help close security gaps.',
           'trusted-advisor-cost-checks|Idle Load Balancers',
           'trusted-advisor-cost-checks|Idle NAT gateways',
           'trusted-advisor-cost-checks|Inactive VPC interface endpoints',
           'trusted-advisor-cost-checks|Unassociated Elastic IP Addresses']),
        b('Idle addresses are not the only address cost. Any public IPv4 address associated with a resource in a VPC is charged as an in-use public IPv4 address, and a public IPv4 address in your account that is not used on a resource is charged as an idle address, at the same hourly rate. So Trusted Advisor flagging unassociated Elastic IP addresses finds only part of the public IPv4 cost.',
          'vpc-pricing',
          ['Any public IPv4 address associated with a resource launched in an Amazon VPC, and public IPv4 addresses assigned to AWS Global Accelerator and AWS Site-to-Site VPN tunnel endpoints are charged as in-use public IPv4 address.',
           'Any public IPv4 address associated to your AWS account that is not used on a resource is charged as idle public IPv4 address.',
           'You pay an hourly rate for each public IPv4 address used by your AWS account.',
           'The price is the same whether the public IPv4 address is in-use public IPv4 addresses that is associated with an AWS resource you own, or an idle public IPv4 addresses in your AWS account not associated with any AWS resources.']),
        b('Which checks you can use depends on the support plan. With the Basic Support plan you can access all checks in the Service Limits category and selected checks in the Security and Fault tolerance categories, which does not include the cost optimization category; with Business Support+, Enterprise Support or Unified Operations you can access all Trusted Advisor checks. The same page announces that Developer Support and Business Support will be discontinued on 1 January 2027, with Business Support+ as the upgrade, so support plan names in older material may differ.',
          'trusted-advisor',
          ['If you have a Basic Support plan, you can use the Trusted Advisor console to access all checks in the Service Limits category and selected checks in the Security and Fault tolerance categories.',
           'If you have a AWS Business Support+, AWS Enterprise Support, or AWS Unified Operations plan, you can use the Trusted Advisor console and the AWS Trusted Advisor API to access all Trusted Advisor checks.',
           'End of Support Notice: Developer Support will be discontinued January 1, 2027.',
           'End of Support Notice: Business Support will be discontinued January 1, 2027.'],
          { status: 'deprecated', allow: ['1', '2027'] }),
        b('Compute Optimizer is another review tool. It generates recommendations for resources that include Amazon NAT Gateway, alongside EC2 instances, Auto Scaling groups, EBS volumes and Lambda functions, once they have accumulated sufficient metric data.',
          'compute-optimizer',
          ['Compute Optimizer generates recommendations for the following resources: Amazon Elastic Compute Cloud (Amazon EC2) instances Amazon EC2 Auto Scaling groups Amazon Elastic Block Store (Amazon EBS) volumes AWS Lambda functions Amazon Elastic Container Service (Amazon ECS) services on AWS Fargate Commercial software licenses Amazon Aurora and Amazon Relational Database Service (Amazon RDS) databases Amazon NAT Gateway',
           'For Compute Optimizer to generate recommendations for these resources, they must meet a specific set of requirements, and must have accumulated sufficient metric data.']),
      ],
      services: ['AWS Trusted Advisor', 'AWS Cost Explorer'],
      design: [
        b('Cue: "review an existing workload for wasted network spend" → Trusted Advisor cost checks (idle NAT gateways, idle load balancers, unused endpoints and addresses) plus Cost Explorer by Region and Availability Zone; "unused Elastic IP addresses" → Trusted Advisor flags unassociated ones, but in-use public IPv4 addresses are billed too; "which flows use the NAT gateway" → VPC Flow Logs and NAT gateway CloudWatch metrics. Questions or older material may still say Business Support or Enterprise Support for the plan that unlocks all checks.',
          ['trusted-advisor-cost-checks', 'ce-filtering'],
          ['trusted-advisor-cost-checks|Unassociated Elastic IP Addresses',
           'trusted-advisor-cost-checks|Idle Load Balancers',
           'ce-filtering|You can use Cost Explorer to see which service you use the most, which Availability Zone (AZ) most of your traffic is in, and which member account uses AWS the most.']),
      ],
    },
  ],
  cues: [
    cue('find which Availability Zone or Region carries the traffic and cost', 'Cost Explorer filters (Availability Zone, Region, Usage type)',
      b('Cost Explorer can show which Availability Zone most of your traffic is in.', 'ce-filtering',
        ['You can use Cost Explorer to see which service you use the most, which Availability Zone (AZ) most of your traffic is in, and which member account uses AWS the most.'])),
    cue('NAT gateways or load balancers that carry little or no traffic', 'Trusted Advisor idle-resource checks',
      b('Trusted Advisor cost optimization checks include Idle NAT gateways and Idle Load Balancers.', 'trusted-advisor-cost-checks',
        ['Idle NAT gateways', 'Idle Load Balancers'])),
    cue('Elastic IP addresses not attached to anything', 'Trusted Advisor: Unassociated Elastic IP Addresses',
      b('Trusted Advisor has a check for unassociated Elastic IP addresses.', 'trusted-advisor-cost-checks',
        ['Unassociated Elastic IP Addresses'])),
    cue('interface endpoints that nobody uses', 'Trusted Advisor: Inactive VPC interface endpoints',
      b('Trusted Advisor has a check for inactive VPC interface endpoints.', 'trusted-advisor-cost-checks',
        ['Inactive VPC interface endpoints'])),
    cue('charge network costs back to a team', 'Cost allocation tags',
      b('Cost allocation tags organise resource costs on your cost allocation report.', 'cost-alloc-tags',
        ['After you activate cost allocation tags, AWS uses the cost allocation tags to organize your resource costs on your cost allocation report, to make it easier for you to categorize and track your AWS costs.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Microsoft Cost Management',
      aws: 'AWS Billing and Cost Management (Cost Explorer, Budgets)',
      mapping: b('Learn pairs AWS Billing and Cost Management with Microsoft Cost Management, which helps you understand your Azure invoice or bill and monitor and control Azure spending. On AWS, Cost Explorer adds filters such as Availability Zone and Region for network analysis.',
        ['learn-hub', 'ce-filtering'],
        ['learn-hub|It also helps you manage your billing account and subscriptions, monitor and control Azure spending, and optimize resource use.',
         'ce-filtering|You can use Cost Explorer to see which service you use the most, which Availability Zone (AZ) most of your traffic is in, and which member account uses AWS the most.']),
      breaks: b('The Learn pairing is at the level of the billing service as a whole. The exam asks which AWS tool answers a specific question, such as which Availability Zone carries the traffic (Cost Explorer filters) or which network resources are idle (Trusted Advisor checks).',
        ['trusted-advisor-cost-checks', 'learn-hub'],
        ['trusted-advisor-cost-checks|Idle NAT gateways',
         'learn-hub|AWS Billing and Cost Management Microsoft Cost Management Cost Management helps you understand your Azure invoice or bill.']),
    },
    {
      concept: 'Azure Advisor',
      aws: 'AWS Trusted Advisor',
      mapping: b('Learn pairs AWS Trusted Advisor with Azure Advisor: Trusted Advisor provides checks across cost optimization, security, performance, fault tolerance and service limits.',
        ['learn-compute', 'trusted-advisor'],
        ['learn-compute|AWS Trusted Advisor provides checks across cost optimization, security, performance, fault tolerance, and service limits.',
         'trusted-advisor|Trusted Advisor inspects your AWS environment, and then makes recommendations when opportunities exist to save money, improve system availability and performance, or help close security gaps.']),
      breaks: b('Which Trusted Advisor checks you can use depends on the AWS support plan: with the Basic Support plan you can access all checks in the Service Limits category and selected checks in the Security and Fault tolerance categories, and the full set needs a higher plan. The Learn row does not mention this plan dependency.',
        ['trusted-advisor', 'learn-compute'],
        ['trusted-advisor|If you have a Basic Support plan, you can use the Trusted Advisor console to access all checks in the Service Limits category and selected checks in the Security and Fault tolerance categories.',
         'learn-compute|AWS Trusted Advisor provides checks across cost optimization, security, performance, fault tolerance, and service limits.']),
    },
  ],
};

export default notes;
