import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'retention-records',
  overview: [
    b('Every database backup is billed as storage until it expires. A retention policy decides how long each backup is kept, and snapshot frequency decides how many backups exist and how much data you can lose. Keeping everything forever is the expensive default; keeping too little breaks recovery or compliance rules. For databases the controls are the RDS backup retention period, manual snapshots, and AWS Backup plans.',
      ['rds-automated-backups', 'rds-backup-retention', 'backup-plans'],
      ['rds-automated-backups|RDS saves the automated backups of your DB instance according to the backup retention period that you specify.',
       'rds-backup-retention|You can set the backup retention period of a DB instance to between 0 and 35 days.',
       'backup-plans|AWS Backup also seamlessly manages your backup plan\'s lifecycle based on your retention settings, which allows you to restore when needed.']),
  ],
  bullets: [
    {
      id: '4.3-K4',
      concepts: [
        b('A data retention policy states how long data and its backups must be kept, and when they may be deleted. For RDS the retention period applies to automated backups: you set it when you create or restore a DB instance, and the console default is seven days while the API and CLI default is one day if you do not set it. The documented range is between 0 and 35 days (a limit that can change), and setting it to 0 disables automated backups.',
          'rds-backup-retention',
          ['You can set the backup retention period when you create or restore a DB instance or Multi-AZ DB cluster.',
           'If you create a DB instance using the Amazon RDS API or the AWS CLI and if you don\'t set the backup retention period, the default backup retention period is one day.',
           'If you create a DB instance using the console, the default backup retention period is seven days.',
           'You can set the backup retention period of a DB instance to between 0 and 35 days.',
           'Setting the backup retention period to 0 disables automated backups.']),
        b('Manual DB snapshots follow a different rule: unlike automated backups, manual snapshots are not subject to the backup retention period. They remain until you delete them, and they count toward the Region\'s backup storage, so old manual snapshots are a common source of cost.',
          ['rds-snapshot-create', 'rds-automated-backups'],
          ['rds-snapshot-create|Unlike automated backups, manual snapshots aren\'t subject to the backup retention period.',
           'rds-automated-backups|Your Amazon RDS backup storage for each AWS Region is composed of the automated backups and manual DB snapshots for that Region.']),
        b('Retention in AWS Backup lives in the backup plan. AWS Backup manages your backup plan\'s lifecycle based on your retention settings. If you lock a vault, backups in it cannot be deleted until their lifecycle completes, so AWS tells you to set retention appropriately to avoid unintended storage costs.',
          ['backup-plans', 'backup-vault-lock'],
          ['backup-plans|AWS Backup also seamlessly manages your backup plan\'s lifecycle based on your retention settings, which allows you to restore when needed.',
           'backup-vault-lock|Because backups in a locked vault cannot be deleted until their lifecycle completes, ensure your retention settings are configured appropriately to avoid unintended storage costs.']),
      ],
      services: ['AWS Backup', 'Amazon RDS'],
      design: [
        b('Cue: "keep database backups only as long as policy requires, minimise storage" → set the shortest retention period that meets the requirement and delete old manual snapshots; "retention must be enforced and cannot be shortened" → Backup Vault Lock (Archive Annex), with retention set carefully.',
          ['rds-backup-retention', 'rds-snapshot-create', 'backup-vault-lock'],
          ['rds-backup-retention|You can set the backup retention period of a DB instance to between 0 and 35 days.',
           'rds-snapshot-create|Unlike automated backups, manual snapshots aren\'t subject to the backup retention period.',
           'backup-vault-lock|Because backups in a locked vault cannot be deleted until their lifecycle completes, ensure your retention settings are configured appropriately to avoid unintended storage costs.']),
      ],
    },
    {
      id: '4.3-S1',
      concepts: [
        b('Snapshot frequency sets the recovery point. For RDS, automated backups include transaction logs that RDS uploads to Amazon S3 every five minutes, so you can restore a DB instance to a specific point in time during the retention period without taking a snapshot every few minutes. Take manual snapshots for specific events, such as before a major change, and for long-term keeps.',
          ['rds-pitr', 'rds-automated-backups'],
          ['rds-pitr|RDS uploads transaction logs for DB instances to Amazon S3 every five minutes.',
           'rds-automated-backups|If necessary, you can recover your DB instance to any point in time during the backup retention period.']),
        b('In AWS Backup you choose how often a plan creates a backup in the backup rule: the rule sets the schedule, the window and the lifecycle. The more often it runs the smaller the possible data loss, and the more backups there are to store; incremental backups reduce that storage because only changes after the first full copy are backed up.',
          ['backup-create-plan', 'backup-what-is'],
          ['backup-create-plan|In the backup rule configuration section, you will set the backup schedule, window, and lifecycle.',
           'backup-create-plan|In the backup frequency menu, choose how often you want this plan to create a backup.',
           'backup-what-is|For each successive incremental backup, only the changes to your AWS resources are backed up.']),
        b('Match the policy to the requirement, not to the maximum. A recovery point objective (see Disaster Bunker) sets the frequency; a compliance requirement sets the minimum retention; everything else is cost to be removed. Backups that must be kept long-term but rarely restored can move to a cheaper tier (Backup Archive and Cold Cellar).',
          ['dr-options'],
          ['dr-options|How often you run your backup will determine your achievable recovery point (which should align to meet your RPO).']),
      ],
      services: ['AWS Backup', 'Amazon RDS'],
      design: [
        b('Cue: "restore to any moment in the last few days" → RDS automated backups with point-in-time restore; "centralised policy across several services with scheduled backups" → AWS Backup plan; "reduce backup storage cost" → shorter retention, incremental backups, delete unneeded manual snapshots.',
          ['rds-pitr', 'backup-create-plan', 'backup-what-is'],
          ['rds-pitr|RDS uploads transaction logs for DB instances to Amazon S3 every five minutes.',
           'backup-create-plan|In the backup frequency menu, choose how often you want this plan to create a backup.',
           'backup-what-is|For each successive incremental backup, only the changes to your AWS resources are backed up.']),
      ],
    },
  ],
  cues: [
    cue('restore the database to a point in time within a retention window', 'RDS automated backups (retention period)',
      b('RDS can recover a DB instance to any point in time during the retention period.', 'rds-automated-backups',
        ['If necessary, you can recover your DB instance to any point in time during the backup retention period.'])),
    cue('keep a database copy until someone deletes it, outside the retention window', 'Manual DB snapshot',
      b('Manual snapshots are not subject to the backup retention period.', 'rds-snapshot-create',
        ['Unlike automated backups, manual snapshots aren\'t subject to the backup retention period.'])),
    cue('turn off automated backups for a disposable test database', 'Retention period set to 0',
      b('Setting the backup retention period to 0 disables automated backups.', 'rds-backup-retention',
        ['Setting the backup retention period to 0 disables automated backups.'])),
    cue('scheduled backups with lifecycle across services, one policy', 'AWS Backup plan (rule with schedule, window and lifecycle)',
      b('A backup rule sets the schedule, window and lifecycle.', 'backup-create-plan',
        ['In the backup rule configuration section, you will set the backup schedule, window, and lifecycle.'])),
    cue('backups must not be deletable before their retention ends', 'AWS Backup Vault Lock',
      b('Backups in a locked vault cannot be deleted until their lifecycle completes.', 'backup-vault-lock',
        ['Because backups in a locked vault cannot be deleted until their lifecycle completes, ensure your retention settings are configured appropriately to avoid unintended storage costs.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Backup',
      aws: 'AWS Backup',
      mapping: b('Learn pairs AWS Backup with Azure Backup, used to back up and recover files, databases, disks and virtual machines.',
        ['learn-storage', 'backup-what-is'],
        ['learn-storage|Backup Backup This option is used to back up and recover files, databases, disks, and virtual machines.',
         'backup-what-is|AWS Backup is a fully-managed service that makes it easy to centralize and automate data protection across AWS services, in the cloud, and on premises.']),
      breaks: b('For databases the AWS exam point is that RDS has its own retention controls separate from AWS Backup: an automated-backup retention period that you set per DB instance, and manual snapshots that are not subject to it. The Learn pairing describes only the AWS Backup-style service.',
        ['rds-backup-retention', 'rds-snapshot-create', 'learn-storage'],
        ['rds-backup-retention|You can set the backup retention period of a DB instance to between 0 and 35 days.',
         'rds-snapshot-create|Unlike automated backups, manual snapshots aren\'t subject to the backup retention period.',
         'learn-storage|Backup Backup This option is used to back up and recover files, databases, disks, and virtual machines.']),
    },
  ],
};

export default notes;
