import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'route-tariff',
  overview: [
    b('Data moving through the network is billed by where it goes. Traffic that stays inside one Availability Zone is the cheapest to move; crossing Availability Zones or Regions, passing through a NAT gateway or a transit hub, or leaving to the internet adds charges. Route design, DNS, endpoints and caching decide how much of your traffic takes the expensive paths. The numbers change, so the exam is about direction: which choice keeps traffic on the cheaper path.',
      ['peering-what-is', 'tgw-what-is', 'vpce-gateway'],
      ['peering-what-is|All data transfer over a VPC peering connection that stays within an Availability Zone is free, even if it\'s between different accounts.',
       'peering-what-is|Charges apply for data transfer over VPC peering connections that cross Availability Zones and Regions.',
       'tgw-what-is|You are charged hourly for each attachment on a transit gateway, and you are charged for the amount of traffic processed on the transit gateway.',
       'vpce-gateway|There is no additional charge for using gateway endpoints.']),
  ],
  beyondProject: [
    b('Your static site is served by CloudFront. The SAA cost point is that a CDN lowers cost as well as latency. Data transfer between CloudFront and your AWS origins is automatically waived when serving traffic through CloudFront, and cached content served from edge locations means fewer requests hit your origin servers, databases and other services that charge based on usage. A longer cache duration reduces the load on your origin and means files are more likely to be served from the edge cache.',
      ['cloudfront-pricing', 'cloudfront-expiration'],
      ['cloudfront-pricing|Data transfer between CloudFront and your AWS origins is automatically waived when serving traffic through CloudFront, giving you a monthly price for both CloudFront delivery and your AWS origin’s data transfer costs to CloudFront.',
       'cloudfront-pricing|you\'ll see fewer requests hitting your origin servers, databases, and other AWS services that charge based on usage—reducing your costs.',
       'cloudfront-expiration|A longer duration also reduces the load on your origin.']),
  ],
  bullets: [
    {
      id: '4.4-K6',
      concepts: [
        b('VPC peering connects VPCs, which can be in different Regions, so resources communicate using private IP addresses without a gateway, VPN connection or network appliance. There is no charge to create a peering connection. Transitive peering relationships are not supported, so a design with many VPCs becomes a mesh of connections.',
          ['peering-what-is', 'peering-basics'],
          ['peering-what-is|The VPCs can be in different Regions (also known as an inter-Region VPC peering connection).',
           'peering-what-is|There is no charge to create a VPC peering connection.',
           'peering-basics|You can create multiple VPC peering connections for each VPC that you own, but transitive peering relationships are not supported.']),
        b('Transit Gateway is a network transit hub used to interconnect VPCs and on-premises networks. You attach VPCs, VPN connections, Direct Connect gateways and peering connections to it, and inter-Region peering connects transit gateways across Regions. It is charged hourly for each attachment and for the amount of traffic processed, so the hub costs more per connection than direct peering but replaces a mesh of peering connections.',
          ['tgw-what-is'],
          ['tgw-what-is|AWS Transit Gateway is a network transit hub used to interconnect virtual private clouds (VPCs) and on-premises networks.',
           'tgw-what-is|As your cloud infrastructure expands globally, inter-Region peering connects transit gateways together using the AWS Global Infrastructure.',
           'tgw-what-is|You are charged hourly for each attachment on a transit gateway, and you are charged for the amount of traffic processed on the transit gateway.']),
        b('PrivateLink interface endpoints give private access to services; an interface endpoint is billed for hourly usage and data processing charges. Gateway endpoints for S3 and DynamoDB have no additional charge. The full comparison with peering and Transit Gateway is in the Don\'t confuse section of Grid Planning Office.',
          ['vpce-interface', 'vpce-gateway'],
          ['vpce-interface|You are billed for hourly usage and data processing charges.',
           'vpce-gateway|There is no additional charge for using gateway endpoints.']),
      ],
      services: ['AWS Transit Gateway', 'Amazon VPC', 'AWS PrivateLink'],
      design: [
        b('Cue: "a pair of VPCs need to talk, lowest cost" → VPC peering; "many VPCs and on-premises networks, simple routing" → Transit Gateway; "private access to S3 or DynamoDB at no extra charge" → gateway endpoint.',
          ['peering-what-is', 'tgw-what-is', 'vpce-gateway'],
          ['peering-what-is|There is no charge to create a VPC peering connection.',
           'tgw-what-is|AWS Transit Gateway is a network transit hub used to interconnect virtual private clouds (VPCs) and on-premises networks.',
           'vpce-gateway|There is no additional charge for using gateway endpoints.']),
      ],
    },
    {
      id: '4.4-K7',
      concepts: [
        b('Amazon Route 53 is a highly available and scalable DNS web service. It performs domain registration, DNS routing and health checking in any combination. When you create a record you choose a routing policy that determines how Route 53 responds to queries, for example latency routing for resources in multiple Regions and failover routing for active-passive failover.',
          ['route53-what-is', 'route53-routing'],
          ['route53-what-is|Amazon Route 53 is a highly available and scalable Domain Name System (DNS) web service.',
           'route53-what-is|You can use Route 53 to perform three main functions in any combination: domain registration, DNS routing, and health checking.',
           'route53-routing|Latency routing policy – Use when you have resources in multiple AWS Regions and you want to route traffic to the Region that provides the best latency.',
           'route53-routing|Failover routing policy – Use when you want to configure active-passive failover.'],
          { allow: ['three'] }),
        b('Alias records route traffic to selected AWS resources such as CloudFront distributions and S3 buckets, and unlike a CNAME record you can create one at the zone apex. Route 53 does not charge for alias queries to AWS resources but does charge for CNAME queries, and its pricing lists hosted zones and records among its pricing components, so the number of hosted zones is a cost item to review.',
          ['route53-alias', 'route53-pricing'],
          ['route53-alias|Alias records let you route traffic to selected AWS resources, such as CloudFront distributions and Amazon S3 buckets.',
           'route53-alias|Unlike a CNAME record, you can create an alias record at the top node of a DNS namespace, also known as the zone apex.',
           'route53-alias|Route 53 doesn\'t charge for alias queries to AWS resources.',
           'route53-alias|Route 53 charges for CNAME queries.',
           'route53-pricing|Authoritative DNS Hosted Zones and Records']),
      ],
      services: ['Amazon Route 53'],
      design: [
        b('Cue: "send users to the Region with the best latency" → latency routing; "standby in another Region" → failover routing; "root domain pointing at CloudFront or S3" → alias record.',
          ['route53-routing', 'route53-alias'],
          ['route53-routing|Latency routing policy – Use when you have resources in multiple AWS Regions and you want to route traffic to the Region that provides the best latency.',
           'route53-alias|Alias records let you route traffic to selected AWS resources, such as CloudFront distributions and Amazon S3 buckets.']),
      ],
    },
    {
      id: '4.4-S3',
      concepts: [
        b('Availability Zone to Availability Zone: data transfer over a VPC peering connection that stays within an Availability Zone is free, while charges apply for transfer that crosses Availability Zones and Regions. For NAT gateways, keep traffic in the gateway\'s Availability Zone or run a gateway in each zone (NAT Toll). The same idea applies to any chatty tier: place the pieces that talk the most in the same zone unless availability requires otherwise.',
          ['peering-what-is', 'vpc-nat-pricing'],
          ['peering-what-is|All data transfer over a VPC peering connection that stays within an Availability Zone is free, even if it\'s between different accounts.',
           'peering-what-is|Charges apply for data transfer over VPC peering connections that cross Availability Zones and Regions.',
           'vpc-nat-pricing|If your AWS resources send or receive a significant volume of traffic across Availability Zones, ensure that the resources are in the same Availability Zone as the NAT gateway.']),
        b('Region to Region: charges apply for peering traffic that crosses Regions, so replicate or move across Regions only when the requirement (disaster recovery, latency, residency) needs it, and avoid designs where a tier in one Region constantly calls a tier in another.',
          'peering-what-is',
          ['Charges apply for data transfer over VPC peering connections that cross Availability Zones and Regions.']),
        b('Private to public: send traffic to S3 and DynamoDB through gateway endpoints, which have no additional charge, instead of through a NAT gateway that bills for each gigabyte it processes. Note that traffic destined for S3 or DynamoDB in a different Region goes to the internet gateway because prefix lists are specific to a Region, so the endpoint only helps for the same Region.',
          ['vpce-gateway', 'vpc-nat-pricing'],
          ['vpce-gateway|There is no additional charge for using gateway endpoints.',
           'vpce-gateway|Traffic that\'s destined for the service (Amazon S3 or DynamoDB) in a different Region goes to the internet gateway because prefix lists are specific to a Region.',
           'vpc-nat-pricing|When you provision a NAT gateway, you are charged for each hour that your NAT gateway is available and each gigabyte of data that it processes.']),
        b('Global Accelerator is for performance and availability, not for cutting transfer cost: you are charged a fixed hourly fee for every accelerator that is provisioned, plus an incremental charge over standard Data Transfer rates (DT-Premium) on the dominant direction of traffic. Choose it when the requirement is static anycast IP addresses or faster failover; otherwise CloudFront caching is the cheaper way to reduce origin traffic.',
          ['ga-pricing', 'ga-what-is'],
          ['ga-pricing|For every accelerator that is provisioned (both enabled and disabled), you are charged a fixed hourly fee and an incremental charge over your standard Data Transfer rates, also called a Data Transfer-Premium fee (DT-Premium).',
           'ga-what-is|The static IP addresses are anycast from the AWS edge network.']),
      ],
      services: ['Amazon VPC', 'AWS Global Accelerator', 'AWS PrivateLink'],
      design: [
        b('Cue: "private subnets download from S3 through a NAT gateway and the bill is high" → gateway endpoint for S3; "chatty tiers in different Availability Zones" → co-locate or accept the cost for availability; "need static IPs and fast regional failover" → Global Accelerator, knowing it adds a premium charge.',
          ['vpce-gateway', 'peering-what-is', 'ga-pricing'],
          ['vpce-gateway|There is no additional charge for using gateway endpoints.',
           'peering-what-is|Charges apply for data transfer over VPC peering connections that cross Availability Zones and Regions.',
           'ga-pricing|For every accelerator that is provisioned (both enabled and disabled), you are charged a fixed hourly fee and an incremental charge over your standard Data Transfer rates, also called a Data Transfer-Premium fee (DT-Premium).']),
      ],
    },
    {
      id: '4.4-S4',
      concepts: [
        b('A CDN is a strategic need when many users repeatedly request the same content from far away, or when you want to protect and offload an origin. CloudFront delivers content through edge locations and retrieves it from the origin only when it is not already in the edge location. That reduces origin requests, origin data transfer and the load on databases behind it.',
          ['cloudfront-what-is', 'cloudfront-pricing'],
          ['cloudfront-what-is|If the content is already in the edge location with the lowest latency, CloudFront delivers it immediately.',
           'cloudfront-pricing|you\'ll see fewer requests hitting your origin servers, databases, and other AWS services that charge based on usage—reducing your costs.']),
        b('Edge caching strategy is mostly about cache duration: you can control how long files stay in a CloudFront cache before CloudFront forwards another request to your origin. A longer duration means better performance and lower origin load, and content that changes constantly gains less from a long duration. After a file expires, the next request makes CloudFront check the origin for the latest version.',
          'cloudfront-expiration',
          ['You can control how long your files stay in a CloudFront cache before CloudFront forwards another request to your origin.',
           'Increasing the duration means that your users get better performance because your files are more likely to be served directly from the edge cache.',
           'After it expires, the next time the edge location gets a request for the file, CloudFront forwards the request to the origin to verify that the cache contains the latest version of the file.']),
        b('To update cached content without waiting for expiry, include a version identifier in file or folder names. With versioning you do not have to wait for an object to expire before CloudFront begins to serve a new version of it, and you do not have to pay for object invalidation, so a long cache duration and versioned names work together.',
          'cloudfront-versioning',
          ['Update existing files using versioned file names When you update existing files in a CloudFront distribution, we recommend that you include some sort of version identifier either in your file names or in your directory names to give yourself better control over your content.',
           'With versioning, you don\'t have to wait for an object to expire before CloudFront begins to serve a new version of it, and you don\'t have to pay for object invalidation.']),
        b('Price class is a cost lever for how widely CloudFront serves your content. By default CloudFront serves your objects from edge locations in all CloudFront Regions, and the price class setting lets you choose the class that corresponds with the maximum price you want to pay for the service. AWS notes that your choice also affects performance for your distribution.',
          'cloudfront-settings',
          ['Choose the price class that corresponds with the maximum price that you want to pay for CloudFront service.',
           'By default, CloudFront serves your objects from edge locations in all CloudFront Regions.',
           'For more information about price classes and about how your choice of price class affects CloudFront performance for your distribution, see CloudFront pricing.']),
        b('CloudFront offers pay-as-you-go pricing and flat-rate pricing plans that combine the CDN with other AWS services into a monthly price with no overage charges. Compare them against expected traffic; AWS lists the included services on the pricing page.',
          'cloudfront-pricing',
          ['CloudFront flat-rate pricing plans combine the Amazon CloudFront global content delivery network (CDN) with multiple AWS services and features into a monthly price with no overage charges.']),
      ],
      services: ['Amazon CloudFront'],
      design: [
        b('Cue: "global users, mostly static content, reduce origin cost" → CloudFront with a long cache duration; check price class when the question limits where users are; "content changes often" → shorter duration or invalidation; "static IPs, non-HTTP traffic" → Global Accelerator, not a CDN.',
          ['cloudfront-what-is', 'cloudfront-expiration', 'ga-what-is'],
          ['cloudfront-what-is|If the content is already in the edge location with the lowest latency, CloudFront delivers it immediately.',
           'cloudfront-expiration|A longer duration also reduces the load on your origin.',
           'ga-what-is|The static IP addresses are anycast from the AWS edge network.']),
      ],
    },
  ],
  cues: [
    cue('connect two VPCs at the lowest cost', 'VPC peering (no charge to create)',
      b('There is no charge to create a VPC peering connection.', 'peering-what-is',
        ['There is no charge to create a VPC peering connection.'])),
    cue('many VPCs and on-premises networks need simple routing through a hub', 'AWS Transit Gateway',
      b('Transit Gateway is a network transit hub, charged per attachment per hour and for traffic processed.', 'tgw-what-is',
        ['You are charged hourly for each attachment on a transit gateway, and you are charged for the amount of traffic processed on the transit gateway.'])),
    cue('private subnets reach S3 and the NAT gateway charges are high', 'S3 gateway endpoint',
      b('There is no additional charge for using gateway endpoints.', 'vpce-gateway',
        ['There is no additional charge for using gateway endpoints.'])),
    cue('reduce traffic and load on the origin for popular static content', 'Amazon CloudFront with a longer cache duration',
      b('A longer cache duration reduces the load on your origin.', 'cloudfront-expiration',
        ['A longer duration also reduces the load on your origin.'])),
    cue('route users to the Region with the best latency', 'Route 53 latency routing',
      b('Latency routing sends traffic to the Region that provides the best latency.', 'route53-routing',
        ['Latency routing policy – Use when you have resources in multiple AWS Regions and you want to route traffic to the Region that provides the best latency.'])),
    cue('root domain name pointing at a CloudFront distribution', 'Route 53 alias record',
      b('You can create an alias record at the zone apex, which a CNAME cannot do.', 'route53-alias',
        ['Unlike a CNAME record, you can create an alias record at the top node of a DNS namespace, also known as the zone apex.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Virtual network peering',
      aws: 'VPC peering',
      mapping: b('Learn says both Azure and AWS support virtual network or VPC peering. Azure virtual network peering connects virtual networks through the Azure backbone network, and once peered the networks appear as one for connectivity purposes.',
        ['learn-networking', 'peering-what-is'],
        ['learn-networking|Both Azure and AWS support virtual network / VPC peering.',
         'learn-networking|After they\'re peered, the two virtual networks appear as one for all connectivity purposes.',
         'peering-what-is|The VPCs can be in different Regions (also known as an inter-Region VPC peering connection).']),
      breaks: b('AWS adds rules the exam relies on: transitive peering relationships are not supported, and data transfer over a peering connection is free within an Availability Zone but charged across Availability Zones and Regions. Learn describes the connection but not these cost rules.',
        ['peering-basics', 'peering-what-is', 'learn-networking'],
        ['peering-basics|You can create multiple VPC peering connections for each VPC that you own, but transitive peering relationships are not supported.',
         'peering-what-is|Charges apply for data transfer over VPC peering connections that cross Availability Zones and Regions.',
         'learn-networking|Both Azure and AWS support virtual network / VPC peering.']),
    },
    {
      concept: 'Azure Virtual WAN',
      aws: 'AWS Transit Gateway',
      mapping: b('Learn says both technologies allow more complex peering via Azure Virtual WAN or AWS Transit Gateway.',
        ['learn-networking', 'tgw-what-is'],
        ['learn-networking|Both technologies allow more complex peering via Azure Virtual WAN or AWS Transit Gateway.',
         'tgw-what-is|AWS Transit Gateway is a network transit hub used to interconnect virtual private clouds (VPCs) and on-premises networks.']),
      breaks: b('The Transit Gateway cost model is part of the AWS question: it is charged hourly for each attachment and for traffic processed, so a hub is not the cheapest answer for connecting just a pair of VPCs. The Learn sentence does not describe any billing.',
        ['tgw-what-is', 'learn-networking'],
        ['tgw-what-is|You are charged hourly for each attachment on a transit gateway, and you are charged for the amount of traffic processed on the transit gateway.',
         'learn-networking|Both technologies allow more complex peering via Azure Virtual WAN or AWS Transit Gateway.']),
    },
    {
      concept: 'Azure DNS',
      aws: 'Amazon Route 53',
      mapping: b('Learn says Route 53 provides both DNS name management and DNS-level traffic routing and failover, whereas in Azure separate services handle these tasks: Azure DNS for domain and DNS management and Traffic Manager for DNS-level traffic routing, load balancing and failover.',
        ['learn-networking', 'route53-what-is'],
        ['learn-networking|In AWS, Route 53 provides both DNS name management and DNS-level traffic routing and failover services.',
         'learn-networking|Azure DNS provides domain and DNS management.',
         'learn-networking|Traffic Manager provides DNS-level traffic routing, load balancing, and failover capabilities.']),
      breaks: b('On AWS, one service covers both, and the routing policy you choose (latency, failover, and others) is a property of the record. Azure DNS alone does not map to the routing policies, so a Route 53 routing question needs the AWS page, not the Azure DNS comparison.',
        ['route53-routing', 'learn-networking'],
        ['route53-routing|Failover routing policy – Use when you want to configure active-passive failover.',
         'learn-networking|Azure DNS provides domain and DNS management.']),
    },
    {
      concept: 'Azure Front Door',
      aws: 'Amazon CloudFront',
      mapping: b('Learn pairs CloudFront with Azure Front Door, a modern cloud content delivery network service that provides high performance, scalability and secure user experiences for content and applications.',
        ['learn-networking', 'cloudfront-what-is'],
        ['learn-networking|Azure Front Door is a modern cloud content delivery network (CDN) service that provides high performance, scalability, and secure user experiences for your content and applications.',
         'cloudfront-what-is|CloudFront delivers your content through a worldwide network of data centers called edge locations.']),
      breaks: b('The cost lever on AWS is that data transfer between CloudFront and your AWS origins is waived when serving traffic through CloudFront, and cached content means fewer requests to the origin. That is an AWS pricing statement the Learn row does not make.',
        ['cloudfront-pricing', 'learn-networking'],
        ['cloudfront-pricing|Data transfer between CloudFront and your AWS origins is automatically waived when serving traffic through CloudFront, giving you a monthly price for both CloudFront delivery and your AWS origin’s data transfer costs to CloudFront.',
         'learn-networking|Azure Front Door is a modern cloud content delivery network (CDN) service that provides high performance, scalability, and secure user experiences for your content and applications.']),
    },
    {
      concept: 'Private Endpoint',
      aws: 'VPC endpoints (gateway and interface endpoints)',
      mapping: b('Learn pairs VPC endpoints with Azure Private Endpoint, which provides secured, private connectivity to various Azure platform as a service resources over a backbone Microsoft private network.',
        ['learn-networking', 'vpce-interface'],
        ['learn-networking|Private Endpoint provides secured, private connectivity to various Azure platform as a service (PaaS) resources, over a backbone Microsoft private network.',
         'vpce-interface|You are billed for hourly usage and data processing charges.']),
      breaks: b('AWS has two endpoint types and they bill differently: gateway endpoints for S3 and DynamoDB have no additional charge, whereas an interface endpoint is billed for hourly usage and data processing. The exam asks you to pick the endpoint type, and the Learn row covers only the private-endpoint idea.',
        ['vpce-gateway', 'vpce-interface', 'learn-networking'],
        ['vpce-gateway|There is no additional charge for using gateway endpoints.',
         'vpce-interface|You are billed for hourly usage and data processing charges.',
         'learn-networking|Private Endpoint provides secured, private connectivity to various Azure platform as a service (PaaS) resources, over a backbone Microsoft private network.'],
        { allow: ['two'] }),
    },
  ],
};

export default notes;
