import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'service-selection-bureau',
  overview: [
    b('Database cost depends first on picking the right kind of database and then on how its capacity is billed. Express Quarter taught the data models and performance; this building asks which choice costs least for the same job. Serverless options bill for what the workload uses instead of for an always-on server, purpose-built databases avoid forcing one engine to do every job, and the storage format (row, key-value, time series, columnar) changes how much data must be read and stored.',
      ['database-decision', 'aurora-serverless', 'dynamodb-ondemand'],
      ['database-decision|AWS serverless offerings include Amazon Aurora DSQL, Amazon Aurora Serverless, Amazon DynamoDB, Amazon ElastiCache, Amazon Keyspaces (for Apache Cassandra), Amazon Timestream for LiveAnalytics, and Amazon Neptune Serverless.',
       'aurora-serverless|Thus, Aurora serverless can help you to stay within budget and avoid paying for computer resources that you don\'t use.',
       'dynamodb-ondemand|With pay-per-request pricing, you don’t have to worry about idle capacity because you only pay for the throughput you actually use.']),
  ],
  beyondProject: [
    b('Your project uses DynamoDB. The SAA cost question is which capacity mode is cheaper for a workload. In on-demand mode there is pay-per-request pricing, so you do not worry about idle capacity, and if you drive no traffic to the table you are not charged for any throughput; provisioned mode asks you to specify throughput capacity and lets auto scaling adjust it in response to traffic changes. Unpredictable or spiky traffic points to on-demand; steady, forecastable traffic is where provisioned capacity is worth planning (Tuning Bay covers the capacity units).',
      ['dynamodb-ondemand', 'dynamodb-provisioned'],
      ['dynamodb-ondemand|With pay-per-request pricing, you don’t have to worry about idle capacity because you only pay for the throughput you actually use.',
       'dynamodb-ondemand|If you are driving zero traffic to your table, then with on-demand, you are not charged for any throughput.',
       'dynamodb-provisioned|When you create a new provisioned table in DynamoDB, you must specify its provisioned throughput capacity.',
       'dynamodb-provisioned|You can use auto scaling to adjust your table’s provisioned capacity automatically in response to traffic changes.']),
  ],
  bullets: [
    {
      id: '4.3-K9',
      concepts: [
        b('There are relational and non-relational OLTP databases, and a separate analytics need. AWS describes two high-level categories of OLTP databases, relational and non-relational, and offers Amazon Redshift when you need to store and analyse massive amounts of data quickly (an OLAP requirement). Using the category that fits the access pattern avoids paying for features, or for scale, that the workload does not use.',
          'database-decision',
          ['There are two high-level categories of AWS OLTP databases—relational and non-relational.',
           'If you need to store and analyze massive amounts of data quickly and efficiently (a requirement that is typically met by an OLAP application), AWS offers Amazon Redshift.'],
          { allow: ['two'] }),
        b('Amazon DynamoDB is a serverless, fully managed, distributed NoSQL database with single-digit millisecond performance at any scale, which AWS suggests for key-value workloads such as session stores or shopping carts. Amazon Aurora is the relational option for migrating or modernising an on-premises relational workload, or one with less predictable query patterns.',
          ['dynamodb-what-is', 'database-decision'],
          ['dynamodb-what-is|Amazon DynamoDB is a serverless, fully managed, distributed NoSQL database with single-digit millisecond performance at any scale.',
           'database-decision|Amazon DynamoDB Key-value Use for workloads such as session stores or shopping carts.',
           'database-decision|Amazon Aurora Relational Use when you\'re migrating or modernizing an on-premises relational workload, or if your workload has less predictable query patterns.']),
      ],
      services: ['Amazon DynamoDB', 'Amazon RDS', 'Amazon Aurora Serverless'],
      design: [
        b('Cue: "simple key lookups at huge scale, unpredictable traffic, minimal operations" → DynamoDB on-demand; "relational schema, joins, an existing MySQL or PostgreSQL app" → Aurora or RDS; "analytical queries over very large data" → Redshift.',
          ['database-decision', 'dynamodb-ondemand'],
          ['database-decision|Amazon DynamoDB Key-value Use for workloads such as session stores or shopping carts.',
           'dynamodb-ondemand|With pay-per-request pricing, you don’t have to worry about idle capacity because you only pay for the throughput you actually use.']),
      ],
    },
    {
      id: '4.3-S3',
      concepts: [
        b('DynamoDB and RDS bill differently. DynamoDB is serverless and its on-demand mode charges per request, so a lightly used table costs very little; with RDS you choose a DB instance class and pay for it while it runs, and for steady use you can reserve it for a term. The cost question is therefore how steady and how large the load is, not which product is cheaper in general.',
          ['dynamodb-ondemand', 'rds-reserved'],
          ['dynamodb-ondemand|If you are driving zero traffic to your table, then with on-demand, you are not charged for any throughput.',
           'rds-reserved|Reserved DB instances are not physical instances, but rather a billing discount applied to the use of certain on-demand DB instances in your account.']),
        b('Aurora serverless is an on-demand, autoscaling configuration for Aurora. It automates monitoring the workload and adjusting capacity, which can help you stay within budget and avoid paying for compute resources you do not use. AWS lists development and test systems and environments with highly variable and unpredictable workloads among the cases where it is especially valuable. Capacity is measured in Aurora capacity units (ACUs) and goes up to 256 ACUs on current versions; the capacity range that is supported depends on the engine and platform version.',
          ['aurora-serverless', 'aurora-serverless-how'],
          ['aurora-serverless|Aurora serverless is an on-demand, autoscaling configuration for Amazon Aurora.',
           'aurora-serverless|Thus, Aurora serverless can help you to stay within budget and avoid paying for computer resources that you don\'t use.',
           'aurora-serverless|This type of automation is especially valuable for multitenant databases, distributed databases, development and test systems, and other environments with highly variable and unpredictable workloads.',
           'aurora-serverless-how|Aurora serverless offers capacity from 0 ACUs to 256 ACUs.',
           'aurora-serverless-how|The following table shows the Aurora serverless capacity ranges and engine version support for Aurora MySQL and Aurora PostgreSQL.']),
        b('In recent Aurora MySQL and Aurora PostgreSQL versions, the writer and readers can scale all the way down to zero ACUs, called automatic pause and resume or auto-pause. It is a choice: you allow it by setting the minimum capacity to zero, and with a nonzero minimum the database never pauses.',
          'aurora-serverless-how',
          ['Scaling to Zero In recent Aurora MySQL and Aurora PostgreSQL versions, Aurora serverless writers and readers can scale all the way down to zero ACUs.',
           'We refer to this capability as automatic pause and resume, or auto-pause.',
           'You can choose whether to allow this behavior by specifying a zero or nonzero value for the minimum capacity.'],
          { allow: ['zero'] }),
        b('Older material may describe Aurora Serverless v1, which AWS now calls a deprecated product with a different architecture from the current Aurora serverless. Treat v1 behaviour as history, not as the answer to a new design question.',
          'aurora-serverless-how',
          ['Platform versions should not be confused with Aurora Serverless v1, which is a deprecated product with a different architecture.'],
          { status: 'deprecated' }),
        b('Serverless is not a synonym for cheapest. A steady workload that runs all day may cost less on a provisioned instance with a commitment, since a Database Savings Plan applies to provisioned and serverless usage, and reserved DB instances give a billing discount for the term. Check how steady the load is before choosing.',
          ['savings-plans-types', 'rds-reserved'],
          ['savings-plans-types|These plans automatically apply to the latest provisioned instance generations regardless of engine, instance family, size, Availability Zone (AZ), or Region, and also apply to serverless usage.',
           'rds-reserved|Reserved DB instances provide you with a significant discount compared to on-demand DB instance pricing.']),
      ],
      services: ['Amazon DynamoDB', 'Amazon RDS', 'Amazon Aurora Serverless'],
      design: [
        b('Cue: "intermittent or unpredictable database use, development and test" → Aurora Serverless or DynamoDB on-demand; "steady, always-on relational workload" → a provisioned instance with a reservation or Database Savings Plan; "key-value access, no servers to manage" → DynamoDB.',
          ['aurora-serverless', 'dynamodb-ondemand', 'rds-reserved'],
          ['aurora-serverless|These range from development and testing environments, to websites and applications that have unpredictable workloads, to the most demanding, business-critical applications that require high scale and availability.',
           'dynamodb-ondemand|With pay-per-request pricing, you don’t have to worry about idle capacity because you only pay for the throughput you actually use.',
           'rds-reserved|Reserved DB instances provide you with a significant discount compared to on-demand DB instance pricing.']),
      ],
    },
    {
      id: '4.3-S4',
      concepts: [
        b('Time series data is a purpose-built type. Amazon Timestream is for large amounts of time series data from sources such as IoT, application metrics and asset tracking. Timestream for LiveAnalytics keeps recent data in memory and moves historical data to a cost optimised storage tier based on user defined policies. AWS\'s page points to Amazon Timestream for InfluxDB for similar capabilities.',
          ['database-decision', 'timestream-what-is'],
          ['database-decision|Amazon Timestream Time series Use when you have a large amount of time series data, potentially from a number of sources, such as Internet of Things (IoT) data, application metrics, and asset tracking.',
           'timestream-what-is|Timestream for LiveAnalytics saves you time and cost in managing the lifecycle of time series data by keeping recent data in memory and moving historical data to a cost optimized storage tier based upon user defined policies.',
           'timestream-what-is|For similar capabilities to Amazon Timestream for LiveAnalytics, consider Amazon Timestream for InfluxDB.']),
        b('AWS has closed new customer access to Timestream for LiveAnalytics. Existing customer workloads are not affected, and AWS recommends that new customers evaluate Amazon Timestream for InfluxDB as an alternative.',
          'timestream-availability',
          ['After careful consideration, we have made the decision to close new customer access to Amazon Timestream for LiveAnalytics, effective 6/20/25.',
           'This change will not impact customer workloads running with Amazon Timestream for LiveAnalytics.',
           'We recommend that new customers evaluate Amazon Timestream for InfluxDB as an alternative due to its similar functionality.']),
        b('Columnar format is the analytics type. Amazon Redshift stores tabular data in columns, which AWS describes as an important factor in optimising analytic query performance because it drastically reduces overall disk I/O requirements and reduces the amount of data you need to load from disk. Use it for analytical queries over large data rather than for transactional lookups.',
          'redshift-columnar',
          ['Columnar storage for database tables is an important factor in optimizing analytic query performance, because it drastically reduces the overall disk I/O requirements.',
           'It reduces the amount of data you need to load from disk.']),
      ],
      services: ['Amazon Redshift', 'Amazon DynamoDB'],
      design: [
        b('Cue: "metrics or IoT readings over time with older data kept cheaply" → a time series database; "analytical queries that scan a few columns of very large tables" → columnar (Redshift); "transactional records with joins" → relational. Putting each data shape in its matching engine is the cost-effective choice because you are not paying a general engine to do a specialised job.',
          ['database-decision', 'redshift-columnar', 'timestream-what-is'],
          ['database-decision|Amazon Timestream Time series Use when you have a large amount of time series data, potentially from a number of sources, such as Internet of Things (IoT) data, application metrics, and asset tracking.',
           'redshift-columnar|It reduces the amount of data you need to load from disk.',
           'timestream-what-is|Timestream for LiveAnalytics saves you time and cost in managing the lifecycle of time series data by keeping recent data in memory and moving historical data to a cost optimized storage tier based upon user defined policies.']),
      ],
    },
  ],
  cues: [
    cue('pay only for the database throughput actually used; traffic is unpredictable', 'DynamoDB on-demand mode',
      b('On-demand mode has pay-per-request pricing with no idle capacity to worry about.', 'dynamodb-ondemand',
        ['With pay-per-request pricing, you don’t have to worry about idle capacity because you only pay for the throughput you actually use.'])),
    cue('relational database for development/test or highly variable workloads, avoid paying for unused compute', 'Aurora serverless (current; Serverless v1 is deprecated)',
      b('Aurora serverless adjusts capacity to demand and can help avoid paying for compute you do not use.', 'aurora-serverless',
        ['Thus, Aurora serverless can help you to stay within budget and avoid paying for computer resources that you don\'t use.'])),
    cue('steady relational workload, lower the on-demand cost', 'Reserved DB instance or Database Savings Plan',
      b('Reserved DB instances give a significant discount compared with on-demand DB instance pricing.', 'rds-reserved',
        ['Reserved DB instances provide you with a significant discount compared to on-demand DB instance pricing.'])),
    cue('IoT or metrics time series with older data on cheaper storage', 'Amazon Timestream',
      b('Timestream moves historical data to a cost optimised storage tier based on policies.', 'timestream-what-is',
        ['Timestream for LiveAnalytics saves you time and cost in managing the lifecycle of time series data by keeping recent data in memory and moving historical data to a cost optimized storage tier based upon user defined policies.'])),
    cue('analytical queries over very large tables, columnar storage', 'Amazon Redshift',
      b('Columnar storage reduces the data loaded from disk for analytic queries.', 'redshift-columnar',
        ['It reduces the amount of data you need to load from disk.'])),
    cue('session store or shopping cart at massive scale', 'Amazon DynamoDB',
      b('AWS suggests DynamoDB for key-value workloads such as session stores or shopping carts.', 'database-decision',
        ['Amazon DynamoDB Key-value Use for workloads such as session stores or shopping carts.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure SQL Database serverless',
      aws: 'Amazon Aurora Serverless',
      mapping: b('Learn pairs Amazon Aurora Serverless with Azure SQL Database serverless (or SQL Database in Microsoft Fabric), and notes that SQL Database serverless can automatically scale compute and pause during inactivity. Current Aurora serverless can also scale all the way down to zero ACUs with automatic pause and resume in recent Aurora MySQL and Aurora PostgreSQL versions.',
        ['learn-databases', 'aurora-serverless', 'aurora-serverless-how'],
        ['learn-databases|Serverless relational database Amazon Aurora Serverless Azure SQL Database serverless or SQL Database in Microsoft Fabric',
         'learn-databases|SQL Database serverless can automatically scale compute and pause during inactivity.',
         'aurora-serverless|Aurora serverless is an on-demand, autoscaling configuration for Amazon Aurora.',
         'aurora-serverless-how|Scaling to Zero In recent Aurora MySQL and Aurora PostgreSQL versions, Aurora serverless writers and readers can scale all the way down to zero ACUs.'],
        { allow: ['zero'] }),
      breaks: b('Learn says these services use different scaling and billing models. On Aurora, whether it can pause is controlled by the minimum capacity you set (zero allows auto-pause), and capacity is adjusted automatically based on application demand.',
        ['learn-databases', 'aurora-serverless', 'aurora-serverless-how'],
        ['learn-databases|These services use different scaling and billing models.',
         'aurora-serverless|Capacity is adjusted automatically based on application demand.',
         'aurora-serverless-how|You can choose whether to allow this behavior by specifying a zero or nonzero value for the minimum capacity.'],
        { allow: ['zero'] }),
    },
    {
      concept: 'Azure Cosmos DB for NoSQL',
      aws: 'Amazon DynamoDB',
      mapping: b('Learn pairs Amazon DynamoDB with Azure Cosmos DB for NoSQL as a key-value and document database: both distribute data by partition key and provide change streams.',
        ['learn-databases', 'dynamodb-what-is'],
        ['learn-databases|Key-value and document database Amazon DynamoDB Azure Cosmos DB for NoSQL Both services distribute data by partition key and provide change streams.',
         'dynamodb-what-is|Amazon DynamoDB is a serverless, fully managed, distributed NoSQL database with single-digit millisecond performance at any scale.']),
      breaks: b('Learn notes that Azure Cosmos DB supports multiple APIs and data models. On AWS, DynamoDB lets you choose between on-demand mode and provisioned mode for your tables.',
        ['learn-databases', 'dynamodb-capacity'],
        ['learn-databases|Azure Cosmos DB supports multiple APIs and data models.',
         'dynamodb-capacity|In Amazon DynamoDB, you can choose between on-demand mode and provisioned mode for your tables to accommodate different workload requirements.']),
    },
  ],
};

export default notes;
