import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'storage-market',
  overview: [
    b('The cost-effective storage service is the one that matches how the data is used, not the one with the cheapest label. Each service has a lower-cost option for data that is read rarely: S3 has Intelligent-Tiering and infrequent-access classes, EFS has Infrequent Access and Archive classes, and FSx has its own Intelligent-Tiering class. The task is to match the access pattern to the service first and then to its cheaper tier.',
      ['storage-decision', 'efs-lifecycle'],
      ['storage-decision|For example, use Amazon S3 Intelligent-Tiering for object data, or the FSx Intelligent-Tiering storage class for Amazon FSx for OpenZFS and Amazon FSx for Lustre workloads.',
       'efs-lifecycle|Use lifecycle management to automatically transition data between storage classes according to the lifecycle configuration for the file system.']),
  ],
  beyondProject: [
    b('Your static site is a good S3 use case, because object storage suits read-heavy workloads such as websites. The SAA question is the comparison: S3 for objects accessed by API, EFS for file data shared by many instances, EBS for a disk attached to one instance, and FSx when a specific file system is required.',
      'storage-decision',
      ['Object storage provides easy access to data through an application programming interface (API) over the internet and is well-suited to read-heavy workloads (such as streaming applications and services).']),
  ],
  bullets: [
    {
      id: '4.1-K4',
      concepts: [
        b('Amazon S3 is object storage for any amount of data: data lakes, websites, mobile applications, backup and restore, archive, enterprise applications, IoT devices and big data analytics.',
          's3-what-is',
          ['Customers of all sizes and industries can use Amazon S3 to store and protect any amount of data for a range of use cases, such as data lakes, websites, mobile applications, backup and restore, archive, enterprise applications, IoT devices, and big data analytics.']),
        b('Amazon EFS is serverless, elastic file storage over NFS that you share without provisioning capacity; Amazon EBS is block storage attached to EC2 instances; and the Amazon FSx family offers managed Windows File Server, Lustre, NetApp ONTAP and OpenZFS file systems. The side-by-side comparison is in the Don\'t confuse section below.',
          ['efs-what-is', 'ebs-what-is', 'storage-decision'],
          ['efs-what-is|Amazon Elastic File System (Amazon EFS) provides serverless, fully elastic file storage so that you can share file data without provisioning or managing storage capacity and performance.',
           'ebs-what-is|Amazon Elastic Block Store (Amazon EBS) provides scalable, high-performance block storage resources that can be used with Amazon Elastic Compute Cloud (Amazon EC2) instances.',
           'storage-decision|Amazon FSx for NetApp ONTAP supports both NFS and SMB protocols, including concurrent multi-protocol access to the same data.']),
        b('FSx for Windows File Server provides fully managed Windows file servers on a native Windows file system for lift-and-shift of enterprise Windows applications; FSx for Lustre is for workloads where speed matters, such as machine learning, HPC, video processing and financial modeling; FSx for OpenZFS moves data from on-premises ZFS or other Linux-based file servers without changing application code.',
          ['fsx-windows', 'fsx-lustre', 'fsx-openzfs'],
          ['fsx-windows|FSx for Windows File Server has the features, performance, and compatibility to easily lift and shift enterprise applications to the AWS Cloud.',
           'fsx-lustre|You use Lustre for workloads where speed matters, such as machine learning, high performance computing (HPC), video processing, and financial modeling.',
           'fsx-openzfs|You can do this without changing your application code or how you manage data.']),
      ],
      services: ['Amazon S3', 'Amazon EFS', 'Amazon EBS', 'Amazon FSx'],
      design: [
        b('Cue: Windows file shares → FSx for Windows File Server; HPC scratch with fast S3-linked storage → FSx for Lustre; NetApp ONTAP features or multi-protocol access → FSx for ONTAP; shared Linux files → EFS; attached disk → EBS; website, backups, data lake → S3.',
          ['fsx-windows', 'storage-decision'],
          ['fsx-windows|Amazon FSx for Windows File Server provides fully managed Microsoft Windows file servers, backed by a fully native Windows file system.',
           'storage-decision|Amazon FSx for NetApp ONTAP supports both NFS and SMB protocols, including concurrent multi-protocol access to the same data.']),
      ],
    },
    {
      id: '4.1-K9',
      concepts: [
        b('An access pattern is how often and how the data is read and written. Choosing storage means matching the access pattern: AWS notes that understanding your access patterns is critical to achieving the performance, cost, efficiency, security and resiliency you want.',
          'storage-decision',
          ['access patterns will be critical to achieving the performance, cost, efficiency, security, and resiliency you want.']),
        b('Frequent access suits the standard class of each service; infrequent or cold access suits a cheaper tier. For file data that is rarely read, EFS Archive provides lower-cost storage for data you access only a few times a year, and EFS lifecycle management moves files based on when they were last accessed (the default policy transitions data to Archive after 90 days without access).',
          ['storage-decision', 'efs-lifecycle'],
          ['storage-decision|For cold, rarely accessed file data, use the Amazon EFS Archive storage class.',
           'storage-decision|This class provides lower-cost storage for data that you access only a few times a year.',
           'storage-decision|You enable it through Amazon EFS Lifecycle Management, whose default policy transitions data to Archive after 90 days without access.',
           'efs-lifecycle|Transition time is based on when the files were last accessed in the Standard storage class.']),
        b('EFS lifecycle management moves files through cheaper classes. By default, files that are not accessed in the Standard storage class are moved to Infrequent Access (IA), which is cost-optimized for data accessed only a few times each quarter, and later to Archive, which is cost-optimized for data accessed only a few times each year or less. By default files are not moved back to Standard when they are accessed in IA or Archive.',
          'efs-lifecycle',
          ['By default, files that are not accessed in Standard storage',
           'By default, files that are not accessed in the Standard storage class for 90 days are transitioned in to the Archive storage class.',
           'Transition into IA – Instructs lifecycle management when to move files in to the Infrequent Access (IA) storage class, which is cost-optimized for data that is accessed only a few times each quarter.',
           'Transition into Archive – Instructs lifecycle management when to move files from the Standard or IA storage class in to the Archive storage class, which is cost-optimized for data that is accessed only a few times each year or less.',
           'By default, files are not moved back to the Standard storage class, and they remain in the IA or Archive storage class when they are accessed.']),
        b('More EFS cost details. EFS offers Regional and One Zone file system types: One Zone file systems store data within a single Availability Zone, so data can be lost if all or part of that zone is lost. Throughput mode is billed separately from storage: with Elastic throughput you pay only for the amount of metadata and data read or written, and with Provisioned throughput you are charged for the throughput enabled for the file system.',
          ['efs-features', 'efs-performance'],
          ['efs-features|Amazon EFS offers Regional and One Zone file system types.',
           'efs-features|One Zone – One Zone file systems store data within a single Availability Zone.',
           'efs-features|In the unlikely case of the loss or damage to all or part of an AWS Availability Zone, data in a One Zone storage class may be lost.',
           'efs-performance|You pay only for the amount of metadata and data read or written, and you don\'t accrue or consume burst credits while using Elastic throughput.',
           'efs-performance|For file systems using Provisioned throughput, you are charged for the amount of throughput enabled for the file system.']),
        b('When the access pattern changes unpredictably, use the automatic tiering options: S3 Intelligent-Tiering for object data, and the FSx Intelligent-Tiering storage class for FSx for OpenZFS and FSx for Lustre, which tiers data across Frequent Access, Infrequent Access and Archive tiers to reduce storage costs for data with changing access patterns.',
          'storage-decision',
          ['For example, use Amazon S3 Intelligent-Tiering for object data, or the FSx Intelligent-Tiering storage class for Amazon FSx for OpenZFS and Amazon FSx for Lustre workloads.',
           'The FSx Intelligent-Tiering storage class automatically tiers data across Frequent Access, Infrequent Access, and Archive tiers to reduce storage costs for data with changing access patterns.']),
        b('Read-heavy object access (streaming, websites) fits S3; low-latency random I/O from a single instance fits block storage; shared read-write access from many instances fits file storage.',
          'storage-decision',
          ['Object storage provides easy access to data through an application programming interface (API) over the internet and is well-suited to read-heavy workloads (such as streaming applications and services).',
           'Block storage offers high-performance storage that is direct-attached to a compute instance with low-latency access, making it suitable for applications that require fast and consistent I/O operations.']),
      ],
      services: ['Amazon S3', 'Amazon EFS', 'Amazon FSx'],
      design: [
        b('Cue: "access pattern is unknown or changes" → Intelligent-Tiering; "files not touched for months" → EFS lifecycle to IA or Archive; the S3 class details are in Cold Cellar.',
          'storage-decision',
          ['For example, use Amazon S3 Intelligent-Tiering for object data, or the FSx Intelligent-Tiering storage class for Amazon FSx for OpenZFS and Amazon FSx for Lustre workloads.']),
      ],
    },
    {
      id: '4.1-K11',
      concepts: [
        b('Object, file and block characteristics: object is API-accessed unstructured data and suits read-heavy workloads; file is a hierarchy of files and folders mountable over NFS or SMB; block is high-performance storage direct-attached to a compute instance. (Cargo Hall has the definitions.)',
          'storage-decision',
          ['Object — Object storage is a technology that stores and manages data in an unstructured format called objects.',
           'File system — File systems store data in a hierarchical structure of files and folders.',
           'Block storage offers high-performance storage that is direct-attached to a compute instance with low-latency access, making it suitable for applications that require fast and consistent I/O operations.']),
      ],
      services: ['Amazon S3', 'Amazon EFS', 'Amazon EBS'],
      design: [
        b('The type dictates the cost model: object storage does not need you to provision capacity ahead of time, EFS is fully elastic, so you do not provision capacity, and block volumes are provisioned by size and type (Block Warehouse).',
          'efs-what-is',
          ['Amazon Elastic File System (Amazon EFS) provides serverless, fully elastic file storage so that you can share file data without provisioning or managing storage capacity and performance.']),
      ],
    },
    {
      id: '4.1-S10',
      concepts: [
        b('To select a cost-effective storage solution, match the storage class to the access pattern. The storage decision guide gives S3 Intelligent-Tiering for object data and the EFS Archive class for cold file data as examples of matching classes to access patterns. As study guidance, settle the access method (API, shared file system, attached disk) and any named file system first, because the cheaper tier only applies within the service that fits.',
          ['storage-decision', 'efs-lifecycle'],
          ['storage-decision|For example, use Amazon S3 Intelligent-Tiering for object data, or the FSx Intelligent-Tiering storage class for Amazon FSx for OpenZFS and Amazon FSx for Lustre workloads.',
           'storage-decision|This class provides lower-cost storage for data that you access only a few times a year.',
           'efs-lifecycle|Lifecycle policies instruct lifecycle management when to transition files into and out of the EFS Infrequent Access (IA) and EFS Archive storage classes.']),
        b('Right-size block storage by choosing the lowest-cost type that meets the performance need (Block Warehouse), and use S3 File Gateway to give on-premises systems a cost-effective alternative to on-premises storage with the data in S3.',
          ['ebs-volume-types', 'sgw-file-s3'],
          ['ebs-volume-types|Scenarios where the lowest storage cost is important',
           'sgw-file-s3|A S3 File Gateway simplifies file storage in Amazon S3, integrates to existing applications through industry-standard file system protocols, and provides a cost-effective alternative to on-premises storage.']),
      ],
      services: ['Amazon S3', 'Amazon EFS', 'Amazon EBS', 'Amazon FSx'],
      design: [
        b('Scenario pattern: "archive that is rarely read" → S3 Glacier classes (Cold Cellar); "shared files rarely touched" → EFS Archive; "database disk" → EBS Provisioned IOPS or General Purpose; "thousands of clients reading objects" → S3 (with CloudFront for repeated reads).',
          ['storage-decision', 'cloudfront-what-is'],
          ['storage-decision|This class provides lower-cost storage for data that you access only a few times a year.',
           'cloudfront-what-is|You also get increased reliability and availability because copies of your files (also known as objects) are now held (or cached) in multiple edge locations around the world.']),
      ],
    },
  ],
  cues: [
    cue('shared file data, grows automatically, rarely used files should cost less', 'Amazon EFS with lifecycle management (IA and Archive classes)',
      b('EFS lifecycle management moves files to IA and Archive based on last access.', 'efs-lifecycle',
        ['Transition time is based on when the files were last accessed in the Standard storage class.'])),
    cue('object data with unknown or changing access patterns', 'S3 Intelligent-Tiering',
      b('AWS recommends S3 Intelligent-Tiering for object data with changing access patterns.', 'storage-decision',
        ['For example, use Amazon S3 Intelligent-Tiering for object data, or the FSx Intelligent-Tiering storage class for Amazon FSx for OpenZFS and Amazon FSx for Lustre workloads.'])),
    cue('Windows applications need SMB file shares', 'Amazon FSx for Windows File Server',
      b('FSx for Windows File Server provides fully managed Windows file servers.', 'fsx-windows',
        ['Amazon FSx for Windows File Server provides fully managed Microsoft Windows file servers, backed by a fully native Windows file system.'])),
    cue('high-performance computing or machine learning training needing fast file system', 'Amazon FSx for Lustre',
      b('Lustre is for workloads where speed matters.', 'fsx-lustre',
        ['You use Lustre for workloads where speed matters, such as machine learning, high performance computing (HPC), video processing, and financial modeling.'])),
    cue('migrate on-premises NetApp or ZFS file servers without changing applications', 'FSx for NetApp ONTAP / FSx for OpenZFS',
      b('ONTAP supports NFS and SMB and OpenZFS moves data from on-premises ZFS servers without changing application code.', 'fsx-openzfs',
        ['You can do this without changing your application code or how you manage data.'])),
    cue('block storage for one EC2 instance', 'Amazon EBS',
      b('EBS volumes attach to EC2 instances and are used like local drives.', 'ebs-what-is',
        ['Amazon EBS volumes — These are storage volumes that you attach to Amazon EC2 instances.'])),
  ],
  examples: [],
  confuse: ['ebs-efs-fsx'],
  azure: [
    {
      concept: 'Blob storage',
      aws: 'Amazon S3',
      mapping: b('Learn pairs Amazon S3 with Azure Blob storage as object storage, and its cool tier (cheaper than standard blob storage for infrequently accessed data that must be available immediately) with S3 Infrequent Access.',
        ['learn-storage', 's3-what-is'],
        ['learn-storage|For data that is infrequently accessed but must be available immediately when accessed, Azure Cool Blob Storage tier provides cheaper storage than standard blob storage.',
         'learn-storage|This storage tier is comparable to AWS S3 - Infrequent Access storage service.',
         's3-what-is|Amazon S3 is an object storage service that stores data as objects, hierarchical data, or tabular data within buckets.']),
      breaks: b('Learn pairs Azure Cool Blob Storage with S3 Infrequent Access. On AWS, S3 also offers Intelligent-Tiering, which AWS gives as an example for object data (Cold Cellar).',
        ['storage-decision', 'learn-storage'],
        ['storage-decision|For example, use Amazon S3 Intelligent-Tiering for object data, or the FSx Intelligent-Tiering storage class for Amazon FSx for OpenZFS and Amazon FSx for Lustre workloads.',
         'learn-storage|This storage tier is comparable to AWS S3 - Infrequent Access storage service.']),
    },
    {
      concept: 'Azure Files',
      aws: 'Amazon EFS and Amazon FSx',
      mapping: b('Learn lists Azure Files for shared file storage and names AWS EFS and the FSx family of managed file systems as the shared storage services on AWS.',
        ['learn-storage', 'efs-what-is'],
        ['learn-storage|Various shared storage services that AWS provides, like Elastic File System (EFS) and the FSx family of managed file systems.',
         'efs-what-is|Amazon EFS supports the Network File System version 4 (NFSv4.1 and NFSv4.0) protocol, so the applications and tools that you use today work seamlessly with Amazon EFS.']),
      breaks: b('On AWS the shared file services split by protocol and engine: EFS for NFS, and the FSx family for Windows, Lustre or ONTAP. Learn pairs FSx for Lustre with Azure Managed Lustre and FSx for NetApp ONTAP with Azure NetApp Files, while FSx for Windows File Server and EFS are listed against Azure Files.',
        ['efs-what-is', 'fsx-windows', 'learn-storage'],
        ['efs-what-is|Amazon EFS supports the Network File System version 4 (NFSv4.1 and NFSv4.0) protocol, so the applications and tools that you use today work seamlessly with Amazon EFS.',
         'fsx-windows|Amazon FSx for Windows File Server provides fully managed Microsoft Windows file servers, backed by a fully native Windows file system.',
         'learn-storage|Various shared storage services that AWS provides, like Elastic File System (EFS) and the FSx family of managed file systems.',
         'learn-storage|Elastic File System Files Provides a basic interface for creating and configuring file systems quickly and sharing common files.',
         'learn-storage|Amazon FSx for Windows File Server Files Provides a managed SMB file share that can work with Active Directory for access control.',
         'learn-storage|Amazon FSx for Lustre Azure Managed Lustre Provides a managed Lustre file system that integrates with object storage.',
         'learn-storage|Amazon FSx for NetApp ONTAP Azure NetApp Files Provides managed NetApp capabilities in the cloud.']),
    },
    {
      concept: 'Azure NetApp Files',
      aws: 'Amazon FSx for NetApp ONTAP',
      mapping: b('Learn pairs Amazon FSx for NetApp ONTAP with Azure NetApp Files, which provides managed NetApp capabilities in the cloud; on AWS, Amazon FSx for NetApp ONTAP is a fully managed service built on the NetApp ONTAP file system.',
        ['learn-storage', 'fsx-ontap'],
        ['learn-storage|Amazon FSx for NetApp ONTAP Azure NetApp Files Provides managed NetApp capabilities in the cloud.',
         'fsx-ontap|Amazon FSx for NetApp ONTAP is a fully managed service that provides highly reliable, scalable, high-performing, and feature-rich file storage built on NetApp\'s popular ONTAP file system.']),
      breaks: b('Learn also pairs FSx for NetApp ONTAP with Azure Elastic SAN for iSCSI or NVMe/TCP LUNs. On AWS, FSx for NetApp ONTAP supports both NFS and SMB protocols, including concurrent multi-protocol access to the same data.',
        ['storage-decision', 'learn-storage'],
        ['storage-decision|Amazon FSx for NetApp ONTAP supports both NFS and SMB protocols, including concurrent multi-protocol access to the same data.',
         'learn-storage|Amazon FSX for NetApp ONTAP iSCSI or NVMe/TCP LUNs Azure Elastic SAN Storage area network (SAN) capabilities in the cloud.']),
    },
  ],
};

export default notes;
