import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'throttle-lb-gate',
  overview: [
    b('Some network-edge choices change cost. A load balancer is billed while it exists, so the number and type of load balancers matters; and throttling decides how much unwanted or excess traffic ever reaches (and bills) the backend. Elastic Load Balancing distributes traffic across targets in one or more Availability Zones, and API Gateway lets you configure throttling and quotas to help protect your APIs from being overwhelmed by too many requests.',
      ['elb-what-is', 'elb-pricing', 'apigw-throttling'],
      ['elb-what-is|Elastic Load Balancing automatically distributes your incoming traffic across multiple targets, such as EC2 instances, containers, and IP addresses, in one or more Availability Zones.',
       'elb-pricing|You are charged for each hour or partial hour that an Application Load Balancer is running.',
       'apigw-throttling|You can configure throttling and quotas for your APIs to help protect them from being overwhelmed by too many requests.']),
  ],
  beyondProject: [
    b('Your project uses API Gateway. The SAA cost points are the choice of API type and where throttling is applied. REST APIs support more features than HTTP APIs, while HTTP APIs are designed with minimal features so that they can be offered at a lower price; caching is a REST API feature and not an HTTP API feature in the comparison table. Caching reduces the number of calls made to your endpoint.',
      ['apigw-http-vs-rest', 'apigw-caching'],
      ['apigw-http-vs-rest|REST APIs support more features than HTTP APIs, while HTTP APIs are designed with minimal features so that they can be offered at a lower price.',
       'apigw-http-vs-rest|Caching Yes No',
       'apigw-caching|With caching, you can reduce the number of calls made to your endpoint and also improve the latency of requests to your API.']),
  ],
  bullets: [
    {
      id: '4.4-K3',
      concepts: [
        b('A load balancer distributes workloads across multiple compute resources, monitors the health of its registered targets and routes traffic only to the healthy ones. Elastic Load Balancing scales the load balancer capacity automatically in response to changes in incoming traffic, so you do not size it yourself.',
          'elb-what-is',
          ['A load balancer distributes workloads across multiple compute resources, such as virtual servers.',
           'It monitors the health of its registered targets, and routes traffic only to the healthy targets.',
           'Elastic Load Balancing scales your load balancer capacity automatically in response to changes in incoming traffic.']),
        b('Load balancers are charged by time and by use. For an Application Load Balancer you are charged for each hour or partial hour that it is running, and each partial hour is billed as a full hour, and also for the Load Balancer Capacity Units (LCU) used per minute. The Network Load Balancer and Gateway Load Balancer are billed the same way with their own capacity units. An idle load balancer still costs its hourly charge, which is why Trusted Advisor has a check for idle load balancers.',
          ['elb-pricing', 'trusted-advisor-cost-checks'],
          ['elb-pricing|You are charged for each hour or partial hour that an Application Load Balancer is running.',
           'elb-pricing|Each partial Application Load Balancer hour used is billed as a full hour.',
           'elb-pricing|You are also charged for the number of Load Balancer Capacity Units (LCU) used per minute.',
           'elb-pricing|You are charged for each hour or partial hour that a Network Load Balancer is running.',
           'elb-pricing|You are charged for each hour or partial hour that a Gateway Load Balancer is running.',
           'elb-pricing|You are also charged for the number of Network Load Balancer Capacity Units (NLCU) used by Network Load Balancer per minute.',
           'trusted-advisor-cost-checks|Idle Load Balancers']),
        b('Cross-zone load balancing is a cost detail. With cross-zone load balancing enabled, each load balancer node distributes traffic across the registered targets in all enabled Availability Zones. With Application Load Balancers it is always enabled at the load balancer level, and AWS says you are not charged for that regional data transfer. With Network Load Balancers and Gateway Load Balancers it is disabled by default, and for a Network Load Balancer you are charged for regional data transfer between Availability Zones when you enable it.',
          ['elb-how-it-works', 'elb-faqs'],
          ['elb-how-it-works|When cross-zone load balancing is enabled, each load balancer node distributes traffic across the registered targets in all enabled Availability Zones.',
           'elb-how-it-works|With Application Load Balancers, cross-zone load balancing is always enabled at the load balancer level.',
           'elb-how-it-works|With Network Load Balancers and Gateway Load Balancers, cross-zone load balancing is disabled by default.',
           'elb-faqs|Since cross-zone load balancing is always on with Application Load Balancer, you are not charged for this type of regional data transfer.',
           'elb-faqs|Yes, you will be charged for regional data transfer between Availability Zones with Network Load Balancer when cross-zone load balancing is enabled.']),
        b('One Application Load Balancer can front several services. You can configure listener rules to route requests to different target groups based on the content of the application traffic, so separate load balancers per application are not needed when the traffic is HTTP or HTTPS.',
          'alb-intro',
          ['You can configure listener rules to route requests to different target groups based on the content of the application traffic.']),
      ],
      services: ['Elastic Load Balancing (ELB)'],
      design: [
        b('Cue: "many small web services, reduce load balancer cost" → one Application Load Balancer with listener rules to several target groups; "load balancer with no traffic" → remove it (Trusted Advisor idle check); choose the type for the traffic first (Elastic Mint and Express Interchange), then consolidate.',
          ['alb-intro', 'elb-pricing', 'trusted-advisor-cost-checks'],
          ['alb-intro|You can configure listener rules to route requests to different target groups based on the content of the application traffic.',
           'elb-pricing|You are charged for each hour or partial hour that an Application Load Balancer is running.',
           'trusted-advisor-cost-checks|Idle Load Balancers']),
      ],
    },
    {
      id: '4.4-S6',
      concepts: [
        b('API Gateway throttles requests using the token bucket algorithm, where a token counts for a request. It examines the rate and a burst of request submissions against all APIs in your account, per Region, and when submissions exceed the steady-state rate and burst limits it begins to throttle requests. Throttles and quotas are targets applied on a best-effort basis, not guaranteed ceilings.',
          'apigw-throttling',
          ['API Gateway throttles requests to your API using the token bucket algorithm, where a token counts for a request.',
           'Specifically, API Gateway examines the rate and a burst of request submissions against all APIs in your account, per Region.',
           'When request submissions exceed the steady-state request rate and burst limits, API Gateway begins to throttle requests.',
           'Both throttles and quotas are applied on a best-effort basis and should be thought of as targets rather than guaranteed request ceilings.']),
        b('Per-client limits are a REST API feature. In the API Gateway comparison table, API keys, per-client rate limiting and per-client usage throttling are Yes for REST APIs and No for HTTP APIs, and caching is also REST only. If a question needs per-customer limits or caching, an HTTP API is not enough, even though HTTP APIs are designed with minimal features so that they can be offered at a lower price.',
          'apigw-http-vs-rest',
          ['Features REST API HTTP API Custom domains Yes Yes API keys Yes No Per-client rate limiting Yes No Per-client usage throttling Yes No Developer portal Yes No',
           'Choose REST APIs if you need API management capabilities such as API keys and per-client rate limiting.',
           'REST APIs support more features than HTTP APIs, while HTTP APIs are designed with minimal features so that they can be offered at a lower price.',
           'Caching Yes No']),
        b('To limit individual clients, use a usage plan. A usage plan specifies who can access one or more deployed API stages and methods, and optionally sets the target request rate to start throttling requests. That protects the backend from one heavy client and ties access to the customers you intend to serve.',
          'apigw-usage-plans',
          ['A usage plan specifies who can access one or more deployed API stages and methods—and optionally sets the target request rate to start throttling requests.',
           'You can configure usage plans and API keys to allow customers to access selected APIs, and begin throttling requests to those APIs based on defined limits and quotas.']),
        b('Cheaper options sit beside throttling. Caching responses reduces the number of calls made to your endpoint. In Lambda, reserved concurrency sets both the maximum and minimum number of concurrent instances allocated to a function, which caps how far a function can scale, and there is no charge for configuring it; provisioned concurrency incurs additional charges.',
          ['apigw-caching', 'lambda-reserved', 'lambda-concurrency'],
          ['apigw-caching|With caching, you can reduce the number of calls made to your endpoint and also improve the latency of requests to your API.',
           'lambda-reserved|Reserved concurrency – This sets both the maximum and minimum number of concurrent instances allocated to your function.',
           'lambda-concurrency|There is no charge for configuring reserved concurrency for a function.',
           'lambda-concurrency|Configuring provisioned concurrency incurs charges to your AWS account.']),
      ],
      services: ['Amazon API Gateway', 'AWS Lambda'],
      design: [
        b('Cue: "protect the backend from a traffic spike" → API Gateway throttling; "limit each customer to a request rate" → usage plan; "cap how far a Lambda function scales" → reserved concurrency; "repeated identical requests" → API caching. Clients that exceed the limit receive 429 Too Many Requests responses, so the client side needs retry with backoff.',
          ['apigw-throttling', 'apigw-usage-plans', 'lambda-reserved'],
          ['apigw-throttling|When request submissions exceed the steady-state request rate and burst limits, API Gateway begins to throttle requests.',
           'apigw-usage-plans|You can configure usage plans and API keys to allow customers to access selected APIs, and begin throttling requests to those APIs based on defined limits and quotas.',
           'lambda-reserved|Reserved concurrency – This sets both the maximum and minimum number of concurrent instances allocated to your function.',
           'apigw-throttling|Clients may receive 429 Too Many Requests error responses at this point.']),
      ],
    },
  ],
  cues: [
    cue('many web services on one ALB to avoid paying for several load balancers', 'Application Load Balancer listener rules and target groups',
      b('An ALB routes to different target groups based on the content of the traffic.', 'alb-intro',
        ['You can configure listener rules to route requests to different target groups based on the content of the application traffic.'])),
    cue('load balancer with no traffic still costs money', 'Remove it (Trusted Advisor: Idle Load Balancers)',
      b('A load balancer is charged for each hour or partial hour that it is running.', 'elb-pricing',
        ['You are charged for each hour or partial hour that an Application Load Balancer is running.'])),
    cue('protect the backend from too many API requests', 'API Gateway throttling',
      b('API Gateway throttling and quotas help protect APIs from being overwhelmed.', 'apigw-throttling',
        ['You can configure throttling and quotas for your APIs to help protect them from being overwhelmed by too many requests.'])),
    cue('limit each API customer to an agreed request rate', 'API Gateway usage plan with API keys',
      b('A usage plan optionally sets the target request rate to start throttling requests.', 'apigw-usage-plans',
        ['A usage plan specifies who can access one or more deployed API stages and methods—and optionally sets the target request rate to start throttling requests.'])),
    cue('API needs the lowest price and few features', 'HTTP API',
      b('HTTP APIs are designed with minimal features so that they can be offered at a lower price.', 'apigw-http-vs-rest',
        ['REST APIs support more features than HTTP APIs, while HTTP APIs are designed with minimal features so that they can be offered at a lower price.'])),
    cue('stop one Lambda function consuming all concurrency', 'Reserved concurrency',
      b('Reserved concurrency sets the maximum and minimum number of concurrent instances for a function.', 'lambda-reserved',
        ['Reserved concurrency – This sets both the maximum and minimum number of concurrent instances allocated to your function.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Application Gateway',
      aws: 'Application Load Balancer',
      mapping: b('Learn says Azure Application Gateway provides application-level rule-based routing comparable to that of the AWS Application Load Balancer.',
        ['learn-networking', 'alb-intro'],
        ['learn-networking|Application Gateway provides application-level rule-based routing comparable to that of the AWS Application Load Balancer.',
         'alb-intro|You can configure listener rules to route requests to different target groups based on the content of the application traffic.']),
      breaks: b('On AWS, an Application Load Balancer is billed for each hour or partial hour it runs plus the Load Balancer Capacity Units it uses, and it can route requests to different target groups based on the content of the application traffic. Learn describes Application Gateway as comparable application-level rule-based routing.',
        ['elb-pricing', 'learn-networking', 'alb-intro'],
        ['elb-pricing|You are charged for each hour or partial hour that an Application Load Balancer is running.',
         'elb-pricing|You are also charged for the number of Load Balancer Capacity Units (LCU) used per minute.',
         'learn-networking|Application Gateway provides application-level rule-based routing comparable to that of the AWS Application Load Balancer.',
         'alb-intro|You can configure listener rules to route requests to different target groups based on the content of the application traffic.']),
    },
    {
      concept: 'Azure API Management',
      aws: 'Amazon API Gateway',
      mapping: b('The Learn hub pairs Amazon API Gateway with Azure API Management as turnkey services for publishing APIs to internal and external customers.',
        ['learn-hub', 'apigw-welcome'],
        ['learn-hub|Amazon API Gateway Azure API Management These services provide a turnkey solution for publishing APIs to internal and external customers.',
         'apigw-welcome|These tasks include traffic management, authorization and access control, monitoring, and API version management.']),
      breaks: b('Learn pairs Amazon API Gateway with Azure API Management as a turnkey solution for publishing APIs. On AWS, API Gateway throttles requests with a token bucket algorithm, and a usage plan can set the target request rate to start throttling requests.',
        ['apigw-throttling', 'apigw-usage-plans', 'learn-hub'],
        ['apigw-throttling|API Gateway throttles requests to your API using the token bucket algorithm, where a token counts for a request.',
         'apigw-usage-plans|A usage plan specifies who can access one or more deployed API stages and methods—and optionally sets the target request rate to start throttling requests.',
         'learn-hub|Amazon API Gateway Azure API Management These services provide a turnkey solution for publishing APIs to internal and external customers.']),
    },
  ],
};

export default notes;
