import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'transit-tariff',
  overview: [
    b('Connecting an on-premises network to AWS can use a dedicated line (Direct Connect), an encrypted tunnel over the internet (Site-to-Site VPN), a client-based VPN for individual users (Client VPN), or plain internet connections. They differ in setup time, bandwidth, consistency and how they are billed. Direct Connect has two billing elements, port hours and outbound data transfer, while a Site-to-Site VPN is charged for each VPN connection-hour plus standard data transfer charges.',
      ['dx-what-is', 'vpn-pricing', 'client-vpn'],
      ['dx-what-is|AWS Direct Connect has two billing elements: port hours and outbound data transfer.',
       'vpn-pricing|You also incur standard AWS data transfer charges for all data transferred via the VPN connection.',
       'client-vpn|AWS Client VPN is a managed client-based VPN service that enables you to securely access your AWS resources and resources in your on-premises network.']),
  ],
  bullets: [
    {
      id: '4.4-K5',
      concepts: [
        b('Direct Connect links your internal network to a Direct Connect location over a standard Ethernet fiber-optic cable. With this connection you can create virtual interfaces to public AWS services or to Amazon VPC, bypassing internet service providers in your network path. It is a private, dedicated line.',
          'dx-what-is',
          ['Direct Connect links your internal network to a Direct Connect location over a standard Ethernet fiber-optic cable.',
           'you can create virtual interfaces directly to public AWS services (for example, to Amazon S3) or to Amazon VPC, bypassing internet service providers in your network path.']),
        b('Site-to-Site VPN creates an IPsec VPN connection between your remote network and Amazon VPC over the internet. Each connection includes two tunnels you can use simultaneously for high availability.',
          ['connectivity-vpn', 's2s-vpn'],
          ['connectivity-vpn|Amazon VPC provides the option of creating an IPsec VPN connection between your remote networks and Amazon VPC over the internet',
           's2s-vpn|Each VPN connection includes two VPN tunnels which you can simultaneously use for high availability.']),
        b('Client VPN is a managed client-based VPN service for individual users, accessed from any location using an OpenVPN-based VPN client. It is the choice for remote users connecting to AWS or the on-premises network, not for connecting two networks to each other.',
          'client-vpn',
          ['AWS Client VPN is a managed client-based VPN service that enables you to securely access your AWS resources and resources in your on-premises network.',
           'With Client VPN, you can access your resources from any location using an OpenVPN-based VPN client.']),
        b('Private lines, dedicated lines and VPNs in exam wording map as follows: Direct Connect is the dedicated line, Site-to-Site VPN is the encrypted tunnel over the internet, and Client VPN is user-to-network access. The full Direct Connect and VPN comparison is in the Don\'t confuse section below.',
          ['dx-what-is', 'connectivity-vpn', 'client-vpn'],
          ['dx-what-is|Direct Connect links your internal network to a Direct Connect location over a standard Ethernet fiber-optic cable.',
           'connectivity-vpn|Amazon VPC provides the option of creating an IPsec VPN connection between your remote networks and Amazon VPC over the internet',
           'client-vpn|Managed service — Eliminates the operational burden of deploying and maintaining third-party remote access VPN solutions through complete AWS management.']),
      ],
      services: ['AWS Direct Connect', 'AWS Site-to-Site VPN', 'AWS Client VPN'],
      design: [
        b('Cue: "dedicated, private, consistent network path" → Direct Connect; "encrypted connection quickly over the internet" → Site-to-Site VPN; "remote employees need secure access" → Client VPN.',
          ['connectivity-dx', 'connectivity-vpn', 'client-vpn'],
          ['connectivity-dx|Direct Connect can reduce network costs, increase bandwidth throughput, and provide a more consistent network experience than internet-based connections.',
           'connectivity-vpn|Amazon VPC provides the option of creating an IPsec VPN connection between your remote networks and Amazon VPC over the internet',
           'client-vpn|With Client VPN, you can access your resources from any location using an OpenVPN-based VPN client.']),
      ],
    },
    {
      id: '4.4-S2',
      concepts: [
        b('Choose by cost and requirement together. Direct Connect can reduce network costs, increase bandwidth throughput and provide a more consistent network experience than internet-based connections, but it has its own billing: port hours, determined by capacity and connection type, and outbound data transfer. A VPN has no dedicated line, is charged per VPN connection-hour plus data transfer, and can be created over your existing internet connection.',
          ['connectivity-dx', 'dx-what-is', 'vpn-pricing'],
          ['connectivity-dx|Direct Connect can reduce network costs, increase bandwidth throughput, and provide a more consistent network experience than internet-based connections.',
           'dx-what-is|Port hour pricing is determined by capacity and connection type (dedicated connection or hosted connection).',
           'vpn-pricing|VPN connection-hour that your connection is provisioned and available.']),
        b('A Direct Connect connection is either dedicated, a physical Ethernet connection associated with a single customer that you request through the console, CLI or API, or hosted, a physical Ethernet connection that an AWS Direct Connect Partner provisions on your behalf. Hosted connections are requested from a partner in the Direct Connect Partner Program.',
          'dx-connection-types',
          ['Dedicated Connection: A physical Ethernet connection associated with a single customer.',
           'Hosted Connection: A physical Ethernet connection that an AWS Direct Connect Partner provisions on behalf of a customer.',
           'Customers request a hosted connection by contacting a partner in the AWS Direct Connect Partner Program, who provisions the connection.']),
        b('Hosted connections offer more port speeds than dedicated ones, including speeds below one gigabit per second, and for a hosted connection the Direct Connect Partner can change the speed. The rule that the port speed cannot be changed after the request applies to dedicated connections.',
          ['dx-hosted', 'dx-dedicated'],
          ['dx-hosted|Port speed For hosted connections, the possible values are 50 Mbps, 100 Mbps, 200 Mbps, 300 Mbps, 400 Mbps, 500 Mbps, 1 Gbps, 2 Gbps, 5 Gbps, 10 Gbps, and 25 Gbps.',
           'dx-dedicated|Port speed The possible values are 1 Gbps, 10 Gbps, 100 Gbps, and 400 Gbps.',
           'dx-dedicated|You can\'t change the port speed after you create the connection request.',
           'dx-dedicated|For hosted connections, your AWS Direct Connect Partner can change the speed.'],
          { allow: ['one'] }),
        b('Direct Connect is private but not encrypted. AWS Direct Connect does not encrypt your traffic in transit by default, so a requirement to encrypt traffic over Direct Connect needs a transit encryption option. Combining Direct Connect with a Site-to-Site VPN provides an IPsec-encrypted private connection.',
          'dx-encryption',
          ['AWS Direct Connect does not encrypt your traffic that is in transit by default.',
           'To encrypt the data in transit that traverses AWS Direct Connect, you must use the transit encryption options for that service.',
           'This combination provides an IPsec-encrypted private connection that also reduces network costs, increases bandwidth throughput, and provides a more consistent network experience than internet-based VPN connections.']),
        b('For critical workloads Direct Connect resiliency is a cost decision too: maximum resiliency uses separate connections that terminate on separate devices in more than one location, providing resiliency against device, connectivity and complete location failures. As study guidance, a Site-to-Site VPN over the internet is a possible backup path, since it is an IPsec VPN connection between your remote networks and Amazon VPC over the internet.',
          ['dx-resiliency', 'connectivity-vpn'],
          ['dx-resiliency|You can achieve maximum resiliency for critical workloads by using separate connections that terminate on separate devices in more than one location',
           'dx-resiliency|This model provides resiliency against device, connectivity, and complete location failures.',
           'connectivity-vpn|Amazon VPC provides the option of creating an IPsec VPN connection between your remote networks and Amazon VPC over the internet']),
        b('Setup time is part of the choice. For a Direct Connect connection created with the classic wizard, AWS says it can take up to 72 business hours to review your request and provision a port, and the physical cross-connect is separate. A Site-to-Site VPN is software configuration over an existing internet connection and needs no physical port.',
          ['dx-classic-connection', 'connectivity-vpn'],
          ['dx-classic-connection|It can take up to 72 business hours for AWS to review your request and provision a port for your connection.',
           'connectivity-vpn|Amazon VPC provides the option of creating an IPsec VPN connection between your remote networks and Amazon VPC over the internet']),
      ],
      services: ['AWS Direct Connect', 'AWS Site-to-Site VPN'],
      design: [
        b('Cue: "large, steady data volumes, consistent latency, lower transfer cost over time" → Direct Connect; "temporary or low-volume, needed this week" → VPN; "backup for Direct Connect" → VPN or a second connection. This is study guidance: the exam wording decides.',
          ['connectivity-dx', 'dx-resiliency'],
          ['connectivity-dx|Direct Connect can reduce network costs, increase bandwidth throughput, and provide a more consistent network experience than internet-based connections.',
           'dx-resiliency|You can achieve maximum resiliency for critical workloads by using separate connections that terminate on separate devices in more than one location']),
      ],
    },
    {
      id: '4.4-S7',
      concepts: [
        b('A Site-to-Site VPN has a bandwidth limit per tunnel: up to 1.25 Gbps per standard tunnel, and up to 5 Gbps per Large Bandwidth Tunnel, which is available for VPN connections attached to Transit Gateway or Cloud WAN. To get more bandwidth from standard tunnels, for VPN connections on a transit gateway you can aggregate multiple tunnels using ECMP, which requires dynamic routing and is not supported on VPN connections that use static routing.',
          ['vpn-tunnels', 'vpn-quotas'],
          ['vpn-tunnels|Standard bandwidth: Up to 1.25 Gbps per tunnel (default)',
           'vpn-tunnels|Large Bandwidth Tunnel (LBT): Up to 5 Gbps per tunnel',
           'vpn-tunnels|Large Bandwidth Tunnels are available only for VPN connections attached to Transit Gateway or Cloud WAN.',
           'vpn-quotas|For Site-to-Site VPN connections on a transit gateway, you can use ECMP to get higher VPN bandwidth by aggregating multiple VPN tunnels.',
           'vpn-quotas|To use ECMP, the VPN connection must be configured for dynamic routing.',
           'vpn-quotas|ECMP is not supported on VPN connections that use static routing.']),
        b('So "a single VPN compared with multiple VPNs" is a bandwidth question: one VPN connection has two tunnels that are for redundancy, and AWS says it is important to configure both tunnels; more throughput than a tunnel allows needs multiple tunnels or connections with ECMP, or a Large Bandwidth Tunnel. Each additional connection is charged per connection-hour plus data transfer.',
          ['vpn-tunnels', 'vpn-pricing'],
          ['vpn-tunnels|Each Site-to-Site VPN connection has two tunnels, with each tunnel using a unique public IP address.',
           'vpn-tunnels|It is important to configure both tunnels for redundancy.',
           'vpn-pricing|You also incur standard AWS data transfer charges for all data transferred via the VPN connection.']),
        b('Direct Connect speed is chosen from the port speeds offered when you create a dedicated connection, and you cannot change the port speed after you create the connection request; to change it you must create and configure a new connection. Size it to the measured traffic, because port-hour pricing depends on capacity. Port speeds available at each location are on the Direct Connect locations page.',
          ['dx-dedicated', 'dx-what-is'],
          ['dx-dedicated|Port speed The possible values are 1 Gbps, 10 Gbps, 100 Gbps, and 400 Gbps.',
           'dx-dedicated|You can\'t change the port speed after you create the connection request.',
           'dx-dedicated|To change the port speed, you must create and configure a new connection.',
           'dx-what-is|Port hour pricing is determined by capacity and connection type (dedicated connection or hosted connection).']),
      ],
      services: ['AWS Direct Connect', 'AWS Site-to-Site VPN'],
      design: [
        b('Cue: "need more than a single VPN tunnel can carry" → multiple tunnels with ECMP (VPN on a transit gateway, dynamic routing) or a Large Bandwidth Tunnel on a Transit Gateway attachment; "sustained high bandwidth" → Direct Connect with a port speed that fits the load.',
          ['vpn-tunnels', 'vpn-quotas', 'dx-dedicated'],
          ['vpn-tunnels|Large Bandwidth Tunnel (LBT): Up to 5 Gbps per tunnel',
           'vpn-quotas|For Site-to-Site VPN connections on a transit gateway, you can use ECMP to get higher VPN bandwidth by aggregating multiple VPN tunnels.',
           'dx-dedicated|Port speed The possible values are 1 Gbps, 10 Gbps, 100 Gbps, and 400 Gbps.']),
      ],
    },
  ],
  cues: [
    cue('dedicated private line from the data centre to AWS', 'AWS Direct Connect',
      b('Direct Connect links your network to a Direct Connect location over a standard Ethernet fiber-optic cable, bypassing internet service providers.', 'dx-what-is',
        ['Direct Connect links your internal network to a Direct Connect location over a standard Ethernet fiber-optic cable.'])),
    cue('encrypted connection to a VPC over the internet, quickly', 'AWS Site-to-Site VPN',
      b('Site-to-Site VPN creates an IPsec VPN connection over the internet.', 'connectivity-vpn',
        ['Amazon VPC provides the option of creating an IPsec VPN connection between your remote networks and Amazon VPC over the internet'])),
    cue('remote employees need secure access to VPC resources', 'AWS Client VPN',
      b('Client VPN is a managed client-based VPN service for secure access from any location.', 'client-vpn',
        ['With Client VPN, you can access your resources from any location using an OpenVPN-based VPN client.'])),
    cue('connection provisioned through an APN partner instead of ordering a physical port', 'Direct Connect hosted connection',
      b('A hosted connection is provisioned by a Direct Connect Partner on behalf of the customer.', 'dx-connection-types',
        ['Hosted Connection: A physical Ethernet connection that an AWS Direct Connect Partner provisions on behalf of a customer.'])),
    cue('VPN throughput exceeds a single tunnel', 'Multiple tunnels with ECMP (VPN on a transit gateway), or a Large Bandwidth Tunnel',
      b('ECMP aggregates multiple VPN tunnels for higher bandwidth on a transit gateway, and needs dynamic routing.', 'vpn-quotas',
        ['For Site-to-Site VPN connections on a transit gateway, you can use ECMP to get higher VPN bandwidth by aggregating multiple VPN tunnels.',
         'ECMP is not supported on VPN connections that use static routing.'])),
    cue('Direct Connect port speed needs to change later', 'Create a new connection (port speed cannot be changed)',
      b('You cannot change the port speed after you create the connection request.', 'dx-dedicated',
        ['You can\'t change the port speed after you create the connection request.'])),
  ],
  examples: [],
  confuse: ['direct-connect-vs-vpn'],
  azure: [
    {
      concept: 'ExpressRoute',
      aws: 'AWS Direct Connect',
      mapping: b('Learn pairs AWS Direct Connect with Azure ExpressRoute: AWS Direct Connect can link a network directly to AWS, and Azure provides similar site-to-site dedicated connections through ExpressRoute.',
        ['learn-networking', 'dx-what-is'],
        ['learn-networking|AWS Direct Connect can link a network directly to AWS.',
         'learn-networking|Azure provides similar site-to-site dedicated connections through ExpressRoute.',
         'dx-what-is|Direct Connect links your internal network to a Direct Connect location over a standard Ethernet fiber-optic cable.']),
      breaks: b('AWS Direct Connect has two billing elements, port hours and outbound data transfer, and for a dedicated connection you cannot change the port speed after you create the connection request. Learn describes ExpressRoute as similar site-to-site dedicated connections.',
        ['dx-what-is', 'dx-dedicated', 'learn-networking'],
        ['dx-what-is|AWS Direct Connect has two billing elements: port hours and outbound data transfer.',
         'dx-dedicated|You can\'t change the port speed after you create the connection request.',
         'learn-networking|Azure provides similar site-to-site dedicated connections through ExpressRoute.']),
    },
    {
      concept: 'VPN Gateway',
      aws: 'AWS Site-to-Site VPN',
      mapping: b('Learn pairs AWS Site-to-Site VPN with Azure VPN Gateway as solutions for connecting on-premises networks to the cloud, and compares their throughput.',
        ['learn-networking', 'vpn-tunnels'],
        ['learn-networking|Both AWS Site-to-Site VPN and Azure VPN Gateway are robust solutions for connecting on-premises networks to the cloud.',
         'vpn-tunnels|Each Site-to-Site VPN connection has two tunnels, with each tunnel using a unique public IP address.']),
      breaks: b('Learn gives VPN Gateway as higher throughput than Site-to-Site VPN. The AWS limits are per tunnel, for a standard tunnel and for a Large Bandwidth Tunnel, and using ECMP requires dynamic routing.',
        ['learn-networking', 'vpn-tunnels', 'vpn-quotas'],
        ['learn-networking|VPN Gateway offers higher throughput for certain configurations',
         'vpn-tunnels|Standard bandwidth: Up to 1.25 Gbps per tunnel (default)',
         'vpn-tunnels|Large Bandwidth Tunnel (LBT): Up to 5 Gbps per tunnel',
         'vpn-quotas|To use ECMP, the VPN connection must be configured for dynamic routing.']),
    },
  ],
};

export default notes;
