import type { Question } from '../../../src/content/types.ts';
import { mc, mr } from '../helpers.ts';

const questions: Question[] = [
  mc({
    id: 'blueprint-hall-001',
    building: 'blueprint-hall',
    bullets: ['2.1-K4'],
    d: 1,
    stem: 'A company runs a web application on Amazon EC2 instances in an Auto Scaling group. The architects want servers to be replaced at will without causing an availability impact. Which design principle BEST meets this requirement?',
    correct: ['Make the application stateless by offloading state, so requests need no data stored on an instance', 'A stateless design leaves no dependence on locally stored data on disk or in memory, so any server can be replaced at will.'],
    wrong: [
      ['Keep each visitor\'s session data in the memory of the instance that first served the visitor', 'State held in instance memory is lost when that instance is replaced, which creates the availability impact.'],
      ['Store the working data of each user on the local disk of the instance that handles the requests of that user', 'Data on a local disk is tied to one server, so replacing the server removes the data.'],
      ['Schedule instance replacements only during the lowest-traffic hours of the week', 'Servers still could not be replaced at will, and the state held on them would still be lost.'],
    ],
    slot: 0,
    evidence: [
      'waf-stateless|Systems should either not require state, or should offload state such that between different client requests, there is no dependence on locally stored data on disk and in memory.',
      'waf-stateless|This allows servers to be replaced at will without causing an availability impact.',
    ],
  }),
  mc({
    id: 'blueprint-hall-002',
    building: 'blueprint-hall',
    bullets: ['2.1-K4'],
    d: 2,
    stem: 'A retail web application runs on Amazon EC2 instances in an Auto Scaling group behind an Application Load Balancer. Shopping cart contents are held in the memory of each instance, so customers lose their carts when the group scales in. Any instance must be able to serve any customer, with the LEAST operational overhead. Which solution meets these requirements?',
    correct: ['Offload the cart data to an Amazon ElastiCache cache that all instances read from and write to', 'Session data is offloaded to an in-memory cache, so no instance holds state and any instance can serve any customer.'],
    wrong: [
      ['Enable sticky sessions on the target group so that each customer keeps returning to the same instance', 'Sticky sessions bind a session to one target, so the cart still lives on that instance and is lost when the instance is removed.'],
      ['Raise the minimum size of the Auto Scaling group so that scale-in events rarely occur', 'Instances can still fail or be replaced, and the application would still depend on state held on one server.'],
      ['Copy the cart data to the Amazon EBS root volume of each instance after every request', 'The data stays local to each instance, so another instance cannot serve the customer and the state is lost on replacement.'],
    ],
    slot: 1,
    evidence: [
      'waf-stateless|Offload session data to a database, cache, or external files.',
      'msa-data-store|Popular stores for session data are in-memory caches such as Memcached or Redis.',
      'alb-target-attrs|you can use the sticky session feature (also known as session affinity) to enable the load balancer to bind a user\'s session to a specific target.',
    ],
  }),
  mr({
    id: 'blueprint-hall-003',
    building: 'blueprint-hall',
    bullets: ['2.1-K4'],
    d: 2,
    stem: 'A company hosts a photo-sharing web application on Amazon EC2 instances behind an Application Load Balancer. Each instance keeps uploaded photos and user sessions on its own disk, which prevents horizontal scaling. Any instance must be able to serve any request. Which TWO actions BEST meet these requirements? (Choose two.)',
    correct: [
      ['Store the uploaded photos in Amazon S3 and have the application retrieve them when needed', 'Large unstructured data such as images is kept in Amazon S3 instead of on the instance, so no photo depends on one server.'],
      ['Move the user session data to an Amazon ElastiCache cache that every instance uses', 'Offloading session data to a cache removes the session state from the instances, so any instance can service any request.'],
    ],
    wrong: [
      ['Increase the instance size of every web server in the Auto Scaling group', 'A larger instance still holds its own state locally, so the application still cannot scale horizontally.'],
      ['Enable sticky sessions on the load balancer so each user always reaches the same instance', 'Sticky sessions bind a user to one target, so requests still depend on which instance they reach.'],
      ['Attach an additional Amazon EBS volume to each instance for photo storage', 'A volume attached to one instance is still local data, so only that instance can serve the photos.'],
    ],
    slots: [1, 3],
    evidence: [
      'waf-stateless|Consider using Amazon S3 to store large, unstructured data, such as images and documents.',
      'waf-stateless|Offload session data to a database, cache, or external files.',
      'waf-stateless|they can scale horizontally because any of the available compute resources (such as EC2 instances and AWS Lambda functions) can service any request.',
    ],
  }),
  mc({
    id: 'blueprint-hall-004',
    building: 'blueprint-hall',
    bullets: ['2.1-K4'],
    d: 2,
    stem: 'A company is splitting a monolithic order system into microservices owned by separate teams. All services still read and write one shared Amazon RDS database, and every schema change must be coordinated across the teams. The company wants each service to be developed and deployed independently. Which approach is MOST aligned with microservices design principles?',
    correct: ['Give each microservice its own data store and let the services exchange data through their APIs', 'Each component of a microservices application maintains its own data, which promotes independence and decentralization.'],
    wrong: [
      ['Keep the shared database and add one read replica endpoint for each team to use', 'All services would still depend on the same data and schema, so the teams remain coupled.'],
      ['Keep the shared database and put a dedicated in-memory cache in front of it for each of the services', 'A cache reduces read load but leaves the shared schema, so teams still cannot change their data independently.'],
      ['Move the shared database to a larger instance class so that every service has more capacity', 'More capacity does not remove the shared schema, so schema changes still need coordination across teams.'],
    ],
    slot: 2,
    evidence: [
      'msa-distributed-data|In traditional applications, all components often share a single database.',
      'msa-distributed-data|In contrast, each component of a microservices-based application maintains its own data, promoting independence and decentralization.',
      'waf-loose-coupling|Loosely coupled systems should avoid sharing data through shared databases or other forms of tightly coupled data storage, which can reintroduce tight coupling and hinder scalability.',
    ],
  }),
  mc({
    id: 'blueprint-hall-005',
    building: 'blueprint-hall',
    bullets: ['2.1-K4', '2.1-S1'],
    d: 3,
    stem: 'An order microservice, a payment microservice and an inventory microservice each keep their own database. One business operation spans all three, and if the payment step fails the stock that the inventory service already reserved must be released. The company wants the services to keep their data separate. Which design BEST handles this failure?',
    correct: ['Use the Saga pattern, with a coordinator that runs compensating actions to undo the completed steps', 'The Saga pattern coordinates a series of compensating actions, so completed work is undone while each service keeps its own data.'],
    wrong: [
      ['Merge the tables of all three services into one database so that a single transaction can roll back', 'A shared database removes the independence of the services, which the company wants to keep.'],
      ['Let the inventory service read the payment database directly to detect failed payments', 'Reading another service\'s data store couples the services and does not coordinate undoing the completed steps.'],
      ['Retry the failed payment step without limit so that no earlier step ever has to be undone', 'Retries cannot guarantee success, so a permanently failed step still leaves completed work that must be undone.'],
    ],
    slot: 3,
    evidence: [
      'msa-distributed-data|Sometimes, business operations require multiple microservices to work together.',
      'msa-distributed-data|If one part fails, you might have to undo some completed tasks.',
      'msa-distributed-data|The Saga pattern helps manage this by coordinating a series of compensating actions.',
    ],
  }),
  mc({
    id: 'blueprint-hall-006',
    building: 'blueprint-hall',
    bullets: ['2.1-K4'],
    d: 3,
    stem: 'A company is building a microservice that stores and retrieves device profiles by a single key. The service does one thing, needs no table joins, and receives large activity spikes of short duration that make capacity planning difficult. The company wants the data store that needs the LEAST capacity planning. Which solution meets these requirements?',
    correct: ['An Amazon DynamoDB table that uses on-demand capacity', 'A simplified data model suits NoSQL, and on-demand capacity serves requests instantly without capacity planning.'],
    wrong: [
      ['An Amazon DynamoDB table with provisioned throughput set to the typical daily load', 'Provisioned throughput must be planned in advance, which is hard when spikes are large and short.'],
      ['An Amazon RDS for MySQL DB instance sized for the peak load, with one read replica', 'A relational instance sized for peak still needs capacity planning, and the service has no need for joins.'],
      ['An Amazon RDS for PostgreSQL Multi-AZ DB instance that is resized after each spike', 'Resizing after each spike is manual capacity planning and reacts too late for short spikes.'],
    ],
    slot: 0,
    evidence: [
      'msa-data-store|Because individual microservices are designed to do one thing well, they typically have a simplified data model that might be well suited to NoSQL persistence.',
      'msa-data-store|However, there are cases where capacity planning is difficult or not possible because of large activity spikes of short duration in your application.',
      'msa-data-store|DynamoDB on-demand is capable of serving thousands of requests per second instantly without capacity planning.',
    ],
  }),
  mc({
    id: 'blueprint-hall-007',
    building: 'blueprint-hall',
    bullets: ['2.1-K10'],
    d: 1,
    stem: 'A company is designing a three-tier web application. The presentation tier is a set of static files and a JavaScript single-page application that calls backend APIs. The company wants to serve the presentation tier with no web servers to manage. Which solution BEST meets these requirements?',
    correct: ['Store the files in Amazon S3 and serve them through Amazon CloudFront', 'Static web content can be served from Amazon S3 and Amazon CloudFront, so no web servers are needed.'],
    wrong: [
      ['Run a web server on Amazon EC2 instances in an Auto Scaling group that serves the files', 'The company would have to patch and manage the instances, which it wants to avoid.'],
      ['Run a web server in AWS Fargate containers that serves the files from the image', 'Containers still need a web server to build, deploy and maintain, which the company wants to avoid.'],
      ['Return each file from an AWS Lambda function behind an Amazon API Gateway API', 'Static content does not need function code for every request, and this adds components to manage.'],
    ],
    slot: 1,
    evidence: [
      'msa-ui|Modern web applications often use JavaScript frameworks to develop single-page applications that communicate with backend APIs.',
      'msa-ui|Static web content can be served using Amazon Simple Storage Service (Amazon S3) and Amazon CloudFront.',
    ],
  }),
  mc({
    id: 'blueprint-hall-008',
    building: 'blueprint-hall',
    bullets: ['2.1-K10'],
    d: 1,
    stem: 'A company is designing the data tier of a three-tier order system. The data consists of structured business objects, and the team needs to join several tables with queries instead of writing join logic in the application. Which data store BEST fits this data tier?',
    correct: ['A relational database on Amazon RDS', 'Relational databases are popular for structured data and business objects, and they allow tables to be joined.'],
    wrong: [
      ['Amazon DynamoDB tables with a partition key', 'DynamoDB cannot join tables, so the join logic would have to be implemented in the application.'],
      ['An in-memory Amazon ElastiCache cluster', 'A cache sits between the application servers and a database to reduce read load, and it is not the data tier itself.'],
      ['Objects stored in an Amazon S3 bucket', 'S3 stores objects and does not run queries that join tables the way a relational database does.'],
    ],
    slot: 2,
    evidence: [
      'msa-data-store|Relational databases are still very popular to store structured data and business objects.',
      "msa-data-store|It is important to understand that NoSQL databases have different access patterns than relational databases.",
      "msa-data-store|If this is necessary, the logic has to be implemented in the application.",
    ],
  }),
  mc({
    id: 'blueprint-hall-009',
    building: 'blueprint-hall',
    bullets: ['2.1-K10'],
    d: 2,
    stem: 'The application servers of a three-tier application repeatedly read the same product-catalog records from an Amazon RDS database. Database read load is high and page latency is rising. The company wants to reduce the read load on the database and improve latency. Which solution meets these requirements MOST effectively?',
    correct: ['Place an Amazon ElastiCache cache between the application servers and the database', 'A cache between the application servers and a database reduces the read load on the database and can improve latency.'],
    wrong: [
      ['Convert the database to a Multi-AZ DB instance deployment and read from the standby', 'The standby of a Multi-AZ DB instance deployment cannot serve read traffic.'],
      ['Raise the maximum size of the Auto Scaling group so that more application servers run', 'More application servers would send even more read queries to the same database.'],
      ['Put an Application Load Balancer between the application servers and the database', 'A load balancer distributes traffic across targets and does not keep copies of frequently read records.'],
    ],
    slot: 3,
    evidence: [
      'msa-data-store|Putting a cache between application servers and a database is a common mechanism for reducing the read load on the database, which, in turn, may allow resources to be used to support more writes.',
      'msa-data-store|Caches can also improve latency.',
      "rds-multi-az-instance|You can't use a standby replica to serve read traffic.",
    ],
  }),
  mr({
    id: 'blueprint-hall-010',
    building: 'blueprint-hall',
    bullets: ['2.1-K10', '2.1-S1'],
    d: 3,
    stem: 'A company runs a three-tier web application. The web servers also serve large static assets, the application tier is one large Amazon EC2 instance that is saturated at peak, and the Amazon RDS database is overloaded by repeated reads. The company wants each tier to scale independently and to be MOST resilient to the loss of an Availability Zone. Which THREE changes meet these requirements? (Choose three.)',
    correct: [
      ['Run the application tier in an Auto Scaling group across Availability Zones behind an Application Load Balancer', 'The load balancer distributes traffic across targets in more than one Availability Zone, so the tier scales out and survives the loss of one zone.'],
      ['Place an Amazon ElastiCache cache between the application tier and the database', 'A cache reduces the read load on the database, so the data tier is no longer overloaded by repeated reads.'],
      ['Serve the static assets from Amazon S3 through Amazon CloudFront', 'Static content leaves the web servers, so the presentation tier no longer has to scale with asset traffic.'],
    ],
    wrong: [
      ['Move the web, application and database tiers onto one larger Amazon EC2 instance', 'One instance cannot scale each tier independently and is a single point of failure for all tiers.'],
      ['Resize the single application instance to the largest available instance type', 'Scaling one instance up does not add capacity in a second Availability Zone and leaves the tier a single point of failure.'],
      ['Run a database copy on each application server to avoid network calls to the data tier', 'Copies on each server break the separation of tiers, so the tiers no longer scale independently.'],
    ],
    slots: [0, 3, 5],
    evidence: [
      'elb-what-is|Elastic Load Balancing automatically distributes your incoming traffic across multiple targets, such as EC2 instances, containers, and IP addresses, in one or more Availability Zones.',
      'msa-data-store|Putting a cache between application servers and a database is a common mechanism for reducing the read load on the database, which, in turn, may allow resources to be used to support more writes.',
      'msa-ui|Static web content can be served using Amazon Simple Storage Service (Amazon S3) and Amazon CloudFront.',
    ],
  }),
  mc({
    id: 'blueprint-hall-011',
    building: 'blueprint-hall',
    bullets: ['2.1-K10', '2.1-S1'],
    d: 2,
    stem: 'A web tier calls an application tier synchronously over HTTP to generate PDF reports. During traffic spikes the application tier is overwhelmed and the web tier returns errors, although users do not need the report immediately. The company wants spikes in one tier to stop failing the other with the LEAST rework. Which solution BEST meets these requirements?',
    correct: ['Add an Amazon SQS queue between the tiers and have the application tier take requests at its own pace', 'An intermediate queue makes the interaction asynchronous and buffers requests, so spikes no longer fail the web tier.'],
    wrong: [
      ['Raise the idle timeout of the load balancer so that the web tier waits much longer for every slow response from the application tier', 'The web tier would still depend on an immediate response, and a saturated application tier would still fail requests.'],
      ['Add a second Application Load Balancer in front of the same application tier', 'The calls remain synchronous, so the application tier is still overwhelmed during spikes.'],
      ['Move the application tier to one larger Amazon EC2 instance that can absorb the spikes', 'One larger instance has a fixed limit and the direct, synchronous coupling between the tiers remains.'],
    ],
    slot: 0,
    evidence: [
      'waf-loose-coupling|To further improve resiliency through loose coupling, make component interactions asynchronous where possible.',
      'waf-loose-coupling|Directly invoking APIs between workload tiers with no capability of failover or asynchronous processing of the request.',
      'sqs-what-is|Scalability – Amazon SQS can process each buffered request independently, scaling transparently to handle any load increases or spikes without any provisioning instructions.',
    ],
  }),
  mc({
    id: 'blueprint-hall-012',
    building: 'blueprint-hall',
    bullets: ['2.1-S1'],
    d: 2,
    stem: 'When a customer places an order, the inventory, billing and shipping services must each react to it. The order service should not know which services consume the event, and new consumers must be added without changing it. The company wants the MOST loosely coupled design with the LEAST custom code. Which solution meets these requirements?',
    correct: ['Publish an order-placed event to an Amazon EventBridge event bus and let each service subscribe with its own rule', 'An event router filters and pushes events to consumers, so the producer stays decoupled and consumers can be added without custom code.'],
    wrong: [
      ["Have the order service call each downstream service's Amazon API Gateway endpoint in turn", 'The order service would know every consumer and need code changes whenever a consumer is added.'],
      ['Have each downstream service poll the order database on a schedule for new rows', 'Polling needs custom code in every service and couples each of them to the order database.'],
      ['Merge the services into one application on a single Amazon EC2 instance that makes in-process calls between the modules', 'One application with in-process calls is tightly coupled and cannot be updated or scaled independently.'],
    ],
    slot: 1,
    evidence: [
      'eda-overview|Producer services and consumer services are decoupled, which allows them to be scaled, updated, and deployed independently.',
      'eda-overview|You no longer need to write custom code to poll, filter, and route events; the event router will automatically filter and push events to consumers.',
    ],
  }),
  mr({
    id: 'blueprint-hall-013',
    building: 'blueprint-hall',
    bullets: ['2.1-S1', '2.1-K4'],
    d: 2,
    stem: 'A start-up is building a stateless microservices backend that must follow serverless principles: no infrastructure to provision or manage, and capacity that scales automatically with use. The team wants the LEAST operational overhead. Which TWO compute options meet these requirements? (Choose two.)',
    correct: [
      ['AWS Lambda functions', 'Lambda is a serverless compute service that suits stateless services, with no servers to provision or manage.'],
      ['AWS Fargate to run the containers of the services', 'Fargate is a serverless compute option for containers, so there are no instances to provision or manage.'],
    ],
    wrong: [
      ['Amazon EC2 instances in an Auto Scaling group that the team patches', 'The team must still provision and manage instances, which breaks the serverless principle of no infrastructure to manage.'],
      ['A cluster of self-managed Amazon EC2 container instances', 'The team would manage and patch the instances that host the containers.'],
      ['Amazon EC2 Dedicated Hosts that run the services', 'Dedicated Hosts are physical servers that the team provisions and manages.'],
    ],
    slots: [2, 3],
    evidence: [
      'msa-whitepaper|Serverless is characterized by the following principles: No infrastructure to provision or manage Automatically scaling by unit of consumption "Pay for value" billing model Built-in availability and fault tolerance Event Driven Architecture (EDA)',
      'waf-stateless|Once designed to be stateless, you can then use serverless compute services, such as AWS Lambda or AWS Fargate.',
    ],
  }),
  mc({
    id: 'blueprint-hall-014',
    building: 'blueprint-hall',
    bullets: ['2.1-S1'],
    d: 3,
    tags: ['trap:sqs-sns-eventbridge-kinesis'],
    stem: 'A company builds an order system with event sourcing: every change is recorded as an event, which creates a timeline of system state for auditing and lets several parts of the application react to the same events. The company needs a central event store and durable storage for all event records. Which combination of AWS services BEST meets these requirements?',
    correct: ['Amazon Kinesis Data Streams as the central event store and Amazon S3 for durable storage of the event records', 'Kinesis Data Streams can serve as the central event store, several applications can consume it independently, and S3 stores the records durably.'],
    wrong: [
      ['An Amazon SQS standard queue as the event store and Amazon EBS snapshots for durable storage', 'Consumers delete a message after processing it, so a queue does not keep a timeline that several parts can react to.'],
      ['An Amazon SNS topic as the central event store and Amazon S3 for the durable storage of the event records', 'An SNS topic delivers messages to subscribers and is not an event store that keeps the timeline of events.'],
      ['An Amazon EventBridge pipe as the event store and Amazon ElastiCache for durable storage', 'A pipe connects one source to one target and does not store events, and an in-memory cache is not durable storage for all records.'],
    ],
    slot: 2,
    evidence: [
      'msa-distributed-data|Every change in the application is recorded as an event, creating a timeline of the system\'s state.',
      'msa-distributed-data|As you can see in Figure 7, Amazon Kinesis Data Streams can serve as your central event store, while Amazon S3 provides a durable storage for all event records.',
      'kinesis-streams|Multiple Kinesis Data Streams applications can consume data from a stream, so that multiple actions, like archiving and processing, can take place concurrently and independently.',
    ],
  }),
  mc({
    id: 'blueprint-hall-015',
    building: 'blueprint-hall',
    bullets: ['2.1-K4', '2.1-S1'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A three-person team is building an internal tool with low, predictable traffic and a simple domain. A colleague proposes splitting it into many microservices from the start. Which guidance from AWS is MOST appropriate for this decision?',
    correct: ['Weigh scale, complexity and the use case, because a monolith or another approach can be more appropriate', 'AWS says the choice between microservices and a monolith is made case by case, and alternatives may be more appropriate.'],
    wrong: [
      ['Always choose microservices, because they are the only architecture that can scale', 'AWS does not say microservices always win, and it says other approaches may be more appropriate in some cases.'],
      ['Always choose a monolith for teams of fewer than five people, whatever the use case', 'AWS recommends deciding case by case on scale, complexity and use case, not by a fixed team size.'],
      ['Choose microservices only if the application already uses a relational database in the data tier of the design', 'The data store is not the deciding factor, and AWS points to scale, complexity and use case.'],
    ],
    slot: 3,
    evidence: [
      'msa-whitepaper|Monolithic architecture or alternative approaches may be more appropriate in some cases.',
      'msa-whitepaper|Deciding between microservices or monoliths should be made on a case-by-case basis, considering factors like scale, complexity, and specific use cases.',
    ],
  }),
  mc({
    id: 'blueprint-hall-016',
    building: 'blueprint-hall',
    bullets: ['2.1-K4', '2.1-K10'],
    d: 3,
    tags: ['mock-reserve'],
    stem: 'The web tier of a three-tier application keeps session data in instance memory and relies on Application Load Balancer sticky sessions. The company wants to run the web tier on Amazon EC2 Spot Instances to reduce cost, without logging users out when an instance is interrupted. Which solution meets these requirements MOST cost-effectively?',
    correct: ['Move the session data to an Amazon ElastiCache cache and run the stateless web tier on Spot Instances', 'With state offloaded, an interrupted instance loses no sessions, and Spot Instances suit applications that can be interrupted.'],
    wrong: [
      ['Keep the sticky sessions and lengthen the duration of the stickiness cookie on the load balancer target group', 'Stickiness still binds each session to one instance, and an interrupted instance takes its sessions with it.'],
      ['Keep the session data in memory and run the web tier on Spot Instances with a larger instance type', 'A larger instance is still interrupted when capacity is needed back, and its memory is lost with it.'],
      ['Move the session data to the local disk of each Spot Instance so that it survives restarts', 'Local disk data is tied to the instance and does not move to another instance when one is interrupted.'],
    ],
    slot: 0,
    evidence: [
      'waf-stateless|A stateless architecture decouples user data and offloads the session data.',
      'ec2-spot|Spot Instances are a cost-effective choice if you can be flexible about when your applications run and if your applications can be interrupted.',
      'alb-target-attrs|you can use the sticky session feature (also known as session affinity) to enable the load balancer to bind a user\'s session to a specific target.',
    ],
  }),
];

export default questions;
