import type { Question } from '../../../src/content/types.ts';
import { mc, mr } from '../helpers.ts';

const questions: Question[] = [
  mc({
    id: 'cache-edge-breakwater-001',
    building: 'cache-edge-breakwater',
    bullets: ['2.1-K7'],
    d: 1,
    stem: 'A company serves product images through an Amazon CloudFront distribution with an Amazon S3 bucket as the origin. The images almost never change. The company wants to reduce the number of requests that reach the origin and speed up delivery to viewers. What should the company do?',
    correct: ['Increase the cache duration for the images', 'A longer cache duration makes it more likely that files are served from the edge location and reduces the load on the origin.'],
    wrong: [
      ['Set the cache duration for the images to zero', 'A duration of zero makes every request go back to the origin, which increases the load that the company wants to reduce.'],
      ['Invalidate all of the images every hour', 'Every invalidated file is fetched from the origin again, which creates origin requests that a longer cache duration avoids.'],
      ['Add a second S3 bucket as an additional origin for the same images', 'A second origin does not keep copies at the edge locations, so viewers are not served faster and requests still reach an origin.'],
    ],
    slot: 0,
    tags: ['trap:cloudfront-vs-global-accelerator'],
    evidence: [
      'cloudfront-expiration|Increasing the duration means that your users get better performance because your files are more likely to be served directly from the edge cache.',
      'cloudfront-expiration|A longer duration also reduces the load on your origin.',
    ],
  }),
  mc({
    id: 'cache-edge-breakwater-002',
    building: 'cache-edge-breakwater',
    bullets: ['2.1-K7'],
    d: 2,
    tags: ['placement-eligible', 'trap:cloudfront-vs-global-accelerator'],
    stem: 'A company runs a multiplayer game on Network Load Balancers in two AWS Regions. Players connect over UDP. Partner firewalls must allow-list a small fixed set of IP addresses, and traffic must move quickly to the healthy Region if one fails. Which solution BEST meets these requirements?',
    correct: ['Create an AWS Global Accelerator accelerator with both Network Load Balancers as endpoints', 'An accelerator provides static anycast IP addresses as the entry point, handles UDP, and routes only to healthy regional endpoints.'],
    wrong: [
      ['Create an Amazon CloudFront distribution with both Network Load Balancers as origins', 'CloudFront speeds up web content with caching at edge locations, while this need is fixed addresses and fast failover for UDP game traffic.'],
      ['Create Amazon Route 53 failover records that point to the DNS names of the two load balancers', 'DNS answers can be cached by client devices and resolvers for long periods, and the load balancer addresses are not a fixed set.'],
      ['Place a Gateway Load Balancer in each Region in front of the game servers', 'A Gateway Load Balancer deploys virtual appliances and does not give clients fixed addresses or fail traffic over between Regions.'],
    ],
    slot: 1,
    evidence: [
      'ga-faq|Global Accelerator is a good fit for non-HTTP use cases, such as gaming (UDP), IoT (MQTT), or Voice over IP, as well as for HTTP use cases that specifically require static IP addresses or deterministic, fast regional failover.',
      'ga-faq|AWS Global Accelerator automatically checks the health of your applications and routes user traffic only to healthy application endpoints.',
      'ga-faq|Some client devices and internet resolvers cache DNS answers for long periods of time.',
    ],
  }),
  mc({
    id: 'cache-edge-breakwater-003',
    building: 'cache-edge-breakwater',
    bullets: ['2.1-K7'],
    d: 2,
    tags: ['placement-eligible', 'trap:cloudfront-vs-global-accelerator'],
    stem: 'A company hosts a static website in an Amazon S3 bucket. Visitors around the world report slow loading of images and scripts, and many visitors request the same files. The company wants the lowest latency for repeat visits with the LEAST operational overhead. Which solution meets these requirements?',
    correct: ['Create an Amazon CloudFront distribution that uses the S3 bucket as its origin', 'Files are cached at edge locations close to viewers, so repeat requests are answered at the edge instead of from the bucket.'],
    wrong: [
      ['Create an AWS Global Accelerator accelerator that uses the S3 bucket as its endpoint', 'The endpoints of a standard accelerator are load balancers, EC2 instances and Elastic IP addresses, and it proxies packets rather than caching files.'],
      ['Replicate the bucket to every Region and add Amazon Route 53 latency records', 'This works but needs a bucket, replication and records for every Region to manage, which is more overhead than a CDN.'],
      ['Place an Amazon ElastiCache cluster in front of the bucket for the website files', 'An in-memory cache sits between an application and its data store inside a Region and does not bring content closer to viewers around the world.'],
    ],
    slot: 2,
    evidence: [
      'cloudfront-what-is|You also get increased reliability and availability because copies of your files (also known as objects) are now held (or cached) in multiple edge locations around the world.',
      'ga-what-is|Endpoints for standard accelerators can be Network Load Balancers, Application Load Balancers, Amazon EC2 instances, or Elastic IP addresses that are located in one AWS Region or multiple Regions.',
      'ga-faq|Global Accelerator improves performance for a wide range of applications over TCP or UDP by proxying packets at the edge to applications running in one or more AWS Regions.',
    ],
  }),
  mc({
    id: 'cache-edge-breakwater-004',
    building: 'cache-edge-breakwater',
    bullets: ['2.1-K7'],
    d: 2,
    tags: ['placement-eligible'],
    stem: 'A website is delivered through Amazon CloudFront from an Amazon S3 origin. Every release changes many JavaScript and CSS files, and visitors must get the new versions immediately after release. The company wants to keep the long cache duration for all other files and pay the LOWEST cost with the LEAST effort. Which approach meets these requirements?',
    correct: ['Put a version identifier in the file names and update the links in the pages to the new names', 'New names are new objects, so viewers get them at once without waiting for expiry or paying for invalidations, and other files stay cached.'],
    wrong: [
      ['Delete the old objects from the S3 bucket and upload the new ones under the same names', 'CloudFront continues to show viewers the cached content until the files expire, so visitors would keep receiving old versions.'],
      ['Set the cache duration to zero for the whole distribution', 'This removes the long cache duration the company wants to keep for all other files, and every request would reach the origin.'],
      ['Invalidate every file in the distribution after each release', 'This also removes the unchanged files from the cache and has to be repeated each release, while versioned names avoid invalidation fees.'],
    ],
    slot: 3,
    evidence: [
      'cloudfront-versioning|To update existing content that CloudFront is set up to distribute for you, we recommend that you use a version identifier in file names or in folder names.',
      "cloudfront-versioning|With versioning, you don't have to wait for an object to expire before CloudFront begins to serve a new version of it, and you don't have to pay for object invalidation.",
      'cloudfront-versioning|However, CloudFront will continue to show viewers content from the edge cache until the files expire.',
    ],
  }),
  mc({
    id: 'cache-edge-breakwater-005',
    building: 'cache-edge-breakwater',
    bullets: ['2.1-K7', '2.1-K3'],
    d: 3,
    tags: ['placement-eligible'],
    stem: 'A web application is delivered through Amazon CloudFront with an Application Load Balancer as the origin. Images under /images/ never change after upload. HTML pages under /pages/ change every few minutes and must not be stale for longer than that. The company wants to cut origin load as far as possible without serving outdated pages. Which configuration BEST meets these requirements?',
    correct: ['Create one cache behavior per path pattern, with a long TTL for /images/ and a short TTL for /pages/', 'Cache duration is set per path pattern in a cache behavior, so images get a long duration and pages stay fresh while still being cached briefly.'],
    wrong: [
      ['Use one cache behavior with a long TTL for all paths', 'A long duration for the HTML pages means viewers could see outdated pages for far longer than the few minutes allowed.'],
      ['Use one cache behavior with a TTL of zero for all paths', 'The images would be fetched from the origin on every request, so the origin load is not reduced.'],
      ['Serve /pages/ directly from the origin and use CloudFront only for /images/', 'The pages would never be cached, so their requests all reach the origin instead of being absorbed by a short TTL at the edge.'],
    ],
    slot: 0,
    evidence: [
      'cloudfront-expiration|To change the cache duration for all files that match the same path pattern, you can change the CloudFront settings for Minimum TTL, Maximum TTL, and Default TTL for a cache behavior.',
      'cloudfront-expiration|A longer duration also reduces the load on your origin.',
      'cloudfront-expiration|By reducing the duration, you can serve dynamic content.',
    ],
  }),
  mc({
    id: 'cache-edge-breakwater-006',
    building: 'cache-edge-breakwater',
    bullets: ['2.1-K3'],
    d: 2,
    tags: ['placement-eligible'],
    stem: 'A mobile game stores player profiles in Amazon DynamoDB. A small number of popular profiles are read many times per second, eventually consistent reads are acceptable, and the game needs microsecond read latency. The company wants the LEAST change to the application code. Which solution BEST meets these requirements?',
    correct: ['Create a DynamoDB Accelerator (DAX) cluster and point the DynamoDB client at it', 'DAX is a DynamoDB-compatible in-memory cache that serves eventually consistent reads in microseconds and needs only minimal changes to use.'],
    wrong: [
      ['Add an Amazon ElastiCache cluster and write code that checks the cache before each DynamoDB request', 'ElastiCache can cache the data, but the application must implement the cache logic itself, which is more code change than DAX.'],
      ['Increase the provisioned read capacity of the table', 'More read capacity adds throughput and does not move reads from single-digit milliseconds to microseconds.'],
      ['Convert the table to a DynamoDB global table in a second Region', 'Replicating the table to another Region does not add an in-memory cache, so reads stay at DynamoDB response times.'],
    ],
    slot: 1,
    evidence: [
      'dax|As an in-memory cache, DAX reduces the response times of eventually consistent read workloads by an order of magnitude from single-digit milliseconds to microseconds.',
      'dax|DAX reduces operational and application complexity by providing a managed service that is API-compatible with DynamoDB.',
      'dax|Therefore, it requires only minimal functional changes to use with an existing application.',
    ],
  }),
  mc({
    id: 'cache-edge-breakwater-007',
    building: 'cache-edge-breakwater',
    bullets: ['2.1-K3'],
    d: 3,
    tags: ['placement-eligible'],
    stem: 'A serverless API uses an Amazon API Gateway REST API, AWS Lambda and Amazon DynamoDB. A GET method returns the same product data to every user, and the same few products are requested again and again. The company wants fewer Lambda invocations, fewer DynamoDB reads and lower response latency for these repeated requests, with the LEAST code change. Which solution BEST meets these requirements?',
    correct: ['Enable API caching on the API stage with a suitable time-to-live', 'The stage cache answers repeated requests from cached responses instead of calling the endpoint, so neither Lambda nor DynamoDB is used for them.'],
    wrong: [
      ['Create a DynamoDB Accelerator (DAX) cluster in front of the table', 'DAX speeds up DynamoDB reads, but every request still invokes the Lambda function, so the invocations are not reduced.'],
      ['Configure provisioned concurrency for the Lambda function', 'Provisioned concurrency prepares execution environments and does not stop repeated requests from invoking the function and reading the table.'],
      ['Increase the provisioned read capacity of the DynamoDB table', 'Extra capacity adds read throughput, but each request still invokes the function and reads the table, so nothing is reduced.'],
    ],
    slot: 2,
    evidence: [
      'apigw-caching|With caching, you can reduce the number of calls made to your endpoint and also improve the latency of requests to your API.',
      'apigw-caching|API Gateway then responds to the request by looking up the endpoint response from the cache instead of making a request to your endpoint.',
    ],
  }),
  mc({
    id: 'cache-edge-breakwater-008',
    building: 'cache-edge-breakwater',
    bullets: ['2.1-K3'],
    d: 2,
    tags: ['placement-eligible'],
    stem: 'AWS Lambda functions read user profiles from Amazon DynamoDB through an Amazon ElastiCache cache. Profiles change a few times a day, and a profile read right after an update must never return old data. The application can tolerate a small delay on writes. Which caching strategy BEST meets these requirements?',
    correct: ['Write-through, so that every profile write also adds or updates the item in the cache', 'The cache is updated every time data is written to the database, so data in the cache is never stale.'],
    wrong: [
      ['Lazy loading only, so that a profile is cached the first time it is read', 'Data is written to the cache only on a miss, so a cached profile can become stale after the database is updated.'],
      ['Lazy loading with a long time to live on each cached profile', 'A time to live keeps data from getting too stale but does not guarantee that a value is not stale, so reads right after an update can be old.'],
      ['Load all profiles into the cache once at startup and never change them', 'The cached copies would never reflect later updates, so they would be stale after the first change.'],
    ],
    slot: 3,
    evidence: [
      'elasticache-strategies|The write-through strategy adds data or updates data in the cache whenever data is written to the database.',
      'elasticache-strategies|The advantages of write-through are as follows: Data in the cache is never stale.',
      'elasticache-strategies|If data is written to the cache only when there is a cache miss, data in the cache can become stale.',
      "elasticache-strategies|This approach doesn't guarantee that a value isn't stale.",
    ],
  }),
  mr({
    id: 'cache-edge-breakwater-009',
    building: 'cache-edge-breakwater',
    bullets: ['2.1-K3'],
    d: 3,
    stem: 'A company caches product details from an Amazon RDS database in Amazon ElastiCache. Only data that customers actually request should take up space in the cache, a failed cache node must not break the application, and cached data must not stay stale for long. Which TWO design choices BEST meet these requirements? (Choose two.)',
    correct: [
      ['Use lazy loading, so that data is cached only when the application requests it', 'Only requested data is cached, and a failed node is replaced by an empty one that the application refills with cache misses instead of failing.'],
      ['Add a time to live to each cached item', 'Expiry keeps cached data from getting too stale because values are refreshed from the database from time to time.'],
    ],
    wrong: [
      ['Use write-through for every database write', 'Most written data is never read, so this fills the cache with data nobody requested, and a new node lacks data until it is written.'],
      ['Load the whole catalogue into the cache at deployment and keep it without expiry', 'This caches data nobody requested and lets entries go stale because nothing refreshes them.'],
      ['Remove the cache and send every read to the database', 'Without a cache there is nothing to go stale, but this fails the goal of caching requested data and increases the load on the database.'],
    ],
    slots: [0, 2],
    evidence: [
      'elasticache-strategies|The advantages of lazy loading are as follows: Only requested data is cached.',
      "elasticache-strategies|Node failures aren't fatal for your application.",
      'elasticache-strategies|However, it keeps data from getting too stale and requires that values in the cache are occasionally refreshed from the database.',
      'elasticache-strategies|Most data is never read, which is a waste of resources.',
    ],
  }),
  mr({
    id: 'cache-edge-breakwater-010',
    building: 'cache-edge-breakwater',
    bullets: ['2.1-K7', '2.1-K3'],
    d: 2,
    tags: ['placement-eligible'],
    stem: 'A company hosts a single-page application in an Amazon S3 bucket and a public REST API that uses Amazon API Gateway, AWS Lambda and Amazon DynamoDB. Users around the world repeatedly request the same static files and the same read-mostly GET response. The company wants lower latency and fewer requests reaching S3 and Lambda, with the LEAST code change. Which TWO actions meet these requirements? (Choose two.)',
    correct: [
      ['Create an Amazon CloudFront distribution that uses the S3 bucket as its origin', 'Static files are served from edge locations close to users, which cuts latency and the number of requests that reach S3.'],
      ['Enable caching on the API Gateway stage', 'Repeated GET requests are answered from cached responses instead of invoking the Lambda function and reading the table.'],
    ],
    wrong: [
      ['Create an AWS Global Accelerator accelerator with the S3 bucket as an endpoint', 'An S3 bucket is not an endpoint of a standard accelerator, and an accelerator proxies packets instead of caching files.'],
      ['Create a DynamoDB Accelerator (DAX) cluster in front of the table', 'DAX caches DynamoDB reads, but each API request would still invoke the Lambda function.'],
      ['Place an Amazon ElastiCache cluster in front of the S3 bucket for the static files', 'ElastiCache is an in-memory store for applications and does not serve the files from locations close to users.'],
    ],
    slots: [1, 4],
    evidence: [
      'cloudfront-what-is|You also get increased reliability and availability because copies of your files (also known as objects) are now held (or cached) in multiple edge locations around the world.',
      'apigw-caching|With caching, you can reduce the number of calls made to your endpoint and also improve the latency of requests to your API.',
      'ga-what-is|Endpoints for standard accelerators can be Network Load Balancers, Application Load Balancers, Amazon EC2 instances, or Elastic IP addresses that are located in one AWS Region or multiple Regions.',
    ],
  }),
  mc({
    id: 'cache-edge-breakwater-011',
    building: 'cache-edge-breakwater',
    bullets: ['2.1-K3'],
    d: 1,
    tags: ['mock-reserve'],
    stem: 'A company wants a managed in-memory data store that sits between its application servers and a relational database and holds frequently read query results. The store must support the Redis OSS or Memcached engines, and the company wants the LEAST operational overhead. Which service should the company use?',
    correct: ['Amazon ElastiCache', 'ElastiCache is a fully managed in-memory data store and cache that works with the Valkey, Memcached and Redis OSS engines.'],
    wrong: [
      ['Amazon DynamoDB Accelerator (DAX)', 'DAX is a caching service for DynamoDB tables and does not cache results from a relational database.'],
      ['Amazon CloudFront', 'CloudFront caches web content at edge locations and is not an in-memory store that application servers query before a database.'],
      ['An Amazon RDS read replica', 'A read replica is another database instance and is not an in-memory cache based on Redis OSS or Memcached.'],
    ],
    slot: 0,
    evidence: [
      'elasticache-what-is|Amazon ElastiCache is a web service that makes it easy to set up, manage, and scale a distributed in-memory data store or cache environment in the cloud.',
      'elasticache-what-is|Since ElastiCache is a fully-managed service, it automatically manages hardware provisioning, monitoring, node replacements, and software patching for your cluster.',
      'dax|DAX is a DynamoDB-compatible caching service that enables you to benefit from fast in-memory performance for demanding applications.',
    ],
  }),
  mc({
    id: 'cache-edge-breakwater-012',
    building: 'cache-edge-breakwater',
    bullets: ['2.1-K7'],
    d: 2,
    tags: ['mock-reserve', 'trap:cloudfront-vs-global-accelerator'],
    stem: 'A company serves a personalised web application from Application Load Balancers in two AWS Regions. The responses cannot be cached. Partner networks must allow-list fixed IP addresses, and traffic must shift to the other Region quickly when one becomes unhealthy. The company wants the LEAST operational overhead. Which solution meets these requirements?',
    correct: ['Create an AWS Global Accelerator accelerator and add both load balancers as endpoints', 'The accelerator provides static IP addresses as fixed entry points and routes traffic only to healthy endpoints in either Region.'],
    wrong: [
      ['Create an Amazon CloudFront distribution and turn off caching for the behaviors', 'CloudFront is built to speed up delivery of content, and with caching off it adds nothing for the fixed-address and fast-failover needs.'],
      ['Create Amazon Route 53 failover records that point to the two load balancers', 'DNS answers are cached by client devices and resolvers, so a shift to the other Region is not deterministic and fast.'],
      ['Run proxy instances with Elastic IP addresses in each Region and fail over with a script', 'The company would patch, scale and script the proxies itself, which is far more operational overhead than a managed service.'],
    ],
    slot: 1,
    evidence: [
      'ga-faq|Global Accelerator is a good fit for non-HTTP use cases, such as gaming (UDP), IoT (MQTT), or Voice over IP, as well as for HTTP use cases that specifically require static IP addresses or deterministic, fast regional failover.',
      'ga-how|The static IP addresses provided by AWS Global Accelerator serve as single fixed entry points for your clients.',
      'ga-faq|Some client devices and internet resolvers cache DNS answers for long periods of time.',
    ],
  }),
];

export default questions;
