import type { Question } from '../../../src/content/types.ts';
import { mc, mr } from '../helpers.ts';

const questions: Question[] = [
  mc({
    id: 'cargo-hall-001',
    building: 'cargo-hall',
    bullets: ['2.1-K13'],
    d: 1,
    tags: ['trap:ebs-efs-fsx'],
    stem: 'A media company stores millions of video files that a streaming application reads through an API over the internet. The workload is read-heavy, and the company does not want to run file servers or manage volumes. Which storage type and service BEST meet these requirements?',
    correct: ['Object storage, using Amazon S3 buckets that the application reads through the S3 API', 'Object storage is accessed through an API over the internet and suits read-heavy streaming workloads, with no servers or volumes to run.'],
    wrong: [
      ['Block storage, using Amazon EBS volumes attached to the streaming servers', 'Block storage is attached to an instance for low-latency disk access, not read through an API over the internet.'],
      ['File storage, using an Amazon EFS file system mounted on the streaming servers', 'File storage is mounted by clients over NFS, which does not match access through an API over the internet.'],
      ['File storage, using Amazon FSx for Windows File Server shares reached over SMB', 'File storage is mounted by clients over SMB, which does not match access through an API over the internet.'],
    ],
    slot: 0,
    evidence: [
      'storage-decision|Object storage provides easy access to data through an application programming interface (API) over the internet and is well-suited to read-heavy workloads (such as streaming applications and services).',
      'storage-decision|Read-heavy workloads such as content distribution, web hosting, big data analytics, and ML workflows.',
    ],
  }),
  mc({
    id: 'cargo-hall-002',
    building: 'cargo-hall',
    bullets: ['2.1-K13'],
    d: 2,
    tags: ['trap:ebs-efs-fsx', 'trap:instance-store-vs-ebs'],
    stem: 'A company runs a self-managed relational database on one Amazon EC2 instance, and no other server accesses the data. The database needs durable storage with low-latency, consistent I/O that works like a local disk. Which storage option meets these requirements with the LEAST change to the application?',
    correct: ['An Amazon EBS volume attached to the instance and formatted with the database file system', 'Block storage attached to a single instance gives low-latency, durable disk access and behaves like a local hard drive.'],
    wrong: [
      ['An Amazon S3 bucket that the database engine reads and writes through the S3 API', 'Object storage is accessed through an API rather than as a local disk, so the database engine would need to change.'],
      ['An Amazon EFS file system mounted on the instance over NFS to hold the database files', 'File storage is built for shared access across many clients, which this single-instance database does not need.'],
      ['Instance store volumes on the host computer, copied nightly to a second Amazon S3 bucket', 'Instance store data does not persist if the instance is stopped or terminated, so the storage is not durable.'],
    ],
    slot: 1,
    evidence: [
      'storage-decision|Storage services or tools Block Applications requiring low-latency, high-performance durable storage attached to single Amazon EC2 instances or containers, such as databases and general-purpose local instance storage.',
      'ebs-what-is|After you attach a volume to an instance, you can use it in the same way you would use a local hard drive attached to a computer, for example to store files or to install applications.',
      'instance-store-lifetime|When the instance is stopped, hibernated, or terminated, every block of the instance store volume is cryptographically erased.',
    ],
  }),
  mr({
    id: 'cargo-hall-003',
    building: 'cargo-hall',
    bullets: ['2.1-K13'],
    d: 2,
    tags: ['trap:ebs-efs-fsx'],
    stem: 'A company is moving two shared-file workloads to AWS. Linux analytics servers on Amazon EC2 need shared read and write access to the same files over NFS. A Windows-based finance team needs file shares that use the SMB protocol on a native Windows file system. The company wants fully managed storage with the LEAST operational overhead. Which TWO solutions meet these requirements? (Choose two.)',
    correct: [
      ['An Amazon EFS file system that the Linux analytics servers mount over NFS', 'Amazon EFS is shared file storage that supports NFS, so many Linux clients can read and write the same files without servers to manage.'],
      ['An Amazon FSx for Windows File Server file system that serves the finance team over SMB', 'FSx for Windows File Server is a fully managed native Windows file system with SMB support.'],
    ],
    wrong: [
      ['Amazon EBS Multi-Attach volumes shared by the Linux analytics servers', 'Multi-Attach is block storage limited to Provisioned IOPS SSD volumes in one Availability Zone, and it is not an NFS file system.'],
      ['An Amazon EFS file system that the Windows-based finance team uses for its shares', 'Amazon EFS does not support Microsoft Windows-based EC2 instances, and the team needs SMB shares.'],
      ['An Amazon S3 bucket that both teams read and write through the S3 API', 'Object storage is reached through an API, not mounted as NFS or SMB file shares.'],
    ],
    slots: [1, 4],
    evidence: [
      'storage-decision|Applications and workloads requiring shared read and write access across multiple Amazon EC2 instances or containers, or from multiple on-premises servers, such as team file shares, highly available enterprise applications, analytics workloads, and ML training.',
      'efs-what-is|Amazon EFS supports the Network File System version 4 (NFSv4.1 and NFSv4.0) protocol, so the applications and tools that you use today work seamlessly with Amazon EFS.',
      'efs-what-is|Using Amazon EFS with Microsoft Windows–based Amazon EC2 instances is not supported.',
      'fsx-windows|Amazon FSx has native support for Windows file system features and for the industry-standard Server Message Block (SMB) protocol to access file storage over a network.',
    ],
  }),
  mc({
    id: 'cargo-hall-004',
    building: 'cargo-hall',
    bullets: ['2.1-K13'],
    d: 3,
    tags: ['trap:ebs-efs-fsx'],
    stem: 'A company runs a clustered application on two Amazon EC2 instances built on the Nitro System in the same Availability Zone. Both instances must read and write the same block device at the same time, and the application coordinates concurrent writes itself. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Create one io2 volume with Multi-Attach enabled and attach it to both instances', 'Multi-Attach lets a single io1 or io2 volume attach to several instances in the same Availability Zone for applications that manage concurrent writes.'],
    wrong: [
      ['Create one General Purpose SSD (gp3) volume and attach it to both instances at once', 'Multi-Attach is documented for Provisioned IOPS SSD (io1 or io2) volumes, so a gp3 volume cannot be shared this way.'],
      ['Create an Amazon EFS file system and mount it on both instances over NFS', 'EFS is file storage over NFS, and the application needs a shared block device.'],
      ['Create an io2 volume in a different Availability Zone and attach it to both instances', 'A volume and the instance it is attached to must be in the same Availability Zone.'],
    ],
    slot: 2,
    evidence: [
      'ebs-multi-attach|Amazon EBS Multi-Attach enables you to attach a single Provisioned IOPS SSD (io1 or io2) volume to multiple instances that are in the same Availability Zone.',
      'ebs-multi-attach|Multi-Attach makes it easier for you to achieve higher application availability in applications that manage concurrent write operations.',
      'ebs-volumes|The volume and instance must be in the same Availability Zone.',
    ],
  }),
  mc({
    id: 'cargo-hall-005',
    building: 'cargo-hall',
    bullets: ['2.1-K13'],
    d: 1,
    stem: 'A company keeps application data on an Amazon EBS volume. The company needs a point-in-time backup of the volume that remains available even if the volume itself is deleted. Which feature meets this requirement?',
    correct: ['Amazon EBS snapshots of the volume, taken on a regular schedule and kept separately', 'Snapshots are point-in-time backups of volumes that persist independently from the volume, and new volumes can be restored from them.'],
    wrong: [
      ['Amazon EBS encryption turned on for the volume with an AWS KMS key', 'Encryption protects data on the volume and its snapshots but does not create a backup copy.'],
      ['Amazon EBS Multi-Attach turned on for the volume and a second instance attached', 'Multi-Attach lets more instances use the same volume, so deleting the volume still removes the data.'],
      ['An instance store volume on the same instance, with the files copied to it each night', 'Instance store data does not persist when the instance is stopped or terminated, so it is not a lasting backup.'],
    ],
    slot: 3,
    evidence: [
      'ebs-what-is|Amazon EBS snapshots — These are point-in-time backups of Amazon EBS volumes that persist independently from the volume itself.',
      'ebs-what-is|You can then restore new volumes from those snapshots at any time.',
      'instance-store-lifetime|When the instance is stopped, hibernated, or terminated, every block of the instance store volume is cryptographically erased.',
    ],
  }),
  mc({
    id: 'cargo-hall-006',
    building: 'cargo-hall',
    bullets: ['2.1-S6'],
    d: 2,
    stem: 'A company packages a web application as Docker containers and runs them on Amazon ECS. The company does not want to provision, configure or scale clusters of virtual machines for the containers. Which compute option BEST meets these requirements?',
    correct: ['AWS Fargate as the launch type for the Amazon ECS tasks that run the containers', 'Fargate runs containers without managing servers or clusters of EC2 instances, and it works with Amazon ECS.'],
    wrong: [
      ['Amazon EC2 instances registered to the ECS cluster and scaled by an Auto Scaling group', 'The company would still provision, patch and scale the cluster of virtual machines that run the containers.'],
      ['Amazon EKS with self-managed worker nodes in an Auto Scaling group of EC2 instances', 'The company would still run and scale virtual machines, and it would also have to adopt Kubernetes.'],
      ['Amazon ECS Anywhere with servers that the company runs in its own data center', 'ECS Anywhere registers external servers to the cluster, which the company would still own and manage.'],
    ],
    slot: 0,
    evidence: [
      'compute-decision|AWS Fargate is a technology that you can use with Amazon ECS to run containers without having to manage servers or clusters of Amazon EC2 instances.',
      'compute-decision|Amazon ECS Anywhere provides support for registering an external instance such as an on-premises server or VM, to your Amazon ECS cluster.',
    ],
  }),
  mc({
    id: 'cargo-hall-007',
    building: 'cargo-hall',
    bullets: ['2.1-S6'],
    d: 2,
    stem: 'A small team has a Java web application. The team wants to deploy only its application code while the service provides the runtime on Amazon EC2 instances and applies patches to the operating system and runtime. Which service meets these requirements with the LEAST operational overhead?',
    correct: ['AWS Elastic Beanstalk with a Java platform environment that runs the code on EC2', 'Elastic Beanstalk is designed for web applications and manages updates for OS patches and runtime on the EC2 instances it manages.'],
    wrong: [
      ['Amazon EC2 instances that the team builds, configures with Java and patches itself', 'The team would be responsible for setup, scaling, patching and securing the servers.'],
      ['AWS Batch with a job definition that wraps the web application', 'Batch plans, schedules and runs batch workloads, and it is not a service for running web applications.'],
      ['Amazon EKS with a managed node group and the application packaged as a container', 'The team would have to containerize the application and operate Kubernetes workloads, which adds overhead.'],
    ],
    slot: 1,
    evidence: [
      'compute-decision|Elastic Beanstalk is specifically designed for running web applications.',
      'compute-decision|Elastic Beanstalk provides managed updates for OS patches, runtime and framework on EC2 instances it manages so customers can just run their application code.',
      'compute-decision|For instance, managing EC2 instances involves responsibility for setup, scaling, patching, and securing servers.',
    ],
  }),
  mc({
    id: 'cargo-hall-008',
    building: 'cargo-hall',
    bullets: ['2.1-S6'],
    d: 3,
    tags: ['trap:s3-storage-classes'],
    stem: 'A research company keeps 200 TB of datasets in Amazon S3 Standard. Some datasets are read daily for weeks and then not touched for months, and the pattern differs by dataset. The company wants storage costs reduced automatically, with no application changes and no planning of access patterns. Which solution is the MOST cost-effective?',
    correct: ['Move the datasets to S3 Intelligent-Tiering so objects move between access tiers as access changes', 'Intelligent-Tiering is the ideal class for unknown or changing access patterns and moves data automatically with no application changes.'],
    wrong: [
      ['Create an S3 Lifecycle rule that moves every object to S3 Standard-IA after a fixed number of days', 'A fixed schedule cannot follow each dataset\'s access pattern, so datasets that are read again would stay in the wrong class.'],
      ['Move all datasets to S3 Glacier Flexible Retrieval to cut the cost of storing them', 'Access times range from minutes to hours, which does not suit datasets that are read daily.'],
      ['Copy the datasets to an Amazon EFS file system and use EFS Lifecycle management to move cold files', 'EFS is file storage, so the applications that use the S3 API would need to change.'],
    ],
    slot: 2,
    evidence: [
      's3-storage-classes|S3 Intelligent-Tiering is the ideal storage class when you want to optimize storage costs for data that has unknown or changing access patterns.',
      'storage-decision|Use storage classes and tiering features that match your access patterns.',
      's3-glacier-classes|S3 Glacier Flexible Retrieval offers flexible retrieval times to help you balance costs, with access times ranging from a few minutes to hours, and free bulk retrievals.',
    ],
  }),
  mr({
    id: 'cargo-hall-009',
    building: 'cargo-hall',
    bullets: ['2.1-S6'],
    d: 3,
    stem: 'A retail company needs two databases. The order-processing system needs a fully managed relational database with full SQL support, automated backups and Multi-AZ deployments. A reporting team needs to run large-scale analytics queries over years of sales data. The company wants managed services with the LEAST operational overhead. Which TWO choices meet these requirements? (Choose two.)',
    correct: [
      ['Amazon RDS for the order-processing system, with automated backups and Multi-AZ', 'RDS is a fully managed relational database with automated backups, software patching and Multi-AZ deployments.'],
      ['Amazon Redshift for the reporting workload, querying the full sales history', 'Redshift is a fully managed data warehousing service designed for large-scale analytics.'],
    ],
    wrong: [
      ['Amazon DynamoDB for the order-processing system, with joins done in the application', 'DynamoDB is a key-value NoSQL database and is not a relational database with full SQL support.'],
      ['Amazon ElastiCache for the reporting workload, holding the full sales history', 'ElastiCache is an ephemeral cache for frequently accessed data and not a store for years of sales data.'],
      ['Amazon Neptune for the reporting queries over the sales history', 'Neptune is a graph database for traversing relationships and is not a data warehouse for analytics.'],
    ],
    slots: [0, 2],
    evidence: [
      'database-decision|Optimized for structured data with full SQL support, automated backups, software patching, and Multi-AZ deployments for high availability.',
      'database-decision|Amazon Redshift is a fully managed, cloud-based data warehousing service that is designed to handle large-scale analytics workloads.',
      'database-decision|Optimized to support microsecond reads and sub-millisecond writes as an ephemeral cache for frequently accessed data.',
    ],
  }),
  mc({
    id: 'cargo-hall-010',
    building: 'cargo-hall',
    bullets: ['2.1-S6'],
    d: 2,
    tags: ['trap:aurora-vs-rds'],
    stem: 'A company runs a Microsoft SQL Server database on Amazon EC2 for an internal line-of-business application. The company wants a fully managed database service that keeps the SQL Server engine and removes patching and backup administration. Which solution meets these requirements?',
    correct: ['Migrate the database to Amazon RDS for SQL Server and keep the engine', 'RDS offers SQL Server among its engines as a fully managed service, so the application keeps its engine and AWS handles patching and backups.'],
    wrong: [
      ['Migrate the database to Amazon Aurora PostgreSQL-Compatible Edition', 'Aurora supports MySQL and PostgreSQL-compatible engines, so the SQL Server engine would be lost and the application would change.'],
      ['Migrate the data to Amazon DynamoDB and rewrite the queries as key-value requests', 'DynamoDB is a key-value NoSQL database, so the SQL queries and the SQL Server engine would be lost.'],
      ['Migrate the data to Amazon Redshift and run the application against the warehouse', 'Redshift is a data warehouse for large-scale analytics, not an engine for a transactional line-of-business application.'],
    ],
    slot: 3,
    evidence: [
      'database-decision|Use when you need a fully managed relational database with your choice of six popular engines: PostgreSQL, MySQL, MariaDB, SQL Server, Oracle, and Db2.',
      'database-decision|Supports MySQL and PostgreSQL-compatible engines with up to five times the throughput of standard MySQL.',
      'database-decision|While rehosting is a fast path to the cloud, you\'re still left with the operational tasks such as upgrades, patches, backups, capacity planning and management, maintaining performance, and availability targets.',
    ],
  }),
  mc({
    id: 'cargo-hall-011',
    building: 'cargo-hall',
    bullets: ['2.1-K13', '2.1-S6'],
    d: 2,
    tags: ['mock-reserve', 'trap:ebs-efs-fsx'],
    stem: 'A company is migrating from on-premises NetApp appliances. Linux servers reach the data over NFS and Windows servers reach the same data over SMB, and the company wants a fully managed service that serves both protocols at once. Which solution BEST meets these requirements?',
    correct: ['An Amazon FSx for NetApp ONTAP file system that both server groups mount', 'FSx for NetApp ONTAP supports NFS and SMB with concurrent multi-protocol access to the same data, which suits mixed Linux and Windows clients.'],
    wrong: [
      ['An Amazon EFS file system mounted by both the Linux and the Windows servers', 'EFS supports NFS only and is not supported with Microsoft Windows-based EC2 instances, so the SMB clients cannot use it.'],
      ['An Amazon FSx for Lustre file system mounted by both groups of servers', 'FSx for Lustre is designed for Unix and Linux file systems and speed-sensitive workloads, not for Windows SMB clients.'],
      ['Amazon EBS Multi-Attach volumes shared by all of the servers', 'Multi-Attach is block storage for instances in one Availability Zone, not a file system with NFS and SMB access.'],
    ],
    slot: 0,
    evidence: [
      'storage-decision|Amazon FSx for NetApp ONTAP supports both NFS and SMB protocols, including concurrent multi-protocol access to the same data.',
      'storage-decision|This makes it suitable for mixed environments where both Linux and Windows clients need access to shared data, such as when migrating from on-premises NetApp appliances.',
      'storage-decision|Amazon FSx for Lustre (for high-performance file systems) is designed for use with Unix/Linux-based file systems.',
    ],
  }),
  mc({
    id: 'cargo-hall-012',
    building: 'cargo-hall',
    bullets: ['2.1-S6'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A research company runs thousands of containerized simulation jobs every night. The company wants a fully managed service that plans, schedules and runs the jobs across Spot and On-Demand Instances, with the LEAST custom scheduling code. Which service should the company use?',
    correct: ['AWS Batch with a compute environment that uses Spot and On-Demand Instances', 'Batch is a fully managed batch computing service that plans, schedules and runs containerized batch workloads across Spot and On-Demand capacity.'],
    wrong: [
      ['AWS Elastic Beanstalk with a worker environment that wraps the simulations', 'Elastic Beanstalk is designed for running web applications and does not plan and schedule batch jobs across Spot capacity.'],
      ['Amazon ECR with a repository that holds the simulation images', 'ECR is a container image registry, which stores images but does not schedule or run jobs.'],
      ['An Amazon EC2 Auto Scaling group with a custom scheduler that the company writes', 'Auto Scaling adds and removes instances by scaling policies, and the company would write the job scheduling itself.'],
    ],
    slot: 1,
    evidence: [
      'compute-decision|AWS Batch is a fully managed batch computing service that plans, schedules, and runs your containerized batch machine learning, simulation, and analytics workloads across the full range of AWS compute offerings, such as Amazon ECS, Amazon EKS, Fargate, and Spot or On-Demand Instances.',
      'compute-decision|Amazon ECR is an AWS managed container image registry service that is secure, scalable, and reliable.',
      'compute-decision|Elastic Beanstalk is specifically designed for running web applications.',
    ],
  }),
];

export default questions;
