import type { Question } from '../../../src/content/types.ts';
import { mc, mr } from '../helpers.ts';

const questions: Question[] = [
  mc({
    id: 'container-dock-001',
    building: 'container-dock',
    bullets: ['2.1-K8'],
    d: 1,
    stem: 'A company is moving an application into Docker containers. The team needs a private, managed place to store the container images, with access controlled through IAM. Which AWS service BEST meets this requirement?',
    correct: ['Amazon ECR', 'Amazon ECR is a managed container image registry that supports private repositories with permissions controlled through IAM.'],
    wrong: [
      ['Amazon ECS', 'Amazon ECS orchestrates containers that run from images, and it is not the registry where the images are stored.'],
      ['AWS Fargate', 'Fargate provides serverless compute capacity to run containers and does not store container images.'],
      ['Amazon EKS', 'Amazon EKS provides managed Kubernetes to orchestrate containers and does not act as the image registry.'],
    ],
    slot: 0,
    evidence: [
      'ecr-what-is|Amazon Elastic Container Registry (Amazon ECR) is an AWS managed container image registry service that is secure, scalable, and reliable.',
      'ecr-what-is|Amazon ECR supports private repositories with resource-based permissions using AWS IAM.',
    ],
  }),
  mc({
    id: 'container-dock-002',
    building: 'container-dock',
    bullets: ['2.1-K14'],
    d: 1,
    stem: 'A company runs an application on Kubernetes in its own data center and uses community Kubernetes tooling. The company wants to move it to AWS with a managed Kubernetes control plane and without refactoring the application. Which service BEST meets these requirements?',
    correct: ['Amazon EKS', 'Amazon EKS is certified Kubernetes-conformant, so Kubernetes-compatible applications deploy without refactoring, and AWS manages the control plane.'],
    wrong: [
      ['Amazon ECS', 'Amazon ECS is the AWS-native orchestrator with its own task definitions and services, so the application would have to be reworked.'],
      ['AWS Lambda with container images', 'Lambda runs event-driven functions and does not run Kubernetes workloads or tooling.'],
      ['Amazon EC2 instances that run a self-managed Kubernetes cluster', 'The company would operate the control plane itself instead of using a managed one.'],
    ],
    slot: 1,
    evidence: [
      'eks-what-is|Amazon EKS is certified Kubernetes-conformant, so you can deploy Kubernetes-compatible applications without refactoring and use Kubernetes community tooling and plugins.',
      'eks-what-is|EKS standard: AWS manages the Kubernetes control plane when you create a cluster with EKS.',
    ],
  }),
  mc({
    id: 'container-dock-003',
    building: 'container-dock',
    bullets: ['2.1-S4'],
    d: 1,
    stem: 'A development team finds that an application behaves differently on developer laptops, in testing and in production because the environments differ. The team wants the application to run the same way on any platform that supports the runtime. Which approach BEST meets this requirement?',
    correct: ['Package the application and its dependencies in container images', 'Containers give a consistent runtime environment that runs on any platform that supports the container runtime.'],
    wrong: [
      ['Install the dependencies by hand on the same Amazon EC2 instance type in every environment', 'Manual installs drift apart over time and do not travel with the application to other platforms.'],
      ['Place each environment in its own AWS account and VPC with the same security groups', 'Account and network isolation separates the environments and does not make the runtime consistent.'],
      ['Document the setup steps for each environment in a shared runbook that the team follows', 'A runbook relies on people following steps and does not guarantee the same runtime everywhere.'],
    ],
    slot: 2,
    evidence: [
      'container-decision|Portability: Benefit from a consistent runtime environment that can run on any platform that supports the container runtime.',
      'container-decision|Consistency: Ensure that the application runs the same way in all environments with a consistent runtime environment.',
    ],
  }),
  mc({
    id: 'container-dock-004',
    building: 'container-dock',
    bullets: ['2.1-S4', '2.1-K14'],
    d: 2,
    stem: 'A company is moving a containerized, stateless web API to AWS. The team has no Kubernetes experience, and it wants the API to run behind a load balancer with no Amazon EC2 instances to patch or scale. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['An Amazon ECS service that uses AWS Fargate, registered with an Application Load Balancer', 'Fargate runs the containers without servers to manage, and ECS services on Fargate support Application Load Balancers.'],
    wrong: [
      ['An Amazon ECS service that runs on Amazon EC2 instances in an Auto Scaling group behind an Application Load Balancer', 'With EC2 capacity the team chooses the instance type and number of instances and manages the capacity, which it wants to avoid.'],
      ['An Amazon EKS cluster with self-managed worker nodes behind an Application Load Balancer', 'The team would need Kubernetes skills and would manage the worker nodes, which conflicts with both requirements.'],
      ['Docker installed on one Amazon EC2 instance that sits behind an Application Load Balancer', 'The team would patch and scale the instance itself, and one instance cannot follow demand or replace failures on its own.'],
    ],
    slot: 3,
    evidence: [
      "ecs-what-is|With Fargate you don't need to manage servers, handle capacity planning, or isolate container workloads for security.",
      'ecs-what-is|Amazon EC2 instances in the AWS cloud You choose the instance type, the number of instances, and manage the capacity.',
      'ecs-service-lb|Amazon ECS services hosted on AWS Fargate support the Application Load Balancers, Network Load Balancers, and Gateway Load Balancers.',
    ],
  }),
  mc({
    id: 'container-dock-005',
    building: 'container-dock',
    bullets: ['2.1-K8'],
    d: 2,
    stem: 'A company stores container images in a private Amazon ECR repository. The security team requires every newly pushed image to be checked for known software vulnerabilities automatically, with the LEAST operational effort. Which solution meets this requirement?',
    correct: ['Configure the repository to scan images on push', 'ECR image scanning identifies software vulnerabilities, and a repository set to scan on push scans each new image as it is pushed.'],
    wrong: [
      ['Add a lifecycle policy to the repository that expires images that contain vulnerabilities', 'Lifecycle policies clean up unused images by rule and do not scan images for vulnerabilities.'],
      ['Turn on cross-Region replication so that a second copy of every image exists in another Region', 'Replication places images where they are needed and does not check them for vulnerabilities.'],
      ['Run a nightly script on an Amazon EC2 instance that pulls every image and runs a scanner', 'This is custom tooling that the team must build and operate, and new images stay unscanned until the nightly run.'],
    ],
    slot: 0,
    evidence: [
      'ecr-what-is|Image scanning helps in identifying software vulnerabilities in your container images.',
      'ecr-what-is|Each repository can be configured to scan on push.',
      'ecr-what-is|This ensures that each new image pushed to the repository is scanned.',
      'ecr-what-is|You define rules that result in the cleaning up of unused images.',
    ],
  }),
  mc({
    id: 'container-dock-006',
    building: 'container-dock',
    bullets: ['2.1-K14'],
    d: 2,
    stem: 'A containerized application runs as tasks in Amazon ECS on AWS Fargate and must read objects from an Amazon S3 bucket. The security team prohibits long-term access keys in container images and task definitions. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Create an IAM role with the S3 permissions and set it as the task role in the task definition', 'The task role vends its permissions to the containers in the task, so the application can use Amazon S3 without any stored access keys.'],
    wrong: [
      ['Attach an EC2 instance profile with the S3 permissions to the Fargate infrastructure that runs the tasks', 'EC2 instance profiles are not available for containers in tasks that run on Fargate.'],
      ['Create an IAM user with the S3 permissions and bake its access keys into the container image', 'Long-term access keys inside an image are exactly what the security team prohibits.'],
      ['Create an IAM user with the S3 permissions and put its access keys in plain-text task definition variables', 'Long-term access keys in the task definition are prohibited, and anyone who can read the definition can read them.'],
    ],
    slot: 1,
    evidence: [
      'ecs-task-role|The task role is required when your application accesses other AWS services, such as Amazon S3.',
      'ecs-task-role|The permissions granted in the IAM role are vended to containers running in the task.',
      'ecs-task-role|On ECS Fargate, EC2 instance profiles are not available for containers in your tasks.',
    ],
  }),
  mc({
    id: 'container-dock-007',
    building: 'container-dock',
    bullets: ['2.1-K14'],
    d: 2,
    stem: 'A company must keep some workloads on its own on-premises servers because of data residency rules. It runs its cloud containers on Amazon ECS and wants to deploy to the on-premises servers with the same ECS APIs and tooling. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Register the on-premises servers to the Amazon ECS cluster by using Amazon ECS Anywhere', 'ECS Anywhere registers an external server or VM to an ECS cluster, so the same ECS tooling deploys to it.'],
    wrong: [
      ['Run AWS Fargate tasks on the on-premises servers by installing the Fargate agent on them', 'Fargate is the serverless compute option in the AWS Cloud, and it cannot be installed on the servers of the company.'],
      ['Install a self-managed Kubernetes cluster on the on-premises servers and manage it separately', 'This creates a second orchestrator with different tooling instead of the same ECS APIs and tooling.'],
      ['Copy the images to Amazon S3 and start them on each server with a custom deployment script', 'Custom scripts replace the ECS scheduler and APIs that the company wants to keep using.'],
    ],
    slot: 2,
    evidence: [
      'ecs-what-is|Amazon ECS Anywhere provides support for registering an external instance such as an on-premises server or virtual machine (VM), to your Amazon ECS cluster.',
      'ecs-what-is|Serverless in the AWS cloud Fargate is a serverless, pay-as-you-go compute engine.',
    ],
  }),
  mc({
    id: 'container-dock-008',
    building: 'container-dock',
    bullets: ['2.1-K14'],
    d: 2,
    stem: 'A company runs a containerized web service as an Amazon ECS service on AWS Fargate. CPU use rises sharply during business hours. The company wants the number of running tasks to follow demand automatically and keep average CPU utilization near a target value, with the LEAST operational overhead. Which solution meets these requirements?',
    correct: ['Configure Amazon ECS Service Auto Scaling with a target tracking policy on average CPU utilization', 'Service Auto Scaling increases or decreases the desired number of tasks based on a target value for a metric.'],
    wrong: [
      ['Configure Cluster Auto Scaling to add Amazon EC2 instances to the cluster when CPU use rises', 'Cluster Auto Scaling manages EC2 instances registered to a cluster, and tasks on Fargate do not run on instances that the company manages.'],
      ['Create an Amazon CloudWatch alarm that notifies an operator who then raises the desired task count by hand', 'This is a manual process that does not follow demand automatically.'],
      ['Raise the CPU and memory values in the task definition to the largest values that Fargate offers', 'Bigger tasks do not change the number of running tasks, so the service does not follow demand.'],
    ],
    slot: 3,
    evidence: [
      'ecs-autoscaling|Automatic scaling is the ability to increase or decrease the desired number of tasks in your Amazon ECS service automatically.',
      'ecs-autoscaling|Increase or decrease the number of tasks that your service runs based on a target value for a specific metric.',
      'ecs-what-is|Cluster Auto Scaling Amazon ECS manages the scaling of Amazon EC2 instances that are registered to your cluster.',
    ],
  }),
  mc({
    id: 'container-dock-009',
    building: 'container-dock',
    bullets: ['2.1-K14', '2.1-S4'],
    d: 3,
    stem: 'A small company is containerizing its microservices. The team has no Kubernetes experience, does not need Kubernetes APIs or tooling, and wants tight control over network and security configuration on AWS. The number of services will grow, and the team wants to keep cluster operations to a minimum. Which solution meets these requirements?',
    correct: ['Amazon ECS with AWS Fargate as the capacity', 'ECS gives control over network and security configuration without Kubernetes, and Fargate removes server and capacity management.'],
    wrong: [
      ['Amazon EKS with managed node groups that the team sizes and patches as the number of services grows', 'EKS adds the Kubernetes operating model that the team does not need, and the nodes still need sizing and patching.'],
      ['Amazon ECS with self-managed Amazon EC2 instances that the team scales as the number of services grows', 'The team would choose instance types and manage the capacity, which adds the operations it wants to minimize.'],
      ['Amazon EKS with self-managed worker nodes so that the team can learn Kubernetes while it grows', 'The company has no need for Kubernetes, and self-managed nodes add the most cluster operations.'],
    ],
    slot: 0,
    evidence: [
      'container-decision|One of the first considerations is your preference for either a serverless operational model or a Kubernetes operation model.',
      'container-decision|Amazon ECS is a good choice if you need more control over the network and security configurations without sacrificing scale or features.',
      "ecs-what-is|With Fargate you don't need to manage servers, handle capacity planning, or isolate container workloads for security.",
    ],
  }),
  mc({
    id: 'container-dock-010',
    building: 'container-dock',
    bullets: ['2.1-S4'],
    d: 2,
    stem: 'A company runs 20 small services, each on its own Amazon EC2 instance at low utilization. Releases are slow, and the company wants to use compute resources more efficiently and to ship changes faster, with the LEAST change to the application code. Which solution meets these requirements?',
    correct: ['Package each service as a container image and run the services together on a shared Amazon ECS cluster', 'Containers use fewer resources than virtual machines and speed up packaging and deployment, and the code does not change.'],
    wrong: [
      ['Move each service to a larger Amazon EC2 instance type to make releases finish sooner', 'Larger instances add more unused capacity and do not make the packaging or deployment process any faster.'],
      ['Rewrite each service as an AWS Lambda function and invoke the functions through Amazon API Gateway', 'This rewrite is a large change to the application code, which the company wants to avoid.'],
      ['Keep one instance for each service and add a separate Auto Scaling group to every service', 'One instance per service keeps the low utilization and adds more groups to operate.'],
    ],
    slot: 1,
    evidence: [
      'container-decision|Efficiency: Use fewer resources than traditional virtual machines with lightweight containers.',
      'container-decision|Agility: Reduce the time that it takes to bring new features or applications to market by quickly packaging and deploying applications.',
    ],
  }),
  mc({
    id: 'container-dock-011',
    building: 'container-dock',
    bullets: ['2.1-K8'],
    d: 3,
    stem: 'A company is containerizing a monolithic web application that runs on one Amazon EC2 instance. The application keeps user sessions in instance memory and saves uploaded files on the instance disk. The containers will run as Amazon ECS tasks that deployments and scaling events replace often. Which solution prevents data loss when tasks are replaced, with the LEAST operational overhead?',
    correct: ['Keep session data in an external managed store such as Amazon ElastiCache and save uploaded files in Amazon S3', 'The application no longer depends on data stored locally on disk or in memory, so tasks can be replaced freely.'],
    wrong: [
      ['Turn on sticky sessions on the load balancer and keep the uploaded files on the ephemeral storage of each task', 'Sticky sessions bind a user to one task, and the session and files are lost when that task is replaced.'],
      ['Increase the CPU and memory of each task so that deployments and scaling events replace tasks less often', 'Tasks are still replaced by deployments and failures, and the state in memory and on disk is lost each time.'],
      ['Run the containers on Amazon EC2 instances and keep sessions in the memory of each host instance', 'The state would still depend on a single host and would be lost when that host is replaced.'],
    ],
    slot: 2,
    evidence: [
      'waf-stateless|Systems should either not require state, or should offload state such that between different client requests, there is no dependence on locally stored data on disk and in memory.',
      'waf-stateless|This allows servers to be replaced at will without causing an availability impact.',
      'ecs-what-is|Service A long running stateless application.',
    ],
  }),
  mr({
    id: 'container-dock-012',
    building: 'container-dock',
    bullets: ['2.1-K8'],
    d: 3,
    stem: 'A company is moving container images from a self-managed registry to AWS. The images must be stored in a private registry with access limited through IAM, every pushed image must be scanned for software vulnerabilities, and unused images must be cleaned up automatically. Which THREE actions meet these requirements with the LEAST operational overhead? (Choose three.)',
    correct: [
      ['Create a private Amazon ECR repository and control access with IAM permissions', 'ECR supports private repositories with resource-based permissions that use IAM.'],
      ['Configure the repository to scan each image when it is pushed', 'A repository can be configured to scan on push, so each new image is checked for software vulnerabilities.'],
      ['Define a lifecycle policy that cleans up unused images in the repository', 'Lifecycle policies use rules to clean up unused images automatically.'],
    ],
    wrong: [
      ['Store the images as tar files in an Amazon S3 bucket and pull them with custom scripts', 'This is not a container registry, and scanning and cleanup would need custom tooling.'],
      ['Run a self-managed registry on an Amazon EC2 instance and clean it with a nightly script', 'The company would operate the registry, the scanning and the cleanup itself.'],
      ['Create pull through cache rules so that old images are removed from the repository', 'Pull through cache rules cache an upstream registry and do not remove unused images.'],
    ],
    slots: [0, 2, 4],
    evidence: [
      'ecr-what-is|Amazon ECR supports private repositories with resource-based permissions using AWS IAM.',
      'ecr-what-is|Each repository can be configured to scan on push.',
      'ecr-what-is|You define rules that result in the cleaning up of unused images.',
      'ecr-what-is|Pull through cache rules provide a way to cache repositories in an upstream registry in your private Amazon ECR registry.',
    ],
  }),
  mr({
    id: 'container-dock-013',
    building: 'container-dock',
    bullets: ['2.1-K14'],
    d: 2,
    stem: 'A company deploys a containerized API on Amazon ECS with AWS Fargate. The API must always run three copies, a failed copy must be replaced automatically, and incoming HTTP traffic must be spread evenly across the copies. Which TWO actions meet these requirements with the LEAST operational overhead? (Choose two.)',
    correct: [
      ['Run the task definition as an Amazon ECS service with a desired count of three', 'An ECS service maintains the desired number of tasks and launches a replacement when a task fails or stops.'],
      ['Register the service with an Application Load Balancer target group whose target type is ip', 'A load balancer distributes traffic across the tasks of the service, and Fargate tasks need an ip target type.'],
    ],
    wrong: [
      ['Run the task definition as three standalone tasks and restart any task that stops', 'Standalone tasks are not maintained by a service scheduler, so replacing a failed task would be manual work.'],
      ['Register the service with a target group whose target type is instance', 'Tasks on Fargate use their own network interface and are not EC2 instances, so the target type must be ip.'],
      ['Place a Gateway Load Balancer in front of the service to route the HTTP traffic', 'Gateway Load Balancers are used with virtual appliances such as firewalls, and an Application Load Balancer routes HTTP and HTTPS traffic.'],
    ],
    slots: [2, 3],
    evidence: [
      'ecs-task-definitions|An Amazon ECS service runs and maintains your desired number of tasks simultaneously in an Amazon ECS cluster.',
      "ecs-task-definitions|if any of your tasks fail or stop for any reason, the Amazon ECS service scheduler launches another instance based on your task definition",
      'ecs-service-lb|Your service can optionally be configured to use Elastic Load Balancing to distribute traffic evenly across the tasks in your service.',
      'fargate-ecs|When you create a target group for these services, you must choose ip as the target type, not instance.',
      'ecs-service-lb|Use virtual appliances, such as firewalls, intrusion detection and prevention systems, and deep packet inspection systems.',
    ],
  }),
  mr({
    id: 'container-dock-014',
    building: 'container-dock',
    bullets: ['2.1-K8'],
    d: 3,
    stem: 'A team is containerizing an application that reads its database password from a configuration file baked into a machine image. The containers will run as Amazon ECS tasks on AWS Fargate. The password must not be stored in the container image or in the task definition text, it must be rotated automatically, and it must reach the container at runtime. Which TWO actions meet these requirements? (Choose two.)',
    correct: [
      ['Store the password as a secret in AWS Secrets Manager and enable automatic rotation', 'Secrets Manager can automatically rotate secrets, which a plain parameter store does not do.'],
      ['Reference the secret in the secrets parameter of the container definition and grant access only to the IAM principals that need it', 'Secrets are injected into containers at runtime, and access is restricted to specific IAM principals.'],
    ],
    wrong: [
      ['Pass the password as a plain-text environment variable in the task definition', 'The password would sit in the task definition text, which the team wants to avoid.'],
      ['Bake the password into the container image in an encrypted file that the application decrypts at startup', 'The password would still be stored in the image and would not rotate automatically.'],
      ['Store the password in an object in an Amazon S3 bucket that the container downloads when it starts', 'Nothing rotates the password automatically, and the team would build the retrieval logic itself.'],
    ],
    slots: [0, 3],
    evidence: [
      'ecs-sensitive-data|Secrets can be seamlessly injected into containers from AWS Secrets Manager and Amazon EC2 Systems Manager Parameter Store.',
      'ecs-sensitive-data|Secrets Manager, however, also includes the ability to automatically rotate secrets, generate random secrets, and share secrets across accounts.',
      'ecs-sensitive-data|Access to these secrets should be restricted to specific IAM principals that are using IAM and injected into containers at runtime.',
      'ecs-sensitive-data|They\'re referenced as environment variables that use the secrets container definition parameter.',
    ],
  }),
  mc({
    id: 'container-dock-015',
    building: 'container-dock',
    bullets: ['2.1-K14'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A company runs Kubernetes workloads on Amazon EKS and wants AWS to manage the worker nodes as well: provisioning capacity, scaling it and patching the operating system. The company wants the LEAST operational overhead. Which solution meets these requirements?',
    correct: ['Create the cluster with EKS Auto Mode', 'With EKS Auto Mode, EKS extends its control to the nodes and provisions infrastructure, scales resources and patches operating systems.'],
    wrong: [
      ['Create a standard EKS cluster, in which AWS manages the control plane and the company manages the nodes', 'In standard EKS, AWS manages the Kubernetes control plane, and the company still operates the nodes.'],
      ['Create a standard EKS cluster and install the Kubernetes Cluster Autoscaler on its node groups', 'The Cluster Autoscaler adjusts the number of nodes, but the company still installs and maintains it and patches the nodes.'],
      ['Create an Amazon ECS cluster with Amazon EC2 capacity and move the workloads to ECS task definitions', 'This abandons Kubernetes and still leaves the company managing the EC2 capacity.'],
    ],
    slot: 3,
    evidence: [
      'eks-what-is|EKS Auto Mode: Using the EKS Auto Mode feature, EKS extends its control to manage Nodes (Kubernetes data plane) as well.',
      'eks-what-is|It simplifies Kubernetes management by automatically provisioning infrastructure, selecting optimal compute instances, dynamically scaling resources, continuously optimizing costs, patching operating systems, and integrating with AWS security services.',
      'eks-what-is|EKS standard: AWS manages the Kubernetes control plane when you create a cluster with EKS.',
    ],
  }),
  mc({
    id: 'container-dock-016',
    building: 'container-dock',
    bullets: ['2.1-K14'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A company runs a set of stateless pods on Amazon EKS because it depends on Kubernetes tooling. The team does not want to provision or scale groups of EC2 instances for these pods, and each pod must have its own compute boundary. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Define a Fargate profile in the cluster so that the pods run on AWS Fargate', 'Fargate profiles control which pods start on Fargate, where each pod has its own compute boundary and no instances are provisioned or scaled.'],
    wrong: [
      ['Move the application to Amazon ECS tasks on AWS Fargate and drop the Kubernetes tooling', 'The company depends on Kubernetes tooling, so leaving Kubernetes breaks that requirement.'],
      ['Create managed node groups in each Availability Zone and size them by hand for the pods', 'Node groups are groups of EC2 instances that the team would still provision and scale.'],
      ['Install Karpenter in the cluster to launch right-sized instances for the pods', 'Karpenter is open-source software that customers install, configure and manage, and it still launches EC2 instances.'],
    ],
    slot: 0,
    evidence: [
      'eks-fargate|You can control which Pods start on Fargate and how they run with Fargate profiles.',
      'eks-fargate|Each Pod that runs on Fargate has its own compute boundary.',
      'eks-fargate|With Fargate, you don’t have to provision, configure, or scale groups of virtual machines on your own to run containers.',
      'eks-autoscaling|Karpenter is open-source software which AWS customers are responsible for installing, configuring, and managing in their Kubernetes clusters.',
    ],
  }),
];

export default questions;
