import type { Question } from '../../../src/content/types.ts';
import { mc, mr } from '../helpers.ts';

const questions: Question[] = [
  mc({
    id: 'message-quay-001',
    building: 'message-quay',
    bullets: ['2.1-K5'],
    d: 1,
    tags: ['trap:sqs-sns-eventbridge-kinesis'],
    stem: 'A company wants its applications to react to events from AWS services and SaaS applications. Rules must select events and send them to targets, and the company wants a serverless service with the LEAST operational overhead. Which service BEST meets these requirements?',
    correct: ['Amazon EventBridge, with rules that send matching events to targets', 'EventBridge is a serverless service that connects application components with events, and a rule specifies which events go to which targets.'],
    wrong: [
      ['Amazon SQS, with a queue that each application polls for events', 'A queue buffers messages for consumers and does not select events by rules and route them to targets.'],
      ['Amazon Kinesis Data Streams, with a stream that each application reads', 'A stream collects and processes large streams of data records, and the applications would have to implement their own routing.'],
      ['AWS Step Functions, with a workflow that waits for each event to arrive', 'Step Functions coordinates the steps of a workflow and is not a service for routing events from sources to targets.'],
    ],
    slot: 0,
    evidence: [
      'eda-overview|Amazon EventBridge is recommended when you want to build an application that reacts to events from SaaS applications, AWS services, or custom applications.',
      'eventbridge-what-is|EventBridge is a serverless service that uses events to connect application components together, making it easier for you to build scalable event-driven applications.',
      'eventbridge-rules|A rule specifies which events to send to which targets for processing.',
    ],
  }),
  mc({
    id: 'message-quay-002',
    building: 'message-quay',
    bullets: ['2.1-K5'],
    d: 2,
    stem: 'A company wants an AWS Lambda function to run whenever any Amazon EC2 instance in the account is terminated. The company wants the LEAST custom code and no polling of the EC2 API. Which solution meets these requirements?',
    correct: ['Create an Amazon EventBridge rule with an event pattern that matches the terminated state and set the function as its target', 'The rule matches EC2 instance state-change events pushed by EventBridge, so no code polls for the change.'],
    wrong: [
      ['Invoke a function every minute that calls the EC2 describe API and compares the instance list with the last result', 'This polls the API and needs custom comparison code, which the company wants to avoid.'],
      ['Install a script on every instance that writes a record to an Amazon Kinesis data stream during shutdown', 'This needs custom code on each instance and misses instances that fail without running a shutdown script.'],
      ['Install an agent on every instance that publishes to an Amazon SNS topic when the operating system shuts down', 'This needs custom code on each instance, and an instance that fails abruptly never publishes anything.'],
    ],
    slot: 1,
    evidence: [
      'eventbridge-patterns|The following event pattern selects all Amazon EC2 instance-termination events.',
      'eda-overview|You no longer need to write custom code to poll, filter, and route events; the event router will automatically filter and push events to consumers.',
    ],
  }),
  mr({
    id: 'message-quay-003',
    building: 'message-quay',
    bullets: ['2.1-K5'],
    d: 2,
    tags: ['trap:sqs-sns-eventbridge-kinesis'],
    stem: 'A company receives events from AWS services. Events with certain values in the event body must start two AWS Lambda functions at the same time, and the company does not want to pay for continuous polling. The company wants the LEAST operational overhead. Which TWO actions meet these requirements? (Choose two.)',
    correct: [
      ['Create an Amazon EventBridge rule with an event pattern that matches the required fields of the events', 'Rules filter on event data before pushing events to consumers, so only the events with the required values are delivered.'],
      ['Add both Lambda functions as targets of the same rule so that they run in parallel', 'A single rule can send an event to multiple targets, which then run in parallel.'],
    ],
    wrong: [
      ['Run an Amazon EC2 instance that polls for the events and forwards each one to the functions', 'Polling and forwarding code on an instance adds operational overhead and continuous polling.'],
      ['Create a scheduled rule that invokes a function every minute to check for new events', 'A schedule polls on a timer instead of reacting to events as they happen.'],
      ['Create an Amazon Kinesis data stream and write one application to read it for each function', 'This adds stream capacity and consumer applications to manage, where a rule can route events directly.'],
    ],
    slots: [0, 2],
    evidence: [
      'eda-overview|EventBridge uses a predefined schema for events and allows you to create rules that are applied across the entire event body to filter before pushing to consumers.',
      'eventbridge-rules|A single rule can send an event to multiple targets, which then run in parallel.',
      'eda-overview|This way, you’re not paying for continuous polling to check for an event.',
    ],
  }),
  mc({
    id: 'message-quay-004',
    building: 'message-quay',
    bullets: ['2.1-K5'],
    d: 3,
    tags: ['trap:sqs-sns-eventbridge-kinesis'],
    stem: 'A company wants to take change records from an Amazon DynamoDB stream, enrich them with extra data, and deliver the resulting events to five consumer applications, each of which is selected by rules on the event contents. The company wants the LEAST custom code. Which solution BEST meets these requirements?',
    correct: ['Create an Amazon EventBridge pipe that reads the stream and sends events to an event bus whose rules select the consumers', 'A pipe handles the single source with enrichment, and an event bus then routes events to multiple targets according to its rules.'],
    wrong: [
      ['Create one Amazon EventBridge pipe that reads the stream and has all five consumers as its targets', 'Each pipe delivers events from a single source to a single target, so one pipe cannot feed five consumers.'],
      ['Send the records to one Amazon SQS queue that all five consumer applications poll', 'A queue typically processes each message through a single subscriber, so the five consumers would not all receive each event.'],
      ['Write an AWS Lambda function that reads the stream, enriches the records and calls the five consumers', 'This is custom code that couples the function to every consumer, which the company wants to avoid.'],
    ],
    slot: 2,
    evidence: [
      'eventbridge-what-is|EventBridge Pipes is intended for point-to-point integrations; each pipe receives events from a single source for processing and delivery to a single target.',
      'eventbridge-what-is|Pipes also include support for advanced transformations and enrichment of events prior to delivery to a target.',
      'eventbridge-what-is|A common use case is to create a pipe with an event bus as its target; the pipe sends events to the event bus, which then sends those events on to multiple targets.',
      'sqs-what-is|It processes messages through a single subscriber typically, ideal for workflows where order and loss prevention are critical.',
    ],
  }),
  mc({
    id: 'message-quay-005',
    building: 'message-quay',
    bullets: ['2.1-K11'],
    d: 1,
    tags: ['trap:sqs-sns-eventbridge-kinesis'],
    stem: 'A web tier accepts image uploads, and a separate fleet of workers resizes the images. During sales, uploads arrive faster than the workers can resize them, and requests must not be lost if the workers are briefly unavailable. Which solution BEST decouples the two tiers?',
    correct: ['Send a message for each upload to an Amazon SQS queue that the workers poll when they are ready', 'A queue buffers requests so each worker can take messages when ready, and the queue absorbs spikes without losing messages.'],
    wrong: [
      ['Publish a message for each upload to an Amazon SNS topic that the workers subscribe to over HTTPS', 'A topic pushes messages to subscribers, so messages can be lost when subscribers are offline unless a queue holds them.'],
      ['Have the web tier send every upload to the workers through an Application Load Balancer', 'The tiers stay directly coupled, so a slow or unavailable worker fails the upload request.'],
      ['Add more web servers so that each upload is resized inline before the response returns', 'Resizing stays tied to the request, and spikes still overload the servers with no buffer between the tiers.'],
    ],
    slot: 3,
    evidence: [
      'sqs-what-is|Scalability – Amazon SQS can process each buffered request independently, scaling transparently to handle any load increases or spikes without any provisioning instructions.',
      'sqs-what-is|To prevent message loss when subscribers are offline, integrating Amazon SNS with Amazon SQS queue messages ensures consistent delivery.',
    ],
  }),
  mc({
    id: 'message-quay-006',
    building: 'message-quay',
    bullets: ['2.1-K11', '2.1-S3'],
    d: 2,
    tags: ['trap:sqs-sns-eventbridge-kinesis'],
    stem: 'When an order is placed, the same message must reach a fulfillment service, an analytics service and a test environment. Each consumer must work at its own pace and must not lose messages while it is offline. The company wants the LEAST operational overhead. Which solution meets these requirements?',
    correct: ['Publish the message to an Amazon SNS topic and subscribe a separate Amazon SQS queue for each consumer', 'The topic replicates the message to every queue, and each queue holds messages for its consumer until it is ready.'],
    wrong: [
      ['Send the message to one Amazon SQS queue that all three consumers poll', 'A queue typically processes each message through a single subscriber, so the consumers would not each receive the message.'],
      ['Publish the message to an Amazon SNS topic and subscribe each consumer directly by its own HTTPS endpoint', 'Subscribers that are offline can miss messages, because no queue holds them for later processing.'],
      ['Have the order service call the endpoint of each consumer in turn and retry on failure', 'The order service stays coupled to every consumer, and the retry logic is custom code that it must maintain.'],
    ],
    slot: 0,
    evidence: [
      'sns-what-is|The Fanout scenario is when a message published to an SNS topic is replicated and pushed to multiple endpoints, such as Firehose delivery streams, Amazon SQS queues, HTTP(S) endpoints, and Lambda functions.',
      'sqs-what-is|It processes messages through a single subscriber typically, ideal for workflows where order and loss prevention are critical.',
      'sns-sqs-fanout|The messages also persist in an Amazon SQS queue for other applications to process later.',
    ],
  }),
  mr({
    id: 'message-quay-007',
    building: 'message-quay',
    bullets: ['2.1-K11'],
    d: 2,
    stem: 'An application processes messages from an Amazon SQS standard queue. Some messages fail repeatedly because of unexpected content. The company wants to set the failed messages aside so that engineers can examine them, while the main queue keeps flowing. Which TWO actions BEST meet these requirements? (Choose two.)',
    correct: [
      ['Create a second queue in the same AWS account and Region and configure it as the dead-letter queue of the source queue', 'A dead-letter queue collects messages that are not processed successfully, and it must be in the same account and Region as its source queue.'],
      ['Set a redrive policy with a maxReceiveCount high enough to allow sufficient retries before a message moves', 'The redrive policy sets how many times a message can be received before it moves, and a high enough value keeps the system resilient to errors.'],
    ],
    wrong: [
      ['Create the dead-letter queue in a different AWS Region so that it survives a Regional outage', 'A dead-letter queue must be in the same AWS account and Region as the source queue.'],
      ['Set the maxReceiveCount to 1 so that a single failure moves the message', 'One failure to receive a message would move it, which gives no room for retries after temporary errors.'],
      ['Delete each message that fails once, and log the message identifier', 'The messages would be lost and the engineers could not examine their contents.'],
    ],
    slots: [3, 4],
    evidence: [
      'sqs-dlq|Amazon SQS supports dead-letter queues (DLQs), which source queues can target for messages that are not processed successfully.',
      'sqs-dlq|The dead-letter queue must be in the same AWS account and Region as the source queue.',
      'sqs-dlq|To ensure that your system is resilient against errors, set the maxReceiveCount high enough to allow for sufficient retries.',
    ],
  }),
  mc({
    id: 'message-quay-008',
    building: 'message-quay',
    bullets: ['2.1-K11'],
    d: 3,
    tags: ['trap:sqs-sns-eventbridge-kinesis'],
    stem: 'An e-commerce company must process the events of each customer in the exact order in which they were sent. Events of different customers can be processed in parallel by many consumers, and duplicates must not be introduced into the queue. Which solution BEST meets these requirements?',
    correct: ['An Amazon SQS FIFO queue that uses the customer ID as the message group ID', 'A FIFO queue preserves the order of messages and adds no duplicates, and message groups provide separate ordered streams within one queue.'],
    wrong: [
      ['An Amazon SQS standard queue whose consumers sort the messages by timestamp', 'A standard queue can deliver more than one copy of a message and out of order, so the consumers would have to correct this themselves.'],
      ['One Amazon SQS standard queue for each customer, each read by a single consumer', 'Standard queues make only a best-effort attempt at ordering and can deliver duplicates, whatever the number of queues.'],
      ['An Amazon SNS standard topic with one Amazon SQS standard queue subscribed for all events', 'Standard queues and topics do not strictly preserve order, and the queue can still receive duplicates.'],
    ],
    slot: 1,
    evidence: [
      'sqs-fifo|The order in which messages are sent and received is strictly preserved and a message is delivered once and remains unavailable until a consumer processes and deletes it.',
      'sqs-fifo|Additionally, FIFO queues support message groups that allow multiple ordered message groups within a single queue.',
      'sqs-standard|Standard queues ensure at-least-once message delivery, but due to the highly distributed architecture, more than one copy of a message might be delivered, and messages may occasionally arrive out of order.',
    ],
  }),
  mc({
    id: 'message-quay-009',
    building: 'message-quay',
    bullets: ['2.1-K11'],
    d: 1,
    stem: 'A company runs its own Apache ActiveMQ message broker whose applications use JMS and AMQP. It wants a managed broker on AWS and does not want to rewrite the messaging code of the applications. Which service BEST meets these requirements?',
    correct: ['Amazon MQ with an Apache ActiveMQ broker', 'Amazon MQ is a managed message broker service for ActiveMQ, and existing brokers can be migrated without rewriting messaging code.'],
    wrong: [
      ['Amazon SQS with standard queues', 'SQS is a queue service that applications use through its own API, so the applications would need new messaging code.'],
      ['Amazon SNS with topics for each application', 'SNS is a publish and subscribe service and is not a managed broker for JMS and AMQP applications.'],
      ['Amazon EventBridge with an event bus', 'EventBridge routes events to targets and is not a message broker that supports JMS and AMQP clients.'],
    ],
    slot: 2,
    evidence: [
      'mq-what-is|You can create a new Amazon MQ broker using industry standard messaging protocols, or migrate existing message brokers to Amazon MQ without rewriting messaging code.',
      'sqs-what-is|We recommend Amazon MQ for migrating applications from existing message brokers that rely on compatibility with APIs such as JMS or protocols such as Advanced Message Queuing Protocol (AMQP), MQTT, OpenWire, and Simple Text Oriented Message Protocol (STOMP).',
    ],
  }),
  mc({
    id: 'message-quay-010',
    building: 'message-quay',
    bullets: ['2.1-K11'],
    d: 2,
    stem: 'Consumers call ReceiveMessage on an Amazon SQS queue in a continuous loop, and most of the calls return empty responses, which increases the cost of using the queue. The company wants the LOWEST cost with the LEAST change to the consumers. Which solution meets these requirements?',
    correct: ['Enable long polling by setting the receive wait time of the queue to more than 0 seconds', 'Long polling waits until a message is available, which reduces the number of empty responses and lowers cost.'],
    wrong: [
      ['Increase the visibility timeout of the queue so that messages stay hidden for longer', 'The visibility timeout hides received messages from other consumers and does not change the number of empty responses.'],
      ['Reduce the message retention period of the queue so that old messages are removed sooner', 'The retention period controls how long messages are kept, and the empty ReceiveMessage calls would continue.'],
      ['Keep short polling and add a delay queue that holds each new message before delivery', 'A delay makes messages available later and does not reduce the number of empty responses from polling.'],
    ],
    slot: 3,
    evidence: [
      'sqs-polling|Long polling helps reduce the cost of using Amazon SQS by reducing the number of empty responses (when there are no messages available for a ReceiveMessage request) and false empty responses (when messages are available but aren\'t included in a response).',
      'sqs-polling|When the wait time for the ReceiveMessage API action is greater than 0, long polling is in effect.',
    ],
  }),
  mc({
    id: 'message-quay-011',
    building: 'message-quay',
    bullets: ['2.1-K11'],
    d: 2,
    stem: 'Workers need about two minutes to process each message from an Amazon SQS queue that uses default settings. Other workers keep receiving the same message while the first worker is still processing it, so work is duplicated. Which change BEST fixes this with the LEAST effort?',
    correct: ['Increase the visibility timeout of the queue to more than the time the workers need to process a message', 'A received message stays hidden from other consumers for the visibility timeout, and the default is 30 seconds, which is shorter than the processing time.'],
    wrong: [
      ['Enable long polling on the queue so that the workers wait longer for new messages to arrive before they return', 'Long polling reduces empty responses and does not stop a message from becoming visible again during processing.'],
      ['Extend the message retention period of the queue to the maximum value', 'The retention period controls how long messages stay in the queue and does not hide a message that is being processed.'],
      ['Attach a dead-letter queue that receives each message after its first receive', 'This would move messages away after the first receive, even though they are still being processed correctly.'],
    ],
    slot: 0,
    evidence: [
      'sqs-visibility|When you receive a message from an Amazon SQS queue, it remains in the queue but becomes temporarily invisible to other consumers.',
      'sqs-visibility|The default visibility timeout for a queue is 30 seconds, but you can adjust this to match the time your application needs to process and delete a message.',
      'sqs-visibility|If you don\'t delete it before the timeout expires, the message becomes visible again in the queue and can be retrieved by another consumer.',
    ],
  }),
  mc({
    id: 'message-quay-012',
    building: 'message-quay',
    bullets: ['2.1-K16'],
    d: 1,
    tags: ['trap:sqs-sns-eventbridge-kinesis'],
    stem: 'An order process has ordered steps: validate payment, reserve stock and send a confirmation. It needs branching, automatic retries and a console view where engineers can visualize and debug each run, with the LEAST custom orchestration code. Which service BEST meets these requirements?',
    correct: ['AWS Step Functions, with a workflow of ordered states', 'Step Functions workflows are made of ordered states, support Retry and Catch, and can be visualized and debugged in the console.'],
    wrong: [
      ['Amazon SQS, with a queue between the steps of the process', 'A queue buffers messages between components and does not sequence steps, branch or show a visual run of a process.'],
      ['Amazon SNS, with a topic for each step of the process', 'A topic delivers a message to subscribers and does not coordinate ordered steps or retries.'],
      ['Amazon EventBridge, with a rule for each step of the process', 'EventBridge routes events to targets and does not hold the sequence and state of a multi-step process.'],
    ],
    slot: 1,
    evidence: [
      'stepfunctions|In the Step Functions\' console, you can visualize, edit, and debug your application’s workflow.',
      'stepfunctions|Error handling (Retry / Catch) – You can retry failed tasks, or catch failed tasks and automatically run alternative steps.',
      'stepfunctions|Orchestrate tasks – You can create workflows that orchestrate a series of tasks, or steps, in a specific order.',
    ],
  }),
  mc({
    id: 'message-quay-013',
    building: 'message-quay',
    bullets: ['2.1-K16'],
    d: 2,
    stem: 'A loan-approval process can take several weeks because it waits for a manager to sign off. Each step must run exactly once, and auditors need the execution history of every run. The company wants the LEAST custom code. Which solution meets these requirements?',
    correct: ['A Standard workflow in AWS Step Functions that waits for a callback with a task token', 'Standard workflows are long-running and auditable with exactly-once execution, and a task token lets the workflow wait for the approval.'],
    wrong: [
      ['An Express workflow in AWS Step Functions that waits for a callback with a task token', 'Express workflows run for up to five minutes and have at-least-once execution, which does not fit weeks of waiting.'],
      ['A chain of AWS Lambda functions in which each function sleeps until the approval arrives', 'This is custom waiting code and has no execution history that auditors can inspect for each run.'],
      ['An Amazon SQS queue whose consumers keep each message hidden until the manager responds', 'A queue has no workflow history, and keeping messages hidden for weeks is custom logic that the company would maintain.'],
    ],
    slot: 2,
    evidence: [
      'stepfunctions|Standard workflows are ideal for long-running, auditable workflows, as they show execution history and visual debugging.',
      'stepfunctions|Standard workflows have exactly-once workflow execution and can run for up to one year.',
      'stepfunctions|Express workflows have at-least-once workflow execution and can run for up to five minutes.',
      'stepfunctions|With a callback and a task token, you can have Step Functions wait until the customers friend confirms the transfer, and then Step Functions will continue the workflow to notify the banking customer that the transfer has completed.',
    ],
  }),
  mc({
    id: 'message-quay-014',
    building: 'message-quay',
    bullets: ['2.1-K16'],
    d: 3,
    stem: 'A company receives a very high rate of sensor readings. Each reading starts a short workflow that finishes within seconds. Every step is idempotent, so a step that occasionally runs more than once does no harm. The company wants the workflow type that BEST fits this high-event-rate processing. Which solution meets these requirements?',
    correct: ['An Express workflow in AWS Step Functions that runs each reading as its own execution', 'Express workflows are ideal for high-event-rate workloads such as streaming data processing, and at-least-once execution is acceptable for idempotent steps.'],
    wrong: [
      ['A Standard workflow in AWS Step Functions for every reading, because it runs each step exactly once', 'Standard workflows are meant for long-running, auditable workflows, not high-event-rate streaming workloads.'],
      ['A Standard workflow in AWS Step Functions with a Wait state between the steps', 'A Wait state adds no benefit for short executions, and Standard remains the type for long-running, auditable workflows.'],
      ['An AWS Lambda function that calls the steps one after another in code', 'This moves the sequencing into custom code instead of using a workflow service for the high-event-rate processing.'],
    ],
    slot: 3,
    evidence: [
      'stepfunctions|Express workflows are ideal for high-event-rate workloads, such as streaming data processing and IoT data ingestion.',
      'stepfunctions|This means that one or more steps in an Express Workflow can potentially run more than once, while each step in the workflow executes at least once.',
      'stepfunctions|Standard workflows are ideal for long-running, auditable workflows, as they show execution history and visual debugging.',
    ],
  }),
  mr({
    id: 'message-quay-015',
    building: 'message-quay',
    bullets: ['2.1-K16'],
    d: 2,
    stem: 'A credit-limit request workflow calls a validation service that sometimes fails on the first attempt. Requests above the customer\'s pre-approved limit must go to a manager, and all other requests must be approved automatically. The company wants the LEAST custom code. Which TWO AWS Step Functions capabilities meet these requirements? (Choose two.)',
    correct: [
      ['A Retry configuration on the validation task', 'A failed task can be retried, so a first failure of the validation service does not need custom code.'],
      ['A Choice state that branches on the requested amount', 'A Choice state decides on the input of the state, so large requests can go to a manager and others be approved automatically.'],
    ],
    wrong: [
      ['A Map state that runs the same steps on every item of a dataset', 'A Map state iterates over the items of a dataset, and the requirement is a decision based on one request.'],
      ['A Parallel state that runs the validation and the manager approval at the same time', 'A Parallel state runs steps at the same time, whereas only large requests should reach a manager.'],
      ['An Express workflow type so that the approval step can wait for several days', 'Express workflows can run for up to five minutes, which is not enough to wait for a manager.'],
    ],
    slots: [1, 2],
    evidence: [
      'stepfunctions|Error handling (Retry / Catch) – You can retry failed tasks, or catch failed tasks and automatically run alternative steps.',
      'stepfunctions|Choose tasks based on data – Using a Choice state, you can have Step Functions make decisions based on the state’s input.',
      'stepfunctions|Express workflows have at-least-once workflow execution and can run for up to five minutes.',
    ],
  }),
  mc({
    id: 'message-quay-016',
    building: 'message-quay',
    bullets: ['2.1-S3'],
    d: 2,
    tags: ['trap:sqs-sns-eventbridge-kinesis'],
    stem: 'A company continuously collects website clickstream records. Two applications must read the same records in real time, concurrently and independently: one computes running aggregates and the other archives the raw records to Amazon S3. Which service BEST meets these requirements?',
    correct: ['Amazon Kinesis Data Streams, with one stream that both applications read', 'Kinesis Data Streams collects and processes large streams of data records in real time, and multiple applications can consume the same stream independently.'],
    wrong: [
      ['One Amazon SQS standard queue that both applications poll for the clickstream records', 'A queue typically processes each message through a single subscriber, so the two applications would split the records instead of each reading all of them.'],
      ['Amazon EventBridge with a custom event bus', 'EventBridge routes events from sources to targets and is not the service for collecting and processing large streams of data records.'],
      ['Amazon MQ with a queue for each application', 'Amazon MQ is recommended for migrating applications from existing brokers, and there is no existing broker here.'],
    ],
    slot: 0,
    evidence: [
      'kinesis-streams|You can use Amazon Kinesis Data Streams to collect and process large streams of data records in real time.',
      'kinesis-streams|Multiple Kinesis Data Streams applications can consume data from a stream, so that multiple actions, like archiving and processing, can take place concurrently and independently.',
      'sqs-what-is|It processes messages through a single subscriber typically, ideal for workflows where order and loss prevention are critical.',
    ],
  }),
  mc({
    id: 'message-quay-017',
    building: 'message-quay',
    bullets: ['2.1-S3'],
    d: 2,
    tags: ['trap:sqs-sns-eventbridge-kinesis'],
    stem: 'A news application must send each breaking-news message to a very large number of subscribed endpoints, including mobile push notifications and email addresses. Messages come from many publishers at high throughput and with low latency, and the message format is not fixed. Which service BEST meets these requirements?',
    correct: ['Amazon SNS, with a topic that the endpoints subscribe to', 'SNS suits high-throughput, low-latency messages with very high fanout, its topics do not depend on a message schema, and it supports push and email endpoints.'],
    wrong: [
      ['Amazon EventBridge, with a rule for each subscribed endpoint', 'EventBridge uses a predefined schema for events and is recommended for reacting to events from SaaS applications, AWS services or custom applications.'],
      ['Amazon SQS, with one queue for each subscribed endpoint', 'Queues are polled by consumers and do not push messages to mobile devices or email addresses.'],
      ['Amazon Kinesis Data Streams, with a stream that each endpoint reads', 'A stream is read by consumer applications and does not push messages to mobile devices or email addresses.'],
    ],
    slot: 1,
    evidence: [
      'eda-overview|Amazon SNS is recommended when you want to build an application that reacts to high throughput and low latency events published by other applications, microservices, or AWS services, or for applications that need very high fanout (thousands or millions of endpoints).',
      'eda-overview|SNS topics are agnostic to the event schema coming through.',
      'sns-what-is|Subscribers to an SNS topic can receive messages through different endpoints, depending on their use case, such as: Amazon SQS Lambda HTTP(S) endpoints Email Mobile push notifications Mobile text messages (SMS)',
    ],
  }),
  mc({
    id: 'message-quay-018',
    building: 'message-quay',
    bullets: ['2.1-S3'],
    d: 3,
    stem: 'A payment service reads messages from an Amazon SQS standard queue, which must remain a standard queue. Occasionally the same message is delivered twice and the customer is charged twice. The company wants to prevent duplicate charges with the LEAST change to the architecture. Which solution meets these requirements?',
    correct: ['Make the charge operation idempotent by sending an idempotency token with each charge request', 'An idempotent service returns the same result for repeated identical requests, so a duplicate message does not charge the customer twice.'],
    wrong: [
      ['Raise the visibility timeout of the queue to the maximum so that no message is delivered again', 'There is no absolute guarantee that a message is not delivered more than once, because of the at-least-once delivery model.'],
      ['Enable long polling on the queue so that consumers receive each message only once', 'Long polling reduces empty responses and does not change the at-least-once delivery of standard queues.'],
      ['Run the consumer on a single instance so that two consumers never see the same message', 'A standard queue can still deliver more than one copy of a message to a single consumer.'],
    ],
    slot: 2,
    evidence: [
      'sqs-standard|Standard queues ensure at-least-once message delivery, but due to the highly distributed architecture, more than one copy of a message might be delivered, and messages may occasionally arrive out of order.',
      'waf-idempotent|An idempotent service promises that each request is processed exactly once, such that making multiple identical requests has the same effect as making a single request.',
      'waf-idempotent|To do this, clients can issue API requests with an idempotency token, which is used whenever the request is repeated.',
    ],
  }),
  mr({
    id: 'message-quay-019',
    building: 'message-quay',
    bullets: ['2.1-S3'],
    d: 3,
    stem: 'An order API calls three downstream services synchronously over HTTP, and the services share one database. An outage in one service now fails orders, and retries sometimes create duplicate records. The company wants to loosely couple the services and make the system MOST resilient to failures in any one of them. Which THREE changes meet these requirements? (Choose three.)',
    correct: [
      ['Put an Amazon SQS queue between the API and each downstream service so that requests are buffered', 'An intermediate queue makes the interaction asynchronous, so an outage in one service no longer fails the API.'],
      ['Attach a dead-letter queue to each queue so that messages that cannot be processed are set aside', 'Messages that are not processed successfully move to a dead-letter queue, where they can be examined without blocking the others.'],
      ['Make the consumers idempotent by using idempotency tokens for each request', 'An idempotent consumer can safely handle a repeated request, so retries do not create duplicate records.'],
    ],
    wrong: [
      ['Keep the services calling one another directly and add retries to the API', 'Directly invoking APIs without asynchronous processing keeps the services tightly coupled.'],
      ['Move the services to larger Amazon EC2 instances so that they fail less often', 'Larger instances do not remove the dependency between the services, so an outage still fails orders.'],
      ['Let the services keep sharing the one database to exchange data with each other', 'Sharing data through a shared database reintroduces tight coupling and hinders scalability.'],
    ],
    slots: [1, 3, 4],
    evidence: [
      'waf-loose-coupling|Directly invoking APIs between workload tiers with no capability of failover or asynchronous processing of the request.',
      'waf-loose-coupling|Loosely coupled systems should avoid sharing data through shared databases or other forms of tightly coupled data storage, which can reintroduce tight coupling and hinder scalability.',
      'sqs-dlq|Amazon SQS supports dead-letter queues (DLQs), which source queues can target for messages that are not processed successfully.',
      'waf-idempotent|Using idempotency tokens in APIs, services can receive a mutating request one or more times without the need to create duplicate records or side effects.',
    ],
  }),
  mc({
    id: 'message-quay-020',
    building: 'message-quay',
    bullets: ['2.1-K5', '2.1-S3'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A company must invoke a function on a recurring cron schedule and also once at a specific future date. It wants flexible time windows for delivery and a limit on retries, using a serverless service with the LEAST operational overhead. Which solution meets these requirements?',
    correct: ['Amazon EventBridge Scheduler, with a recurring schedule and a one-time schedule', 'EventBridge Scheduler is a serverless scheduler with cron and rate expressions, one-time invocations, flexible time windows and retry limits.'],
    wrong: [
      ['An Amazon EC2 instance that runs cron jobs which call the function', 'The company would have to run and patch the instance, which adds operational overhead.'],
      ['An AWS Step Functions Standard workflow with a Wait state that holds until each invocation time', 'The company would have to build and maintain a workflow for every schedule instead of using a scheduler.'],
      ['An Amazon SQS queue that delivers each message after a delay', 'A queue does not create recurring cron schedules or invoke functions at a time the company defines.'],
    ],
    slot: 3,
    evidence: [
      'eventbridge-what-is|In addition, EventBridge provides EventBridge Scheduler, a serverless scheduler that allows you to create, run, and manage tasks from one central, managed service.',
      'eventbridge-what-is|With EventBridge Scheduler, you can create schedules using cron and rate expressions for recurring patterns, or configure one-time invocations.',
      'eventbridge-what-is|You can set up flexible time windows for delivery, define retry limits, and set the maximum retention time for failed API invocations.',
    ],
  }),
  mc({
    id: 'message-quay-021',
    building: 'message-quay',
    bullets: ['2.1-K11'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A consumer application of an Amazon SQS queue will be offline for planned maintenance for ten days. Messages that arrive in that time must not be deleted by the queue. The company wants the LEAST effort. Which change meets these requirements?',
    correct: ['Set the message retention period of the queue to the maximum of 14 days', 'The default retention period is 4 days, and it can be set to a value up to 14 days, so messages survive ten days.'],
    wrong: [
      ['Leave the default message retention period, which keeps messages for ten days', 'The default message retention period is 4 days, so older messages are deleted automatically.'],
      ['Set the visibility timeout of the queue to the maximum so that messages stay hidden', 'The visibility timeout hides received messages from other consumers and does not extend how long messages are kept.'],
      ['Enable long polling with the longest wait time so that the queue waits for the consumer', 'Long polling reduces empty responses and does not extend the time that messages stay in the queue.'],
    ],
    slot: 0,
    evidence: [
      'sqs-what-is|Amazon SQS automatically deletes messages that have been in a queue for more than the maximum message retention period.',
      'sqs-what-is|The default message retention period is 4 days.',
      'sqs-what-is|However, you can set the message retention period to a value from 60 seconds to 1,209,600 seconds (14 days) using the SetQueueAttributes action.',
    ],
  }),
  mc({
    id: 'message-quay-022',
    building: 'message-quay',
    bullets: ['2.1-K16', '2.1-S3'],
    d: 3,
    tags: ['mock-reserve'],
    stem: 'When a customer orders thirty items, the system must run the same set of workflow steps on each item, and the iterations should run in parallel so that the whole order is prepared quickly. The company wants the LEAST custom code. Which solution meets these requirements?',
    correct: ['An AWS Step Functions workflow that uses a Map state over the items of the order', 'A Map state runs a set of workflow steps on each item in a dataset, and the iterations run in parallel.'],
    wrong: [
      ['An AWS Step Functions workflow that uses a Choice state for each item of the order', 'A Choice state decides between branches based on its input and does not repeat the steps for each item.'],
      ['An AWS Step Functions workflow that uses a Parallel state with thirty hand-written branches', 'A Parallel state runs defined steps in parallel on the input, and thirty branches would be hand-built and fixed in number.'],
      ['An Amazon SNS topic that publishes the order to thirty subscribed AWS Lambda functions', 'Each function would receive the whole order, and no workflow coordinates the steps for each item.'],
    ],
    slot: 1,
    evidence: [
      'stepfunctions|Dynamically process data elements – Using a Map state, Step Functions can run a set of workflow steps on each item in a dataset.',
      'stepfunctions|The iterations run in parallel, which makes it possible to process a dataset quickly.',
      'stepfunctions|Choose tasks based on data – Using a Choice state, you can have Step Functions make decisions based on the state’s input.',
    ],
  }),
];

export default questions;
