import type { Question } from '../../../src/content/types.ts';
import { mc, mr } from '../helpers.ts';

const questions: Question[] = [
  mc({
    id: 'purpose-built-workshop-001',
    building: 'purpose-built-workshop',
    bullets: ['2.1-K2'],
    d: 1,
    stem: 'A company\'s trading partners upload daily files with SFTP clients that the partners cannot change. The company wants the files to land in an Amazon S3 bucket and does not want to run or patch SFTP servers. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Create an AWS Transfer Family server that uses the SFTP protocol and stores files in the S3 bucket', 'Transfer Family is a fully managed service for SFTP transfers directly into AWS storage, and partners can keep their existing client configurations.'],
    wrong: [
      ['Run an SFTP server on an Amazon EC2 instance and copy each uploaded file to the S3 bucket', 'The company would run, patch and scale the SFTP server itself, which the company wants to avoid.'],
      ['Create an AWS DataSync task and ask each partner to start it from the partner\'s SFTP client', 'DataSync transfers files between storage systems and AWS services and does not give partners an SFTP endpoint.'],
      ['Enable Amazon S3 Transfer Acceleration on the bucket and ask partners to upload to the accelerate endpoint', 'Partners would have to switch from SFTP to the S3 accelerate endpoint, and they cannot change their clients.'],
    ],
    slot: 0,
    evidence: [
      'transfer-what-is|AWS Transfer Family offers fully managed support for the transfer of files over SFTP, AS2, FTPS, FTP, and web browser-based transfers directly into and out of AWS storage services.',
      'transfer-what-is|You can seamlessly migrate, automate, and monitor your file transfer workflows by maintaining existing client-side configurations for authentication, access, and firewalls',
      'datasync-how|The following diagram shows a high-level overview of DataSync transferring files between self-managed, on-premises storage systems and AWS services.',
    ],
  }),
  mc({
    id: 'purpose-built-workshop-002',
    building: 'purpose-built-workshop',
    bullets: ['2.1-K2'],
    d: 2,
    tags: ['trap:secrets-manager-vs-parameter-store'],
    stem: 'An application on Amazon ECS reads an Amazon RDS database password from a configuration file in its container image. A new policy requires the password to be rotated automatically every 30 days without rebuilding images or redeploying the application. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Store the password in AWS Secrets Manager, turn on automatic rotation and have the application retrieve it at runtime', 'Secrets Manager rotates credentials on a schedule, and because the application retrieves them at runtime, rotation needs no application update.'],
    wrong: [
      ['Store the password as a SecureString parameter in AWS Systems Manager Parameter Store and update it by hand each month', 'The manual update is not automatic rotation, and AWS recommends Secrets Manager for credentials that must rotate automatically.'],
      ['Store the password in a task definition environment variable and redeploy the tasks after each change', 'Every rotation would need a redeployment, which the company wants to avoid.'],
      ['Store the password in an Amazon S3 object and run a function each month to overwrite the object', 'The company would write and maintain the rotation code and the retrieval logic itself.'],
    ],
    slot: 1,
    evidence: [
      'secrets-intro|You replace hard-coded credentials with a runtime call to the Secrets Manager service to retrieve credentials dynamically when you need them.',
      'secrets-intro|Since the credentials are no longer stored with the application, rotating credentials no longer requires updating your applications and deploying changes to application clients.',
      'ssm-parameter-store|For secrets such as database credentials, API keys, or tokens, we recommend AWS Secrets Manager, which provides purpose built security controls including automatic rotation and cross-region replication.',
    ],
  }),
  mc({
    id: 'purpose-built-workshop-003',
    building: 'purpose-built-workshop',
    bullets: ['2.1-K2'],
    d: 2,
    tags: ['trap:sqs-sns-eventbridge-kinesis'],
    stem: 'An online store\'s checkout service calls an order-fulfillment service directly. During promotions, fulfillment slows down and checkout requests time out. The company wants checkout to accept orders even when fulfillment is slow or briefly offline, using a managed service with the LEAST operational overhead. Which solution BEST meets these requirements?',
    correct: ['Have checkout place each order in an Amazon SQS queue that the fulfillment service reads at its own pace', 'The queue buffers orders durably so checkout is decoupled from fulfillment, and it absorbs spikes without provisioning.'],
    wrong: [
      ['Have checkout publish each order to an Amazon SNS topic with the fulfillment service\'s HTTPS endpoint subscribed', 'A subscriber that is offline can miss messages when no queue holds them, so orders could be lost.'],
      ['Add more fulfillment servers in an Amazon EC2 Auto Scaling group behind the same direct call', 'Checkout would still call fulfillment directly, so an offline or slow service would still fail checkout requests.'],
      ['Put an Application Load Balancer between the two services and raise the checkout timeout', 'The services stay coupled, and a longer timeout only makes customers wait while fulfillment is unavailable.'],
    ],
    slot: 2,
    evidence: [
      'sqs-what-is|Amazon Simple Queue Service (Amazon SQS) offers a secure, durable, and available hosted queue that lets you integrate and decouple distributed software systems and components.',
      'sqs-what-is|Scalability – Amazon SQS can process each buffered request independently, scaling transparently to handle any load increases or spikes without any provisioning instructions.',
      'sqs-what-is|To prevent message loss when subscribers are offline, integrating Amazon SNS with Amazon SQS queue messages ensures consistent delivery.',
    ],
  }),
  mr({
    id: 'purpose-built-workshop-004',
    building: 'purpose-built-workshop',
    bullets: ['2.1-K2'],
    d: 2,
    tags: ['trap:sqs-sns-eventbridge-kinesis'],
    stem: 'Suppliers send purchase files to a company over FTPS. The company must store the files in Amazon S3 and have a processing application handle each file later. The application is sometimes offline for hours, and no file notification may be lost. The company wants managed services with the LEAST operational overhead. Which TWO actions meet these requirements? (Choose two.)',
    correct: [
      ['Create an AWS Transfer Family server that uses the FTPS protocol and stores the files in the S3 bucket', 'Transfer Family offers fully managed FTPS transfers directly into AWS storage, so there is no server to run.'],
      ['Send an S3 event notification for each new object to an Amazon SQS queue that the application reads when it is online', 'S3 can send event notifications to SQS queues, and the durable queue holds each message until the application is back.'],
    ],
    wrong: [
      ['Run an FTPS server on an Amazon EC2 instance that writes the files to the S3 bucket', 'The company would run, patch and scale the FTPS server itself.'],
      ['Send an S3 event notification to an Amazon SNS topic with the application\'s HTTPS endpoint as the subscriber', 'An offline subscriber can miss messages because no queue holds them, so notifications could be lost.'],
      ['Turn on Amazon S3 Transfer Acceleration and have the suppliers upload to the accelerate endpoint', 'Suppliers send files over FTPS, and Transfer Acceleration provides an S3 endpoint rather than an FTPS server.'],
    ],
    slots: [0, 3],
    evidence: [
      'transfer-what-is|AWS Transfer Family offers fully managed support for the transfer of files over SFTP, AS2, FTPS, FTP, and web browser-based transfers directly into and out of AWS storage services.',
      's3-event-notifications|Amazon S3 can send event notification messages to the following destinations.',
      's3-event-notifications|Amazon Simple Notification Service (Amazon SNS) topics Amazon Simple Queue Service (Amazon SQS) queues AWS Lambda function Amazon EventBridge',
      'sqs-what-is|To prevent message loss when subscribers are offline, integrating Amazon SNS with Amazon SQS queue messages ensures consistent delivery.',
    ],
  }),
  mc({
    id: 'purpose-built-workshop-005',
    building: 'purpose-built-workshop',
    bullets: ['2.1-K2'],
    d: 3,
    tags: ['trap:secrets-manager-vs-parameter-store'],
    stem: 'A company runs a payment application in one Region and keeps a warm standby in a second Region. Database credentials are rotated every 30 days. The standby application must read the current credentials from inside its own Region, even if the primary Region is unavailable, and the company does not want to write synchronization code. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Store the credentials in AWS Secrets Manager with automatic rotation and replicate the secret to the second Region', 'Replicas serve applications in the other Region, and rotation of the primary secret propagates the new value to every replica.'],
    wrong: [
      ['Store the credentials in the primary Region only and let the standby call that Region\'s Secrets Manager endpoint', 'The standby would depend on the primary Region, so it could not read credentials during a primary Region outage.'],
      ['Keep SecureString parameters in Parameter Store in both Regions and update each copy on a schedule', 'Parameter Store does not rotate the credentials automatically or replicate them, so the company would build the sync.'],
      ['Copy the secret to the second Region with a scheduled AWS Lambda function that the company writes', 'This is the custom synchronization code that the company wants to avoid.'],
    ],
    slot: 3,
    evidence: [
      'secrets-replicate|You can replicate your secrets in multiple AWS Regions to support applications spread across those Regions to meet Regional access and low latency requirements.',
      'secrets-replicate|If you turn on rotation for your primary secret, Secrets Manager rotates the secret in the primary Region, and the new secret value propagates to all of the associated replica secrets.',
      'ssm-parameter-store|For secrets such as database credentials, API keys, or tokens, we recommend AWS Secrets Manager, which provides purpose built security controls including automatic rotation and cross-region replication.',
    ],
  }),
  mc({
    id: 'purpose-built-workshop-006',
    building: 'purpose-built-workshop',
    bullets: ['2.1-S7'],
    d: 1,
    stem: 'A social networking company wants to recommend friends by traversing relationships among hundreds of millions of users. The queries must return results with low latency, and the company wants a fully managed database. Which database BEST fits this workload?',
    correct: ['Amazon Neptune, a fully managed graph database for highly connected datasets', 'Neptune is purpose-built for traversing large numbers of relationships and supports recommendation engines.'],
    wrong: [
      ['Amazon RDS for MySQL, with a table of friendships and many self-joins', 'RDS is built for structured data in tables, not for traversing large numbers of relationships.'],
      ['Amazon DynamoDB, with one item per user listing the user\'s friends', 'A key-value table fetches items by key, and it is not built for traversing relationship patterns.'],
      ['Amazon Redshift, with the friendships loaded into a data warehouse', 'Redshift is a data warehouse for large-scale analytics, not for low-latency relationship traversal.'],
    ],
    slot: 1,
    evidence: [
      'neptune-what-is|Amazon Neptune is a fast, reliable, fully managed graph database service that makes it easy to build and run applications that work with highly connected datasets.',
      'database-decision|Optimized for traversing and evaluating large numbers of relationships, and identifying patterns with minimal latency.',
    ],
  }),
  mc({
    id: 'purpose-built-workshop-007',
    building: 'purpose-built-workshop',
    bullets: ['2.1-S7'],
    d: 2,
    stem: 'A gaming company stores player session state and shopping-cart items for millions of concurrent users. Items are always read and written by player ID, load is unpredictable, and the company wants single-digit millisecond latency with no database servers to manage. Which database is the BEST fit?',
    correct: ['Amazon DynamoDB, a serverless key-value table keyed by player ID', 'DynamoDB is serverless with single-digit millisecond performance at any scale, and AWS suggests it for session stores and shopping carts.'],
    wrong: [
      ['Amazon RDS for PostgreSQL on a large Multi-AZ DB instance with read replicas', 'The company would size and manage DB instances, and it does not need a relational model for lookups by player ID.'],
      ['Amazon DocumentDB (with MongoDB compatibility) cluster that stores each session as a document', 'DocumentDB suits rich queries across document fields, which lookups by player ID do not need.'],
      ['Amazon Redshift cluster that stores each session as a row in a warehouse table', 'Redshift is a data warehouse for large-scale analytics, not a low-latency store for session lookups.'],
    ],
    slot: 2,
    evidence: [
      'dynamodb-what-is|Amazon DynamoDB is a serverless, fully managed, distributed NoSQL database with single-digit millisecond performance at any scale.',
      'database-decision|Use for workloads such as session stores or shopping carts.',
    ],
  }),
  mc({
    id: 'purpose-built-workshop-008',
    building: 'purpose-built-workshop',
    bullets: ['2.1-S7'],
    d: 2,
    stem: 'A company\'s catalog application stores product data as JSON-like documents in a self-managed MongoDB database. Developers run rich queries across the fields of the documents. The company wants a fully managed AWS database with the LEAST application change. Which solution BEST meets these requirements?',
    correct: ['Migrate the data to Amazon DocumentDB (with MongoDB compatibility)', 'DocumentDB is the purpose-built document database for JSON-like documents with rich querying across fields, with MongoDB compatibility.'],
    wrong: [
      ['Migrate the data to Amazon DynamoDB and remodel each document as key-value items', 'DynamoDB is a key-value database, so the document model and the field queries would have to be reworked.'],
      ['Migrate the data to Amazon RDS for MySQL and store each document in a text column', 'RDS is a relational database for structured data in tables, so the document queries would have to be rewritten.'],
      ['Migrate the data to Amazon Keyspaces (for Apache Cassandra) and rewrite the queries', 'Keyspaces is a wide-column database for Cassandra workloads and is not a document database.'],
    ],
    slot: 3,
    evidence: [
      'database-decision|Use when you want to store JSON-like documents with rich querying abilities across the fields of the documents.',
      'database-decision|Optimized for storing semi-structured data as documents with multilayered attributes.',
      'database-decision|Use when you need to migrate your on-premises Cassandra workloads, or when you need to process data at high speeds for applications that require single-digit millisecond latency.',
    ],
  }),
  mc({
    id: 'purpose-built-workshop-009',
    building: 'purpose-built-workshop',
    bullets: ['2.1-S7'],
    d: 3,
    stem: 'A microservices platform needs a primary database that keeps data in memory for microsecond reads and single-digit millisecond writes. Data must not be lost when a node fails or restarts, and the developers already use Valkey client libraries. Which solution meets these requirements with the LEAST application change?',
    correct: ['Amazon MemoryDB, which stores data durably across multiple Availability Zones', 'MemoryDB is a durable in-memory database with microsecond reads, Multi-AZ durability and Valkey and Redis OSS compatibility.'],
    wrong: [
      ['Amazon ElastiCache used as the store of record for the microservices', 'ElastiCache is an ephemeral cache for frequently accessed data, so it is not a durable primary database.'],
      ['Amazon DynamoDB tables that the microservices read through the AWS SDK', 'DynamoDB reads are single-digit millisecond and not microsecond, and the code would move off Valkey client libraries.'],
      ['Amazon RDS for MySQL on a large Multi-AZ DB instance with in-memory buffers', 'RDS is a disk-based relational database, so it does not give in-memory microsecond reads or Valkey compatibility.'],
    ],
    slot: 0,
    evidence: [
      'memorydb|Amazon MemoryDB is compatible with the popular open source data stores Valkey and Redis OSS, enabling you to quickly build applications using the same flexible and friendly data structures, APIs, and commands that they already use.',
      'memorydb|MemoryDB also stores data durably across multiple Availability Zones (AZs) using a Multi-AZ transactional log to enable fast failover, database recovery, and node restarts.',
      'database-decision|Optimized to support microsecond reads and sub-millisecond writes as an ephemeral cache for frequently accessed data.',
    ],
  }),
  mr({
    id: 'purpose-built-workshop-010',
    building: 'purpose-built-workshop',
    bullets: ['2.1-S7'],
    d: 3,
    stem: 'An e-commerce company is designing a new platform. The product catalog and user profiles are semi-structured JSON-like documents that need rich queries across fields. Product browsing needs low, predictable latency at a very high request rate. Inventory and order processing need a relational data model with transaction support. The company wants a purpose-built managed database for each need. Which THREE choices meet these requirements? (Choose three.)',
    correct: [
      ['Amazon DocumentDB (with MongoDB compatibility) for the catalog and user profiles', 'DocumentDB stores semi-structured documents and supports rich queries across their fields.'],
      ['Amazon DynamoDB for serving product browsing requests', 'DynamoDB provides low, predictable latency at very high request rates.'],
      ['Amazon Aurora for inventory and order processing', 'Aurora provides the relational data model and transaction support that inventory and orders need.'],
    ],
    wrong: [
      ['Amazon Neptune for inventory and order processing', 'Neptune is a graph database for highly connected datasets and not a relational database for transactions.'],
      ['Amazon Redshift for serving product browsing requests', 'Redshift is a data warehouse for analytics, not a store for low-latency browsing requests.'],
      ['Amazon ElastiCache as the only store for the user profiles', 'ElastiCache is an ephemeral cache for frequently accessed data, so profiles kept only there would not be durable.'],
    ],
    slots: [0, 3, 4],
    evidence: [
      'database-decision|in an ecommerce use case, you might use Amazon DocumentDB (for product catalogs and user profiles) for the flexibility that is provided by semi-structured data',
      'database-decision|You might also add Aurora into the mix for inventory and order processing, where a relational data model and transaction support are needed.',
      'dynamodb-what-is|DynamoDB is purpose-built and optimized for operational workloads that require consistent performance at any scale.',
    ],
  }),
  mc({
    id: 'purpose-built-workshop-011',
    building: 'purpose-built-workshop',
    bullets: ['2.1-S7'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A company runs an Apache Cassandra cluster on premises for a high-throughput application that needs single-digit millisecond latency. The company wants to move to a managed AWS database that keeps the Cassandra data model, with the LEAST operational overhead. Which service should the company choose?',
    correct: ['Amazon Keyspaces (for Apache Cassandra), the wide-column service for Cassandra workloads', 'Keyspaces is the purpose-built wide-column database for migrating on-premises Cassandra workloads with single-digit millisecond latency.'],
    wrong: [
      ['Amazon Neptune, loading the Cassandra tables as a graph', 'Neptune is a graph database for highly connected data and does not keep the Cassandra data model.'],
      ['Amazon RDS for PostgreSQL, loading the Cassandra tables as relational tables', 'RDS is a relational database for structured data, so the data model and application queries would change.'],
      ['Amazon ElastiCache, loading the Cassandra data into an in-memory cache', 'ElastiCache is an ephemeral cache and not a durable database for the Cassandra data.'],
    ],
    slot: 1,
    evidence: [
      'database-decision|Use when you need to migrate your on-premises Cassandra workloads, or when you need to process data at high speeds for applications that require single-digit millisecond latency.',
      'database-decision|Optimized for workloads that require heavy reads/writes and high throughput, coupled with low latency and linear scalability.',
    ],
  }),
  mc({
    id: 'purpose-built-workshop-012',
    building: 'purpose-built-workshop',
    bullets: ['2.1-K2'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A company exchanges purchase orders and invoices with retail partners using the AS2 protocol for business-to-business transactions. The files must be stored in Amazon S3, and the company does not want to run its own AS2 servers. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Use AWS Transfer Family with the AS2 protocol and an S3 bucket as the storage', 'Transfer Family offers fully managed AS2 support directly into AWS storage, and B2B transactions are a listed AS2 use case.'],
    wrong: [
      ['Run AS2 server software on an Amazon EC2 instance and copy received files to the bucket', 'The company would run, patch and scale the AS2 server itself.'],
      ['Create an Amazon SQS queue and ask each partner to send its documents as queue messages', 'A queue is a messaging service and does not provide an AS2 endpoint for the partners.'],
      ['Create an AWS DataSync task that copies the partners\' documents into the bucket on a schedule', 'DataSync moves data between storage systems and AWS and does not provide an AS2 endpoint for partners.'],
    ],
    slot: 0,
    evidence: [
      'transfer-what-is|AWS Transfer Family offers fully managed support for the transfer of files over SFTP, AS2, FTPS, FTP, and web browser-based transfers directly into and out of AWS storage services.',
      'transfer-what-is|The following are some common use cases for using Transfer Family with AS2: Workflows with compliance requirements that rely on having data protection and security features built into the protocol Supply chain logistics Payments workflows Business-to-business (B2B) transactions',
    ],
  }),
];

export default questions;
