import type { Question } from '../../../src/content/types.ts';
import { mc, mr } from '../helpers.ts';

const questions: Question[] = [
  mc({
    id: 'scaling-floodgate-001',
    building: 'scaling-floodgate',
    bullets: ['2.1-K6'],
    d: 1,
    stem: 'A company runs the stateless web tier of an application on one large Amazon EC2 instance. Traffic keeps growing, and the loss of that instance would take the application offline. The company wants capacity that grows with demand and survives the loss of an instance, with the LEAST manual effort. Which solution BEST meets these requirements?',
    correct: ['Place the instances in an Auto Scaling group across two Availability Zones behind an Application Load Balancer', 'Adding instances is horizontal scaling, which suits a stateless tier; the group replaces failed instances and launches capacity in another Availability Zone if one becomes unavailable, with no manual steps.'],
    wrong: [
      ['Change the instance to the next larger instance type each time the load grows', 'This is vertical scaling of a single instance, so one failure still takes the application offline and each resize is manual.'],
      ['Attach an additional Amazon EBS volume to the instance so that it can hold more of the working data', 'Storage does not add compute capacity, and the application would still run on a single instance that is a single point of failure.'],
      ['Launch a second instance by hand in another Availability Zone and change the DNS record whenever one fails', 'Both the capacity changes and the recovery steps are manual, which conflicts with the LEAST manual effort requirement.'],
    ],
    slot: 0,
    evidence: [
      'waf-stateless|In addition to server replacement, another benefit of stateless applications is that they can scale horizontally because any of the available compute resources (such as EC2 instances and AWS Lambda functions) can service any request.',
      'asg-benefits|If one Availability Zone becomes unavailable, Amazon EC2 Auto Scaling can launch instances in another one to compensate.',
      'asg-what-is|Amazon EC2 Auto Scaling automatically monitors the health and availability of your instances using EC2 health checks and replaces terminated or impaired instances to maintain your desired capacity.',
    ],
  }),
  mc({
    id: 'scaling-floodgate-002',
    building: 'scaling-floodgate',
    bullets: ['2.1-K6', '2.1-K15'],
    d: 2,
    stem: 'A company runs an order-processing application on a single Amazon RDS for PostgreSQL DB instance. CPU is saturated by a high volume of INSERT and UPDATE statements, while read traffic is small. The company accepts a short change during a maintenance window. Which action BEST addresses the bottleneck?',
    correct: ['Modify the DB instance to use a larger DB instance class', 'Write traffic can only be handled by the primary, so the way to add capacity for writes is to scale vertically by changing the DB instance size.'],
    wrong: [
      ['Create an RDS read replica and send the INSERT and UPDATE statements to it', 'A read replica is read-only, so it cannot accept the write statements that are saturating the primary.'],
      ['Enable Multi-AZ so that the standby replica takes a share of the write load', 'A standby replica exists for high availability and cannot serve traffic, so it does not relieve the primary.'],
      ['Place an Amazon CloudFront distribution in front of the application to absorb the traffic', 'A CDN caches content for viewers and does not reduce the number of write statements the database must process.'],
    ],
    slot: 1,
    evidence: [
      'rds-scaling-ha|With Amazon RDS, you can scale vertically by modifying your DB instance size to meet your performance and capacity requirements.',
      "rds-scaling-ha|Read replicas are read-only and can't handle write operations.",
      "rds-read-replicas|Unlike a read replica, a standby replica can't serve read traffic.",
    ],
  }),
  mc({
    id: 'scaling-floodgate-003',
    building: 'scaling-floodgate',
    bullets: ['2.1-K6'],
    d: 2,
    stem: "A web application keeps each user's shopping-cart session in memory on the Amazon EC2 instance that served the first request. The company wants to add and remove instances behind a load balancer so that any instance can serve any request, and a replaced instance must not lose carts. Which change BEST meets these requirements?",
    correct: ['Store the session data in an in-memory cache such as Amazon ElastiCache that all instances share', 'Offloading session state removes the dependence on local memory, so servers can be replaced at will and any instance can serve any request.'],
    wrong: [
      ['Turn on sticky sessions on the target group so that each user returns to the same instance', 'Stickiness binds a user to one target, so a replaced instance still loses its carts and not every instance can serve every user.'],
      ['Move the application to a larger instance type that can hold more sessions in memory', 'This scales one instance vertically, which keeps the state on that instance and cannot support adding and removing instances.'],
      ['Increase the deregistration delay so that instances being removed keep their sessions for longer', 'The delay only gives in-flight requests time to finish while the target stops receiving new requests, so the carts are still lost.'],
    ],
    slot: 2,
    evidence: [
      'waf-stateless|Systems should either not require state, or should offload state such that between different client requests, there is no dependence on locally stored data on disk and in memory.',
      'waf-stateless|This allows servers to be replaced at will without causing an availability impact.',
      'msa-data-store|Popular stores for session data are in-memory caches such as Memcached or Redis.',
      "alb-target-attrs|However, you can use the sticky session feature (also known as session affinity) to enable the load balancer to bind a user's session to a specific target.",
    ],
  }),
  mc({
    id: 'scaling-floodgate-004',
    building: 'scaling-floodgate',
    bullets: ['2.1-K6'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A company runs a licensed legacy application on one Amazon EC2 instance that has an Amazon EBS root volume. The application keeps its working set in memory, cannot run on more than one server, and is now memory-bound. The company wants to fix this with the LEAST change to the architecture. Which solution meets these requirements?',
    correct: ['Change the instance type of the existing instance to a larger, memory-optimized type', 'Resizing by changing the instance type adds memory to the same instance, which suits an application that cannot be spread across several servers.'],
    wrong: [
      ['Place the instance in an Auto Scaling group behind an Application Load Balancer', 'This is horizontal scaling and needs the application to run on several servers, which it cannot do.'],
      ['Add another Amazon EBS volume to the instance so that more data can be held', 'An extra volume adds storage and does not add the memory the application is short of.'],
      ['Put an Application Load Balancer in front of the instance so that the memory use is spread across requests', 'A load balancer distributes requests across several targets and cannot add memory to the single instance behind it.'],
    ],
    slot: 3,
    evidence: [
      'ec2-resize|If this is the case, you can resize your instance by changing its instance type.',
      'ec2-resize|To add additional storage to your instance without changing the instance type, add an EBS volume to the instance.',
    ],
  }),
  mr({
    id: 'scaling-floodgate-005',
    building: 'scaling-floodgate',
    bullets: ['2.1-K6', '2.1-K15'],
    d: 3,
    tags: ['trap:multi-az-vs-read-replicas'],
    stem: 'The web tier of a company application runs on stateless Amazon EC2 instances. At peak the web tier is CPU-bound, and an Amazon RDS for MySQL DB instance is saturated by product-catalogue read queries, while writes are modest. The company wants each tier to scale with the LEAST application redesign. Which TWO actions meet these requirements? (Choose two.)',
    correct: [
      ['Place the web instances in an Auto Scaling group behind an Application Load Balancer', 'A stateless tier scales horizontally, and the load balancer spreads requests across the instances as the group adds and removes them.'],
      ['Create RDS read replicas and direct the catalogue queries to them', 'Read replicas offload read-intensive work from the primary, and the application only has to point its read-only queries at the replicas.'],
    ],
    wrong: [
      ['Enable Multi-AZ so that the standby replica answers the catalogue queries', 'The standby replica in a Multi-AZ deployment cannot serve read traffic, so it does not relieve the read load.'],
      ['Replace the web tier with a single instance of the largest available instance type', 'This is vertical scaling of one server, which has a ceiling and leaves a single point of failure for the whole web tier.'],
      ['Configure the DB instance to add and remove read replicas automatically as read demand changes', 'RDS does not support autoscaling of read replicas, so they must be created and removed manually.'],
    ],
    slots: [1, 3],
    evidence: [
      'asg-what-is|You can use Elastic Load Balancing load balancing and health checks to ensure an even distribution of application traffic to your healthy instances.',
      'rds-scaling-ha|Amazon RDS provides horizontal scaling by using read replicas to offload read-intensive workloads and improve database performance.',
      "rds-read-replicas|Unlike a read replica, a standby replica can't serve read traffic.",
      "rds-read-replicas|RDS doesn't support autoscaling of read replicas, which is the automatic add or removing of read replicas as read demand changes.",
    ],
  }),
  mc({
    id: 'scaling-floodgate-006',
    building: 'scaling-floodgate',
    bullets: ['2.1-K9'],
    d: 1,
    stem: 'A company runs a web application on three Amazon EC2 instances in two Availability Zones. Clients must use one entry point, requests must be spread across the instances, and no request may be sent to an instance that has failed. The company wants the LEAST operational overhead. Which solution meets these requirements?',
    correct: ['Create an Application Load Balancer, register the instances in a target group, and configure health checks', 'The load balancer is the single point of contact, spreads requests across targets in several Availability Zones, and routes only to targets that pass health checks.'],
    wrong: [
      ['Run reverse proxy software on a separate instance that forwards each request to one of the three instances', 'The proxy is one more instance to patch, scale and keep available, and it becomes a single point of failure.'],
      ['Associate an Elastic IP address with the least busy instance and move it by hand when load shifts', 'Moving the address is manual work, and all clients would still reach one instance at a time instead of being spread.'],
      ['Publish the private IP address of every instance to clients and have each client retry on failure', 'Clients would have to track instance addresses and handle failures themselves, which adds overhead and does not give one entry point.'],
    ],
    slot: 0,
    evidence: [
      'elb-what-is|It monitors the health of its registered targets, and routes traffic only to the healthy targets.',
      'elb-what-is|Using a load balancer increases the availability and fault tolerance of your applications.',
      'alb-intro|A load balancer serves as the single point of contact for clients.',
    ],
  }),
  mc({
    id: 'scaling-floodgate-007',
    building: 'scaling-floodgate',
    bullets: ['2.1-K9'],
    d: 2,
    tags: ['trap:alb-nlb-gwlb'],
    stem: 'An online store runs as separate services on Amazon EC2 instances: product pages under /products/* and shopping carts under /cart/*, each in its own target group. All traffic is HTTPS on one domain name. The company wants one load balancer that sends each request to the correct service based on the URL path, with the LEAST operational overhead. Which load balancer should the company use?',
    correct: ['An Application Load Balancer with listener rules that use path conditions', 'An Application Load Balancer works at the application layer and can forward requests to different target groups based on the URL in the request.'],
    wrong: [
      ['A Network Load Balancer with a TLS listener and one target group per service', 'A Network Load Balancer works at the fourth layer and does not route on the URL path of an HTTP request.'],
      ['A Gateway Load Balancer placed in front of both target groups', 'A Gateway Load Balancer is for deploying and scaling virtual appliances such as firewalls and not for routing web requests to services.'],
      ['A Classic Load Balancer with one listener for each service', 'A Classic Load Balancer lacks the path-condition routing that lets an Application Load Balancer split services by URL.'],
    ],
    slot: 1,
    evidence: [
      'alb-intro|Support for Path conditions. You can configure rules for your listener that forward requests based on the URL in the request.',
      'nlb-intro|A Network Load Balancer functions at the fourth layer of the Open Systems Interconnection (OSI) model.',
      'gwlb-intro|Gateway Load Balancers enable you to deploy, scale, and manage virtual appliances, such as firewalls, intrusion detection and prevention systems, and deep packet inspection systems.',
    ],
  }),
  mc({
    id: 'scaling-floodgate-008',
    building: 'scaling-floodgate',
    bullets: ['2.1-K9', '2.1-S2'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A web application runs in an Auto Scaling group behind an Application Load Balancer. Occasionally the application process on an instance stops responding although the instance still passes its EC2 status checks, so the load balancer marks it unhealthy but the instance stays in the group. The company wants such instances replaced automatically with the LEAST custom code. Which solution meets these requirements?',
    correct: ['Turn on Elastic Load Balancing health checks for the Auto Scaling group', 'With these checks on, the group replaces a running instance when an attached load balancer reports it as unhealthy, so no extra code is needed.'],
    wrong: [
      ['Increase the minimum size of the group so that healthy instances absorb the traffic', 'Extra capacity does not remove the unhealthy instance, which would stay registered in the group.'],
      ['Create an Amazon CloudWatch alarm on CPU utilization that invokes an AWS Lambda function to terminate the instance', 'This needs custom code, and CPU utilization is not a reliable signal that the application stopped responding.'],
      ['Enable detailed monitoring on the instances so that the group can see application failures', 'Detailed monitoring publishes metrics at a finer interval and does not make the group act on load balancer health.'],
    ],
    slot: 2,
    evidence: [
      'asg-attach-lb|By default, Amazon EC2 Auto Scaling only replaces instances that are unhealthy or unreachable based on Amazon EC2 health checks.',
      'asg-attach-lb|If you turn on Elastic Load Balancing health checks, Amazon EC2 Auto Scaling can replace a running instance if any of the Elastic Load Balancing load balancers you attach to the Auto Scaling group report it as unhealthy.',
    ],
  }),
  mc({
    id: 'scaling-floodgate-009',
    building: 'scaling-floodgate',
    bullets: ['2.1-K9'],
    d: 3,
    tags: ['trap:alb-nlb-gwlb'],
    stem: 'A company runs a TCP-based service behind a Network Load Balancer with both Availability Zones enabled. Two instances are registered in Availability Zone A and eight in Availability Zone B. Each load balancer node receives half of the client traffic, so the instances in Availability Zone A are overloaded while those in Availability Zone B are mostly idle. The company wants requests spread evenly across all ten instances without changing how many instances run in each Availability Zone. Which solution meets these requirements with the LEAST change?',
    correct: ['Turn on cross-zone load balancing for the Network Load Balancer', 'With cross-zone load balancing enabled, each node distributes traffic across the registered targets in all enabled Availability Zones, so every instance gets an equal share.'],
    wrong: [
      ['Replace the Network Load Balancer with an Application Load Balancer', 'The service uses TCP rather than HTTP, so an Application Load Balancer does not fit, and the replacement is a larger change.'],
      ['Add two more instances in Availability Zone A and leave the load balancer settings as they are', 'This changes how many instances run in each Availability Zone, which the company wants to avoid, and does not change how nodes share traffic.'],
      ['Increase the deregistration delay on the target group so that overloaded instances drain slowly', 'The deregistration delay applies to targets being removed and has no effect on how traffic is shared among healthy targets.'],
    ],
    slot: 3,
    evidence: [
      'elb-how-it-works|When cross-zone load balancing is enabled, each load balancer node distributes traffic across the registered targets in all enabled Availability Zones.',
      'elb-how-it-works|With Network Load Balancers and Gateway Load Balancers, cross-zone load balancing is disabled by default.',
      'alb-target-attrs|Elastic Load Balancing stops sending requests to targets that are deregistering.',
    ],
  }),
  mr({
    id: 'scaling-floodgate-010',
    building: 'scaling-floodgate',
    bullets: ['2.1-K9', '2.1-S2'],
    d: 3,
    stem: 'A web application runs in an Auto Scaling group behind an Application Load Balancer with a target tracking policy. New instances take several minutes to warm their caches. During scale-out, each new instance immediately receives a full share of requests and responds slowly, and the group then scales out again because the new instances report unrepresentative metrics. Which TWO actions address these problems with the LEAST operational overhead? (Choose two.)',
    correct: [
      ['Enable slow start mode on the target group', 'Slow start gives new targets time to warm up by increasing the requests they receive gradually instead of sending a full share at once.'],
      ['Set an instance warmup time for the target tracking scaling policy', 'A warming instance is not counted in the aggregated metrics of the group, so unrepresentative values do not trigger further scale-out.'],
    ],
    wrong: [
      ['Switch the target group to the least outstanding requests routing algorithm', 'Slow start cannot be enabled with the least outstanding requests algorithm, so this blocks the fix for the overloaded new instances.'],
      ['Increase the deregistration delay on the target group', 'The delay applies when targets are removed and has no effect on how new instances are warmed up.'],
      ['Turn on sticky sessions so that users stay on the instances that are already warm', 'Stickiness binds a session to a target and does not limit how many new requests a freshly registered instance receives or what its metrics report.'],
    ],
    slots: [0, 2],
    evidence: [
      'alb-target-attrs|Using slow start mode gives targets time to warm up before the load balancer sends them a full share of requests.',
      "alb-target-attrs|You can't enable slow start mode when using the least outstanding requests or weighted random routing algorithms.",
      'asg-target-tracking|Until its specified warmup time has expired, an instance is not counted toward the aggregated EC2 instance metrics of the Auto Scaling group.',
    ],
  }),
  mc({
    id: 'scaling-floodgate-011',
    building: 'scaling-floodgate',
    bullets: ['2.1-K15'],
    d: 1,
    tags: ['trap:multi-az-vs-read-replicas'],
    stem: "A company's Amazon RDS for MySQL production database slows down every morning when analysts run long reporting queries. The analysts only read data and can accept results that are slightly out of date. The company wants to keep the reports from affecting production with the LEAST disruption. Which solution meets these requirements?",
    correct: ['Create a read replica and point the reporting queries at it', 'A read replica is a read-only copy that exists for scaling reads and business reporting, so the reports no longer compete with production work.'],
    wrong: [
      ['Enable Multi-AZ and point the reporting queries at the standby replica', 'The standby replica in a Multi-AZ deployment cannot serve read traffic, so it cannot run the reports.'],
      ['Restore a snapshot of the database into a new DB instance every morning for the analysts', 'This adds daily manual or scripted work, and the copy is already hours old when the analysts begin.'],
      ['Move the DB instance to a larger DB instance class so both workloads fit on the same server', 'The reports still run on the production instance, so they continue to compete with production traffic.'],
    ],
    slot: 0,
    evidence: [
      'rds-read-replicas|Business reporting or data warehousing scenarios where you might want business reporting queries to run against a read replica, rather than your production DB instance.',
      "rds-read-replicas|Unlike a read replica, a standby replica can't serve read traffic.",
    ],
  }),
  mc({
    id: 'scaling-floodgate-012',
    building: 'scaling-floodgate',
    bullets: ['2.1-K15'],
    d: 3,
    tags: ['trap:multi-az-vs-read-replicas'],
    stem: 'A retailer runs an Amazon RDS for PostgreSQL primary DB instance that is overloaded by read traffic, most of it product browsing. After a customer places an order, the confirmation page must show that order immediately. The company wants to offload reads while making sure the confirmation page never misses a just-written order. Which design BEST meets these requirements?',
    correct: ['Create read replicas for the product browsing queries and read the confirmation page from the primary instance', 'Replicas are updated asynchronously and can lag, so only the lag-tolerant browsing reads go to them while the order read goes to the primary.'],
    wrong: [
      ['Send every read, including the confirmation page, to the read replicas because replication to them is synchronous', 'Updates are copied to a read replica asynchronously, so a just-written order may not be there yet.'],
      ['Enable Multi-AZ and read the confirmation page from the standby replica', 'The standby replica cannot serve read traffic, so the confirmation page could not be read from it.'],
      ['Create read replicas and send the order writes to them so the confirmation page finds the order on the same node', 'Read replicas allow only read-only access, so the order writes would be rejected.'],
    ],
    slot: 1,
    evidence: [
      'rds-read-replicas|When you make updates to the primary DB instance, Amazon RDS copies them asynchronously to the read replica.',
      'rds-scaling-ha|Replicas might introduce minor latency due to asynchronous replication.',
      'rds-read-replicas|Clients have read/write access to the primary DB instance and read-only access to the replica.',
    ],
  }),
  mc({
    id: 'scaling-floodgate-013',
    building: 'scaling-floodgate',
    bullets: ['2.1-K15'],
    d: 2,
    tags: ['trap:aurora-vs-rds'],
    stem: 'A company runs Amazon RDS for MySQL with a few read replicas. Read traffic rises sharply during promotions and falls afterwards. The company wants the number of read replicas to follow demand automatically without paying for idle replicas, and is willing to change database engine. Which solution BEST meets these requirements with the LEAST operational overhead?',
    correct: ['Migrate to Amazon Aurora MySQL and apply an Aurora Auto Scaling policy to the Aurora Replicas', 'Aurora Auto Scaling adds and removes Aurora Replicas as the workload changes, which RDS read replicas cannot do automatically.'],
    wrong: [
      ['Turn on auto scaling for the RDS read replicas in the RDS console', 'RDS does not support autoscaling of read replicas, so this option does not exist for RDS for MySQL.'],
      ['Create enough RDS read replicas to cover the largest promotion and keep them running', 'Replicas that run permanently are billed as standard DB instances, so this pays for idle capacity between promotions.'],
      ['Write a scheduled AWS Lambda function that creates and deletes read replicas around promotions', 'This is custom code to build and maintain, and a schedule cannot follow unplanned changes in read demand.'],
    ],
    slot: 2,
    evidence: [
      "rds-read-replicas|RDS doesn't support autoscaling of read replicas, which is the automatic add or removing of read replicas as read demand changes.",
      'aurora-autoscaling|To meet your connectivity and workload requirements, Aurora Auto Scaling dynamically adjusts the number of Aurora Replicas (reader DB instances) provisioned for an Aurora DB cluster.',
      "rds-read-replicas|Read replicas are billed as standard DB instances at the same rates as the DB instance class used for the replica.",
    ],
  }),
  mc({
    id: 'scaling-floodgate-014',
    building: 'scaling-floodgate',
    bullets: ['2.1-K15'],
    d: 2,
    tags: ['trap:multi-az-vs-read-replicas'],
    stem: 'A company runs a business-critical Amazon RDS for PostgreSQL DB instance in one AWS Region. To prepare for a Regional outage, the company wants a copy of the database in a second Region that can be promoted to a standalone instance if the primary fails. The company wants the LEAST operational effort. Which solution meets these requirements?',
    correct: ['Create a cross-Region read replica in the second Region', 'A read replica can reside in a different Region and can be promoted to a standalone instance as a disaster recovery solution.'],
    wrong: [
      ['Enable Multi-AZ on the DB instance', 'A Multi-AZ standby replica is maintained in a different Availability Zone, not in a second Region, so it does not protect against a Regional outage.'],
      ['Create a read replica in another Availability Zone of the same Region', 'The replica stays in the same Region, so a Regional outage would affect both the primary and the replica.'],
      ['Export the data every night with a script and import it into a new DB instance in the second Region', 'The nightly scripts are extra operational work, and the copy is up to a day behind.'],
    ],
    slot: 3,
    evidence: [
      'rds-read-replicas|In some cases, a read replica resides in a different AWS Region from its primary DB instance.',
      'rds-read-replicas|You can promote a read replica to a standalone instance as a disaster recovery solution if the primary DB instance fails.',
      'rds-scaling-ha|Multi-AZ deployments provide high availability and durability by automatically maintaining a synchronous standby replica in a different Availability Zone.',
    ],
  }),
  mr({
    id: 'scaling-floodgate-015',
    building: 'scaling-floodgate',
    bullets: ['2.1-K15'],
    d: 2,
    tags: ['trap:multi-az-vs-read-replicas'],
    stem: 'A company runs a single-Availability-Zone Amazon RDS for MySQL production DB instance. Read traffic is growing, and the company also wants the database to fail over automatically to another Availability Zone if the primary instance fails. Which TWO actions meet these requirements? (Choose two.)',
    correct: [
      ['Create read replicas and route the read-only queries to them', 'Read replicas scale out reads beyond the capacity of a single DB instance.'],
      ['Enable a Multi-AZ deployment so that a standby replica is maintained in another Availability Zone', 'A Multi-AZ deployment automatically fails over to the standby replica when the primary has a problem, which meets the failover requirement.'],
    ],
    wrong: [
      ['Send the read queries to the Multi-AZ standby replica to scale reads', 'A standby replica is there for high availability and cannot serve read traffic.'],
      ['Increase the allocated storage of the DB instance so that it can serve more read requests', 'More allocated storage does not add read capacity and does not provide failover to another Availability Zone.'],
      ['Take hourly snapshots and restore the latest one to a new DB instance after a failure', 'A restore is a manual recovery and not an automatic failover, and it does not add read capacity.'],
    ],
    slots: [0, 4],
    evidence: [
      'rds-read-replicas|In this way, you can elastically scale out beyond the capacity constraints of a single DB instance for read-heavy database workloads.',
      'rds-scaling-ha|Multi-AZ deployments minimize downtime during planned maintenance or infrastructure failure by automatically failing over to the standby replica.',
      "rds-read-replicas|Unlike a read replica, a standby replica can't serve read traffic.",
    ],
  }),
  mc({
    id: 'scaling-floodgate-016',
    building: 'scaling-floodgate',
    bullets: ['2.1-S2'],
    d: 1,
    stem: 'A company runs a web application in an Amazon EC2 Auto Scaling group. Load varies unpredictably during the day. The company wants average CPU utilization to stay near 50 percent, with instances added and removed automatically and the LEAST operational overhead. Which solution meets these requirements?',
    correct: ['Create a target tracking scaling policy with a target of 50 percent average CPU utilization', 'Target tracking keeps a metric near a chosen target value, and the group scales out above the target and scales in below it.'],
    wrong: [
      ['Create step scaling policies together with the CloudWatch alarms that invoke them', 'With step scaling you create and manage the alarms and the step adjustments yourself, which is more overhead than a target.'],
      ['Create scheduled actions that change the desired capacity at fixed hours of the day', 'The load is unpredictable, so a fixed schedule cannot follow the actual CPU utilization.'],
      ['Set the minimum and desired capacity of the group to the size needed at the busiest moment of the day', 'This keeps peak capacity running all day, so CPU utilization stays far below the target and capacity is wasted.'],
    ],
    slot: 0,
    evidence: [
      'asg-target-tracking|You can meet this need by creating a target tracking scaling policy that targets an average CPU utilization of 50 percent.',
      'asg-target-tracking|With target tracking, you select a metric and a target value to represent the ideal average utilization or throughput level for your application.',
      'asg-step|With step scaling and simple scaling, you create and manage the CloudWatch alarms that invoke the scaling process.',
    ],
  }),
  mc({
    id: 'scaling-floodgate-017',
    building: 'scaling-floodgate',
    bullets: ['2.1-S2'],
    d: 2,
    stem: 'An online retailer will run a flash sale that starts at a known time next Friday. Earlier sales needed far more capacity than a normal day, so the company wants 40 instances ready when the sale starts and wants to return to normal capacity afterwards. The company wants the lowest cost and effort. Which solution BEST meets these requirements?',
    correct: ['Create scheduled actions that raise the desired capacity before the sale and lower it afterwards', 'Scheduled scaling changes desired capacity at specific times, and it can run once, so the capacity is ready before the sale and removed after it.'],
    wrong: [
      ['Create a target tracking policy on average CPU utilization and rely on it to react once the sale starts', 'A tracking policy is reactive, so instances arrive only after the load has already built up.'],
      ['Set the minimum size of the group to 40 permanently', 'This keeps sale-level capacity running every day, which wastes cost outside the sale.'],
      ['Enable predictive scaling so that the group learns the sale pattern', 'Predictive scaling forecasts from daily or weekly patterns in historical data, and a single sale does not form such a pattern.'],
    ],
    slot: 1,
    evidence: [
      'asg-scheduled|You can create scheduled actions that scale one time only or that scale on a recurring schedule.',
      "asg-scheduled|You create scheduled actions that increase or decrease your group's desired capacity at specific times.",
      'asg-predictive|Predictive scaling works by analyzing historical load data to detect daily or weekly patterns in traffic flows.',
    ],
  }),
  mc({
    id: 'scaling-floodgate-018',
    building: 'scaling-floodgate',
    bullets: ['2.1-S2'],
    d: 2,
    stem: 'An application runs in an Amazon EC2 Auto Scaling group. Traffic follows a consistent daily cycle, high during business hours and low overnight. Each new instance takes about ten minutes to initialize, and users notice slow responses at the start of each business day while the group scales out. The company wants capacity ready before the load arrives, without hand-written schedules. Which solution BEST meets these requirements?',
    correct: ['Configure a predictive scaling policy for the group', 'Predictive scaling forecasts capacity from historical daily patterns and launches instances in advance, which helps applications that take a long time to initialize.'],
    wrong: [
      ['Configure a target tracking policy on average CPU utilization only', 'A tracking policy reacts after utilization rises, so slow-to-initialize instances still arrive late.'],
      ['Write recurring scheduled actions that raise the desired capacity before each business day', 'This works but requires reviewing the load pattern and maintaining schedules by hand, which the company wants to avoid.'],
      ['Configure a step scaling policy with a lower alarm threshold so that it reacts earlier', 'Step scaling is still dynamic and reactive, and a lower threshold wastes capacity without having instances ready in advance.'],
    ],
    slot: 2,
    evidence: [
      'asg-predictive|Predictive scaling is well suited for situations where you have: Cyclical traffic, such as high use of resources during regular business hours and low use of resources during evenings and weekends',
      'asg-predictive|Predictive scaling can help you scale faster by launching capacity in advance of forecasted load, compared to using only dynamic scaling, which is reactive in nature.',
      "asg-predictive|You also don't have to spend time reviewing your application's load patterns and trying to schedule the right amount of capacity using scheduled scaling.",
    ],
  }),
  mc({
    id: 'scaling-floodgate-019',
    building: 'scaling-floodgate',
    bullets: ['2.1-S2'],
    d: 3,
    stem: 'A video-processing application runs worker instances in an Auto Scaling group that read jobs from an Amazon SQS queue. The jobs spend most of their time waiting on a remote service, so CPU utilization stays low even when the queue is long. The company wants the group to scale so that each instance has a steady number of waiting jobs, with the LEAST custom code. Which solution BEST meets these requirements?',
    correct: ['Create a target tracking policy on a backlog-per-instance metric that is built with metric math', 'The number of messages per instance changes in proportion to group size, so it works as a target tracking metric, and metric math avoids publishing a custom metric.'],
    wrong: [
      ['Create a target tracking policy directly on the ApproximateNumberOfMessagesVisible queue metric', 'The queue length does not change in proportion to the size of the group that processes it, so it is not suitable for target tracking.'],
      ['Create a target tracking policy on average CPU utilization of the group with a target of 50 percent', 'The jobs wait on a remote service, so CPU stays low whatever the queue length and the group would not scale on the backlog.'],
      ['Create a target tracking policy on the ALBRequestCountPerTarget metric of the load balancer', 'The workers pull jobs from a queue and are not behind a load balancer, so this metric does not describe their load.'],
    ],
    slot: 3,
    evidence: [
      'asg-sqs|The solution is to use a backlog per instance metric with the target value being the acceptable backlog per instance to maintain.',
      'asg-sqs|The issue with using a CloudWatch Amazon SQS metric like ApproximateNumberOfMessagesVisible for target tracking is that the number of messages in the queue might not change proportionally to the size of the Auto Scaling group that processes messages from the queue.',
      'asg-target-tracking|Instead of publishing new metrics to use in your scaling policy, you can use metric math to combine existing metrics.',
    ],
  }),
  mc({
    id: 'scaling-floodgate-020',
    building: 'scaling-floodgate',
    bullets: ['2.1-S2'],
    d: 3,
    stem: 'A payroll application needs at least 20 instances between 08:00 and 09:00 on each weekday, when employees submit timesheets. Demand above that baseline is unpredictable, and outside that hour the group should run only a few instances. The company wants acceptable response times without over-provisioning. Which solution BEST meets these requirements?',
    correct: ['Create recurring scheduled actions that raise the minimum capacity for that hour, plus a target tracking policy', 'The schedule has the baseline ready before 08:00 and the policy keeps adding capacity above it when demand exceeds the baseline.'],
    wrong: [
      ['Use only a target tracking policy with a low minimum capacity', 'The policy reacts only after the load arrives, so the baseline of 20 instances would not be ready when the hour begins.'],
      ['Use only scheduled actions that set the capacity to the expected peak for that hour and never change it', 'Demand above the baseline is unpredictable, and a fixed schedule cannot add capacity beyond what was planned.'],
      ['Keep the minimum capacity at 20 instances all day and add a target tracking policy for the extra load', 'The group would run 20 instances outside the busy hour, which is the over-provisioning the company wants to avoid.'],
    ],
    slot: 0,
    evidence: [
      'asg-scheduled|You can use scheduled scaling and scaling policies together to get the benefits of both approaches to scaling.',
      'asg-scheduled|After a scheduled scaling action runs, the scaling policy can continue to make decisions about whether to further scale capacity.',
      'asg-scheduled|While your application scales to match demand, current capacity must fall within the minimum and maximum capacity that was set by your scheduled action.',
    ],
  }),
  mc({
    id: 'scaling-floodgate-021',
    building: 'scaling-floodgate',
    bullets: ['2.1-S2', '2.1-K9'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'An API runs on Amazon EC2 instances in an Auto Scaling group behind an Application Load Balancer. Each instance performs best at about 1,000 requests per minute. The company wants the group to add instances when the average number of requests per instance rises above that level, and to remove them when it falls. Which scaling policy configuration should the company use?',
    correct: ['A target tracking policy that uses the ALBRequestCountPerTarget metric with a target value of 1,000', 'This predefined metric is the average request count per target of the group, and the target value is the throughput that one instance handles in a minute.'],
    wrong: [
      ['A target tracking policy that uses the load balancer RequestCount metric', 'The total request count does not change when the group scales, so it cannot guide a policy about requests per instance.'],
      ['A target tracking policy that uses the load balancer Latency metric', 'Latency can rise with utilization but does not change in proportion to the number of instances, so it does not work for target tracking.'],
      ['A target tracking policy that uses the ASGAverageNetworkOut metric', 'Outbound network traffic is not the requests-per-instance figure the company wants to hold near a target.'],
    ],
    slot: 1,
    evidence: [
      'asg-target-tracking|ALBRequestCountPerTarget—Average Application Load Balancer request count per target for your Auto Scaling group.',
      "asg-target-tracking|The number of requests received by the load balancer doesn't change based on the utilization of the Auto Scaling group.",
      "asg-target-tracking|Request latency can increase based on increasing utilization, but doesn't necessarily change proportionally.",
    ],
  }),
  mr({
    id: 'scaling-floodgate-022',
    building: 'scaling-floodgate',
    bullets: ['2.1-S2'],
    d: 2,
    stem: 'A company runs a fault-tolerant batch-processing tier in an Amazon EC2 Auto Scaling group. Demand peaks for a few hours each day. The company wants to keep the capacity it needs at peak while paying the LOWEST compute cost. Which TWO actions meet these requirements? (Choose two.)',
    correct: [
      ['Use a scaling policy that removes capacity when demand is lower', 'Scaling in during quiet periods means the company pays only for the instances that the load requires.'],
      ['Configure the group to launch both Spot Instances and On-Demand Instances', 'A single group can combine purchase options, so Spot Instance usage lowers the cost of the capacity the group needs.'],
    ],
    wrong: [
      ['Set the minimum and maximum sizes of the group to the peak size', 'The group would always run the peak number of instances, so no capacity is removed when demand is lower.'],
      ['Turn off the scale-in part of the scaling policy so that instances are never removed', 'Without scale-in the group keeps its largest size after each peak and the cost does not fall.'],
      ['Replace the group with one very large instance that always runs', 'A single always-on instance sized for the peak is paid for all day and removes the fault tolerance of a group.'],
    ],
    slots: [2, 3],
    evidence: [
      'asg-what-is|Using auto scaling allows you to maintain application availability and reduce costs by adding capacity to handle peak loads and removing capacity when demand is lower.',
      'asg-what-is|Within a single Auto Scaling group, you can launch multiple instance types and purchase options (Spot and On-Demand Instances), allowing you to optimize costs through Spot Instance usage.',
    ],
  }),
];

export default questions;
