import type { Question } from '../../../src/content/types.ts';
import { mc, mr } from '../helpers.ts';

const questions: Question[] = [
  mc({
    id: 'serverless-mill-001',
    building: 'serverless-mill',
    bullets: ['2.1-K1'],
    d: 1,
    stem: 'A company is adding a live chat feature to its web application. The browser and the server must both be able to send messages at any time over one persistent connection, and the company wants a fully managed API front end. Which Amazon API Gateway API type BEST meets these requirements?',
    correct: ['A WebSocket API that keeps a stateful, full-duplex connection between each client and the server', 'WebSocket APIs follow the WebSocket protocol, which enables stateful, full-duplex communication, so either side can send a message at any time.'],
    wrong: [
      ['An HTTP API that the browser polls every second to check whether new chat messages have arrived', 'HTTP APIs are stateless request and response APIs, so the server cannot push messages over a persistent connection.'],
      ['A REST API with an edge-optimized endpoint that returns the new chat messages on each request', 'REST APIs are stateless, and an edge-optimized endpoint changes where requests enter the network, not how client and server communicate.'],
      ['A private REST API that the clients reach through an interface VPC endpoint inside the VPC', 'A private endpoint is reachable only from a VPC, and a REST API is stateless, so it gives no persistent two-way connection.'],
    ],
    slot: 0,
    evidence: [
      'apigw-welcome|Adhere to the WebSocket protocol, which enables stateful, full-duplex communication between client and server.',
      'apigw-welcome|Support for stateful (WebSocket) and stateless (HTTP and REST) APIs.',
    ],
  }),
  mc({
    id: 'serverless-mill-002',
    building: 'serverless-mill',
    bullets: ['2.1-K1'],
    d: 2,
    tags: ['placement-eligible'],
    stem: 'A company exposes a public API through Amazon API Gateway that invokes AWS Lambda functions. The security team requires an AWS WAF web ACL that blocks SQL injection attempts and limits the request rate of each client IP address before requests reach the backend. Which solution meets these requirements with the LEAST operational overhead?',
    correct: ['Create the API as a REST API and associate a web ACL with a SQL injection rule and a rate-based rule with the API stage', 'REST APIs integrate with AWS WAF, and a web ACL can block SQL injection and apply rate-based rules for each client IP address.'],
    wrong: [
      ['Create the API as an HTTP API and associate a web ACL with a SQL injection rule and a rate-based rule with its stage', 'HTTP APIs do not support AWS WAF integration, so the web ACL cannot be associated with the API.'],
      ['Create the API as an HTTP API and add a Lambda authorizer that scans request bodies for SQL syntax and counts requests per IP address', 'This needs custom code to build and maintain, instead of the managed rules and low operational overhead that the company wants.'],
      ['Create the API as a REST API and require API keys with a usage plan that sets a throttle for each customer', 'Usage plans throttle per API key and are not meant to block access, and they do nothing to detect SQL injection.'],
    ],
    slot: 1,
    evidence: [
      'apigw-http-vs-rest|Choose REST APIs if you need features such as API keys, per-client throttling, request validation, AWS WAF integration, or private API endpoints.',
      'apigw-http-vs-rest|Security features REST API HTTP API Mutual TLS authentication Yes Yes Certificates for backend authentication Yes No AWS WAF Yes No',
      'apigw-waf|You can use AWS WAF to protect your API Gateway REST API from common web exploits, such as SQL injection and cross-site scripting (XSS) attacks.',
      'apigw-waf|For example, you can use rate-based rules to specify the number of web requests that are allowed by each client IP in a trailing, continuously updated, 5-minute period.',
    ],
  }),
  mc({
    id: 'serverless-mill-003',
    building: 'serverless-mill',
    bullets: ['2.1-K12'],
    d: 1,
    stem: 'A company runs an AWS Lambda function that resizes images. The function completes successfully, but it is CPU-bound and runs too slowly. The team wants to give the function more CPU power with the LEAST change to the application. What should the team do?',
    correct: ['Increase the memory setting of the function', 'Lambda allocates CPU power in proportion to the configured memory, so more memory gives a CPU-bound function more CPU.'],
    wrong: [
      ['Increase the reserved concurrency of the function', 'Reserved concurrency controls how many invocations can run at the same time and does not change the CPU that each invocation gets.'],
      ['Increase the timeout of the function to 900 seconds', 'A longer timeout lets one run last longer, but it does not make the code run faster.'],
      ['Configure provisioned concurrency for the function', 'Provisioned concurrency pre-initializes execution environments to reduce cold starts and does not add CPU power to an invocation.'],
    ],
    slot: 2,
    evidence: [
      'lambda-memory|Lambda allocates CPU power in proportion to the amount of memory configured.',
      'lambda-memory|If a function is CPU, network or memory-bound, then increasing the memory setting can dramatically improve its performance.',
    ],
  }),
  mc({
    id: 'serverless-mill-004',
    building: 'serverless-mill',
    bullets: ['2.1-S5'],
    d: 1,
    stem: 'A company wants to create a thumbnail every time a user uploads an image to an Amazon S3 bucket. Uploads are infrequent and arrive at unpredictable times, and the company does not want to provision or manage servers. Which solution is the MOST cost-effective?',
    correct: ['Configure the bucket to invoke an AWS Lambda function that creates the thumbnail on each upload', 'Lambda runs code in response to events such as S3 uploads with no servers to manage, and serverless billing follows the value delivered.'],
    wrong: [
      ['Run an Amazon EC2 instance that lists the bucket every minute and creates thumbnails for new objects', 'The instance runs and bills all the time and must be provisioned, patched and scaled, which the company wants to avoid.'],
      ['Run an Amazon ECS service on Amazon EC2 container instances that watches the bucket continuously', 'The company would manage the container instances and pay for idle capacity between infrequent uploads.'],
      ['Run an Amazon ECS service on AWS Fargate with one task that polls the bucket all day long', 'There are no servers to manage, but the task runs and bills continuously and idles between uploads, which costs more than running code only on events.'],
    ],
    slot: 3,
    evidence: [
      'lambda-welcome|You write a handler function, connect it to a trigger (API Gateway, Amazon S3, Amazon SQS, EventBridge, and 200+ other AWS services), and Lambda executes it.',
      'msa-whitepaper|Serverless is characterized by the following principles: No infrastructure to provision or manage Automatically scaling by unit of consumption "Pay for value" billing model Built-in availability and fault tolerance Event Driven Architecture (EDA)',
    ],
  }),
  mc({
    id: 'serverless-mill-005',
    building: 'serverless-mill',
    bullets: ['2.1-K1'],
    d: 2,
    tags: ['placement-eligible'],
    stem: 'A software company sells access to a public API that runs on Amazon API Gateway and AWS Lambda. Premium customers must be allowed a higher request rate than free customers, and every customer must have a monthly request quota. The company wants to identify customers by a key and enforce these limits with the LEAST custom code. Which solution meets these requirements?',
    correct: ['Create a REST API, issue an API key to each customer, and attach the keys to usage plans that define throttling limits and quotas', 'A usage plan uses API keys to identify clients and sets a throttle and a quota for them, and REST APIs support API keys and per-client throttling.'],
    wrong: [
      ['Create an HTTP API and keep a request counter for every customer in an Amazon DynamoDB table that the function updates', 'HTTP APIs have no API keys or per-client throttling, so all of the limit logic would be custom code.'],
      ['Raise the account-level throttling limit for the Region and rely on it to give premium customers a higher rate', 'The account-level limit applies to all APIs in the account, so it cannot give one customer a different rate than another.'],
      ['Set a different reserved concurrency value on the Lambda function for each customer tier', 'Reserved concurrency applies to one function as a whole, so it cannot identify customers or enforce monthly quotas.'],
    ],
    slot: 0,
    evidence: [
      'apigw-usage-plans|A usage plan specifies who can access one or more deployed API stages and methods',
      'apigw-usage-plans|The plan uses API keys to identify API clients and who can access the associated API stages for each key.',
      'apigw-http-vs-rest|Features REST API HTTP API Custom domains Yes Yes API keys Yes No Per-client rate limiting Yes No Per-client usage throttling Yes No',
      'apigw-throttling|Per-account limits are applied to all APIs in an account in a specified Region.',
    ],
  }),
  mc({
    id: 'serverless-mill-006',
    building: 'serverless-mill',
    bullets: ['2.1-K12'],
    d: 2,
    tags: ['placement-eligible'],
    stem: 'A company runs many AWS Lambda functions in one Region. A nightly bulk-import function scales out and uses so much of the account concurrency that the checkout function behind Amazon API Gateway is throttled. The company must guarantee that the checkout function always has capacity to run. Which solution meets this requirement with the LEAST operational overhead?',
    correct: ['Configure reserved concurrency for the checkout function', 'Reserved concurrency reserves the specified capacity exclusively for the function, so the import function cannot use it.'],
    wrong: [
      ['Configure provisioned concurrency for the bulk-import function so that its environments start faster', 'Provisioned concurrency pre-initializes environments to cut cold starts and does not stop the import function from consuming account concurrency.'],
      ['Request an increase of the account concurrency quota and make no other change to the functions', 'A larger shared pool guarantees nothing, because the import function can still use the capacity that the checkout function needs.'],
      ['Enable caching on the API Gateway stage that fronts the checkout function to reduce the load', 'Caching applies to GET methods by default and does not reserve Lambda concurrency for the checkout requests.'],
    ],
    slot: 1,
    evidence: [
      'lambda-reserved|Reserved concurrency is useful for ensuring that your most critical functions always have enough concurrency to handle incoming requests.',
      'lambda-reserved|When a function has reserved concurrency, no other function can use that concurrency.',
      'lambda-concurrency|By default, Lambda provides your account with a total concurrency limit of 1,000 concurrent executions across all functions in an AWS Region.',
    ],
  }),
  mc({
    id: 'serverless-mill-007',
    building: 'serverless-mill',
    bullets: ['2.1-K12'],
    d: 2,
    stem: 'A company serves a latency-sensitive customer API through Amazon API Gateway and an AWS Lambda function. At the start of each daily sales event the first requests are slow, because new execution environments must initialize. The company needs consistently low response times during the event. Which solution meets this requirement with the LEAST change to the code?',
    correct: ['Configure provisioned concurrency on an alias of the function', 'Provisioned concurrency keeps pre-initialized execution environments ready to respond immediately, which removes cold-start delays for interactive APIs.'],
    wrong: [
      ['Configure reserved concurrency on the function and set it to the expected peak number of requests', 'Reserved concurrency guarantees and caps capacity but does not pre-initialize execution environments, so cold starts continue.'],
      ['Convert the REST API in Amazon API Gateway to an HTTP API for the sales event', 'The API type decides features and price, not the time that Lambda needs to initialize a new execution environment.'],
      ['Increase the timeout of the function to the maximum number of seconds that Lambda allows', 'The timeout limits how long one invocation may run and has no effect on how long a new environment takes to initialize.'],
    ],
    slot: 2,
    evidence: [
      'lambda-provisioned|Provisioned concurrency – This is the number of pre-initialized execution environments allocated to your function.',
      'lambda-provisioned|These execution environments are ready to respond immediately to incoming function requests.',
      'lambda-provisioned|Generally, interactive workloads benefit the most from the feature.',
      'lambda-reserved|Reserved concurrency acts as both a lower and upper bound - it reserves the specified capacity exclusively for your function while also preventing it from scaling beyond that limit.',
    ],
  }),
  mc({
    id: 'serverless-mill-008',
    building: 'serverless-mill',
    bullets: ['2.1-S5', '2.1-K12'],
    d: 3,
    tags: ['placement-eligible'],
    stem: 'A company has a media-processing step packaged as a container image. Each upload starts one run that processes a single file in one process for about two hours, and the work cannot be split into smaller steps. Runs are infrequent, and the company does not want to manage servers or clusters of instances. Which solution is the MOST cost-effective?',
    correct: ['Run the image as an Amazon ECS task on AWS Fargate that is started for each upload', 'Fargate runs containers without servers to manage, a task performs its work and then stops, and the company pays only while the task runs.'],
    wrong: [
      ['Create an AWS Lambda function from the container image and invoke it for each upload', 'A single Lambda invocation can run for up to 15 minutes, so a two-hour process cannot finish.'],
      ['Run the image as an Amazon ECS service on AWS Fargate with one task that always runs', 'The task runs and bills all day although runs are infrequent, so it costs more than starting a task for each upload.'],
      ['Run the image on a self-managed Amazon EC2 instance that stays on and polls for new uploads', 'The company would manage and pay for an always-on instance, which conflicts with the requirement to avoid servers.'],
    ],
    slot: 3,
    evidence: [
      'lambda-quotas|Code can run for up to 15 minutes in a single invocation',
      'fargate-ecs|With AWS Fargate, you no longer have to provision, configure, or scale clusters of virtual machines to run containers.',
      'ecs-what-is|Fargate is a serverless, pay-as-you-go compute engine.',
      'ecs-what-is|Task An application such as a batch job that performs work, and then stops.',
    ],
  }),
  mc({
    id: 'serverless-mill-009',
    building: 'serverless-mill',
    bullets: ['2.1-K1'],
    d: 2,
    stem: 'A mobile app signs users in with an Amazon Cognito user pool. The backend is a REST API in Amazon API Gateway, and only signed-in users may call it. The company wants API Gateway to validate each caller before a request reaches the backend, with the LEAST custom code. Which solution meets these requirements?',
    correct: ['Create an Amazon Cognito user pool authorizer for the API methods and have the app send its token in the Authorization header', 'API Gateway lets the call succeed only when a valid token from the user pool is supplied, and no authorization code has to be written.'],
    wrong: [
      ['Give every user an API key and require the key on the API methods through a usage plan', 'AWS says not to use API keys for authentication or authorization, because a key identifies a client for a usage plan and not a signed-in user.'],
      ['Write a Lambda authorizer that calls the user pool to validate the token on every request', 'This works, but it needs custom code to write and maintain, while the Cognito authorizer performs the check without code.'],
      ['Associate an AWS WAF web ACL that allows only requests that contain an Authorization header', 'AWS WAF can match header values but does not validate a token against a user pool, so any caller could add a header.'],
    ],
    slot: 0,
    evidence: [
      'apigw-cognito-authorizer|you can use an Amazon Cognito user pool to control who can access your API in Amazon API Gateway.',
      'apigw-cognito-authorizer|The API call succeeds only if the required token is supplied and the supplied token is valid',
      "apigw-usage-plans|Don't use API keys for authentication or authorization to control access to your APIs.",
      'apigw-lambda-authorizer|Use a Lambda authorizer to implement a custom authorization scheme.',
    ],
  }),
  mr({
    id: 'serverless-mill-010',
    building: 'serverless-mill',
    bullets: ['2.1-K1'],
    d: 3,
    tags: ['placement-eligible'],
    stem: 'A company is designing a public product-catalog API on Amazon API Gateway in front of an AWS Lambda function. API Gateway must reject malformed request bodies before it invokes the function, and it must answer repeated GET requests from a cache for 300 seconds instead of invoking the function. Which TWO actions meet these requirements with the LEAST operational overhead? (Choose two.)',
    correct: [
      ['Create the API as a REST API', 'Request validation and caching are available in REST APIs and not in HTTP APIs.'],
      ['Enable caching on the API stage with a time-to-live of 300 seconds', 'API Gateway caches endpoint responses for the TTL period and answers repeated requests from the cache, so the function is not invoked.'],
    ],
    wrong: [
      ['Create the API as an HTTP API to get request validation and caching at a lower price', 'HTTP APIs cost less but offer neither request validation nor caching.'],
      ['Configure a usage plan that limits every client to 300 requests', 'A usage plan throttles or caps requests for each client and neither validates bodies nor serves cached responses.'],
      ['Enable provisioned concurrency on the function so that repeated requests run faster', 'Provisioned concurrency reduces cold starts, but every request still invokes the function and bodies are not validated at the gateway.'],
    ],
    slots: [0, 3],
    evidence: [
      'apigw-http-vs-rest|Caching Yes No User-controlled deployments Yes Yes Automatic deployments No Yes Custom gateway responses Yes No Canary release deployments Yes No Request validation Yes No',
      'apigw-caching|When you enable caching for a stage, API Gateway caches responses from your endpoint for a specified time-to-live (TTL) period, in seconds.',
      'apigw-caching|The default TTL value for API caching is 300 seconds.',
    ],
  }),
  mc({
    id: 'serverless-mill-011',
    building: 'serverless-mill',
    bullets: ['2.1-S5'],
    d: 2,
    tags: ['placement-eligible'],
    stem: 'A startup runs an API whose traffic is close to zero overnight and jumps to thousands of requests per second during marketing campaigns. The small team does not want to manage servers or plan capacity, and it wants to pay in proportion to usage. Which architecture is the MOST suitable?',
    correct: ['Amazon API Gateway invoking AWS Lambda functions that read and write an Amazon DynamoDB table', 'Each layer is serverless and scales automatically by unit of consumption with pay-for-value billing, so nothing is sized for campaigns or paid for overnight.'],
    wrong: [
      ['An Application Load Balancer in front of an Amazon EC2 Auto Scaling group sized for the campaign peak', 'Instances sized for the peak run and bill overnight, and the team has to manage the instances and the capacity.'],
      ['An Amazon ECS cluster on Amazon EC2 instances behind a Network Load Balancer, sized for the campaign peak', 'The team must manage and pay for the cluster capacity all night, which conflicts with no servers and usage-based cost.'],
      ['An Amazon EKS cluster with a managed node group that has a fixed number of worker nodes', 'A fixed node group does not follow demand, and the team still operates the cluster, which conflicts with usage-based cost.'],
    ],
    slot: 1,
    evidence: [
      'msa-whitepaper|Serverless is characterized by the following principles: No infrastructure to provision or manage Automatically scaling by unit of consumption "Pay for value" billing model Built-in availability and fault tolerance Event Driven Architecture (EDA)',
      'apigw-welcome|Together with AWS Lambda, API Gateway forms the app-facing part of the AWS serverless infrastructure.',
    ],
  }),
  mr({
    id: 'serverless-mill-012',
    building: 'serverless-mill',
    bullets: ['2.1-K12'],
    d: 3,
    tags: ['placement-eligible'],
    stem: 'A company runs an interactive web application on Amazon API Gateway and AWS Lambda. Traffic is predictable: it rises every weekday at 08:00 and falls after 18:00, and users report slow first requests at the start of the peak because of cold starts. The company wants to remove the slow starts while paying for pre-initialized capacity only during business hours. Which TWO actions meet these requirements at the LOWEST cost? (Choose two.)',
    correct: [
      ['Publish a function version and configure provisioned concurrency on an alias that points to it', 'Provisioned concurrency keeps pre-initialized execution environments ready, and it works with versions and aliases but not with the $LATEST version.'],
      ['Use Application Auto Scaling scheduled scaling to raise provisioned concurrency before 08:00 and lower it after 18:00', 'Scheduled scaling follows predictable load changes, so pre-initialized capacity exists only when it is needed.'],
    ],
    wrong: [
      ['Configure provisioned concurrency on the $LATEST version of the function', 'Provisioned concurrency cannot be used with the $LATEST version of a function.'],
      ['Set reserved concurrency to the peak value so that the execution environments stay initialized', 'Reserved concurrency reserves and caps capacity but does not keep execution environments pre-initialized.'],
      ['Increase the memory of the function to 10,240 MB', 'More memory adds CPU power, but new execution environments still have to initialize, so cold starts remain and each run costs more.'],
    ],
    slots: [1, 4],
    evidence: [
      'lambda-provisioned|You cannot use provisioned concurrency with the $LATEST version of any function.',
      'lambda-provisioned|With Application Auto Scaling, you can set your own scaling schedule according to predictable load changes.',
      'lambda-provisioned|Provisioned concurrency – This is the number of pre-initialized execution environments allocated to your function.',
    ],
  }),
  mr({
    id: 'serverless-mill-013',
    building: 'serverless-mill',
    bullets: ['2.1-K12'],
    d: 2,
    stem: 'A company is building an AWS Lambda function that updates items in an Amazon DynamoDB table. The function must receive its permissions without any long-term access keys stored in its code or configuration. Which TWO actions meet these requirements with the LEAST operational overhead? (Choose two.)',
    correct: [
      ['Create an IAM role that allows the required DynamoDB actions on the table and set it as the execution role of the function', 'The execution role grants the function permission to access AWS services and resources, so no access keys are needed.'],
      ['Specify the Lambda service principal as a trusted service in the trust policy of the role', 'Lambda can assume the execution role only when the trust policy names the Lambda service principal as a trusted service.'],
    ],
    wrong: [
      ['Store the access keys of an IAM user that has DynamoDB permissions in the environment variables of the function', 'Long-term access keys in configuration are exactly what the company wants to avoid.'],
      ['Attach a resource-based policy to the function that allows the DynamoDB service to access it', 'A resource-based policy on a function grants others access to the function and does not give the function permission to call DynamoDB.'],
      ['Write code in the function that calls the role-assumption API to assume the execution role on every invocation', 'Lambda assumes the execution role automatically, and AWS advises avoiding manual role-assumption calls in function code.'],
    ],
    slots: [2, 3],
    evidence: [
      "lambda-exec-role|A Lambda function's execution role is an AWS Identity and Access Management (IAM) role that grants the function permission to access AWS services and resources.",
      "lambda-exec-role|In order for Lambda to properly assume your execution role, the role's trust policy must specify the Lambda service principal (lambda.amazonaws.com) as a trusted service.",
      'lambda-exec-role|You should avoid manually calling sts:AssumeRole to assume the execution role in your function code.',
      'lambda-resource-policy|With resource-based permissions policies, you can grant other AWS accounts, users, organizations, and AWS services access to your Lambda functions.',
    ],
  }),
  mc({
    id: 'serverless-mill-014',
    building: 'serverless-mill',
    bullets: ['2.1-S5'],
    d: 3,
    tags: ['placement-eligible'],
    stem: 'A company has an image-analysis function packaged as a 4 GB container image because of large libraries. Messages in an Amazon SQS queue start it at unpredictable times, and each run finishes in about 40 seconds. The team wants to avoid refactoring how the function is packaged and to avoid managing servers or container clusters. Which solution is the MOST cost-effective?',
    correct: ['Create an AWS Lambda function from the container image and use the queue as its event source', 'Lambda accepts container images as a deployment package, runs in response to SQS messages, and has no servers to manage.'],
    wrong: [
      ['Run the image as an Amazon ECS service on AWS Fargate with tasks that poll the queue all day', 'The tasks run and bill continuously even when the queue is empty, which costs more than paying only when messages arrive.'],
      ['Run the image on Amazon EC2 instances in an Auto Scaling group that poll the queue for messages', 'The team would manage instances, patching and scaling, which conflicts with the requirement to avoid servers.'],
      ['Rewrite the function as a .zip package and split it into several smaller functions', 'This is the refactoring of the packaging that the team wants to avoid, and Lambda already supports container images.'],
    ],
    slot: 2,
    evidence: [
      'lambda-images|Lambda supports two types of deployment packages: container images and .zip file archives.',
      'lambda-images|Lambda supports a maximum uncompressed image size of 10 GB, including all layers.',
      'lambda-welcome|You write a handler function, connect it to a trigger (API Gateway, Amazon S3, Amazon SQS, EventBridge, and 200+ other AWS services), and Lambda executes it.',
    ],
  }),
  mc({
    id: 'serverless-mill-015',
    building: 'serverless-mill',
    bullets: ['2.1-K1'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A company runs a REST API on Amazon API Gateway for mobile clients located on several continents. The company wants requests to enter the AWS network close to each client, with the LEAST operational overhead and no other services to configure. Which API endpoint type should the company use?',
    correct: ['An edge-optimized endpoint', 'An edge-optimized API endpoint typically routes requests to the nearest CloudFront Point of Presence, which helps when clients are geographically distributed.'],
    wrong: [
      ['A Regional endpoint that serves the clients of every continent from one Region', 'A Regional API endpoint is intended for clients in the same Region and does not route requests through nearby edge locations.'],
      ['A private endpoint that the mobile clients reach through an interface VPC endpoint', 'A private API endpoint can only be accessed from a VPC, so mobile clients on the internet cannot reach it.'],
      ['An HTTP API with an edge-optimized endpoint to keep the cost of the API low', 'HTTP APIs do not offer the edge-optimized endpoint type, so this combination does not exist.'],
    ],
    slot: 3,
    evidence: [
      'apigw-endpoint-types|An edge-optimized API endpoint typically routes requests to the nearest CloudFront Point of Presence (POP), which could help in cases where your clients are geographically distributed.',
      'apigw-endpoint-types|A Regional API endpoint is intended for clients in the same Region.',
      'apigw-http-vs-rest|Endpoint types REST API HTTP API Edge-optimized Yes No Regional Yes Yes Private Yes No',
    ],
  }),
  mc({
    id: 'serverless-mill-016',
    building: 'serverless-mill',
    bullets: ['2.1-K12'],
    d: 2,
    tags: ['mock-reserve'],
    stem: 'A company discovers that a faulty AWS Lambda function is writing bad data. Several event sources invoke the function. The company must stop the function from processing any events immediately, while keeping the function, its code and its configuration, with the LEAST effort. What should the company do?',
    correct: ['Set the reserved concurrency of the function to 0', 'Setting reserved concurrency to 0 intentionally throttles the function, so it stops processing events until the limit is removed.'],
    wrong: [
      ['Delete the function and recreate it after the problem is fixed', 'Deleting the function removes its code and configuration, which the company wants to keep.'],
      ['Reduce the timeout of the function to the minimum value that Lambda allows', 'The function would still be invoked and could still write bad data before it times out.'],
      ['Reduce the memory of the function to the minimum value that Lambda allows', 'The function would still process events, only with less CPU power and memory.'],
    ],
    slot: 0,
    evidence: [
      'lambda-reserved|To intentionally throttle a function, set its reserved concurrency to 0.',
      'lambda-reserved|This stops your function from processing any events until you remove the limit.',
    ],
  }),
];

export default questions;
