import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'blueprint-hall',
  overview: [
    b('Some design questions come up before any service is chosen: how the application is divided (one deployable unit or many small services), where its state lives (in the servers or outside them), and how its parts are layered. This building covers microservice design principles, stateless versus stateful workloads, and multi-tier architectures.',
      'msa-whitepaper',
      ['Adopting microservices offers benefits, such as improved scalability, resilience, flexibility, and faster development cycles.']),
    b('AWS itself says the choice is not automatic: monolithic architecture or alternative approaches may be more appropriate in some cases, and the decision should be made case by case.',
      'msa-whitepaper',
      ['Monolithic architecture or alternative approaches may be more appropriate in some cases.',
       'Deciding between microservices or monoliths should be made on a case-by-case basis, considering factors like scale, complexity, and specific use cases.']),
  ],
  bullets: [
    {
      id: '2.1-K4',
      concepts: [
        b('Microservices rely on small, loosely coupled services that communicate through well-defined APIs and are managed by autonomous teams. They combine ideas from agile development, service-oriented architectures, API-first design and CI/CD.',
          'msa-whitepaper',
          ['This method relies on small, loosely coupled services that communicate through well-defined APIs, which are managed by autonomous teams.',
           'Microservices architectures combine successful and proven concepts from various fields, such as: Agile software development Service-oriented architectures API-first design Continuous Integration/Continuous Delivery (CI/CD)']),
        b('A microservices architecture separates functionality into cohesive verticals according to specific domains, rather than technological layers. A layered monolith, by contrast, splits an application into a presentation layer, an application layer and a data layer.',
          'msa-simple',
          ['Typical monolithic applications consist of different layers: a presentation layer, an application layer, and a data layer.',
           'Microservices architectures, on the other hand, separate functionalities into cohesive verticals according to specific domains, rather than technological layers.']),
        b('Each microservice maintains its own data instead of sharing one database. That promotes independence and decentralization, but brings the trade-off between consistency and performance: it is often more practical to accept slight delays in data updates (eventual consistency) than to insist on instant updates.',
          'msa-distributed-data',
          ['In contrast, each component of a microservices-based application maintains its own data, promoting independence and decentralization.',
           'It\'s often more practical to accept slight delays in data updates (eventual consistency) than to insist on instant updates (immediate consistency).']),
        b('A {{term:stateless}} workload does not store session information, which means any available compute resource can serve any request. A stateful workload keeps data between requests in the server\'s own disk or memory, so requests depend on which server they reach. Stateless is the design AWS recommends where possible.',
          'waf-stateless',
          ['Systems should either not require state, or should offload state such that between different client requests, there is no dependence on locally stored data on disk and in memory.',
           'In addition to server replacement, another benefit of stateless applications is that they can scale horizontally because any of the available compute resources (such as EC2 instances and AWS Lambda functions) can service any request.']),
        b('To make an application stateless, offload the {{term:session}} data. A stateless architecture decouples user data and offloads the session data. Microservices guidance names in-memory caches (Memcached or Redis, offered as Amazon ElastiCache) as popular stores for session data.',
          ['waf-stateless', 'msa-data-store'],
          ['waf-stateless|A stateless architecture decouples user data and offloads the session data.',
           'msa-data-store|Popular stores for session data are in-memory caches such as Memcached or Redis.']),
        b('Once a workload is stateless you can use serverless compute such as AWS Lambda or AWS Fargate, and it is also easier to replace servers.',
          'waf-stateless',
          ['Once designed to be stateless, you can then use serverless compute services, such as AWS Lambda or AWS Fargate.']),
      ],
      services: ['Amazon ElastiCache', 'AWS Lambda', 'AWS Fargate', 'Amazon DynamoDB'],
      design: [
        b('For individual microservices, AWS notes that each is designed to do one thing well and so typically has a simplified data model that might be well suited to NoSQL persistence (for example Amazon DynamoDB), though NoSQL has different access patterns, such as no table joins.',
          'msa-data-store',
          ['Because individual microservices are designed to do one thing well, they typically have a simplified data model that might be well suited to NoSQL persistence.',
           'For example, it\'s not possible to join tables.']),
        b('Stateless components that store state in an external data store can run on EC2 Spot Instances, because losing one instance loses no state. (Spot is explained in the Treasury notes.)',
          'waf-stateless',
          ['A stateless architecture decouples user data and offloads the session data.']),
      ],
    },
    {
      id: '2.1-K10',
      concepts: [
        b('A typical layered application separates a presentation layer, an application layer and a data layer. The presentation tier is what users interact with, for example static web content served from Amazon S3 through Amazon CloudFront or a single-page application calling backend APIs.',
          ['msa-simple', 'msa-ui'],
          ['msa-simple|Typical monolithic applications consist of different layers: a presentation layer, an application layer, and a data layer.',
           'msa-ui|Static web content can be served using Amazon Simple Storage Service (Amazon S3) and Amazon CloudFront.']),
        b('The data tier persists data. In-memory caches such as ElastiCache sit between the application servers and the database, reducing the read load on the database, which may let it support more writes; caches can also improve latency.',
          'msa-data-store',
          ['Putting a cache between application servers and a database is a common mechanism for reducing the read load on the database, which, in turn, may allow resources to be used to support more writes.',
           'Caches can also improve latency.']),
        b('Relational databases (Amazon RDS and Amazon Aurora) remain popular for structured data and business objects, but are not designed for endless scale. NoSQL databases favour scalability, performance and availability over the consistency of relational databases.',
          'msa-data-store',
          ['Relational databases are still very popular to store structured data and business objects.',
           'Relational databases, however, are not designed for endless scale, which can make it difficult and time intensive to apply techniques to support a high number of queries.',
           'NoSQL databases have been designed to favor scalability, performance, and availability over the consistency of relational databases.']),
      ],
      services: ['Amazon CloudFront', 'Amazon S3', 'Amazon ElastiCache', 'Amazon RDS', 'Amazon DynamoDB'],
      design: [
        b('Each layer can then scale and fail independently: put a load balancer in front of a fleet at the application layer (see Scaling Floodgate), a cache between it and the database, and keep the layers in separate subnets (see Surveyor\'s Grid and Gatehouse).',
          'msa-data-store',
          ['Putting a cache between application servers and a database is a common mechanism for reducing the read load on the database']),
      ],
    },
    {
      id: '2.1-S1',
      concepts: [
        b('Event-driven, microservice and multi-tier are patterns to combine, not exclusive choices. The Microservices on AWS whitepaper describes three microservices patterns: API driven, event driven and data streaming.',
          'msa-whitepaper',
          ['This whitepaper explores three popular microservices patterns: API driven, event driven, and data streaming.'],
          { allow: ['three'] }),
        b('Serverless is characterised by no infrastructure to provision or manage, automatic scaling by unit of consumption, a "pay for value" billing model, built-in availability and fault tolerance, and event-driven architecture.',
          'msa-whitepaper',
          ['Serverless is characterized by the following principles: No infrastructure to provision or manage Automatically scaling by unit of consumption "Pay for value" billing model Built-in availability and fault tolerance Event Driven Architecture (EDA)']),
        b('Matching a requirement to a pattern: independent teams and deployment, with domains that change at different speeds, point to microservices; several independent reactions to something that happened point to event-driven (see Message Quay); a conventional user-facing application with distinct web, logic and data concerns fits a multi-tier layout.',
          'msa-whitepaper',
          ['Microservices offer a streamlined approach to software development that accelerates deployment, encourages innovation, enhances maintainability, and boosts scalability.']),
      ],
      services: ['Amazon EventBridge', 'Amazon SQS', 'AWS Lambda', 'Amazon API Gateway'],
      design: [
        b('Whichever pattern you choose, keep the components decoupled through an intermediate layer and keep the compute stateless; those decisions are what make the rest scale and survive failures.',
          ['waf-loose-coupling', 'waf-stateless'],
          ['waf-loose-coupling|Implementing loose coupling between dependencies isolates a failure in one from impacting another.',
           'waf-stateless|there is no dependence on locally stored data on disk and in memory.']),
      ],
    },
  ],
  cues: [
    cue('users lose their session/shopping cart when an instance is replaced or scaled in', 'Make the application stateless: offload session data (for example to ElastiCache)',
      b('A stateless architecture decouples user data and offloads the session data, and in-memory caches are popular stores for session data.', ['waf-stateless', 'msa-data-store'],
        ['waf-stateless|A stateless architecture decouples user data and offloads the session data.',
         'msa-data-store|Popular stores for session data are in-memory caches such as Memcached or Redis.'])),
    cue('scale horizontally / any server can handle any request', 'Stateless design',
      b('Stateless applications can scale horizontally because any available compute resource can service any request.', 'waf-stateless',
        ['they can scale horizontally because any of the available compute resources (such as EC2 instances and AWS Lambda functions) can service any request.'])),
    cue('each team owns and deploys its own service / independent deployment', 'Microservices',
      b('Microservices are small, loosely coupled services with well-defined APIs managed by autonomous teams.', 'msa-whitepaper',
        ['This method relies on small, loosely coupled services that communicate through well-defined APIs, which are managed by autonomous teams.'])),
    cue('services should not share one database', 'Database per microservice (decentralised data)',
      b('Each component of a microservices-based application maintains its own data.', 'msa-distributed-data',
        ['each component of a microservices-based application maintains its own data, promoting independence and decentralization.'])),
    cue('reduce read load on the database / improve latency for repeated reads', 'Add a cache layer (ElastiCache) between the app and the database',
      b('A cache between application servers and a database reduces the database read load and can improve latency.', 'msa-data-store',
        ['Putting a cache between application servers and a database is a common mechanism for reducing the read load on the database, which, in turn, may allow resources to be used to support more writes.'])),
  ],
  examples: [],
  confuse: [],
};

export default notes;
