import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'cache-edge-breakwater',
  overview: [
    b('A cache keeps a copy of data closer to the consumer or in faster storage, so repeated requests are answered without going back to the source. On AWS the same idea appears at several layers: at the edge (CloudFront), in front of an API (API Gateway cache), between the application and the database (ElastiCache) and inside DynamoDB (DAX).',
      ['cloudfront-what-is', 'apigw-caching', 'msa-data-store', 'dax'],
      ['cloudfront-what-is|copies of your files (also known as objects) are now held (or cached) in multiple edge locations around the world.',
       'apigw-caching|With caching, you can reduce the number of calls made to your endpoint and also improve the latency of requests to your API.',
       'msa-data-store|Putting a cache between application servers and a database is a common mechanism for reducing the read load on the database, which, in turn, may allow resources to be used to support more writes.',
       'dax|DAX is a DynamoDB-compatible caching service that enables you to benefit from fast in-memory performance for demanding applications.']),
  ],
  beyondProject: [
    b('You have already put CloudFront in front of a static site. The SAA question is which layer a cache belongs in: edge caching for static and dynamic web content close to users, an in-memory cache such as ElastiCache for repeated database reads, DAX for DynamoDB, and the API Gateway stage cache for API responses. It also asks you to tell CloudFront from AWS Global Accelerator, which accelerates traffic without caching it.',
      ['cloudfront-what-is', 'ga-what-is'],
      ['cloudfront-what-is|Amazon CloudFront is a web service that speeds up distribution of your static and dynamic web content, such as .html, .css, .js, and image files, to your users.',
       'ga-what-is|AWS Global Accelerator is a service in which you create accelerators to improve the performance of your applications for local and global users.']),
  ],
  bullets: [
    {
      id: '2.1-K3',
      concepts: [
        b('Lazy loading loads data into the cache only when necessary. Its advantages are that only requested data is cached and node failures are not fatal for the application. Its disadvantages are a cache-miss penalty (three trips: the cache request, the database query and the cache write) and stale data.',
          'elasticache-strategies',
          ['Lazy loading As the name implies, lazy loading is a caching strategy that loads data into the cache only when necessary.',
           'The advantages of lazy loading are as follows: Only requested data is cached.',
           'Node failures aren\'t fatal for your application.',
           'The disadvantages of lazy loading are as follows: There is a cache miss penalty.',
           'Each cache miss results in three trips: Initial request for data from the cacheQuery of the database for the dataWriting the data to the cache',
           'If data is written to the cache only when there is a cache miss, data in the cache can become stale.']),
        b('Write-through adds or updates data in the cache whenever data is written to the database, so data in the cache is never stale. Its disadvantage is missing data until it is written. Adding a time to live (TTL) value to cached items minimises wasted space.',
          'elasticache-strategies',
          ['The advantages of write-through are as follows: Data in the cache is never stale.',
           'The disadvantages of write-through are as follows: Missing data.',
           'By adding a time to live (TTL) value, you can minimize wasted space.']),
        b('Amazon ElastiCache is a web service for setting up, managing and scaling a distributed in-memory data store or cache in the cloud. It is fully managed, handling hardware provisioning, monitoring, node replacement and software patching, and works with the Valkey, Memcached and Redis OSS engines.',
          'elasticache-what-is',
          ['Amazon ElastiCache is a web service that makes it easy to set up, manage, and scale a distributed in-memory data store or cache environment in the cloud.',
           'Since ElastiCache is a fully-managed service, it automatically manages hardware provisioning, monitoring, node replacements, and software patching for your cluster.',
           'NoteAmazon ElastiCache works with the Valkey, Memcached, and Redis OSS engines.']),
        b('Amazon DynamoDB Accelerator (DAX) is a DynamoDB-compatible caching service. As an in-memory cache, it reduces the response times of eventually consistent read workloads from single-digit milliseconds to microseconds.',
          'dax',
          ['DAX is a DynamoDB-compatible caching service that enables you to benefit from fast in-memory performance for demanding applications.',
           'DAX addresses three core scenarios: As an in-memory cache, DAX reduces the response times of eventually consistent read workloads by an order of magnitude from single-digit milliseconds to microseconds.']),
        b('API Gateway can cache responses for a REST API stage for a time-to-live period, which reduces calls to your endpoint and improves latency.',
          'apigw-caching',
          ['When you enable caching for a stage, API Gateway caches responses from your endpoint for a specified time-to-live (TTL) period, in seconds.']),
      ],
      services: ['Amazon ElastiCache', 'Amazon CloudFront', 'Amazon DynamoDB', 'Amazon API Gateway'],
      design: [
        b('A cache between the application servers and the database reduces the database read load, which may free resources for writes, and can also improve latency. Popular stores for session data are in-memory caches such as Memcached or Redis.',
          'msa-data-store',
          ['Putting a cache between application servers and a database is a common mechanism for reducing the read load on the database, which, in turn, may allow resources to be used to support more writes.',
           'Popular stores for session data are in-memory caches such as Memcached or Redis.']),
        b('Choose the strategy by data: lazy loading when you can tolerate stale data and want only requested items cached; write-through when stale data is not acceptable. A TTL bounds how long any entry can be stale.',
          'elasticache-strategies',
          ['What strategies to implement for populating and maintaining your cache depend upon what data you cache and the access patterns to that data.']),
      ],
    },
    {
      id: '2.1-K7',
      concepts: [
        b('Amazon CloudFront is a content delivery network (CDN) web service that speeds up distribution of static and dynamic web content. It delivers content through a worldwide network of data centres called edge locations. A request is routed to the edge location with the lowest latency; if the content is already there CloudFront delivers it immediately, otherwise it retrieves it from the origin, such as an S3 bucket or an HTTP server.',
          'cloudfront-what-is',
          ['Amazon CloudFront is a web service that speeds up distribution of your static and dynamic web content, such as .html, .css, .js, and image files, to your users.',
           'CloudFront delivers your content through a worldwide network of data centers called edge locations.',
           'If the content is already in the edge location with the lowest latency, CloudFront delivers it immediately.',
           'CloudFront retrieves it from an origin that you\'ve defined—such as an Amazon S3 bucket, a MediaPackage channel, or an HTTP server']),
        b('You control how long objects stay in CloudFront\'s cache. After a file expires, the next request makes the edge location forward the request to the origin to verify that the cache has the latest version. Longer cache duration reduces the load on your origin.',
          'cloudfront-expiration',
          ['After it expires, the next time the edge location gets a request for the file, CloudFront forwards the request to the origin to verify that the cache contains the latest version of the file.',
           'A longer duration also reduces the load on your origin.']),
        b('AWS Global Accelerator is also an edge accelerator, but it does not cache. With a standard accelerator it directs traffic over the AWS global network to endpoints in the nearest Region to the client, using static IP addresses that are anycast from the AWS edge network. The CloudFront vs Global Accelerator comparison is in Edge Link Terminal.',
          'ga-what-is',
          ['With a standard accelerator, Global Accelerator directs traffic over the AWS global network to endpoints in the nearest Region to the client.',
           'The static IP addresses are anycast from the AWS edge network.']),
      ],
      services: ['Amazon CloudFront', 'AWS Global Accelerator'],
      design: [
        b('Use a CDN when many users in many places fetch the same content: users get lower latency and higher data transfer rates, and copies held at multiple edge locations also raise reliability and availability.',
          'cloudfront-what-is',
          ['Users get lower latency—the time it takes to load the first byte of the file—and higher data transfer rates.',
           'You also get increased reliability and availability because copies of your files (also known as objects) are now held (or cached) in multiple edge locations around the world.']),
      ],
    },
  ],
  cues: [
    cue('serve static and dynamic web content to global users with low latency', 'Amazon CloudFront',
      b('CloudFront speeds up distribution of static and dynamic content through edge locations.', 'cloudfront-what-is',
        ['Amazon CloudFront is a web service that speeds up distribution of your static and dynamic web content, such as .html, .css, .js, and image files, to your users.'])),
    cue('reduce load on the origin / database read-heavy', 'A cache (CloudFront at the edge, ElastiCache before the database)',
      b('A longer cache duration reduces the load on the origin, and a cache before the database reduces its read load.', ['cloudfront-expiration', 'msa-data-store'],
        ['cloudfront-expiration|A longer duration also reduces the load on your origin.',
         'msa-data-store|Putting a cache between application servers and a database is a common mechanism for reducing the read load on the database, which, in turn, may allow resources to be used to support more writes.'])),
    cue('in-memory cache for DynamoDB, microsecond reads', 'DynamoDB Accelerator (DAX)',
      b('DAX reduces eventually consistent read response times from single-digit milliseconds to microseconds.', 'dax',
        ['As an in-memory cache, DAX reduces the response times of eventually consistent read workloads by an order of magnitude from single-digit milliseconds to microseconds.'])),
    cue('in-memory data store/cache, session store, Redis or Memcached compatible', 'Amazon ElastiCache',
      b('ElastiCache is a managed distributed in-memory data store or cache that works with Valkey, Memcached and Redis OSS.', 'elasticache-what-is',
        ['NoteAmazon ElastiCache works with the Valkey, Memcached, and Redis OSS engines.'])),
    cue('cached data must never be stale', 'Write-through caching',
      b('With write-through, data in the cache is never stale.', 'elasticache-strategies',
        ['The advantages of write-through are as follows: Data in the cache is never stale.'])),
    cue('only cache what is actually requested', 'Lazy loading',
      b('With lazy loading only requested data is cached.', 'elasticache-strategies',
        ['The advantages of lazy loading are as follows: Only requested data is cached.'])),
    cue('static IP addresses and fast failover to the nearest healthy Region (not content caching)', 'AWS Global Accelerator',
      b('Global Accelerator provides static anycast IP addresses and routes to the optimal regional endpoint based on health, client location and policies.', 'ga-what-is',
        ['For standard accelerators, Global Accelerator uses the AWS global network to route traffic to the optimal regional endpoint based on health, client location, and policies that you configure, which increases the availability of your applications.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Front Door',
      aws: 'Amazon CloudFront',
      mapping: b('The Learn comparison pairs CloudFront with Azure Front Door, a content delivery network service; it also lists Azure Front Door as a counterpart to AWS Global Accelerator.',
        ['learn-networking', 'cloudfront-what-is'],
        ['learn-networking|Content delivery networks CloudFront Azure Front Door Azure Front Door is a modern cloud content delivery network (CDN) service that provides high performance, scalability, and secure user experiences for your content and applications.',
         'learn-networking|Global traffic acceleration (anycast on backbone) AWS Global Accelerator Azure Front Door / Azure cross-region load balancer',
         'cloudfront-what-is|CloudFront delivers your content through a worldwide network of data centers called edge locations.']),
      breaks: b('One Azure service (Front Door) appears on both sides of the Learn comparison, but AWS keeps two separate products: CloudFront (cache content at the edge) and Global Accelerator (route traffic over the AWS network with static anycast IPs). Learn also notes that Front Door works at layer 7 with integrated CDN and WAF, while the closest match for Global Accelerator is the layer-4 cross-region load balancer.',
        ['learn-networking', 'ga-what-is'],
        ['learn-networking|Azure Front Door operates at layer 7 (HTTP/HTTPS) with integrated CDN and WAF.',
         'learn-networking|Azure cross-region Load Balancer operates at layer 4 for TCP/UDP, which closely matches AWS Global Accelerator\'s layer-4 behavior.',
         'ga-what-is|The static IP addresses are anycast from the AWS edge network.'],
        { allow: ['two'] }),
    },
    {
      concept: 'Azure Managed Redis',
      aws: 'Amazon ElastiCache',
      mapping: b('The Learn databases page pairs Amazon ElastiCache with Azure Managed Redis as the in-memory cache and temporary data store, for caching, sessions and other low-latency temporary-data patterns.',
        ['learn-databases', 'elasticache-what-is'],
        ['learn-databases|In-memory cache and temporary data store Amazon ElastiCache Azure Managed Redis Use Azure Managed Redis for caching, sessions, messaging, and other low-latency temporary-data patterns.',
         'elasticache-what-is|Amazon ElastiCache is a web service that makes it easy to set up, manage, and scale a distributed in-memory data store or cache environment in the cloud.']),
      breaks: b('Learn says Azure Managed Redis is a cache and temporary data store, and lists no direct Azure equivalent for Amazon MemoryDB, which is designed as a durable primary database. On the exam, treat ElastiCache as a cache and do not assume the Azure Redis service replaces a durable database.',
        ['learn-databases', 'elasticache-what-is'],
        ['learn-databases|Azure Managed Redis is a cache and temporary data store.',
         'learn-databases|Durable Redis-compatible database Amazon MemoryDB No direct equivalent Amazon MemoryDB is designed as a durable primary database.',
         'elasticache-what-is|NoteAmazon ElastiCache works with the Valkey, Memcached, and Redis OSS engines.']),
    },
  ],
};

export default notes;
