import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'cargo-hall',
  overview: [
    b('AWS storage comes in three types: block, file and object. The type determines how data is accessed, so identify the type first and the service second. Amazon EBS is block storage, Amazon EFS and Amazon FSx are file storage, and Amazon S3 is object storage.',
      'storage-decision',
      ['You can select from block, file, and object storage services as well as cloud data migration options for your workload.',
       'Protocols play a crucial role when considering AWS storage services as they determine how data is accessed, transferred, and managed within the storage environment.'],
      { allow: ['three'] }),
    b('This building teaches the three types and how AWS decision guides help you choose compute, storage and database technologies from requirements. The detailed comparisons of EBS, EFS and FSx, and of instance store and EBS, are in Storage Market and Block Warehouse.',
      ['storage-decision', 'compute-decision', 'database-decision'],
      ['storage-decision|You can select from block, file, and object storage services as well as cloud data migration options for your workload.',
       'compute-decision|These include Amazon EC2 for resizable virtual servers, Elastic Beanstalk for deploying web applications on your choice of a number of popular platforms, AWS Lambda for serverless computing, Amazon ECS and EKS for container orchestration, and AWS Fargate for serverless containers.',
       'database-decision|AWS offers a growing number of database options (15+) with diverse data models to support a variety of workloads.'],
      { allow: ['three'] }),
  ],
  bullets: [
    {
      id: '2.1-K13',
      concepts: [
        b('Object storage stores and manages data in an unstructured format called objects, and provides access through an application programming interface (API) over the internet. It is well suited to read-heavy workloads such as streaming applications. Amazon S3 is an object storage service that stores data as objects within buckets.',
          ['storage-decision', 's3-what-is'],
          ['storage-decision|Object — Object storage is a technology that stores and manages data in an unstructured format called objects.',
           'storage-decision|Object storage provides easy access to data through an application programming interface (API) over the internet and is well-suited to read-heavy workloads (such as streaming applications and services).',
           's3-what-is|Amazon S3 is an object storage service that stores data as objects, hierarchical data, or tabular data within buckets.']),
        b('Block storage divides data into blocks of equal size and stores each block on underlying physical storage in a manner optimised for fast access. It offers high-performance storage direct-attached to a compute instance with low-latency access. Amazon EBS provides block storage volumes that you attach to Amazon EC2 instances and then use like a local hard drive.',
          ['storage-decision', 'ebs-what-is'],
          ['storage-decision|It takes any data, like a file or database entry, and divides it into blocks of equal sizes.',
           'storage-decision|Block storage offers high-performance storage that is direct-attached to a compute instance with low-latency access, making it suitable for applications that require fast and consistent I/O operations.',
           'ebs-what-is|Amazon EBS volumes — These are storage volumes that you attach to Amazon EC2 instances.',
           'ebs-what-is|After you attach a volume to an instance, you can use it in the same way you would use a local hard drive attached to a computer, for example to store files or to install applications.']),
        b('File storage keeps data in a hierarchical structure of files and folders and is natively mountable from virtually any operating system using industry-standard protocols like NFS and SMB. Amazon EFS provides serverless, fully elastic file storage that supports the Network File System (NFS) protocol, so multiple clients can share file data; Amazon FSx offers managed file systems that align to widely used file systems and protocols.',
          ['storage-decision', 'efs-what-is'],
          ['storage-decision|File system — File systems store data in a hierarchical structure of files and folders.',
           'storage-decision|File-based storage is natively mountable from virtually any operating system using industry-standard protocols like NFS and SMB.',
           'efs-what-is|Amazon Elastic File System (Amazon EFS) provides serverless, fully elastic file storage so that you can share file data without provisioning or managing storage capacity and performance.',
           'efs-what-is|Amazon EFS supports the Network File System version 4 (NFSv4.1 and NFSv4.0) protocol, so the applications and tools that you use today work seamlessly with Amazon EFS.']),
        b('AWS summarises the match between workload and type: block for applications requiring low-latency, high-performance durable storage attached to single EC2 instances or containers, such as databases; file for applications requiring shared read and write access across multiple EC2 instances or containers, or from multiple on-premises servers, such as team file shares.',
          'storage-decision',
          ['Storage services or tools Block Applications requiring low-latency, high-performance durable storage attached to single Amazon EC2 instances or containers, such as databases and general-purpose local instance storage.',
           'Applications and workloads requiring shared read and write access across multiple Amazon EC2 instances or containers, or from multiple on-premises servers, such as team file shares, highly available enterprise applications, analytics workloads, and ML training.']),
        b('Block storage is usually attached to a single instance, but EBS Multi-Attach is an exception: it lets you attach a single Provisioned IOPS SSD (io1 or io2) volume to multiple instances in the same Availability Zone.',
          'ebs-multi-attach',
          ['Amazon EBS Multi-Attach enables you to attach a single Provisioned IOPS SSD (io1 or io2) volume to multiple instances that are in the same Availability Zone.']),
        b('EBS snapshots are point-in-time backups of EBS volumes that persist independently from the volume itself.',
          'ebs-what-is',
          ['Amazon EBS snapshots — These are point-in-time backups of Amazon EBS volumes that persist independently from the volume itself.']),
      ],
      services: ['Amazon S3', 'Amazon EFS', 'Amazon EBS', 'Amazon EC2'],
      design: [
        b('Ask what the access pattern is: a disk attached to an instance (block, EBS), a file system mounted and shared by many clients (file, EFS or FSx), or objects stored and fetched by API (S3). Once the type is clear, durability, performance and cost help select the exact service and class.',
          ['storage-decision', 'efs-what-is'],
          ['storage-decision|Protocols play a crucial role when considering AWS storage services as they determine how data is accessed, transferred, and managed within the storage environment.',
           'storage-decision|Storage services or tools Block Applications requiring low-latency, high-performance durable storage attached to single Amazon EC2 instances or containers, such as databases and general-purpose local instance storage.',
           'storage-decision|File-based storage is natively mountable from virtually any operating system using industry-standard protocols like NFS and SMB.',
           'storage-decision|Object storage provides easy access to data through an application programming interface (API) over the internet and is well-suited to read-heavy workloads (such as streaming applications and services).']),
      ],
    },
    {
      id: '2.1-S6',
      concepts: [
        b('To recommend technology from requirements, AWS publishes decision guides. For compute, the guide lists Amazon EC2 for resizable virtual servers, Elastic Beanstalk for deploying web applications, AWS Lambda for serverless computing, Amazon ECS and EKS for container orchestration, and AWS Fargate for serverless containers.',
          'compute-decision',
          ['These include Amazon EC2 for resizable virtual servers, Elastic Beanstalk for deploying web applications on your choice of a number of popular platforms, AWS Lambda for serverless computing, Amazon ECS and EKS for container orchestration, and AWS Fargate for serverless containers.']),
        b('For databases, AWS offers many database options with diverse data models: relational, key-value, document, in-memory, graph, time series, vector and wide-column. Databases fall into OLTP (relational and non-relational) and analytics. Purpose-Built Workshop covers the data-model matching in detail.',
          'database-decision',
          ['AWS offers a growing number of database options (15+) with diverse data models to support a variety of workloads.',
           'These include relational, key-value, document, in-memory, graph, time series, vector, and wide-column.',
           'There are two high-level categories of AWS OLTP databases—relational and non-relational.'],
          { allow: ['two'] }),
        b('For storage, match block, file and object to the workload (see the previous bullet). The networking technologies are covered in their own buildings: Elastic Load Balancing in Scaling Floodgate, and CloudFront and Global Accelerator in Cache & Edge Breakwater.',
          'storage-decision',
          ['You can select from block, file, and object storage services as well as cloud data migration options for your workload.']),
        b('The decision guides expect you to weigh requirements, not just features: for example, for databases, performance (does it need to support a high concurrency of transactions, or deploy in multiple geographic Regions), and for storage, choosing right-sized storage classes and tiering to reduce the storage footprint.',
          ['database-decision', 'storage-decision'],
          ['database-decision|Performance - Consider whether your database will need to support a high concurrency of transactions (10,000 or more), and whether it needs to be deployed in multiple geographic regions.',
           'storage-decision|For storage, choosing right-sized storage classes and using tiering such as Intelligent-Tiering and Infrequent Access or Archive tiers helps reduce your storage footprint.']),
      ],
      services: ['Amazon EC2', 'AWS Lambda', 'Amazon S3', 'Amazon EBS', 'Amazon EFS'],
      design: [
        b('A good answer names the technology and the reason in the question\'s own terms: shared file system for many Linux servers → EFS; attached low-latency disk for a database on EC2 → EBS; objects fetched by API → S3; no servers to manage → Lambda or Fargate.',
          ['storage-decision', 'efs-what-is', 'lambda-welcome', 'fargate-ecs'],
          ['storage-decision|Storage services or tools Block Applications requiring low-latency, high-performance durable storage attached to single Amazon EC2 instances or containers, such as databases and general-purpose local instance storage.',
           'storage-decision|Object storage provides easy access to data through an application programming interface (API) over the internet and is well-suited to read-heavy workloads (such as streaming applications and services).',
           'efs-what-is|Amazon Elastic File System (Amazon EFS) provides serverless, fully elastic file storage so that you can share file data without provisioning or managing storage capacity and performance.',
           'lambda-welcome|With Lambda, you can run code without provisioning or managing servers.',
           'fargate-ecs|With AWS Fargate, you no longer have to provision, configure, or scale clusters of virtual machines to run containers.']),
      ],
    },
  ],
  cues: [
    cue('shared file system mounted by many EC2 instances, NFS', 'Amazon EFS (Linux, NFS)',
      b('EFS provides serverless, elastic file storage for sharing file data and supports the NFS protocol.', 'efs-what-is',
        ['Amazon Elastic File System (Amazon EFS) provides serverless, fully elastic file storage so that you can share file data without provisioning or managing storage capacity and performance.'])),
    cue('SMB / Windows file shares / NetApp ONTAP / OpenZFS / Lustre', 'Amazon FSx (matching variant)',
      b('FSx offers managed file systems for Windows (SMB), NetApp ONTAP (NFS and SMB), OpenZFS (NFS) and Lustre (speed-sensitive workloads such as HPC).', ['storage-decision', 'fsx-windows', 'fsx-openzfs', 'fsx-lustre'],
        ['storage-decision|Amazon FSx for NetApp ONTAP supports both NFS and SMB protocols, including concurrent multi-protocol access to the same data.',
         'fsx-windows|Amazon FSx has native support for Windows file system features and for the industry-standard Server Message Block (SMB) protocol to access file storage over a network.',
         'fsx-openzfs|Amazon FSx for OpenZFS file systems are broadly accessible from Linux, Windows, and macOS compute instances and containers using the industry-standard NFS protocol (v3, v4.0, v4.1, v4.2).',
         'fsx-lustre|You use Lustre for workloads where speed matters, such as machine learning, high performance computing (HPC), video processing, and financial modeling.'])),
    cue('boot volume / low-latency disk attached to one instance / database on EC2', 'Amazon EBS',
      b('EBS volumes attach to EC2 instances and behave like a local hard drive.', 'ebs-what-is',
        ['After you attach a volume to an instance, you can use it in the same way you would use a local hard drive attached to a computer, for example to store files or to install applications.'])),
    cue('store unstructured data as objects, access over an API / static website / data lake', 'Amazon S3',
      b('Object storage stores unstructured data as objects and is accessed through an API.', 'storage-decision',
        ['Object storage provides easy access to data through an application programming interface (API) over the internet and is well-suited to read-heavy workloads (such as streaming applications and services).'])),
    cue('point-in-time backup of a disk', 'EBS snapshot',
      b('EBS snapshots are point-in-time backups of volumes that persist independently from the volume.', 'ebs-what-is',
        ['Amazon EBS snapshots — These are point-in-time backups of Amazon EBS volumes that persist independently from the volume itself.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Blob storage',
      aws: 'Amazon S3',
      mapping: b('Learn describes Azure Blob storage as storing any type of text or binary data, such as a document, media file or application installer, and compares it with AWS S3.',
        ['learn-storage', 's3-what-is'],
        ['learn-storage|In Azure Storage, subscription-bound storage accounts allow you to create and manage the following storage services: Blob storage stores any type of text or binary data, such as a document, media file, or application installer.',
         's3-what-is|Amazon S3 is an object storage service that stores data as objects, hierarchical data, or tabular data within buckets.']),
      breaks: b('Learn says Blob storage serves the same purpose as both AWS S3 and EBS. On AWS they are different storage types: S3 is object storage accessed through an API, and EBS is block storage attached to an EC2 instance.',
        ['learn-storage', 'storage-decision'],
        ['learn-storage|Blob storage serves the same purpose as both AWS S3 and EBS.',
         'storage-decision|Object storage provides easy access to data through an application programming interface (API) over the internet and is well-suited to read-heavy workloads (such as streaming applications and services).',
         'storage-decision|Block storage offers high-performance storage that is direct-attached to a compute instance with low-latency access, making it suitable for applications that require fast and consistent I/O operations.']),
    },
    {
      concept: 'Azure Files',
      aws: 'Amazon EFS and Amazon FSx',
      mapping: b('Learn groups the shared AWS storage services (Amazon EFS and the FSx family of managed file systems) as the file-sharing side of AWS storage, which Azure serves with Azure Files.',
        ['learn-storage', 'efs-what-is'],
        ['learn-storage|Various shared storage services that AWS provides, like Elastic File System (EFS) and the FSx family of managed file systems.',
         'learn-storage|Azure Files can be deployed in two main ways: by directly mounting the serverless Azure file shares or by caching Azure file shares on-premises using Azure File Sync.',
         'efs-what-is|Amazon EFS supports the Network File System version 4 (NFSv4.1 and NFSv4.0) protocol, so the applications and tools that you use today work seamlessly with Amazon EFS.'],
        { allow: ['two'] }),
      breaks: b('AWS splits file storage across services by protocol and file system: EFS for NFS, and FSx variants for Windows (SMB), NetApp ONTAP (NFS and SMB), OpenZFS (NFS) and Lustre. The Learn comparison groups EFS and the FSx family together on the AWS side.',
        ['storage-decision', 'fsx-windows', 'fsx-openzfs', 'learn-storage'],
        ['storage-decision|Amazon FSx for NetApp ONTAP supports both NFS and SMB protocols, including concurrent multi-protocol access to the same data.',
         'fsx-windows|Amazon FSx has native support for Windows file system features and for the industry-standard Server Message Block (SMB) protocol to access file storage over a network.',
         'fsx-openzfs|Amazon FSx for OpenZFS file systems are broadly accessible from Linux, Windows, and macOS compute instances and containers using the industry-standard NFS protocol (v3, v4.0, v4.1, v4.2).',
         'learn-storage|Various shared storage services that AWS provides, like Elastic File System (EFS) and the FSx family of managed file systems.']),
    },
    {
      concept: 'Azure managed disks',
      aws: 'Amazon EBS',
      mapping: b('Learn pairs Amazon EBS with Azure managed disks, SSD storage that is optimised for I/O-intensive read/write operations, and matches EBS volume types to disk types.',
        ['learn-storage', 'ebs-what-is'],
        ['learn-storage|Virtual server disks AWS service Azure service Description Elastic Block Store (EBS) Managed disks SSD storage that\'s optimized for I/O-intensive read/write operations.',
         'ebs-what-is|Amazon Elastic Block Store (Amazon EBS) provides scalable, high-performance block storage resources that can be used with Amazon Elastic Compute Cloud (Amazon EC2) instances.']),
      breaks: b('Learn notes that for higher-performing disks, on both clouds you need to match the storage performance of the VM with the provisioned disk type and configuration. EBS volume-type choices are covered in Block Warehouse.',
        ['learn-storage', 'ebs-what-is'],
        ['learn-storage|For higher-performing disks, on both AWS and Azure you need to match the storage performance of the VM with the provisioned disk type and configuration.',
         'ebs-what-is|Amazon EBS snapshots — These are point-in-time backups of Amazon EBS volumes that persist independently from the volume itself.']),
    },
  ],
};

export default notes;
