import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'container-dock',
  overview: [
    b('A container packages an application with its dependencies so it runs the same way anywhere a container runtime exists. AWS describes the benefits as portability (a consistent runtime environment on any platform that supports the container runtime) and gives you a layered choice: a registry to store images, an orchestrator to schedule them, and compute to run them.',
      'container-decision',
      ['Portability: Benefit from a consistent runtime environment that can run on any platform that supports the container runtime.',
       'The orchestration layer schedules and scales your environment.']),
  ],
  bullets: [
    {
      id: '2.1-K8',
      concepts: [
        b('To migrate an existing application into containers you build a container image, store it in a registry, and run it on an orchestrator. Amazon ECR is the AWS managed container image registry; you push, pull and manage Docker and OCI images with your preferred CLI, and private repositories use resource-based permissions with IAM.',
          'ecr-what-is',
          ['Amazon Elastic Container Registry (Amazon ECR) is an AWS managed container image registry service that is secure, scalable, and reliable.',
           'Amazon ECR supports private repositories with resource-based permissions using AWS IAM.',
           'You can use your preferred CLI to push, pull, and manage Docker images, Open Container Initiative (OCI) images, and OCI compatible artifacts.']),
        b('AWS App2Container was a command line tool to lift and shift applications from on-premises data centres or virtual machines into containers managed by Amazon ECS, Amazon EKS or AWS App Runner, without needing the application\'s source code. AWS now states that it is no longer open to new customers, so treat it as background, not as the answer to a new design.',
          'a2c',
          ['AWS App2Container (A2C) is a command line tool to help you lift and shift applications that run in your on-premises data centers or on virtual machines, so that they run in containers that are managed by Amazon ECS, Amazon EKS, or AWS App Runner.',
           'App2Container does not need source code for the application to containerize it.',
           'AWS .NET Modernization Tools Porting Assistant (PA) for .NET, AWS App2Container (A2C), AWS Toolkit for .NET Refactoring (TR), and AWS Microservice Extractor (ME) for .NET is no longer open to new customers.'],
          { status: 'deprecated' }),
        b('AWS lists the benefits of containerisation as reduced operational overhead and infrastructure costs, increased development and deployment agility, and standardised build and deployment processes across an organisation.',
          'a2c',
          ['There are many benefits to containerization: Reduces operational overhead and infrastructure costs Increases development and deployment agility Standardizes build and deployment processes across an organization']),
      ],
      services: ['Amazon ECR', 'Amazon ECS', 'Amazon EKS', 'AWS Fargate'],
      design: [
        b('Migration to containers is easier when the application is already stateless: state held on the instance has to move to a managed store before any container can be replaced freely (see Blueprint Hall).',
          'waf-stateless',
          ['Systems should either not require state, or should offload state such that between different client requests, there is no dependence on locally stored data on disk and in memory.']),
      ],
    },
    {
      id: '2.1-K14',
      concepts: [
        b('Amazon ECS is a fully managed container orchestration service that helps you deploy, manage and scale containerised applications. A task definition is the blueprint for the application; a task is an application such as a batch job that performs work and then stops; a service is a long-running stateless application; a cluster is the infrastructure your application runs on.',
          'ecs-what-is',
          ['Amazon Elastic Container Service (Amazon ECS) is a fully managed container orchestration service that helps you easily deploy, manage, and scale containerized applications.',
           'Task definition The blueprint for the application.',
           'Task An application such as a batch job that performs work, and then stops.',
           'Service A long running stateless application.',
           'Cluster The infrastructure your application runs on.']),
        b('ECS capacity, the infrastructure where containers run, can be Fargate (a serverless, pay-as-you-go compute engine where you do not manage servers), Amazon EC2 instances (you choose the instance type and number and manage the capacity), ECS Managed Instances (EC2 instance types with AWS handling provisioning, patching and scaling), or on-premises servers through ECS Anywhere.',
          'ecs-what-is',
          ['The capacity is the infrastructure where your containers run.',
           'Serverless in the AWS cloud Fargate is a serverless, pay-as-you-go compute engine.',
           'Amazon EC2 instances in the AWS cloud You choose the instance type, the number of instances, and manage the capacity.',
           'Amazon ECS Managed Instances is a compute option for Amazon ECS that enables you to run containerized workloads on a range of Amazon EC2 instance types while offloading infrastructure management to AWS.',
           'Amazon ECS Anywhere provides support for registering an external instance such as an on-premises server or virtual machine (VM), to your Amazon ECS cluster.']),
        b('Amazon EKS is a fully managed Kubernetes service. It is certified Kubernetes-conformant, so Kubernetes-compatible applications deploy without refactoring. With EKS standard, AWS manages the Kubernetes control plane; EKS Auto Mode extends that to managing nodes as well.',
          'eks-what-is',
          ['Amazon Elastic Kubernetes Service (EKS) provides a fully managed Kubernetes service that eliminates the complexity of operating Kubernetes clusters.',
           'Amazon EKS is certified Kubernetes-conformant, so you can deploy Kubernetes-compatible applications without refactoring and use Kubernetes community tooling and plugins.',
           'EKS standard: AWS manages the Kubernetes control plane when you create a cluster with EKS.',
           'EKS Auto Mode: Using the EKS Auto Mode feature, EKS extends its control to manage Nodes (Kubernetes data plane) as well.']),
        b('Fargate is not a separate orchestrator: you can use Fargate with both Amazon ECS and Amazon EKS, and EC2 instances can be the compute layer for both too.',
          'container-decision',
          ['You can use Fargate with both Amazon ECS and Amazon EKS.',
           'EC2 instances can be used as the compute layer for both Amazon ECS and Amazon EKS.']),
        b('AWS App Runner is a fully managed service that simplifies deploying containerised web applications and APIs: you provide a container image and App Runner builds, deploys and scales the application. AWS now states that App Runner is no longer open to new customers, so treat it as background, not as the answer to a new design.',
          ['container-decision', 'apprunner-what-is'],
          ['container-decision|AWS App Runner is a fully managed service designed to simplify the deployment and use of containerized web applications and APIs.',
           'container-decision|You provide your container image, and App Runner automatically builds, deploys, and scales your application.',
           'apprunner-what-is|AWS App Runner is no longer open to new customers.'],
          { status: 'deprecated' }),
      ],
      services: ['Amazon ECS', 'Amazon EKS', 'AWS Fargate', 'Amazon ECR'],
      design: [
        b('The first decision AWS suggests is your operating model: a serverless operational model or a Kubernetes operational model. Choose EKS where you want Kubernetes and its portability of skills and tooling; otherwise Amazon ECS is the AWS-native orchestrator.',
          'container-decision',
          ['One of the first considerations is your preference for either a serverless operational model or a Kubernetes operation model.',
           'Amazon EKS provides flexibility and control over application deployment and orchestration provided by Kubernetes technology.']),
      ],
    },
    {
      id: '2.1-S4',
      concepts: [
        b('Use containers when you want portability and a consistent runtime, or when the application does not fit a function\'s limits but you still want to avoid managing servers (Fargate). Being packaged as an image does not rule out Lambda, because Lambda also accepts container images as a deployment package; Lambda is still aimed at request-response or event-driven work (see Serverless Mill). Choose EC2 capacity when you want to choose the instance type and manage the capacity yourself.',
          ['container-decision', 'fargate-ecs', 'lambda-images', 'lambda-welcome', 'ecs-what-is'],
          ['container-decision|Portability: Benefit from a consistent runtime environment that can run on any platform that supports the container runtime.',
           'fargate-ecs|With AWS Fargate, you no longer have to provision, configure, or scale clusters of virtual machines to run containers.',
           'lambda-images|Lambda supports two types of deployment packages: container images and .zip file archives.',
           'lambda-welcome|Request-response or event-driven workloads (APIs, data processing, automation)',
           'ecs-what-is|Amazon EC2 instances in the AWS cloud You choose the instance type, the number of instances, and manage the capacity.']),
        b('With Fargate you do not need to manage servers, handle capacity planning, or isolate container workloads for security; with the EC2 option you choose the instance type, the number of instances and manage the capacity.',
          'ecs-what-is',
          ['With Fargate you don\'t need to manage servers, handle capacity planning, or isolate container workloads for security.',
           'Amazon EC2 instances in the AWS cloud You choose the instance type, the number of instances, and manage the capacity.']),
      ],
      services: ['Amazon ECS', 'Amazon EKS', 'AWS Fargate', 'AWS Lambda', 'Amazon EC2'],
      design: [
        b('Typical answer shapes: a containerised microservice where you want minimal server management → ECS on Fargate; existing Kubernetes workloads or Kubernetes tooling required → EKS; short event-driven tasks → Lambda. App Runner also appears in AWS\'s container decision guide, but it is no longer open to new customers.',
          ['container-decision', 'ecs-what-is', 'eks-what-is', 'lambda-welcome', 'apprunner-what-is'],
          ['ecs-what-is|With Fargate you don\'t need to manage servers, handle capacity planning, or isolate container workloads for security.',
           'eks-what-is|Amazon EKS is certified Kubernetes-conformant, so you can deploy Kubernetes-compatible applications without refactoring and use Kubernetes community tooling and plugins.',
           'lambda-welcome|Request-response or event-driven workloads (APIs, data processing, automation)',
           'apprunner-what-is|AWS App Runner is no longer open to new customers.']),
      ],
    },
  ],
  cues: [
    cue('run containers without managing servers or clusters of instances', 'AWS Fargate (with ECS or EKS)',
      b('With Fargate you no longer provision, configure or scale clusters of virtual machines to run containers.', 'fargate-ecs',
        ['With AWS Fargate, you no longer have to provision, configure, or scale clusters of virtual machines to run containers.'])),
    cue('existing Kubernetes workloads / must use Kubernetes APIs and tooling', 'Amazon EKS',
      b('EKS is certified Kubernetes-conformant, so Kubernetes-compatible applications deploy without refactoring.', 'eks-what-is',
        ['Amazon EKS is certified Kubernetes-conformant, so you can deploy Kubernetes-compatible applications without refactoring and use Kubernetes community tooling and plugins.'])),
    cue('managed container orchestration (not Kubernetes)', 'Amazon ECS',
      b('Amazon ECS is a fully managed container orchestration service.', 'ecs-what-is',
        ['Amazon Elastic Container Service (Amazon ECS) is a fully managed container orchestration service that helps you easily deploy, manage, and scale containerized applications.'])),
    cue('store and manage container images privately', 'Amazon ECR',
      b('ECR is a managed container image registry with private repositories and IAM permissions.', 'ecr-what-is',
        ['Amazon ECR supports private repositories with resource-based permissions using AWS IAM.'])),
    cue('containers must run on your own on-premises servers under ECS', 'Amazon ECS Anywhere',
      b('ECS Anywhere lets you register an on-premises server or VM to your ECS cluster.', 'ecs-what-is',
        ['Amazon ECS Anywhere provides support for registering an external instance such as an on-premises server or virtual machine (VM), to your Amazon ECS cluster.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Kubernetes Service (AKS)',
      aws: 'Amazon EKS',
      mapping: b('The Learn comparison pairs Amazon EKS with Azure Kubernetes Service: both orchestrate containerised application deployments with Kubernetes.',
        ['learn-compute', 'eks-what-is'],
        ['learn-compute|Amazon Elastic Kubernetes Service (Amazon EKS) Azure Kubernetes Service (AKS) You can use Amazon EKS and Azure Kubernetes Service (AKS) to orchestrate Docker containerized application deployments with Kubernetes.',
         'eks-what-is|Amazon EKS is certified Kubernetes-conformant, so you can deploy Kubernetes-compatible applications without refactoring and use Kubernetes community tooling and plugins.']),
      breaks: b('AKS has two modes (Standard and Automatic) and EKS also has two approaches (standard EKS and EKS Auto Mode), but AWS has a second, non-Kubernetes orchestrator, Amazon ECS. The Learn comparison pairs ECS with Azure Container Apps, not with AKS.',
        ['learn-compute', 'eks-what-is', 'ecs-what-is'],
        ['learn-compute|Azure Kubernetes Service (AKS) provides two modes: AKS Standard for full control and customization and AKS Automatic for simplified, production-ready deployments with built-in best practices.',
         'learn-compute|AWS service Azure service Description Amazon Elastic Container Service (Amazon ECS) Azure Container Apps Amazon ECS is a container orchestration service for deploying and managing containerized applications.',
         'eks-what-is|Two of the main approaches to using Amazon EKS are as follows: EKS standard: AWS manages the Kubernetes control plane when you create a cluster with EKS.'],
        { allow: ['two'] }),
    },
    {
      concept: 'Azure Container Registry',
      aws: 'Amazon ECR',
      mapping: b('The Learn comparison pairs Amazon ECR with Azure Container Registry: container registries that store Docker-formatted images for container deployments.',
        ['learn-compute', 'ecr-what-is'],
        ['learn-compute|Amazon Elastic Container Registry (Amazon ECR) Azure Container Registry Container registries store Docker-formatted images and create all types of container deployments in the cloud.',
         'ecr-what-is|You can use your preferred CLI to push, pull, and manage Docker images, Open Container Initiative (OCI) images, and OCI compatible artifacts.']),
      breaks: b('The Microsoft Learn comparison describes both as registries for Docker-formatted images and says nothing about access control. On the AWS side, private ECR repositories have resource-based permissions using IAM.',
        ['ecr-what-is', 'learn-compute'],
        ['ecr-what-is|Amazon ECR supports private repositories with resource-based permissions using AWS IAM.',
         'learn-compute|Amazon Elastic Container Registry (Amazon ECR) Azure Container Registry Container registries store Docker-formatted images and create all types of container deployments in the cloud.']),
    },
    {
      concept: 'Azure Container Instances / Azure Container Apps',
      aws: 'AWS Fargate',
      mapping: b('The Learn comparison pairs AWS Fargate with Azure Container Instances and Azure Container Apps: serverless container compute.',
        ['learn-compute', 'fargate-ecs'],
        ['learn-compute|AWS Fargate Azure Container Instances, Azure Container Apps AWS Fargate is a serverless compute engine that provides compute capacity for Amazon ECS tasks and Amazon EKS pods.',
         'fargate-ecs|With AWS Fargate, you no longer have to provision, configure, or scale clusters of virtual machines to run containers.']),
      breaks: b('On AWS, Fargate is one capacity option that you use with either ECS or EKS (EC2 instances are the other), so the orchestrator (ECS or EKS) and the capacity (Fargate or EC2) are chosen separately. The Microsoft Learn comparison pairs the one AWS service with two Azure services, Container Instances and Container Apps.',
        ['container-decision', 'learn-compute'],
        ['container-decision|You can use Fargate with both Amazon ECS and Amazon EKS.',
         'container-decision|EC2 instances can be used as the compute layer for both Amazon ECS and Amazon EKS.',
         'learn-compute|AWS Fargate Azure Container Instances, Azure Container Apps AWS Fargate is a serverless compute engine that provides compute capacity for Amazon ECS tasks and Amazon EKS pods.'],
        { allow: ['two'] }),
    },
  ],
};

export default notes;
