import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'disaster-bunker',
  overview: [
    b('Disaster recovery (DR) is planning for how to get back after a disaster. The decision is driven by the {{term:rto}} (how long you can be down) and the {{term:rpo}} (how much data you can lose). Read both in the question, then pick the strategy that meets them without more cost and complexity than needed.',
      'dr-objectives',
      ['When creating a Disaster Recovery (DR) strategy, organizations most commonly plan for the Recovery Time Objective (RTO) and Recovery Point Objective (RPO).']),
    b('Your DR plan should be a subset of the organization\'s business continuity plan, not a standalone document. The four strategies, compared in the Don\'t confuse section below, range from the low cost and low complexity of making backups to more complex strategies using multiple active Regions.',
      ['dr-objectives', 'dr-options'],
      ['dr-objectives|Your disaster recovery plan should be a subset of your organization’s business continuity plan (BCP), it should not be a standalone document.',
       'dr-options|Disaster recovery strategies available to you within AWS can be broadly categorized into four approaches, ranging from the low cost and low complexity of making backups to more complex strategies using multiple active Regions.'],
      { allow: ['four'] }),
  ],
  bullets: [
    {
      id: '2.2-K4',
      concepts: [
        b('RTO is the maximum acceptable delay between the interruption of service and restoration of service; RPO is the maximum acceptable amount of time since the last data recovery point. RTO is about downtime and RPO is about data loss.',
          'dr-objectives',
          ['Recovery Time Objective (RTO) is the maximum acceptable delay between the interruption of service and restoration of service.',
           'Recovery Point Objective (RPO) is the maximum acceptable amount of time since the last data recovery point.']),
        b('Backup and restore: take periodic or continuous backups and restore them after a disaster. Suitable for mitigating data loss or corruption. How often you run your backup determines the recovery point you can achieve.',
          'dr-options',
          ['Backup and restore is a suitable approach for mitigating against data loss or corruption.',
           'How often you run your backup will determine your achievable recovery point (which should align to meet your RPO).']),
        b('Pilot light: replicate data to another Region and provision a copy of the core infrastructure, with application servers switched off until failover. Warm standby: a scaled-down but fully functional copy that can handle traffic at reduced capacity immediately. Multi-site active/active: run in multiple Regions at once, serving traffic from all of them.',
          'dr-options',
          ['With the pilot light approach, you replicate your data from one Region to another and provision a copy of your core workload infrastructure.',
           'The warm standby approach involves ensuring that there is a scaled down, but fully functional, copy of your production environment in another Region.',
           'Multi-site active/active serves traffic from all regions to which it is deployed, whereas hot standby serves traffic only from a single region, and the other Region(s) are only used for disaster recovery.']),
        b('AWS provides continuous, cross-region, asynchronous replication through services including S3 Replication, RDS read replicas, Aurora global databases and DynamoDB global tables. Point-in-time backups are available through EBS snapshots, DynamoDB backup and RDS snapshots, and AWS Backup can copy backups across accounts and to other Regions.',
          'dr-options',
          ['AWS provides continuous, cross-region, asynchronous data replication for data using the following services and resources: Amazon Simple Storage Service (Amazon S3) Replication Amazon RDS read replicas Amazon Aurora global databases Amazon DynamoDB global tables Amazon DocumentDB global clusters Global Datastore for Amazon ElastiCache (Redis OSS)',
           'Or, you can use AWS Backup to copy backups across accounts and to other AWS Regions.',
           'Backup with point-in-time recovery is available through the following services and resources: Amazon Elastic Block Store (Amazon EBS) snapshot Amazon DynamoDB backup Amazon RDS snapshot']),
        b('AWS Elastic Disaster Recovery is a service for recovery of on-premises and cloud-based applications: it minimizes downtime and data loss using affordable storage, minimal compute, and point-in-time recovery, by replicating the applications running on supported operating systems.',
          'drs-what-is',
          ['AWS Elastic Disaster Recovery minimizes downtime and data loss with fast, reliable recovery of on-premises and cloud-based applications using affordable storage, minimal compute, and point-in-time recovery.',
           'You can increase IT resilience when you use AWS Elastic Disaster Recovery to replicate on-premises or cloud-based applications running on supported operating systems.']),
        b('Back up configuration and infrastructure as well as data. In addition to data, you must back up the configuration and infrastructure necessary to redeploy the workload to meet your RTO; without infrastructure as code, restoring in the recovery Region may be complex and exceed the RTO.',
          'dr-options',
          ['In addition to data, you must also back up the configuration and infrastructure necessary to redeploy your workload and meet your Recovery Time Objective (RTO).',
           'Without IaC, it may be complex to restore workloads in the recovery Region, which will lead to increased recovery times and possibly exceed your RTO.']),
      ],
      services: ['AWS Backup', 'Amazon Route 53'],
      design: [
        b('Choose by RTO and RPO: use your RTO and RPO needs to choose between the four approaches, which run from the low cost and low complexity of making backups to more complex strategies using multiple active Regions.',
          'dr-options',
          ['Use your RTO and RPO needs to help you choose between these approaches.',
           'Disaster recovery strategies available to you within AWS can be broadly categorized into four approaches, ranging from the low cost and low complexity of making backups to more complex strategies using multiple active Regions.'],
          { allow: ['four'] }),
      ],
    },
    {
      id: '2.2-K6',
      concepts: [
        b('Failover is the switch of traffic from the failed environment to the recovery one. In active/passive designs the passive site does not actively serve traffic until a failover event is triggered; in active/active designs all sites serve traffic.',
          'dr-options',
          ['The passive site does not actively serve traffic until a failover event is triggered.',
           'Multi-site active/active serves traffic from all regions to which it is deployed']),
        b('Route 53 does the traffic part: Route 53 health checks monitor the health and performance of web applications and other resources; active-passive failover uses the failover routing policy and active-active uses any other routing policy.',
          ['route53-failover', 'route53-failover-types'],
          ['route53-failover|Amazon Route 53 health checks monitor the health and performance of your web applications, web servers, and other resources.',
           'route53-failover-types|You configure active-active failover using any routing policy (or combination of routing policies) other than failover, and you configure active-passive failover using the failover routing policy.']),
        b('Prefer data plane operations during failover. AWS divides services into a data plane, responsible for delivering real-time service, and a control plane, used to configure the environment. For maximum resiliency, use only data plane operations as part of your failover operation, because data planes typically have higher availability design goals than control planes.',
          'dr-options',
          ['The data plane is responsible for delivering real-time service while control planes are used to configure the environment.',
           'For maximum resiliency, you should use only data plane operations as part of your failover operation.',
           'This is because the data planes typically have higher availability design goals than the control planes.']),
      ],
      services: ['Amazon Route 53'],
      design: [
        b('Automate the failover path (health check → DNS failover → scale out with Auto Scaling) and test it; for warm standby, the scaled-down environment relies on Auto Scaling to scale out to support production traffic.',
          'dr-options',
          ['To scale-out the infrastructure to support production traffic, see Amazon EC2 Auto Scaling in the Warm Standby section.']),
      ],
    },
    {
      id: '2.2-S6',
      concepts: [
        b('Selecting a strategy is a matching exercise on RTO, RPO, cost and the size of the disaster. For a disaster that is only the loss of one data centre in an already highly available workload, backup and restore may suffice. If the definition of a disaster includes a whole Region, or regulation requires it, consider pilot light, warm standby or multi-site active/active.',
          'dr-options',
          ['For a disaster event based on disruption or loss of one physical data center for a well-architected, highly available workload, you may only require a backup and restore approach to disaster recovery.',
           'If your definition of a disaster goes beyond the disruption or loss of a physical data center to that of a Region or if you are subject to regulatory requirements that require it, then you should consider Pilot Light, Warm Standby, or Multi-Site Active/Active.']),
        b('Multi-site active/active is the most complex and costly approach, but can reduce recovery time to near zero for most disasters; data corruption may still need backups, so the recovery point is usually non-zero.',
          'dr-options',
          ['This approach is the most complex and costly approach to disaster recovery, but it can reduce your recovery time to near zero for most disasters with the correct technology choices and implementation (however data corruption may need to rely on backups, which usually results in a non-zero recovery point).']),
        b('For pilot light, continuous data replication to live databases and data stores in the DR Region is the best approach for a low RPO, used in addition to the point-in-time backups. Continuous replication is near zero for data loss but may not protect against corruption or malicious deletion as well as point-in-time backups.',
          'dr-options',
          ['For pilot light, continuous data replication to live databases and data stores in the DR region is the best approach for low RPO (when used in addition to the point-in-time backups discussed previously).',
           'Continuous replication of data has the advantage of being the shortest time (near zero) to back up your data, but may not protect against disaster events such as data corruption or malicious attack (such as unauthorized data deletion) as well as point-in-time backups.']),
      ],
      services: ['AWS Backup', 'Amazon Route 53'],
      design: [
        b('Quick selection, following the whitepaper\'s ordering: lowest cost and complexity → backup and restore; minimal ongoing cost with core infrastructure already in place → pilot light; must serve traffic immediately at reduced capacity → warm standby; near-zero recovery time with the most complexity and cost accepted → multi-site active/active.',
          'dr-options',
          ['Disaster recovery strategies available to you within AWS can be broadly categorized into four approaches, ranging from the low cost and low complexity of making backups to more complex strategies using multiple active Regions.',
           'A pilot light approach minimizes the ongoing cost of disaster recovery by minimizing the active resources, and simplifies recovery at the time of a disaster because the core infrastructure requirements are all in place.',
           'The distinction is that pilot light cannot process requests without additional action taken first, whereas warm standby can handle traffic (at reduced capacity levels) immediately.',
           'This approach is the most complex and costly approach to disaster recovery, but it can reduce your recovery time to near zero for most disasters with the correct technology choices and implementation (however data corruption may need to rely on backups, which usually results in a non-zero recovery point).']),
      ],
    },
  ],
  cues: [
    cue('lowest cost and complexity, recovery from backups is acceptable', 'Backup and restore',
      b('Backup and restore is at the low-cost, low-complexity end of the DR strategies.', 'dr-options',
        ['Disaster recovery strategies available to you within AWS can be broadly categorized into four approaches, ranging from the low cost and low complexity of making backups to more complex strategies using multiple active Regions.'])),
    cue('core infrastructure ready in another Region but servers switched off', 'Pilot light',
      b('Pilot light replicates data and provisions a copy of the core infrastructure.', 'dr-options',
        ['With the pilot light approach, you replicate your data from one Region to another and provision a copy of your core workload infrastructure.'])),
    cue('scaled-down but fully functional environment that can take traffic immediately', 'Warm standby',
      b('Warm standby can handle traffic at reduced capacity immediately, unlike pilot light.', 'dr-options',
        ['The distinction is that pilot light cannot process requests without additional action taken first, whereas warm standby can handle traffic (at reduced capacity levels) immediately.'])),
    cue('near-zero downtime, all Regions serve traffic', 'Multi-site active/active',
      b('Multi-site active/active serves traffic from all deployed Regions and can reduce recovery time to near zero.', 'dr-options',
        ['Multi-site active/active serves traffic from all regions to which it is deployed, whereas hot standby serves traffic only from a single region, and the other Region(s) are only used for disaster recovery.'])),
    cue('maximum acceptable data loss expressed as time', 'RPO',
      b('RPO is the maximum acceptable amount of time since the last data recovery point.', 'dr-objectives',
        ['Recovery Point Objective (RPO) is the maximum acceptable amount of time since the last data recovery point.'])),
    cue('maximum acceptable downtime', 'RTO',
      b('RTO is the maximum acceptable delay between the interruption of service and restoration of service.', 'dr-objectives',
        ['Recovery Time Objective (RTO) is the maximum acceptable delay between the interruption of service and restoration of service.'])),
    cue('automatically send users to the standby site when the primary fails', 'Route 53 health checks with failover routing',
      b('Active-passive failover uses the failover routing policy.', 'route53-failover-types',
        ['You configure active-active failover using any routing policy (or combination of routing policies) other than failover, and you configure active-passive failover using the failover routing policy.'])),
  ],
  examples: [],
  confuse: ['dr-strategies'],
  azure: [
    {
      concept: 'Azure Backup',
      aws: 'AWS Backup',
      mapping: b('The Learn storage comparison pairs AWS Backup with Azure Backup, used to back up and recover files, databases, disks and virtual machines.',
        ['learn-storage', 'backup-what-is'],
        ['learn-storage|Backup Backup This option is used to back up and recover files, databases, disks, and virtual machines.',
         'backup-what-is|AWS Backup is a fully-managed service that makes it easy to centralize and automate data protection across AWS services, in the cloud, and on premises.']),
      breaks: b('The service and the strategy share a name but are different things. AWS Backup is a service; "backup and restore" is the first of four AWS DR strategies, which range from making backups to more complex strategies using multiple active Regions. The Azure Backup entry in the comparison describes backing up and recovering files, databases, disks and virtual machines, and Learn also says Azure Backup supports backing up compatible on-premises Windows systems.',
        ['dr-options', 'learn-storage'],
        ['dr-options|Disaster recovery strategies available to you within AWS can be broadly categorized into four approaches, ranging from the low cost and low complexity of making backups to more complex strategies using multiple active Regions.',
         'learn-storage|Backup Backup This option is used to back up and recover files, databases, disks, and virtual machines.',
         'learn-storage|Azure Backup also supports backing up compatible on-premises Windows systems.'],
        { allow: ['four'] }),
    },
    {
      concept: 'Azure Site Recovery',
      aws: 'AWS Elastic Disaster Recovery',
      mapping: b('Azure Site Recovery provides continuous replication, failover and recovery capabilities for virtual machines, supporting an Azure disaster recovery strategy. AWS Elastic Disaster Recovery has a comparable purpose: it replicates on-premises or cloud-based applications so that you can recover them. The Microsoft Learn comparison pages do not list this pairing, so it is drawn from each product\'s own pages.',
        ['learn-azure-asr', 'drs-what-is'],
        ['learn-azure-asr|Azure Site Recovery (ASR) provides infrastructure resiliency for your business-critical workloads by providing continuous replication, failover, and recovery capabilities.',
         'drs-what-is|You can increase IT resilience when you use AWS Elastic Disaster Recovery to replicate on-premises or cloud-based applications running on supported operating systems.']),
      breaks: b('Each product describes itself differently, and the Learn comparison pages do not list either product: Site Recovery protects virtual machines against disruptions ranging from zonal failures to regional outages, and Elastic Disaster Recovery replicates on-premises or cloud-based applications on supported operating systems.',
        ['learn-azure-asr', 'drs-what-is'],
        ['learn-azure-asr|ASR supports your disaster recovery (DR) strategy by protecting virtual machines against planned and unplanned disruptions, ranging from zonal failures to regional outages, while meeting your recovery objectives (RPO and RTO).',
         'drs-what-is|You can increase IT resilience when you use AWS Elastic Disaster Recovery to replicate on-premises or cloud-based applications running on supported operating systems.'],
        { allow: ['two'] }),
    },
  ],
};

export default notes;
