import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'durable-dock',
  overview: [
    b('Durability is the chance your data is still there; availability is the chance you can reach it right now. Different storage services get durability in different ways: S3 spreads objects across Availability Zones, EFS offers Regional or One Zone file systems, and EBS volumes live in a single Availability Zone, so snapshots and backups matter more there.',
      ['s3-durability', 'efs-features', 'ebs-volumes'],
      ['s3-durability|Designed to provide 99.999999999% durability and 99.99% availability of objects over a given year.',
       'efs-features|Regional – Regional file systems (recommended) store data redundantly across multiple geographically separated Availability Zones within the same AWS Region.',
       'ebs-volumes|The volume and instance must be in the same Availability Zone.']),
  ],
  bullets: [
    {
      id: '2.2-K11',
      concepts: [
        b('Amazon S3 provides a highly durable storage infrastructure designed for mission-critical and primary data storage. Most storage classes redundantly store objects on multiple devices across a minimum of three Availability Zones in an AWS Region. S3 is designed for 99.999999999% durability and 99.99% availability of objects over a given year; these are design targets that AWS can change.',
          's3-durability',
          ['Amazon S3 provides a highly durable storage infrastructure designed for mission-critical and primary data storage.',
           'S3 Standard, S3 Intelligent-Tiering, S3 Standard-IA, S3 Glacier Instant Retrieval, S3 Glacier Flexible Retrieval, and S3 Glacier Deep Archive redundantly store objects on multiple devices across a minimum of three Availability Zones in an AWS Region.',
           'Designed to provide 99.999999999% durability and 99.99% availability of objects over a given year.']),
        b('A single-zone S3 class is different: with S3 Express One Zone your data is redundantly stored on multiple devices within a single Availability Zone, so unlike the multi-AZ classes it does not spread data across zones.',
          's3-storage-classes',
          ['With S3 Express One Zone, your data is redundantly stored on multiple devices within a single Availability Zone.']),
        b('Amazon EBS volumes are durable, block-level storage devices that you attach to instances, and the volume and instance must be in the same Availability Zone. EBS durability depends on the type: io2 Block Express volumes provide 99.999% durability and other volume types 99.8% to 99.9% durability, according to AWS. Snapshots are point-in-time backups that persist independently from the volume.',
          ['ebs-volumes', 'ebs-what-is'],
          ['ebs-volumes|An Amazon EBS volume is a durable, block-level storage device that you can attach to your instances.',
           'ebs-volumes|The volume and instance must be in the same Availability Zone.',
           'ebs-what-is|Data availability and durability — io2 Block Express volumes provide 99.999% durability with an annual failure rate of 0.001%.',
           'ebs-what-is|Other volume types provide 99.8% to 99.9% durability with an annual failure rate of 0.1% to 0.2%.',
           'ebs-what-is|Amazon EBS snapshots — These are point-in-time backups of Amazon EBS volumes that persist independently from the volume itself.']),
        b('Amazon EFS has two file system types: Regional file systems (recommended) store data redundantly across multiple geographically separated Availability Zones within the same Region, and One Zone file systems store data within a single Availability Zone. For added protection EFS automatically backs up One Zone file systems with AWS Backup.',
          'efs-features',
          ['Regional – Regional file systems (recommended) store data redundantly across multiple geographically separated Availability Zones within the same AWS Region.',
           'One Zone – One Zone file systems store data within a single Availability Zone.',
           'For added data protection, Amazon EFS automatically backs up One Zone file systems with AWS Backup.'],
          { allow: ['two'] }),
        b('Replication copies data to a second location: S3 replication can have destination buckets in a different Region or the same Region as the source bucket, and EFS replication automatically and transparently replicates data and metadata to a destination file system, letting you fail over in a disaster or game-day exercise.',
          ['s3-replication', 'efs-replication'],
          ['s3-replication|The destination buckets can be in different AWS Regions or within the same Region as the source bucket.',
           'efs-replication|When you enable replication on an EFS file system, Amazon EFS automatically and transparently replicates the data and metadata on the source file system to a destination file system.',
           'efs-replication|In the event of a disaster or when performing game day exercises, you can fail over to your replica file system.']),
      ],
      services: ['Amazon S3', 'Amazon EBS', 'Amazon EFS'],
      design: [
        b('Read the failure the question describes: loss of one AZ → multi-AZ storage (S3 classes spread across AZs, EFS Regional) or a copy elsewhere; loss of a Region → cross-Region replication or copied backups; accidental deletion or corruption → versioning, snapshots and backups, because replication also copies bad changes.',
          ['s3-durability', 'dr-options'],
          ['s3-durability|With versioning, you can easily recover from both unintended user actions and application failures.',
           'dr-options|Continuous replication of data has the advantage of being the shortest time (near zero) to back up your data, but may not protect against disaster events such as data corruption or malicious attack (such as unauthorized data deletion) as well as point-in-time backups.']),
      ],
    },
    {
      id: '2.2-S5',
      concepts: [
        b('S3 versioning preserves, retrieves and restores every version of every object in a bucket, which helps you recover from both unintended user actions and application failures.',
          's3-durability',
          ['You can use versioning to preserve, retrieve, and restore every version of every object that is stored in your Amazon S3 bucket.',
           'With versioning, you can easily recover from both unintended user actions and application failures.']),
        b('EBS snapshots back up volumes at a point in time, independently of the volume. AWS Backup centralises and automates data protection across AWS services using backup plans (policies) that you apply to the resources you want to protect.',
          ['ebs-what-is', 'backup-what-is'],
          ['ebs-what-is|You can create snapshots to back up the data on your Amazon EBS volumes.',
           'backup-what-is|With AWS Backup, you can create backup policies known as backup plans.',
           'backup-what-is|Use these backup plans to define your backup requirements and then apply them to the AWS resources that you want to protect across the AWS services that you use.']),
        b('AWS Backup can copy backups to multiple different AWS Regions on demand or automatically as part of a scheduled backup plan, which is valuable when you must keep backups a minimum distance away from production data.',
          'backup-what-is',
          ['Using AWS Backup, you can copy backups to multiple different AWS Regions on demand or automatically as part of a scheduled backup plan.',
           'Cross-Region backup is particularly valuable if you have business continuity or compliance requirements to store backups a minimum distance away from your production data.']),
        b('Whole RDS and database backup, and the S3 Object Lock and Glacier Vault Lock immutability options, are covered in the Citadel (Archive Annex); the disaster recovery strategies that use these backups are in Disaster Bunker.',
          'dr-options',
          ['Backup and restore is a suitable approach for mitigating against data loss or corruption.']),
      ],
      services: ['AWS Backup', 'Amazon S3', 'Amazon EBS', 'Amazon EFS'],
      design: [
        b('Typical answer: protect against deletion with versioning and backups, against AZ loss with multi-AZ or replicated data, and against Region loss with cross-Region replication or cross-Region backup copies, then match the choice to the stated RPO.',
          ['dr-options', 'backup-what-is'],
          ['dr-options|How often you run your backup will determine your achievable recovery point (which should align to meet your RPO).',
           'backup-what-is|Using AWS Backup, you can copy backups to multiple different AWS Regions on demand or automatically as part of a scheduled backup plan.']),
      ],
    },
  ],
  cues: [
    cue('objects must survive the loss of an Availability Zone', 'S3 Standard or other multi-AZ classes (not One Zone)',
      b('Most S3 classes store objects across a minimum of three Availability Zones.', 's3-durability',
        ['S3 Standard, S3 Intelligent-Tiering, S3 Standard-IA, S3 Glacier Instant Retrieval, S3 Glacier Flexible Retrieval, and S3 Glacier Deep Archive redundantly store objects on multiple devices across a minimum of three Availability Zones in an AWS Region.'])),
    cue('shared file system must survive an AZ failure', 'EFS Regional file system',
      b('Regional EFS file systems store data redundantly across multiple Availability Zones.', 'efs-features',
        ['Regional – Regional file systems (recommended) store data redundantly across multiple geographically separated Availability Zones within the same AWS Region.'])),
    cue('recover from accidental overwrite or deletion of objects', 'S3 versioning',
      b('Versioning lets you restore every version of every object.', 's3-durability',
        ['With versioning, you can easily recover from both unintended user actions and application failures.'])),
    cue('point-in-time backup of an EBS volume', 'EBS snapshot',
      b('Snapshots are point-in-time backups that persist independently from the volume.', 'ebs-what-is',
        ['Amazon EBS snapshots — These are point-in-time backups of Amazon EBS volumes that persist independently from the volume itself.'])),
    cue('centrally schedule and enforce backups across services, copy to another Region', 'AWS Backup (backup plans)',
      b('Backup plans define backup requirements and apply to resources across services; backups can be copied to other Regions.', 'backup-what-is',
        ['Use these backup plans to define your backup requirements and then apply them to the AWS resources that you want to protect across the AWS services that you use.'])),
    cue('copy data to another Region continuously', 'S3 cross-Region replication / EFS replication',
      b('S3 replication destinations can be in a different Region; EFS replicates to a destination file system.', 's3-replication',
        ['The destination buckets can be in different AWS Regions or within the same Region as the source bucket.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure storage redundancy (LRS, ZRS, GRS)',
      aws: 'Amazon S3 storage classes, EFS Regional and One Zone, and replication',
      mapping: b('Azure Storage offers locally redundant storage (LRS), which replicates data to a single physical datacenter in the primary region, and zone-redundant storage (ZRS), which copies data synchronously across three or more availability zones. For comparison, most S3 storage classes store objects across a minimum of three Availability Zones in an AWS Region.',
        ['learn-storage-redundancy', 's3-durability'],
        ['learn-storage-redundancy|Locally redundant storage (LRS) replicates the data within your storage accounts to a single physical datacenter located in the primary region of your choice.',
         'learn-storage-redundancy|Zone-redundant storage (ZRS) copies your data synchronously across three or more Azure availability zones in the primary region.',
         's3-durability|S3 Standard, S3 Intelligent-Tiering, S3 Standard-IA, S3 Glacier Instant Retrieval, S3 Glacier Flexible Retrieval, and S3 Glacier Deep Archive redundantly store objects on multiple devices across a minimum of three Availability Zones in an AWS Region.']),
      breaks: b('Two things differ. First, on Azure you choose the redundancy level as a property of the storage account, while on AWS multi-AZ is built into most S3 classes and you instead choose between classes, EFS file system types and EBS (single Availability Zone). Second, Azure geo-redundant storage copies data to a secondary region asynchronously as part of the redundancy option, whereas on AWS you configure cross-Region replication or cross-Region backup copies yourself. (Microsoft Learn\'s AWS comparison page words geo-redundant replication differently from the dedicated Azure Storage page; the dedicated page is used here.)',
        ['learn-storage-redundancy', 'learn-storage', 's3-replication'],
        ['learn-storage-redundancy|It then copies your data asynchronously to the secondary region.',
         'learn-storage|On Azure, you control how data is replicated by using locally redundant storage (LRS) or zone-redundant storage (ZRS).',
         'learn-storage|AWS customers often replicate their S3 buckets to another region by using cross-region replication.',
         's3-replication|The destination buckets can be in different AWS Regions or within the same Region as the source bucket.'],
        { allow: ['two'] }),
    },
  ],
};

export default notes;
