import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'island-charts',
  overview: [
    b('Resilient designs start from AWS geography: {{term:availability-zone|Availability Zones}} are physically separated locations inside a {{term:region}}, so spreading a workload across them avoids correlated failures; spreading across Regions protects against a whole-Region problem and is also part of disaster recovery. Amazon Route 53 is the DNS service that steers users to healthy, nearby endpoints, and route tables decide where traffic goes inside the network.',
      ['waf-multi-location', 'route53-what-is', 'vpc-route-tables'],
      ['waf-multi-location|Availability Zones are resource hosting locations that are physically separated from each other to avoid correlated failures due to risks such as fires, floods, and tornadoes.',
       'waf-multi-location|Distribute workload data and resources across multiple Availability Zones or, where necessary, across AWS Regions.',
       'route53-what-is|Amazon Route 53 is a highly available and scalable Domain Name System (DNS) web service.',
       'vpc-route-tables|Each route table contains a set of rules, called routes, that determine where network traffic from your subnet or gateway is directed.']),
  ],
  bullets: [
    {
      id: '2.2-K1',
      concepts: [
        b('Production workloads should be distributed among multiple Availability Zones or Regions to achieve fault tolerance and high availability. All compute associated with your workload should be distributed among multiple Availability Zones, and you can replicate data synchronously between Availability Zones for most workloads without significantly impacting user experience.',
          'waf-multi-location',
          ['Desired outcome: Production workloads are distributed among multiple Availability Zones (AZs) or Regions to achieve fault tolerance and high availability.',
           'All compute associated with your workload should be distributed among multiple Availability Zones.',
           'You can replicate data synchronously between Availability Zones for most workloads without significantly impacting user experience.']),
        b('Whether to stay in one Region (multi-AZ) or go multi-Region is a requirements decision: evaluate whether resilience needs can be met by a multi-AZ approach or require a multi-Region approach, and consider multiple Regions as part of the disaster recovery strategy even if you do not run active in more than one.',
          'waf-multi-location',
          ['Work with business and technical stakeholders to evaluate your workload, and determine whether its resilience needs can be met by a multi-AZ approach (single AWS Region) or if they require a multi-Region approach (if multiple Regions are permitted).',
           'Even if you choose not to operate in multiple Regions for high availability, consider multiple Regions as part of your disaster recovery (DR) strategy.']),
        b('Amazon Route 53 is a highly available and scalable DNS web service that can perform three main functions in any combination: domain registration, DNS routing and health checking.',
          'route53-what-is',
          ['Amazon Route 53 is a highly available and scalable Domain Name System (DNS) web service.',
           'You can use Route 53 to perform three main functions in any combination: domain registration, DNS routing, and health checking.']),
        b('When you create a record you choose a routing policy, which determines how Route 53 responds to queries: simple (a single resource), failover (active-passive), geolocation (by user location), geoproximity (by resource location, with optional shifting), latency (to the Region with the best latency), IP-based, multivalue answer (up to eight healthy records chosen at random) and weighted (in proportions you specify).',
          'route53-routing',
          ['When you create a record, you choose a routing policy, which determines how Amazon Route 53 responds to queries: Simple routing policy – Use for a single resource that performs a given function for your domain, for example, a web server that serves content for the example.com website.',
           'Failover routing policy – Use when you want to configure active-passive failover.',
           'Geolocation routing policy – Use when you want to route traffic based on the location of your users.',
           'Geoproximity routing policy – Use when you want to route traffic based on the location of your resources and, optionally, shift traffic from resources in one location to resources in another location.',
           'Latency routing policy – Use when you have resources in multiple AWS Regions and you want to route traffic to the Region that provides the best latency.',
           'Multivalue answer routing policy – Use when you want Route 53 to respond to DNS queries with up to eight healthy records selected at random.',
           'Weighted routing policy – Use to route traffic to multiple resources in proportions that you specify.'],
          { allow: ['eight'] }),
        b('Route 53 health checks monitor the health and performance of web applications, web servers and other resources, and enable failover. Active-passive failover uses the failover routing policy; active-active failover uses any other routing policy (or a combination) so that all resources are available most of the time unless Route 53 considers them unhealthy.',
          ['route53-failover', 'route53-failover-types'],
          ['route53-failover|Amazon Route 53 health checks monitor the health and performance of your web applications, web servers, and other resources.',
           'route53-failover-types|You configure active-active failover using any routing policy (or combination of routing policies) other than failover, and you configure active-passive failover using the failover routing policy.',
           'route53-failover-types|In active-active failover, all the records that have the same name, the same type (such as A or AAAA), and the same routing policy (such as weighted or latency) are active unless Route 53 considers them unhealthy.']),
      ],
      services: ['Amazon Route 53', 'Elastic Load Balancing (ELB)'],
      design: [
        b('Choose the routing policy from the requirement: best performance for users across Regions → latency; legal or content localisation by user location → geolocation; primary and standby → failover; gradual rollout or A/B split → weighted.',
          'route53-routing',
          ['Latency routing policy – Use when you have resources in multiple AWS Regions and you want to route traffic to the Region that provides the best latency.',
           'Weighted routing policy – Use to route traffic to multiple resources in proportions that you specify.']),
      ],
    },
    {
      id: '2.2-K3',
      concepts: [
        b('Each route table contains a set of rules, called routes, that determine where network traffic from your subnet or gateway is directed. A route specifies a destination (a CIDR block or prefix list) and a target such as an internet gateway, NAT gateway, VPC peering connection or VPN connection; traffic is routed based on its destination IP address.',
          'vpc-route-tables',
          ['Each route table contains a set of rules, called routes, that determine where network traffic from your subnet or gateway is directed.',
           'Each route specifies a destination (CIDR block or prefix list) and a target (such as an internet gateway, NAT gateway, VPC peering connection, or VPN connection).',
           'Traffic is routed to targets based on its destination IP address.']),
        b('When you create a VPC, a main route table is created for it. When more than one route matches, AWS directs traffic using the most specific route that matches the traffic.',
          ['vpc-route-tables', 'vpc-route-priority'],
          ['vpc-route-tables|When you create a VPC, we also create the main route table for the VPC.',
           'vpc-route-priority|In general, we direct traffic using the most specific route that matches the traffic.']),
        b('A public subnet is one with a direct route to an internet gateway. Resources in a public subnet can reach the public internet. Route tables are what make a subnet public, private, VPN-only or isolated.',
          ['vpc-subnets', 'vpc-route-tables'],
          ['vpc-subnets|Public subnet – The subnet has a direct route to an internet gateway.',
           'vpc-subnets|Resources in a public subnet can access the public internet.',
           'vpc-route-tables|Route tables enable you to create complex networking architectures that include public subnets, private subnets, VPN-only subnets, and isolated subnets.']),
      ],
      services: ['Amazon VPC'],
      design: [
        b('When a question says an instance in a subnet cannot reach the internet, check the route table first: does the subnet\'s route table have a route to an internet gateway (public) or to a NAT gateway (private subnet outbound)? Routing is only half of the answer: security groups and network ACLs also filter the traffic (see Gatehouse).',
          'vpc-route-tables',
          ['Each route specifies a destination (CIDR block or prefix list) and a target (such as an internet gateway, NAT gateway, VPC peering connection, or VPN connection).']),
      ],
    },
    {
      id: '2.2-S2',
      concepts: [
        b('Within one Region, a highly available design spreads instances across Availability Zones: an Auto Scaling group can span multiple Availability Zones and balances instances evenly across them as it scales, and a load balancer distributes traffic to healthy targets in one or more Availability Zones.',
          ['asg-what-is', 'elb-what-is'],
          ['asg-what-is|You can specify multiple Availability Zones for your Auto Scaling group, and Amazon EC2 Auto Scaling balances your instances evenly across the Availability Zones as the group scales.',
           'elb-what-is|Elastic Load Balancing automatically distributes your incoming traffic across multiple targets, such as EC2 instances, containers, and IP addresses, in one or more Availability Zones.']),
        b('Across Regions, Route 53 provides the routing: health checks and DNS failover or latency routing send users to a healthy Region. To ease multi-Region deployments and keep consistency, AWS CloudFormation StackSets can replicate infrastructure across multiple Regions.',
          ['route53-failover-types', 'waf-multi-location'],
          ['route53-failover-types|You can use Route 53 health checking to configure active-active and active-passive failover configurations.',
           'waf-multi-location|To ease multi-Regional deployments and maintain consistency, AWS CloudFormation StackSets can replicate your entire AWS infrastructure across multiple Regions.']),
        b('Fault isolation: common points of failure such as generators and cooling equipment are not shared across Availability Zones, so a design that keeps a copy of each tier in more than one AZ survives the loss of one.',
          'fault-isolation-az',
          ['Common points of failure, like generators and cooling equipment, are not shared across Availability Zones and are designed to be supplied by different power substations.']),
      ],
      services: ['Amazon Route 53', 'Amazon VPC', 'Elastic Load Balancing (ELB)'],
      design: [
        b('Pattern: a load balancer and an Auto Scaling group across multiple Availability Zones within a Region for high availability; Route 53 health checks with failover or latency routing in front of a second Region when the requirement is Region-level fault tolerance or global latency.',
          ['waf-multi-location', 'route53-routing'],
          ['waf-multi-location|Distribute workload data and resources across multiple Availability Zones or, where necessary, across AWS Regions.',
           'route53-routing|Latency routing policy – Use when you have resources in multiple AWS Regions and you want to route traffic to the Region that provides the best latency.']),
      ],
    },
  ],
  cues: [
    cue('survive the failure of one data centre / Availability Zone', 'Deploy across multiple Availability Zones (load balancer + Auto Scaling group)',
      b('Production workloads should be distributed among multiple Availability Zones to achieve fault tolerance and high availability.', 'waf-multi-location',
        ['Desired outcome: Production workloads are distributed among multiple Availability Zones (AZs) or Regions to achieve fault tolerance and high availability.'])),
    cue('route users to the Region with the lowest latency', 'Route 53 latency routing',
      b('Latency routing sends traffic to the Region that provides the best latency.', 'route53-routing',
        ['Latency routing policy – Use when you have resources in multiple AWS Regions and you want to route traffic to the Region that provides the best latency.'])),
    cue('primary site with a standby that takes over on failure', 'Route 53 failover routing (active-passive) with health checks',
      b('Failover routing is for active-passive failover.', 'route53-routing',
        ['Failover routing policy – Use when you want to configure active-passive failover.'])),
    cue('route by the user\'s country or location', 'Route 53 geolocation routing',
      b('Geolocation routing is based on the location of your users.', 'route53-routing',
        ['Geolocation routing policy – Use when you want to route traffic based on the location of your users.'])),
    cue('send a percentage of traffic to a new version', 'Route 53 weighted routing',
      b('Weighted routing sends traffic to multiple resources in proportions that you specify.', 'route53-routing',
        ['Weighted routing policy – Use to route traffic to multiple resources in proportions that you specify.'])),
    cue('subnet has a route to an internet gateway', 'Public subnet',
      b('A public subnet has a direct route to an internet gateway.', 'vpc-subnets',
        ['Public subnet – The subnet has a direct route to an internet gateway.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure DNS and Azure Traffic Manager',
      aws: 'Amazon Route 53',
      mapping: b('Learn explains that in AWS, Route 53 provides both DNS name management and DNS-level traffic routing and failover, while Azure splits these across two services: Azure DNS for domain and DNS management and Traffic Manager for DNS-level traffic routing, load balancing and failover.',
        ['learn-networking', 'route53-what-is'],
        ['learn-networking|Route 53, Azure DNS, and Azure Traffic Manager In AWS, Route 53 provides both DNS name management and DNS-level traffic routing and failover services.',
         'learn-networking|Traffic Manager provides DNS-level traffic routing, load balancing, and failover capabilities.',
         'route53-what-is|You can use Route 53 to perform three main functions in any combination: domain registration, DNS routing, and health checking.'],
        { allow: ['two'] }),
      breaks: b('On AWS one service covers both, and you choose a routing policy per record (simple, failover, geolocation, geoproximity, latency, IP-based, multivalue, weighted). The exam asks which routing policy matches a requirement, so learn them as Route 53 vocabulary rather than as separate services.',
        ['route53-routing', 'learn-networking'],
        ['route53-routing|When you create a record, you choose a routing policy, which determines how Amazon Route 53 responds to queries:',
         'learn-networking|Route 53, Azure DNS, and Azure Traffic Manager In AWS, Route 53 provides both DNS name management and DNS-level traffic routing and failover services.']),
    },
  ],
};

export default notes;
