import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'island-charts',
  overview: [
    b('Resilient designs start from AWS geography: {{term:availability-zone|Availability Zones}} are physically separated locations inside a {{term:region}}, so spreading a workload across them avoids correlated failures; spreading across Regions protects against a whole-Region problem and is also part of disaster recovery. Amazon Route 53 is the DNS service whose routing policies and health checks steer users to endpoints, and route tables decide where traffic goes inside the network.',
      ['waf-multi-location', 'route53-what-is', 'vpc-route-tables'],
      ['waf-multi-location|Availability Zones are resource hosting locations that are physically separated from each other to avoid correlated failures due to risks such as fires, floods, and tornadoes.',
       'waf-multi-location|Distribute workload data and resources across multiple Availability Zones or, where necessary, across AWS Regions.',
       'route53-what-is|Amazon Route 53 is a highly available and scalable Domain Name System (DNS) web service.',
       'vpc-route-tables|Each route table contains a set of rules, called routes, that determine where network traffic from your subnet or gateway is directed.']),
  ],
  bullets: [
    {
      id: '2.2-K1',
      concepts: [
        b('Production workloads should be distributed among multiple Availability Zones or Regions to achieve fault tolerance and high availability. All compute associated with your workload should be distributed among multiple Availability Zones, and you can replicate data synchronously between Availability Zones for most workloads without significantly impacting user experience.',
          'waf-multi-location',
          ['Desired outcome: Production workloads are distributed among multiple Availability Zones (AZs) or Regions to achieve fault tolerance and high availability.',
           'All compute associated with your workload should be distributed among multiple Availability Zones.',
           'You can replicate data synchronously between Availability Zones for most workloads without significantly impacting user experience.']),
        b('Whether to stay in one Region (multi-AZ) or go multi-Region is a requirements decision: evaluate whether resilience needs can be met by a multi-AZ approach or require a multi-Region approach, and consider multiple Regions as part of the disaster recovery strategy even if you do not run active in more than one.',
          'waf-multi-location',
          ['Work with business and technical stakeholders to evaluate your workload, and determine whether its resilience needs can be met by a multi-AZ approach (single AWS Region) or if they require a multi-Region approach (if multiple Regions are permitted).',
           'Even if you choose not to operate in multiple Regions for high availability, consider multiple Regions as part of your disaster recovery (DR) strategy.']),
        b('Amazon Route 53 is a highly available and scalable DNS web service that can perform three main functions in any combination: domain registration, DNS routing and health checking.',
          'route53-what-is',
          ['Amazon Route 53 is a highly available and scalable Domain Name System (DNS) web service.',
           'You can use Route 53 to perform three main functions in any combination: domain registration, DNS routing, and health checking.']),
        b('When you create a record you choose a routing policy, which determines how Route 53 responds to queries: simple (a single resource), failover (active-passive), geolocation (by user location), geoproximity (by resource location, with optional shifting), latency (to the Region with the best latency), IP-based, multivalue answer (up to eight healthy records chosen at random) and weighted (in proportions you specify).',
          'route53-routing',
          ['When you create a record, you choose a routing policy, which determines how Amazon Route 53 responds to queries: Simple routing policy – Use for a single resource that performs a given function for your domain, for example, a web server that serves content for the example.com website.',
           'Failover routing policy – Use when you want to configure active-passive failover.',
           'Geolocation routing policy – Use when you want to route traffic based on the location of your users.',
           'Geoproximity routing policy – Use when you want to route traffic based on the location of your resources and, optionally, shift traffic from resources in one location to resources in another location.',
           'Latency routing policy – Use when you have resources in multiple AWS Regions and you want to route traffic to the Region that provides the best latency.',
           'Multivalue answer routing policy – Use when you want Route 53 to respond to DNS queries with up to eight healthy records selected at random.',
           'Weighted routing policy – Use to route traffic to multiple resources in proportions that you specify.'],
          { allow: ['eight'] }),
        b('Geolocation records need a fallback. You can create a default record that handles both queries from unmapped IP addresses and queries from locations where you have not created geolocation records; without one, Route 53 returns a "no answer" response for queries from those locations.',
          'route53-geo',
          ['You can create a default record that handles both queries from unmapped IP addresses and queries from locations where you haven\'t created geolocation records.',
           'If you don\'t create a default record, Route 53 returns a "no answer" response for queries from those locations.']),
        b('Alias records are a Route 53-specific extension to DNS that route traffic to selected AWS resources, such as CloudFront distributions and S3 buckets. Unlike a CNAME record, you can create an alias record at the zone apex (the top node of a DNS namespace): you cannot create a CNAME record for example.com, but you can create an alias record for example.com.',
          'route53-alias',
          ['Amazon Route 53 alias records provide a Route 53–specific extension to DNS.',
           'Alias records let you route traffic to selected AWS resources, such as CloudFront distributions and Amazon S3 buckets.',
           'Unlike a CNAME record, you can create an alias record at the top node of a DNS namespace, also known as the zone apex.',
           'You can\'t create a CNAME record for example.com, but you can create an alias record for example.com that routes traffic to www.example.com']),
        b('Route 53 health checks monitor the health and performance of web applications, web servers and other resources, and enable failover. Active-passive failover uses the failover routing policy; active-active failover uses any other routing policy (or a combination) so that all resources are available most of the time unless Route 53 considers them unhealthy.',
          ['route53-failover', 'route53-failover-types'],
          ['route53-failover|Amazon Route 53 health checks monitor the health and performance of your web applications, web servers, and other resources.',
           'route53-failover-types|You configure active-active failover using any routing policy (or combination of routing policies) other than failover, and you configure active-passive failover using the failover routing policy.',
           'route53-failover-types|In active-active failover, all the records that have the same name, the same type (such as A or AAAA), and the same routing policy (such as weighted or latency) are active unless Route 53 considers them unhealthy.']),
      ],
      services: ['Amazon Route 53', 'Elastic Load Balancing (ELB)'],
      design: [
        b('Choose the routing policy from the requirement: the Region with the best latency → latency; the location of your users → geolocation; the location of your resources, with optional shifting → geoproximity; primary and standby → failover; proportions that you specify → weighted; and for a name at the zone apex that points at an AWS resource, use an alias record, which routes traffic to selected AWS resources and is chosen separately from the routing policy.',
          ['route53-routing', 'route53-alias'],
          ['route53-routing|Latency routing policy – Use when you have resources in multiple AWS Regions and you want to route traffic to the Region that provides the best latency.',
           'route53-routing|Geolocation routing policy – Use when you want to route traffic based on the location of your users.',
           'route53-routing|Geoproximity routing policy – Use when you want to route traffic based on the location of your resources and, optionally, shift traffic from resources in one location to resources in another location.',
           'route53-routing|Failover routing policy – Use when you want to configure active-passive failover.',
           'route53-routing|Weighted routing policy – Use to route traffic to multiple resources in proportions that you specify.',
           'route53-alias|Unlike a CNAME record, you can create an alias record at the top node of a DNS namespace, also known as the zone apex.',
           'route53-alias|Alias records let you route traffic to selected AWS resources, such as CloudFront distributions and Amazon S3 buckets.']),
      ],
    },
    {
      id: '2.2-K3',
      concepts: [
        b('Each route table contains a set of rules, called routes, that determine where network traffic from your subnet or gateway is directed. A route specifies a destination (a CIDR block or prefix list) and a target such as an internet gateway, NAT gateway, VPC peering connection or VPN connection; traffic is routed based on its destination IP address.',
          'vpc-route-tables',
          ['Each route table contains a set of rules, called routes, that determine where network traffic from your subnet or gateway is directed.',
           'Each route specifies a destination (CIDR block or prefix list) and a target (such as an internet gateway, NAT gateway, VPC peering connection, or VPN connection).',
           'Traffic is routed to targets based on its destination IP address.']),
        b('When you create a VPC, a main route table is created for it. When more than one route matches, AWS directs traffic using the most specific route that matches the traffic.',
          ['vpc-route-tables', 'vpc-route-priority'],
          ['vpc-route-tables|When you create a VPC, we also create the main route table for the VPC.',
           'vpc-route-priority|In general, we direct traffic using the most specific route that matches the traffic.']),
        b('A public subnet is one with a direct route to an internet gateway. Resources in a public subnet can reach the public internet. Route tables are what make a subnet public, private, VPN-only or isolated.',
          ['vpc-subnets', 'vpc-route-tables'],
          ['vpc-subnets|Public subnet – The subnet has a direct route to an internet gateway.',
           'vpc-subnets|Resources in a public subnet can access the public internet.',
           'vpc-route-tables|Route tables enable you to create complex networking architectures that include public subnets, private subnets, VPN-only subnets, and isolated subnets.']),
      ],
      services: ['Amazon VPC'],
      design: [
        b('When an instance in a subnet cannot reach the internet, check the route table: does the subnet\'s route table have a route to an internet gateway (public subnet), or to a NAT gateway for outbound access from a private subnet? Routing is only part of it. An instance in a public subnet also needs a public IP address or Elastic IP address, a public NAT gateway sits in a public subnet and needs an Elastic IP address, and security groups and network ACLs also filter the traffic (see Gatehouse).',
          ['vpc-route-tables', 'vpc-igw', 'vpc-nat-gateway'],
          ['vpc-route-tables|Each route specifies a destination (CIDR block or prefix list) and a target (such as an internet gateway, NAT gateway, VPC peering connection, or VPN connection).',
           'vpc-igw|The instances in the public subnet must have public IP addresses or Elastic IP addresses to enable communication with the internet over the internet gateway.',
           'vpc-nat-gateway|You create a public NAT gateway in a public subnet and must associate an Elastic IP address with the NAT gateway at creation.',
           'vpc-nat-gateway|You can use a NAT gateway so that instances in a private subnet can connect to services outside your VPC but external services can\'t initiate a connection with those instances.']),
      ],
    },
    {
      id: '2.2-S2',
      concepts: [
        b('Within one Region, a highly available design spreads instances across Availability Zones: an Auto Scaling group can span multiple Availability Zones and balances instances evenly across them as it scales, and a load balancer distributes traffic to healthy targets in one or more Availability Zones.',
          ['asg-what-is', 'elb-what-is'],
          ['asg-what-is|You can specify multiple Availability Zones for your Auto Scaling group, and Amazon EC2 Auto Scaling balances your instances evenly across the Availability Zones as the group scales.',
           'elb-what-is|Elastic Load Balancing automatically distributes your incoming traffic across multiple targets, such as EC2 instances, containers, and IP addresses, in one or more Availability Zones.']),
        b('Across Regions, Route 53 provides the routing: health checks and DNS failover or latency routing send users to a healthy Region. To ease multi-Region deployments and keep consistency, AWS CloudFormation StackSets can replicate infrastructure across multiple Regions.',
          ['route53-failover-types', 'waf-multi-location'],
          ['route53-failover-types|You can use Route 53 health checking to configure active-active and active-passive failover configurations.',
           'waf-multi-location|To ease multi-Regional deployments and maintain consistency, AWS CloudFormation StackSets can replicate your entire AWS infrastructure across multiple Regions.']),
        b('Fault isolation: common points of failure such as generators and cooling equipment are not shared across Availability Zones, so a design that keeps a copy of each tier in more than one AZ survives the loss of one.',
          'fault-isolation-az',
          ['Common points of failure, like generators and cooling equipment, are not shared across Availability Zones and are designed to be supplied by different power substations.']),
      ],
      services: ['Amazon Route 53', 'Amazon VPC', 'Elastic Load Balancing (ELB)'],
      design: [
        b('Pattern: a load balancer and an Auto Scaling group across multiple Availability Zones within a Region for high availability; Route 53 health checks with failover or latency routing in front of a second Region when the requirement is Region-level fault tolerance or global latency.',
          ['waf-multi-location', 'route53-routing'],
          ['waf-multi-location|Distribute workload data and resources across multiple Availability Zones or, where necessary, across AWS Regions.',
           'route53-routing|Latency routing policy – Use when you have resources in multiple AWS Regions and you want to route traffic to the Region that provides the best latency.']),
      ],
    },
  ],
  cues: [
    cue('survive the failure of one data centre / Availability Zone', 'Deploy across multiple Availability Zones (load balancer + Auto Scaling group)',
      b('Production workloads should be distributed among multiple Availability Zones to achieve fault tolerance and high availability.', 'waf-multi-location',
        ['Desired outcome: Production workloads are distributed among multiple Availability Zones (AZs) or Regions to achieve fault tolerance and high availability.'])),
    cue('route users to the Region with the lowest latency', 'Route 53 latency routing',
      b('Latency routing sends traffic to the Region that provides the best latency.', 'route53-routing',
        ['Latency routing policy – Use when you have resources in multiple AWS Regions and you want to route traffic to the Region that provides the best latency.'])),
    cue('primary site with a standby that takes over on failure', 'Route 53 failover routing (active-passive) with health checks',
      b('Failover routing is for active-passive failover.', 'route53-routing',
        ['Failover routing policy – Use when you want to configure active-passive failover.'])),
    cue('route by the user\'s country or location', 'Route 53 geolocation routing (with a default record for unmapped locations)',
      b('Geolocation routing is based on the location of your users; a default record handles queries from locations without a geolocation record.', ['route53-routing', 'route53-geo'],
        ['route53-routing|Geolocation routing policy – Use when you want to route traffic based on the location of your users.',
         'route53-geo|If you don\'t create a default record, Route 53 returns a "no answer" response for queries from those locations.'])),
    cue('apex / root domain name (example.com) must point at an AWS resource such as CloudFront', 'Route 53 alias record (a CNAME cannot be used at the zone apex)',
      b('You can create an alias record at the zone apex; you cannot create a CNAME record there.', 'route53-alias',
        ['You can\'t create a CNAME record for example.com, but you can create an alias record for example.com that routes traffic to www.example.com'])),
    cue('send specified proportions of traffic to different resources', 'Route 53 weighted routing',
      b('Weighted routing sends traffic to multiple resources in proportions that you specify.', 'route53-routing',
        ['Weighted routing policy – Use to route traffic to multiple resources in proportions that you specify.'])),
    cue('subnet has a route to an internet gateway', 'Public subnet',
      b('A public subnet has a direct route to an internet gateway.', 'vpc-subnets',
        ['Public subnet – The subnet has a direct route to an internet gateway.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure DNS and Azure Traffic Manager',
      aws: 'Amazon Route 53',
      mapping: b('Learn explains that in AWS, Route 53 provides both DNS name management and DNS-level traffic routing and failover, while Azure splits these across two services: Azure DNS for domain and DNS management and Traffic Manager for DNS-level traffic routing, load balancing and failover.',
        ['learn-networking', 'route53-what-is'],
        ['learn-networking|Route 53, Azure DNS, and Azure Traffic Manager In AWS, Route 53 provides both DNS name management and DNS-level traffic routing and failover services.',
         'learn-networking|Traffic Manager provides DNS-level traffic routing, load balancing, and failover capabilities.',
         'route53-what-is|You can use Route 53 to perform three main functions in any combination: domain registration, DNS routing, and health checking.'],
        { allow: ['two'] }),
      breaks: b('On AWS one service covers both, and you choose a routing policy per record (simple, failover, geolocation, geoproximity, latency, IP-based, multivalue, weighted). On the Azure side, Microsoft Learn lists the DNS-level routing, load balancing and failover under the separate Traffic Manager service.',
        ['route53-routing', 'learn-networking'],
        ['route53-routing|When you create a record, you choose a routing policy, which determines how Amazon Route 53 responds to queries:',
         'learn-networking|Route 53, Azure DNS, and Azure Traffic Manager In AWS, Route 53 provides both DNS name management and DNS-level traffic routing and failover services.',
         'learn-networking|Traffic Manager provides DNS-level traffic routing, load balancing, and failover capabilities.']),
    },
  ],
};

export default notes;
