import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'legacy-wharf',
  overview: [
    b('Some applications cannot be changed: they keep state on the server, assume one database and were never built for the cloud. This building covers pre-built AI services and infrastructure-level reliability. Pre-built AWS AI services such as Amazon Comprehend and Amazon Polly give an application a capability through an API, so you do not have to build the model yourself. And several AWS features raise the reliability of an unchanged application by working around it, such as load balancing with sticky sessions, automatic instance recovery, Multi-AZ databases and DNS failover.',
      ['comprehend-what-is', 'polly-what-is', 'alb-target-attrs', 'ec2-recover'],
      ['comprehend-what-is|Amazon Comprehend uses natural language processing (NLP) to extract insights about the content of documents.',
       'polly-what-is|Amazon Polly is a cloud service that converts text into lifelike speech.',
       'alb-target-attrs|This feature is useful for servers that maintain state information in order to provide a continuous experience to clients.',
       'ec2-recover|These recovery mechanisms are designed to restore instance availability when AWS detects an underlying hardware or software issue that causes a system status check to fail.']),
  ],
  bullets: [
    {
      id: '2.2-K2',
      concepts: [
        b('Amazon Comprehend uses natural language processing (NLP) to extract insights about the content of documents. You can use the pre-trained models it provides or train custom models for classification and entity recognition, and access it through the console or APIs.',
          'comprehend-what-is',
          ['Amazon Comprehend uses natural language processing (NLP) to extract insights about the content of documents.',
           'You can use the pre-trained models that Amazon Comprehend provides, or you can train your own custom models for classification and entity recognition.',
           'You can access Amazon Comprehend document analysis capabilities using the Amazon Comprehend console or using the Amazon Comprehend APIs.']),
        b('Amazon Polly is a cloud service that converts text into lifelike speech. It supports multiple languages and includes a variety of lifelike voices, and can be used to develop applications that increase engagement and accessibility.',
          'polly-what-is',
          ['Amazon Polly is a cloud service that converts text into lifelike speech.',
           'Amazon Polly supports multiple languages and includes a variety of lifelike voices.',
           'You can use Amazon Polly to develop applications that increase engagement and accessibility.']),
        b('{{rename:sagemaker-ai}} is the managed service for building, training and deploying your own machine learning models, in contrast to calling a pre-trained service like Comprehend or Polly.',
          'sagemaker-what-is',
          ['Amazon SageMaker AI is a fully managed machine learning (ML) service.']),
        b('Other pre-built AI services cover other inputs. Amazon Rekognition analyses images and video. Amazon Textract detects text, forms and tables in documents. Amazon Transcribe converts audio to text. Amazon Translate translates text. Amazon Lex builds conversational interfaces using voice and text.',
          ['rekognition-what-is', 'textract-what-is', 'transcribe-what-is', 'translate-what-is', 'lex-what-is'],
          ['rekognition-what-is|Amazon Rekognition is a cloud-based image and video analysis service that makes it easy to add advanced computer vision capabilities to your applications.',
           'textract-what-is|Amazon Textract helps you add document text detection and analysis to your applications.',
           'textract-what-is|Extract text, forms, and tables from documents with structured data, using the Amazon Textract Document Analysis API.',
           'transcribe-what-is|Amazon Transcribe is an automatic speech recognition service that uses machine learning models to convert audio to text.',
           'translate-what-is|Amazon Translate is a text translation service that uses advanced machine learning technologies to provide high-quality translation on demand.',
           'lex-what-is|Amazon Lex V2 is an AWS service for building conversational interfaces for applications using voice and text.']),
      ],
      services: ['Amazon Comprehend', 'Amazon Polly', 'Amazon Rekognition', 'Amazon Textract', 'Amazon Transcribe', 'Amazon Translate', 'Amazon Lex'],
      design: [
        b('Match the task to the managed AI service: extract entities, sentiment or key phrases from text → Comprehend; read text aloud → Polly; analyse images or video → Rekognition; pull text, forms and tables out of documents → Textract; speech to text → Transcribe; translate text → Translate; chatbot → Lex. Calling a service like these avoids building and hosting a model yourself.',
          ['comprehend-what-is', 'polly-what-is', 'rekognition-what-is', 'textract-what-is', 'transcribe-what-is', 'translate-what-is', 'lex-what-is'],
          ['comprehend-what-is|For example, using Amazon Comprehend you can search social networking feeds for mentions of products or scan an entire document repository for key phrases.',
           'polly-what-is|Amazon Polly is a cloud service that converts text into lifelike speech.',
           'rekognition-what-is|Amazon Rekognition is a cloud-based image and video analysis service that makes it easy to add advanced computer vision capabilities to your applications.',
           'textract-what-is|Extract text, forms, and tables from documents with structured data, using the Amazon Textract Document Analysis API.',
           'transcribe-what-is|Amazon Transcribe is an automatic speech recognition service that uses machine learning models to convert audio to text.',
           'translate-what-is|Amazon Translate is a text translation service that uses advanced machine learning technologies to provide high-quality translation on demand.',
           'lex-what-is|Amazon Lex V2 is an AWS service for building conversational interfaces for applications using voice and text.']),
      ],
    },
    {
      id: '2.2-S7',
      concepts: [
        b('{{term:sticky-sessions|Sticky sessions}} let an Application Load Balancer bind a user\'s {{term:session}} to a specific target so all requests in the session go to the same target. AWS says this is useful for servers that maintain state information. It needs client cookie support, and is enabled at the target group level. Prefer externalising state (see Blueprint Hall), but sticky sessions help when the application cannot be changed.',
          'alb-target-attrs',
          ['you can use the sticky session feature (also known as session affinity) to enable the load balancer to bind a user\'s session to a specific target.',
           'This feature is useful for servers that maintain state information in order to provide a continuous experience to clients.',
           'To use sticky sessions, the client must support cookies.',
           'Sticky sessions are enabled at the target group level.']),
        b('Automatic instance recovery restores availability when AWS detects an underlying hardware or software issue that fails a system status check, by moving the instance to a different host. The instance keeps its instance ID, IP addresses (including Elastic IP), instance metadata, attached EBS volumes and Availability Zone, but data in memory (and in instance store volumes for CloudWatch action based recovery) is lost.',
          'ec2-recover',
          ['These recovery mechanisms are designed to restore instance availability when AWS detects an underlying hardware or software issue that causes a system status check to fail.',
           'During the instance recovery process, AWS will attempt to move your instance from the host with the underlying hardware or software issue to a different host.',
           'Preserved elements: Instance ID Public, private, and Elastic IP addresses Instance metadata Placement group Attached EBS volumes Availability Zone Lost elements: Data stored in volatile memory (RAM) Data stored on instance store volumes (applicable to CloudWatch action based recovery only) Operating system uptime resets to zero']),
        b('A Multi-AZ RDS deployment gives a database high availability without application changes: RDS automatically provisions and maintains a synchronous standby replica in a different Availability Zone to provide data redundancy and failover support.',
          'rds-multi-az-instance',
          ['In a Multi-AZ DB instance deployment, Amazon RDS automatically provisions and maintains a synchronous standby replica in a different Availability Zone.',
           'Amazon RDS provides high availability and failover support for DB instances using Multi-AZ deployments with a single standby DB instance.']),
        b('A load balancer plus an Auto Scaling group replaces failed instances and spreads traffic, and Route 53 health checks with failover routing can switch DNS to a standby when the primary fails; both work in front of an application without code changes.',
          ['asg-what-is', 'route53-failover-types'],
          ['asg-what-is|Amazon EC2 Auto Scaling automatically monitors the health and availability of your instances using EC2 health checks and replaces terminated or impaired instances to maintain your desired capacity.',
           'route53-failover-types|You configure active-active failover using any routing policy (or combination of routing policies) other than failover, and you configure active-passive failover using the failover routing policy.']),
      ],
      services: ['Elastic Load Balancing (ELB)', 'Amazon Route 53', 'Amazon RDS'],
      design: [
        b('When a scenario says the application cannot be changed, infrastructure-level options fit that constraint: Multi-AZ for the database, a load balancer (with sticky sessions if the app keeps session state), Auto Scaling or automatic instance recovery for the servers, and Route 53 failover for the site. An option that requires rewriting the application does not meet that constraint. When changes are allowed, externalising state is the stronger long-term fix (see Blueprint Hall).',
          ['alb-target-attrs', 'rds-multi-az-instance', 'asg-what-is', 'ec2-recover', 'route53-failover-types'],
          ['alb-target-attrs|This ensures that all requests from the user during the session are sent to the same target.',
           'rds-multi-az-instance|In a Multi-AZ DB instance deployment, Amazon RDS automatically provisions and maintains a synchronous standby replica in a different Availability Zone.',
           'asg-what-is|Amazon EC2 Auto Scaling automatically monitors the health and availability of your instances using EC2 health checks and replaces terminated or impaired instances to maintain your desired capacity.',
           'ec2-recover|These recovery mechanisms are designed to restore instance availability when AWS detects an underlying hardware or software issue that causes a system status check to fail.',
           'route53-failover-types|Use an active-passive failover configuration when you want a primary resource or group of resources to be available the majority of the time and you want a secondary resource or group of resources to be on standby in case all the primary resources become unavailable.']),
      ],
    },
    {
      id: '2.2-S8',
      concepts: [
        b('Use purpose-built services for the workload instead of generic infrastructure: AWS describes a growing set of database models and services, each built for a data shape, and managed AI services built for tasks like text analysis and speech. See Purpose-Built Workshop for the database matching.',
          'database-decision',
          ['AWS offers a growing number of database options (15+) with diverse data models to support a variety of workloads.',
           'This might involve migrating your applications to use purpose-built cloud databases.']),
        b('Examples from this building: text understanding → Comprehend; speech output → Polly; a managed relational database that needs to survive an AZ failure → RDS Multi-AZ.',
          ['comprehend-what-is', 'polly-what-is', 'rds-multi-az-instance'],
          ['comprehend-what-is|You can use the pre-trained models that Amazon Comprehend provides, or you can train your own custom models for classification and entity recognition.',
           'polly-what-is|Amazon Polly supports multiple languages and includes a variety of lifelike voices.',
           'rds-multi-az-instance|Amazon RDS provides high availability and failover support for DB instances using Multi-AZ deployments with a single standby DB instance.']),
      ],
      services: ['Amazon Comprehend', 'Amazon Polly', 'Amazon RDS'],
      design: [
        b('Rule of thumb for scenario questions: when a purpose-built AWS service exists for the task, such as a purpose-built NoSQL database like Amazon DynamoDB, consider it for the design.',
          'database-decision',
          ['For example, you could use Amazon Aurora or purpose-built NoSQL databases such as Amazon DynamoDB, Amazon Neptune, or Amazon DocumentDB (with MongoDB compatibility).']),
      ],
    },
  ],
  cues: [
    cue('extract sentiment, entities or key phrases from text without building a model', 'Amazon Comprehend',
      b('Comprehend uses NLP to extract insights from documents with pre-trained models.', 'comprehend-what-is',
        ['Amazon Comprehend uses natural language processing (NLP) to extract insights about the content of documents.'])),
    cue('convert text to spoken audio', 'Amazon Polly',
      b('Polly converts text into lifelike speech.', 'polly-what-is',
        ['Amazon Polly is a cloud service that converts text into lifelike speech.'])),
    cue('analyse images or video / detect objects or faces', 'Amazon Rekognition',
      b('Rekognition is an image and video analysis service for adding computer vision to applications.', 'rekognition-what-is',
        ['Amazon Rekognition is a cloud-based image and video analysis service that makes it easy to add advanced computer vision capabilities to your applications.'])),
    cue('extract text, forms or tables from scanned documents', 'Amazon Textract',
      b('Textract extracts text, forms and tables from documents.', 'textract-what-is',
        ['Extract text, forms, and tables from documents with structured data, using the Amazon Textract Document Analysis API.'])),
    cue('convert recorded speech or audio to text', 'Amazon Transcribe',
      b('Transcribe is an automatic speech recognition service that converts audio to text.', 'transcribe-what-is',
        ['Amazon Transcribe is an automatic speech recognition service that uses machine learning models to convert audio to text.'])),
    cue('translate text between languages', 'Amazon Translate',
      b('Translate is a text translation service.', 'translate-what-is',
        ['Amazon Translate is a text translation service that uses advanced machine learning technologies to provide high-quality translation on demand.'])),
    cue('application keeps session state on the server and cannot be modified', 'ALB sticky sessions',
      b('Sticky sessions send all requests in a session to the same target and suit servers that maintain state.', 'alb-target-attrs',
        ['This feature is useful for servers that maintain state information in order to provide a continuous experience to clients.'])),
    cue('instance impaired by underlying hardware, keep the same instance ID and IP', 'EC2 automatic instance recovery',
      b('Recovery preserves the instance ID, IP addresses, metadata and attached EBS volumes.', 'ec2-recover',
        ['Preserved elements: Instance ID Public, private, and Elastic IP addresses Instance metadata Placement group Attached EBS volumes Availability Zone Lost elements: Data stored in volatile memory (RAM)'])),
    cue('legacy database needs high availability, no application change', 'RDS Multi-AZ',
      b('RDS provisions and maintains a synchronous standby in a different Availability Zone.', 'rds-multi-az-instance',
        ['In a Multi-AZ DB instance deployment, Amazon RDS automatically provisions and maintains a synchronous standby replica in a different Availability Zone.'])),
  ],
  examples: [],
  confuse: [],
};

export default notes;
