import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'legacy-wharf',
  overview: [
    b('Some applications cannot be changed: they keep state on the server, assume one database and were never built for the cloud. This building covers pre-built AI services and infrastructure-level reliability. Pre-built AWS AI services such as Amazon Comprehend and Amazon Polly give an application a capability through an API without you building or training a model. And several AWS features raise the reliability of an unchanged application by working around it, such as load balancing with sticky sessions, automatic instance recovery, Multi-AZ databases and DNS failover.',
      ['comprehend-what-is', 'polly-what-is', 'alb-target-attrs', 'ec2-recover'],
      ['comprehend-what-is|Amazon Comprehend uses natural language processing (NLP) to extract insights about the content of documents.',
       'polly-what-is|Amazon Polly is a cloud service that converts text into lifelike speech.',
       'alb-target-attrs|This feature is useful for servers that maintain state information in order to provide a continuous experience to clients.',
       'ec2-recover|These recovery mechanisms are designed to restore instance availability when AWS detects an underlying hardware or software issue that causes a system status check to fail.']),
  ],
  bullets: [
    {
      id: '2.2-K2',
      concepts: [
        b('Amazon Comprehend uses natural language processing (NLP) to extract insights about the content of documents. You can use the pre-trained models it provides or train custom models for classification and entity recognition, and access it through the console or APIs.',
          'comprehend-what-is',
          ['Amazon Comprehend uses natural language processing (NLP) to extract insights about the content of documents.',
           'You can use the pre-trained models that Amazon Comprehend provides, or you can train your own custom models for classification and entity recognition.',
           'You can access Amazon Comprehend document analysis capabilities using the Amazon Comprehend console or using the Amazon Comprehend APIs.']),
        b('Amazon Polly is a cloud service that converts text into lifelike speech. It supports multiple languages and includes a variety of lifelike voices, and can be used to develop applications that increase engagement and accessibility.',
          'polly-what-is',
          ['Amazon Polly is a cloud service that converts text into lifelike speech.',
           'Amazon Polly supports multiple languages and includes a variety of lifelike voices.',
           'You can use Amazon Polly to develop applications that increase engagement and accessibility.']),
        b('{{rename:sagemaker-ai}} is the managed service for building, training and deploying your own machine learning models, in contrast to calling a pre-trained service like Comprehend or Polly.',
          'sagemaker-what-is',
          ['Amazon SageMaker AI is a fully managed machine learning (ML) service.']),
      ],
      services: ['Amazon Comprehend', 'Amazon Polly'],
      design: [
        b('The exam pattern: the requirement names a task that matches one managed AI service (extract entities or sentiment from text → Comprehend; read text aloud → Polly), and the right answer is to call that service rather than build and host a model.',
          ['comprehend-what-is', 'polly-what-is'],
          ['comprehend-what-is|For example, using Amazon Comprehend you can search social networking feeds for mentions of products or scan an entire document repository for key phrases.',
           'polly-what-is|Amazon Polly is a cloud service that converts text into lifelike speech.']),
      ],
    },
    {
      id: '2.2-S7',
      concepts: [
        b('Sticky sessions let an Application Load Balancer bind a user\'s {{term:session}} to a specific target so all requests in the session go to the same target. AWS says this is useful for servers that maintain state information. It needs client cookie support, and is enabled at the target group level. Prefer externalising state (see Blueprint Hall), but sticky sessions help when the application cannot be changed.',
          'alb-target-attrs',
          ['you can use the sticky session feature (also known as session affinity) to enable the load balancer to bind a user\'s session to a specific target.',
           'This feature is useful for servers that maintain state information in order to provide a continuous experience to clients.',
           'To use sticky sessions, the client must support cookies.',
           'Sticky sessions are enabled at the target group level.']),
        b('Automatic instance recovery restores availability when AWS detects an underlying hardware or software issue that fails a system status check, by moving the instance to a different host. The instance keeps its instance ID, IP addresses (including Elastic IP), instance metadata, attached EBS volumes and Availability Zone, but data in memory (and in instance store volumes for CloudWatch action based recovery) is lost.',
          'ec2-recover',
          ['These recovery mechanisms are designed to restore instance availability when AWS detects an underlying hardware or software issue that causes a system status check to fail.',
           'During the instance recovery process, AWS will attempt to move your instance from the host with the underlying hardware or software issue to a different host.',
           'Preserved elements: Instance ID Public, private, and Elastic IP addresses Instance metadata Placement group Attached EBS volumes Availability Zone Lost elements: Data stored in volatile memory (RAM) Data stored on instance store volumes (applicable to CloudWatch action based recovery only) Operating system uptime resets to zero']),
        b('A Multi-AZ RDS deployment gives a database high availability without application changes: RDS automatically provisions and maintains a synchronous standby replica in a different Availability Zone to provide data redundancy and failover support.',
          'rds-multi-az-instance',
          ['In a Multi-AZ DB instance deployment, Amazon RDS automatically provisions and maintains a synchronous standby replica in a different Availability Zone.',
           'Amazon RDS provides high availability and failover support for DB instances using Multi-AZ deployments with a single standby DB instance.']),
        b('A load balancer plus an Auto Scaling group replaces failed instances and spreads traffic, and Route 53 health checks with failover routing can switch DNS to a standby when the primary fails; both work in front of an application without code changes.',
          ['asg-what-is', 'route53-failover-types'],
          ['asg-what-is|Amazon EC2 Auto Scaling automatically monitors the health and availability of your instances using EC2 health checks and replaces terminated or impaired instances to maintain your desired capacity.',
           'route53-failover-types|You configure active-active failover using any routing policy (or combination of routing policies) other than failover, and you configure active-passive failover using the failover routing policy.']),
      ],
      services: ['Elastic Load Balancing (ELB)', 'Amazon Route 53', 'Amazon RDS'],
      design: [
        b('When the question says application changes are not possible, choose infrastructure-level answers: Multi-AZ for the database, a load balancer (with sticky sessions if the app keeps session state) and Auto Scaling or automatic instance recovery for the servers, Route 53 failover for the site. Answers that require refactoring the application are wrong.',
          ['alb-target-attrs', 'rds-multi-az-instance'],
          ['alb-target-attrs|This ensures that all requests from the user during the session are sent to the same target.',
           'rds-multi-az-instance|In a Multi-AZ DB instance deployment, Amazon RDS automatically provisions and maintains a synchronous standby replica in a different Availability Zone.']),
      ],
    },
    {
      id: '2.2-S8',
      concepts: [
        b('Use purpose-built services for the workload instead of generic infrastructure: AWS describes a growing set of database models and services, each built for a data shape, and managed AI services built for tasks like text analysis and speech. See Purpose-Built Workshop for the database matching.',
          'database-decision',
          ['AWS offers a growing number of database options (15+) with diverse data models to support a variety of workloads.',
           'This might involve migrating your applications to use purpose-built cloud databases.']),
        b('Examples from this building: text understanding → Comprehend; speech output → Polly; a managed relational database that needs to survive an AZ failure → RDS Multi-AZ.',
          ['comprehend-what-is', 'polly-what-is', 'rds-multi-az-instance'],
          ['comprehend-what-is|You can use the pre-trained models that Amazon Comprehend provides, or you can train your own custom models for classification and entity recognition.',
           'polly-what-is|Amazon Polly supports multiple languages and includes a variety of lifelike voices.',
           'rds-multi-az-instance|Amazon RDS provides high availability and failover support for DB instances using Multi-AZ deployments with a single standby DB instance.']),
      ],
      services: ['Amazon Comprehend', 'Amazon Polly', 'Amazon RDS'],
      design: [
        b('Rule of thumb for scenario questions: if a managed, purpose-built service exists for the task, choosing it beats running software yourself on EC2, because AWS handles the infrastructure.',
          'database-decision',
          ['For example, you could use Amazon Aurora or purpose-built NoSQL databases such as Amazon DynamoDB, Amazon Neptune, or Amazon DocumentDB (with MongoDB compatibility).']),
      ],
    },
  ],
  cues: [
    cue('extract sentiment, entities or key phrases from text without building a model', 'Amazon Comprehend',
      b('Comprehend uses NLP to extract insights from documents with pre-trained models.', 'comprehend-what-is',
        ['Amazon Comprehend uses natural language processing (NLP) to extract insights about the content of documents.'])),
    cue('convert text to spoken audio', 'Amazon Polly',
      b('Polly converts text into lifelike speech.', 'polly-what-is',
        ['Amazon Polly is a cloud service that converts text into lifelike speech.'])),
    cue('application keeps session state on the server and cannot be modified', 'ALB sticky sessions',
      b('Sticky sessions send all requests in a session to the same target and suit servers that maintain state.', 'alb-target-attrs',
        ['This feature is useful for servers that maintain state information in order to provide a continuous experience to clients.'])),
    cue('instance impaired by underlying hardware, keep the same instance ID and IP', 'EC2 automatic instance recovery',
      b('Recovery preserves the instance ID, IP addresses, metadata and attached EBS volumes.', 'ec2-recover',
        ['Preserved elements: Instance ID Public, private, and Elastic IP addresses Instance metadata Placement group Attached EBS volumes Availability Zone Lost elements: Data stored in volatile memory (RAM)'])),
    cue('legacy database needs high availability, no application change', 'RDS Multi-AZ',
      b('RDS provisions and maintains a synchronous standby in a different Availability Zone.', 'rds-multi-az-instance',
        ['In a Multi-AZ DB instance deployment, Amazon RDS automatically provisions and maintains a synchronous standby replica in a different Availability Zone.'])),
  ],
  examples: [],
  confuse: [],
};

export default notes;
