import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue, example } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'message-quay',
  overview: [
    b('When one part of a system calls another directly, a slow or failed callee slows or breaks the caller. {{term:loose-coupling}} avoids that by putting something in between: a queue, a topic, an event bus, a stream or a workflow. AWS\'s reliability guidance says components usually should not integrate through direct point-to-point interaction but through an intermediate durable layer such as an Amazon SQS queue, a streaming platform such as Amazon Kinesis, or AWS Step Functions.',
      'waf-loose-coupling',
      ['Implementing loose coupling between dependencies isolates a failure in one from impacting another.',
       'The two components do not integrate through direct point-to-point interaction but usually through an intermediate durable storage layer, such as an Amazon SQS queue, a streaming data platform such as Amazon Kinesis, or AWS Step Functions.']),
    b('Choosing the right middle layer comes down to matching the requirement. The Don\'t confuse section below compares SQS, SNS, EventBridge and Kinesis Data Streams.',
      'eda-overview', ['An event-driven architecture uses events to trigger and communicate between decoupled services and is common in modern applications built with microservices.']),
  ],
  bullets: [
    {
      id: '2.1-K5',
      concepts: [
        b('An event-driven architecture uses events to trigger and communicate between decoupled services. It has three key components: event producers, event routers and event consumers. Events can carry state (the item purchased, its price and a delivery address) or be identifiers (a notification that an order was shipped).',
          'eda-overview',
          ['An event-driven architecture uses events to trigger and communicate between decoupled services and is common in modern applications built with microservices.',
           'Event-driven architectures have three key components: event producers, event routers, and event consumers.',
           'Events can either carry the state (the item purchased, its price, and a delivery address) or events can be identifiers (a notification that an order was shipped).'],
          { allow: ['three'] }),
        b('Amazon EventBridge is a serverless service that uses events to connect application components, making it easier to build scalable event-driven applications. A rule specifies which events go to which targets, and an event pattern selects events by source, type or attributes.',
          ['eventbridge-what-is', 'eventbridge-rules', 'eventbridge-patterns'],
          ['eventbridge-what-is|EventBridge is a serverless service that uses events to connect application components together, making it easier for you to build scalable event-driven applications.',
           'eventbridge-rules|A rule specifies which events to send to which targets for processing.',
           'eventbridge-patterns|you\'ll likely want to select a subset of all the events delivered, based on the source of the event, the event type, and/or attributes of those events.']),
        b('A single EventBridge rule can send an event to multiple targets, which then run in parallel. Rules either match on event data or run on a defined schedule, although scheduled rules are a legacy feature and EventBridge Scheduler is the newer way to schedule tasks. AWS describes a Custom Event Bus (which retains events for a period you set and supports ordered delivery and replay) alongside the classic bus, which remains available, and says to start new applications with the Custom Event Bus.',
          ['eventbridge-what-is', 'eventbridge-rules'],
          ['eventbridge-rules|A single rule can send an event to multiple targets, which then run in parallel.You can create two types of rules: rules that match on event data as events are delivered, and rules that run on a defined schedule.',
           'eventbridge-rules|Scheduled rules are a legacy feature of EventBridge.EventBridge offers a more flexible and powerful way to create, run, and manage scheduled tasks centrally, at scale: EventBridge Scheduler.',
           'eventbridge-what-is|The Custom Event Bus routes events to subscribers that consumers create themselves, retains events for a period that you set, and supports ordered delivery, replay, and non-JSON payloads.',
           'eventbridge-what-is|For new applications, start with the Custom Event Bus.',
           'eventbridge-what-is|Custom Event Bus - Classic remains available, and this guide describes both.']),
      ],
      services: ['Amazon EventBridge', 'AWS Lambda', 'Amazon SNS', 'Amazon SQS'],
      design: [
        b('Choose events when something happens and several independent parts of the system may need to react. The producer does not know who the consumers are, so you can add or change consumers without touching it.',
          'eda-overview', ['An event-driven architecture uses events to trigger and communicate between decoupled services']),
      ],
    },
    {
      id: '2.1-K11',
      concepts: [
        b('Amazon SQS offers a secure, durable and available hosted queue that lets you integrate and decouple distributed software systems and components. A producer sends a message and a consumer takes it when ready, so the two can work at different speeds.',
          'sqs-what-is', ['Amazon SQS decouples and scales distributed software systems and components as a queue service.'], { allow: ['two'] }),
        b('Standard queues are the default queue type. They ensure at-least-once delivery, so more than one copy of a message might be delivered and messages may occasionally arrive out of order, although they make a best-effort attempt to maintain the order in which messages are sent. SQS stores each message redundantly in multiple Availability Zones before acknowledging it.',
          'sqs-standard',
          ['Amazon SQS provides standard queues as the default queue type',
           'Standard queues ensure at-least-once message delivery, but due to the highly distributed architecture, more than one copy of a message might be delivered, and messages may occasionally arrive out of order.',
           'Despite this, standard queues make a best-effort attempt to maintain the order in which messages are sent.',
           'Amazon SQS redundantly stores the message in multiple availability zones (AZs) before acknowledging it.'],
          { allow: ['two'] }),
        b('A dead-letter queue (DLQ) is a queue that source queues can target for messages that are not processed successfully, so you can examine and analyse them. It must be in the same account and Region as the source queue.',
          'sqs-dlq',
          ['Amazon SQS supports dead-letter queues (DLQs), which source queues can target for messages that are not processed successfully.',
           'The dead-letter queue must be in the same AWS account and Region as the source queue.']),
        b('Amazon SNS is publish/subscribe: publishers send messages to a topic, and the topic delivers them to multiple subscribers. Subscribers can be SQS queues, Lambda functions, HTTP(S) endpoints, email, mobile push and SMS.',
          'sns-what-is',
          ['Publishers communicate asynchronously with subscribers by sending messages to a topic, which is a logical access point and communication channel.',
           'Subscribers to an SNS topic can receive messages through different endpoints, depending on their use case, such as: Amazon SQS Lambda HTTP(S) endpoints Email Mobile push notifications Mobile text messages (SMS)']),
        b('Amazon MQ is the managed broker option in the same family as SQS and SNS. AWS lists SQS, SNS and Amazon MQ as managed messaging services each designed for specific roles within distributed systems. Amazon MQ is a managed message broker service for Apache ActiveMQ Classic and RabbitMQ, and you can migrate existing message brokers to it without rewriting messaging code.',
          ['sqs-what-is', 'mq-what-is'],
          ['sqs-what-is|Amazon SQS, Amazon SNS, and Amazon MQ offer highly scalable and easy-to-use managed messaging services, each designed for specific roles within distributed systems.',
           'mq-what-is|Amazon MQ is a managed message broker service for Apache ActiveMQ Classic and RabbitMQ that manages the setup, operation, and maintenance of message brokers.',
           'mq-what-is|You can create a new Amazon MQ broker using industry standard messaging protocols, or migrate existing message brokers to Amazon MQ without rewriting messaging code.']),
      ],
      services: ['Amazon SQS', 'Amazon SNS', 'Amazon MQ'],
      design: [
        b('A common shape: a queue between a web tier and a processing tier so request spikes are buffered, messages that cannot be processed go to a dead-letter queue, and the consumers work at their own speed. Add SNS in front for fanout to several queues.',
          ['sqs-what-is', 'sns-what-is', 'sqs-dlq'],
          ['sqs-what-is|Scalability – Amazon SQS can process each buffered request independently, scaling transparently to handle any load increases or spikes without any provisioning instructions.',
           'sqs-dlq|Amazon SQS supports dead-letter queues (DLQs), which source queues can target for messages that are not processed successfully.',
           'sqs-what-is|For wider distribution, integrating Amazon SQS with Amazon SNS enables a fanout messaging pattern, effectively pushing messages to multiple subscribers at once.',
           'sns-what-is|The Fanout scenario is when a message published to an SNS topic is replicated and pushed to multiple endpoints']),
      ],
    },
    {
      id: '2.1-K16',
      concepts: [
        b('With AWS Step Functions you create workflows; in Step Functions a state machine is called a workflow, made of event-driven steps called states, and running workflows are executions. Step Functions can call AWS services such as Lambda to perform tasks.',
          'stepfunctions',
          ['In Step Functions, state machines are called workflows, which are a series of event-driven steps.',
           'Each step in a workflow is called a state.',
           'Depending on your use case, you can have Step Functions call AWS services, such as Lambda, to perform tasks.']),
        b('There are two workflow types. Standard workflows are ideal for long-running, auditable workflows, as they show execution history and visual debugging; they have exactly-once workflow execution and can run for up to one year. Express workflows are ideal for high-event-rate workloads such as streaming data processing and IoT data ingestion; they have at-least-once workflow execution, so a step can potentially run more than once, and can run for up to five minutes.',
          'stepfunctions',
          ['Step Functions has two workflow types: Standard workflows are ideal for long-running, auditable workflows, as they show execution history and visual debugging.',
           'Standard workflows have exactly-once workflow execution and can run for up to one year.',
           'Express workflows are ideal for high-event-rate workloads, such as streaming data processing and IoT data ingestion.',
           'Express workflows have at-least-once workflow execution and can run for up to five minutes.',
           'This means that one or more steps in an Express Workflow can potentially run more than once, while each step in the workflow executes at least once.'],
          { allow: ['two'] }),
        b('Step Functions is one of the intermediate layers AWS names for loose coupling, alongside queues and streams, because the workflow holds the coordination logic instead of the individual components calling each other.',
          'waf-loose-coupling', ['usually through an intermediate durable storage layer, such as an Amazon SQS queue, a streaming data platform such as Amazon Kinesis, or AWS Step Functions.']),
      ],
      services: ['AWS Step Functions', 'AWS Lambda'],
      design: [
        b('Step Functions fits a business process with ordered steps, branching, retries and error handling that you would otherwise code into a chain of functions. A queue or events fit better when there is no central sequence, just independent reactions.',
          'stepfunctions',
          ['With AWS Step Functions, you can create workflows, also called State machines, to build distributed applications, automate processes, orchestrate microservices, and create data and machine learning pipelines.',
           'Error handling (Retry / Catch) – You can retry failed tasks, or catch failed tasks and automatically run alternative steps.']),
      ],
    },
    {
      id: '2.1-S3',
      concepts: [
        b('Making dependencies loosely coupled means decoupling queuing systems, streaming systems and workflows, which minimises the impact of changes or failure on a system and isolates a failure in one component from affecting another.',
          'waf-loose-coupling',
          ['Decoupling dependencies, such as queuing systems, streaming systems, and workflows, help minimize the impact of changes or failure on a system.',
           'Implementing loose coupling between dependencies isolates a failure in one from impacting another.']),
        b('Consumers must also be safe to retry. An idempotent service processes a request so that making multiple identical requests has the same effect as making a single request, which AWS achieves with an idempotency token.',
          'waf-idempotent',
          ['An idempotent service promises that each request is processed exactly once, such that making multiple identical requests has the same effect as making a single request.',
           'To do this, clients can issue API requests with an idempotency token, which is used whenever the request is repeated.']),
      ],
      services: ['Amazon SQS', 'Amazon SNS', 'Amazon EventBridge', 'AWS Step Functions', 'Amazon Kinesis'],
      design: [
        b('Match the requirement: buffer and decouple speeds (SQS), notify many subscribers (SNS), route events by content with rules (EventBridge), process a continuous stream (Kinesis Data Streams), coordinate a multi-step process (Step Functions).',
          ['sqs-what-is', 'sns-what-is', 'eventbridge-what-is', 'kinesis-streams', 'stepfunctions'],
          ['sqs-what-is|Amazon SQS decouples and scales distributed software systems and components as a queue service.',
           'sns-what-is|The topic acts as a logical access point, ensuring messages are delivered to multiple subscribers across different platforms.',
           'eventbridge-what-is|EventBridge provides simple and consistent ways to ingest, filter, transform, and deliver events so you can build applications quickly.',
           'kinesis-streams|You can use Amazon Kinesis Data Streams to collect and process large streams of data records in real time.',
           'stepfunctions|In Step Functions, state machines are called workflows, which are a series of event-driven steps.']),
      ],
    },
  ],
  cues: [
    cue('decouple the producer and consumer / absorb traffic spikes / buffer requests', 'Amazon SQS',
      b('SQS is a hosted queue that decouples and scales distributed systems and components.', 'sqs-what-is',
        ['Amazon SQS decouples and scales distributed software systems and components as a queue service.'])),
    cue('send one message to multiple subscribers / fanout / email, SMS, mobile push', 'Amazon SNS',
      b('SNS delivers messages from publishers to multiple subscribers, including SQS, Lambda, email, push and SMS.', 'sns-what-is',
        ['The Fanout scenario is when a message published to an SNS topic is replicated and pushed to multiple endpoints'])),
    cue('react to events from AWS services or SaaS applications, route by rules', 'Amazon EventBridge',
      b('A rule specifies which events to send to which targets, and one rule can send an event to multiple targets.', 'eventbridge-rules',
        ['A rule specifies which events to send to which targets for processing.'])),
    cue('real-time streaming data read by several independent consumers, records kept in order within a shard', 'Kinesis Data Streams',
      b('Kinesis Data Streams collects and processes large streams of data records in real time; several applications can consume the same stream independently, and each shard holds a sequence of data records.', ['kinesis-streams', 'kinesis-concepts'],
        ['kinesis-streams|You can use Amazon Kinesis Data Streams to collect and process large streams of data records in real time.',
         'kinesis-streams|Multiple Kinesis Data Streams applications can consume data from a stream, so that multiple actions, like archiving and processing, can take place concurrently and independently.',
         'kinesis-concepts|Each shard has a sequence of data records.'])),
    cue('coordinate multiple steps with retries and branching / visual workflow', 'AWS Step Functions',
      b('Step Functions creates workflows of event-driven steps, lets you visualize, edit and debug them, and can retry failed tasks or catch them and run alternative steps.', 'stepfunctions',
        ['In the Step Functions\' console, you can visualize, edit, and debug your application’s workflow.',
         'Error handling (Retry / Catch) – You can retry failed tasks, or catch failed tasks and automatically run alternative steps.'])),
    cue('migrate an existing ActiveMQ or RabbitMQ message broker without rewriting messaging code', 'Amazon MQ',
      b('Amazon MQ is a managed message broker service for Apache ActiveMQ Classic and RabbitMQ, and existing brokers can be migrated to it without rewriting messaging code.', 'mq-what-is',
        ['You can create a new Amazon MQ broker using industry standard messaging protocols, or migrate existing message brokers to Amazon MQ without rewriting messaging code.'])),
    cue('failed messages should be set aside for analysis', 'SQS dead-letter queue',
      b('A dead-letter queue holds messages that are not processed successfully so you can analyse them.', 'sqs-dlq',
        ['Analyze the contents of messages moved to the dead-letter queue to diagnose application issues.'])),
  ],
  examples: [
    example('EventBridge event pattern for new objects in one bucket', 'other',
      `
{
  "source": ["aws.s3"],
  "detail-type": ["Object Created"],
  "detail": {
    "bucket": { "name": ["example-uploads-bucket"] }
  }
}
`,
      [
        b('An event pattern defines the data EventBridge uses to decide whether to send an event to a target. You write the fields you want to match; events that do not match are not delivered to that rule\'s targets.', 'eventbridge-patterns',
          ['To specify which events to send to a target, you create an event pattern.', 'An event pattern defines the data EventBridge uses to determine whether to send the event to the target.']),
        b('`source` and `detail-type` select events by the source of the event and the event type; the `detail` section selects on attributes of the event, here one bucket name.', 'eventbridge-patterns',
          ['based on the source of the event, the event type, and/or attributes of those events.']),
        b('The pattern belongs in a rule, and the rule names the targets, which can be several and run in parallel. Illustrative only: the bucket name is a placeholder.', 'eventbridge-rules',
          ['A rule specifies which events to send to which targets for processing.', 'A single rule can send an event to multiple targets, which then run in parallel.']),
      ]),
  ],
  confuse: ['sqs-sns-eventbridge-kinesis'],
  azure: [
    {
      concept: 'Azure Event Grid',
      aws: 'Amazon EventBridge',
      mapping: b('Microsoft Learn pairs Azure Event Grid with EventBridge as the managed event routing service for event-driven architectures.',
        ['learn-compute', 'eventbridge-what-is'],
        ['learn-compute|Managed event routing for event-driven architectures.', 'eventbridge-what-is|EventBridge is a serverless service that uses events to connect application components together, making it easier for you to build scalable event-driven applications.']),
      breaks: b('The Microsoft Learn comparison covers only the event-routing piece. On AWS, queues and topics are separate services: SQS is the queue, SNS is publish/subscribe, and EventBridge routes events by rules.',
        ['sqs-what-is', 'sns-what-is', 'learn-compute'],
        ['sqs-what-is|Amazon SQS decouples and scales distributed software systems and components as a queue service.',
         'sns-what-is|Amazon Simple Notification Service (Amazon SNS) is a fully managed service that provides message delivery from publishers (producers) to subscribers (consumers).',
         'learn-compute|AWS EventBridge Azure Event Grid']),
    },
    {
      concept: 'Azure Durable Functions and Azure Logic Apps',
      aws: 'AWS Step Functions',
      mapping: b('The Learn comparison pairs Step Functions with Durable Functions and Logic Apps: stateful workflow orchestration.',
        ['learn-compute', 'stepfunctions'],
        ['learn-compute|AWS Step Functions Azure durable functions, Azure Logic Apps', 'stepfunctions|With AWS Step Functions, you can create workflows, also called State machines, to build distributed applications, automate processes, orchestrate microservices, and create data and machine learning pipelines.']),
      breaks: b('The Microsoft Learn comparison names the pairing but not workflow types. Step Functions workflows are defined as state machines of states, and there are two types: Standard (long-running, auditable, exactly-once) and Express (high-event-rate, at-least-once).',
        ['stepfunctions', 'learn-compute'],
        ['stepfunctions|Standard workflows are ideal for long-running, auditable workflows, as they show execution history and visual debugging.',
         'stepfunctions|Express workflows are ideal for high-event-rate workloads, such as streaming data processing and IoT data ingestion.',
         'learn-compute|AWS Step Functions Azure durable functions, Azure Logic Apps'],
        { allow: ['two'] }),
    },
    {
      concept: 'Azure Service Bus',
      aws: 'Amazon SQS and Amazon SNS',
      mapping: b('Azure Service Bus is a fully managed enterprise message broker with message queues and publish-subscribe topics. On AWS, Amazon SQS is a queue service and Amazon SNS delivers messages from publishers to subscribers; together they are the closest match, not a one-to-one equivalent.',
        ['learn-azure-servicebus', 'sqs-what-is', 'sns-what-is'],
        ['learn-azure-servicebus|Azure Service Bus is a fully managed enterprise message broker with message queues and publish-subscribe topics.',
         'sqs-what-is|Amazon SQS decouples and scales distributed software systems and components as a queue service.',
         'sns-what-is|Amazon Simple Notification Service (Amazon SNS) is a fully managed service that provides message delivery from publishers (producers) to subscribers (consumers).']),
      breaks: b('Service Bus puts queues and topics in one service, while AWS splits the roles across SQS and SNS, and offers Amazon MQ as a managed broker for ActiveMQ and RabbitMQ.',
        ['learn-azure-servicebus', 'mq-what-is'],
        ['learn-azure-servicebus|Azure Service Bus is a fully managed enterprise message broker with message queues and publish-subscribe topics.',
         'mq-what-is|Amazon MQ is a managed message broker service for Apache ActiveMQ Classic and RabbitMQ that manages the setup, operation, and maintenance of message brokers.']),
    },
  ],
};

export default notes;
