import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'purpose-built-workshop',
  overview: [
    b('A purpose-built service is shaped for one data model or job. Examples in this building: a managed file transfer service for moving files into AWS storage, a secrets service instead of hard-coded credentials, and a database whose model fits the data, such as a graph database for connected data.',
      ['transfer-what-is', 'secrets-intro', 'database-decision'],
      ['transfer-what-is|AWS Transfer Family is a secure transfer service that enables you to transfer files into and out of AWS storage services.',
       'secrets-intro|Secrets Manager helps you improve your security posture, because you no longer need hard-coded credentials in application source code.',
       'database-decision|AWS offers a growing number of database options (15+) with diverse data models to support a variety of workloads.']),
  ],
  bullets: [
    {
      id: '2.1-K2',
      concepts: [
        b('AWS Transfer Family offers fully managed support for transferring files over SFTP, AS2, FTPS and FTP, and web browser-based transfers, directly into and out of AWS storage services. Use it when partners or legacy systems must keep using a file transfer protocol but you want the files to land in AWS storage.',
          'transfer-what-is',
          ['AWS Transfer Family offers fully managed support for the transfer of files over SFTP, AS2, FTPS, FTP, and web browser-based transfers directly into and out of AWS storage services.']),
        b('Amazon SQS offers a secure, durable and available hosted queue that lets you decouple distributed software systems and components. (Details are in Message Quay.)',
          'sqs-what-is',
          ['Amazon SQS decouples and scales distributed software systems and components as a queue service.']),
        b('AWS Secrets Manager helps you manage, retrieve and rotate database credentials, application credentials, OAuth tokens, API keys and other secrets throughout their lifecycles. You replace hard-coded credentials with a runtime call to retrieve them dynamically, and you can configure an automatic rotation schedule.',
          'secrets-intro',
          ['AWS Secrets Manager helps you manage, retrieve, and rotate database credentials, application credentials, OAuth tokens, API keys, and other secrets throughout their lifecycles',
           'You replace hard-coded credentials with a runtime call to the Secrets Manager service to retrieve credentials dynamically when you need them.',
           'With Secrets Manager, you can configure an automatic rotation schedule for your secrets.']),
      ],
      services: ['AWS Transfer Family', 'Amazon SQS', 'AWS Secrets Manager'],
      design: [
        b('Typical match-ups: a partner needs SFTP into your S3 bucket → Transfer Family; components should not call each other directly → SQS; application needs a database password without storing it in code → Secrets Manager (with rotation). The Secrets Manager vs Parameter Store comparison is in Warden\'s Lodge.',
          ['transfer-what-is', 'secrets-intro'],
          ['transfer-what-is|AWS Transfer Family is a secure transfer service that enables you to transfer files into and out of AWS storage services.',
           'secrets-intro|Storing the credentials in Secrets Manager helps avoid possible compromise by anyone who can inspect your application or the components.']),
      ],
    },
    {
      id: '2.1-S7',
      concepts: [
        b('AWS describes the purpose-built idea for data: use Amazon Aurora or purpose-built NoSQL databases such as Amazon DynamoDB, Amazon Neptune or Amazon DocumentDB instead of one general database for everything. The database models it lists are relational, key-value, document, in-memory, graph, time series, vector and wide-column.',
          'database-decision',
          ['For example, you could use Amazon Aurora or purpose-built NoSQL databases such as Amazon DynamoDB, Amazon Neptune, or Amazon DocumentDB (with MongoDB compatibility).',
           'These include relational, key-value, document, in-memory, graph, time series, vector, and wide-column.']),
        b('Key-value: Amazon DynamoDB is a serverless, fully managed, distributed NoSQL database with single-digit millisecond performance at any scale. AWS suggests it for workloads such as session stores or shopping carts.',
          ['dynamodb-what-is', 'database-decision'],
          ['dynamodb-what-is|Amazon DynamoDB is a serverless, fully managed, distributed NoSQL database with single-digit millisecond performance at any scale.',
           'database-decision|Amazon DynamoDB Key-value Use for workloads such as session stores or shopping carts.']),
        b('Document: Amazon DocumentDB (with MongoDB compatibility) is for storing JSON-like documents with rich querying across the fields of the documents.',
          'database-decision',
          ['Amazon DocumentDB (with MongoDB compatibility) Document Use when you want to store JSON-like documents with rich querying abilities across the fields of the documents.']),
        b('Graph: Amazon Neptune is a fast, reliable, fully managed graph database for applications that work with highly connected datasets, with use cases such as recommendation engines, fraud detection, knowledge graphs, drug discovery and network security.',
          'neptune-what-is',
          ['Amazon Neptune is a fast, reliable, fully managed graph database service that makes it easy to build and run applications that work with highly connected datasets.',
           'Neptune powers graph use cases such as recommendation engines, fraud detection, knowledge graphs, drug discovery, and network security.']),
        b('Time series: Amazon Timestream is for large amounts of time series data from many sources, such as IoT data, application metrics and asset tracking. AWS has closed new customer access to Amazon Timestream for LiveAnalytics and recommends that new customers evaluate Amazon Timestream for InfluxDB. Wide-column: Amazon Keyspaces (for Apache Cassandra) is for migrating on-premises Cassandra workloads.',
          ['database-decision', 'timestream-availability'],
          ['database-decision|Amazon Timestream Time series Use when you have a large amount of time series data, potentially from a number of sources, such as Internet of Things (IoT) data, application metrics, and asset tracking.',
           'timestream-availability|After careful consideration, we have made the decision to close new customer access to Amazon Timestream for LiveAnalytics',
           'timestream-availability|We recommend that new customers evaluate Amazon Timestream for InfluxDB as an alternative due to its similar functionality.',
           'database-decision|Amazon Keyspaces (for Apache Cassandra) Wide-column Use when you need to migrate your on-premises Cassandra workloads']),
        b('In-memory: for response times in microseconds, use an in-memory caching solution such as Amazon ElastiCache alongside your database, or Amazon MemoryDB when you need a fully durable, persistent in-memory database.',
          'database-decision',
          ['If your workload requires extremely high read performance with a response time measured in microseconds (rather than single-digit milliseconds), you might want to consider using in- memory caching solutions such as Amazon ElastiCache alongside your database, or a fully durable, persistent in-memory database such as Amazon MemoryDB.']),
        b('Relational: Amazon RDS is a fully managed relational database with a choice of engines (PostgreSQL, MySQL, MariaDB, SQL Server, Oracle and Db2); Amazon Aurora is for migrating or modernising on-premises relational workloads, or workloads with less predictable query patterns. Analytics at scale is Amazon Redshift, a fully managed data warehousing service. (The Aurora vs RDS comparison is in Database Registry.)',
          'database-decision',
          ['Amazon RDS Relational Use when you need a fully managed relational database with your choice of six popular engines: PostgreSQL, MySQL, MariaDB, SQL Server, Oracle, and Db2.',
           'Amazon Aurora Relational Use when you\'re migrating or modernizing an on-premises relational workload, or if your workload has less predictable query patterns.',
           'Amazon Redshift is a fully managed, cloud-based data warehousing service that is designed to handle large-scale analytics workloads.']),
      ],
      services: ['Amazon DynamoDB', 'Amazon Neptune', 'Amazon ElastiCache', 'Amazon RDS'],
      design: [
        b('Read the data shape in the question: highly connected relationships → graph (Neptune); JSON documents with rich queries → DocumentDB; simple key lookups at massive scale → DynamoDB; relational → RDS or Aurora; microsecond reads in front of a database → an in-memory cache such as ElastiCache; metrics or IoT data over time → a time series database.',
          ['database-decision', 'neptune-what-is'],
          ['database-decision|Key-value databases can scale to large amounts of data and extremely high throughput of requests, while servicing millions of simultaneous users through distributed processing and storage.',
           'neptune-what-is|Neptune powers graph use cases such as recommendation engines, fraud detection, knowledge graphs, drug discovery, and network security.',
           'database-decision|Amazon DocumentDB (with MongoDB compatibility) Document Use when you want to store JSON-like documents with rich querying abilities across the fields of the documents.',
           'database-decision|Amazon RDS Relational Use when you need a fully managed relational database with your choice of six popular engines: PostgreSQL, MySQL, MariaDB, SQL Server, Oracle, and Db2.',
           'database-decision|If your workload requires extremely high read performance with a response time measured in microseconds (rather than single-digit milliseconds), you might want to consider using in- memory caching solutions such as Amazon ElastiCache alongside your database, or a fully durable, persistent in-memory database such as Amazon MemoryDB.',
           'database-decision|Amazon Timestream Time series Use when you have a large amount of time series data, potentially from a number of sources, such as Internet of Things (IoT) data, application metrics, and asset tracking.']),
      ],
    },
  ],
  cues: [
    cue('partners upload files over SFTP/FTPS to AWS storage', 'AWS Transfer Family',
      b('Transfer Family supports SFTP, AS2, FTPS and FTP into and out of AWS storage.', 'transfer-what-is',
        ['AWS Transfer Family offers fully managed support for the transfer of files over SFTP, AS2, FTPS, FTP, and web browser-based transfers directly into and out of AWS storage services.'])),
    cue('no hard-coded database credentials / rotate credentials automatically', 'AWS Secrets Manager',
      b('Secrets Manager rotates secrets and removes hard-coded credentials.', 'secrets-intro',
        ['With Secrets Manager, you can configure an automatic rotation schedule for your secrets.'])),
    cue('highly connected data, relationships, recommendation or fraud detection', 'Amazon Neptune',
      b('Neptune is a graph database for highly connected datasets.', 'neptune-what-is',
        ['Neptune powers graph use cases such as recommendation engines, fraud detection, knowledge graphs, drug discovery, and network security.'])),
    cue('session store or shopping cart at massive scale, key-value', 'Amazon DynamoDB (a serverless key-value table); when microsecond in-memory reads are the need, an in-memory cache such as ElastiCache',
      b('AWS suggests DynamoDB for session stores or shopping carts, and suggests an in-memory cache such as ElastiCache when response times need to be measured in microseconds.', 'database-decision',
        ['Amazon DynamoDB Key-value Use for workloads such as session stores or shopping carts.',
         'If your workload requires extremely high read performance with a response time measured in microseconds (rather than single-digit milliseconds), you might want to consider using in- memory caching solutions such as Amazon ElastiCache alongside your database, or a fully durable, persistent in-memory database such as Amazon MemoryDB.'])),
    cue('JSON documents with rich queries, MongoDB compatible', 'Amazon DocumentDB',
      b('DocumentDB stores JSON-like documents with rich querying across fields.', 'database-decision',
        ['Amazon DocumentDB (with MongoDB compatibility) Document Use when you want to store JSON-like documents with rich querying abilities across the fields of the documents.'])),
    cue('IoT or metrics time series data', 'Amazon Timestream (LiveAnalytics is closed to new customers; Timestream for InfluxDB is the alternative AWS recommends)',
      b('Timestream is for large amounts of time series data from IoT, metrics and asset tracking.', ['database-decision', 'timestream-availability'],
        ['database-decision|Amazon Timestream Time series Use when you have a large amount of time series data, potentially from a number of sources, such as Internet of Things (IoT) data, application metrics, and asset tracking.',
         'timestream-availability|We recommend that new customers evaluate Amazon Timestream for InfluxDB as an alternative due to its similar functionality.'])),
    cue('migrate on-premises Cassandra', 'Amazon Keyspaces',
      b('Keyspaces is the wide-column service for migrating on-premises Cassandra workloads.', 'database-decision',
        ['Amazon Keyspaces (for Apache Cassandra) Wide-column Use when you need to migrate your on-premises Cassandra workloads'])),
    cue('data warehouse, large-scale analytics (OLAP)', 'Amazon Redshift',
      b('Redshift is a fully managed data warehousing service for large-scale analytics.', 'database-decision',
        ['Amazon Redshift is a fully managed, cloud-based data warehousing service that is designed to handle large-scale analytics workloads.'])),
  ],
  examples: [],
  confuse: [],
};

export default notes;
