import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'rebuild-yard',
  overview: [
    b('Instead of repairing servers by hand, rebuild them from a known definition. {{term:immutable-infrastructure}} means you never change running production resources in place: you deploy replacements built from a version-controlled configuration. Automation (CloudFormation for provisioning, Systems Manager for operating, Auto Scaling for replacing) makes the rebuild repeatable.',
      ['waf-immutable', 'waf-automate-changes'],
      ['waf-immutable|Immutable infrastructure is a model that mandates that no updates, security patches, or configuration changes happen in-place on production workloads.',
       'waf-automate-changes|Today, this means the use of automation wherever practical in operations, including testing and deploying changes, adding or removing capacity, and migrating data.']),
  ],
  bullets: [
    {
      id: '2.2-K7',
      concepts: [
        b('With immutable infrastructure no in-place modifications are allowed on infrastructure resources within a workload. The Well-Architected benefits are reliability, consistency and reproducibility of deployments; fewer configuration drifts, because replacing resources with a known, version-controlled configuration returns them to a known, tested state; safer deployments with fast rollback, because the previous working version is not changed; and an enhanced security posture, because remote access mechanisms such as SSH can be disabled.',
          'waf-immutable',
          ['Follow an immutable infrastructure deployment strategy to increase the reliability, consistency, and reproducibility in your workload deployments.',
           'Desired outcome: With immutable infrastructure, no in-place modifications are allowed to run infrastructure resources within a workload.',
           'Reduction in configuration drifts: By replacing infrastructure resources with a known and version-controlled configuration, the infrastructure is set to a known, tested, and trusted state, avoiding configuration drifts.',
           'Safer deployments with fast rollback and recovery processes: Deployments are safer because the previous working version is not changed.',
           'Enhanced security posture: By not allowing changes to infrastructure, remote access mechanisms (such as SSH) can be disabled.']),
        b('Two deployment strategies for immutable infrastructure: a canary deployment directs a small number of customers to the new version, usually on a single instance (the canary); a blue/green deployment is similar except that a full fleet of the application is deployed in parallel.',
          'waf-immutable',
          ['There are two main strategies for this deployment: Canary deployment: The practice of directing a small number of your customers to the new version, usually running on a single service instance (the canary).',
           'Blue/green deployment: Similar to the canary deployment, except that a full fleet of the application is deployed in parallel.'],
          { allow: ['two'] }),
        b('An {{term:ami}} provides the software required to set up and boot an EC2 instance, so a new AMI is the natural unit of an immutable release. An Auto Scaling group instance refresh updates the instances in a group, for example to deploy a new AMI or user data script across the group.',
          ['ami', 'asg-instance-refresh'],
          ['ami|An Amazon Machine Image (AMI) is an image that provides the software that is required to set up and boot an Amazon EC2 instance.',
           'asg-instance-refresh|Some situations where an instance refresh can help include: Deploying a new Amazon Machine Image (AMI) or user data script across your Auto Scaling group.']),
      ],
      services: ['Amazon EC2 Auto Scaling', 'AWS CloudFormation'],
      design: [
        b('The immutable approach to deploying an update: build a new image or template and deploy it as new resources instead of changing the running ones, using a canary or blue/green deployment. Deployments are safer with fast rollback because the previous working version is not changed. Use automation as much as possible to increase reproducibility and minimise human error.',
          'waf-immutable',
          ['Canary deployment: The practice of directing a small number of your customers to the new version, usually running on a single service instance (the canary).',
           'Blue/green deployment: Similar to the canary deployment, except that a full fleet of the application is deployed in parallel.',
           'Safer deployments with fast rollback and recovery processes: Deployments are safer because the previous working version is not changed.',
           'When defining an immutable infrastructure deployment strategy, it is recommended to use automation as much as possible to increase reproducibility and minimize the potential of human error.']),
      ],
    },
    {
      id: '2.2-S1',
      concepts: [
        b('AWS CloudFormation helps you model and set up AWS resources: you create a {{term:cloudformation-stack|template}} describing the resources, and CloudFormation provisions and configures them as a stack. Because templates are text files, you track changes to your infrastructure the same way developers control revisions to source code; deleting the stack deletes all its resources.',
          'cfn-what-is',
          ['You create a template that describes all the AWS resources that you want (like Amazon EC2 instances or Amazon RDS DB instances), and CloudFormation takes care of provisioning and configuring those resources for you.',
           'Because these templates are text files, you simply track differences in your templates to track changes to your infrastructure, similar to the way developers control revisions to source code.',
           'You can delete the stack just as easily, which deletes all the resources in the stack.']),
        b('Infrastructure integrity can be checked: drift detection identifies stack resources whose configuration was changed outside CloudFormation, so you can bring them back in sync with the template.',
          'cfn-drift',
          ['You can use drift detection to identify stack resources to which configuration changes have been made outside of CloudFormation management.',
           'You can then take corrective action so that your stack resources are again in sync with their definitions in the stack template, such as updating the drifted resources directly so that they agree with their template definition.']),
        b('AWS Systems Manager helps you centrally view, manage and operate nodes at scale. Its tools include Run Command, Session Manager, Automation and Parameter Store. Patch Manager automates the process of patching managed nodes with security-related and other updates; nodes must be managed, which means SSM Agent is installed and can communicate with Systems Manager.',
          ['ssm-what-is', 'ssm-patch'],
          ['ssm-what-is|AWS Systems Manager helps you centrally view, manage, and operate nodes at scale in AWS, on-premises, and multicloud environments.',
           'ssm-what-is|Tools consist of the individual capabilities of Systems Manager and their features such as Run Command, Session Manager, Automation, and Parameter Store.',
           'ssm-what-is|To use Systems Manager, nodes must be managed, which means SSM Agent is installed on the machine and the agent can communicate with the Systems Manager service.',
           'ssm-patch|Patch Manager automates the process of patching managed nodes with both security-related updates and other types of updates.']),
        b('Systems Manager Session Manager lets you securely connect to nodes without opening inbound ports, which fits the immutable idea of disabling SSH.',
          'ssm-what-is',
          ['With Systems Manager tools you can do the following: Just-in-time access node access Patch nodes at scale Securely connect to nodes without opening inbound ports Run commands remotely on nodes Securely store data referenced by applications Automate common systems administration tasks']),
        b('Deployments and patching should be automated to eliminate negative impact; Auto Scaling monitors instance health and replaces terminated or impaired instances to maintain desired capacity.',
          ['waf-automate-changes', 'asg-what-is'],
          ['waf-automate-changes|Deployments and patching are automated to eliminate negative impact.',
           'asg-what-is|Amazon EC2 Auto Scaling automatically monitors the health and availability of your instances using EC2 health checks and replaces terminated or impaired instances to maintain your desired capacity.']),
      ],
      services: ['AWS CloudFormation', 'AWS Systems Manager', 'Amazon EC2 Auto Scaling'],
      design: [
        b('Picking the tool: provision whole environments repeatably, including across Regions with CloudFormation StackSets → CloudFormation; patch and operate existing instances at scale without inbound ports → Systems Manager; roll a new image across a fleet → Auto Scaling instance refresh; detect manual changes → CloudFormation drift detection.',
          ['cfn-what-is', 'ssm-patch', 'asg-instance-refresh', 'ssm-what-is', 'cfn-drift', 'waf-multi-location'],
          ['cfn-what-is|By using CloudFormation, you easily manage a collection of resources as a single unit.',
           'waf-multi-location|To ease multi-Regional deployments and maintain consistency, AWS CloudFormation StackSets can replicate your entire AWS infrastructure across multiple Regions.',
           'ssm-what-is|With Systems Manager tools you can do the following: Just-in-time access node access Patch nodes at scale Securely connect to nodes without opening inbound ports Run commands remotely on nodes Securely store data referenced by applications Automate common systems administration tasks',
           'cfn-drift|You can use drift detection to identify stack resources to which configuration changes have been made outside of CloudFormation management.',
           'ssm-patch|Patch Manager automates the process of patching managed nodes with both security-related updates and other types of updates.',
           'asg-instance-refresh|You can use an instance refresh to update the instances in your Auto Scaling group.']),
      ],
    },
  ],
  cues: [
    cue('no in-place changes to production servers / replace rather than patch', 'Immutable infrastructure (new AMI or template, canary or blue/green)',
      b('Immutable infrastructure mandates no in-place updates, patches or configuration changes on production workloads.', 'waf-immutable',
        ['Immutable infrastructure is a model that mandates that no updates, security patches, or configuration changes happen in-place on production workloads.'])),
    cue('repeatable, version-controlled environment definition', 'AWS CloudFormation',
      b('Templates are text files whose changes you can track like source code.', 'cfn-what-is',
        ['Because these templates are text files, you simply track differences in your templates to track changes to your infrastructure, similar to the way developers control revisions to source code.'])),
    cue('someone changed a resource manually outside the template', 'CloudFormation drift detection',
      b('Drift detection identifies resources changed outside CloudFormation.', 'cfn-drift',
        ['You can use drift detection to identify stack resources to which configuration changes have been made outside of CloudFormation management.'])),
    cue('patch instances at scale / run commands without SSH or inbound ports', 'AWS Systems Manager (Patch Manager, Session Manager, Run Command)',
      b('Systems Manager patches nodes at scale and connects securely without opening inbound ports.', 'ssm-what-is',
        ['With Systems Manager tools you can do the following: Just-in-time access node access Patch nodes at scale Securely connect to nodes without opening inbound ports Run commands remotely on nodes Securely store data referenced by applications Automate common systems administration tasks'])),
    cue('roll out a new AMI to every instance in an Auto Scaling group', 'Auto Scaling instance refresh',
      b('An instance refresh can deploy a new AMI or user data script across the group.', 'asg-instance-refresh',
        ['Some situations where an instance refresh can help include: Deploying a new Amazon Machine Image (AMI) or user data script across your Auto Scaling group.'])),
    cue('send a small share of users to the new version first', 'Canary deployment',
      b('A canary deployment directs a small number of customers to the new version.', 'waf-immutable',
        ['Canary deployment: The practice of directing a small number of your customers to the new version, usually running on a single service instance (the canary).'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Resource Manager / Bicep',
      aws: 'AWS CloudFormation',
      mapping: b('Learn pairs AWS CloudFormation with Azure Resource Manager and Bicep (and other tools): ways to build and deploy repeatable cloud environments by using declarative syntax to define infrastructure as code.',
        ['learn-hub', 'cfn-what-is'],
        ['learn-hub|These services provide ways for developers and cloud admins to build and deploy repeatable cloud environments by using declarative syntax or common programming languages to define infrastructure as code.',
         'cfn-what-is|You create a template that describes all the AWS resources that you want (like Amazon EC2 instances or Amazon RDS DB instances), and CloudFormation takes care of provisioning and configuring those resources for you.']),
      breaks: b('The Microsoft Learn comparison describes only the shared purpose (declarative or code-based infrastructure as code). On the AWS side, the CloudFormation unit of management is the stack, which manages a collection of resources as a single unit, and drift detection identifies resources changed outside CloudFormation.',
        ['cfn-what-is', 'cfn-drift', 'learn-hub'],
        ['cfn-what-is|By using CloudFormation, you easily manage a collection of resources as a single unit.',
         'cfn-drift|You can use drift detection to identify stack resources to which configuration changes have been made outside of CloudFormation management.',
         'learn-hub|These services provide ways for developers and cloud admins to build and deploy repeatable cloud environments by using declarative syntax or common programming languages to define infrastructure as code.']),
    },
    {
      concept: 'Azure Automation and Azure Update Manager',
      aws: 'AWS Systems Manager',
      mapping: b('Learn pairs AWS Systems Manager with Azure Automation and Azure Update Manager. Azure Update Manager helps manage updates for machines that run Windows and Linux across Azure, on-premises and other clouds.',
        ['learn-hub', 'ssm-what-is'],
        ['learn-hub|AWS Systems Manager Azure Automation Azure Update Manager Automation configures and operates applications of all shapes and sizes.',
         'learn-hub|Azure Update Manager is a service that helps manage updates for all your machines, including machines that run on Windows and Linux, across Azure, on-premises, and on other cloud platforms.',
         'ssm-what-is|AWS Systems Manager helps you centrally view, manage, and operate nodes at scale in AWS, on-premises, and multicloud environments.']),
      breaks: b('The Microsoft Learn comparison pairs one AWS service with two Azure services. Systems Manager is one AWS service with many tools (Run Command, Session Manager, Automation, Parameter Store, Patch Manager), and its nodes must be managed through SSM Agent.',
        ['ssm-what-is', 'learn-hub'],
        ['ssm-what-is|To use Systems Manager, nodes must be managed, which means SSM Agent is installed on the machine and the agent can communicate with the Systems Manager service.',
         'learn-hub|AWS Systems Manager Azure Automation Azure Update Manager Automation configures and operates applications of all shapes and sizes.'],
        { allow: ['two'] }),
    },
  ],
};

export default notes;
