import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'scaling-floodgate',
  overview: [
    b('When demand grows you can make one resource bigger (vertical scaling) or add more of them (horizontal scaling). Horizontal scaling needs something to spread the load across the copies, which is a load balancer, and something to add and remove copies automatically, which is Amazon EC2 Auto Scaling. For databases, horizontal scaling of reads is done with read replicas.',
      ['rds-scaling-ha', 'elb-what-is', 'asg-what-is'],
      ['rds-scaling-ha|With Amazon RDS, you can scale vertically by modifying your DB instance size to meet your performance and capacity requirements.',
       'rds-scaling-ha|Amazon RDS provides horizontal scaling by using read replicas to offload read-intensive workloads and improve database performance.',
       'elb-what-is|Elastic Load Balancing automatically distributes your incoming traffic across multiple targets, such as EC2 instances, containers, and IP addresses, in one or more Availability Zones.',
       'asg-what-is|Amazon EC2 Auto Scaling helps you ensure that you have the correct number of Amazon EC2 instances available to handle the load for your application.']),
  ],
  bullets: [
    {
      id: '2.1-K6',
      concepts: [
        b('Vertical scaling makes a resource bigger. For EC2 you resize an instance by changing its instance type, and from then on you pay the rate of the new type. For RDS you modify the DB instance size.',
          ['ec2-resize', 'rds-scaling-ha'],
          ['ec2-resize|If this is the case, you can resize your instance by changing its instance type.',
           'ec2-resize|When you change the instance type, you\'ll start paying the rate of the new instance type.',
           'rds-scaling-ha|With Amazon RDS, you can scale vertically by modifying your DB instance size to meet your performance and capacity requirements.']),
        b('Horizontal scaling adds more instances. For EC2 this means an Auto Scaling group: a collection of EC2 instances where you set a minimum and a maximum size, and EC2 Auto Scaling keeps the group within those limits. For RDS it means read replicas.',
          ['asg-what-is', 'rds-scaling-ha'],
          ['asg-what-is|You create collections of EC2 instances, called Auto Scaling groups.',
           'asg-what-is|You can specify the minimum number of instances in each Auto Scaling group, and Amazon EC2 Auto Scaling ensures that your group never goes below this size.',
           'asg-what-is|You can specify the maximum number of instances in each Auto Scaling group, and Amazon EC2 Auto Scaling ensures that your group never goes above this size.',
           'rds-scaling-ha|Amazon RDS provides horizontal scaling by using read replicas to offload read-intensive workloads and improve database performance.']),
        b('Horizontal scaling works smoothly only for stateless components, because any instance must be able to serve any request. That is the connection to the previous building: a stateful tier forces sticky behaviour or data loss on scale-in.',
          'waf-stateless',
          ['they can scale horizontally because any of the available compute resources (such as EC2 instances and AWS Lambda functions) can service any request.']),
      ],
      services: ['Amazon EC2 Auto Scaling', 'Amazon RDS', 'Amazon EC2'],
      design: [
        b('Prefer horizontal scaling for the stateless application tier (add instances behind a load balancer across Availability Zones) and use vertical scaling for components that cannot be split easily, such as a single writer database instance.',
          ['asg-what-is', 'rds-scaling-ha'],
          ['asg-what-is|You can specify multiple Availability Zones for your Auto Scaling group, and Amazon EC2 Auto Scaling balances your instances evenly across the Availability Zones as the group scales.',
           'rds-scaling-ha|With Amazon RDS, you can scale vertically by modifying your DB instance size to meet your performance and capacity requirements.']),
      ],
    },
    {
      id: '2.1-K9',
      concepts: [
        b('A load balancer distributes workloads across multiple compute resources and serves as the single point of contact for clients. Using one increases the availability and fault tolerance of your applications. Elastic Load Balancing distributes incoming traffic across multiple targets such as EC2 instances, containers and IP addresses, in one or more Availability Zones, and scales the load balancer itself automatically.',
          ['elb-what-is', 'alb-intro'],
          ['elb-what-is|Using a load balancer increases the availability and fault tolerance of your applications.',
           'elb-what-is|Elastic Load Balancing scales your load balancer capacity automatically in response to changes in incoming traffic.',
           'alb-intro|A load balancer serves as the single point of contact for clients.']),
        b('A load balancer monitors the health of its registered targets and routes traffic only to the healthy ones.',
          'elb-what-is',
          ['It monitors the health of its registered targets, and routes traffic only to the healthy targets.']),
        b('An Application Load Balancer functions at the application layer, the seventh layer of the OSI model. You add listeners that check for connection requests on a protocol and port, and rules that decide how requests route to target groups. Rules can route on host or path conditions, HTTP headers and methods, query parameters and source IP addresses.',
          'alb-intro',
          ['An Application Load Balancer functions at the application layer, the seventh layer of the Open Systems Interconnection (OSI) model.',
           'A listener checks for connection requests from clients, using the protocol and port that you configure.',
           'Each target group routes requests to one or more registered targets, such as EC2 instances, using the protocol and port number that you specify.',
           'Support for routing based on fields in the request, such as HTTP header conditions and methods, query parameters, and source IP addresses.']),
        b('Elastic Load Balancing offers four types: Application Load Balancers, Network Load Balancers, Gateway Load Balancers and the previous-generation Classic Load Balancers. The comparison between the current three is in Express Interchange.',
          'alb-intro',
          ['Elastic Load Balancing supports the following load balancers: Application Load Balancers, Network Load Balancers, Gateway Load Balancers, and Classic Load Balancers.'],
          { allow: ['four', 'three'] }),
        b('You can use AWS WAF with an Application Load Balancer to allow or block requests based on web ACL rules, and ACM certificates for HTTPS listeners.',
          ['elb-what-is', 'alb-intro'],
          ['elb-what-is|AWS WAF — You can use AWS WAF with your Application Load Balancer to allow or block requests based on the rules in a web access control list (web ACL).',
           'alb-intro|AWS Certificate Manager — When you create an HTTPS listener, you can specify certificates provided by ACM.']),
      ],
      services: ['Elastic Load Balancing (ELB)'],
      design: [
        b('Place the load balancer in front of an Auto Scaling group that spans Availability Zones: the load balancer spreads requests across healthy instances, and the group replaces instances that fail health checks.',
          'asg-what-is',
          ['Load balancing You can use Elastic Load Balancing load balancing and health checks to ensure an even distribution of application traffic to your healthy instances.',
           'Amazon EC2 Auto Scaling automatically monitors the health and availability of your instances using EC2 health checks and replaces terminated or impaired instances to maintain your desired capacity.']),
      ],
    },
    {
      id: '2.1-K15',
      concepts: [
        b('A read replica is a read-only copy of a DB instance. Updates to the primary are copied to it asynchronously, so you can reduce the load on the primary by routing read queries to the replica and scale out beyond the capacity of a single DB instance for read-heavy workloads.',
          'rds-read-replicas',
          ['A read replica is a read-only copy of a DB instance.',
           'You can reduce the load on your primary DB instance by routing queries from your applications to the read replica.',
           'In this way, you can elastically scale out beyond the capacity constraints of a single DB instance for read-heavy database workloads.',
           'When you make updates to the primary DB instance, Amazon RDS copies them asynchronously to the read replica.']),
        b('Use cases AWS lists include scaling beyond the compute or I/O capacity of a single instance for read-heavy workloads, and business reporting or data warehousing queries that you want to run against a replica instead of production.',
          'rds-read-replicas',
          ['Scaling beyond the compute or I/O capacity of a single DB instance for read-heavy database workloads.',
           'Business reporting or data warehousing scenarios where you might want business reporting queries to run against a read replica, rather than your production DB instance.']),
        b('A read replica can also be promoted to a standalone instance as a disaster recovery solution if the primary fails. RDS does not support autoscaling of read replicas, which would be the automatic adding or removing of replicas as read demand changes.',
          'rds-read-replicas',
          ['You can promote a read replica to a standalone instance as a disaster recovery solution if the primary DB instance fails.',
           'RDS doesn\'t support autoscaling of read replicas, which is the automatic add or removing of read replicas as read demand changes.']),
        b('Read replicas are for read scaling and do not replace Multi-AZ high availability: a read replica can be configured for an instance that also has a standby configured for high availability. The Multi-AZ vs read replica comparison is in Read Replica Annex.',
          'rds-read-replicas',
          ['You can configure a read replica for a DB instance that also has a standby replica configured for high availability in a Multi-AZ deployment.']),
      ],
      services: ['Amazon RDS'],
      design: [
        b('Choose a read replica when the symptom is read load: slow reads, a busy primary, or reports slowing production. It does nothing for write load, and because replication is asynchronous the replica can lag behind the primary.',
          'rds-read-replicas',
          ['Amazon RDS then uses the asynchronous replication method for the DB engine to update the read replica whenever there is a change to the primary DB instance.']),
      ],
    },
    {
      id: '2.1-S2',
      concepts: [
        b('A target tracking scaling policy automatically scales the capacity of an Auto Scaling group based on a target metric value: you select a metric and a target value for the ideal average utilisation or throughput level.',
          'asg-target-tracking',
          ['A target tracking scaling policy automatically scales the capacity of your Auto Scaling group based on a target metric value.',
           'With target tracking, you select a metric and a target value to represent the ideal average utilization or throughput level for your application.']),
        b('Scheduled scaling sets up scaling based on predictable load changes: you create scheduled actions that increase or decrease desired capacity at specific times.',
          'asg-scheduled',
          ['With scheduled scaling, you can set up automatic scaling for your application based on predictable load changes.',
           'You create scheduled actions that increase or decrease your group\'s desired capacity at specific times.']),
        b('Predictive scaling analyses historical load data to detect daily or weekly patterns and forecasts future capacity needs, so the group can proactively increase capacity before the load arrives.',
          'asg-predictive',
          ['Predictive scaling works by analyzing historical load data to detect daily or weekly patterns in traffic flows.',
           'It uses this information to forecast future capacity needs so Amazon EC2 Auto Scaling can proactively increase the capacity of your Auto Scaling group to match the anticipated load.']),
        b('Auto Scaling reduces cost by removing capacity when demand is lower, and a single group can launch multiple instance types and purchase options (Spot and On-Demand) to optimise costs.',
          'asg-what-is',
          ['Using auto scaling allows you to maintain application availability and reduce costs by adding capacity to handle peak loads and removing capacity when demand is lower.',
           'Within a single Auto Scaling group, you can launch multiple instance types and purchase options (Spot and On-Demand Instances), allowing you to optimize costs through Spot Instance usage.']),
      ],
      services: ['Amazon EC2 Auto Scaling', 'Elastic Load Balancing (ELB)'],
      design: [
        b('Pick the scaling method by how predictable the demand is: unpredictable spikes → target tracking; known times (a weekly peak) → scheduled; recurring daily or weekly cycles that you want the group ready for in advance → predictive. Combine them with a minimum capacity for availability and a maximum to cap cost.',
          ['asg-target-tracking', 'asg-scheduled', 'asg-predictive'],
          ['asg-target-tracking|A target tracking scaling policy automatically scales the capacity of your Auto Scaling group based on a target metric value.',
           'asg-scheduled|With scheduled scaling, you can set up automatic scaling for your application based on predictable load changes.',
           'asg-predictive|Predictive scaling is well suited for situations where you have: Cyclical traffic, such as high use of resources during regular business hours and low use of resources during evenings and weekends']),
      ],
    },
  ],
  cues: [
    cue('automatically add and remove EC2 instances as demand changes', 'EC2 Auto Scaling group',
      b('Auto Scaling ensures you have the correct number of EC2 instances for the load.', 'asg-what-is',
        ['Amazon EC2 Auto Scaling helps you ensure that you have the correct number of Amazon EC2 instances available to handle the load for your application.'])),
    cue('keep average CPU at about X percent', 'Target tracking scaling policy',
      b('You pick a metric and a target value for ideal average utilisation.', 'asg-target-tracking',
        ['With target tracking, you select a metric and a target value to represent the ideal average utilization or throughput level for your application.'])),
    cue('traffic rises every weekday morning / known event at a known time', 'Scheduled scaling',
      b('Scheduled actions change desired capacity at specific times for predictable load changes.', 'asg-scheduled',
        ['You create scheduled actions that increase or decrease your group\'s desired capacity at specific times.'])),
    cue('recurring daily/weekly patterns, capacity should be ready before load arrives', 'Predictive scaling',
      b('Predictive scaling forecasts future capacity needs from historical load data.', 'asg-predictive',
        ['It uses this information to forecast future capacity needs so Amazon EC2 Auto Scaling can proactively increase the capacity of your Auto Scaling group to match the anticipated load.'])),
    cue('distribute traffic to healthy instances across AZs', 'Elastic Load Balancing',
      b('A load balancer routes traffic only to healthy targets in one or more Availability Zones.', 'elb-what-is',
        ['It monitors the health of its registered targets, and routes traffic only to the healthy targets.'])),
    cue('route by URL path or host name / HTTP headers', 'Application Load Balancer',
      b('ALB rules can use host and path conditions and request fields.', 'alb-intro',
        ['Support for routing based on fields in the request, such as HTTP header conditions and methods, query parameters, and source IP addresses.'])),
    cue('database reads are slow / reporting queries slow production', 'RDS read replica',
      b('Read replicas offload read-intensive workloads and reporting from the primary.', 'rds-read-replicas',
        ['Business reporting or data warehousing scenarios where you might want business reporting queries to run against a read replica, rather than your production DB instance.'])),
    cue('bigger instance for the same workload without redesign', 'Vertical scaling (change instance type / DB instance size)',
      b('You can resize an instance by changing its instance type.', 'ec2-resize',
        ['If this is the case, you can resize your instance by changing its instance type.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Virtual Machine Scale Sets',
      aws: 'Amazon EC2 Auto Scaling',
      mapping: b('The Learn comparison pairs AWS Auto Scaling with Azure Virtual Machine Scale Sets (and App Service autoscaling): deploy and manage identical sets of VMs that scale with demand.',
        ['learn-compute', 'asg-what-is'],
        ['learn-compute|AWS service Azure service Description AWS Auto Scaling Azure Virtual Machine Scale Sets, Azure App Service autoscaling In Azure, you can use virtual machine scale sets to deploy and manage identical sets of VMs.',
         'asg-what-is|You create collections of EC2 instances, called Auto Scaling groups.']),
      breaks: b('On AWS the exam asks which scaling method fits: target tracking, scheduled or predictive scaling, each with its own trigger. Match the question\'s demand pattern to the method; the Learn row does not distinguish them.',
        ['asg-predictive', 'learn-compute'],
        ['asg-predictive|Predictive scaling works by analyzing historical load data to detect daily or weekly patterns in traffic flows.',
         'learn-compute|AWS service Azure service Description AWS Auto Scaling Azure Virtual Machine Scale Sets, Azure App Service autoscaling In Azure, you can use virtual machine scale sets to deploy and manage identical sets of VMs.'],
        { allow: ['three'] }),
    },
    {
      concept: 'Azure Load Balancer and Application Gateway',
      aws: 'Elastic Load Balancing',
      mapping: b('Learn pairs Elastic Load Balancing with two Azure services: Azure Load Balancer provides the layer 4 capabilities of the AWS Network Load Balancer, and Application Gateway provides application-level rule-based routing comparable to the AWS Application Load Balancer.',
        ['learn-networking', 'alb-intro'],
        ['learn-networking|Elastic Load Balancing, Azure Load Balancer, and Azure Application Gateway The Azure equivalents of the Elastic Load Balancing services are: Load Balancer provides the same network layer 4 capabilities as the AWS Network Load Balancer, so you can distribute traffic for multiple VMs at the network level.',
         'learn-networking|Application Gateway provides application-level rule-based routing comparable to that of the AWS Application Load Balancer.',
         'alb-intro|An Application Load Balancer functions at the application layer, the seventh layer of the Open Systems Interconnection (OSI) model.'],
        { allow: ['two'] }),
      breaks: b('AWS has a third current load balancer type, the Gateway Load Balancer, which has no row in this Learn pairing; it is covered in Express Interchange.',
        ['elb-what-is', 'learn-networking'],
        ['elb-what-is|For more information about the current generation load balancers, see the following documentation: User Guide for Application Load Balancers User Guide for Network Load Balancers User Guide for Gateway Load Balancers',
         'learn-networking|Elastic Load Balancing, Azure Load Balancer, and Azure Application Gateway The Azure equivalents of the Elastic Load Balancing services are:'],
        { allow: ['third'] }),
    },
  ],
};

export default notes;
