import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'serverless-mill',
  overview: [
    b('Serverless means you do not manage the servers: AWS handles infrastructure, scaling and patching. This building covers the pieces the exam names: Amazon API Gateway (the front door for APIs), AWS Lambda (functions) and AWS Fargate (containers without servers to manage).',
      ['lambda-welcome', 'apigw-welcome', 'fargate-ecs'],
      ['lambda-welcome|AWS Lambda is a serverless compute service.',
       'apigw-welcome|API Gateway acts as a "front door" for applications to access data, business logic, or functionality from your backend services',
       'fargate-ecs|With AWS Fargate, you no longer have to provision, configure, or scale clusters of virtual machines to run containers.']),
  ],
  beyondProject: [
    b('You have already built the serverless pattern: a function behind an API. The SAA-level questions are about choosing. Which API type fits (REST or HTTP), when does a function stop fitting (runtime and size limits, long-running work), and when do containers on Fargate fit better than Lambda?',
      ['apigw-http-vs-rest', 'lambda-quotas'],
      ['apigw-http-vs-rest|REST APIs support more features than HTTP APIs, while HTTP APIs are designed with minimal features so that they can be offered at a lower price.',
       'lambda-quotas|Code can run for up to 15 minutes in a single invocation']),
    b('If the API in your project is a REST API, you can use the features that HTTP APIs lack: AWS WAF integration, API keys, per-client throttling, request validation and private endpoints. If it is an HTTP API, note that it has none of those.',
      'apigw-http-vs-rest',
      ['Choose REST APIs if you need features such as API keys, per-client throttling, request validation, AWS WAF integration, or private API endpoints.']),
  ],
  bullets: [
    {
      id: '2.1-K1',
      concepts: [
        b('Amazon API Gateway is an AWS service for creating, publishing, maintaining, monitoring and securing REST, HTTP and WebSocket APIs at any scale. It handles traffic management, authorization and access control, monitoring and API version management.',
          'apigw-welcome',
          ['These tasks include traffic management, authorization and access control, monitoring, and API version management.',
           'Together with AWS Lambda, API Gateway forms the app-facing part of the AWS serverless infrastructure.']),
        b('A REST API and an HTTP API are both RESTful API products. REST APIs support more features; HTTP APIs have minimal features so that they can be offered at a lower price. Choose REST APIs if you need API keys, per-client throttling, request validation, AWS WAF integration or private API endpoints; choose HTTP APIs if you do not need those features.',
          'apigw-http-vs-rest',
          ['REST APIs and HTTP APIs are both RESTful API products.',
           'REST APIs support more features than HTTP APIs, while HTTP APIs are designed with minimal features so that they can be offered at a lower price.',
           'Choose REST APIs if you need features such as API keys, per-client throttling, request validation, AWS WAF integration, or private API endpoints.',
           'Choose HTTP APIs if you don\'t need the features included with REST APIs.']),
        b('WebSocket APIs follow the WebSocket protocol, which enables stateful, full-duplex communication between client and server, while HTTP and REST APIs are stateless.',
          'apigw-welcome',
          ['Support for stateful (WebSocket) and stateless (HTTP and REST) APIs.']),
        b('In the comparison table, only REST APIs offer edge-optimized and private endpoint types, caching and AWS WAF; resource policies are also REST only. Both types support IAM, Amazon Cognito and Lambda authorizers.',
          'apigw-http-vs-rest',
          ['Endpoint types REST API HTTP API Edge-optimized Yes No Regional Yes Yes Private Yes No',
           'Features REST API HTTP API CORS configuration Yes Yes Test invocations Yes No Caching Yes No',
           'Security features REST API HTTP API Mutual TLS authentication Yes Yes Certificates for backend authentication Yes No AWS WAF Yes No',
           'Authorization options REST API HTTP API IAM Yes Yes Resource policies Yes No Amazon Cognito Yes Yes 1 Custom authorization with an AWS Lambda function Yes Yes']),
        b('API Gateway throttles requests with a token bucket algorithm: when requests exceed the steady-state rate and burst limits it begins to throttle, and clients may receive 429 Too Many Requests responses. Usage plans let you set throttles per client.',
          'apigw-throttling',
          ['API Gateway throttles requests to your API using the token bucket algorithm, where a token counts for a request.',
           'When request submissions exceed the steady-state request rate and burst limits, API Gateway begins to throttle requests.',
           'Clients may receive 429 Too Many Requests error responses at this point.',
           'Alternatively, you can enable usage plans to set throttles on client request submissions based on specified requests rates and quotas.']),
        b('Caching a REST API stage reduces the number of calls to your endpoint and improves latency: API Gateway caches endpoint responses for a time-to-live (TTL) period and answers from the cache.',
          'apigw-caching',
          ['With caching, you can reduce the number of calls made to your endpoint and also improve the latency of requests to your API.',
           'API Gateway then responds to the request by looking up the endpoint response from the cache instead of making a request to your endpoint.']),
      ],
      services: ['Amazon API Gateway', 'AWS Lambda', 'Amazon Cognito'],
      design: [
        b('API Gateway fronts backends such as workloads on EC2, code on Lambda or any web application, and forms the app-facing part of the serverless stack with Lambda. Pair it with Cognito user pools, IAM or a Lambda authorizer for authentication.',
          'apigw-welcome',
          ['API Gateway acts as a "front door" for applications to access data, business logic, or functionality from your backend services, such as workloads running on Amazon Elastic Compute Cloud (Amazon EC2), code running on AWS Lambda, any web application, or real-time communication applications.',
           'Powerful, flexible authentication mechanisms, such as AWS Identity and Access Management policies, Lambda authorizer functions, and Amazon Cognito user pools.']),
      ],
    },
    {
      id: '2.1-K12',
      concepts: [
        b('AWS Lambda is a serverless compute service: you run code without provisioning or managing servers, and Lambda manages server maintenance, capacity provisioning, scaling and patching. You write a handler function, connect it to a trigger such as API Gateway, Amazon S3, Amazon SQS or EventBridge, and Lambda runs it.',
          'lambda-welcome',
          ['With Lambda, you can run code without provisioning or managing servers.',
           'Lambda automatically manages the underlying infrastructure – including server maintenance, capacity provisioning, scaling, and patching',
           'You write a handler function, connect it to a trigger (API Gateway, Amazon S3, Amazon SQS, EventBridge, and 200+ other AWS services), and Lambda executes it.']),
        b('Each Lambda invocation runs independently with no shared state, scaling horizontally to match demand. That is why a function is the stateless building block of the previous section.',
          'lambda-welcome',
          ['Each invocation runs independently with no shared state, scaling horizontally to match demand.']),
        b('Lambda has limits that decide whether it fits. A single invocation can run for up to 15 minutes (the function timeout is 900 seconds), and function memory is configurable from 128 MB to 10,240 MB. These are documented quotas that AWS can change; check the Lambda quotas page.',
          'lambda-quotas',
          ['Function timeout 900 seconds (15 minutes).',
           'Code can run for up to 15 minutes in a single invocation',
           'Function memory allocation 128 MB to 10,240 MB, in 1-MB increments.']),
        b('Concurrency is the number of in-flight requests your function is handling at the same time. By default an account has a concurrency limit of 1,000 concurrent executions across all functions in a Region. There are two controls: reserved concurrency and provisioned concurrency.',
          'lambda-concurrency',
          ['In Lambda, concurrency is the number of in-flight requests that your function is handling at the same time.',
           'By default, your account has a concurrency limit of 1,000 concurrent executions across all functions in a Region.',
           'There are two types of concurrency controls available: reserved concurrency and provisioned concurrency.'],
          { allow: ['two'] }),
        b('AWS Fargate runs containers without servers to manage: you no longer provision, configure or scale clusters of virtual machines. You package the application in containers, specify CPU and memory, define networking and IAM policies, and launch it. Each Fargate task has its own isolation boundary.',
          'fargate-ecs',
          ['With AWS Fargate, you no longer have to provision, configure, or scale clusters of virtual machines to run containers.',
           'When you run your tasks and services with Fargate, you package your application in containers, specify the CPU and memory requirements, define networking and IAM policies, and launch the application.',
           'Each Fargate task has its own isolation boundary and does not share the underlying kernel, CPU resources, memory resources, or elastic network interface with another task.']),
      ],
      services: ['AWS Lambda', 'AWS Fargate', 'Amazon API Gateway'],
      design: [
        b('Typical serverless pattern: API Gateway receives the request, Lambda runs the logic, and a managed data store (for example DynamoDB) holds state. Because the function is stateless and managed by AWS, every layer scales without servers to patch.',
          ['apigw-welcome', 'lambda-welcome'],
          ['apigw-welcome|Together with AWS Lambda, API Gateway forms the app-facing part of the AWS serverless infrastructure.',
           'lambda-welcome|Each invocation runs independently with no shared state, scaling horizontally to match demand.']),
      ],
    },
    {
      id: '2.1-S5',
      concepts: [
        b('Serverless is characterised by no infrastructure to provision or manage, automatic scaling by unit of consumption, a "pay for value" billing model, built-in availability and fault tolerance, and event-driven architecture. Choose it when you want those properties and the workload fits its limits.',
          'msa-whitepaper',
          ['Serverless is characterized by the following principles: No infrastructure to provision or manage Automatically scaling by unit of consumption "Pay for value" billing model Built-in availability and fault tolerance Event Driven Architecture (EDA)']),
        b('Lambda fits request-response or event-driven work such as APIs, data processing and automation. A workload that needs to run longer than a Lambda invocation allows, or that already ships as a container, points to containers (Fargate) instead.',
          ['lambda-welcome', 'lambda-quotas'],
          ['lambda-welcome|Request-response or event-driven workloads (APIs, data processing, automation)',
           'lambda-quotas|Code can run for up to 15 minutes in a single invocation']),
        b('Serverless compute requires a stateless design: once designed to be stateless you can use AWS Lambda or AWS Fargate.',
          'waf-stateless',
          ['Once designed to be stateless, you can then use serverless compute services, such as AWS Lambda or AWS Fargate.']),
      ],
      services: ['AWS Lambda', 'AWS Fargate', 'Amazon API Gateway'],
      design: [
        b('Decision cue: choose Lambda for short, event-driven or request-driven tasks with variable traffic and no desire to manage servers; Fargate when the application is containerised or needs more runtime than a function allows but you still do not want to manage instances; EC2 when you need control of the instance. (Container choices are in Container Dock.)',
          ['lambda-welcome', 'fargate-ecs'],
          ['lambda-welcome|Lambda automatically manages the underlying infrastructure – including server maintenance, capacity provisioning, scaling, and patching',
           'fargate-ecs|This removes the need to choose server types, decide when to scale your clusters, or optimize cluster packing.']),
      ],
    },
  ],
  cues: [
    cue('no servers to manage / run code in response to events', 'AWS Lambda',
      b('With Lambda you run code without provisioning or managing servers, in response to events or API calls.', 'lambda-welcome',
        ['With Lambda, you can run code without provisioning or managing servers.'])),
    cue('processing takes longer than 15 minutes', 'Not a single Lambda invocation: use Fargate/containers or split the work (for example with Step Functions)',
      b('A single Lambda invocation can run for up to 15 minutes.', 'lambda-quotas',
        ['Code can run for up to 15 minutes in a single invocation'])),
    cue('containers, but no EC2 instances to manage', 'AWS Fargate',
      b('Fargate removes the need to choose server types, decide when to scale clusters, or optimize cluster packing.', 'fargate-ecs',
        ['This removes the need to choose server types, decide when to scale your clusters, or optimize cluster packing.'])),
    cue('publish/secure/throttle an API in front of Lambda or other backends', 'Amazon API Gateway',
      b('API Gateway is the front door and handles traffic management, authorization and access control, monitoring and version management.', 'apigw-welcome',
        ['These tasks include traffic management, authorization and access control, monitoring, and API version management.'])),
    cue('API needs AWS WAF, API keys, per-client throttling, request validation or a private endpoint', 'API Gateway REST API (not HTTP API)',
      b('Those are the features AWS lists as reasons to choose REST APIs.', 'apigw-http-vs-rest',
        ['Choose REST APIs if you need features such as API keys, per-client throttling, request validation, AWS WAF integration, or private API endpoints.'])),
    cue('cheapest, minimal-feature API for a Lambda proxy', 'API Gateway HTTP API',
      b('HTTP APIs are designed with minimal features so that they can be offered at a lower price.', 'apigw-http-vs-rest',
        ['REST APIs support more features than HTTP APIs, while HTTP APIs are designed with minimal features so that they can be offered at a lower price.'])),
    cue('cache API responses to cut backend calls and latency', 'API Gateway stage cache (REST API)',
      b('Caching reduces calls to the endpoint and improves latency.', 'apigw-caching',
        ['With caching, you can reduce the number of calls made to your endpoint and also improve the latency of requests to your API.'])),
    cue('two-way, real-time communication such as chat', 'API Gateway WebSocket API',
      b('WebSocket APIs enable stateful, full-duplex communication between client and server.', 'apigw-welcome',
        ['Adhere to the WebSocket protocol, which enables stateful, full-duplex communication between client and server.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Functions',
      aws: 'AWS Lambda',
      mapping: b('The Learn compute comparison pairs AWS Lambda with Azure Functions: both provide serverless, event-driven code execution with automatic scaling.',
        ['learn-compute', 'lambda-welcome'],
        ['learn-compute|AWS Lambda Azure Functions Both services provide serverless, event-driven code execution with pay-per-execution pricing and automatic scaling.',
         'lambda-welcome|AWS Lambda is a serverless compute service.']),
      breaks: b('The Learn row calls the two equivalents, but exam questions test AWS limits and controls that the row does not cover: Lambda has a maximum invocation time and a concurrency model (reserved and provisioned concurrency) that you reason about by number of in-flight requests.',
        ['lambda-quotas', 'lambda-concurrency', 'learn-compute'],
        ['lambda-quotas|Code can run for up to 15 minutes in a single invocation',
         'lambda-concurrency|There are two types of concurrency controls available: reserved concurrency and provisioned concurrency.',
         'learn-compute|AWS Lambda Azure Functions Both services provide serverless, event-driven code execution with pay-per-execution pricing and automatic scaling.'],
        { allow: ['two'] }),
    },
    {
      concept: 'Azure API Management',
      aws: 'Amazon API Gateway',
      mapping: b('The Learn hub pairs Amazon API Gateway with Azure API Management as turnkey services for publishing APIs to internal and external customers.',
        ['learn-hub', 'apigw-welcome'],
        ['learn-hub|Amazon API Gateway Azure API Management These services provide a turnkey solution for publishing APIs to internal and external customers.',
         'apigw-welcome|These tasks include traffic management, authorization and access control, monitoring, and API version management.']),
      breaks: b('On AWS you choose between two API products inside the service, REST APIs and HTTP APIs, and the choice decides which features you get (for example AWS WAF integration and caching are REST API only). That choice has no counterpart in the Learn row.',
        ['apigw-http-vs-rest', 'learn-hub'],
        ['apigw-http-vs-rest|REST APIs support more features than HTTP APIs, while HTTP APIs are designed with minimal features so that they can be offered at a lower price.',
         'learn-hub|Amazon API Gateway Azure API Management These services provide a turnkey solution for publishing APIs to internal and external customers.'],
        { allow: ['two'] }),
    },
  ],
};

export default notes;
