import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'single-point-watch',
  overview: [
    b('A single point of failure is any one component whose failure takes the whole workload down. Removing them takes both: redundancy (a second copy in another Availability Zone behind something that detects failure and reroutes) and defensive interaction patterns (limited retries, throttling, failing fast, graceful degradation) so that one slow dependency cannot drag everything with it.',
      ['waf-multi-location', 'waf-graceful'],
      ['waf-multi-location|Distribute workload data and resources across multiple Availability Zones or, where necessary, across AWS Regions.',
       'waf-graceful|Application components should continue to perform their core function even if dependencies become unavailable.']),
  ],
  bullets: [
    {
      id: '2.2-K5',
      concepts: [
        b('Graceful degradation: application components should continue to perform their core function even if dependencies become unavailable. Turning hard dependencies into soft ones improves the availability of the system as a whole and keeps the most important functions working during failures.',
          'waf-graceful',
          ['Application components should continue to perform their core function even if dependencies become unavailable.',
           'Graceful degradation improves the availability of the system as a whole and maintains the functionality of the most important functions even during failures.']),
        b('Control and limit retries: use exponential backoff to retry at progressively longer intervals, add jitter to randomise the intervals, and limit the maximum number of retries. Backoff and jitter avoid artificial traffic spikes from unintentionally coordinated retries.',
          'waf-retries',
          ['Use exponential backoff to retry requests at progressively longer intervals between each retry.',
           'Limit the maximum number of retries.',
           'Introduce jitter between retries to randomize retry intervals.',
           'Backoff and jitter help avoid artificial traffic spikes due to unintentionally coordinated retries at common intervals.']),
        b('Throttle requests to mitigate resource exhaustion from unexpected increases in demand: requests below the throttling rate are processed and those over the limit are rejected with a message that they were throttled.',
          'waf-throttle',
          ['Throttle requests to mitigate resource exhaustion due to unexpected increases in demand.',
           'Requests below throttling rates are processed while those over the defined limit are rejected with a return message indicating the request was throttled.']),
        b('Fail fast and limit queues: when a service cannot respond successfully to a request, fail fast. Failing fast releases the resources associated with the request and lets a service that is running out of resources recover, and such systems are easier to debug. A queue can buffer requests when the rate is too high, but do not let long queue backlogs build up, because they can mean processing stale requests that a client has already given up on.',
          'waf-fail-fast',
          ['When a service is unable to respond successfully to a request, fail fast.',
           'This allows resources associated with a request to be released, and permits a service to recover if it’s running out of resources.',
           'Systems that fail fast are easier to debug and fix, and often expose issues in coding and configuration before releases are published into production.',
           'However, do not allow a buildup of long queue backlogs that can result in processing stale requests that a client has already given up on.']),
        b('Decoupling through queues, streams and workflows (see Message Quay) and idempotent mutating operations are the other distributed-system patterns the Well-Architected reliability guidance lists, so that retries and duplicates are safe.',
          ['waf-loose-coupling', 'waf-idempotent'],
          ['waf-loose-coupling|Implementing loose coupling between dependencies isolates a failure in one from impacting another.',
           'waf-idempotent|To do this, clients can issue API requests with an idempotency token, which is used whenever the request is repeated.']),
      ],
      services: ['Amazon SQS', 'Amazon API Gateway', 'AWS Step Functions'],
      design: [
        b('Match the symptom to the pattern: retry storms → backoff with jitter and a retry limit; a flood of requests → throttling (for example API Gateway throttling); a dependency that is unavailable or slow while the page can still do its core job → graceful degradation; a service that fails when the request rate is too high → a queue to buffer requests, with backlogs kept short.',
          ['waf-retries', 'waf-throttle', 'waf-graceful', 'waf-fail-fast'],
          ['waf-retries|Backoff and jitter help avoid artificial traffic spikes due to unintentionally coordinated retries at common intervals.',
           'waf-throttle|Throttle requests to mitigate resource exhaustion due to unexpected increases in demand.',
           'waf-graceful|Application components should continue to perform their core function even if dependencies become unavailable.',
           'waf-fail-fast|When a service is able to respond successfully under normal conditions but fails when the rate of requests is too high, use a queue to buffer requests.']),
      ],
    },
    {
      id: '2.2-K8',
      concepts: [
        b('A load balancer removes the single instance as a single point of failure: it distributes traffic across multiple targets in one or more Availability Zones, monitors target health, and sends requests only to healthy targets. Using one increases availability and fault tolerance. (Types and sizing are in Scaling Floodgate and Express Interchange.)',
          'elb-what-is',
          ['Elastic Load Balancing automatically distributes your incoming traffic across multiple targets, such as EC2 instances, containers, and IP addresses, in one or more Availability Zones.',
           'It monitors the health of its registered targets, and routes traffic only to the healthy targets.',
           'Using a load balancer increases the availability and fault tolerance of your applications.']),
        b('Pair the load balancer with an Auto Scaling group: EC2 Auto Scaling automatically monitors the health and availability of instances and replaces terminated or impaired instances to maintain the desired capacity, balancing instances evenly across the Availability Zones you specify.',
          'asg-what-is',
          ['Amazon EC2 Auto Scaling automatically monitors the health and availability of your instances using EC2 health checks and replaces terminated or impaired instances to maintain your desired capacity.',
           'You can specify multiple Availability Zones for your Auto Scaling group, and Amazon EC2 Auto Scaling balances your instances evenly across the Availability Zones as the group scales.']),
        b('By default an Auto Scaling group replaces only instances that are unhealthy or unreachable according to EC2 health checks. If you turn on Elastic Load Balancing health checks, the group can also replace a running instance that an attached load balancer reports as unhealthy.',
          'asg-attach-lb',
          ['By default, Amazon EC2 Auto Scaling only replaces instances that are unhealthy or unreachable based on Amazon EC2 health checks.',
           'If you turn on Elastic Load Balancing health checks, Amazon EC2 Auto Scaling can replace a running instance if any of the Elastic Load Balancing load balancers you attach to the Auto Scaling group report it as unhealthy.']),
      ],
      services: ['Elastic Load Balancing (ELB)', 'Amazon EC2 Auto Scaling'],
      design: [
        b('A load balancer and Auto Scaling group across Availability Zones gives the application tier no single instance and no single AZ failure point. The load balancer itself scales automatically in response to changes in incoming traffic.',
          'elb-what-is',
          ['Elastic Load Balancing scales your load balancer capacity automatically in response to changes in incoming traffic.']),
      ],
    },
    {
      id: '2.2-K9',
      concepts: [
        b('Amazon RDS Proxy lets applications pool and share database connections to improve their ability to scale. It establishes a database connection pool and reuses connections, so the proxy manages a smaller number of long-lived connections to the DB instance while applications open many client connections.',
          ['rds-proxy', 'rds-proxy-planning'],
          ['rds-proxy|By using Amazon RDS Proxy, you can allow your applications to pool and share database connections to improve their ability to scale.',
           'rds-proxy|RDS Proxy establishes a database connection pool and reuses connections in this pool.',
           'rds-proxy-planning|The proxy enables applications to open many client connections, while the proxy manages a smaller number of long-lived connections to the DB instance .']),
        b('RDS Proxy makes applications more resilient to database failures by automatically connecting to a standby DB instance while preserving application connections. It can also enforce IAM authentication for clients, and connect to databases using IAM database authentication or credentials stored in AWS Secrets Manager.',
          'rds-proxy',
          ['RDS Proxy makes applications more resilient to database failures by automatically connecting to a standby DB instance while preserving application connections.',
           'By using RDS Proxy, you can enforce AWS Identity and Access Management (IAM) authentication for clients connecting to the proxy, and the proxy can connect to databases using either IAM database authentication or credentials stored in AWS Secrets Manager.']),
        b('Good candidates for a proxy: any DB instance that encounters "too many connections" errors, and AWS Lambda functions, which can open many connections at once; Lambda can use IAM authentication it already has instead of database credentials in code.',
          'rds-proxy-planning',
          ['Any DB instance that encounters "too many connections" errors is a good candidate for associating with a proxy.',
           'AWS Lambda functions can also be good candidates for using a proxy.',
           'You can take advantage of any IAM authentication you already have for Lambda functions, instead of managing database credentials in your Lambda application code.']),
      ],
      services: ['Amazon RDS', 'AWS Lambda', 'AWS Secrets Manager'],
      design: [
        b('Cue pattern: Lambda or a large fleet exhausting database connections, or failovers breaking application connections → RDS Proxy. It does not replace Multi-AZ: Multi-AZ provides the standby that the proxy reconnects to.',
          ['rds-proxy', 'rds-multi-az'],
          ['rds-proxy|RDS Proxy makes applications more resilient to database failures by automatically connecting to a standby DB instance while preserving application connections.',
           'rds-multi-az|A Multi-AZ DB instance deployment has one standby DB instance that provides failover support, but doesn\'t serve read traffic.']),
      ],
    },
    {
      id: '2.2-S4',
      concepts: [
        b('Work through the tiers and ask what happens if this one thing fails: compute (instances behind a load balancer in an Auto Scaling group across AZs), database (a Multi-AZ deployment, where a standby provides failover support), connections (RDS Proxy), DNS and Regions (Route 53 health checks), and dependencies (retries, throttling, graceful degradation).',
          ['elb-what-is', 'rds-multi-az', 'route53-failover'],
          ['elb-what-is|Using a load balancer increases the availability and fault tolerance of your applications.',
           'rds-multi-az|A Multi-AZ DB instance deployment has one standby DB instance that provides failover support, but doesn\'t serve read traffic.',
           'route53-failover|Amazon Route 53 health checks monitor the health and performance of your web applications, web servers, and other resources.']),
        b('RDS Multi-AZ comes in two shapes: a Multi-AZ DB instance deployment with one standby that provides failover support but does not serve read traffic, and a Multi-AZ DB cluster deployment whose standbys provide failover support and can also serve read traffic. (The full comparison with read replicas is in Read Replica Annex.)',
          'rds-multi-az',
          ['A Multi-AZ DB instance deployment has one standby DB instance that provides failover support, but doesn\'t serve read traffic.',
           'A Multi-AZ DB cluster deployment has standby DB instances that provide failover support and can also serve read traffic.'],
          { allow: ['two'] }),
      ],
      services: ['Elastic Load Balancing (ELB)', 'Amazon RDS', 'Amazon EC2 Auto Scaling'],
      design: [
        b('A common fix: replace the single EC2 instance with an Auto Scaling group behind a load balancer across Availability Zones, and replace the single-AZ database with a Multi-AZ deployment. Route 53 failover is a further layer: with active-passive failover, a secondary resource stands by in case all the primary resources become unavailable.',
          ['asg-what-is', 'rds-multi-az', 'route53-failover-types'],
          ['asg-what-is|Amazon EC2 Auto Scaling automatically monitors the health and availability of your instances using EC2 health checks and replaces terminated or impaired instances to maintain your desired capacity.',
           'rds-multi-az|A Multi-AZ DB instance deployment has one standby DB instance that provides failover support, but doesn\'t serve read traffic.',
           'route53-failover-types|Use an active-passive failover configuration when you want a primary resource or group of resources to be available the majority of the time and you want a secondary resource or group of resources to be on standby in case all the primary resources become unavailable.']),
      ],
    },
  ],
  cues: [
    cue('too many database connections from Lambda or a large fleet', 'Amazon RDS Proxy',
      b('RDS Proxy pools and shares database connections, and Lambda functions are good candidates.', 'rds-proxy-planning',
        ['AWS Lambda functions can also be good candidates for using a proxy.'])),
    cue('applications should keep their connections during database failover', 'Amazon RDS Proxy',
      b('RDS Proxy automatically connects to a standby DB instance while preserving application connections.', 'rds-proxy',
        ['RDS Proxy makes applications more resilient to database failures by automatically connecting to a standby DB instance while preserving application connections.'])),
    cue('database must survive an Availability Zone failure', 'RDS Multi-AZ deployment',
      b('A Multi-AZ deployment includes standby instances that provide failover support.', 'rds-multi-az',
        ['A Multi-AZ DB instance deployment has one standby DB instance that provides failover support, but doesn\'t serve read traffic.'])),
    cue('retries from many clients overload a recovering service', 'Exponential backoff with jitter and a maximum retry count',
      b('Backoff and jitter avoid artificial traffic spikes from coordinated retries.', 'waf-retries',
        ['Backoff and jitter help avoid artificial traffic spikes due to unintentionally coordinated retries at common intervals.'])),
    cue('a non-critical dependency fails but the page should still load', 'Graceful degradation',
      b('Components should continue their core function even if dependencies become unavailable.', 'waf-graceful',
        ['Application components should continue to perform their core function even if dependencies become unavailable.'])),
    cue('instances the load balancer marks unhealthy should be replaced', 'Auto Scaling group with Elastic Load Balancing health checks turned on',
      b('By default the group replaces instances based on EC2 health checks only; turning on Elastic Load Balancing health checks lets it replace instances the load balancer reports as unhealthy.', 'asg-attach-lb',
        ['If you turn on Elastic Load Balancing health checks, Amazon EC2 Auto Scaling can replace a running instance if any of the Elastic Load Balancing load balancers you attach to the Auto Scaling group report it as unhealthy.'])),
    cue('replace failed instances automatically', 'EC2 Auto Scaling health checks',
      b('Auto Scaling replaces terminated or impaired instances to maintain desired capacity.', 'asg-what-is',
        ['Amazon EC2 Auto Scaling automatically monitors the health and availability of your instances using EC2 health checks and replaces terminated or impaired instances to maintain your desired capacity.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Application Gateway',
      aws: 'Application Load Balancer',
      mapping: b('Learn pairs Azure Application Gateway with the AWS Application Load Balancer for application-level rule-based routing.',
        ['learn-networking', 'alb-intro'],
        ['learn-networking|Application Gateway provides application-level rule-based routing comparable to that of the AWS Application Load Balancer.',
         'alb-intro|An Application Load Balancer functions at the application layer, the seventh layer of the Open Systems Interconnection (OSI) model.']),
      breaks: b('The Microsoft Learn comparison compares the routing function only. The availability behaviour in this building is described separately on the AWS side: the load balancer sends traffic only to healthy targets, and an Auto Scaling group replaces terminated or impaired instances.',
        ['elb-what-is', 'asg-what-is', 'learn-networking'],
        ['elb-what-is|It monitors the health of its registered targets, and routes traffic only to the healthy targets.',
         'asg-what-is|Amazon EC2 Auto Scaling automatically monitors the health and availability of your instances using EC2 health checks and replaces terminated or impaired instances to maintain your desired capacity.',
         'learn-networking|Application Gateway provides application-level rule-based routing comparable to that of the AWS Application Load Balancer.']),
    },
  ],
};

export default notes;
