import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'tide-gauges',
  overview: [
    b('You cannot keep a workload available if you cannot see it. This building covers visibility and limits: service quotas (the ceilings AWS puts on your account), tracing (where in a request the time or the errors are), and metrics (the numbers that tell you whether the availability the business asked for is being delivered).',
      ['servicequotas', 'xray', 'waf-availability'],
      ['servicequotas|Quotas, also referred to as limits in AWS services, are the maximum values for the resources, actions, and items in your AWS account.',
       'xray|AWS X-Ray is a service that collects data about requests that your application serves, and provides tools that you can use to view, filter, and gain insights into that data to identify issues and opportunities for optimization.',
       'waf-availability|Availability is the percentage of time that a workload is available for use.']),
  ],
  bullets: [
    {
      id: '2.2-K10',
      concepts: [
        b('Service quotas, also called limits, are the maximum values for the resources, actions and items in your AWS account. Each AWS service defines its quotas and default values. Service Quotas lets you look up quotas in one place and request increases; Support might approve, deny or partially approve a request.',
          'servicequotas',
          ['Quotas, also referred to as limits in AWS services, are the maximum values for the resources, actions, and items in your AWS account.',
           'Each AWS service defines its quotas and establishes default values for those quotas.',
           'Service Quotas enables you to look up your service quotas and to request increases.',
           'Support might approve, deny, or partially approve your requests.']),
        b('You can create CloudWatch alarms to notify you when you are close to a quota threshold, so a quota is raised before it causes an outage.',
          'servicequotas-cw',
          ['You can create Amazon CloudWatch alarms to notify you when you\'re close to a quota value threshold.']),
        b('Standby and multi-Region environments need their own quotas. If you use multiple accounts or Regions, request the appropriate quotas in all environments where production workloads run, so failover to another Region or account is not blocked by quota exhaustion. Quota drift, where a limit is changed in one Region and not in all, is important to track.',
          'waf-quotas-regions',
          ['If you are using multiple accounts or Regions, request the appropriate quotas in all environments in which your production workloads run.',
           'Desired outcome: Services and applications should not be affected by service quota exhaustion for configurations that span accounts or Regions or that have resilience designs using zone, Region, or account failover.',
           'Service quota drift, the condition where service quota limits for a specific named quota is changed in one Region and not all Regions, is very important to track and assess.']),
        b('Failover tests are often not scaled to peak capacity, so exercises can fail to find quota differences between Regions. Plan for the passive Region to be able to take the full load.',
          'waf-quotas-regions',
          ['The testing plans of passive Region failovers are rarely scaled to peak active capacity, meaning that game day or table top exercises can fail to find differences in service quotas between Regions and also then maintain the correct limits.']),
        b('Throttling is a service protecting itself by rejecting requests over a rate. API Gateway throttles with a token bucket and answers 429 Too Many Requests when the rate and burst limits are exceeded; Lambda has an account concurrency limit across functions in a Region with reserved and provisioned concurrency controls. Both are covered in Serverless Mill.',
          ['apigw-throttling', 'lambda-concurrency'],
          ['apigw-throttling|Clients may receive 429 Too Many Requests error responses at this point.',
           'lambda-concurrency|By default, your account has a concurrency limit of 1,000 concurrent executions across all functions in a Region.']),
        b('AWS Trusted Advisor inspects your AWS environment and recommends where to save money, improve availability and performance, or close security gaps. With the Basic Support plan you can use the console to access all checks in the Service Limits category and selected checks in the Security and Fault tolerance categories.',
          'trusted-advisor',
          ['Trusted Advisor inspects your AWS environment, and then makes recommendations when opportunities exist to save money, improve system availability and performance, or help close security gaps.',
           'If you have a Basic Support plan, you can use the Trusted Advisor console to access all checks in the Service Limits category and selected checks in the Security and Fault tolerance categories.']),
      ],
      services: ['AWS Trusted Advisor', 'Amazon API Gateway', 'Amazon CloudWatch'],
      design: [
        b('A launch, load test or failover that fails with a limit error although nothing is mis-configured points to a service quota: check and raise it in that Region (and in the standby Region). A "Too Many Requests" throttling error from an API points to the request rate: slow retries down with exponential backoff (see Single Point Watch).',
          ['servicequotas', 'waf-quotas-regions', 'apigw-throttling', 'waf-retries'],
          ['servicequotas|If your business needs aren\'t met by the default limit of service resources or operations that apply to an AWS account, resource, or an AWS Region, you might need to increase your service quota values.',
           'waf-quotas-regions|Services and applications should not be affected by service quota exhaustion for configurations that span accounts or Regions or that have resilience designs using zone, Region, or account failover.',
           'apigw-throttling|Clients may receive 429 Too Many Requests error responses at this point.',
           'waf-retries|Use exponential backoff to retry requests at progressively longer intervals between each retry.']),
      ],
    },
    {
      id: '2.2-K12',
      concepts: [
        b('AWS X-Ray collects data about the requests your application serves and gives you tools to view, filter and gain insights into that data. For any traced request you can see detail about the request and response, and about calls your application makes to downstream AWS resources, microservices, databases and web APIs.',
          'xray',
          ['AWS X-Ray is a service that collects data about requests that your application serves, and provides tools that you can use to view, filter, and gain insights into that data to identify issues and opportunities for optimization.',
           'For any traced request to your application, you can see detailed information not only about the request and response, but also about calls that your application makes to downstream AWS resources, microservices, databases, and web APIs.']),
        b('X-Ray builds a trace map from the data, which you use to identify bottlenecks, latency spikes and other issues. Instrumenting your application means sending trace data for incoming and outbound requests; integrated AWS services can add tracing headers and send trace data themselves.',
          'xray',
          ['Use the trace map to identify bottlenecks, latency spikes, and other issues to solve to improve the performance of your applications.',
           'Instrumenting your application involves sending trace data for incoming and outbound requests and other events within your application, along with metadata about each request.',
           'AWS services that are integrated with X-Ray can add tracing headers to incoming requests, send trace data to X-Ray, or run the X-Ray daemon.']),
        b('Monitor all components of the workload, including the front-end, business logic and storage tiers, with Amazon CloudWatch or third-party tools: define key metrics, and set thresholds for invoking alarms.',
          'waf-monitor-components',
          ['All components of your workload should be monitored, including the front-end, business logic, and storage tiers.',
           'Define key metrics, describe how to extract them from logs (if necessary), and set thresholds for invoking corresponding alarm events.']),
        b('CloudWatch, CloudTrail and AWS Config answer different questions. CloudWatch collects metrics and sets alarms on them against thresholds (how is it performing). CloudTrail records actions taken by a user, role or AWS service as events, including actions in the console, CLI and SDKs (who did what). AWS Config provides a detailed view of how AWS resources are configured and how that changed over time (what changed, and does the configuration comply).',
          ['cw-what-is', 'cloudtrail-what-is', 'config-what-is'],
          ['cw-what-is|Operational visibility with metrics, alarms, and dashboards Metrics collect and track key performance data at user-defined intervals.',
           'cw-what-is|You can set up alarms that continuously monitor CloudWatch metrics against user-defined thresholds.',
           'cloudtrail-what-is|Actions taken by a user, role, or an AWS service are recorded as events in CloudTrail.',
           'cloudtrail-what-is|Events include actions taken in the AWS Management Console, AWS Command Line Interface, and AWS SDKs and APIs.',
           'config-what-is|AWS Config provides a detailed view of the configuration of AWS resources in your AWS account.',
           'config-what-is|This includes how the resources are related to one another and how they were configured in the past so that you can see how the configurations and relationships change over time.',
           'config-what-is|You can use AWS Config rules to evaluate the configuration settings of your AWS resources.']),
      ],
      services: ['AWS X-Ray', 'Amazon CloudWatch', 'AWS CloudTrail', 'AWS Config'],
      design: [
        b('Use CloudWatch to know that something is wrong (metrics, alarms, logs), and X-Ray to find where in a distributed request the latency or errors arise.',
          ['cw-what-is', 'xray'],
          ['cw-what-is|Operational visibility with metrics, alarms, and dashboards',
           'xray|Use the trace map to identify bottlenecks, latency spikes, and other issues to solve to improve the performance of your applications.']),
      ],
    },
    {
      id: '2.2-S3',
      concepts: [
        b('Availability is the percentage of time that a workload is available for use, calculated over a period such as a month or year; "five nines" is shorthand for 99.999% available. Pick metrics that show the business requirement being met, then alarm on them.',
          'waf-availability',
          ['Availability is the percentage of time that a workload is available for use.',
           'This percentage is calculated over a period of time, such as a month, year, or trailing three years.',
           'Common short-hand refers only to the “number of nines”; for example, “five nines” translates to being 99.999% available'],
          { allow: ['five', 'three'] }),
        b('For load balanced applications, the Application Load Balancer publishes HealthyHostCount and UnHealthyHostCount, the numbers of targets considered healthy and unhealthy. AWS recommends monitoring for a non-zero UnHealthyHostCount and alarming on a non-zero value for more than one data point.',
          'alb-metrics',
          ['Dimensions TargetGroup, LoadBalancer TargetGroup, AvailabilityZone, LoadBalancer HealthyHostCount The number of targets that are considered healthy.',
           'We recommend you monitor for non-zero UnHealthyHostCount in the Minimum statistic, and alarm on non-zero value for more than one data point.']),
        b('Alarms turn metrics into notifications: configure relevant alarms based on service and application metrics so operational events get a rapid response.',
          'waf-monitor-components',
          ['Define key metrics, describe how to extract them from logs (if necessary), and set thresholds for invoking corresponding alarm events.']),
      ],
      services: ['Amazon CloudWatch', 'Elastic Load Balancing (ELB)'],
      design: [
        b('A common monitoring setup: alarm on the load balancer\'s target health (UnHealthyHostCount) and on quota usage, and use X-Ray when the need is to locate a slow dependency in a request.',
          ['alb-metrics', 'servicequotas-cw', 'xray'],
          ['alb-metrics|We recommend you monitor for non-zero UnHealthyHostCount in the Minimum statistic, and alarm on non-zero value for more than one data point.',
           'servicequotas-cw|You can create Amazon CloudWatch alarms to notify you when you\'re close to a quota value threshold.',
           'xray|Use the trace map to identify bottlenecks, latency spikes, and other issues to solve to improve the performance of your applications.']),
      ],
    },
  ],
  cues: [
    cue('cannot launch more instances / limit exceeded error', 'Service Quotas: check the quota and request an increase',
      b('Service Quotas lets you look up quotas and request increases.', 'servicequotas',
        ['Service Quotas enables you to look up your service quotas and to request increases.'])),
    cue('standby Region must be able to take the full load', 'Request matching quotas in the standby Region',
      b('Request the appropriate quotas in all environments in which production workloads run.', 'waf-quotas-regions',
        ['If you are using multiple accounts or Regions, request the appropriate quotas in all environments in which your production workloads run.'])),
    cue('find which downstream call is slow in a distributed request', 'AWS X-Ray',
      b('X-Ray traces calls to downstream AWS resources, microservices, databases and web APIs.', 'xray',
        ['For any traced request to your application, you can see detailed information not only about the request and response, but also about calls that your application makes to downstream AWS resources, microservices, databases, and web APIs.'])),
    cue('who made this API call / who changed this setting', 'AWS CloudTrail',
      b('CloudTrail records actions taken by a user, role or AWS service as events.', 'cloudtrail-what-is',
        ['Actions taken by a user, role, or an AWS service are recorded as events in CloudTrail.'])),
    cue('track how a resource configuration changed over time / evaluate against rules', 'AWS Config',
      b('AWS Config shows how resources were configured in the past and evaluates them with rules.', 'config-what-is',
        ['This includes how the resources are related to one another and how they were configured in the past so that you can see how the configurations and relationships change over time.',
         'You can use AWS Config rules to evaluate the configuration settings of your AWS resources.'])),
    cue('alert when a metric crosses a threshold', 'Amazon CloudWatch alarm',
      b('Define key metrics and set thresholds for invoking alarm events.', 'waf-monitor-components',
        ['Define key metrics, describe how to extract them from logs (if necessary), and set thresholds for invoking corresponding alarm events.'])),
    cue('recommendations across cost, performance, fault tolerance, security and service limits', 'AWS Trusted Advisor',
      b('Trusted Advisor makes recommendations to save money, improve availability and performance, or close security gaps.', 'trusted-advisor',
        ['Trusted Advisor inspects your AWS environment, and then makes recommendations when opportunities exist to save money, improve system availability and performance, or help close security gaps.'])),
    cue('number of unhealthy targets behind a load balancer', 'ALB UnHealthyHostCount metric',
      b('UnHealthyHostCount is the number of targets considered unhealthy.', 'alb-metrics',
        ['Dimensions LoadBalancer AvailabilityZone, LoadBalancer TargetGroup, LoadBalancer TargetGroup, AvailabilityZone, LoadBalancer UnHealthyHostCount The number of targets that are considered unhealthy.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Monitor (Application Insights)',
      aws: 'Amazon CloudWatch and AWS X-Ray',
      mapping: b('Learn pairs CloudWatch and X-Ray with Azure Monitor, and says to use Application Insights, a feature of Azure Monitor, to instrument your code for in-depth application performance monitoring. That is the role X-Ray plays on AWS.',
        ['learn-hub', 'xray'],
        ['learn-hub|Use Application Insights, a feature of Azure Monitor, to instrument your code for more in-depth application performance monitoring.',
         'learn-hub|In AWS, you typically use both X-Ray and CloudWatch.',
         'xray|Instrumenting your application involves sending trace data for incoming and outbound requests and other events within your application, along with metadata about each request.']),
      breaks: b('Learn pairs both AWS services with the one Azure service, Azure Monitor. On AWS the jobs sit in two services: CloudWatch collects metrics and sets alarms on them, and X-Ray traces requests.',
        ['xray', 'cw-what-is', 'learn-hub'],
        ['xray|Use the trace map to identify bottlenecks, latency spikes, and other issues to solve to improve the performance of your applications.',
         'cw-what-is|You can set up alarms that continuously monitor CloudWatch metrics against user-defined thresholds.',
         'learn-hub|DevOps and application monitoring AWS service Azure service Description Amazon CloudWatch and AWS X-Ray Azure Monitor'],
        { allow: ['two'] }),
    },
    {
      concept: 'Azure Advisor',
      aws: 'AWS Trusted Advisor',
      mapping: b('Learn pairs AWS Trusted Advisor with Azure Advisor: analysis of resource configuration to help you use best practices. Learn lists the Trusted Advisor check categories as cost optimization, security, performance, fault tolerance and service limits.',
        ['learn-compute', 'trusted-advisor'],
        ['learn-compute|AWS Trusted Advisor Azure Advisor AWS Trusted Advisor provides checks across cost optimization, security, performance, fault tolerance, and service limits.',
         'trusted-advisor|Trusted Advisor inspects your AWS environment, and then makes recommendations when opportunities exist to save money, improve system availability and performance, or help close security gaps.']),
      breaks: b('Learn describes Azure Advisor as covering the same pillars in a single integrated experience. On the AWS side, the Trusted Advisor checks you can see depend on your AWS Support plan: with Basic Support you get the Service Limits category and selected Security and Fault tolerance checks.',
        ['trusted-advisor', 'learn-compute'],
        ['trusted-advisor|If you have a Basic Support plan, you can use the Trusted Advisor console to access all checks in the Service Limits category and selected checks in the Security and Fault tolerance categories.',
         'learn-compute|Azure Advisor covers the same pillars in a single integrated experience.']),
    },
  ],
};

export default notes;
