import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'cache-pavilion',
  overview: [
    b('A database cache keeps frequently read data in memory so the database answers fewer queries. Cache & Edge Breakwater explained where caches sit and the lazy-loading and write-through strategies. This building is about picking the caching service for a database: ElastiCache for general database caching, DAX for DynamoDB, and MemoryDB when the in-memory store must itself be the durable database.',
      ['elasticache-what-is', 'dax', 'memorydb'],
      ['elasticache-what-is|Amazon ElastiCache is a web service that makes it easy to set up, manage, and scale a distributed in-memory data store or cache environment in the cloud.',
       'dax|DAX is a DynamoDB-compatible caching service that enables you to benefit from fast in-memory performance for demanding applications.',
       'memorydb|Amazon MemoryDB is a durable, in-memory database service that delivers ultra-fast performance.']),
  ],
  bullets: [
    {
      id: '3.3-K2',
      concepts: [
        b('ElastiCache is an in-memory key-value store that sits between your application and the data store it accesses. Whenever the application requests data, it first asks the cache; on a miss it reads the database and populates the cache (lazy loading), and writes can update the cache too (write-through).',
          'elasticache-strategies',
          ['Amazon ElastiCache is an in-memory key-value store that sits between your application and the data store (database) that it accesses.',
           'A cache miss occurs when data isn\'t in the cache or is expired:']),
        b('ElastiCache supports the Valkey, Memcached and Redis OSS engines, and each is an in-memory key-value store. Choose Memcached for the simplest model, large nodes with multiple cores or threads, the ability to scale out and in by adding and removing nodes, and caching objects. In AWS\'s comparison table, Memcached has no replication, automatic failover, Pub/Sub or sorted sets, while Valkey and Redis OSS offer them. That table lists durability (through a Multi-AZ transactional log) only for cluster-mode-enabled ElastiCache for Valkey 9.0 and later; MemoryDB, below, is the service built to be a durable primary database.',
          'elasticache-engines',
          ['Amazon ElastiCache supports the Valkey, Memcached, and Redis OSS cache engines.',
           'Each of them is an in-memory key-value store.',
           'Choose Memcached if the following apply for you: You need the simplest model possible. You need to run large nodes with multiple cores or threads. You need the ability to scale out and in, adding and removing nodes as demand on your system increases and decreases. You need to cache objects.',
           'High availability (replication) No Yes Yes Automatic failover No Optional Required Pub/Sub capabilities No Yes Yes Sorted sets No Yes Yes',
           'Durability No No Valkey 9.0 and later (sync/async)']),
        b('Amazon DynamoDB Accelerator (DAX) is a DynamoDB-compatible caching service that is API-compatible with DynamoDB, so it needs only minimal functional changes to use with an existing application. It reduces response times of eventually consistent reads from single-digit milliseconds to microseconds. A request that specifies strongly consistent reads is passed through to DynamoDB, so DAX does not speed those up. For read-heavy or bursty workloads it can reduce the need to overprovision read capacity units.',
          ['dax', 'dax-concepts'],
          ['dax-concepts|If the request specifies strongly consistent reads, DAX passes the request through to DynamoDB.',
           'DAX reduces operational and application complexity by providing a managed service that is API-compatible with DynamoDB.',
           'Therefore, it requires only minimal functional changes to use with an existing application.',
           'For read-heavy or bursty workloads, DAX provides increased throughput and potential operational cost savings by reducing the need to overprovision read capacity units.']),
        b('Amazon MemoryDB is a durable, in-memory database compatible with Valkey and Redis OSS: all data is stored in memory for microsecond reads and single-digit millisecond writes, and stored durably across multiple Availability Zones using a Multi-AZ transactional log. It can be a high-performance primary database, eliminating the need to manage a separate cache and durable database.',
          'memorydb',
          ['Amazon MemoryDB is a durable, in-memory database service that delivers ultra-fast performance.',
           'With MemoryDB, all of your data is stored in memory, which enables you to achieve microsecond read and single-digit millisecond write latency and high throughput.',
           'MemoryDB also stores data durably across multiple Availability Zones (AZs) using a Multi-AZ transactional log to enable fast failover, database recovery, and node restarts.']),
      ],
      services: ['Amazon ElastiCache', 'Amazon DynamoDB'],
      design: [
        b('Cue to service: cache in front of RDS or Aurora, session store → ElastiCache; DynamoDB reads need microsecond latency with little code change → DAX; Redis-compatible data that must not be lost → MemoryDB.',
          'database-decision',
          ['If your workload requires extremely high read performance with a response time measured in microseconds (rather than single-digit milliseconds), you might want to consider using in- memory caching solutions such as Amazon ElastiCache alongside your database, or a fully durable, persistent in-memory database such as Amazon MemoryDB.']),
      ],
    },
    {
      id: '3.3-S5',
      concepts: [
        b('Integrate the cache by deciding what to cache and how to keep it fresh. Lazy loading caches only requested data and tolerates node failures, but a miss costs three trips and the data can go stale; write-through keeps the cache current but caches data that may never be read; adding a time to live (TTL) value can minimize wasted space.',
          'elasticache-strategies',
          ['The advantages of lazy loading are as follows: Only requested data is cached.',
           'Each cache miss results in three trips: Initial request for data from the cacheQuery of the database for the dataWriting the data to the cache',
           'The advantages of write-through are as follows: Data in the cache is never stale.',
           'By adding a time to live (TTL) value, you can minimize wasted space.']),
        b('ElastiCache offers serverless caching, which eliminates the need to provision instances or configure nodes or clusters. For these serverless caches, reading from replicas can significantly improve performance compared with reading only from the primary cache node.',
          ['elasticache-what-is', 'elasticache-strategies'],
          ['elasticache-what-is|ElastiCache Serverless enables you to create a highly available cache in under a minute, and eliminates the need to provision instances or configure nodes or clusters.',
           'elasticache-strategies|You can often significantly improve performance for ElastiCache serverless caches by reading from replicas instead of the primary cache node.']),
        b('DAX write operations (BatchWriteItem, UpdateItem, DeleteItem and PutItem) are write-through: the data is first written to the DynamoDB table and then to the DAX cluster, so writes still go to DynamoDB. DAX also supports server-side encryption.',
          ['dax-concepts', 'dax'],
          ['dax-concepts|Write operations The following DAX API operations are considered "write-through": BatchWriteItem UpdateItem DeleteItem PutItem With these operations, data is first written to the DynamoDB table, and then to the DAX cluster.',
           'dax|DAX supports server-side encryption.']),
      ],
      services: ['Amazon ElastiCache', 'Amazon DynamoDB'],
      design: [
        b('Cue: read-heavy database, results rarely change → cache with a TTL; data must never be stale → write-through; cache must survive restarts as the system of record → MemoryDB rather than a cache.',
          ['elasticache-strategies', 'memorydb'],
          ['elasticache-strategies|The advantages of write-through are as follows: Data in the cache is never stale.',
           'memorydb|Amazon MemoryDB is a durable, in-memory database service that delivers ultra-fast performance.']),
      ],
    },
  ],
  cues: [
    cue('cache for RDS/Aurora queries, session store, Redis- or Memcached-compatible', 'Amazon ElastiCache',
      b('ElastiCache is a managed in-memory data store or cache that works with Valkey, Memcached and Redis OSS.', 'elasticache-what-is',
        ['NoteAmazon ElastiCache works with the Valkey, Memcached, and Redis OSS engines.'])),
    cue('simple object cache, multithreaded nodes, scale out by adding nodes', 'ElastiCache for Memcached',
      b('Choose Memcached for the simplest model, large multi-core nodes, scaling by adding nodes and caching objects.', 'elasticache-engines',
        ['Choose Memcached if the following apply for you: You need the simplest model possible. You need to run large nodes with multiple cores or threads. You need the ability to scale out and in, adding and removing nodes as demand on your system increases and decreases. You need to cache objects.'])),
    cue('DynamoDB reads must be served in microseconds with minimal code changes', 'DynamoDB Accelerator (DAX)',
      b('DAX is API-compatible with DynamoDB so it needs only minimal functional changes.', 'dax',
        ['Therefore, it requires only minimal functional changes to use with an existing application.'])),
    cue('in-memory store that must be durable, used as the primary database', 'Amazon MemoryDB',
      b('MemoryDB stores data durably across multiple Availability Zones using a Multi-AZ transactional log.', 'memorydb',
        ['MemoryDB also stores data durably across multiple Availability Zones (AZs) using a Multi-AZ transactional log to enable fast failover, database recovery, and node restarts.'])),
    cue('reduce over-provisioned DynamoDB read capacity for repeated reads of the same keys', 'DAX',
      b('DAX can reduce the need to overprovision read capacity units for read-heavy or bursty workloads.', 'dax',
        ['For read-heavy or bursty workloads, DAX provides increased throughput and potential operational cost savings by reducing the need to overprovision read capacity units.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Managed Redis',
      aws: 'Amazon ElastiCache',
      mapping: b('Learn pairs ElastiCache with Azure Managed Redis, a managed service based on Redis Enterprise for caching, sessions, messaging and other low-latency temporary-data patterns.',
        ['learn-databases', 'elasticache-what-is'],
        ['learn-databases|For in-memory caching and temporary data, Azure Managed Redis provides a managed service based on Redis Enterprise.',
         'learn-databases|Use Azure Managed Redis for caching, sessions, messaging, and other low-latency temporary-data patterns.',
         'elasticache-what-is|Amazon ElastiCache is a web service that makes it easy to set up, manage, and scale a distributed in-memory data store or cache environment in the cloud.']),
      breaks: b('Learn says not to use Azure Managed Redis as the authoritative persistent database for a workload, and lists no direct Azure equivalent for Amazon MemoryDB. On AWS, the choice between ElastiCache (cache) and MemoryDB (durable database) is itself an exam topic, and DAX is a third option specific to DynamoDB.',
        ['learn-databases', 'memorydb', 'dax'],
        ['learn-databases|Don\'t use it as the authoritative persistent database for a workload.',
         'learn-databases|Durable Redis-compatible database Amazon MemoryDB No direct equivalent Amazon MemoryDB is designed as a durable primary database.',
         'memorydb|Amazon MemoryDB is a durable, in-memory database service that delivers ultra-fast performance.',
         'dax|DAX is a DynamoDB-compatible caching service that enables you to benefit from fast in-memory performance for demanding applications.'],
        { allow: ['third'] }),
    },
  ],
};

export default notes;
