import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'container-yard',
  overview: [
    b('Serverless Mill and Container Dock introduced Lambda, Fargate, ECS and EKS. This building is about how they perform under load: how a function avoids cold starts and how many copies of it run, and how container services add and remove tasks or nodes automatically.',
      ['lambda-provisioned', 'ecs-autoscaling'],
      ['lambda-provisioned|Provisioned concurrency is useful for reducing cold start latencies for functions and designed to make functions available with double-digit millisecond response times.',
       'ecs-autoscaling|Automatic scaling is the ability to increase or decrease the desired number of tasks in your Amazon ECS service automatically.']),
  ],
  beyondProject: [
    b('Your Lambda function works, so the SAA-level questions are about load: Lambda concurrency is the number of in-flight requests your function is handling at once, and two controls shape it. Reserved concurrency sets both the maximum and the minimum number of concurrent instances allocated to a function, so it reserves capacity for the function and also caps it. Provisioned concurrency keeps pre-initialised execution environments ready to respond immediately, which is how you reduce cold-start latency.',
      ['lambda-reserved', 'lambda-provisioned'],
      ['lambda-reserved|In Lambda, concurrency is the number of in-flight requests that your function is currently handling.',
       'lambda-reserved|Reserved concurrency – This sets both the maximum and minimum number of concurrent instances allocated to your function.',
       'lambda-provisioned|Provisioned concurrency – This is the number of pre-initialized execution environments allocated to your function.'],
      { allow: ['two'] }),
  ],
  bullets: [
    {
      id: '3.2-K5',
      concepts: [
        b('Lambda runs each invocation independently and scales horizontally to match demand. By default the account has a total concurrency limit of 1,000 concurrent executions across all functions in a Region, and reserved concurrency dedicates part of it to one function so that no other function can use it; functions without reserved concurrency share the remaining pool.',
          ['lambda-welcome', 'lambda-concurrency'],
          ['lambda-welcome|Each invocation runs independently with no shared state, scaling horizontally to match demand.',
           'lambda-concurrency|By default, Lambda provides your account with a total concurrency limit of 1,000 concurrent executions across all functions in an AWS Region.',
           'lambda-concurrency|When you dedicate reserved concurrency to a function, no other function can use that concurrency.',
           'lambda-concurrency|Functions that don\'t have reserved concurrency share the remaining pool of unreserved concurrency.']),
        b('Provisioned concurrency is useful for reducing cold start latencies, with interactive workloads (web and mobile applications) benefiting most, while asynchronous workloads such as data processing pipelines are often less latency sensitive and do not usually need it. Configuring provisioned concurrency incurs additional charges; reserved concurrency has no charge.',
          ['lambda-provisioned', 'lambda-concurrency'],
          ['lambda-provisioned|Provisioned concurrency is useful for reducing cold start latencies for functions and designed to make functions available with double-digit millisecond response times.',
           'lambda-provisioned|Generally, interactive workloads benefit the most from the feature.',
           'lambda-provisioned|Asynchronous workloads, such as data processing pipelines, are often less latency sensitive and so do not usually need provisioned concurrency.',
           'lambda-concurrency|There is no charge for configuring reserved concurrency for a function.',
           'lambda-provisioned|Configuring provisioned concurrency incurs additional charges to your AWS account.']),
        b('Lambda SnapStart is the other cold start option: Lambda initialises your function when you publish a function version and takes a snapshot of the initialised execution environment, which can bring startup down to as low as sub-second. SnapStart supports the Java 11 and later, Python 3.12 and later, and .NET 8 and later managed runtimes, and for Java managed runtimes there is no additional cost for SnapStart.',
          'lambda-snapstart',
          ['Lambda SnapStart can provide as low as sub-second startup performance, typically with no changes to your function code.',
           'SnapStart supports the following Lambda managed runtimes and the corresponding AWS Lambda base images across ZIP and container image deployment format: Java 11 and later Python 3.12 and later .NET 8 and later.',
           'For Java managed runtimes, there\'s no additional cost for SnapStart.']),
        b('Fargate removes the need to choose server types, decide when to scale clusters or optimise cluster packing, and each task has its own isolation boundary.',
          'fargate-ecs',
          ['This removes the need to choose server types, decide when to scale your clusters, or optimize cluster packing.',
           'Each Fargate task has its own isolation boundary and does not share the underlying kernel, CPU resources, memory resources, or elastic network interface with another task.']),
      ],
      services: ['AWS Lambda', 'AWS Fargate'],
      design: [
        b('Cue: first requests are slow after idle periods → provisioned concurrency; a critical function must always have capacity, or one function must be capped → reserved concurrency; functions throttled during a spike → the account concurrency limit, which you can ask to have raised.',
          ['lambda-provisioned', 'lambda-reserved', 'lambda-concurrency'],
          ['lambda-provisioned|Provisioned concurrency is useful for reducing cold start latencies for functions and designed to make functions available with double-digit millisecond response times.',
           'lambda-reserved|Reserved concurrency is useful for ensuring that your most critical functions always have enough concurrency to handle incoming requests.',
           'lambda-reserved|Reserved concurrency – This sets both the maximum and minimum number of concurrent instances allocated to your function.',
           'lambda-concurrency|To support your specific account needs, you can request a quota increase and configure function-level concurrency controls so that your critical functions don\'t experience throttling.']),
      ],
    },
    {
      id: '3.2-K6',
      concepts: [
        b('Amazon ECS service auto scaling increases or decreases the desired number of tasks automatically, using Application Auto Scaling. ECS publishes CloudWatch metrics with your service\'s average CPU and memory usage, which you can use to scale out at peak times and scale in to reduce cost when utilisation is low.',
          'ecs-autoscaling',
          ['Automatic scaling is the ability to increase or decrease the desired number of tasks in your Amazon ECS service automatically.',
           'Amazon ECS leverages the Application Auto Scaling service to provide this functionality.',
           'You can use these and other CloudWatch metrics to scale out your service (add more tasks) to deal with high demand at peak times, and to scale in your service (run fewer tasks) to reduce costs during periods of low utilization.']),
        b('ECS service auto scaling supports scaling to a target metric value (like a thermostat), scaling by step adjustments that vary with the size of a CloudWatch alarm breach, and scheduled actions.',
          'ecs-autoscaling',
          ['Use a target metric to scale Amazon ECS services— Increase or decrease the number of tasks that your service runs based on a target value for a specific metric.',
           'Use predefined increments based on CloudWatch alarms to scale Amazon ECS services— Increase or decrease the number of tasks that your service runs based on a set of scaling adjustments, known as step adjustments, that vary based on the size of the alarm breach.']),
        b('On Amazon EKS, autoscaling is a major Kubernetes function. EKS Auto Mode automatically scales cluster compute resources: if a pod cannot fit onto existing nodes, it creates a new one, and it also consolidates workloads and deletes nodes. It builds upon Karpenter, and EKS also supports Cluster Autoscaler.',
          'eks-autoscaling',
          ['Autoscaling is a function that automatically scales your resources out and in to meet changing demands.',
           'EKS Auto Mode Amazon EKS Auto Mode automatically scales cluster compute resources.',
           'If a pod can’t fit onto existing nodes, EKS Auto Mode creates a new one.',
           'EKS Auto Mode builds upon Karpenter.']),
      ],
      services: ['Amazon ECS', 'Amazon EKS', 'AWS Fargate'],
      design: [
        b('Cue: scale the number of containers (ECS tasks) with load → ECS service auto scaling; scale Kubernetes worker capacity as pods are added → EKS Auto Mode, Karpenter or Cluster Autoscaler; no choosing server types or scaling clusters yourself → Fargate.',
          ['ecs-autoscaling', 'eks-autoscaling', 'fargate-ecs'],
          ['fargate-ecs|This removes the need to choose server types, decide when to scale your clusters, or optimize cluster packing.',
           'ecs-autoscaling|Automatic scaling is the ability to increase or decrease the desired number of tasks in your Amazon ECS service automatically.',
           'eks-autoscaling|If a pod can’t fit onto existing nodes, EKS Auto Mode creates a new one.']),
      ],
    },
  ],
  cues: [
    cue('first request after idle is slow (cold start) for a latency-sensitive API', 'Lambda provisioned concurrency',
      b('Provisioned concurrency reduces cold start latencies; interactive workloads benefit most.', 'lambda-provisioned',
        ['Provisioned concurrency is useful for reducing cold start latencies for functions and designed to make functions available with double-digit millisecond response times.'])),
    cue('guarantee or cap the concurrent executions of one function', 'Lambda reserved concurrency',
      b('Reserved concurrency sets both the maximum and the minimum number of concurrent instances for a function and dedicates them to it.', 'lambda-reserved',
        ['Reserved concurrency – This sets both the maximum and minimum number of concurrent instances allocated to your function.'])),
    cue('add or remove ECS tasks automatically based on CPU or memory', 'ECS service auto scaling (Application Auto Scaling)',
      b('ECS publishes CPU and memory metrics used to scale a service out and in.', 'ecs-autoscaling',
        ['You can use these and other CloudWatch metrics to scale out your service (add more tasks) to deal with high demand at peak times, and to scale in your service (run fewer tasks) to reduce costs during periods of low utilization.'])),
    cue('Kubernetes pods cannot be scheduled for lack of nodes', 'EKS Auto Mode / Karpenter / Cluster Autoscaler',
      b('EKS Auto Mode creates a new node if a pod cannot fit onto existing nodes.', 'eks-autoscaling',
        ['If a pod can’t fit onto existing nodes, EKS Auto Mode creates a new one.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Kubernetes Service (AKS)',
      aws: 'Amazon EKS',
      mapping: b('Learn pairs AKS with Amazon EKS and notes AKS has two modes, AKS Standard for full control and customisation and AKS Automatic for simplified, production-ready deployments. EKS has a comparable split between standard EKS and EKS Auto Mode.',
        ['learn-compute', 'eks-what-is'],
        ['learn-compute|Azure Kubernetes Service (AKS) provides two modes: AKS Standard for full control and customization and AKS Automatic for simplified, production-ready deployments with built-in best practices.',
         'eks-what-is|Choose between standard EKS or fully automated EKS Auto Mode'],
        { allow: ['two'] }),
      breaks: b('On the AWS side, EKS Auto Mode builds on Karpenter to scale cluster compute resources. Learn pairs Amazon EKS with AKS for orchestrating containerized deployments with Kubernetes, and pairs AWS Auto Scaling with Azure virtual machine scale sets and App Service autoscaling; Karpenter has no Learn pairing.',
        ['eks-autoscaling', 'learn-compute'],
        ['eks-autoscaling|EKS Auto Mode builds upon Karpenter.',
         'learn-compute|AWS service Azure service Description AWS Auto Scaling Azure Virtual Machine Scale Sets, Azure App Service autoscaling',
         'learn-compute|Amazon Elastic Kubernetes Service (Amazon EKS) Azure Kubernetes Service (AKS) You can use Amazon EKS and Azure Kubernetes Service (AKS) to orchestrate Docker containerized application deployments with Kubernetes.']),
    },
    {
      concept: 'Azure Container Apps',
      aws: 'Amazon ECS (and AWS Fargate)',
      mapping: b('Learn pairs Amazon ECS and AWS Fargate with Azure Container Apps, a managed container platform that provides built-in scaling, service discovery and traffic management.',
        ['learn-compute', 'ecs-autoscaling'],
        ['learn-compute|Azure Container Apps is a managed container platform that provides built-in scaling, service discovery, and traffic management.',
         'ecs-autoscaling|Automatic scaling is the ability to increase or decrease the desired number of tasks in your Amazon ECS service automatically.']),
      breaks: b('Learn lists AWS Fargate against two Azure services, Azure Container Instances and Azure Container Apps, while it pairs ECS with Container Apps alone. On AWS, Fargate is one serverless compute engine that you use with both ECS and EKS, and ECS service scaling is configured on the service through Application Auto Scaling.',
        ['ecs-autoscaling', 'container-decision', 'learn-compute'],
        ['ecs-autoscaling|Amazon ECS leverages the Application Auto Scaling service to provide this functionality.',
         'container-decision|You can use Fargate with both Amazon ECS and Amazon EKS.',
         'learn-compute|AWS Fargate Azure Container Instances, Azure Container Apps AWS Fargate is a serverless compute engine that provides compute capacity for Amazon ECS tasks and Amazon EKS pods.'],
        { allow: ['two'] }),
    },
  ],
};

export default notes;
