import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'database-registry',
  overview: [
    b('Choosing a database is choosing a data model and an engine. AWS offers a growing number of database options with diverse data models: relational, key-value, document, in-memory, graph, time series, vector and wide-column. The first cut is relational versus non-relational; the second is which engine or service inside that group, and whether you are migrating from an existing engine.',
      'database-decision',
      ['AWS offers a growing number of database options (15+) with diverse data models to support a variety of workloads.',
       'These include relational, key-value, document, in-memory, graph, time series, vector, and wide-column.']),
  ],
  beyondProject: [
    b('Your project already uses DynamoDB, a serverless, fully managed, distributed NoSQL database with single-digit millisecond performance at any scale. The SAA question is whether DynamoDB is the right type at all: AWS suggests it for key-value workloads such as session stores or shopping carts, and a workload that needs joins or rich relational queries points to a relational engine instead. You also choose the capacity mode: on-demand or provisioned.',
      ['dynamodb-what-is', 'database-decision', 'dynamodb-capacity'],
      ['dynamodb-what-is|Amazon DynamoDB is a serverless, fully managed, distributed NoSQL database with single-digit millisecond performance at any scale.',
       'database-decision|Amazon DynamoDB Key-value Use for workloads such as session stores or shopping carts.',
       'dynamodb-capacity|In Amazon DynamoDB, you can choose between on-demand mode and provisioned mode for your tables to accommodate different workload requirements.'],
      { allow: ['two'] }),
  ],
  bullets: [
    {
      id: '3.3-K6',
      concepts: [
        b('AWS DMS migrates relational databases, data warehouses, NoSQL databases and other data stores into the AWS Cloud or between cloud and on-premises setups. You can discover source data stores, convert source schemas and migrate the data.',
          'dms-what-is',
          ['AWS Database Migration Service (AWS DMS) is a cloud service that makes it possible to migrate relational databases, data warehouses, NoSQL databases, and other types of data stores.',
           'With AWS DMS, you can discover your source data stores, convert your source schemas, and migrate your data.']),
        b('A {{term:homogeneous-migration}} keeps the same engine (AWS DMS supports it for moving away from old infrastructure), while a {{term:heterogeneous-migration}} changes engine: AWS DMS supports fully heterogeneous migrations between supported engines, and DMS Schema Conversion (or the AWS Schema Conversion Tool) converts the source schemas to the new target engine first.',
          'dms-what-is',
          ['Conversely, if you want to migrate away from old infrastructure but continue to use the same database engine, AWS DMS also supports that process.',
           'AWS DMS supports fully heterogeneous data migrations between the supported engines.',
           'To migrate to a different database engine, you can use DMS Schema Conversion.']),
        b('After converting the schema, you can perform one-time migrations or replicate ongoing changes to keep sources and targets in sync.',
          'dms-what-is',
          ['You can perform one-time migrations or replicate ongoing changes to keep sources and targets in sync.']),
        b('Targets AWS names include Amazon RDS and Aurora (managed relational services), Amazon Redshift (managed data warehouse), Amazon DynamoDB (NoSQL) and Amazon S3 (low-cost storage).',
          'dms-what-is',
          ['For example, AWS DMS can help you take advantage of the managed database services provided by Amazon Relational Database Service (Amazon RDS) or Amazon Aurora. Or it can help you move to the managed data warehouse service provided by Amazon Redshift, NoSQL platforms like Amazon DynamoDB, or low-cost storage platforms like Amazon Simple Storage Service (Amazon S3).']),
      ],
      services: ['AWS DMS', 'Amazon RDS', 'Amazon Aurora'],
      design: [
        b('Cue: same engine, move to AWS → homogeneous migration with DMS; different engine (for example a commercial engine to an open-source-compatible one) → schema conversion first, then DMS; keep the source live while migrating → ongoing replication.',
          'dms-what-is',
          ['You can perform one-time migrations or replicate ongoing changes to keep sources and targets in sync.']),
      ],
    },
    {
      id: '3.3-K8',
      concepts: [
        b('Relational databases are still very popular for structured data and business objects, but are not designed for endless scale. NoSQL databases favour scalability, performance and availability over the consistency of relational databases, and typically do not enforce a strict schema.',
          'msa-data-store',
          ['Relational databases are still very popular to store structured data and business objects.',
           'Relational databases, however, are not designed for endless scale, which can make it difficult and time intensive to apply techniques to support a high number of queries.',
           'NoSQL databases have been designed to favor scalability, performance, and availability over the consistency of relational databases.']),
        b('There are two high-level categories of AWS OLTP databases, relational and non-relational. If you need to store and analyse massive amounts of data quickly (an OLAP requirement), AWS offers Amazon Redshift.',
          'database-decision',
          ['There are two high-level categories of AWS OLTP databases—relational and non-relational.',
           'If you need to store and analyze massive amounts of data quickly and efficiently (a requirement that is typically met by an OLAP application), AWS offers Amazon Redshift.'],
          { allow: ['two'] }),
        b('Serverless database options include Aurora DSQL, Aurora Serverless, DynamoDB, ElastiCache, Keyspaces, Timestream for LiveAnalytics and Neptune Serverless. Aurora serverless is an on-demand, autoscaling configuration that adjusts capacity based on application demand.',
          ['database-decision', 'aurora-serverless'],
          ['database-decision|AWS serverless offerings include Amazon Aurora DSQL, Amazon Aurora Serverless, Amazon DynamoDB, Amazon ElastiCache, Amazon Keyspaces (for Apache Cassandra), Amazon Timestream for LiveAnalytics, and Amazon Neptune Serverless.',
           'aurora-serverless|Aurora serverless is an on-demand, autoscaling configuration for Amazon Aurora.']),
        b('In-memory: for microsecond response times use an in-memory cache such as ElastiCache alongside your database, or Amazon MemoryDB when you need a fully durable, persistent in-memory database.',
          'database-decision',
          ['If your workload requires extremely high read performance with a response time measured in microseconds (rather than single-digit milliseconds), you might want to consider using in- memory caching solutions such as Amazon ElastiCache alongside your database, or a fully durable, persistent in-memory database such as Amazon MemoryDB.']),
      ],
      services: ['Amazon RDS', 'Amazon DynamoDB', 'Amazon ElastiCache', 'Amazon Aurora'],
      design: [
        b('Cue: structured data, joins and transactions → relational; massive scale with simple access patterns → key-value (DynamoDB); highly connected relationships → graph (Neptune); JSON documents → DocumentDB; analytics over large data → Redshift.',
          'database-decision',
          ['Key-value databases can scale to large amounts of data and extremely high throughput of requests, while servicing millions of simultaneous users through distributed processing and storage.']),
      ],
    },
    {
      id: '3.3-S3',
      concepts: [
        b('Amazon RDS offers a choice of engines (PostgreSQL, MySQL, MariaDB, SQL Server, Oracle and Db2), and Aurora is compatible with MySQL and PostgreSQL. Engine choice is usually dictated by the application: what it already uses, which features it needs, and whether you are keeping the engine (homogeneous) or changing it (heterogeneous).',
          ['database-decision', 'aurora-overview', 'dms-what-is'],
          ['database-decision|Amazon RDS Relational Use when you need a fully managed relational database with your choice of six popular engines: PostgreSQL, MySQL, MariaDB, SQL Server, Oracle, and Db2.',
           'aurora-overview|Amazon Aurora (Aurora) is a fully managed relational database engine that\'s compatible with MySQL and PostgreSQL.',
           'dms-what-is|Conversely, if you want to migrate away from old infrastructure but continue to use the same database engine, AWS DMS also supports that process.']),
        b('Aurora lets the code, tools and applications you use with existing MySQL and PostgreSQL databases keep working, which is why compatibility with an existing engine is the first filter in a migration question.',
          'aurora-overview',
          ['The code, tools, and applications you use today with your existing MySQL and PostgreSQL databases can be used with Aurora.']),
      ],
      services: ['Amazon RDS', 'Amazon Aurora', 'AWS DMS'],
      design: [
        b('Cue: "the application uses Oracle/SQL Server and cannot change" → RDS with that engine; "MySQL or PostgreSQL application, needs higher resilience and more elastic capacity" → Aurora.',
          'database-decision',
          ['Amazon Aurora Relational Use when you\'re migrating or modernizing an on-premises relational workload, or if your workload has less predictable query patterns.']),
      ],
    },
    {
      id: '3.3-S4',
      concepts: [
        b('Aurora is the relational choice for migrating or modernising an on-premises relational workload, or one with less predictable query patterns; DynamoDB is the key-value choice for session stores or shopping carts; DocumentDB, Neptune, Timestream and Keyspaces cover document, graph, time series and Cassandra-compatible wide-column needs.',
          'database-decision',
          ['Amazon Aurora Relational Use when you\'re migrating or modernizing an on-premises relational workload, or if your workload has less predictable query patterns.',
           'Amazon DynamoDB Key-value Use for workloads such as session stores or shopping carts.',
           'Amazon DocumentDB (with MongoDB compatibility) Document Use when you want to store JSON-like documents with rich querying abilities across the fields of the documents.',
           'Amazon Timestream Time series Use when you have a large amount of time series data, potentially from a number of sources, such as Internet of Things (IoT) data, application metrics, and asset tracking.']),
        b('DynamoDB capacity is chosen as on-demand mode or provisioned mode, and the throughput mode determines how capacity is managed and how reads and writes are charged. (Capacity planning detail is in Tuning Bay.)',
          'dynamodb-capacity',
          ['A table’s throughput mode determines how the capacity of a table is managed.',
           'Throughput mode also determines how you\'re charged for the read and write operations on your tables.']),
      ],
      services: ['Amazon Aurora', 'Amazon DynamoDB', 'Amazon RDS'],
      design: [
        b('Decision cue from the question: needs SQL, joins and transactions → Aurora or RDS; needs predictable single-digit-millisecond key lookups at any scale with no servers to manage → DynamoDB. The Aurora vs RDS comparison below covers the first branch.',
          'dynamodb-what-is',
          ['Amazon DynamoDB is a serverless, fully managed, distributed NoSQL database with single-digit millisecond performance at any scale.']),
      ],
    },
  ],
  cues: [
    cue('keep the same database engine while moving to AWS', 'Homogeneous migration with AWS DMS',
      b('AWS DMS supports migrating away from old infrastructure while continuing to use the same engine.', 'dms-what-is',
        ['Conversely, if you want to migrate away from old infrastructure but continue to use the same database engine, AWS DMS also supports that process.'])),
    cue('migrate to a different engine (for example commercial to open source)', 'Heterogeneous migration: schema conversion plus AWS DMS',
      b('DMS Schema Conversion converts source schemas to a new target engine before DMS migrates the data.', 'dms-what-is',
        ['To migrate to a different database engine, you can use DMS Schema Conversion.'])),
    cue('MySQL- or PostgreSQL-compatible with data copies across three AZs', 'Amazon Aurora',
      b('Aurora is compatible with MySQL and PostgreSQL and keeps copies of the data across three Availability Zones.', 'aurora-storage',
        ['A cluster volume consists of copies of the data across three Availability Zones in a single AWS Region.'])),
    cue('Oracle, SQL Server, MariaDB or Db2', 'Amazon RDS (not Aurora)',
      b('Those are RDS engines.', 'database-decision',
        ['Amazon RDS Relational Use when you need a fully managed relational database with your choice of six popular engines: PostgreSQL, MySQL, MariaDB, SQL Server, Oracle, and Db2.'])),
    cue('unpredictable load, database capacity should scale on demand', 'Aurora serverless or DynamoDB on-demand',
      b('Aurora serverless adjusts capacity automatically based on application demand.', 'aurora-serverless',
        ['Capacity is adjusted automatically based on application demand.'])),
    cue('key-value lookups at massive scale with single-digit millisecond latency', 'Amazon DynamoDB',
      b('DynamoDB is a serverless NoSQL database with single-digit millisecond performance at any scale.', 'dynamodb-what-is',
        ['Amazon DynamoDB is a serverless, fully managed, distributed NoSQL database with single-digit millisecond performance at any scale.'])),
  ],
  examples: [],
  confuse: ['aurora-vs-rds'],
  azure: [
    {
      concept: 'Azure SQL Database, Azure Database for MySQL/PostgreSQL',
      aws: 'Amazon RDS',
      mapping: b('Learn pairs Amazon RDS with Azure SQL Database, Azure Database for MySQL and Azure Database for PostgreSQL as managed relational database services, and notes you can also run SQL Server on Azure Virtual Machines.',
        ['learn-databases', 'rds-what-is'],
        ['learn-databases|Amazon Relational Database Service (Amazon RDS) provides managed relational database engines.',
         'learn-databases|Azure provides managed services for several corresponding engines: Azure SQL Database Azure Database for MySQL Azure Database for PostgreSQL SQL Database in Microsoft Fabric',
         'rds-what-is|Amazon Relational Database Service (Amazon RDS) is a web service that makes it easier to set up, operate, and scale a relational database in the AWS Cloud.']),
      breaks: b('Learn warns not to select an Azure service based only on engine compatibility; compare availability and operating models too. On AWS one service (RDS) fronts several engines, and Aurora is a separate engine family. Learn also pairs Aurora Serverless with SQL Database serverless but warns that they use different scaling and billing models, so do not assume scaling behaves alike.',
        ['learn-databases', 'aurora-serverless'],
        ['learn-databases|Don\'t select a service based only on engine compatibility.',
         'learn-databases|These services use different scaling and billing models.',
         'learn-databases|SQL Database serverless can automatically scale compute and pause during inactivity.',
         'aurora-serverless|Capacity is adjusted automatically based on application demand.']),
    },
    {
      concept: 'Azure Cosmos DB for NoSQL',
      aws: 'Amazon DynamoDB',
      mapping: b('Learn pairs DynamoDB with Azure Cosmos DB for NoSQL: both distribute data by partition key and provide change streams.',
        ['learn-databases', 'dynamodb-what-is'],
        ['learn-databases|Both services distribute data by partition key and provide change streams.',
         'dynamodb-what-is|Amazon DynamoDB is a serverless, fully managed, distributed NoSQL database with single-digit millisecond performance at any scale.']),
      breaks: b('Learn states that the consistency, indexing, query, transaction, capacity and pricing models differ, and says to plan application and data-model changes instead of assuming API compatibility. A DynamoDB design is not a Cosmos DB design with new names.',
        ['learn-databases', 'dynamodb-capacity'],
        ['learn-databases|Their consistency, indexing, query, transaction, capacity, and pricing models differ.',
         'learn-databases|Plan application and data-model changes instead of assuming API compatibility.',
         'dynamodb-capacity|In Amazon DynamoDB, you can choose between on-demand mode and provisioned mode for your tables to accommodate different workload requirements.']),
    },
    {
      concept: 'Azure Database Migration Service',
      aws: 'AWS Database Migration Service (AWS DMS)',
      mapping: b('Learn pairs AWS DMS with Azure Database Migration Service, and says support varies by source, target and online or offline migration mode, so verify the current supported scenarios before selecting a tool.',
        ['learn-databases', 'dms-what-is'],
        ['learn-databases|Support varies by source, target, and online or offline migration mode.',
         'dms-what-is|AWS DMS supports fully heterogeneous data migrations between the supported engines.']),
      breaks: b('Learn adds that database migration requires more than moving data: inventory engine features, stored procedures, extensions, indexes and consistency assumptions. On AWS this is why schema conversion is a separate step before DMS in a heterogeneous migration.',
        ['learn-databases', 'dms-what-is'],
        ['learn-databases|Database migration requires more than moving data.',
         'dms-what-is|To migrate to a different database engine, you can use DMS Schema Conversion.']),
    },
  ],
};

export default notes;
