import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'data-lake-reservoir',
  overview: [
    b('A {{term:data-lake}} keeps raw data in one place and lets many tools analyse it. On AWS the usual pattern is Amazon S3 for storage, AWS Glue Data Catalog for metadata, AWS Lake Formation for governance, Amazon Athena for SQL queries and {{rename:quick}} for dashboards.',
      ['what-is-data-lake', 'lake-formation', 'athena-what-is'],
      ['what-is-data-lake|You can store your data as-is, without having to first structure the data, and run different types of analytics—from dashboards and visualizations to big data processing, real-time analytics, and machine learning to guide better decisions.',
       'lake-formation|With Lake Formation, you can manage fine-grained access control for your data lake data on Amazon Simple Storage Service (Amazon S3) and its metadata in AWS Glue Data Catalog.',
       'athena-what-is|Amazon Athena is an interactive query service that makes it easy to analyze data directly in Amazon Simple Storage Service (Amazon S3) using standard SQL.']),
  ],
  bullets: [
    {
      id: '3.5-K1',
      concepts: [
        b('Amazon Athena is an interactive query service that analyses data directly in S3 using standard SQL: you point it at the data and run ad-hoc queries. It is serverless, so there is no infrastructure to set up or manage, and it scales automatically by running queries in parallel.',
          'athena-what-is',
          ['Amazon Athena is an interactive query service that makes it easy to analyze data directly in Amazon Simple Storage Service (Amazon S3) using standard SQL.',
           'With a few actions in the AWS Management Console, you can point Athena at your data stored in Amazon S3 and begin using standard SQL to run ad-hoc queries and get results in seconds.',
           'Athena scales automatically—running queries in parallel—so results are fast, even with large datasets and complex queries.']),
        b('AWS Lake Formation helps you centrally govern, secure and share data for analytics and machine learning. It provides its own permissions model that augments IAM, with fine-grained access at the column, row and cell levels enforced across analytics services such as Athena, Quick, Redshift Spectrum, EMR and Glue.',
          'lake-formation',
          ['AWS Lake Formation helps you centrally govern, secure, and globally share data for analytics and machine learning.',
           'Lake Formation provides its own permissions model that augments the IAM permissions model.',
           'Lake Formation permissions are enforced using granular controls at the column, row, and cell-levels across AWS analytics and machine learning services, including Amazon Athena, Amazon Quick, Amazon Redshift Spectrum, Amazon EMR, and AWS Glue.']),
        b('AWS Glue is a serverless data integration service for discovering, preparing, moving and integrating data from multiple sources, with a centralised data catalog. (Refinery covers transformation.)',
          'glue-what-is',
          ['AWS Glue is a serverless data integration service that makes it easy for analytics users to discover, prepare, move, and integrate data from multiple sources.']),
        b('{{rename:quick}} includes Amazon Quick Sight, the feature for interactive data visualisation and business intelligence: connect to data sources, build dashboards and embed analytics in applications.',
          'quick-what-is',
          ['Amazon Quick Sight – Interactive data visualization and business intelligence.',
           'Connect to data sources, build dashboards, and embed analytics in applications.']),
      ],
      services: ['Amazon Athena', 'AWS Lake Formation', 'Amazon Quick'],
      design: [
        b('Cue: ad-hoc SQL on files in S3 with nothing to provision → Athena; fine-grained access control to data in the lake → Lake Formation; dashboards and BI → Quick (Quick Sight).',
          ['athena-what-is', 'lake-formation', 'quick-what-is'],
          ['athena-what-is|With a few actions in the AWS Management Console, you can point Athena at your data stored in Amazon S3 and begin using standard SQL to run ad-hoc queries and get results in seconds.',
           'lake-formation|With Lake Formation, you can manage fine-grained access control for your data lake data on Amazon Simple Storage Service (Amazon S3) and its metadata in AWS Glue Data Catalog.',
           'quick-what-is|Amazon Quick Sight – Interactive data visualization and business intelligence.']),
      ],
    },
    {
      id: '3.5-S1',
      concepts: [
        b('Building a data lake: store data as-is in S3 without structuring it first, then catalogue it so tools can query it. S3 is the usual storage layer for data lakes; AWS lists data lakes among its use cases.',
          ['what-is-data-lake', 's3-what-is'],
          ['what-is-data-lake|A data lake is different, because it stores relational data from line of business applications, and non-relational data from mobile apps, IoT devices, and social media.',
           's3-what-is|Customers of all sizes and industries can use Amazon S3 to store and protect any amount of data for a range of use cases, such as data lakes, websites, mobile applications, backup and restore, archive, enterprise applications, IoT devices, and big data analytics.']),
        b('Securing it: Lake Formation manages fine-grained access to data lake data in S3 and its metadata in the Glue Data Catalog with a simple grant or revoke mechanism, much like a relational database, and can share data across AWS accounts and organizations. Layer S3 controls (Block Public Access, encryption, bucket policies) underneath.',
          ['lake-formation', 's3-block-public-access'],
          ['lake-formation|Lake Formation permissions model enables fine-grained access to data stored in data lakes as well as external data sources such as Amazon Redshift data warehouses, Amazon DynamoDB databases, and third-party data sources through a simple grant or revoke mechanism, much like a relational database management system (RDBMS).',
           'lake-formation|Lake Formation also allows you to share data internally and externally across multiple AWS accounts, AWS organizations or directly with IAM principals in another account providing fine-grained access to the Data Catalog metadata and underlying data.']),
        b('Make queries cheaper and faster by storing the data in a columnar format and partitioning it. Apache Parquet and ORC are columnar formats optimised for fast retrieval, with compression by column and predicate pushdown; partitioning lets a query restrict the amount of data scanned, improving performance and reducing cost.',
          ['athena-columnar', 'athena-partitions'],
          ['athena-columnar|Apache Parquet and ORC are columnar storage formats that are optimized for fast retrieval of data and used in AWS analytical applications.',
           'athena-columnar|Predicate pushdown in Parquet and ORC enables Athena queries to fetch only the blocks it needs, improving query performance.',
           'athena-partitions|By partitioning your data, you can restrict the amount of data scanned by each query, thus improving performance and reducing cost.']),
      ],
      services: ['Amazon S3', 'AWS Lake Formation', 'Amazon Athena'],
      design: [
        b('Reference design: raw data lands in S3, Glue crawlers or jobs catalogue and transform it (Refinery), Lake Formation governs access, Athena queries it, Quick visualises it.',
          ['glue-what-is', 'lake-formation', 'athena-what-is'],
          ['glue-what-is|AWS Glue is a serverless data integration service that makes it easy for analytics users to discover, prepare, move, and integrate data from multiple sources.',
           'lake-formation|AWS Lake Formation helps you centrally govern, secure, and globally share data for analytics and machine learning.',
           'athena-what-is|Amazon Athena is an interactive query service that makes it easy to analyze data directly in Amazon Simple Storage Service (Amazon S3) using standard SQL.']),
      ],
    },
    {
      id: '3.5-S4',
      concepts: [
        b('Visualisation strategy: choose the BI tool and connect it to the governed data. Amazon Quick Sight connects to data sources, builds dashboards and embeds analytics in applications, and Lake Formation permissions are enforced when Quick reads the lake.',
          ['quick-what-is', 'lake-formation'],
          ['quick-what-is|Connect to data sources, build dashboards, and embed analytics in applications.',
           'lake-formation|Lake Formation permissions are enforced using granular controls at the column, row, and cell-levels across AWS analytics and machine learning services, including Amazon Athena, Amazon Quick, Amazon Redshift Spectrum, Amazon EMR, and AWS Glue.']),
        b('Quick is an AI-powered service for automating tasks, analysing data, building web applications and conducting research through natural language chat; the exam guide lists it under its current name, and older material calls the business-intelligence feature QuickSight.',
          'quick-what-is',
          ['Amazon Quick is an AI-powered service for automating tasks, analyzing data, building web applications, and conducting research.']),
      ],
      services: ['Amazon Quick'],
      design: [
        b('Cue: business users need dashboards and shareable reports on lake data → Quick Sight reading from Athena or other sources; they need row-level restrictions → enforce them in Lake Formation.',
          'quick-what-is',
          ['Amazon Quick Sight – Interactive data visualization and business intelligence.']),
      ],
    },
  ],
  cues: [
    cue('run SQL queries directly on data in S3 with no servers to manage', 'Amazon Athena',
      b('Athena queries data in S3 with standard SQL and is serverless.', 'athena-what-is',
        ['Amazon Athena is an interactive query service that makes it easy to analyze data directly in Amazon Simple Storage Service (Amazon S3) using standard SQL.'])),
    cue('column-level or row-level access control on data lake data', 'AWS Lake Formation',
      b('Lake Formation enforces column, row and cell-level permissions.', 'lake-formation',
        ['Lake Formation permissions are enforced using granular controls at the column, row, and cell-levels across AWS analytics and machine learning services, including Amazon Athena, Amazon Quick, Amazon Redshift Spectrum, Amazon EMR, and AWS Glue.'])),
    cue('reduce the amount of data Athena scans', 'Partition the data and store it in a columnar format such as Parquet',
      b('Partitioning restricts the data scanned, and columnar formats let queries fetch only the blocks they need.', 'athena-partitions',
        ['By partitioning your data, you can restrict the amount of data scanned by each query, thus improving performance and reducing cost.'])),
    cue('interactive dashboards and BI over data sources', 'Amazon Quick (Quick Sight)',
      b('Quick Sight provides interactive visualisation and business intelligence.', 'quick-what-is',
        ['Amazon Quick Sight – Interactive data visualization and business intelligence.'])),
    cue('store all data as-is, structured and unstructured, at any scale', 'Data lake on Amazon S3',
      b('A data lake is a centralised repository for structured and unstructured data at any scale.', 'what-is-data-lake',
        ['A data lake is a centralized repository that allows you to store all your structured and unstructured data at any scale.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Data Lake Storage',
      aws: 'Amazon S3',
      mapping: b('Learn pairs Amazon S3 with Azure Data Lake Storage: both provide durable object storage for analytical data, and Data Lake Storage provides object storage with a hierarchical namespace.',
        ['learn-analytics', 's3-what-is'],
        ['learn-analytics|Amazon S3 Azure Data Lake Storage Both provide durable object storage for analytical data.',
         'learn-analytics|Data Lake Storage provides object storage with a hierarchical namespace.',
         's3-what-is|Amazon S3 is an object storage service that stores data as objects, hierarchical data, or tabular data within buckets.']),
      breaks: b('Learn says to compare namespace behaviour, security, lifecycle management, replication, ecosystem integration and data-transfer costs, so do not assume they are interchangeable. For the AWS exam, S3 plus Glue, Lake Formation and Athena is the data lake pattern.',
        ['learn-analytics', 'lake-formation'],
        ['learn-analytics|Compare namespace behavior, security, lifecycle management, replication, ecosystem integration, and data-transfer costs.',
         'lake-formation|AWS Lake Formation helps you centrally govern, secure, and globally share data for analytics and machine learning.']),
    },
    {
      concept: 'OneLake security and Microsoft Purview in Fabric',
      aws: 'AWS Lake Formation',
      mapping: b('Learn pairs AWS Lake Formation, which manages access to S3-based data lakes, with OneLake security and Microsoft Purview in Fabric.',
        ['learn-analytics', 'lake-formation'],
        ['learn-analytics|AWS Lake Formation manages access to S3-based data lakes.',
         'lake-formation|Lake Formation provides its own permissions model that augments the IAM permissions model.']),
      breaks: b('Learn warns that Fabric separates storage permissions, item permissions and governance capabilities, so map authorisation and governance requirements instead of assuming a single-service equivalent. Lake Formation is a single AWS service with its own permissions model layered on IAM.',
        ['learn-analytics', 'lake-formation'],
        ['learn-analytics|Fabric separates storage permissions, item permissions, and governance capabilities.',
         'learn-analytics|Map authorization and governance requirements instead of assuming a single-service equivalent.',
         'lake-formation|Lake Formation provides its own permissions model that augments the IAM permissions model.']),
    },
    {
      concept: 'Power BI',
      aws: 'Amazon Quick (Quick Sight)',
      mapping: b('Learn pairs {{rename:quick}} with Power BI: both provide semantic modelling, reports, dashboards, sharing and embedded analytics, and Learn says to compare licensing, capacity, identity, governance, authoring and embedding requirements.',
        ['learn-analytics', 'quick-what-is'],
        ['learn-analytics|Amazon QuickSight Power BI Both provide semantic modeling, reports, dashboards, sharing, and embedded analytics.',
         'learn-analytics|Compare licensing, capacity, identity, governance, authoring, and embedding requirements.',
         'quick-what-is|Amazon Quick Sight – Interactive data visualization and business intelligence.']),
      breaks: b('The AWS name has changed: the exam guide lists Amazon Quick, and Quick Sight is now a feature within it, while the Learn page still uses the earlier name QuickSight.',
        ['quick-what-is', 'learn-analytics'],
        ['quick-what-is|QuickSight continues as Amazon Quick Sight, a feature within Quick.',
         'learn-analytics|Amazon QuickSight Power BI Both provide semantic modeling, reports, dashboards, sharing, and embedded analytics.']),
    },
  ],
};

export default notes;
