import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'edge-link-terminal',
  overview: [
    b('This building is about where traffic enters your architecture and how outside networks reach it. Edge services (CloudFront and Global Accelerator) bring users onto the AWS network near them; connection options (Site-to-Site VPN, Direct Connect and PrivateLink) join your own networks or services to AWS; and placement decides in which Region, edge location or on-premises site each resource should live to meet the requirement.',
      ['cloudfront-what-is', 'ga-what-is', 's2s-vpn', 'dx-what-is'],
      ['cloudfront-what-is|CloudFront delivers your content through a worldwide network of data centers called edge locations.',
       'ga-what-is|AWS Global Accelerator is a service in which you create accelerators to improve the performance of your applications for local and global users.',
       's2s-vpn|You can enable access to your remote devices from your VPC by creating an AWS Site-to-Site VPN (Site-to-Site VPN) connection',
       'dx-what-is|Direct Connect links your internal network to a Direct Connect location over a standard Ethernet fiber-optic cable.']),
  ],
  beyondProject: [
    b('Your static site already uses CloudFront. The SAA step is knowing what CloudFront is for and where AWS Global Accelerator fits instead. CloudFront speeds up distribution of static and dynamic web content. Global Accelerator improves performance for applications over TCP or UDP by proxying packets at the edge to applications running in one or more AWS Regions, and AWS calls it a good fit for non-HTTP use cases and for HTTP use cases that specifically require static IP addresses or deterministic, fast regional failover. They are compared in the Don\'t confuse section below.',
      ['cloudfront-what-is', 'ga-faq'],
      ['cloudfront-what-is|Amazon CloudFront is a web service that speeds up distribution of your static and dynamic web content, such as .html, .css, .js, and image files, to your users.',
       'ga-faq|Global Accelerator improves performance for a wide range of applications over TCP or UDP by proxying packets at the edge to applications running in one or more AWS Regions.',
       'ga-faq|Global Accelerator is a good fit for non-HTTP use cases, such as gaming (UDP), IoT (MQTT), or Voice over IP, as well as for HTTP use cases that specifically require static IP addresses or deterministic, fast regional failover.']),
  ],
  bullets: [
    {
      id: '3.4-K1',
      concepts: [
        b('CloudFront caches content at edge locations and routes each request to the edge location with the lowest latency; it can serve origins such as S3 buckets, Elastic Load Balancing or API Gateway, and data transfer from your origin to CloudFront is always free when the origin is an AWS origin such as S3, Elastic Load Balancing or API Gateway.',
          'cloudfront-what-is',
          ['When a user requests content that you\'re serving with CloudFront, the request is routed to the edge location that provides the lowest latency (time delay), so that content is delivered with the best possible performance.',
           'The data transfer from your origin to CloudFront is always free when using AWS origins like Amazon Simple Storage Service (Amazon S3), Elastic Load Balancing, or Amazon API Gateway.']),
        b('Global Accelerator provides static anycast IP addresses as fixed entry points and routes traffic over the AWS global network to the optimal regional endpoint based on health, client location and configured policies. It is a global service that supports endpoints in multiple Regions.',
          ['ga-what-is', 'ga-how'],
          ['ga-how|The static IP addresses provided by AWS Global Accelerator serve as single fixed entry points for your clients.',
           'ga-what-is|Global Accelerator is a global service that supports endpoints in multiple AWS Regions.',
           'ga-what-is|For standard accelerators, Global Accelerator uses the AWS global network to route traffic to the optimal regional endpoint based on health, client location, and policies that you configure, which increases the availability of your applications.']),
        b('A custom routing accelerator lets you map one or more users to a specific destination among many destinations, for example a fleet of game servers.',
          ['ga-what-is', 'ga-product'],
          ['ga-what-is|With a custom routing accelerator, you can map one or more users to a specific destination among many destinations.',
           'ga-product|Low-latency gaming and media workloads Use custom routing to deterministically route traffic to a fleet of EC2 instances.']),
      ],
      services: ['Amazon CloudFront', 'AWS Global Accelerator'],
      design: [
        b('Cue: cache, lower origin load, static website → CloudFront; static IPs for allow-listing, deterministic routing independent of DNS, fast regional failover, or non-HTTP traffic over TCP or UDP → Global Accelerator.',
          ['ga-product', 'ga-faq'],
          ['ga-product|Global static IP Simplify allowlisting in enterprise firewalling and IoT use cases.',
           'ga-product|Users can access your application endpoints through static IP addresses to enjoy deterministic routing independent of DNS.',
           'ga-faq|Global Accelerator is a good fit for non-HTTP use cases, such as gaming (UDP), IoT (MQTT), or Voice over IP, as well as for HTTP use cases that specifically require static IP addresses or deterministic, fast regional failover.']),
      ],
    },
    {
      id: '3.4-K4',
      concepts: [
        b('AWS Site-to-Site VPN connects a VPC to a remote network or device over IPsec VPN connections through the internet; each VPN connection includes two tunnels you can use simultaneously for high availability.',
          's2s-vpn',
          ['You can enable access to your remote devices from your VPC by creating an AWS Site-to-Site VPN (Site-to-Site VPN) connection, and configuring routing to pass traffic through the connection.',
           'Site-to-Site VPN supports Internet Protocol security (IPsec) VPN connections.',
           'Each VPN connection includes two VPN tunnels which you can simultaneously use for high availability.'],
          { allow: ['two'] }),
        b('AWS Direct Connect links your internal network to a Direct Connect location over a standard Ethernet fiber-optic cable, and you create virtual interfaces directly to public AWS services or to Amazon VPC, bypassing internet service providers in your network path. Direct Connect does not encrypt your traffic in transit by default; you can combine a Direct Connect connection with the Site-to-Site VPN when you need encryption.',
          ['dx-what-is', 'dx-encryption'],
          ['dx-what-is|Direct Connect links your internal network to a Direct Connect location over a standard Ethernet fiber-optic cable.',
           'dx-what-is|With this connection, you can create virtual interfaces directly to public AWS services (for example, to Amazon S3) or to Amazon VPC, bypassing internet service providers in your network path.',
           'dx-encryption|AWS Direct Connect does not encrypt your traffic that is in transit by default.',
           'dx-encryption|With AWS Direct Connect and AWS Site-to-Site VPN, you can combine one or more AWS Direct Connect dedicated network connections with the Amazon VPC VPN.']),
        b('AWS PrivateLink privately connects a VPC to services and resources as if they were in the VPC, without an internet gateway, NAT device, public IP address, Direct Connect or Site-to-Site VPN connection. The full Direct Connect vs VPN comparison is in Transit Tariff, and Customs House covers VPC endpoints.',
          'privatelink-what-is',
          ['AWS PrivateLink is a highly available, scalable technology that you can use to privately connect your VPC to services and resources as if they were in your VPC.',
           'You do not need to use an internet gateway, NAT device, public IP address, Direct Connect connection, or AWS Site-to-Site VPN connection to allow communication with the service or resource from your private subnets.']),
        b('AWS Transit Gateway is a network transit hub used to interconnect VPCs and on-premises networks; you can attach VPCs, a Direct Connect gateway and VPN connections to it (Grid Planning Office).',
          'tgw-what-is',
          ['AWS Transit Gateway is a network transit hub used to interconnect virtual private clouds (VPCs) and on-premises networks.',
           'Attachments — You can attach the following: One or more VPCs A Connect SD-WAN/third-party network appliance An AWS Direct Connect gateway A peering connection with another transit gateway A VPN connection to a transit gateway']),
      ],
      services: ['AWS Site-to-Site VPN', 'AWS Direct Connect', 'AWS PrivateLink'],
      design: [
        b('Cue: IPsec-encrypted connection over the internet → Site-to-Site VPN; a connection that bypasses internet service providers → Direct Connect (add a VPN when the traffic must also be encrypted); private access to a service without an internet gateway, NAT device or public IP address → PrivateLink.',
          ['s2s-vpn', 'dx-what-is', 'privatelink-what-is', 'dx-encryption'],
          ['s2s-vpn|Site-to-Site VPN supports Internet Protocol security (IPsec) VPN connections.',
           'dx-what-is|With this connection, you can create virtual interfaces directly to public AWS services (for example, to Amazon S3) or to Amazon VPC, bypassing internet service providers in your network path.',
           'dx-encryption|AWS Direct Connect does not encrypt your traffic that is in transit by default.',
           'privatelink-what-is|You do not need to use an internet gateway, NAT device, public IP address, Direct Connect connection, or AWS Site-to-Site VPN connection to allow communication with the service or resource from your private subnets.']),
      ],
    },
    {
      id: '3.4-S3',
      concepts: [
        b('Placement starts with the Region: choose it for the users, the services available and the requirements; a Region close to the majority of your users lowers network latency.',
          'regions-and-azs',
          ['Also, you can lower network latency when you select a Region that is close to the majority of your users.']),
        b('AWS Outposts extends AWS infrastructure, services, APIs and tools to customer premises, for applications that need local access to AWS managed infrastructure for lower latency and local data processing.',
          'outposts-what-is',
          ['AWS Outposts is a fully managed service that extends AWS infrastructure, services, APIs, and tools to customer premises.',
           'By providing local access to AWS managed infrastructure, AWS Outposts enables customers to build and run applications on premises using the same programming interfaces as in AWS Regions, while using local compute and storage resources for lower latency and local data processing needs.']),
        b('AWS Wavelength deploys standard AWS compute and storage services to the edge of communications service providers\' networks, to deliver low latency to mobile devices and end users; you extend a VPC to one or more Wavelength Zones.',
          'wavelength-what-is',
          ['AWS Wavelength enables developers to build applications that require edge computing infrastructure to deliver low latency to mobile devices and end users or increase the resiliency of their existing edge applications.',
           'Wavelength deploys standard AWS compute and storage services to the edge of communications service providers\' (CSP) networks.']),
        b('AWS Local Zones places compute, storage, database and other select AWS resources close to large population and industry centers, so you can give your users low-latency access to your applications. AWS Outposts, by contrast, extends AWS infrastructure, services, APIs and tools to customer premises.',
          ['local-zones', 'outposts-what-is'],
          ['local-zones|AWS Local Zones places compute, storage, database, and other select AWS resources close to large population and industry centers.',
           'local-zones|You can use Local Zones to provide your users with low-latency access to your applications.',
           'outposts-what-is|AWS Outposts is a fully managed service that extends AWS infrastructure, services, APIs, and tools to customer premises.']),
        b('Spread across Availability Zones inside the Region for resilience, and use Global Accelerator or Route 53 policies when users are in several Regions.',
          ['waf-multi-location', 'route53-routing'],
          ['waf-multi-location|Distribute workload data and resources across multiple Availability Zones or, where necessary, across AWS Regions.',
           'route53-routing|Latency routing policy – Use when you have resources in multiple AWS Regions and you want to route traffic to the Region that provides the best latency.']),
      ],
      services: ['Amazon CloudFront', 'AWS Global Accelerator'],
      design: [
        b('Cue: a Region near most users → choose that Region for latency, and CloudFront for cacheable content; local data processing on premises → Outposts; low latency to users near large population and industry centers → Local Zones; mobile devices on a carrier network → Wavelength; non-HTTP traffic (gaming, IoT, VoIP) or HTTP that needs static IP addresses or fast regional failover → Global Accelerator.',
          ['outposts-what-is', 'wavelength-what-is', 'local-zones', 'regions-and-azs', 'ga-faq'],
          ['outposts-what-is|By providing local access to AWS managed infrastructure, AWS Outposts enables customers to build and run applications on premises using the same programming interfaces as in AWS Regions, while using local compute and storage resources for lower latency and local data processing needs.',
           'wavelength-what-is|AWS Wavelength enables developers to build applications that require edge computing infrastructure to deliver low latency to mobile devices and end users or increase the resiliency of their existing edge applications.',
           'local-zones|You can use Local Zones to provide your users with low-latency access to your applications.',
           'regions-and-azs|Also, you can lower network latency when you select a Region that is close to the majority of your users.',
           'ga-faq|CloudFront improves performance for both cacheable content (such as images and videos) and dynamic content (such as API acceleration and dynamic site delivery).',
           'ga-faq|Global Accelerator is a good fit for non-HTTP use cases, such as gaming (UDP), IoT (MQTT), or Voice over IP, as well as for HTTP use cases that specifically require static IP addresses or deterministic, fast regional failover.']),
      ],
    },
  ],
  cues: [
    cue('cache static content close to users and reduce origin load', 'Amazon CloudFront',
      b('Content is cached at edge locations, and a longer cache duration reduces the load on your origin.', 'cloudfront-expiration',
        ['A longer duration also reduces the load on your origin.'])),
    cue('static IP addresses to allow-list, fast regional failover, or non-HTTP traffic such as gaming (UDP) or VoIP', 'AWS Global Accelerator',
      b('Global Accelerator suits non-HTTP use cases and HTTP use cases that require static IP addresses or deterministic, fast regional failover.', 'ga-faq',
        ['Global Accelerator is a good fit for non-HTTP use cases, such as gaming (UDP), IoT (MQTT), or Voice over IP, as well as for HTTP use cases that specifically require static IP addresses or deterministic, fast regional failover.'])),
    cue('low latency to users near a large population or industry center', 'AWS Local Zones',
      b('Local Zones place compute, storage and database resources close to large population and industry centers.', 'local-zones',
        ['AWS Local Zones places compute, storage, database, and other select AWS resources close to large population and industry centers.'])),
    cue('dedicated private connection bypassing internet providers', 'AWS Direct Connect',
      b('Direct Connect bypasses internet service providers in your network path.', 'dx-what-is',
        ['With this connection, you can create virtual interfaces directly to public AWS services (for example, to Amazon S3) or to Amazon VPC, bypassing internet service providers in your network path.'])),
    cue('IPsec VPN to AWS over the internet', 'AWS Site-to-Site VPN',
      b('Site-to-Site VPN supports IPsec VPN connections.', 's2s-vpn',
        ['Site-to-Site VPN supports Internet Protocol security (IPsec) VPN connections.'])),
    cue('compute and storage on premises with the same AWS APIs', 'AWS Outposts',
      b('Outposts extends AWS infrastructure, services, APIs and tools to customer premises.', 'outposts-what-is',
        ['AWS Outposts is a fully managed service that extends AWS infrastructure, services, APIs, and tools to customer premises.'])),
    cue('ultra-low latency for mobile devices at the carrier edge', 'AWS Wavelength',
      b('Wavelength deploys AWS compute and storage to the edge of communications service providers\' networks.', 'wavelength-what-is',
        ['Wavelength deploys standard AWS compute and storage services to the edge of communications service providers\' (CSP) networks.'])),
  ],
  examples: [],
  confuse: ['cloudfront-vs-global-accelerator'],
  azure: [
    {
      concept: 'Azure Front Door',
      aws: 'Amazon CloudFront',
      mapping: b('Learn pairs CloudFront with Azure Front Door as content delivery network services, and lists Front Door against Global Accelerator for global anycast entry points on the provider\'s backbone network.',
        ['learn-networking', 'cloudfront-what-is'],
        ['learn-networking|Content delivery networks CloudFront Azure Front Door Azure Front Door is a modern cloud content delivery network (CDN) service that provides high performance, scalability, and secure user experiences for your content and applications.',
         'learn-networking|These services provide global anycast entry points on the provider\'s backbone network to improve application performance and availability across regions.',
         'cloudfront-what-is|CloudFront delivers your content through a worldwide network of data centers called edge locations.']),
      breaks: b('Learn describes Azure Front Door as operating at layer 7 with integrated CDN and WAF, while the Azure cross-region Load Balancer operates at layer 4 and closely matches the layer-4 behaviour of Global Accelerator.',
        ['learn-networking', 'ga-what-is'],
        ['learn-networking|Azure Front Door operates at layer 7 (HTTP/HTTPS) with integrated CDN and WAF.',
         'learn-networking|Azure cross-region Load Balancer operates at layer 4 for TCP/UDP, which closely matches AWS Global Accelerator\'s layer-4 behavior.',
         'ga-what-is|Global Accelerator is a global service that supports endpoints in multiple AWS Regions.']),
    },
    {
      concept: 'ExpressRoute and VPN Gateway',
      aws: 'AWS Direct Connect and AWS Site-to-Site VPN',
      mapping: b('Learn pairs Direct Connect with ExpressRoute, a dedicated private network connection from your local network to Azure, and notes both Azure and AWS offer site-to-site VPN connections.',
        ['learn-networking', 'dx-what-is'],
        ['learn-networking|AWS Direct Connect can link a network directly to AWS. Azure provides similar site-to-site dedicated connections through ExpressRoute.',
         'learn-networking|Both Azure and AWS offer site-to-site VPN connections.',
         'dx-what-is|Direct Connect links your internal network to a Direct Connect location over a standard Ethernet fiber-optic cable.']),
      breaks: b('Learn says VPN Gateway offers higher throughput for certain configurations than Site-to-Site VPN. AWS documents its limits per tunnel (see Transit Tariff).',
        ['learn-networking', 'vpn-tunnels', 's2s-vpn'],
        ['learn-networking|They provide similar features, but there\'s a notable difference with performance.',
         'learn-networking|VPN Gateway offers higher throughput for certain configurations',
         'vpn-tunnels|Standard bandwidth: Up to 1.25 Gbps per tunnel (default)',
         'vpn-tunnels|Large Bandwidth Tunnel (LBT): Up to 5 Gbps per tunnel']),
    },
  ],
};

export default notes;
