import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'engine-works',
  overview: [
    b('Choosing compute for performance means matching the shape of the workload to the compute option and then sizing it. Amazon EC2 instance types are grouped in families by their compute, memory and storage capabilities; Lambda lets you size a function by its memory setting; AWS Batch and Amazon EMR cover batch and big-data processing; Fargate removes the servers from container workloads.',
      ['ec2-instance-types', 'lambda-memory', 'batch-what-is', 'emr-what-is'],
      ['ec2-instance-types|Each instance type offers different compute, memory, and storage capabilities, and is grouped in an instance family based on these capabilities.',
       'lambda-memory|Lambda allocates CPU power in proportion to the amount of memory configured.',
       'batch-what-is|AWS Batch helps you to run batch computing workloads on the AWS Cloud.',
       'emr-what-is|Amazon EMR, which was previously called Amazon Elastic MapReduce, is a managed cluster platform that simplifies running big data frameworks, such as Apache Hadoop and Apache Spark, on AWS to process and analyze vast amounts of data.']),
  ],
  beyondProject: [
    b('Your visitor counter runs on Lambda. The SAA question is how to size it: Lambda allocates CPU power in proportion to the memory you configure, so memory is the one performance dial on a function. You can configure memory between 128 MB and 10,240 MB, and at 1,769 MB a function has the equivalent of one vCPU. These are documented limits that can change.',
      'lambda-memory',
      ['Lambda allocates CPU power in proportion to the amount of memory configured.',
       'You can configure memory between 128 MB and 10,240 MB in 1-MB increments.',
       'At 1,769 MB, a function has the equivalent of one vCPU (one vCPU-second of credits per second).']),
  ],
  bullets: [
    {
      id: '3.2-K1',
      concepts: [
        b('AWS Batch runs batch computing workloads on AWS. It removes the heavy lifting of configuring and managing the infrastructure, provisions resources in response to submitted jobs to eliminate capacity constraints, and automatically provisions compute and optimises the workload distribution based on the quantity and scale of the workloads.',
          'batch-what-is',
          ['AWS Batch helps you to run batch computing workloads on the AWS Cloud.',
           'This service can efficiently provision resources in response to jobs submitted in order to eliminate capacity constraints, reduce compute costs, and deliver results quickly.',
           'AWS Batch automatically provisions compute resources and optimizes the workload distribution based on the quantity and scale of the workloads.']),
        b('Amazon EMR is a managed cluster platform that simplifies running big data frameworks such as Apache Hadoop and Apache Spark to process and analyse vast amounts of data, and can also transform and move large amounts of data into and out of stores like Amazon S3 and Amazon DynamoDB.',
          'emr-what-is',
          ['Amazon EMR, which was previously called Amazon Elastic MapReduce, is a managed cluster platform that simplifies running big data frameworks, such as Apache Hadoop and Apache Spark, on AWS to process and analyze vast amounts of data.',
           'Amazon EMR also lets you transform and move large amounts of data into and out of other AWS data stores and databases, such as Amazon Simple Storage Service (Amazon S3) and Amazon DynamoDB.']),
        b('AWS Fargate lets you run containers without provisioning, configuring or scaling clusters of virtual machines: you package the application in containers, specify the CPU and memory requirements and launch it. (See Container Dock for ECS and EKS.)',
          'fargate-ecs',
          ['With AWS Fargate, you no longer have to provision, configure, or scale clusters of virtual machines to run containers.',
           'When you run your tasks and services with Fargate, you package your application in containers, specify the CPU and memory requirements, define networking and IAM policies, and launch the application.']),
        b('The compute decision guide lists the choices: Amazon EC2 for resizable virtual servers, Elastic Beanstalk for deploying web applications, Lambda for serverless computing, ECS and EKS for container orchestration, and Fargate for serverless containers.',
          'compute-decision',
          ['These include Amazon EC2 for resizable virtual servers, Elastic Beanstalk for deploying web applications on your choice of a number of popular platforms, AWS Lambda for serverless computing, Amazon ECS and EKS for container orchestration, and AWS Fargate for serverless containers.']),
      ],
      services: ['AWS Batch', 'Amazon EMR', 'AWS Fargate', 'Amazon EC2', 'AWS Lambda'],
      design: [
        b('Cue to service: queued, schedulable batch jobs (rendering, simulations, nightly processing) → AWS Batch; Hadoop or Spark big-data processing → EMR; containers without servers → Fargate; short event-driven functions → Lambda; control over the operating system or specialised hardware → EC2.',
          ['batch-what-is', 'emr-what-is'],
          ['batch-what-is|AWS Batch removes the undifferentiated heavy lifting of configuring and managing the required infrastructure',
           'emr-what-is|Amazon EMR, which was previously called Amazon Elastic MapReduce, is a managed cluster platform that simplifies running big data frameworks, such as Apache Hadoop and Apache Spark, on AWS to process and analyze vast amounts of data.']),
      ],
    },
    {
      id: '3.2-S3',
      concepts: [
        b('General purpose instances provide a balance of compute, memory and networking resources, ideal for applications that use these resources in equal proportions, such as web servers and code repositories.',
          'ec2-gp',
          ['General purpose instances provide a balance of compute, memory, and networking resources.',
           'These instances are ideal for applications that use these resources in equal proportions, such as web servers and code repositories.']),
        b('Compute optimized instances are for compute intensive applications that benefit from high performance processors: batch processing, media transcoding, high performance web servers, high performance computing (HPC), scientific modelling, dedicated gaming servers, ad server engines and machine learning inference.',
          'ec2-co',
          ['Compute optimized instances are designed for compute intensive applications that benefit from high performance processors.',
           'These instances are ideal for batch processing workloads, media transcoding, high performance web servers, high performance computing (HPC), scientific modeling, dedicated gaming servers, ad server engines, and machine learning inference.']),
        b('Memory optimized instances deliver fast performance for workloads that process large data sets in memory.',
          'ec2-mo',
          ['Memory optimized instances are designed to deliver fast performance for workloads that process large data sets in memory.']),
        b('Storage optimized instances are for workloads that need high, sequential read and write access to very large data sets on local storage, and are optimised to deliver tens of thousands of low-latency random I/O operations per second (IOPS).',
          'ec2-so',
          ['Storage optimized instances are designed for workloads that require high, sequential read and write access to very large data sets on local storage.',
           'They are optimized to deliver tens of thousands of low-latency, random I/O operations per second (IOPS) to applications.']),
        b('Accelerated computing instances use hardware accelerators or co-processors for functions such as floating point calculations, graphics processing or data pattern matching, more efficiently than software on CPUs.',
          'ec2-ac',
          ['Accelerated computing instances use hardware accelerators, or co-processors, to perform functions, such as floating point number calculations, graphics processing, or data pattern matching, more efficiently than is possible in software running on CPUs.']),
        b('Burstable performance (T) instances provide a baseline level of CPU performance with the ability to burst above the baseline, governed by CPU credits. The baseline is designed for the majority of general purpose workloads such as web servers, small and medium databases and development and test environments.',
          'ec2-instance-types',
          ['Burstable performance (T) instances provide a baseline level of CPU performance with the ability to burst above the baseline.',
           'The baseline utilization and ability to burst are governed by CPU credits.']),
      ],
      services: ['Amazon EC2'],
      design: [
        b('Read the resource that limits the workload: CPU-bound → compute optimized; large in-memory data set → memory optimized; local disk I/O → storage optimized; GPUs or specialised hardware → accelerated; balanced or unknown → general purpose; spiky and mostly idle → burstable.',
          'ec2-instance-types',
          ['Select an instance type based on the requirements of the application or software that you plan to run on your instance.']),
      ],
    },
    {
      id: '3.2-S4',
      concepts: [
        b('For Lambda, memory is the performance setting. Lambda allocates CPU power in proportion to the amount of memory configured, and you can increase or decrease memory and CPU power with the Memory setting. Raise memory when a function is CPU-bound or slow, and measure to find the right size.',
          'lambda-memory',
          ['Lambda allocates CPU power in proportion to the amount of memory configured.',
           'You can increase or decrease the memory and CPU power allocated to your function using the Memory setting.']),
        b('Lambda also has a time limit: a single invocation can run for up to 15 minutes (a quota that can change), so long-running work belongs elsewhere (Batch, Fargate or a workflow).',
          'lambda-quotas',
          ['Code can run for up to 15 minutes in a single invocation']),
        b('For EC2 sizing, changing the instance type resizes the instance (the vertical-scaling move from Scaling Floodgate), and you start paying the rate of the new type.',
          'ec2-resize',
          ['If this is the case, you can resize your instance by changing its instance type.',
           'When you change the instance type, you\'ll start paying the rate of the new instance type.']),
      ],
      services: ['AWS Lambda', 'Amazon EC2'],
      design: [
        b('Cue: Lambda function times out or runs slowly with no code change allowed → increase its memory (which increases CPU); EC2 workload bottleneck on one resource → move to the family that is rich in that resource.',
          'lambda-memory',
          ['Lambda allocates CPU power in proportion to the amount of memory configured.']),
      ],
    },
  ],
  cues: [
    cue('large data sets processed in memory', 'Memory optimized EC2 instances',
      b('Memory optimized instances are designed for workloads that process large data sets in memory.', 'ec2-mo',
        ['Memory optimized instances are designed to deliver fast performance for workloads that process large data sets in memory.'])),
    cue('compute-intensive: batch processing, transcoding, HPC, scientific modelling', 'Compute optimized EC2 instances',
      b('Compute optimized instances suit batch processing, media transcoding and HPC.', 'ec2-co',
        ['These instances are ideal for batch processing workloads, media transcoding, high performance web servers, high performance computing (HPC), scientific modeling, dedicated gaming servers, ad server engines, and machine learning inference.'])),
    cue('high sequential read/write to very large local data sets, tens of thousands of IOPS', 'Storage optimized EC2 instances',
      b('Storage optimized instances target high sequential access to very large local data sets and low-latency random I/O.', 'ec2-so',
        ['They are optimized to deliver tens of thousands of low-latency, random I/O operations per second (IOPS) to applications.'])),
    cue('GPUs, graphics processing, floating point calculations', 'Accelerated computing EC2 instances',
      b('Accelerated computing instances use hardware accelerators or co-processors.', 'ec2-ac',
        ['Accelerated computing instances use hardware accelerators, or co-processors, to perform functions, such as floating point number calculations, graphics processing, or data pattern matching, more efficiently than is possible in software running on CPUs.'])),
    cue('balanced CPU, memory and networking, web servers', 'General purpose EC2 instances',
      b('General purpose instances balance compute, memory and networking.', 'ec2-gp',
        ['General purpose instances provide a balance of compute, memory, and networking resources.'])),
    cue('job queue of batch workloads, provision compute automatically', 'AWS Batch',
      b('AWS Batch provisions resources in response to submitted jobs.', 'batch-what-is',
        ['This service can efficiently provision resources in response to jobs submitted in order to eliminate capacity constraints, reduce compute costs, and deliver results quickly.'])),
    cue('Hadoop or Spark big data processing on managed clusters', 'Amazon EMR',
      b('EMR runs frameworks such as Hadoop and Spark on managed clusters.', 'emr-what-is',
        ['Amazon EMR, which was previously called Amazon Elastic MapReduce, is a managed cluster platform that simplifies running big data frameworks, such as Apache Hadoop and Apache Spark, on AWS to process and analyze vast amounts of data.'])),
    cue('Lambda function is CPU-bound or slow', 'Increase the function\'s memory setting',
      b('Lambda allocates CPU in proportion to memory.', 'lambda-memory',
        ['Lambda allocates CPU power in proportion to the amount of memory configured.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Virtual Machines',
      aws: 'Amazon EC2 instance types',
      mapping: b('Learn pairs EC2 instance types with Azure Virtual Machines and says AWS instance types and Azure VM sizes have similar categories, but the RAM, CPU and storage capabilities differ.',
        ['learn-compute', 'ec2-instance-types'],
        ['learn-compute|AWS instance types and Azure VM sizes have similar categories, but the RAM, CPU, and storage capabilities differ.',
         'ec2-instance-types|Each instance type offers different compute, memory, and storage capabilities, and is grouped in an instance family based on these capabilities.']),
      breaks: b('Do not map instance sizes one to one. Learn says the capabilities differ, so the exam skill is choosing the AWS family (general purpose, compute, memory, storage, accelerated) from the workload, not translating an Azure VM size.',
        ['learn-compute', 'ec2-gp'],
        ['learn-compute|AWS instance types and Azure VM sizes have similar categories, but the RAM, CPU, and storage capabilities differ.',
         'ec2-gp|These instances are ideal for applications that use these resources in equal proportions, such as web servers and code repositories.']),
    },
    {
      concept: 'Azure Batch',
      aws: 'AWS Batch',
      mapping: b('Learn pairs AWS Batch with Azure Batch: managing compute-intensive work across a scalable collection of VMs.',
        ['learn-compute', 'batch-what-is'],
        ['learn-compute|Azure Batch helps you manage compute-intensive work across a scalable collection of VMs.',
         'batch-what-is|AWS Batch automatically provisions compute resources and optimizes the workload distribution based on the quantity and scale of the workloads.']),
      breaks: b('AWS Batch provisions the compute for submitted jobs for you. On AWS the related big-data choice is a separate service, Amazon EMR, for Hadoop and Spark clusters.',
        ['emr-what-is', 'learn-compute'],
        ['emr-what-is|Amazon EMR, which was previously called Amazon Elastic MapReduce, is a managed cluster platform that simplifies running big data frameworks, such as Apache Hadoop and Apache Spark, on AWS to process and analyze vast amounts of data.',
         'learn-compute|Azure Batch helps you manage compute-intensive work across a scalable collection of VMs.']),
    },
  ],
};

export default notes;
