import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'express-interchange',
  overview: [
    b('Elastic Load Balancing offers different load balancers for different traffic. Scaling Floodgate and Single-Point Watch explained why you use one; this building is about choosing among them. AWS describes each type by the layer of the Open Systems Interconnection (OSI) model it works at, and by features such as static IP addresses and PrivateLink support.',
      ['elb-what-is', 'alb-intro', 'elb-features'],
      ['elb-what-is|Elastic Load Balancing automatically distributes your incoming traffic across multiple targets, such as EC2 instances, containers, and IP addresses, in one or more Availability Zones.',
       'elb-features|Load Balancer type Layer 7 Layer 4 Layer 3 Gateway + Layer 4 Load Balancing Layer 4/7',
       'alb-intro|Elastic Load Balancing supports the following load balancers: Application Load Balancers, Network Load Balancers, Gateway Load Balancers, and Classic Load Balancers.']),
  ],
  bullets: [
    {
      id: '3.4-K3',
      concepts: [
        b('Every load balancer has the same building blocks. A listener checks for connection requests from clients using the protocol and port you configure, and forwards them to a target group, which routes requests to one or more registered targets using the protocol and port you specify; health checks are configured per target group.',
          'nlb-intro',
          ['A listener checks for connection requests from clients, using the protocol and port that you configure, and forwards requests to a target group.',
           'A target group routes requests to one or more registered targets, such as EC2 instances, using the protocol and the port number that you specify.',
           'You can configure health checks on a per target group basis.']),
        b('An Application Load Balancer evaluates listener rules in priority order and can route requests to different target groups based on the content of the application traffic. Path conditions let you structure an application as smaller services and route to the correct service based on the URL; host conditions route on the host field in the HTTP header.',
          'alb-intro',
          ['After the load balancer receives a request, it evaluates the listener rules in priority order to determine which rule to apply, and then selects a target from the target group for the rule action.',
           'This enables you to structure your application as smaller services, and route requests to the correct service based on the content of the URL.',
           'You can configure rules for your listener that forward requests based on the host field in the HTTP header.']),
        b('Application Load Balancers provide native support for WebSockets and can use ACM-provided certificates for HTTPS listeners; they work with AWS WAF. WebSockets are not a reason to rule out a Network Load Balancer, since AWS lists WebSocket support for the Network Load Balancer as well.',
          ['alb-listeners', 'alb-intro', 'elb-what-is', 'elb-features'],
          ['alb-listeners|Application Load Balancers provide native support for WebSockets.',
           'elb-features|Preserve Source IP address ✔ ✔ ✔ - WebSockets ✔ ✔ ✔ -',
           'alb-intro|AWS Certificate Manager — When you create an HTTPS listener, you can specify certificates provided by ACM.',
           'elb-what-is|AWS WAF — You can use AWS WAF with your Application Load Balancer to allow or block requests based on the rules in a web access control list (web ACL).']),
        b('A Network Load Balancer node distributes traffic, by default, across the registered targets in its own Availability Zone only; if you enable cross-zone load balancing each node distributes across targets in all enabled zones. Enable more than one zone to increase fault tolerance.',
          'nlb-intro',
          ['By default, each load balancer node distributes traffic across the registered targets in its Availability Zone only.',
           'If you enable cross-zone load balancing, each load balancer node distributes traffic across the registered targets in all enabled Availability Zones.']),
        b('The previous-generation Classic Load Balancer is still documented, but AWS recommends that you migrate to a current generation load balancer.',
          'elb-what-is',
          ['Classic Load Balancers are the previous generation of load balancers from Elastic Load Balancing.',
           'We recommend that you migrate to a current generation load balancer.']),
      ],
      services: ['Elastic Load Balancing (ELB)'],
      design: [
        b('Cue: content-based rules (path, host), redirects or user authentication on the load balancer → Application Load Balancer; a fixed IP address or Elastic IP, raw TCP or UDP at very high volume → Network Load Balancer; a fleet of virtual appliances such as firewalls placed inline → Gateway Load Balancer.',
          ['alb-intro', 'nlb-intro', 'gwlb-intro', 'elb-features'],
          ['elb-features|If extreme performance and static IP is needed for your application, we recommend that you use a Network Load Balancer.',
           'elb-features|Redirects ✔ - - - Fixed Response ✔ - - -',
           'elb-features|User Authentication ✔ - - -',
           'gwlb-intro|Gateway Load Balancers enable you to deploy, scale, and manage virtual appliances, such as firewalls, intrusion detection and prevention systems, and deep packet inspection systems.']),
      ],
    },
    {
      id: '3.4-S4',
      concepts: [
        b('Select by traffic type. Application Load Balancer: seventh-layer content-based routing, microservices behind paths or hosts, WAF. Network Load Balancer: fourth-layer TCP, UDP or TLS traffic at very high volume, and static IP addresses per zone with optional Elastic IPs. Gateway Load Balancer: third-layer, transparent insertion of firewalls, intrusion prevention and deep packet inspection appliances.',
          ['alb-intro', 'nlb-intro', 'gwlb-intro'],
          ['alb-intro|An Application Load Balancer functions at the application layer, the seventh layer of the Open Systems Interconnection (OSI) model.',
           'nlb-intro|Network Load Balancer functions at the fourth layer of the Open Systems Interconnection (OSI) model.',
           'nlb-intro|When you create an Internet-facing load balancer, you can optionally associate one Elastic IP address per subnet.',
           'gwlb-intro|A Gateway Load Balancer operates at the third layer of the Open Systems Interconnection (OSI) model, the network layer.']),
        b('A Network Load Balancer can handle millions of requests per second and gives each enabled zone a network interface with a static IP address, which matters when clients must allow-list fixed addresses.',
          'nlb-intro',
          ['It can handle millions of requests per second.',
           'Each load balancer node in the Availability Zone uses this network interface to get a static IP address.']),
        b('A Gateway Load Balancer endpoint is a VPC endpoint that provides private connectivity between virtual appliances in the service provider VPC and application servers in the service consumer VPC.',
          'gwlb-intro',
          ['A Gateway Load Balancer endpoint is a VPC endpoint that provides private connectivity between virtual appliances in the service provider VPC and application servers in the service consumer VPC.']),
        b('Two more selection facts. When a requirement is for a static IP address, AWS recommends the Network Load Balancer, and Global Accelerator is the other AWS service that provides static IP addresses (anycast from the AWS edge network). A PrivateLink endpoint service requires either a Network Load Balancer or a Gateway Load Balancer in front of it.',
          ['elb-features', 'ga-what-is', 'privatelink-service'],
          ['elb-features|If extreme performance and static IP is needed for your application, we recommend that you use a Network Load Balancer.',
           'ga-what-is|By default, Global Accelerator provides you with static IP addresses that you associate with your accelerator.',
           'ga-what-is|The static IP addresses are anycast from the AWS edge network.',
           'privatelink-service|Endpoint services require either a Network Load Balancer or a Gateway Load Balancer.'],
          { allow: ['two'] }),
        b('A Gateway Load Balancer maintains flow stickiness to a specific target appliance, so both directions of a flow go through the same appliance, and it scales the appliances with demand.',
          'gwlb-intro',
          ['It maintains flow stickiness to a specific target appliance using 5-tuple (default), 3-tuple, or 2-tuple.',
           'It combines a transparent network gateway (that is, a single entry and exit point for all traffic) and distributes traffic while scaling your virtual appliances with the demand.'],
          { allow: ['two'] }),
      ],
      services: ['Elastic Load Balancing (ELB)'],
      design: [
        b('Cue chain: HTTP/HTTPS with routing rules or WAF → ALB; TCP/UDP, extreme performance or static IPs → NLB; inline third-party appliance fleet → GWLB; exposing a service to other VPCs or accounts through PrivateLink → an NLB (or GWLB) in front of it. If two answers seem possible, compare the layer each operates at and the features above.',
          ['alb-intro', 'nlb-intro', 'gwlb-intro', 'privatelink-service'],
          ['alb-intro|You can configure listener rules to route requests to different target groups based on the content of the application traffic.',
           'nlb-intro|Network Load Balancer functions at the fourth layer of the Open Systems Interconnection (OSI) model.',
           'gwlb-intro|Gateway Load Balancers enable you to deploy, scale, and manage virtual appliances, such as firewalls, intrusion detection and prevention systems, and deep packet inspection systems.',
           'privatelink-service|Endpoint services require either a Network Load Balancer or a Gateway Load Balancer.']),
      ],
    },
  ],
  cues: [
    cue('route /images to one target group and /api to another', 'Application Load Balancer path-based routing',
      b('Path conditions route requests to the correct service based on the URL.', 'alb-intro',
        ['This enables you to structure your application as smaller services, and route requests to the correct service based on the content of the URL.'])),
    cue('route by host name (api.example.com vs www.example.com)', 'Application Load Balancer host-based routing',
      b('Host conditions forward requests based on the host field in the HTTP header.', 'alb-intro',
        ['You can configure rules for your listener that forward requests based on the host field in the HTTP header.'])),
    cue('static IP addresses / Elastic IP for the load balancer; TCP or UDP', 'Network Load Balancer',
      b('A Network Load Balancer gives each enabled zone a static IP address and allows Elastic IPs on internet-facing balancers.', 'nlb-intro',
        ['When you create an Internet-facing load balancer, you can optionally associate one Elastic IP address per subnet.'])),
    cue('millions of requests per second, fourth layer', 'Network Load Balancer',
      b('A Network Load Balancer works at the fourth layer and can handle millions of requests per second.', 'nlb-intro',
        ['It can handle millions of requests per second.'])),
    cue('expose your service to other VPCs through AWS PrivateLink', 'A Network Load Balancer (or Gateway Load Balancer) as the endpoint service front end',
      b('Endpoint services require either a Network Load Balancer or a Gateway Load Balancer.', 'privatelink-service',
        ['Endpoint services require either a Network Load Balancer or a Gateway Load Balancer.'])),
    cue('deploy firewall or intrusion detection virtual appliances behind a transparent gateway', 'Gateway Load Balancer',
      b('Gateway Load Balancers deploy, scale and manage virtual appliances.', 'gwlb-intro',
        ['Gateway Load Balancers enable you to deploy, scale, and manage virtual appliances, such as firewalls, intrusion detection and prevention systems, and deep packet inspection systems.'])),
    cue('integrate AWS WAF with the load balancer', 'Application Load Balancer',
      b('AWS WAF can be used with an Application Load Balancer.', 'elb-what-is',
        ['AWS WAF — You can use AWS WAF with your Application Load Balancer to allow or block requests based on the rules in a web access control list (web ACL).'])),
    cue('WebSocket connections combined with path or host routing rules', 'Application Load Balancer',
      b('Application Load Balancers provide native support for WebSockets, and their listener rules route on content.', 'alb-listeners',
        ['Application Load Balancers provide native support for WebSockets.'])),
  ],
  examples: [],
  confuse: ['alb-nlb-gwlb'],
  azure: [
    {
      concept: 'Azure Load Balancer',
      aws: 'Network Load Balancer',
      mapping: b('Learn pairs the AWS Network Load Balancer with Azure Load Balancer, which provides the same network-level capabilities for TCP or UDP traffic.',
        ['learn-networking', 'nlb-intro'],
        ['learn-networking|Load Balancer provides the same network layer 4 capabilities as the AWS Network Load Balancer, so you can distribute traffic for multiple VMs at the network level.',
         'learn-networking|Azure Load Balancer load balances traffic at layer 4 (TCP or UDP).',
         'nlb-intro|Network Load Balancer functions at the fourth layer of the Open Systems Interconnection (OSI) model.']),
      breaks: b('The Learn comparison lists two Azure counterparts, Load Balancer for the fourth layer and Application Gateway for application-level routing, and does not mention the AWS Gateway Load Balancer. A separate Learn page does describe an Azure analogue: Gateway Load Balancer is a SKU of Azure Load Balancer for third-party network virtual appliances, the same job as the AWS Gateway Load Balancer.',
        ['gwlb-intro', 'learn-networking', 'learn-azure-gwlb'],
        ['gwlb-intro|Gateway Load Balancers enable you to deploy, scale, and manage virtual appliances, such as firewalls, intrusion detection and prevention systems, and deep packet inspection systems.',
         'learn-networking|Load Balancer provides the same network layer 4 capabilities as the AWS Network Load Balancer, so you can distribute traffic for multiple VMs at the network level.',
         'learn-networking|Application Gateway provides application-level rule-based routing comparable to that of the AWS Application Load Balancer.',
         'learn-azure-gwlb|Gateway Load Balancer is a SKU of the Azure Load Balancer portfolio designed for high performance and high availability scenarios with third-party Network Virtual Appliances (NVAs).'],
        { allow: ['two'] }),
    },
    {
      concept: 'Azure Application Gateway',
      aws: 'Application Load Balancer',
      mapping: b('Learn pairs Azure Application Gateway with the AWS Application Load Balancer for application-level rule-based routing.',
        ['learn-networking', 'alb-intro'],
        ['learn-networking|Application Gateway provides application-level rule-based routing comparable to that of the AWS Application Load Balancer.',
         'alb-intro|An Application Load Balancer functions at the application layer, the seventh layer of the Open Systems Interconnection (OSI) model.']),
      breaks: b('The AWS Application Load Balancer works at the application layer, the seventh layer, and routes on listener rules such as path and host conditions. Learn describes Application Gateway only as comparable application-level rule-based routing; the match is by role, not feature for feature.',
        ['alb-intro', 'learn-networking'],
        ['alb-intro|An Application Load Balancer functions at the application layer, the seventh layer of the Open Systems Interconnection (OSI) model.',
         'alb-intro|You can configure rules for your listener that forward requests based on the host field in the HTTP header.',
         'learn-networking|Application Gateway provides application-level rule-based routing comparable to that of the AWS Application Load Balancer.']),
    },
  ],
};

export default notes;
