import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'express-rail-hub',
  overview: [
    b('A queue between components lets each side scale at its own pace. Producers add messages as fast as they like, the queue holds them, and a pool of consumers drains the queue; you scale the consumers on how much is waiting, not on how fast the producers send. Publish/subscribe adds the other shape: one message pushed to many receivers. Message Quay compares SQS, SNS, EventBridge and Kinesis; this building is about scaling with them.',
      ['sns-sqs-fanout', 'asg-sqs'],
      ['sns-sqs-fanout|It decouples sending and receiving components—without requiring each component to be available at the same time.',
       'sns-sqs-fanout|Amazon SNS lets applications send time-critical messages to multiple subscribers through a “push” mechanism.',
       'asg-sqs|You can scale your Auto Scaling group in response to changes in system load in an Amazon Simple Queue Service (Amazon SQS) queue.']),
  ],
  bullets: [
    {
      id: '3.2-K3',
      concepts: [
        b('Queuing: Amazon SQS is a message queue service that distributed applications use to exchange messages through a polling model. It decouples sending and receiving components without requiring each component to be available at the same time. Standard queues give at-least-once delivery, may deliver more than one copy of a message, and messages may occasionally arrive out of order; FIFO queues strictly preserve order and deliver each message once.',
          ['sns-sqs-fanout', 'sqs-standard', 'sqs-fifo'],
          ['sns-sqs-fanout|Amazon SQS is a message queue service that distributed applications use to exchange messages through a polling model.',
           'sqs-standard|Standard queues ensure at-least-once message delivery, but due to the highly distributed architecture, more than one copy of a message might be delivered, and messages may occasionally arrive out of order.',
           'sqs-fifo|The order in which messages are sent and received is strictly preserved and a message is delivered once and remains unavailable until a consumer processes and deletes it.']),
        b('Publish/subscribe: Amazon SNS lets applications send time-critical messages to multiple subscribers through a push mechanism, which removes the need to check or poll for updates.',
          'sns-sqs-fanout',
          ['Amazon SNS lets applications send time-critical messages to multiple subscribers through a “push” mechanism.',
           'This removes the need to check or “poll” for updates.']),
        b('Using SNS and SQS together, messages reach applications that need instant notification of an event, and the messages also persist in an SQS queue for other consumers to process later. This is the fanout pattern.',
          'sns-sqs-fanout',
          ['When you use Amazon SNS and Amazon SQS together, messages reach applications that need instant notification of an event.']),
        b('Some SQS settings matter for consumers. The {{term:visibility-timeout}} hides a received message from other consumers while you work on it. Long polling queries all servers and responds once a message is available, which can reduce the number of empty responses and potentially lower costs, compared with short polling (the default).',
          ['sqs-visibility', 'sqs-polling'],
          ['sqs-visibility|This invisibility is controlled by the visibility timeout, which ensures that other consumers cannot process the same message while you are working on it.',
           'sqs-polling|Long polling – ReceiveMessage queries all servers for messages, sending a response once at least one message is available, up to the specified maximum.',
           'sqs-polling|This option can reduce the number of empty responses and potentially lower costs.',
           'sqs-polling|Short polling (default) – The ReceiveMessage request queries a subset of servers (based on a weighted random distribution) to find available messages and sends an immediate response, even if no messages are found.']),
      ],
      services: ['Amazon SQS', 'Amazon SNS'],
      design: [
        b('Cue: workers pull when ready and the order does not matter → standard queue; order and no duplicates matter → FIFO queue; many systems must react to the same event → SNS (often fanning out to one SQS queue per consumer).',
          ['sqs-fifo', 'sns-sqs-fanout'],
          ['sqs-fifo|FIFO (First-In-First-Out) queues have all the capabilities of the standard queues, but are designed to enhance messaging between applications when the order of operations and events is critical, or where duplicates can\'t be tolerated.',
           'sns-sqs-fanout|When you use Amazon SNS and Amazon SQS together, messages reach applications that need instant notification of an event.']),
      ],
    },
    {
      id: '3.2-S1',
      concepts: [
        b('Decoupling lets a producer tier and a consumer tier scale independently. The AWS example is a web app that accepts image uploads and places the raw data in an SQS queue, while an Auto Scaling group of EC2 instances processes and publishes the images. If the number of uploads varies over time, use dynamic scaling on the consumer group.',
          'asg-sqs',
          ['The app places the raw bitmap data of the images in an SQS queue for processing.',
           'The architecture for this scenario works well if the number of image uploads doesn\'t vary over time. But if the number of uploads changes over time, you might consider using dynamic scaling to scale the capacity of your Auto Scaling group.']),
        b('The scaling metric for queue consumers is the backlog per instance, not the raw queue length, because the number of messages in the queue does not solely define the number of instances needed. A target tracking policy based on a custom SQS queue metric lets dynamic scaling adjust to the demand curve more effectively.',
          'asg-sqs',
          ['The solution is to use a backlog per instance metric with the target value being the acceptable backlog per instance to maintain.',
           'That\'s because the number of messages in your SQS queue does not solely define the number of instances needed.',
           'If you use a target tracking scaling policy based on a custom Amazon SQS queue metric, dynamic scaling can adjust to the demand curve of your application more effectively.']),
        b('Amazon SQS stores each message redundantly in multiple Availability Zones before acknowledging it, and the queue decouples sending and receiving without requiring each component to be available at the same time, so a burst of messages waits in the queue until consumers have capacity.',
          ['sqs-standard', 'sns-sqs-fanout'],
          ['sqs-standard|Amazon SQS redundantly stores the message in multiple availability zones (AZs) before acknowledging it.',
           'sns-sqs-fanout|It decouples sending and receiving components—without requiring each component to be available at the same time.']),
        b('Messages that are not processed successfully can be moved to a dead-letter queue (DLQ), and the idempotent processing principle keeps retries safe.',
          ['sqs-dlq', 'waf-idempotent'],
          ['sqs-dlq|Amazon SQS supports dead-letter queues (DLQs), which source queues can target for messages that are not processed successfully.',
           'waf-idempotent|To do this, clients can issue API requests with an idempotency token, which is used whenever the request is repeated.']),
      ],
      services: ['Amazon SQS', 'Amazon SNS', 'Amazon EC2 Auto Scaling'],
      design: [
        b('Pattern for "components must scale independently" or "traffic spikes overwhelm the processing tier": put an SQS queue between the tiers, scale the consumers on queue backlog, and let the web tier return once the message is queued instead of processing it synchronously.',
          'asg-sqs',
          ['There are some scenarios where you might think about scaling in response to activity in an Amazon SQS queue.']),
      ],
    },
  ],
  cues: [
    cue('spikes in requests overwhelm the processing tier; tiers should scale independently', 'Insert an SQS queue and scale consumers on queue backlog',
      b('The AWS scaling example puts image data in an SQS queue and scales the processing group dynamically.', 'asg-sqs',
        ['The app places the raw bitmap data of the images in an SQS queue for processing.'])),
    cue('order of operations is critical and duplicates cannot be tolerated', 'SQS FIFO queue',
      b('FIFO queues preserve order and avoid duplicates.', 'sqs-fifo',
        ['FIFO (First-In-First-Out) queues have all the capabilities of the standard queues, but are designed to enhance messaging between applications when the order of operations and events is critical, or where duplicates can\'t be tolerated.'])),
    cue('push one message to many subscribers', 'Amazon SNS (often fanning out to SQS queues)',
      b('SNS pushes time-critical messages to multiple subscribers.', 'sns-sqs-fanout',
        ['Amazon SNS lets applications send time-critical messages to multiple subscribers through a “push” mechanism.'])),
    cue('reduce empty receives and polling cost', 'SQS long polling',
      b('Long polling can reduce empty responses and potentially lower costs.', 'sqs-polling',
        ['This option can reduce the number of empty responses and potentially lower costs.'])),
    cue('two consumers must not process the same message at once', 'SQS visibility timeout',
      b('The visibility timeout stops other consumers processing a message you are working on.', 'sqs-visibility',
        ['This invisibility is controlled by the visibility timeout, which ensures that other consumers cannot process the same message while you are working on it.'])),
  ],
  examples: [],
  confuse: [],
};

export default notes;
