import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'freight-depot',
  overview: [
    b('This building turns the storage types of Cargo Hall into performance and scale decisions: which service meets the I/O demand, which one grows with the business, and how on-premises systems reach AWS storage through a gateway. The detailed EBS, EFS and FSx comparison is in Storage Market.',
      ['storage-decision', 's3-performance', 'efs-what-is'],
      ['storage-decision|You can select from block, file, and object storage services as well as cloud data migration options for your workload.',
       's3-performance|There are no limits to the number of prefixes in a bucket.',
       'efs-what-is|Amazon EFS is built to scale on demand to petabytes without disrupting applications, growing and shrinking automatically as you add and remove files.']),
  ],
  beyondProject: [
    b('Your static site uses S3 as object storage. SAA asks how it behaves at scale: S3 performance scales by spreading requests across prefixes, and S3 can store any amount of data. It also asks when S3 is the wrong tool: an operating system disk needs block storage (EBS), and a shared mounted file system needs file storage (EFS or FSx).',
      ['s3-performance', 's3-what-is'],
      ['s3-performance|For example, your application can achieve at least 3,500 PUT/COPY/POST/DELETE or 5,500 GET/HEAD requests per second per partitioned Amazon S3 prefix.',
       's3-what-is|Customers of all sizes and industries can use Amazon S3 to store and protect any amount of data for a range of use cases, such as data lakes, websites, mobile applications, backup and restore, archive, enterprise applications, IoT devices, and big data analytics.']),
  ],
  bullets: [
    {
      id: '3.1-K1',
      concepts: [
        b('AWS Storage Gateway connects an on-premises software appliance with cloud-based storage to provide seamless and secure integration between your on-premises IT environment and the AWS storage infrastructure. It offers file-based (S3 File Gateway and FSx File Gateway), volume-based (Volume Gateway) and tape-based (Tape Gateway) solutions. FSx File Gateway is no longer available to new customers, so the file gateway to choose for a new design is S3 File Gateway.',
          ['storage-gateway-docs', 'sgw-volume', 'sgw-fsx-file'],
          ['storage-gateway-docs|AWS Storage Gateway is a service that connects an on-premises software appliance with cloud-based storage to provide seamless and secure integration between your on-premises IT environment and the AWS storage infrastructure in the AWS Cloud.',
           'sgw-volume|AWS Storage Gateway offers file-based (S3 File Gateway and FSx File Gateway), volume-based (Volume Gateway), and tape-based (Tape Gateway) storage solutions.',
           'sgw-fsx-file|Amazon FSx File Gateway is no longer available to new customers.']),
        b('S3 File Gateway supports a file interface into Amazon S3: applications store and retrieve files directly using NFS version 3 or 4.1, or using SMB version 2 and 3, and you can think of it as a file system mount on S3. It provides a cost-effective alternative to on-premises storage.',
          'sgw-file-s3',
          ['With a S3 File Gateway, you can do the following: You can store and retrieve files directly using the NFS version 3 or 4.1 protocol.',
           'You can store and retrieve files directly using the SMB file system version, 2 and 3 protocol.',
           'You can think of a S3 File Gateway as a file system mount on Amazon S3.',
           'A S3 File Gateway simplifies file storage in Amazon S3, integrates to existing applications through industry-standard file system protocols, and provides a cost-effective alternative to on-premises storage.']),
        b('Volume Gateway provides cloud-backed storage volumes that you can mount as iSCSI devices from your on-premises application servers. Tape Gateway provides cloud-backed virtual tape storage, so you can archive backup data durably in S3 Glacier Flexible Retrieval or S3 Glacier Deep Archive.',
          ['sgw-volume', 'sgw-tape'],
          ['sgw-volume|Volume Gateway provides cloud-backed storage volumes that you can mount as Internet Small Computer System Interface (iSCSI) devices from your on-premises application servers.',
           'sgw-tape|Tape Gateway provides cloud-backed virtual tape storage.',
           'sgw-tape|With Tape Gateway, you can cost-effectively and durably archive backup data in S3 Glacier Flexible Retrieval or S3 Glacier Deep Archive.']),
        b('Amazon FSx File Gateway is no longer available to new customers; existing customers can continue to use it normally. Do not choose it for a new design.',
          'sgw-fsx-file',
          ['Amazon FSx File Gateway is no longer available to new customers.',
           'Existing customers of FSx File Gateway can continue to use the service normally.'],
          { status: 'deprecated' }),
      ],
      services: ['AWS Storage Gateway'],
      design: [
        b('Match the on-premises protocol to the gateway: NFS or SMB file shares backed by S3 → S3 File Gateway (including Windows clients that use SMB); block volumes over iSCSI → Volume Gateway; backup software that expects tape → Tape Gateway. Bulk one-time moves are a different tool (Transfer Dock).',
          ['sgw-file-s3', 'sgw-volume', 'sgw-tape'],
          ['sgw-file-s3|You can think of a S3 File Gateway as a file system mount on Amazon S3.',
           'sgw-volume|Volume Gateway provides cloud-backed storage volumes that you can mount as Internet Small Computer System Interface (iSCSI) devices from your on-premises application servers.',
           'sgw-tape|Tape Gateway provides cloud-backed virtual tape storage.']),
      ],
    },
    {
      id: '3.1-K2',
      concepts: [
        b('Amazon S3 stores any amount of data as objects for uses such as data lakes, websites, mobile applications, backup and restore, archive and big data analytics. Amazon EFS provides serverless, elastic file storage shared over NFS. Amazon EBS provides block volumes attached to EC2 instances.',
          ['s3-what-is', 'efs-what-is', 'ebs-what-is'],
          ['s3-what-is|Customers of all sizes and industries can use Amazon S3 to store and protect any amount of data for a range of use cases, such as data lakes, websites, mobile applications, backup and restore, archive, enterprise applications, IoT devices, and big data analytics.',
           'efs-what-is|Amazon Elastic File System (Amazon EFS) provides serverless, fully elastic file storage so that you can share file data without provisioning or managing storage capacity and performance.',
           'ebs-what-is|Amazon Elastic Block Store (Amazon EBS) provides scalable, high-performance block storage resources that can be used with Amazon Elastic Compute Cloud (Amazon EC2) instances.']),
        b('For container workloads on Amazon EKS you can attach file and block storage through Container Storage Interface (CSI) drivers, such as the Amazon EFS CSI driver and the Amazon EBS CSI driver.',
          'storage-decision',
          ['For container workloads, you can provide file, block, and object access to workloads on Amazon EKS: Attach file and block storage through Container Storage Interface (CSI) drivers, such as the Amazon EFS CSI driver and the Amazon EBS CSI driver.']),
        b('Amazon FSx for Lustre is a high-performance file system for workloads where speed matters, such as machine learning, high performance computing (HPC), video processing and financial modeling, and you can link its file systems to data repositories on Amazon S3. EBS Multi-Attach is an exception to one-instance block storage: it lets you attach a single Provisioned IOPS SSD (io1 or io2) volume to multiple instances in the same Availability Zone.',
          ['fsx-lustre', 'ebs-multi-attach'],
          ['fsx-lustre|You use Lustre for workloads where speed matters, such as machine learning, high performance computing (HPC), video processing, and financial modeling.',
           'fsx-lustre|You can link FSx for Lustre file systems to data repositories on Amazon S3 or to on-premises data stores.',
           'ebs-multi-attach|Amazon EBS Multi-Attach enables you to attach a single Provisioned IOPS SSD (io1 or io2) volume to multiple instances that are in the same Availability Zone.']),
      ],
      services: ['Amazon S3', 'Amazon EFS', 'Amazon EBS'],
      design: [
        b('Pick the service by access method first (API objects, mounted shared files, attached disk), then tune with the performance and scale facts below.',
          'storage-decision',
          ['Protocols play a crucial role when considering AWS storage services as they determine how data is accessed, transferred, and managed within the storage environment.']),
      ],
    },
    {
      id: '3.1-K3',
      concepts: [
        b('Object, file and block are the storage types: object storage manages data as objects accessed through an API and suits read-heavy workloads, block storage is direct-attached high-performance storage with low-latency access, and file storage is a hierarchy of files and folders mountable over NFS or SMB. Cargo Hall has the full definitions.',
          'storage-decision',
          ['Object storage provides easy access to data through an application programming interface (API) over the internet and is well-suited to read-heavy workloads (such as streaming applications and services).',
           'Block storage offers high-performance storage that is direct-attached to a compute instance with low-latency access, making it suitable for applications that require fast and consistent I/O operations.',
           'File-based storage is natively mountable from virtually any operating system using industry-standard protocols like NFS and SMB.']),
      ],
      services: ['Amazon S3', 'Amazon EFS', 'Amazon EBS'],
      design: [
        b('The characteristics to compare: access method, latency, shareability (usually one instance for block, with EBS Multi-Attach as the exception for io1 and io2 volumes in one Availability Zone; many clients for file; many applications by API for object), and scale.',
          ['storage-decision', 'ebs-multi-attach'],
          ['storage-decision|Applications and workloads requiring shared read and write access across multiple Amazon EC2 instances or containers, or from multiple on-premises servers, such as team file shares, highly available enterprise applications, analytics workloads, and ML training.',
           'ebs-multi-attach|Amazon EBS Multi-Attach enables you to attach a single Provisioned IOPS SSD (io1 or io2) volume to multiple instances that are in the same Availability Zone.']),
      ],
    },
    {
      id: '3.1-S1',
      concepts: [
        b('S3 request performance scales by prefix: an application can achieve at least 3,500 PUT/COPY/POST/DELETE or 5,500 GET/HEAD requests per second per partitioned prefix, there are no limits to the number of prefixes in a bucket, and you can scale writes and reads by using multiple prefixes in parallel. "At least" matters: AWS documents these as floors, not ceilings.',
          's3-performance',
          ['For example, your application can achieve at least 3,500 PUT/COPY/POST/DELETE or 5,500 GET/HEAD requests per second per partitioned Amazon S3 prefix.',
           'There are no limits to the number of prefixes in a bucket.',
           'Similarly, you can scale write operations by writing to multiple prefixes.']),
        b('Multipart upload and S3 Transfer Acceleration both help S3 transfer performance. Multipart upload is a best practice for objects that are 100 MB or larger, and parts can be uploaded in parallel to improve throughput. S3 Transfer Acceleration is a bucket-level feature for fast transfers of files over long distances between a client and an S3 general purpose bucket.',
          ['s3-multipart', 's3-transfer-acceleration'],
          ['s3-multipart|It\'s a best practice to use multipart upload for objects that are 100 MB or larger instead of uploading them in a single operation.',
           's3-multipart|Improved throughput – You can upload parts in parallel to improve throughput.',
           's3-transfer-acceleration|Amazon S3 Transfer Acceleration is a bucket-level feature that enables fast, easy, and secure transfers of files over long distances between your client and an S3 general purpose bucket.']),
        b('EBS SSD volume types: General Purpose SSD (gp3) suits transactional workloads, virtual desktops, medium-sized single-instance databases, low-latency interactive applications, boot volumes and development and test. Provisioned IOPS SSD (io2 Block Express) is for workloads that need consistent sub-millisecond latency, sustained IOPS performance, and I/O-intensive database workloads.',
          'ebs-volume-types',
          ['Transactional workloadsVirtual desktopsMedium-sized, single-instance databasesLow-latency interactive applicationsBoot volumesDevelopment and test environments',
           'Consistent sub-millisecond latency with average latency under 500 microseconds',
           'I/O-intensive database workloads']),
        b('EBS HDD volume types are optimised for large streaming workloads where throughput is the dominant performance attribute: Throughput Optimized HDD (st1) for big data, data warehouses and log processing, and Cold HDD (sc1) for infrequently accessed data where the lowest storage cost matters.',
          'ebs-volume-types',
          ['HDD-backed volumes are optimized for large streaming workloads where the dominant performance attribute is throughput.',
           'Big data Data warehouses Log processing Throughput-oriented storage for data that is infrequently accessed Scenarios where the lowest storage cost is important']),
        b('EFS performance is shaped by the file system type (Regional or One Zone), the performance mode (General Purpose or Max I/O) and the throughput mode (Elastic, Provisioned or Bursting). Max I/O has higher per-operation latencies than General Purpose, and AWS recommends General Purpose for faster performance.',
          'efs-performance',
          ['The following configurations impact the performance of an Amazon EFS file system: File system type – Regional or One ZonePerformance mode – General Purpose or Max I/O ImportantMax I/O performance mode has higher per-operation latencies than General Purpose performance mode.',
           'For faster performance, we recommend always using General Purpose performance mode.',
           'Throughput mode – Elastic, Provisioned, or Bursting']),
      ],
      services: ['Amazon S3', 'Amazon EBS', 'Amazon EFS'],
      design: [
        b('Cue to configuration: an I/O-intensive database on EC2 → Provisioned IOPS SSD; a general boot or dev volume → General Purpose SSD; sequential big-data, data warehouse or log-processing throughput → st1; infrequently accessed data where the lowest storage cost matters → sc1; very many requests to S3 → spread across prefixes (and consider caching in front, see Cache & Edge Breakwater).',
          'ebs-volume-types',
          ['I/O-intensive database workloads', 'Transactional workloadsVirtual desktopsMedium-sized, single-instance databasesLow-latency interactive applicationsBoot volumesDevelopment and test environments']),
      ],
    },
    {
      id: '3.1-S2',
      concepts: [
        b('S3 stores any amount of data, and EFS is built to scale on demand to petabytes without disrupting applications, growing and shrinking automatically as you add and remove files. EBS volumes have a defined size range per type, and with Elastic Volumes you can increase the volume size, change the volume type or adjust performance of an EBS volume.',
          ['s3-what-is', 'efs-what-is', 'ebs-volume-types', 'ebs-modify'],
          ['s3-what-is|Customers of all sizes and industries can use Amazon S3 to store and protect any amount of data for a range of use cases, such as data lakes, websites, mobile applications, backup and restore, archive, enterprise applications, IoT devices, and big data analytics.',
           'efs-what-is|Amazon EFS is built to scale on demand to petabytes without disrupting applications, growing and shrinking automatically as you add and remove files.',
           'ebs-volume-types|Volume size 1 GiB - 64 TiB 1 GiB - 16 TiB 4 GiB - 64 TiB 4 GiB - 16 TiB',
           'ebs-modify|With Amazon EBS Elastic Volumes, you can increase the volume size, change the volume type, or adjust the performance of your EBS volumes.']),
        b('Planning for future needs also means choosing storage that does not need provisioning ahead of time: EFS lets you share file data without provisioning or managing storage capacity and performance, and Storage Gateway extends on-premises systems into S3.',
          'efs-what-is',
          ['Amazon Elastic File System (Amazon EFS) provides serverless, fully elastic file storage so that you can share file data without provisioning or managing storage capacity and performance.']),
      ],
      services: ['Amazon S3', 'Amazon EFS', 'Amazon EBS'],
      design: [
        b('Cue: capacity unknown and growing, shared by many clients → EFS or S3; a sized volume attached to an instance → EBS (Elastic Volumes lets you increase its size when needed).',
          ['efs-what-is', 'ebs-modify'],
          ['efs-what-is|Amazon EFS is built to scale on demand to petabytes without disrupting applications, growing and shrinking automatically as you add and remove files.',
           'ebs-modify|With Amazon EBS Elastic Volumes, you can increase the volume size, change the volume type, or adjust the performance of your EBS volumes.']),
      ],
    },
  ],
  cues: [
    cue('on-premises application mounts NFS or SMB shares that are stored in S3', 'S3 File Gateway',
      b('S3 File Gateway lets applications store and retrieve files over NFS or SMB directly in S3.', 'sgw-file-s3',
        ['With a S3 File Gateway, you can do the following: You can store and retrieve files directly using the NFS version 3 or 4.1 protocol.',
         'You can store and retrieve files directly using the SMB file system version, 2 and 3 protocol.'])),
    cue('on-premises servers need iSCSI block volumes backed by the cloud', 'Volume Gateway',
      b('Volume Gateway provides cloud-backed storage volumes mounted as iSCSI devices.', 'sgw-volume',
        ['Volume Gateway provides cloud-backed storage volumes that you can mount as Internet Small Computer System Interface (iSCSI) devices from your on-premises application servers.'])),
    cue('replace a physical tape library for backups', 'Tape Gateway',
      b('Tape Gateway provides cloud-backed virtual tape storage for archiving backup data.', 'sgw-tape',
        ['Tape Gateway provides cloud-backed virtual tape storage.'])),
    cue('I/O-intensive database on EC2 needs sustained IOPS and low latency', 'EBS Provisioned IOPS SSD (io2)',
      b('Provisioned IOPS SSD is for workloads that need consistent sub-millisecond latency and sustained IOPS.', 'ebs-volume-types',
        ['I/O-intensive database workloads'])),
    cue('big-data scans, data warehouse or log processing, throughput-oriented', 'EBS Throughput Optimized HDD (st1)',
      b('HDD volumes are optimised for large streaming workloads where throughput is dominant; st1 use cases are big data, data warehouses and log processing.', 'ebs-volume-types',
        ['HDD-backed volumes are optimized for large streaming workloads where the dominant performance attribute is throughput.',
         'Use cases Big data Data warehouses Log processing'])),
    cue('infrequently accessed data on EBS, lowest storage cost is important', 'EBS Cold HDD (sc1)',
      b('Cold HDD suits throughput-oriented storage for infrequently accessed data and scenarios where the lowest storage cost is important.', 'ebs-volume-types',
        ['Throughput-oriented storage for data that is infrequently accessed Scenarios where the lowest storage cost is important'])),
    cue('very high S3 request rate', 'Spread requests across multiple prefixes',
      b('S3 performance scales per prefix and a bucket can have any number of prefixes.', 's3-performance',
        ['There are no limits to the number of prefixes in a bucket.'])),
    cue('shared storage that grows automatically without provisioning', 'Amazon EFS',
      b('EFS grows and shrinks automatically as you add and remove files.', 'efs-what-is',
        ['Amazon EFS is built to scale on demand to petabytes without disrupting applications, growing and shrinking automatically as you add and remove files.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Blob storage',
      aws: 'Amazon S3',
      mapping: b('Learn compares Azure Blob storage (any type of text or binary data) with S3 and lists S3 uses such as cloud applications, content distribution, backup, archive, immutable storage, disaster recovery and big data analytics.',
        ['learn-storage', 's3-what-is'],
        ['learn-storage|Storage comparison Object storage AWS service Azure service Description Simple Storage Services (S3) Blob storage Object storage service for use cases that include cloud applications, content distribution, backup, archive, immutable storage, disaster recovery, and big data analytics.',
         's3-what-is|Amazon S3 is an object storage service that stores data as objects, hierarchical data, or tabular data within buckets.']),
      breaks: b('Learn says Blob storage serves the same purpose as both AWS S3 and EBS, so one Azure service is compared with both S3 and EBS. On the AWS side, S3 object performance is described per prefix (at least 3,500 write or 5,500 read requests per second per partitioned prefix); the Learn comparison page does not discuss request-rate guidance.',
        ['s3-performance', 'learn-storage'],
        ['s3-performance|For example, your application can achieve at least 3,500 PUT/COPY/POST/DELETE or 5,500 GET/HEAD requests per second per partitioned Amazon S3 prefix.',
         'learn-storage|Blob storage serves the same purpose as both AWS S3 and EBS.']),
    },
    {
      concept: 'Azure Files',
      aws: 'Amazon EFS',
      mapping: b('Learn lists Azure Files with the shared storage on Azure (and AWS EFS and FSx as the shared storage services on AWS). Azure Files can be deployed by directly mounting serverless Azure file shares or by caching Azure file shares on-premises with Azure File Sync.',
        ['learn-storage', 'efs-what-is'],
        ['learn-storage|Azure Files can be deployed in two main ways: by directly mounting the serverless Azure file shares or by caching Azure file shares on-premises using Azure File Sync.',
         'learn-storage|Various shared storage services that AWS provides, like Elastic File System (EFS) and the FSx family of managed file systems.',
         'efs-what-is|Amazon EFS is built to scale on demand to petabytes without disrupting applications, growing and shrinking automatically as you add and remove files.'],
        { allow: ['two'] }),
      breaks: b('Learn lists Azure File Sync against S3 File Gateway (locally cached NFS and SMB file shares that are cloud-backed), not against EFS. Its table has no row for FSx File Gateway, which AWS no longer offers to new customers, so do not read Azure File Sync as a mapping to that gateway.',
        ['learn-storage', 'sgw-file-s3', 'sgw-fsx-file'],
        ['learn-storage|Hybrid storage AWS service Azure service Description AWS Storage Gateway: S3 File Gateway Azure Data Box Gateway, Azure File Sync Provides on-premises, locally cached NFS and SMB file shares that are cloud-backed.',
         'sgw-file-s3|You can think of a S3 File Gateway as a file system mount on Amazon S3.',
         'sgw-fsx-file|Amazon FSx File Gateway is no longer available to new customers.']),
    },
    {
      concept: 'Azure managed disks',
      aws: 'Amazon EBS',
      mapping: b('Learn pairs EBS volume types with Azure managed disk types by use: gp2/gp3 with Standard SSD for web servers and dev/test, gp2 with Premium SSD, gp3 with Premium SSD v2, and io2 with Ultra Disk for IO-intensive workloads.',
        ['learn-storage', 'ebs-volume-types'],
        ['learn-storage|AWS EBS volume type Azure managed disk Use Can this managed disk be used as an OS Disk gp2/gp3 Standard SSD Web servers and lightly used application servers or dev/test environments Yes gp2 Premium SSD Production and performance-sensitive workloads Yes gp3 Premium SSD v2 Performance-sensitive workloads or workloads that require high IOPS and low latency No io2 Ultra Disk Storage IO-intensive workloads, performance-demanding databases, and high-transaction workloads that require high throughput and IOPS No',
         'ebs-volume-types|I/O-intensive database workloads']),
      breaks: b('EBS also has HDD-backed types (st1, sc1) for throughput-oriented and cold data, which the Learn disk table does not map.',
        ['ebs-volume-types', 'learn-storage'],
        ['ebs-volume-types|HDD-backed volumes are optimized for large streaming workloads where the dominant performance attribute is throughput.',
         'learn-storage|Comparing block storage choices Both platforms provide different types of disks to meet particular performance needs.']),
    },
  ],
};

export default notes;
