import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'grid-planning-office',
  overview: [
    b('Network design is decided mostly before anything is deployed: how the address space is carved up, which subnets are public or private, how traffic is routed, and how separate networks connect. Address ranges matter early: you cannot create a VPC peering connection between VPCs that have matching or overlapping CIDR blocks. This building covers the design questions; Surveyor\'s Grid explains CIDR notation, and Gatehouse covers the route tables, security groups and network ACLs that control traffic inside a VPC.',
      ['vpc-cidr-blocks', 'peering-basics'],
      ['vpc-cidr-blocks|The allowed block size is between a /16 netmask (65,536 IP addresses) and /28 netmask (16 IP addresses).',
       'peering-basics|You cannot create a VPC peering connection between VPCs that have matching or overlapping IPv4 or IPv6 CIDR blocks.']),
  ],
  bullets: [
    {
      id: '3.4-K2',
      concepts: [
        b('IP addressing: a VPC must have an IPv4 CIDR block, between /16 (65,536 addresses) and /28 (16 addresses), and AWS recommends choosing from the private IPv4 ranges in RFC 1918. After creation you can associate additional IPv4 CIDR blocks and one or more IPv6 CIDR blocks, which is how a VPC gets room to grow.',
          'vpc-cidr-blocks',
          ['When you create a VPC, you must specify an IPv4 CIDR block for the VPC.',
           'The allowed block size is between a /16 netmask (65,536 IP addresses) and /28 netmask (16 IP addresses).',
           'After you\'ve created your VPC, you can associate additional IPv4 CIDR blocks with the VPC.',
           'When you create a VPC, we recommend that you specify a CIDR block from the private IPv4 address ranges as specified in RFC 1918.']),
        b('Subnet tiers: a public subnet has a direct route to an internet gateway and its resources can reach the public internet; a private subnet does not. The common layout puts a public subnet and a private subnet in each Availability Zone.',
          'vpc-subnets',
          ['Public subnet – The subnet has a direct route to an internet gateway.',
           'Resources in a public subnet can access the public internet.',
           'Each Availability Zone has a public subnet and a private subnet.']),
        b('Routing: each route table contains routes that direct subnet or gateway traffic, each route has a destination and a target (internet gateway, NAT gateway, VPC peering connection, VPN connection and so on), and AWS uses the most specific matching route.',
          ['vpc-route-tables', 'vpc-route-priority'],
          ['vpc-route-tables|Each route specifies a destination (CIDR block or prefix list) and a target (such as an internet gateway, NAT gateway, VPC peering connection, or VPN connection).',
           'vpc-route-priority|In general, we direct traffic using the most specific route that matches the traffic.']),
      ],
      services: ['Amazon VPC'],
      design: [
        b('Plan the address space with every network you will ever connect in mind: VPCs that will be peered need non-overlapping CIDR blocks. If the VPCs already have overlapping ranges, AWS notes that PrivateLink is a good solution.',
          ['peering-basics', 'connectivity-privatelink'],
          ['peering-basics|You cannot create a VPC peering connection between VPCs that have matching or overlapping IPv4 or IPv6 CIDR blocks.',
           'connectivity-privatelink|Alternatively, AWS PrivateLink is a good solution when the VPCs have overlapped IP addresses.']),
      ],
    },
    {
      id: '3.4-S1',
      concepts: [
        b('Multi-tier topology: web tier in public subnets, application and data tiers in private subnets, one set per Availability Zone, with a load balancer in front. (Blueprint Hall covers the tiers; Gatehouse covers the controls between them.)',
          'vpc-subnets',
          ['Public subnet – The subnet has a direct route to an internet gateway.',
           'Each Availability Zone has a public subnet and a private subnet.']),
        b('Connecting two VPCs: a VPC peering connection routes traffic between them using private addresses, across accounts and Regions, but it is not transitive and needs non-overlapping CIDR blocks.',
          ['peering-what-is', 'peering-basics'],
          ['peering-what-is|The VPCs can be in different Regions (also known as an inter-Region VPC peering connection).',
           'peering-basics|VPC peering does not support transitive peering relationships.'],
          { allow: ['two'] }),
        b('Connecting many VPCs and on-premises networks (hybrid or global): AWS Transit Gateway is a network transit hub that interconnects VPCs and on-premises networks, scales elastically based on the volume of network traffic, can be peered intra-Region and inter-Region by creating a peering attachment, and can use several transit gateway route tables, associations and propagations to segment traffic.',
          ['tgw-what-is', 'tgw-how', 'tgw-peering', 'connectivity-tgw'],
          ['tgw-what-is|AWS Transit Gateway is a network transit hub used to interconnect virtual private clouds (VPCs) and on-premises networks.',
           'tgw-how|A transit gateway scales elastically based on the volume of network traffic.',
           'tgw-peering|You can peer both intra-Region and inter-Region transit gateways, and route traffic between them, which includes IPv4 and IPv6 traffic.',
           'connectivity-tgw|You can take advantage of several Transit Gateway route tables, associations, and propagations to segment your traffic within the same Transit Gateway.']),
        b('Reaching a specific service privately: AWS PrivateLink connects a VPC to services and resources as if they were in the VPC, across VPC and account boundaries, without an internet gateway, NAT device or public IP address.',
          'privatelink-what-is',
          ['AWS PrivateLink is a highly available, scalable technology that you can use to privately connect your VPC to services and resources as if they were in your VPC.',
           'You can create AWS PrivateLink-based VPC endpoints to access services, resources, and network segments across VPC and account boundaries.']),
      ],
      services: ['Amazon VPC', 'AWS Transit Gateway'],
      design: [
        b('Cue to design: hub-and-spoke across many VPCs and on-premises → Transit Gateway; two VPCs only → peering; single shared service → PrivateLink; hybrid links are covered in Edge & Link Terminal.',
          ['tgw-what-is', 'peering-what-is', 'privatelink-what-is'],
          ['tgw-what-is|AWS Transit Gateway is a network transit hub used to interconnect virtual private clouds (VPCs) and on-premises networks.',
           'peering-what-is|VPC peering connection is a networking connection between two VPCs that enables you to route traffic between them using private IPv4 addresses or IPv6 addresses.',
           'privatelink-what-is|Therefore, you control the specific API endpoints, sites, services, and resources that are reachable from your VPC.']),
      ],
    },
    {
      id: '3.4-S2',
      concepts: [
        b('Room to scale: start from a block large enough for growth (up to /16), use additional IPv4 CIDR blocks if needed later, and choose a topology that does not need re-wiring as networks are added. A transit gateway scales elastically based on traffic, while peering needs one connection per pair of VPCs because it is not transitive.',
          ['vpc-cidr-blocks', 'tgw-how', 'peering-basics'],
          ['vpc-cidr-blocks|After you\'ve created your VPC, you can associate additional IPv4 CIDR blocks with the VPC.',
           'tgw-how|A transit gateway scales elastically based on the volume of network traffic.',
           'peering-basics|If you want to enable routing of traffic between VPC B and VPC C, you must create a unique VPC peering connection between them.',
           'vpc-cidr-blocks|The allowed block size is between a /16 netmask (65,536 IP addresses) and /28 netmask (16 IP addresses).']),
        b('The common layout gives each Availability Zone its own public subnet and private subnet, and a VPC can also have one or more IPv6 CIDR blocks associated with it.',
          ['vpc-subnets', 'vpc-cidr-blocks'],
          ['vpc-subnets|Each Availability Zone has a public subnet and a private subnet.',
           'vpc-cidr-blocks|You can optionally associate additional IPv4 CIDR blocks and one or more IPv6 CIDR blocks.']),
      ],
      services: ['Amazon VPC', 'AWS Transit Gateway'],
      design: [
        b('Cue: "dozens of VPCs will be added" → Transit Gateway rather than a mesh of peering connections; "the VPC is running out of addresses" → add a CIDR block.',
          ['tgw-how', 'vpc-cidr-blocks'],
          ['tgw-how|A transit gateway scales elastically based on the volume of network traffic.',
           'vpc-cidr-blocks|After you\'ve created your VPC, you can associate additional IPv4 CIDR blocks with the VPC.']),
      ],
    },
  ],
  cues: [
    cue('connect two VPCs privately, no overlapping CIDR blocks', 'VPC peering',
      b('Peering routes traffic between two VPCs using private addresses.', 'peering-what-is',
        ['VPC peering connection is a networking connection between two VPCs that enables you to route traffic between them using private IPv4 addresses or IPv6 addresses.'])),
    cue('VPC A is peered with B and C and B must talk to C', 'Peering is not transitive: create B–C peering or use a transit gateway',
      b('VPC peering does not support transitive peering relationships.', 'peering-basics',
        ['VPC peering does not support transitive peering relationships.'])),
    cue('hub for many VPCs and on-premises networks', 'AWS Transit Gateway',
      b('Transit Gateway is a hub that interconnects VPCs and on-premises networks.', 'tgw-what-is',
        ['AWS Transit Gateway is a network transit hub used to interconnect virtual private clouds (VPCs) and on-premises networks.'])),
    cue('private access to one service across accounts without exposing the network', 'AWS PrivateLink',
      b('PrivateLink gives access to specific services across VPC and account boundaries.', 'privatelink-what-is',
        ['You can create AWS PrivateLink-based VPC endpoints to access services, resources, and network segments across VPC and account boundaries.'])),
    cue('overlapping CIDR blocks prevent a connection', 'Peering is impossible; PrivateLink works when the VPCs have overlapping IP addresses',
      b('Peering requires non-overlapping CIDR blocks, while AWS describes PrivateLink as a good solution when the VPCs have overlapped IP addresses.', ['peering-basics', 'connectivity-privatelink'],
        ['peering-basics|You cannot create a VPC peering connection between VPCs that have matching or overlapping IPv4 or IPv6 CIDR blocks.',
         'connectivity-privatelink|Alternatively, AWS PrivateLink is a good solution when the VPCs have overlapped IP addresses.'])),
    cue('VPC is running out of IP addresses', 'Associate an additional CIDR block',
      b('You can associate additional IPv4 CIDR blocks with an existing VPC.', 'vpc-cidr-blocks',
        ['After you\'ve created your VPC, you can associate additional IPv4 CIDR blocks with the VPC.'])),
  ],
  examples: [],
  confuse: ['peering-tgw-privatelink'],
  azure: [
    {
      concept: 'Virtual Network',
      aws: 'Amazon VPC',
      mapping: b('Learn describes Azure virtual networks and AWS VPCs as similar: both provide isolated, logically defined network spaces within their cloud platforms.',
        ['learn-networking', 'vpc-cidr-blocks'],
        ['learn-networking|Azure virtual networks and AWS virtual private clouds (VPCs) are similar in that they both provide isolated, logically defined network spaces within their respective cloud platforms.',
         'vpc-cidr-blocks|When you create a VPC, you must specify an IPv4 CIDR block for the VPC.']),
      breaks: b('Subnet placement differs, and it shapes the design. In AWS each subnet is bound to a single Availability Zone, so zonal redundancy needs one subnet per zone; in Azure a subnet is a regional construct that spans all availability zones.',
        ['learn-networking', 'vpc-subnets'],
        ['learn-networking|In AWS, each subnet is bound to a single Availability Zone, so achieving zonal redundancy requires creating one subnet per Availability Zone.',
         'learn-networking|In Azure, a subnet is a regional construct that spans all availability zones in the region.',
         'vpc-subnets|Each Availability Zone has a public subnet and a private subnet.']),
    },
    {
      concept: 'Virtual network peering and Azure Virtual WAN',
      aws: 'VPC peering and AWS Transit Gateway',
      mapping: b('Learn says both Azure and AWS support virtual network / VPC peering, and that more complex peering is done via Azure Virtual WAN or AWS Transit Gateway.',
        ['learn-networking', 'tgw-what-is'],
        ['learn-networking|Both Azure and AWS support virtual network / VPC peering.',
         'learn-networking|Both technologies allow more complex peering via Azure Virtual WAN or AWS Transit Gateway.',
         'tgw-what-is|AWS Transit Gateway is a network transit hub used to interconnect virtual private clouds (VPCs) and on-premises networks.']),
      breaks: b('Learn also lists Azure Private Link as similar to AWS PrivateLink, providing private connectivity from a virtual network to an Azure platform service, a customer-owned service or a partner service. On the AWS side, PrivateLink lets you control the specific services and resources reachable from your VPC, whereas VPC peering needs non-overlapping CIDR blocks and is not transitive.',
        ['privatelink-what-is', 'peering-basics', 'learn-networking'],
        ['privatelink-what-is|Therefore, you control the specific API endpoints, sites, services, and resources that are reachable from your VPC.',
         'peering-basics|VPC peering does not support transitive peering relationships.',
         'learn-networking|Private Link is similar to AWS PrivateLink.',
         'learn-networking|Azure Private Link provides private connectivity from a virtual network to an Azure platform as a service (PaaS) solution, a customer-owned service, or a Microsoft partner service.']),
    },
  ],
};

export default notes;
