import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'ingestion-gate',
  overview: [
    b('An ingestion access point is where producers send data into AWS: a Kinesis data stream, a Firehose stream, a Kafka cluster or a file transfer endpoint. Securing it means answering: who may send (IAM or equivalent), over which network path (public internet or private through a VPC endpoint), and how the data is protected (encryption in transit and at rest). Streaming Canal explains the services; this building is about locking the door.',
      ['kinesis-iam', 'kinesis-vpc', 'kinesis-sse'],
      ['kinesis-iam|AWS Identity and Access Management (IAM) enables you to do the following: Create users and groups under your AWS account',
       'kinesis-vpc|You can use an interface VPC endpoint to prevent traffic between your Amazon VPC and Kinesis Data Streams from leaving the Amazon network.',
       'kinesis-sse|Server-side encryption using AWS Key Management Service (AWS KMS) keys makes it easy for you to meet strict data management requirements by encrypting your data at rest within Amazon Kinesis Data Streams.']),
  ],
  bullets: [
    {
      id: '3.5-K5',
      concepts: [
        b('Who may write: access to Kinesis Data Streams is controlled with IAM, so producers and consumers get permissions through users, groups and roles, including roles that other accounts can assume.',
          'kinesis-iam',
          ['Create users and groups under your AWS account Assign unique security credentials to each user under your AWS account Control each user\'s permissions to perform tasks using AWS resources Allow the users in another AWS account to share your AWS resources Create roles for your AWS account and define the users or services that can assume them']),
        b('Which path: an interface VPC endpoint, powered by AWS PrivateLink, keeps traffic between your VPC and Kinesis Data Streams (and likewise Firehose) on the Amazon network, with no internet gateway, NAT device, VPN connection or Direct Connect connection needed.',
          ['kinesis-vpc', 'firehose-vpc'],
          ['kinesis-vpc|Interface VPC endpoints don\'t require an internet gateway, NAT device, VPN connection, or Direct Connect connection.',
           'kinesis-vpc|Interface VPC endpoints are powered by AWS PrivateLink, an AWS technology that enables private communication between AWS services using an elastic network interface with private IPs in your Amazon VPC.',
           'firehose-vpc|You can use an interface VPC endpoint (AWS PrivateLink) to access Amazon Data Firehose from your VPC without requiring an Internet Gateway or NAT Gateway.']),
        b('Data protection at rest: Kinesis Data Streams supports server-side encryption with AWS KMS keys, which encrypts your data at rest within the stream.',
          'kinesis-sse',
          ['Server-side encryption using AWS Key Management Service (AWS KMS) keys makes it easy for you to meet strict data management requirements by encrypting your data at rest within Amazon Kinesis Data Streams.']),
        b('Amazon MSK clients can authenticate with IAM, which also allows or denies Apache Kafka actions, or with mutual TLS or SASL/SCRAM and Apache Kafka ACLs. Mutual TLS client authentication needs an AWS Private CA, and MSK provides encryption options that it renews certificates for automatically.',
          ['msk-clientauth', 'msk-mtls', 'msk-encryption'],
          ['msk-clientauth|Alternatively, you can use TLS or SASL/SCRAM to authenticate clients, and Apache Kafka ACLs to allow or deny actions.',
           'msk-mtls|To use client authentication, you need an AWS Private CA.',
           'msk-encryption|Amazon MSK provides data encryption options that you can use to meet strict data management requirements.']),
        b('File-based ingestion points can also be private: a Transfer Family server endpoint can be hosted inside a VPC for transferring data to and from an S3 bucket or EFS file system without going over the public internet. For new servers use EndpointType=VPC; AWS states that the older VPC_ENDPOINT type can no longer be created in accounts that had not already used it.',
          'transfer-vpc',
          ['You can host your server\'s endpoint inside a virtual private cloud (VPC) to use for transferring data to and from an Amazon S3 bucket or Amazon EFS file system without going over the public internet.',
           'After this date, use EndpointType=VPC.',
           'Discontinuing the use of VPC_ENDPOINT'],
          { status: 'deprecated' }),
      ],
      services: ['Amazon Kinesis', 'Amazon Data Firehose', 'Amazon MSK', 'AWS PrivateLink', 'AWS Transfer Family'],
      design: [
        b('Cue: producers in a private subnet must send to the stream without internet access → interface VPC endpoint (PrivateLink); "restrict which accounts or roles can put records" → IAM policy or role; "encrypt data in the stream" → KMS server-side encryption.',
          ['kinesis-vpc', 'kinesis-sse'],
          ['kinesis-vpc|You can use an interface VPC endpoint to prevent traffic between your Amazon VPC and Kinesis Data Streams from leaving the Amazon network.',
           'kinesis-sse|Server-side encryption using AWS Key Management Service (AWS KMS) keys makes it easy for you to meet strict data management requirements by encrypting your data at rest within Amazon Kinesis Data Streams.']),
      ],
    },
    {
      id: '3.5-S6',
      concepts: [
        b('Ingestion configuration for streams: Kinesis Data Streams capacity is a function of shards, or you can choose on-demand capacity mode; Firehose lets you set a buffer size and buffer interval, and it can transform data before delivery.',
          ['kinesis-concepts', 'firehose'],
          ['kinesis-concepts|The data capacity of your stream is a function of the number of shards that you specify for the stream.',
           'kinesis-concepts|Currently, in Kinesis Data Streams, you can choose between an on-demand mode and a provisioned mode for your data streams.',
           'firehose|Amazon Data Firehose buffers incoming streaming data to a certain size or for a certain period of time before delivering it to destinations.'],
          { allow: ['two'] }),
        b('Retention is part of the configuration: a Kinesis stream\'s retention period defaults to 24 hours and can be increased up to 8760 hours (365 days), with additional charges for longer retention, so replay needs are sized here.',
          'kinesis-concepts',
          ['A stream’s retention period is set to a default of 24 hours after creation.',
           'You can increase the retention period up to 8760 hours (365 days) using the IncreaseStreamRetentionPeriod operation']),
        b('Choose the Kafka deployment for MSK: MSK Provisioned lets you choose broker instance types, storage and number of brokers, while MSK Serverless runs Kafka without managing cluster capacity.',
          'msk-what-is',
          ['Create an MSK Provisioned cluster by following the Get started using Amazon MSK tutorial.',
           'Run Apache Kafka without having to manage and scale cluster capacity with MSK Serverless.']),
        b('For file ingestion, DataSync agents and Transfer Family servers are the configured access points; secure them with IAM roles and keep the endpoints private where possible (Transfer Dock).',
          ['datasync-how', 'transfer-vpc'],
          ['datasync-how|Data moving into AWS, encrypted using Transport Layer Security (TLS).',
           'transfer-vpc|You can host your server\'s endpoint inside a virtual private cloud (VPC) to use for transferring data to and from an Amazon S3 bucket or Amazon EFS file system without going over the public internet.']),
      ],
      services: ['Amazon Kinesis', 'Amazon Data Firehose', 'Amazon MSK'],
      design: [
        b('Cue: "unpredictable producer volume, no capacity planning" → Kinesis on-demand capacity mode; "deliver in larger, less frequent batches" → raise Firehose buffer size or interval; "keep records longer for reprocessing" → raise Kinesis retention.',
          ['kinesis-concepts', 'firehose'],
          ['kinesis-concepts|A data stream capacity mode determines how capacity is managed and how you are charged for the usage of your data stream.',
           'firehose|Amazon Data Firehose buffers incoming streaming data to a certain size or for a certain period of time before delivering it to destinations.']),
      ],
    },
  ],
  cues: [
    cue('producers in private subnets must reach Kinesis or Firehose without internet', 'Interface VPC endpoint (AWS PrivateLink)',
      b('An interface VPC endpoint keeps traffic on the Amazon network and needs no internet gateway or NAT device.', 'firehose-vpc',
        ['You can use an interface VPC endpoint (AWS PrivateLink) to access Amazon Data Firehose from your VPC without requiring an Internet Gateway or NAT Gateway.'])),
    cue('encrypt the stream\'s data at rest', 'Kinesis Data Streams server-side encryption with AWS KMS',
      b('Server-side encryption with KMS keys encrypts data at rest within the stream.', 'kinesis-sse',
        ['Server-side encryption using AWS Key Management Service (AWS KMS) keys makes it easy for you to meet strict data management requirements by encrypting your data at rest within Amazon Kinesis Data Streams.'])),
    cue('Kafka clients authenticated with IAM', 'Amazon MSK IAM access control',
      b('MSK can use IAM to authenticate clients and to allow or deny Apache Kafka actions.', 'msk-clientauth',
        ['Alternatively, you can use TLS or SASL/SCRAM to authenticate clients, and Apache Kafka ACLs to allow or deny actions.'])),
    cue('SFTP endpoint reachable only from inside the VPC', 'Transfer Family server with a VPC-hosted endpoint',
      b('A Transfer Family server endpoint can be hosted inside a VPC.', 'transfer-vpc',
        ['You can host your server\'s endpoint inside a virtual private cloud (VPC) to use for transferring data to and from an Amazon S3 bucket or Amazon EFS file system without going over the public internet.'])),
    cue('let a producer in another account write to your stream', 'Cross-account IAM role or resource sharing',
      b('IAM lets users in another AWS account share your resources and lets you create roles others can assume.', 'kinesis-iam',
        ['Create users and groups under your AWS account Assign unique security credentials to each user under your AWS account Control each user\'s permissions to perform tasks using AWS resources Allow the users in another AWS account to share your AWS resources Create roles for your AWS account and define the users or services that can assume them'])),
  ],
  examples: [],
  confuse: [],
};

export default notes;
