import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'read-replica-annex',
  overview: [
    b('Database replication copies changes from one database to another. On AWS it serves different purposes: high availability inside a Region (the Multi-AZ standby) and read scaling or distance (read replicas, which can sit in another Region). Choosing between them is one of the most frequent database questions on the exam.',
      ['rds-multi-az-instance', 'rds-read-replicas'],
      ['rds-multi-az-instance|Amazon RDS provides high availability and failover support for DB instances using Multi-AZ deployments with a single standby DB instance.',
       'rds-read-replicas|A read replica is a read-only copy of a DB instance.']),
  ],
  bullets: [
    {
      id: '3.3-K1',
      concepts: [
        b('Availability Zones and Regions shape database placement. An Aurora cluster volume keeps copies of the data across three Availability Zones in a single Region. RDS Multi-AZ places a synchronous standby in a different Availability Zone from the primary, and RDS read replicas can run in the same Region or a different one.',
          ['aurora-storage', 'rds-multi-az-instance', 'rds-read-replicas'],
          ['aurora-storage|A cluster volume consists of copies of the data across three Availability Zones in a single AWS Region.',
           'rds-multi-az-instance|In a Multi-AZ DB instance deployment, Amazon RDS automatically provisions and maintains a synchronous standby replica in a different Availability Zone.',
           'rds-read-replicas|In some cases, a read replica resides in a different AWS Region from its primary DB instance.']),
        b('An Aurora global database spans multiple Regions: it has a primary DB cluster in one Region and up to 10 secondary clusters in different Regions, and Aurora automatically synchronises changes from the primary to the secondaries. It gives fast recovery from a Region-wide outage.',
          'aurora-global',
          ['With the Amazon Aurora Global Database feature, you set up multiple Aurora DB clusters that span multiple AWS Regions.',
           'Aurora automatically synchronizes all changes made in the primary DB cluster to one or more secondary clusters.',
           'An Aurora global database has a primary DB cluster in one Region, and up to 10 secondary DB clusters in different Regions.']),
      ],
      services: ['Amazon RDS', 'Amazon Aurora'],
      design: [
        b('Region-level resilience for a relational database is a cross-Region read replica (RDS) or an Aurora global database; Availability Zone-level resilience is Multi-AZ (RDS) or Aurora\'s multi-AZ storage with replicas in separate zones.',
          ['rds-read-replicas', 'aurora-global'],
          ['rds-read-replicas|You can promote a read replica to a standalone instance as a disaster recovery solution if the primary DB instance fails.',
           'aurora-global|This multi-Region configuration provides fast recovery from the rare outage that might affect an entire AWS Region.']),
      ],
    },
    {
      id: '3.3-K7',
      concepts: [
        b('RDS Multi-AZ replication is synchronous: the primary is synchronously replicated across Availability Zones to a standby, which provides data redundancy and minimises latency spikes during system backups. Read replica replication is asynchronous, using the engine\'s own asynchronous method, so a replica can lag behind its source.',
          ['rds-multi-az-instance', 'rds-read-replicas'],
          ['rds-multi-az-instance|The primary DB instance is synchronously replicated across Availability Zones to a standby replica to provide data redundancy and minimize latency spikes during system backups.',
           'rds-read-replicas|Amazon RDS then uses the asynchronous replication method for the DB engine to update the read replica whenever there is a change to the primary DB instance.']),
        b('Because a read replica serves reads while the source may be unavailable, the data on it might be stale in that case. AWS lists serving read traffic while the source is unavailable, business reporting, scaling read-heavy workloads and disaster recovery as the use cases.',
          'rds-read-replicas',
          ['Serving read traffic while the source DB instance is unavailable.',
           'For this use case, keep in mind that the data on the read replica might be stale because the source DB instance is unavailable.',
           'Business reporting or data warehousing scenarios where you might want business reporting queries to run against a read replica, rather than your production DB instance.']),
        b('Aurora replicates differently: every Aurora cluster has built-in replication between DB instances sharing one cluster volume, and the other instances are read-only Aurora Replicas that scale reads and are promoted automatically if the writer becomes unavailable.',
          'aurora-replication',
          ['Each Aurora DB cluster has built-in replication between multiple DB instances in the same cluster.',
           'Aurora Replicas also help to increase availability.',
           'If the writer instance in a cluster becomes unavailable, Aurora automatically promotes one of the reader instances to take its place as the new writer.']),
        b('Aurora Replicas are reached through the cluster\'s reader endpoint, which spreads read-only connections across the replicas. An Aurora cluster can contain up to 15 Aurora Replicas (a documented limit that can change).',
          'aurora-replication',
          ['You typically do so by connecting to the reader endpoint of the cluster.',
           'An Aurora DB cluster can contain up to 15 Aurora Replicas.']),
      ],
      services: ['Amazon RDS', 'Amazon Aurora'],
      design: [
        b('Read the replication word: synchronous standby for availability (Multi-AZ); asynchronous copy for read scaling or another Region (read replica); built-in Aurora Replicas for both reads and failover within a cluster.',
          ['rds-multi-az-instance', 'rds-read-replicas'],
          ['rds-multi-az-instance|The primary DB instance is synchronously replicated across Availability Zones to a standby replica to provide data redundancy and minimize latency spikes during system backups.',
           'rds-read-replicas|When you make updates to the primary DB instance, Amazon RDS copies them asynchronously to the read replica.']),
      ],
    },
    {
      id: '3.3-S1',
      concepts: [
        b('To configure read replicas: create one from an existing source DB instance (RDS takes a snapshot of the source and creates a read-only instance from it), then direct read-only queries from your applications to the replica endpoint while writes continue to go to the primary.',
          'rds-read-replicas',
          ['When you create a read replica, you specify an existing DB instance as the source.',
           'Then Amazon RDS takes a snapshot of the source instance and creates a read-only instance from the snapshot.',
           'The read replica operates as a DB instance that allows only read-only connections.']),
        b('Match the configuration to the requirement: reporting or analytics queries → a read replica so they stop slowing production; users in another geography or Region-level DR → a cross-Region read replica; high availability → Multi-AZ, and a read replica can be added to a Multi-AZ instance when you need both.',
          'rds-read-replicas',
          ['You can configure a read replica for a DB instance that also has a standby replica configured for high availability in a Multi-AZ deployment.',
           'In some cases, a read replica resides in a different AWS Region from its primary DB instance.']),
        b('Remember limits: RDS does not autoscale read replicas, and writes always go to the primary, so read replicas do not help a write-bound workload. For Aurora, add Aurora Replicas and use the reader endpoint.',
          ['rds-read-replicas', 'aurora-replication'],
          ['rds-read-replicas|RDS doesn\'t support autoscaling of read replicas, which is the automatic add or removing of read replicas as read demand changes.',
           'aurora-replication|You typically do so by connecting to the reader endpoint of the cluster.']),
      ],
      services: ['Amazon RDS', 'Amazon Aurora'],
      design: [
        b('Scenario cue: "the database is slow only for reporting" → read replica; "needs automatic failover" → Multi-AZ; "needs a copy in another Region for DR or local reads" → cross-Region read replica or Aurora global database.',
          ['rds-read-replicas', 'rds-multi-az'],
          ['rds-read-replicas|You can reduce the load on your primary DB instance by routing queries from your applications to the read replica.',
           'rds-multi-az|A Multi-AZ DB instance deployment has one standby DB instance that provides failover support, but doesn\'t serve read traffic.']),
      ],
    },
  ],
  cues: [
    cue('automatic failover to another Availability Zone, no application change', 'RDS Multi-AZ deployment',
      b('Multi-AZ provides high availability and failover support through a standby in another Availability Zone.', 'rds-multi-az-instance',
        ['Amazon RDS provides high availability and failover support for DB instances using Multi-AZ deployments with a single standby DB instance.'])),
    cue('offload read-heavy or reporting queries from the primary', 'RDS read replica',
      b('Routing queries to a read replica reduces load on the primary.', 'rds-read-replicas',
        ['You can reduce the load on your primary DB instance by routing queries from your applications to the read replica.'])),
    cue('copy of the database in another Region for DR or local reads', 'Cross-Region read replica (RDS) or Aurora global database',
      b('A read replica can live in another Region and can be promoted if the primary fails.', 'rds-read-replicas',
        ['You can promote a read replica to a standalone instance as a disaster recovery solution if the primary DB instance fails.'])),
    cue('synchronous replication', 'Multi-AZ standby',
      b('Multi-AZ replicates the primary synchronously to the standby.', 'rds-multi-az-instance',
        ['The primary DB instance is synchronously replicated across Availability Zones to a standby replica to provide data redundancy and minimize latency spikes during system backups.'])),
    cue('asynchronous replication', 'Read replica',
      b('Read replicas are updated asynchronously.', 'rds-read-replicas',
        ['When you make updates to the primary DB instance, Amazon RDS copies them asynchronously to the read replica.'])),
    cue('Aurora readers share storage and one is promoted if the writer fails', 'Aurora Replicas (reader endpoint)',
      b('Aurora automatically promotes a reader if the writer becomes unavailable.', 'aurora-replication',
        ['If the writer instance in a cluster becomes unavailable, Aurora automatically promotes one of the reader instances to take its place as the new writer.'])),
    cue('multi-Region Aurora with fast regional recovery', 'Aurora global database',
      b('An Aurora global database spans Regions and provides fast recovery from a Region-wide outage.', 'aurora-global',
        ['This multi-Region configuration provides fast recovery from the rare outage that might affect an entire AWS Region.'])),
  ],
  examples: [],
  confuse: ['multi-az-vs-read-replicas'],
};

export default notes;
