import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'streaming-canal',
  overview: [
    b('Streaming data is emitted at high volume in a continuous, incremental manner, often requiring low-latency processing. AWS has three streaming ingestion services the exam expects you to separate: Kinesis Data Streams (you build the consumers), {{rename:data-firehose}} (managed delivery to a destination) and Amazon MSK (managed Apache Kafka).',
      ['what-is-streaming-data', 'kinesis-streams', 'firehose', 'msk-what-is'],
      ['what-is-streaming-data|Streaming data is data that is emitted at high volume in a continuous, incremental manner, often requiring low-latency processing.',
       'kinesis-streams|You can use Amazon Kinesis Data Streams to collect and process large streams of data records in real time.',
       'firehose|Amazon Data Firehose is a fully managed service for delivering real-time streaming data to destinations such as Amazon Simple Storage Service (Amazon S3), Amazon Redshift, Amazon OpenSearch Service',
       'msk-what-is|fully managed service that enables you to build and run applications that use Apache Kafka to process streaming data.'],
      { allow: ['three'] }),
  ],
  bullets: [
    {
      id: '3.5-K2',
      concepts: [
        b('Ingestion frequency is a design input: batch data arrives in periodic loads, while streaming data arrives continuously and incrementally and often needs low-latency processing. Choose the ingestion service by how often and how fast data must be processed.',
          'what-is-streaming-data',
          ['Streaming data is data that is emitted at high volume in a continuous, incremental manner, often requiring low-latency processing.',
           'Streaming data can include location, event, and sensor data that companies use for real-time analytics and visibility into many aspects of their business.']),
        b('Amazon Data Firehose buffers incoming streaming data to a certain size or for a certain period of time before delivering it to destinations; buffer size is in MBs and buffer interval is in seconds. AWS describes Firehose as enabling near real-time analytics; because delivery waits for the buffer, think of it as delivery in batches rather than record-by-record processing, and note that for S3 the buffer interval can be set from 0 to 900 seconds.',
          ['firehose', 'firehose-faqs'],
          ['firehose|Amazon Data Firehose buffers incoming streaming data to a certain size or for a certain period of time before delivering it to destinations.',
           'firehose|Buffer Size is in MBs and Buffer Interval is in seconds.',
           'firehose-faqs|It can capture, transform, and load streaming data into Amazon S3, Amazon Redshift, Amazon OpenSearch Service, Snowflake, Apache Iceberg tables and Splunk, enabling near real-time analytics with existing business intelligence tools and dashboards you’re already using today.',
           'firehose-faqs|You can configure the values for S3 buffer size (1 MB to 128 MB) or buffer interval (0 to 900 seconds), and the condition satisfied first triggers data delivery to Amazon S3.']),
        b('Kinesis Data Streams lets consumers process records as they arrive in real time, with the data retained for a retention period that defaults to 24 hours and can be increased up to 8760 hours (365 days), which AWS documents on its terminology page.',
          'kinesis-concepts',
          ['A stream’s retention period is set to a default of 24 hours after creation.',
           'You can increase the retention period up to 8760 hours (365 days) using the IncreaseStreamRetentionPeriod operation']),
      ],
      services: ['Amazon Kinesis', 'Amazon Data Firehose'],
      design: [
        b('Cue: delivering streaming data to S3 or Redshift with no code, where near real-time delivery is enough → Firehose; custom code that processes records as they arrive → Kinesis Data Streams (or MSK for Kafka).',
          ['firehose', 'firehose-faqs', 'kinesis-streams'],
          ['firehose|You configure your data producers to send data to Amazon Data Firehose, and it automatically delivers the data to the destination that you specified.',
           'firehose-faqs|It can capture, transform, and load streaming data into Amazon S3, Amazon Redshift, Amazon OpenSearch Service, Snowflake, Apache Iceberg tables and Splunk, enabling near real-time analytics with existing business intelligence tools and dashboards you’re already using today.',
           'kinesis-streams|You can use Amazon Kinesis Data Streams to collect and process large streams of data records in real time.']),
      ],
    },
    {
      id: '3.5-K7',
      concepts: [
        b('A Kinesis data stream is a set of shards, and a shard is a uniquely identified sequence of data records; each shard provides a fixed unit of capacity, so the capacity of the stream is a function of the number of shards. A stream also has a capacity mode, on-demand or provisioned, that determines how capacity is managed and how you are charged.',
          'kinesis-concepts',
          ['A Kinesis data stream is a set of shards.',
           'A shard is a uniquely identified sequence of data records in a stream.',
           'A stream is composed of one or more shards, each of which provides a fixed unit of capacity.',
           'Currently, in Kinesis Data Streams, you can choose between an on-demand mode and a provisioned mode for your data streams.'],
          { allow: ['two'] }),
        b('Multiple consumers can read the same stream in parallel. With enhanced fan-out, consumers receive records with dedicated throughput of up to 2 MB per second per shard and records are pushed to them, so they do not contend with other consumers or need to poll.',
          ['kinesis-consumers', 'kinesis-efo'],
          ['kinesis-consumers|allowing multiple consumers to read data from the same stream in parallel, without contending for read throughput with other consumers.',
           'kinesis-efo|This feature lets consumers receive records from a stream with throughput of up to 2 MB of data per second per shard.',
           'kinesis-efo|Kinesis Data Streams pushes data records from the stream to consumers that use enhanced fan-out.']),
        b('Amazon Data Firehose is a fully managed service for delivering real-time streaming data to destinations such as S3, Redshift, OpenSearch Service, Splunk, Apache Iceberg tables and HTTP endpoints. You do not write applications or manage resources, and it can capture, transform and load the data; it can also read from an existing Kinesis data stream.',
          ['firehose', 'firehose-faqs'],
          ['Amazon Data Firehose is a fully managed service for delivering real-time streaming data to destinations such as Amazon Simple Storage Service (Amazon S3), Amazon Redshift, Amazon OpenSearch Service, Amazon OpenSearch Serverless, Splunk, Apache Iceberg Tables, and any custom HTTP endpoint',
           'With Amazon Data Firehose, you don\'t need to write applications or manage resources.',
           'You can also configure your Firehose stream to automatically read data from an existing Kinesis data stream, and load it into destinations.',
           'firehose-faqs|It can capture, transform, and load streaming data into Amazon S3, Amazon Redshift, Amazon OpenSearch Service, Snowflake, Apache Iceberg tables and Splunk, enabling near real-time analytics with existing business intelligence tools and dashboards you’re already using today.']),
        b('Amazon MSK is a fully managed service for building and running applications that use Apache Kafka. It provides control-plane operations such as creating, updating and deleting clusters, lets you use Kafka data-plane operations, and runs open-source Kafka so existing applications, tooling and plugins work without code changes. MSK Provisioned lets you choose broker instance types, storage and number of brokers; MSK Serverless runs Kafka without managing cluster capacity.',
          ['msk-what-is', 'msk-provisioned'],
          ['msk-what-is|Amazon MSK provides the control-plane operations, such as those for creating, updating, and deleting clusters.',
           'msk-what-is|It lets you use Apache Kafka data-plane operations, such as those for producing and consuming data.',
           'msk-what-is|It runs open-source versions of Apache Kafka.',
           'msk-what-is|This means existing applications, tooling, and plugins from partners and the Apache Kafka community are supported without requiring changes to application code.',
           'msk-provisioned|MSK Provisioned is an MSK cluster deployment option that allows you to manually configure and scale your Apache Kafka clusters.',
           'msk-what-is|Run Apache Kafka without having to manage and scale cluster capacity with MSK Serverless.']),
      ],
      services: ['Amazon Kinesis', 'Amazon Data Firehose', 'Amazon MSK'],
      design: [
        b('Cue: existing Kafka applications or Kafka tooling must keep working → MSK; AWS-native streaming with custom consumers → Kinesis Data Streams; just deliver to a destination → Firehose.',
          ['msk-what-is', 'kinesis-streams', 'firehose'],
          ['msk-what-is|This means existing applications, tooling, and plugins from partners and the Apache Kafka community are supported without requiring changes to application code.',
           'kinesis-streams|You can use Amazon Kinesis Data Streams to collect and process large streams of data records in real time.',
           'firehose|With Amazon Data Firehose, you don\'t need to write applications or manage resources.']),
      ],
    },
    {
      id: '3.5-S2',
      concepts: [
        b('A typical streaming architecture: producers send to a stream (Kinesis Data Streams or MSK); consumers such as Lambda or Managed Service for Apache Flink process records; Firehose delivers to S3, Redshift or OpenSearch for analysis. A Kinesis data stream can feed Firehose, and Firehose is itself one of the consumer options for Kinesis Data Streams.',
          ['kinesis-consumers', 'firehose'],
          ['kinesis-consumers|You can also develop consumers using other AWS services such as AWS Lambda, Amazon Managed Service for Apache Flink, and Amazon Data Firehose.',
           'firehose|You can also configure your Firehose stream to automatically read data from an existing Kinesis data stream, and load it into destinations.']),
        b('Scale a stream deliberately: capacity is a function of the number of shards, or choose on-demand capacity mode so that capacity is managed for you. Design partition keys so records spread across shards.',
          'kinesis-concepts',
          ['The data capacity of your stream is a function of the number of shards that you specify for the stream.',
           'A data stream capacity mode determines how capacity is managed and how you are charged for the usage of your data stream.']),
        b('Decouple the stream from the processing with a queue or event bus when consumers fail or lag, and keep processing idempotent because records can be delivered more than once in distributed systems.',
          'msa-distributed-data',
          ['Remember, in distributed systems, events might be delivered multiple times due to retries, so it\'s important to design your applications to handle this.']),
      ],
      services: ['Amazon Kinesis', 'Amazon Data Firehose', 'Amazon MSK'],
      design: [
        b('Pattern for clickstream or IoT telemetry: producers → Kinesis Data Streams → (Lambda or Flink for real-time processing) and Firehose → S3 data lake → Athena. Choose MSK instead of Kinesis if Kafka compatibility is a stated requirement.',
          ['kinesis-streams', 'firehose'],
          ['kinesis-streams|You can use Amazon Kinesis Data Streams to collect and process large streams of data records in real time.',
           'firehose|Amazon Data Firehose is a fully managed service for delivering real-time streaming data to destinations such as Amazon Simple Storage Service (Amazon S3), Amazon Redshift, Amazon OpenSearch Service']),
      ],
    },
  ],
  cues: [
    cue('custom real-time processing, several independent consumers of the same stream', 'Kinesis Data Streams (enhanced fan-out for dedicated throughput)',
      b('Multiple consumers can read the same stream in parallel without contending for throughput.', 'kinesis-consumers',
        ['allowing multiple consumers to read data from the same stream in parallel, without contending for read throughput with other consumers.'])),
    cue('load streaming data into S3, Redshift or OpenSearch with no code to manage', 'Amazon Data Firehose',
      b('Firehose delivers automatically to the configured destination without applications to write.', 'firehose',
        ['With Amazon Data Firehose, you don\'t need to write applications or manage resources.'])),
    cue('Apache Kafka compatible, existing Kafka clients', 'Amazon MSK',
      b('MSK runs open-source Apache Kafka so existing applications and tooling work without code changes.', 'msk-what-is',
        ['This means existing applications, tooling, and plugins from partners and the Apache Kafka community are supported without requiring changes to application code.'])),
    cue('Kafka without managing cluster capacity', 'MSK Serverless',
      b('MSK Serverless runs Apache Kafka without managing and scaling cluster capacity.', 'msk-what-is',
        ['Run Apache Kafka without having to manage and scale cluster capacity with MSK Serverless.'])),
    cue('stream capacity should be managed automatically', 'Kinesis Data Streams on-demand capacity mode',
      b('A stream capacity mode determines how capacity is managed; on-demand is one of two modes.', 'kinesis-concepts',
        ['A data stream capacity mode determines how capacity is managed and how you are charged for the usage of your data stream.'],
        { allow: ['two'] })),
    cue('buffer streaming data by size or time before delivery', 'Amazon Data Firehose (buffer size and interval)',
      b('Firehose buffers by size and interval before delivering.', 'firehose',
        ['Amazon Data Firehose buffers incoming streaming data to a certain size or for a certain period of time before delivering it to destinations.'])),
  ],
  examples: [],
  confuse: ['kds-vs-firehose'],
  azure: [
    {
      concept: 'Azure Event Hubs',
      aws: 'Amazon Kinesis Data Streams',
      mapping: b('Learn pairs Kinesis Data Streams with Azure Event Hubs: both ingest and retain high-throughput event streams for independent consumers.',
        ['learn-analytics', 'kinesis-streams'],
        ['learn-analytics|Amazon Kinesis Data Streams Azure Event Hubs Both ingest and retain high-throughput event streams for independent consumers.',
         'kinesis-streams|You can use Amazon Kinesis Data Streams to collect and process large streams of data records in real time.']),
      breaks: b('Learn tells you to compare partitioning, retention, replay, throughput, protocols and scaling rather than treating them as identical. On the AWS side a stream is made of shards, each a fixed unit of capacity. The Learn analytics comparison has no row for Amazon Data Firehose, so it does not tell you what Azure service matches Firehose delivery.',
        ['learn-analytics', 'kinesis-concepts'],
        ['learn-analytics|Compare partitioning, retention, replay, throughput, protocols, and scaling.',
         'kinesis-concepts|A stream is composed of one or more shards, each of which provides a fixed unit of capacity.']),
    },
    {
      concept: 'Event Hubs for Apache Kafka',
      aws: 'Amazon MSK',
      mapping: b('Learn pairs Amazon MSK with Event Hubs for Apache Kafka.',
        ['learn-analytics', 'msk-what-is'],
        ['learn-analytics|Amazon Managed Streaming for Apache Kafka Event Hubs for Apache Kafka',
         'msk-what-is|It runs open-source versions of Apache Kafka.']),
      breaks: b('Learn states that Amazon MSK runs open-source Apache Kafka whereas Event Hubs provides a Kafka-compatible endpoint and is not an Apache Kafka cluster; a Kafka-compatible endpoint does not provide every Apache Kafka broker feature, so validate protocol features before treating them as equal.',
        ['learn-analytics', 'msk-what-is'],
        ['learn-analytics|Amazon MSK runs open-source Apache Kafka. Event Hubs provides a Kafka-compatible endpoint and isn\'t an Apache Kafka cluster.',
         'learn-analytics|A Kafka-compatible endpoint doesn\'t provide every Apache Kafka broker feature.',
         'msk-what-is|It runs open-source versions of Apache Kafka.']),
    },
  ],
};

export default notes;
