import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'transfer-dock',
  overview: [
    b('Moving data into AWS is a choice between online and offline paths, and the deciding inputs are how much data there is, how fast the network really is, and whether the transfer is a one-time move or an ongoing sync. Storage Gateway (Freight Depot) is for continuing hybrid access; this building covers moving the data itself.',
      ['datasync-what-is', 'snowball-edge', 'transfer-what-is'],
      ['datasync-what-is|AWS DataSync is a secure, reliable, high‐speed file transfer service that helps you quickly and easily transfer your file or object data to, from, and between AWS storage services.',
       'snowball-edge|Each Snowball Edge device can transport data at speeds faster than the internet.',
       'transfer-what-is|AWS Transfer Family is a secure transfer service that enables you to transfer files into and out of AWS storage services.']),
  ],
  bullets: [
    {
      id: '3.5-K3',
      concepts: [
        b('AWS DataSync is a high-speed file transfer service for file or object data to, from and between AWS storage services. It works with on-premises NFS, SMB, HDFS and object storage, with AWS storage services (S3, EFS and the FSx file systems), and with storage in other clouds. A DataSync agent copies data from an on-premises storage system, and data moving into AWS is encrypted with TLS.',
          ['datasync-what-is', 'datasync-how'],
          ['datasync-what-is|DataSync works with the following on-premises storage systems: Network File System (NFS) Server Message Block (SMB) Hadoop Distributed File Systems (HDFS) Object storage',
           'datasync-what-is|DataSync works with the following AWS storage services: Amazon S3 Amazon EFS Amazon FSx for Windows File Server Amazon FSx for Lustre Amazon FSx for OpenZFS Amazon FSx for NetApp ONTAP',
           'datasync-how|Data moving into AWS, encrypted using Transport Layer Security (TLS).']),
        b('AWS Transfer Family offers fully managed support for transferring files over SFTP, AS2, FTPS and FTP, and browser-based transfers, directly into and out of AWS storage. Use it when partners or applications must keep using those protocols.',
          'transfer-what-is',
          ['AWS Transfer Family offers fully managed support for the transfer of files over SFTP, AS2, FTPS, FTP, and web browser-based transfers directly into and out of AWS storage services.']),
        b('AWS Storage Gateway connects an on-premises appliance to cloud storage for ongoing hybrid access, with S3 File Gateway, Volume Gateway and Tape Gateway options (Freight Depot).',
          'sgw-volume',
          ['AWS Storage Gateway offers file-based (S3 File Gateway and FSx File Gateway), volume-based (Volume Gateway), and tape-based (Tape Gateway) storage solutions.']),
        b('The offline-transfer pattern ships storage devices instead of sending the data over the network. Snowball Edge is a device with on-board storage and compute that can transfer data to or from the AWS Cloud; the data is moved by shipping the devices through a regional carrier, which AWS says can be faster than the internet.',
          'snowball-edge',
          ['Snowball Edge is a device with on-board storage and compute power for select AWS capabilities.',
           'Each Snowball Edge device can transport data at speeds faster than the internet.',
           'This transport is done by shipping the data in the devices through a regional carrier.']),
        b('AWS now states that Snowball Edge is no longer available to new customers and points new customers to AWS DataSync for online transfers, AWS Data Transfer Terminal for secure physical transfers, or AWS Partner solutions.',
          'snowball-edge',
          ['AWS Snowball Edge is no longer available to new customers.',
           'New customers should explore AWS DataSync for online transfers, AWS Data Transfer Terminal for secure physical transfers, or AWS Partner solutions.'],
          { status: 'closed' }),
        b('AWS Data Transfer Terminal is a network-ready physical location where you bring your own storage devices for fast data transfer to and from your AWS Cloud services; you schedule a reservation from the console.',
          'dtt',
          ['AWS Data Transfer Terminal is a network-ready, physical location you can bring your data storage devices for fast data transfer to and from your AWS Cloud service.',
           'Schedule a reservation at one of our physical Data Transfer Terminal facilities from the AWS Management Console']),
      ],
      services: ['AWS DataSync', 'AWS Storage Gateway', 'AWS Transfer Family', 'AWS Snow Family'],
      design: [
        b('Cue: online migration of file or object data on a schedule or one-time → DataSync; partners using SFTP → Transfer Family; ongoing on-premises access to cloud storage → Storage Gateway; huge data on a slow link → an offline physical option.',
          ['datasync-what-is', 'transfer-what-is', 'snowball-edge'],
          ['datasync-what-is|AWS DataSync is a secure, reliable, high‐speed file transfer service that helps you quickly and easily transfer your file or object data to, from, and between AWS storage services.',
           'transfer-what-is|AWS Transfer Family is a secure transfer service that enables you to transfer files into and out of AWS storage services.',
           'snowball-edge|Each Snowball Edge device can transport data at speeds faster than the internet.']),
      ],
    },
    {
      id: '3.5-K6',
      concepts: [
        b('Sizes and speeds decide online versus offline. When moving the data over the network would take too long, the offline options apply: a Snowball Edge device (shipped, and no longer offered to new customers) or a Data Transfer Terminal location where you bring your own storage devices.',
          ['snowball-edge', 'dtt'],
          ['snowball-edge|Each Snowball Edge device can transport data at speeds faster than the internet.',
           'dtt|AWS Data Transfer Terminal is a network-ready, physical location you can bring your data storage devices for fast data transfer to and from your AWS Cloud service.']),
        b('DataSync is described as a high-speed transfer service that handles the movement for you; use it when the network is fast enough to finish within the required window, and add Transfer Family or Storage Gateway when the protocol or continuing access dictates.',
          'datasync-what-is',
          ['AWS DataSync is a secure, reliable, high‐speed file transfer service that helps you quickly and easily transfer your file or object data to, from, and between AWS storage services.']),
        b('Direct Connect is a network option rather than a shipped device: it links your internal network to a Direct Connect location over a standard Ethernet fiber-optic cable, and its virtual interfaces bypass internet service providers in your network path (see Edge & Link Terminal and Transit Tariff).',
          'dx-what-is',
          ['Direct Connect links your internal network to a Direct Connect location over a standard Ethernet fiber-optic cable.',
           'With this connection, you can create virtual interfaces directly to public AWS services (for example, to Amazon S3) or to Amazon VPC, bypassing internet service providers in your network path.']),
      ],
      services: ['AWS DataSync', 'AWS Snow Family', 'AWS Direct Connect'],
      design: [
        b('Estimate the network transfer time as the amount of data divided by the bandwidth you can really sustain. Cue: "deadline is shorter than the network can manage" or "link is slow and the data set is very large" → an offline device; "ongoing small changes" → an online service such as DataSync.',
          ['snowball-edge', 'datasync-what-is'],
          ['snowball-edge|Each Snowball Edge device can transport data at speeds faster than the internet.',
           'datasync-what-is|Migrate data – Transfer active datasets rapidly over the network into AWS storage services.']),
      ],
    },
    {
      id: '3.5-S3',
      concepts: [
        b('A transfer design names the source, the protocol, the destination and the path: NFS, SMB, HDFS or object storage source → DataSync (agent on premises) → S3, EFS or FSx; SFTP or FTPS partners → Transfer Family → S3 or EFS; physical media for huge or slow-link data → offline option.',
          ['datasync-what-is', 'transfer-what-is'],
          ['datasync-what-is|DataSync works with the following on-premises storage systems: Network File System (NFS) Server Message Block (SMB) Hadoop Distributed File Systems (HDFS) Object storage',
           'transfer-what-is|AWS Transfer Family offers fully managed support for the transfer of files over SFTP, AS2, FTPS, FTP, and web browser-based transfers directly into and out of AWS storage services.']),
        b('Secure the transfer: DataSync data moving into AWS is encrypted with Transport Layer Security (TLS). With Transfer Family, FTP is the exception among its protocols: it sends clear text and does not encrypt traffic, so data that crosses the public network must use SFTP or FTPS. Choose the destination storage type to match later use (object for a data lake, file for shared access).',
          ['datasync-how', 'transfer-ftp'],
          ['datasync-how|Data moving into AWS, encrypted using Transport Layer Security (TLS).',
           'transfer-ftp|FTP uses clear text and does not support encryption of traffic.',
           'transfer-ftp|If you need your server to have data traverse the public network, you must use secure protocols, such as SFTP or FTPS.']),
      ],
      services: ['AWS DataSync', 'AWS Transfer Family', 'AWS Storage Gateway'],
      design: [
        b('Pattern: a very large one-time data set on a slow link → an offline path first, then DataSync for the changes that follow; data that on-premises applications keep using → Storage Gateway.',
          ['sgw-file-s3', 'datasync-what-is'],
          ['sgw-file-s3|You can think of a S3 File Gateway as a file system mount on Amazon S3.',
           'datasync-what-is|Migrate data – Transfer active datasets rapidly over the network into AWS storage services.']),
      ],
    },
  ],
  cues: [
    cue('migrate NFS or SMB file data to S3, EFS or FSx over the network', 'AWS DataSync',
      b('DataSync works with on-premises NFS and SMB and with S3, EFS and FSx.', 'datasync-what-is',
        ['DataSync works with the following on-premises storage systems: Network File System (NFS) Server Message Block (SMB) Hadoop Distributed File Systems (HDFS) Object storage'])),
    cue('trading partners send files by SFTP or FTPS into S3', 'AWS Transfer Family',
      b('Transfer Family supports SFTP, AS2, FTPS and FTP into and out of AWS storage.', 'transfer-what-is',
        ['AWS Transfer Family offers fully managed support for the transfer of files over SFTP, AS2, FTPS, FTP, and web browser-based transfers directly into and out of AWS storage services.'])),
    cue('very large data set and slow or no network, physical shipment', 'Offline transfer (Snowball Edge pattern; no longer available to new customers)',
      b('Snowball Edge devices move data by shipping, which can be faster than the internet.', 'snowball-edge',
        ['Each Snowball Edge device can transport data at speeds faster than the internet.'])),
    cue('on-premises application keeps using cloud storage through a local appliance', 'AWS Storage Gateway',
      b('Storage Gateway connects an on-premises appliance to cloud-based storage.', 'storage-gateway-docs',
        ['AWS Storage Gateway is a service that connects an on-premises software appliance with cloud-based storage to provide seamless and secure integration between your on-premises IT environment and the AWS storage infrastructure in the AWS Cloud.'])),
    cue('bring your own storage devices to an AWS location for fast upload', 'AWS Data Transfer Terminal',
      b('Data Transfer Terminal is a physical location for fast data transfer to and from AWS.', 'dtt',
        ['AWS Data Transfer Terminal is a network-ready, physical location you can bring your data storage devices for fast data transfer to and from your AWS Cloud service.'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Data Box',
      aws: 'AWS Snowball Edge',
      mapping: b('Learn pairs Snowball Edge with Azure Data Box: a petabyte-scale to exabyte-scale data transport solution that uses enhanced-security data storage devices to transfer large amounts of data to and from Azure.',
        ['learn-storage', 'snowball-edge'],
        ['learn-storage|Snowball Edge Data Box Petabyte-scale to exabyte-scale data transport solution that uses enhanced-security data storage devices to transfer large amounts of data to and from Azure.',
         'snowball-edge|Snowball Edge is a device with on-board storage and compute power for select AWS capabilities.']),
      breaks: b('AWS states that Snowball Edge is no longer available to new customers and suggests DataSync, Data Transfer Terminal or partner solutions, while Learn pairs Snowball Edge with Azure Data Box.',
        ['snowball-edge', 'learn-storage'],
        ['snowball-edge|AWS Snowball Edge is no longer available to new customers.',
         'learn-storage|Snowball Edge Data Box Petabyte-scale to exabyte-scale data transport solution that uses enhanced-security data storage devices to transfer large amounts of data to and from Azure.']),
    },
    {
      concept: 'Azure Data Box Gateway / Azure File Sync',
      aws: 'AWS DataSync and AWS Storage Gateway',
      mapping: b('Learn pairs S3 File Gateway with Azure Data Box Gateway and Azure File Sync as on-premises, locally cached NFS and SMB file shares that are cloud-backed.',
        ['learn-storage', 'sgw-file-s3'],
        ['learn-storage|Provides on-premises, locally cached NFS and SMB file shares that are cloud-backed.',
         'sgw-file-s3|You can think of a S3 File Gateway as a file system mount on Amazon S3.']),
      breaks: b('Learn pairs DataSync with Azure File Sync, but they are different tools: Azure File Sync is a cache and sync service for Azure Files, closer to S3 File Gateway, while DataSync is a transfer service that moves file or object data between storage systems.',
        ['learn-storage', 'datasync-what-is'],
        ['learn-storage|DataSync File Sync Azure Files can be deployed in two main ways: by directly mounting the serverless Azure file shares or by caching Azure file shares on-premises using Azure File Sync.',
         'datasync-what-is|AWS DataSync is a secure, reliable, high‐speed file transfer service that helps you quickly and easily transfer your file or object data to, from, and between AWS storage services.']),
    },
  ],
};

export default notes;
