import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'tuning-bay',
  overview: [
    b('Tuning a database starts from how it is used (read-intensive or write-intensive, which keys, how many connections) and ends in a capacity decision: capacity units for DynamoDB, instance class and storage type for RDS. A good design also keeps connection counts under control, which is where RDS Proxy comes in.',
      ['dynamodb-partition-keys', 'rds-instance-class', 'rds-proxy'],
      ['dynamodb-partition-keys|You can determine the access patterns that your application requires, and read and write units that each table and secondary index requires.',
       'rds-instance-class|The DB instance class determines the computation and memory capacity of an Amazon RDS DB instance.',
       'rds-proxy|By using Amazon RDS Proxy, you can allow your applications to pool and share database connections to improve their ability to scale.']),
  ],
  beyondProject: [
    b('You already use DynamoDB. The SAA step is capacity: provisioned mode, where you set read and write capacity units and can use auto scaling, or on-demand mode, which scales automatically without capacity planning. The DynamoDB guidance also asks you to design for uniform activity across partition keys, because a hot key defeats scaling.',
      ['dynamodb-provisioned', 'dynamodb-ondemand', 'dynamodb-partition-keys'],
      ['dynamodb-provisioned|For provisioned mode tables, you specify throughput requirements in terms of capacity units.',
       'dynamodb-ondemand|Amazon DynamoDB on-demand offers a truly serverless database experience that automatically scales to accommodate the most demanding workloads without capacity planning.',
       'dynamodb-partition-keys|You should design your application for uniform activity across all partition keys in the table and its secondary indexes.']),
  ],
  bullets: [
    {
      id: '3.3-K3',
      concepts: [
        b('An access pattern is how the application reads and writes data. For DynamoDB you determine the access patterns your application requires, and the read and write units each table and secondary index needs, then design the key schema: a simple primary key (a partition key only) or a composite key (a partition key and a sort key), with uniform activity across partition keys.',
          'dynamodb-partition-keys',
          ['The primary key that uniquely identifies each item in an Amazon DynamoDB table can be simple (a partition key only) or composite (a partition key combined with a sort key).',
           'You should design your application for uniform activity across all partition keys in the table and its secondary indexes.',
           'You can determine the access patterns that your application requires, and read and write units that each table and secondary index requires.']),
        b('Read-intensive and write-intensive workloads call for different answers: add read replicas or a cache for read-intensive relational workloads (Read-Replica Annex, Cache Pavilion); for write-intensive workloads a replica does not help, because writes go to the primary, so raise instance size, use Provisioned IOPS storage, or choose a database built for write scale.',
          ['rds-read-replicas', 'database-decision'],
          ['rds-read-replicas|The read replica operates as a DB instance that allows only read-only connections.',
           'database-decision|Key-value databases can scale to large amounts of data and extremely high throughput of requests, while servicing millions of simultaneous users through distributed processing and storage.']),
      ],
      services: ['Amazon DynamoDB', 'Amazon RDS'],
      design: [
        b('Cue: "read-intensive" → replicas or cache; "write-intensive" → larger or Provisioned IOPS instance, or DynamoDB with well-distributed keys; "unpredictable" → on-demand or Aurora serverless.',
          'dynamodb-ondemand',
          ['Amazon DynamoDB on-demand offers a truly serverless database experience that automatically scales to accommodate the most demanding workloads without capacity planning.']),
      ],
    },
    {
      id: '3.3-K4',
      concepts: [
        b('DynamoDB provisioned mode uses capacity units. For an item up to 4 KB, one read capacity unit (RCU) represents one strongly consistent read per second, or two eventually consistent reads per second; a write capacity unit (WCU) represents one write per second for an item up to 1 KB. You can modify them later or enable DynamoDB auto scaling.',
          'dynamodb-provisioned',
          ['For an item up to 4 KB, one read capacity unit (RCU) represents one strongly consistent read operation per second, or two eventually consistent read operations per second.',
           'A write capacity unit (WCU) represents one write per second for an item up to 1 KB.',
           'You can modify these settings later, if needed, or enable DynamoDB auto scaling to modify them automatically.'],
          { allow: ['two'] }),
        b('DynamoDB on-demand mode needs no capacity planning: it eliminates capacity management and monitoring and scales automatically, with pay-per-request pricing so there is no idle capacity to pay for.',
          'dynamodb-ondemand',
          ['On-demand simplifies the setup process, eliminates capacity management and monitoring, and provides fast, automatic scaling.',
           'With pay-per-request pricing, you don’t have to worry about idle capacity because you only pay for the throughput you actually use.']),
        b('For RDS, the DB instance class determines computation and memory capacity, and consists of a class type and a size (db.r6g is a memory-optimised class type; db.r6g.2xlarge is a class within it). Class types include general-purpose, memory-optimized, compute-optimized, burstable-performance and optimized reads.',
          ['rds-instance-class', 'rds-instance-class-types'],
          ['rds-instance-class|The DB instance class determines the computation and memory capacity of an Amazon RDS DB instance.',
           'rds-instance-class|A DB instance class consists of both the DB instance class type and the size.',
           'rds-instance-class-types|Amazon RDS supports DB instance classes for the following use cases: General-purpose Memory-optimized Compute-optimized Burstable-performance Optimized Reads']),
        b('RDS storage comes in Provisioned IOPS SSD, designed for I/O-intensive database workloads that need low I/O latency and consistent throughput and best suited to production, and General Purpose SSD, cost-effective for a broad range of workloads on medium-sized instances and best suited to development and testing.',
          'rds-storage',
          ['Provisioned IOPS storage is designed to meet the needs of I/O-intensive workloads, particularly database workloads, that require low I/O latency and consistent I/O throughput.',
           'Provisioned IOPS storage is best suited for production environments.',
           'General Purpose SSD volumes offer cost-effective storage that is ideal for a broad range of workloads running on medium-sized DB instances.',
           'General Purpose storage is best suited for development and testing environments.']),
        b('RDS magnetic storage is deprecated: AWS states you can no longer create new DB instances with it, existing magnetic volumes were migrated to gp3, and from July 1, 2026 you can no longer restore a snapshot to magnetic storage. Choose General Purpose SSD or Provisioned IOPS SSD.',
          'rds-storage',
          ['Magnetic (deprecated) – Magnetic storage is deprecated and is no longer offered for new DB instances.',
           'Starting July 1, 2026, you can no longer restore a snapshot to magnetic storage.',
           'Use General Purpose SSD or Provisioned IOPS SSD for any new storage needs.'],
          { status: 'deprecated' }),
      ],
      services: ['Amazon RDS', 'Amazon DynamoDB', 'Amazon Aurora'],
      design: [
        b('Cue: steady, predictable DynamoDB traffic → provisioned capacity with auto scaling; spiky or unknown traffic → on-demand; production OLTP database that is I/O-bound → Provisioned IOPS storage; memory-bound → memory-optimised instance class.',
          ['dynamodb-provisioned', 'rds-storage'],
          ['dynamodb-provisioned|You can modify these settings later, if needed, or enable DynamoDB auto scaling to modify them automatically.',
           'rds-storage|Provisioned IOPS storage is best suited for production environments.']),
      ],
    },
    {
      id: '3.3-K5',
      concepts: [
        b('Each client connection costs the database resources. Amazon RDS Proxy pools and shares database connections: the proxy enables applications to open many client connections while it manages a smaller number of long-lived connections to the DB instance, which can also reduce CPU overhead for establishing connections.',
          'rds-proxy-planning',
          ['The proxy enables applications to open many client connections, while the proxy manages a smaller number of long-lived connections to the DB instance .',
           'It can also help reduce the CPU overhead for establishing connections.']),
        b('RDS Proxy makes applications more resilient to database failures by connecting to a standby instance while preserving application connections, handles unpredictable surges in database traffic, and can enforce IAM authentication, using IAM database authentication or credentials from Secrets Manager.',
          'rds-proxy',
          ['RDS Proxy makes applications more resilient to database failures by automatically connecting to a standby DB instance while preserving application connections.',
           'Using RDS Proxy, you can handle unpredictable surges in database traffic.',
           'By using RDS Proxy, you can enforce AWS Identity and Access Management (IAM) authentication for clients connecting to the proxy, and the proxy can connect to databases using either IAM database authentication or credentials stored in AWS Secrets Manager.']),
        b('A database that reports "too many connections" is a good candidate for a proxy, and so are AWS Lambda functions. (Single-Point Watch covers the resilience angle.)',
          'rds-proxy-planning',
          ['Any DB instance that encounters "too many connections" errors is a good candidate for associating with a proxy.',
           'AWS Lambda functions can also be good candidates for using a proxy.']),
      ],
      services: ['Amazon RDS', 'AWS Lambda'],
      design: [
        b('Cue: connection exhaustion from Lambda or many app servers → RDS Proxy; the application cannot be changed apart from its endpoint → RDS Proxy sits between the app and the database.',
          'rds-proxy-planning',
          ['AWS Lambda functions can also be good candidates for using a proxy.']),
      ],
    },
    {
      id: '3.3-S2',
      concepts: [
        b('A database architecture combines the choices above: engine and type (Database Registry), capacity (instance class, storage, capacity units), scale-out for reads (replicas, cache), connection management (proxy) and resilience (Multi-AZ). Design from the stated access pattern and the bottleneck, then add one component per problem.',
          'database-decision',
          ['Performance - Consider whether your database will need to support a high concurrency of transactions (10,000 or more), and whether it needs to be deployed in multiple geographic regions.']),
        b('The database decision guide frames performance questions this way: whether the database must support a high concurrency of transactions and whether it needs to be deployed in multiple geographic Regions. Aurora is suggested for less predictable query patterns, and in-memory caching alongside the database for microsecond reads.',
          'database-decision',
          ['Amazon Aurora Relational Use when you\'re migrating or modernizing an on-premises relational workload, or if your workload has less predictable query patterns.',
           'If your workload requires extremely high read performance with a response time measured in microseconds (rather than single-digit milliseconds), you might want to consider using in- memory caching solutions such as Amazon ElastiCache alongside your database, or a fully durable, persistent in-memory database such as Amazon MemoryDB.']),
      ],
      services: ['Amazon RDS', 'Amazon DynamoDB', 'Amazon Aurora'],
      design: [
        b('Build the answer step by step: pick the database type, size it for the bottleneck (instance class and storage, or capacity mode), add replicas or a cache for reads, a proxy for connections, and Multi-AZ for availability.',
          ['rds-instance-class', 'rds-proxy'],
          ['rds-instance-class|The DB instance class determines the computation and memory capacity of an Amazon RDS DB instance.',
           'rds-proxy|By using Amazon RDS Proxy, you can allow your applications to pool and share database connections to improve their ability to scale.']),
      ],
    },
  ],
  cues: [
    cue('DynamoDB traffic is unpredictable or spiky, no capacity planning wanted', 'DynamoDB on-demand capacity mode',
      b('On-demand mode scales automatically without capacity planning.', 'dynamodb-ondemand',
        ['Amazon DynamoDB on-demand offers a truly serverless database experience that automatically scales to accommodate the most demanding workloads without capacity planning.'])),
    cue('predictable DynamoDB traffic, set read/write capacity and adjust automatically', 'Provisioned capacity with DynamoDB auto scaling',
      b('Provisioned mode uses capacity units and can use auto scaling.', 'dynamodb-provisioned',
        ['You can modify these settings later, if needed, or enable DynamoDB auto scaling to modify them automatically.'])),
    cue('I/O-intensive production database needing low latency and consistent throughput', 'RDS Provisioned IOPS SSD storage',
      b('Provisioned IOPS storage is designed for I/O-intensive database workloads.', 'rds-storage',
        ['Provisioned IOPS storage is designed to meet the needs of I/O-intensive workloads, particularly database workloads, that require low I/O latency and consistent I/O throughput.'])),
    cue('development and test database, cost-effective storage', 'RDS General Purpose SSD storage',
      b('General Purpose storage is best suited for development and testing environments.', 'rds-storage',
        ['General Purpose storage is best suited for development and testing environments.'])),
    cue('too many database connections', 'Amazon RDS Proxy',
      b('Any instance that encounters "too many connections" errors is a good candidate for a proxy.', 'rds-proxy-planning',
        ['Any DB instance that encounters "too many connections" errors is a good candidate for associating with a proxy.'])),
    cue('memory-bound database', 'Memory-optimized RDS DB instance class',
      b('Memory-optimized is one of the RDS DB instance class types.', 'rds-instance-class-types',
        ['Amazon RDS supports DB instance classes for the following use cases: General-purpose Memory-optimized Compute-optimized Burstable-performance Optimized Reads'])),
  ],
  examples: [],
  confuse: [],
};

export default notes;
