import type { BuildingNotes } from '../../../src/content/types.ts';
import { b, cue } from '../../helpers.ts';

const notes: BuildingNotes = {
  building: 'turbine-hall',
  overview: [
    b('Scaling for performance is two questions: which metric tells you more capacity is needed, and which kind of scaling policy acts on it. Edge services answer a third question, which is whether the work can move closer to the user so it never reaches your Region at all.',
      ['asg-target-tracking', 'cloudfront-what-is'],
      ['asg-target-tracking|With target tracking, you select a metric and a target value to represent the ideal average utilization or throughput level for your application.',
       'cloudfront-what-is|CloudFront delivers your content through a worldwide network of data centers called edge locations.']),
  ],
  bullets: [
    {
      id: '3.2-K2',
      concepts: [
        b('AWS global infrastructure puts content and compute near users. CloudFront delivers content through a worldwide network of edge locations and routes each request to the edge location with the lowest latency; content already cached there is delivered immediately.',
          'cloudfront-what-is',
          ['CloudFront delivers your content through a worldwide network of data centers called edge locations.',
           'When a user requests content that you\'re serving with CloudFront, the request is routed to the edge location that provides the lowest latency (time delay), so that content is delivered with the best possible performance.']),
        b('Code can run at the edge too. CloudFront Functions are lightweight JavaScript functions for high-scale, latency-sensitive CDN customisations with submillisecond startup. Lambda@Edge is an extension of AWS Lambda for complex functions and full application logic closer to your viewers.',
          'cf-edge-functions',
          ['You can write lightweight functions in JavaScript for high-scale, latency-sensitive CDN customizations.',
           'The CloudFront Functions runtime environment offers submillisecond startup times, scales immediately to handle millions of requests per second, and is highly secure.',
           'Lambda@Edge is an extension of AWS Lambda that offers powerful and flexible computing for complex functions and full application logic closer to your viewers']),
        b('Distributing across Availability Zones and Regions is the other half of distributed computing: spread compute across Availability Zones for fault tolerance and use Regions close to users for latency (Island Charts covers Route 53 routing across zones and Regions; Charter Hall covers the Region and Availability Zone model).',
          'waf-multi-location',
          ['Distribute workload data and resources across multiple Availability Zones or, where necessary, across AWS Regions.']),
      ],
      services: ['Amazon CloudFront'],
      design: [
        b('Cue: personalise, redirect or rewrite requests with very low latency at scale → CloudFront Functions; heavier logic at the edge → Lambda@Edge; static and dynamic content for global users → CloudFront.',
          'cf-edge-functions',
          ['You can write lightweight functions in JavaScript for high-scale, latency-sensitive CDN customizations.']),
      ],
    },
    {
      id: '3.2-K4',
      concepts: [
        b('Amazon EC2 Auto Scaling keeps the right number of instances for the load, and you can scale in several ways: manual, scheduled, dynamic and predictive scaling. (The scheduled, predictive and target tracking policies are explained in Scaling Floodgate.)',
          ['asg-what-is', 'asg-target-tracking', 'asg-scheduled', 'asg-predictive'],
          ['asg-what-is|Amazon EC2 Auto Scaling helps you ensure that you have the correct number of Amazon EC2 instances available to handle the load for your application.',
           'asg-target-tracking|A target tracking scaling policy automatically scales the capacity of your Auto Scaling group based on a target metric value.',
           'asg-scheduled|With scheduled scaling, you can set up automatic scaling for your application based on predictable load changes.',
           'asg-predictive|Predictive scaling works by analyzing historical load data to detect daily or weekly patterns in traffic flows.']),
        b('Application Auto Scaling does the same for resources of individual AWS services beyond EC2, such as DynamoDB tables and global secondary indexes, Aurora replicas, Amazon ECS services, ElastiCache, Amazon EMR clusters, Lambda provisioned concurrency, Spot Fleet requests and custom resources.',
          'appas-what-is',
          ['Application Auto Scaling is a web service for developers and system administrators who need a solution for automatically scaling their scalable resources for individual AWS services beyond Amazon EC2 Auto Scaling.',
           'Aurora replicas Amazon Comprehend document classification and entity recognizer endpoints DynamoDB tables and global secondary indexes Amazon ECS services',
           'ElastiCache replication groups (Redis OSS and Valkey) and Memcached clusters Amazon EMR clusters Amazon Keyspaces (for Apache Cassandra) tables Lambda function provisioned concurrency',
           'Spot Fleet requests Pool of Amazon WorkSpaces Custom resources provided by your own applications or services.']),
        b('AWS documents how to migrate from scaling plans to EC2 Auto Scaling and Application Auto Scaling scaling policies.',
          'scaling-plan-migrate',
          ['You can migrate from a scaling plan to Amazon EC2 Auto Scaling and Application Auto Scaling scaling policies.']),
      ],
      services: ['Amazon EC2 Auto Scaling', 'AWS Auto Scaling'],
      design: [
        b('Cue: scale a DynamoDB table\'s capacity or an ECS service automatically → Application Auto Scaling; scale EC2 instances → EC2 Auto Scaling.',
          'appas-what-is',
          ['Amazon ECS services ElastiCache replication groups (Redis OSS and Valkey) and Memcached clusters Amazon EMR clusters']),
      ],
    },
    {
      id: '3.2-S2',
      concepts: [
        b('Target tracking policies use predefined metrics or custom metrics. The predefined metrics are the group\'s average CPU utilisation (ASGAverageCPUUtilization), average network bytes in and out, and Application Load Balancer request count per target (ALBRequestCountPerTarget). Custom metrics allow scaling on other CloudWatch metrics, including high-resolution metrics.',
          'asg-target-tracking',
          ['You can create target tracking scaling policies with either predefined metrics or custom metrics.',
           'ASGAverageCPUUtilization—Average CPU utilization of the Auto Scaling group.',
           'ALBRequestCountPerTarget—Average Application Load Balancer request count per target for your Auto Scaling group.',
           'Custom metrics allow you to scale on other available CloudWatch metrics including high-resolution metrics that are published at finer intervals in the order of a few seconds.']),
        b('Step scaling and simple scaling policies scale the group in predefined increments based on CloudWatch alarms: you define separate policies for scaling out and scaling in when an alarm threshold is breached.',
          'asg-step',
          ['Step scaling and simple scaling policies scale the capacity of your Auto Scaling group in predefined increments based on CloudWatch alarms.',
           'You can define separate scaling policies to handle scaling out (increasing capacity) and scaling in (decreasing capacity) when an alarm threshold is breached.']),
        b('Pick a metric that tracks the real bottleneck. The predefined metrics include average CPU utilisation and Application Load Balancer request count per target, and custom metrics let you scale on other CloudWatch metrics. A queue-based worker fleet scales on a custom backlog per instance metric (see Express Rail Hub). You can use multiple target tracking policies together, provided that each uses a different metric.',
          ['asg-target-tracking', 'asg-sqs'],
          ['asg-target-tracking|To help optimize scaling performance, you can use multiple target tracking scaling policies together, provided that each of them uses a different metric.',
           'asg-target-tracking|ASGAverageCPUUtilization—Average CPU utilization of the Auto Scaling group.',
           'asg-target-tracking|ALBRequestCountPerTarget—Average Application Load Balancer request count per target for your Auto Scaling group.',
           'asg-sqs|The solution is to use a backlog per instance metric with the target value being the acceptable backlog per instance to maintain.']),
      ],
      services: ['Amazon EC2 Auto Scaling', 'Amazon CloudWatch'],
      design: [
        b('Cue: "keep average CPU at a target value" → target tracking on CPU; "add more instances the further a metric exceeds its threshold" → step scaling; "keep requests per instance steady behind an ALB" → target tracking on ALBRequestCountPerTarget.',
          ['asg-target-tracking', 'asg-step'],
          ['asg-target-tracking|ALBRequestCountPerTarget—Average Application Load Balancer request count per target for your Auto Scaling group.',
           'asg-step|You can define separate scaling policies to handle scaling out (increasing capacity) and scaling in (decreasing capacity) when an alarm threshold is breached.']),
      ],
    },
  ],
  cues: [
    cue('maintain average CPU utilisation at a target value', 'Target tracking scaling policy (ASGAverageCPUUtilization)',
      b('ASGAverageCPUUtilization is the average CPU utilisation of the Auto Scaling group.', 'asg-target-tracking',
        ['ASGAverageCPUUtilization—Average CPU utilization of the Auto Scaling group.'])),
    cue('scale based on requests per instance behind a load balancer', 'Target tracking on ALBRequestCountPerTarget',
      b('ALBRequestCountPerTarget is the average ALB request count per target for the group.', 'asg-target-tracking',
        ['ALBRequestCountPerTarget—Average Application Load Balancer request count per target for your Auto Scaling group.'])),
    cue('add capacity in steps depending on how far a CloudWatch alarm is breached', 'Step scaling policy',
      b('Step scaling scales in predefined increments based on CloudWatch alarms.', 'asg-step',
        ['Step scaling and simple scaling policies scale the capacity of your Auto Scaling group in predefined increments based on CloudWatch alarms.'])),
    cue('automatically scale DynamoDB capacity, ECS services or Aurora replicas', 'Application Auto Scaling',
      b('Application Auto Scaling scales resources for individual AWS services beyond EC2.', 'appas-what-is',
        ['Application Auto Scaling is a web service for developers and system administrators who need a solution for automatically scaling their scalable resources for individual AWS services beyond Amazon EC2 Auto Scaling.'])),
    cue('lightweight request rewriting at the CDN edge with submillisecond startup', 'CloudFront Functions',
      b('CloudFront Functions have submillisecond startup times and scale immediately to millions of requests per second.', 'cf-edge-functions',
        ['The CloudFront Functions runtime environment offers submillisecond startup times, scales immediately to handle millions of requests per second, and is highly secure.'])),
    cue('complex application logic close to viewers', 'Lambda@Edge',
      b('Lambda@Edge offers computing for complex functions and full application logic closer to your viewers.', 'cf-edge-functions',
        ['Lambda@Edge is an extension of AWS Lambda that offers powerful and flexible computing for complex functions and full application logic closer to your viewers'])),
  ],
  examples: [],
  confuse: [],
  azure: [
    {
      concept: 'Azure Virtual Machine Scale Sets / App Service autoscaling',
      aws: 'Amazon EC2 Auto Scaling (and Application Auto Scaling)',
      mapping: b('Learn pairs AWS Auto Scaling with Azure Virtual Machine Scale Sets and App Service autoscaling. You can use Azure App Service to automatically scale App Service applications.',
        ['learn-compute', 'asg-what-is'],
        ['learn-compute|AWS service Azure service Description AWS Auto Scaling Azure Virtual Machine Scale Sets, Azure App Service autoscaling In Azure, you can use virtual machine scale sets to deploy and manage identical sets of VMs.',
         'learn-compute|You can use Azure App Service to automatically scale Azure App Service applications.',
         'asg-what-is|You create collections of EC2 instances, called Auto Scaling groups.']),
      breaks: b('On AWS the scaling service you need depends on the resource: EC2 Auto Scaling groups for instances, and Application Auto Scaling for resources such as DynamoDB tables, ECS services and Aurora replicas.',
        ['appas-what-is', 'learn-compute'],
        ['appas-what-is|Application Auto Scaling is a web service for developers and system administrators who need a solution for automatically scaling their scalable resources for individual AWS services beyond Amazon EC2 Auto Scaling.',
         'learn-compute|You can use Azure App Service to automatically scale Azure App Service applications.']),
    },
    {
      concept: 'Azure Monitor',
      aws: 'Amazon CloudWatch (as the source of scaling metrics)',
      mapping: b('Learn pairs CloudWatch and X-Ray with Azure Monitor, the telemetry service. On AWS, CloudWatch metrics and alarms are what drive scaling policies.',
        ['learn-hub', 'asg-step'],
        ['learn-hub|Azure Monitor is a comprehensive solution that you can use to collect, analyze, and act on telemetry from your cloud and on-premises environments.',
         'asg-step|Step scaling and simple scaling policies scale the capacity of your Auto Scaling group in predefined increments based on CloudWatch alarms.']),
      breaks: b('Learn pairs both Amazon CloudWatch and AWS X-Ray with the single service Azure Monitor. On AWS, CloudWatch metrics and alarms drive scaling policies: step scaling responds to a CloudWatch alarm, and target tracking holds a metric at a target value.',
        ['asg-target-tracking', 'asg-step', 'learn-hub'],
        ['asg-target-tracking|With target tracking, you select a metric and a target value to represent the ideal average utilization or throughput level for your application.',
         'asg-step|Step scaling and simple scaling policies scale the capacity of your Auto Scaling group in predefined increments based on CloudWatch alarms.',
         'learn-hub|DevOps and application monitoring AWS service Azure service Description Amazon CloudWatch and AWS X-Ray Azure Monitor']),
    },
  ],
};

export default notes;
